### ISSUE TITLE
rtpproxy: ice_candidate_priority_avp has missleading documentation

### ISSUE THREAD

**Issue by dunst0** [kamailio/kamailio#1003]
### Description

Dokumentation says:
```
If specified and if value of the avp value is not 0, rtpproxy_manage function adds ICE relay candidate attributes to sdp stream(s) containing ICE candidate attributes.
```
I would read it as, if the avp is set and the value is 0 no ICE relay candidate attributes, would be added. Instead a

#### Log Messages

```
Feb 20 15:21:45 <local0.err> voip-integration-cust1 kamailio[33439]: ERROR: rtpproxy [rtpproxy.c:2332]: force_rtp_proxy(): invalid ice candidate priority value 0
Feb 20 15:21:51 <local0.err> voip-integration-cust1 kamailio[33439]: ERROR: rtpproxy [rtpproxy.c:2332]: force_rtp_proxy(): invalid ice candidate priority value 0
```

### Possible Solutions

Accept 0 as a possible value or change documentation to give information that 0 is no valid input.

**Comment by miconda** [comment]
Quick look into the code and the valid values seems to be only 1 or 2. I guess the docs needs to be updated to reflect it. Maybe the dev that added the feature can comment more.

**Comment by dunst0** [comment]
The lines from 2323 to 2337 shows to me that internal the 0 is used for disabling the feature if no avp is set. https://github.com/kamailio/kamailio/blob/master/src/modules/rtpproxy/rtpproxy.c#L2323-L2337

So the check could be changed to:
`ice_candidate_priority_val.n < 0 || ice_candidate_priority_val.n > 2`

**Comment by miconda** [comment]
Using `git balme` I noticed that @juha-h worked on this feature, maybe he can comment on the accepted values by the avp.

**Comment by miconda** [comment]
Pushed a fix for it in latest branches.
