### ISSUE TITLE
Want to see active users/connected users to SIP server

### ISSUE THREAD

**Issue by silicus-mandar** [kamailio/kamailio#1008]
Hello,

I want to see active users SIP users for this purpose I checked the location table of kamailio database it does have active users entries however as per my observation there is 45 secs to 1 min delay before the entry actually added to this table i.e. suppose if I am registering the user through pjspi,jssip or any client I cannot see entry for that user in location table. I have to wait up-to 1 min to see the user in location table.
Is there any way we can Identify if user is online without delayed entry?

**Comment by miconda** [comment]
The issue tracker is used only to report bugs or track requests for new features.

For discussion about using kamailio or about kamailio.cfg, use the mailing list sr-users@lists.sip-router.org (https://www.kamailio.org/w/mailing-lists/). Also, see the readme of the usrloc module for this specific case, mainly understand the db_mode parameter.
