### ISSUE TITLE
Dialog: Core dump when using dlg_set_timeout

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#1011]
dlg_set_timeout("2419200", $var(entry), $var(id));

The both $var's contains strings. If I enclose them with "" there's no segfault, but the var's doesn't seem to be parsed by dlg_set_timeout either.

Doing this causes a seg fault when kamailio starts. Version 4.4.2

Will try to get a core dump, but not sure since this is a production system...

**Comment by miconda** [comment]
The values in the variables have to be numbers, not strings. Try to convert first with {s.int}, like:

```
$var(entry) = $(var(entry){s.int});
$var(id) = $(var(id){s.int});
dlg_set_timeout("2419200", "$var(entry)", "$var(id)");
```

**Comment by oej** [comment]
I did later - but we should not segfault for a bad config, right?

**Comment by miconda** [comment]
Sure, that needs to be caught. I tried to suggest a solution for now.

**Comment by oej** [comment]
Thank you! I still can't find the proper dialog, but that's another problem.

**Comment by miconda** [comment]
I pushed some commits with safety checks back to 4.4. If the issue is still there, reopen.
