### ISSUE TITLE
substr transformation error does not include config line number

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#1019]
I noticed that when there is an error in substr transformation, config file line number is not included in the error message:

Mar  4 22:40:24 lohi /usr/bin/sip-proxy[7801]: ERROR: pv [pv_trans.c:572]: tr_eval_string(): substr out of range

**Comment by miconda** [comment]
I pushed a patch to attempt to print the line for string transformation errors, as they are commonly used. However, this can be also accomplished for all error logs by setting config parameters:

```
log_prefix_mode=1
log_prefix="(cfg line: $cfg(line) "
```

**Comment by kamailio-sync** [comment]
Daniel-Constantin Mierla writes:

> I pushed a patch to attempt to print the line for string transformation errors, as they are commonly used. However, this can be also accomplished for all error logs by setting config parameters:
> 
> ```
> log_prefix_mode=1
> log_prefix="(cfg line: $cfg(line) "

OK, good to know, since also uri2dst2() errors don't show config line
number.

-- Juha
