### ISSUE TITLE
SCA: Inbound calls show SCA apperance until call is picked up

### ISSUE THREAD

**Issue by TheGrandWazoo** [kamailio/kamailio#103]
Using Kamailio 4.1.3 and now 4.2.3 I get a scenario that an incoming call from an Audiocodes Gateway (MP-114 or Mediant-1000) shows the call appearance on the Phones (Polycom VVX-310, VVX-410 and SPIP-650).  When a phone picks up the call, the appearances disappear from the other phones.
The other side of that, when one of the Polycom's calls out, the line appearance act normally.
Used the latest kamailio.cfg with the additions of the module based configs from the 4.2 wiki.

**Comment by TheGrandWazoo** [comment]
Upon further investigation and debugging, I have found that the SCA AoR must match the URI of the incoming request to send SCA updates.
I have NOT tried to rewrite this URI in kamailio, only changing the Tel->IP Routing on the Audiocodes gateway to match the SCA AoR required.

**Comment by miconda** [comment]
I understand that this was sorted out, closing here. Re-open if there are still issues to look at.
