### ISSUE TITLE
Makefile.defs: default locks review

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#1035]
Apparently the default locks are set to PTHREAD mutex, when the architecture is not handled explicitely. It should be reviewed and eventually switch to standard POSIX, they should work everywhere while PTHREAD are targeting threads and work only in few cases for processes.

**Comment by subnetsRU** [comment]
There is not enough add arch to Makefile.defs, because build aborts with error:
```
gmake[2]: Entering directory '/usr/ports/net/kamailio/work/kamailio-4.4.5'
CC (gcc) [kamailio]             nonsip_hooks.o
In file included from parser/../mem/../lock_ops.h:92:0,
                 from parser/../mem/shm.h:39,
                 from parser/../mem/shm_mem.h:34,
                 from parser/../ut.h:45,
                 from parser/../ip_addr.h:40,
                 from parser/msg_parser.h:37,
                 from nonsip_hooks.h:35,
                 from nonsip_hooks.c:31:
parser/../mem/../fastlock.h:112:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
parser/../mem/../fastlock.h: In function 'tsl':
parser/../mem/../fastlock.h:260:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
parser/../mem/../fastlock.h: In function 'get_lock':
parser/../mem/../fastlock.h:282:2: warning: implicit declaration of function 'membar_getlock' [-Wimplicit-function-declaration]
  membar_getlock();
  ^
parser/../mem/../fastlock.h: In function 'release_lock':
parser/../mem/../fastlock.h:379:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
gmake[2]: *** [Makefile.rules:97: nonsip_hooks.o] Error 1
gmake[2]: Leaving directory '/usr/ports/net/kamailio/work/kamailio-4.4.5'
```

**Comment by subnetsRU** [comment]
There isn't enough again your last modification Makefile.defs: it doesn't work with ports framework:
I've add info string to your "hack":
```
ifeq ($(ARCH), amd64)
    ARCH=x86_64
    $(info switch target architecture from amd64 to <$(ARCH)>)
endif
```
and I've got:

`switch target architecture from amd64 to <amd64>`

I can't explain it because I have not enough expirience and I can't decide is this issue to freebsd ports framework or to kamailio...

Maybe Kurt (pi@freebsd.org) or somebody more free then him can help us?

**Comment by subnetsRU** [comment]
Yes, now arch changed properly. Thanks!

**Comment by miconda** [comment]
Very likely the ports system set the ARCH variable in environment or command line for building kamailio, that's why a simple assignment didn't work. Also, the Makefile should have done the amd64=>x86_64 even without my changes if the ARCH was not enforced from outside.

**Comment by opsec** [comment]
5.0.1 hit the FreeBSD ports tree a few minutes ago and was extensivly tested by Alexey Panfilov. It looks like we could solve the problem.

**Comment by miconda** [comment]
Closing, with the good results from way back of 5.0.1
