### ISSUE TITLE
Problem with topos together with track_cseq_updates

### ISSUE THREAD

**Issue by lamSteven** [kamailio/kamailio#1038]
### Description

When using the dialog track_cseq_updates feature (to increase the cseq for calls that are authenticated using the uac uac_auth) together with topos, it seems like a reply is not handled by topos.

#### Log Messages

I have a 2219 line debug log demonstrating this, i can supply this on request.

**Comment by miconda** [comment]
Attach the logs file here or make it available on some web site/pastebin -- they are useful to investigate.

Also, can you grab ngrep output for such situation (all sip messages passing through the server: `ngrep -d any -qt -W byline port 5060`).

**Comment by lamSteven** [comment]
Thank you for your reply, i have attached somewhat anonymised logs.
If you need anything else, let me know!

[topos-track_cseq_updates.txt](https://github.com/kamailio/kamailio/files/853241/topos-track_cseq_updates.txt)
[topos-track_cseq_updates-outgoing-sip.txt](https://github.com/kamailio/kamailio/files/853242/topos-track_cseq_updates-outgoing-sip.txt)

**Comment by miconda** [comment]
What version of kamailio are you using (get the output of `kamailio -v`)?

**Comment by lamSteven** [comment]
version: kamailio 4.4.5 (x86_64/linux) 
From the "http://deb.kamailio.org/kamailio44 jessie  main" repository.

**Comment by miconda** [comment]
I think I found a lead to the issue, need a bit of time to push the fix. Would you be able to test with master branch or version 5.0? There were more changes to topos and backporting them to 4.4 might not be straightforward.

**Comment by lamSteven** [comment]
Sure, no problem!
I have a installation to test this on. Here i tested kamailio 5.0.0 with the same result.
If you want i can also give you ssh access so you can see what happens for yourself...

**Comment by miconda** [comment]
Can you try changing the order you load dialog and topos modules and test again? It may be a quick fix after looking a bit at the code -- even if working, I am planning a more consistent fix.

**Comment by lamSteven** [comment]
I already gave this a try ;-)
It doesn't make any difference if i load topos.so before or after the dialog.so and uac.so modules

**Comment by miconda** [comment]
Hmm, can you provide log messages with debug=3 when topos is loaded before dialog module?

**Comment by miconda** [comment]
Just re-pinging in case you missed my previous comment. It will help troubleshooting as the issue seems the missing Via headers which should be added by topos callbacks when receiving the sip response.

**Comment by lamSteven** [comment]
I'm sorry for the delay!

Attached you'll find two full debug logs: one with topos loaded before dialog, one with topos loaded after dialog.

[topos_before_dialog.txt](https://github.com/kamailio/kamailio/files/901938/topos_before_dialog.txt)
[topos_after_dialog.txt](https://github.com/kamailio/kamailio/files/901939/topos_after_dialog.txt)

**Comment by miconda** [comment]
Closing - topos got a lot of fixes and new code, if there is still an issue, open a new one and attach the logs using current master branch.

**Comment by skrusty** [comment]
Is this fixed in 4 branch? (4.7 for example) or just 5.

**Comment by henningw** [comment]
I was not able to identify a dedicated fix with this issue. The best would be if you try to reproduce it with the newest release in the 5.1 branch or (even better) with current master.
