### ISSUE TITLE
 ERROR: cnxcc  terminate_call(): Error executing dlg_end_dlg command. Return code was [404]

### ISSUE THREAD

**Issue by dipenpatel235** [kamailio/kamailio#1051]
#### Log Messages

```
terminate_call(): Error executing dlg_end_dlg command. Return code was [404]
Apr  1 06:49:56 sip /usr/sbin/kamailio[1316]: ALERT: cnxcc [cnxcc_check.c:81]: check_calls_by_money(): [S2N5rn7nlu] call has exhausted its credit. Breaking the loop
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
 kamctl -v
/usr/sbin/kamctl 4.2.0

```

* **Operating System**:

```
Centos 6 64bit
```

**Comment by miconda** [comment]
Is this happening often? Does it happen to have the sip traffic (pcap) for such case?

**Comment by dipenpatel235** [comment]
Is this happening often?
 - yes never terminate call on exceed balance. so that why balance is going to negative?


error log

Apr  7 02:41:15 newsip /usr/local/sbin/kamailio[28567]: ERROR: cnxcc [cnxcc_mod.c:734]: __setup_billing(): Call [Cl11aQtI3l] not found
Apr  7 02:41:15 newsip /usr/local/sbin/kamailio[28567]: INFO: <script>: Setting credit 0.01 for user 919999999999
Apr  7 02:41:15 newsip /usr/local/sbin/kamailio[28567]: INFO: <script>: Setting up money based credit control rate=0.000271667
Apr  7 02:41:25 newsip /usr/local/sbin/kamailio[28534]: ERROR: <script>: dialog start:Cl11aQtI3l:7130:20332
Apr  7 02:41:26 newsip /usr/local/sbin/kamailio[28556]: ALERT: cnxcc [cnxcc_check.c:76]: check_calls_by_money(): [Cl11aQtI3l] call has exhausted its credit. Breaking the loop
Apr  7 02:41:26 newsip /usr/local/sbin/kamailio[28556]: ERROR: cnxcc [cnxcc_mod.c:1089]: terminate_call(): Error executing dlg_end_dlg command. Return code was [404]
Apr  7 02:42:22 newsip /usr/local/sbin/kamailio[28569]: ERROR: <core> [tcp_read.c:292]: tcp_read_data(): error reading: Connection reset by peer (104) ([49.34.1.126]:48004 ->
Apr  7 02:42:22 newsip /usr/local/sbin/kamailio[28569]: ERROR: <core> [tcp_read.c:293]: tcp_read_data(): -> [163.172.89.240]:443)
Apr  7 02:42:22 newsip /usr/local/sbin/kamailio[28569]: ERROR: <core> [tcp_read.c:1321]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f42f6a89628 r: 0x7f42f6a896a8
Apr  7 02:43:50 newsip /usr/local/sbin/kamailio[28571]: ERROR: cnxcc [cnxcc_mod.c:584]: __stop_billing(): Call [Cl11aQtI3l] not found
Apr  7 02:43:50 newsip /usr/local/sbin/kamailio[28571]: ERROR: <script>: RTP-stats:60 7654 1642 9296 0
Apr  7 02:47:29 newsip /usr/local/sbin/kamailio[28572]: ERROR: <core> [tcp_read.c:292]: tcp_read_data(): error reading: Connection reset by peer (104) ([49.34.1.126]:48007 ->
Apr  7 02:47:29 newsip /usr/local/sbin/kamailio[28572]: ERROR: <core> [tcp_read.c:293]: tcp_read_data(): -> [163.172.89.240]:443)
Apr  7 02:47:29 newsip /usr/local/sbin/kamailio[28572]: ERROR: <core> [tcp_read.c:1321]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f42f6a89628 r: 0x7f42f6a896a8

**Comment by Pepelux** [comment]
I have the same problem with Kamailio 4.4.6

**Comment by miconda** [comment]
Closing this one because the code was updated to use internal dialog API to end the call instead of building the old-style MI command and executing it. The code is now different. If still an issue with latest version, open a new issue with the relevant details and logs for it.
