### ISSUE TITLE
sipcapture: destination_ip is truncated when its length is 15 (xxx.xxx.xxx.xxx) 

### ISSUE THREAD

**Issue by marianojm** [kamailio/kamailio#1058]
For example when ip is "200.108.217.174", destination_ip is stored in sip_capture_call_20170405 as "0.108.217.174"
(testing module sipcapture in kamailio 4.4.0)

here it is: "full sql code sended to mysql in storing", (Captured with tcpdump at port 3306)

insert into `sip_capture_rest_20170405` (`date`,`micro_ts`,`method`,`reply_reason`,`ruri`,`ruri_user`,`from_user`,`from_tag`,`to_user`,`to_tag`,`pid_user`,`contact_user`,`auth_user`,`callid`,`callid_aleg`,`via_1`,`via_1_branch`,`cseq`,`reason`,`content_type`,`auth`,`user_agent`,`source_ip`,`source_port`,`destination_ip`,`destination_port`,`contact_ip`,`contact_port`,`originator_ip`,`originator_port`,`proto`,`family`,`rtp_stat`,`type`,`node`,`correlation_id`,`from_domain`,`to_domain`,`ruri_domain`,`msg` ) values ('2017-04-05 12:17:27',1491394647138116,'NOTIFY','','sip:vhcau2pu@200.108.217.174:49507;transport=ws','vhcau2pu','1002','Hg4cF3a42j4rQ','1002','','','mod_sofia','','ac8031c3-949c-1235-2d9c-0655eb53760b','','SIP/2.0/WSS 169.57.161.254;branch=z9hG4bK9b9b.7c3c72afaf2a4d99a510a2c40fbe419a.0','z9hG4bK9b9b.7c3c72afaf2a4d99a510a2c40fbe419a.0','105361259 NOTIFY','','application/simple-message-summary','','2600hz','169.57.161.254',5060,**'0.108.217.174'**,'49507,'169.57.161.252',11000,'',0,3,2,'',1,'homer01:1','ac8031c3-949c-1235-2d9c-0655eb53760b','ZeroUY.sp.xentric.co','ZeroUY.sp.xentric.co','200.108.217.174','NOTIFY sip:vhcau2pu@200.108.217.174:49507;transport=ws SIP/2.0\r\nVia: SIP/2.0/WSS 169.57.161.254;branch=z9hG4bK9b9b.7c3c72afaf2a4d99a510a2c40fbe419a.0\r\nVia: SIP/2.0/UDP 169.57.161.252:11000;received=169.57.161.252;rport=11000;branch=z9hG4bKXmF1Fv8y0D91B\r\nMax-Forwards: 50\r\nFrom: <sip:1002@ZeroUY.sp.xentric.co>;tag=Hg4cF3a42j4rQ\r\nTo: <sip:1002@ZeroUY.sp.xentric.co>\r\nCall-ID: ac8031c3-949c-1235-2d9c-0655eb53760b\r\nCSeq: 105361259 NOTIFY\r\nContact: <sip:mod_sofia@169.57.161.252:11000>\r\nUser-Agent: 2600hz\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE\r\nSupported: path, replaces\r\nEvent: message-summary\r\nAllow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer\r\nSubscription-State: terminated;reason=noresource\r\nContent-Type: application/simple-message-summary\r\nContent-Length: 98\r\n\r\nMessages-Waiting: no\r\nMessage-Account: sip:1002@ZeroUY.sp.xentric.co\r\nVoice-Message: 0/1 (0/0)\r\n\r\n')

**Comment by adubovikov** [comment]
@marianojm please don't open several tickets for the same issue in different projects.
I will close the ticket, please continue investigate it here: https://github.com/sipcapture/homer/issues/220
