### ISSUE TITLE
Incorrect contact in 183 and 200 ok when topos module used

### ISSUE THREAD

**Issue by sergey-vb** [kamailio/kamailio#1077]
**Description**

When using topos, Kamailio does not set correct contact in 183 progres and 200 OK.
But for INVITE and Bye contacts are correct.

**Troubleshooting**

When loaded topoh module all work as expected without any issue. 

**Reproduction**

Place a call from sip softphone behind NAT to PSTN GW or in opposite direction. You will have a call with 30 sec long because contact in 183 and 200 OK are incorrect. But when you get Bye from PSTN GW contact are correct.

**Additional Information**

version: kamailio 5.0.1 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 14:27:34 Apr  5 2017 with gcc 4.8.2
[wrong-contact-dump-with-topos.txt](https://github.com/kamailio/kamailio/files/932684/wrong-contact-dump-with-topos.txt)

**Comment by sergey-vb** [comment]
Seems I have fixed this with
#1081 

Can you look at it Daniel?

Dump with success call with many re-Invites - in attache.

Thank you.
[OK-contact-dump-with-topos.txt](https://github.com/kamailio/kamailio/files/942602/OK-contact-dump-with-topos.txt)

**Comment by miconda** [comment]
Thanks! I am going to backport the patch to branch 5.0.
