### ISSUE TITLE
Daemon not restated if process exited with not null code

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1085]
Details in attached log file.
[kamailio-fail.txt](https://github.com/kamailio/kamailio/files/949032/kamailio-fail.txt)

**Comment by sergey-safarov** [comment]
Hello @linuxmaniac 
Yes, I want say "non-zero exit code" or  "Unclean exit code"
Clean exit code is "0" or codes marked as "SuccessExitStatus"
Please see same link

> SuccessExitStatus=1 2 8 SIGKILL
> ensures that exit codes 1, 2, 8 and the termination signal SIGKILL are considered clean service terminations.

**Comment by miconda** [comment]
This can be fixed by packagers on their systemd scripts.
