### ISSUE TITLE
Installation broken because of commented out mpath in example config

### ISSUE THREAD

**Issue by SipSeb** [kamailio/kamailio#1096]
### Description

When installing Kamailio on a new system, Kamailio can't start because it doesn't know where to load the modules from. This is at least when installing from Debian packages.

#### Reproduction

Install Kamailio on a new system from the official Debian packages (v.5.0, v4.4 is unaffected). dpkg will fail in configure phase because the Kamailio config is invalid and thus it can't be started.

### Possible Solutions

After enabling the commented out mpath line in the example configuration file, the installation succeeds.

There is a pull request fixing the issue:
https://github.com/kamailio/kamailio/pull/1095

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.0.1 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 4.9.2
```

* **Operating System**:

```
Debian Jessie Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

**Comment by miconda** [comment]
What is the output of the command:

```
kamailio -I
```

**Comment by SipSeb** [comment]
This is the output of kamailio -I
```
Print out of kamailio internals
  Version: kamailio 5.0.1 (x86_64/linux)
  Default config: /etc/kamailio/kamailio.cfg
  Default paths to modules: /usr/lib64/kamailio/modules
  Compile flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
  MAX_RECV_BUFFER_SIZE=262144
  MAX_LISTEN=16
  MAX_URI_SIZE=1024
  BUF_SIZE=65535
  DEFAULT PKG_SIZE=8MB
  DEFAULT SHM_SIZE=64MB
  ADAPTIVE_WAIT_LOOPS=1024
  TCP poll methods: poll, epoll_lt, epoll_et, sigio_rt, select
  Source code revision ID: unknown
  Compiled with: gcc 4.9.2
  Compiled on:
Thank you for flying kamailio!
```

However, the the default configuration gets installed with these lines:
```
/* set paths to location of modules */
# mpath="/usr/lib/x86_64-linux-gnu/kamailio/modules/"
```

This is where the modules actually are located. 

How can I influence the path given by `kamailio -I`?

After your comment, I first thought there was a problem with our own packages built locally, but the problem is the same when installing from `http://deb.kamailio.org/kamailio50`.

**Comment by miconda** [comment]
Looking at `src/Makefile.defs`, the `LIBDIR` has to be set in the build command, like:

```
make LIBDIR=lib/x86_64-linux-gnu
```
Maybe there is a way to know in Debian specs what value to set here.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> Looking at `src/Makefile.defs`, the `LIBDIR` has to be set in the
> build command, like: 
> 
> ```
> make LIBDIR=lib/x86_64-linux-gnu
> ```
> Maybe there is a way to know in Debian specs what value to set here.

pkg-config command may help there.

-- juha

**Comment by linuxmaniac** [comment]
From https://kamailio.sipwise.com/view/kam5.0/job/kamailio50-binaries/architecture=amd64,distribution=jessie,label=slave/3/consoleText

```
/usr/bin/make install LIBDIR=lib/x86_64-linux-gnu group_include="kstandard"
```

**Comment by linuxmaniac** [comment]
@SipSeb please check tomorrow's deb from http://deb.kamailio.org/kamailio50-nightly/ or build it from source, It should be fixed

**Comment by miconda** [comment]
Thanks @linuxmaniac !

**Comment by linuxmaniac** [comment]
Thanks @SipSeb for the report
