### ISSUE TITLE
I_perform_user_authorization_request(): no int value param passed

### ISSUE THREAD

**Issue by riccardovarotto** [kamailio/kamailio#1099]
### Description

Using I-CSCF Kamailio module with 5.0.1 version we got the error:
"I_perform_user_authorization_request(): no int value param passed"

Same configuration file works well on 5.0.0 version

#### Debugging Data

 1(26715) ERROR: *** cfgtrace:request_route=[register] c=[/etc/KAMAILIO_ASTERISK_CFG/IMS_5/icscf/./kamailio.cfg] l=374 a=26 n=I_perform_user_authorization_request
 1(26715) ERROR: <core> [core/sr_module.c:1766]: get_int_fparam(): Unexpected param type: 1280329042
 1(26715) ERROR: ims_icscf [registration.c:78]: I_perform_user_authorization_request(): no int value param passed
 1(26715) ERROR: *** cfgtrace:request_route=[register] c=[/etc/KAMAILIO_ASTERISK_CFG/IMS_5/icscf/./kamailio.cfg] l=375 a=26 n=send_reply

[log_ko.gz](https://github.com/kamailio/kamailio/files/961675/log_ko.gz)

[kamailio.cfg.txt](https://github.com/kamailio/kamailio/files/961677/kamailio.cfg.txt)

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
This is about configuring kamailio, use sr-users@lists.kamailio.org mailing lists for such discussions.

The bug tracker here is to report bugs in the C code.

Look also at the docs for the function you report having problem with its parameters:

  * http://www.kamailio.org/docs/modules/5.0.x/src/modules/ims_icscf.html#idp49436212

**Comment by riccardovarotto** [comment]
Yes, but I think something wrong enter on C parsing code of the second parameter of the above configuration function.

**Comment by miconda** [comment]
There were no recent changes in that module in branch 5.0:

```
commit 78f0b44532b0a2a7a97068e0f68832dec6b1b5b2
Author: Victor Seva <linuxmaniac@torreviejawireless.org>
Date:   Mon Feb 13 15:29:35 2017 +0100

    ims_icscf: Rename module interface file #82

    (cherry picked from commit 149b76b99a6c6f89cd5e95d33b9d9ac11208fd3f)

commit 728c7e477634f30f251dee804ffa505c675bb2e4
Author: Victor Seva <linuxmaniac@torreviejawireless.org>
Date:   Mon Jan 16 09:58:41 2017 +0100

    ims_icscf: fix compiler warnings
...
```

@ngvoice may comment, but again it feels like a config issue.

**Comment by riccardovarotto** [comment]
The problem is not in that module as on log:

 1(26715) ERROR: <core> [core/sr_module.c:1766]: get_int_fparam(): Unexpected param type: 1280329042

**Comment by miconda** [comment]
`get_int_fparam()` is a helper function that didn't change probably for more than 5 years. The error is triggered by the module, when trying to use the helper function.

Show what you have in config at line 374

**Comment by kamailio-sync** [comment]
Hi,

It's fixed in trunk/Dev and should be cherry-picked for the 5.0 branch, too.

I can take care of that tomorrow.

Thanks,
Carsten

Am 27.04.2017 17:35 schrieb "Daniel-Constantin Mierla" <
notifications@github.com>:

**Comment by riccardovarotto** [comment]
Thank you

**Comment by ngvoice** [comment]
Fixed in Commit c270da3cd3200e7074fd7368f0899e679c38c5c2 for branch 5.0.

**Comment by riccardovarotto** [comment]
It works well!

Thank you

**Comment by uts09** [comment]
Getting same error in 4.4.7. Can you please share the patch file for 4.4.7?
