### ISSUE TITLE
Potential bug in kamailio-basic-kemi-python.py

### ISSUE THREAD

**Issue by verticelo** [kamailio/kamailio#1117]
In the file kamailio-basic-kemi-python.py:65 it reads

```
# handle requests within SIP dialogs
self.ksr_route_withindlg(msg);
```

I wonder if it shouldn't read:
```
# handle requests within SIP dialogs
if self.ksr_route_withindlg(msg) == -255:
    return 1

  # -- only initial requests (no To tag)
```

Seems like that is the intended behavior based on the native example script and the return codes from ksr_route_withindlg(). Kamailio will always keep processing everything below line 69 regardless of the outcome of ksr_route_withindlg(). It might run fine anyway, but the comment is misleading in that case.

I'm a beginner on Kamailio so any apologies if I misunderstood something here.

The KEMI module is really exciting and we are developing a new project with it. So far it works great!

**Comment by miconda** [comment]
Thanks for reporting, pushed a patch to fix it.
