### ISSUE TITLE
Parse error in config file with $msrp(msgid) pseudovariable

### ISSUE THREAD

**Issue by NGSegovia** [kamailio/kamailio#1122]
### Description

I got parse error in config file.
I am using MSRP module and if I try to use (to print a log) with `$msrp(msgid)` I get an error. According to the psudovariables documentation should work. 

#### Reproduction

Just use within an event_route[msrp:frame-in]  block $msrp(msgid).

#### Log Messages

```
0(9827) ERROR: msrp [msrp_vars.c:118]: pv_parse_msrp_name(): unknown PV msrp name msgid
 0(9827) ERROR: <core> [pvapi.c:877]: pv_parse_spec2(): pvar "msrp" has an invalid name param [msgid]
 0(9827) ERROR: <core> [pvapi.c:1032]: pv_parse_spec2(): wrong char [)/41] in [$msrp(msgid)] at [11 (5)]
 0(9827) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file route.cfg, line 649, column 40-51: Can't get from cache: $msrp(msgid)
ERROR: bad config file (1 errors)
```

### Additional Information

  * **Kamailio Version** -4.4.5

* **Operating System**:

```
Linux test 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Thanks, there was a missing break when parsing the name. Can you try with latest branch 4.4 or newer branches? Reopen if the issue is still there.
