### ISSUE TITLE
ERROR searching pvar "uac_req" in sample kamailio.cfg config file for PCSCF

### ISSUE THREAD

**Issue by vhuertas** [kamailio/kamailio#1123]
### Description

I have configured a kamailio as PCSCF taking the configuration sample files (kamailio.cfg and pcscf.cfg) in https://github.com/kamailio/kamailio/tree/master/misc/examples/pcscf

The version of kamailio installed is the 5.1.

When I perform "service pcscf start" the services doesn't restart giving a parsing error for a pseudo variable called $uac_req. The error is found in this section:

route[NATPING] {
	route(preload_pcscf);

	sht_iterator_start("nat_iterator", "natping");
	while(sht_iterator_next("nat_iterator")) {
		xlog("OPTIONS to $shtitval(nat_iterator) via $shtitkey(nat_iterator)...\n");
		$uac_req(method) = "OPTIONS";
		$uac_req(ruri) = $shtitval(nat_iterator);
		$uac_req(furi) = PCSCF_URL;
		$uac_req(turi) = $shtitval(nat_iterator);
		$uac_req(ouri) = $shtitkey(nat_iterator); 
		$uac_req(evroute) = 1;
		uac_req_send();	
	}
	sht_iterator_end("nat_iterator");
}

I have checked that I have only one "uac.so" file in /usr/lib64/kamailio/modules/ and the date of the file is April 15th. So I guess that the file is updated.
 
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

ERROR: <core> [core/pvapi.c:828]: pv_parse_spec2(): error searching pvar "uac_req" 0(2271) ERROR: <core> [core/pvapi.c:1032]: pv_parse_spec2(): wrong char [m/109] in [$uac_req(method)] at [9 (5)] 0(2271) CRITICAL: <core> [core/cfg.y:3414]: yyerror_at(): parse error in config file /etc/kamailio/pcscf/kamailio.cfg, line 906, column 3-18: Can't get from cache: $uac_req(method) ERROR: bad config file (1 errors)

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.1.0-dev2 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 4.7.2

* **Operating System**:

Debian 8

**Comment by miconda** [comment]
Be sure you have defined WITH_NATPING.

If you still have troubles, email to sr-users@lists.kamailio.org, because this is a config issue. This tracker is only for bugs in the code and racking features requests, not discussion on how to configure or use kamailio.

**Comment by leechul** [comment]
How about i don't want to use NATPING.
