### ISSUE TITLE
User-Agent header and Server header not sent in the requests/responses

### ISSUE THREAD

**Issue by logslie** [kamailio/kamailio#1126]
### Description

When configuring as a global configuration the following parameters:

user_agent_header="User-Agent: foobar-1.0.0"
server_header="Server: foobar-1.0.0"

I expected to have in every responses the Server header and in every requests the User-Agent header. But I'm only see the Server header in the first 100 response and the User Agent header is never sent in the responses.

#### Log Messages

I don't have any error message in the log.

#### SIP Traffic

- First response to an INVITE with Server header.
![responsewithserverheader](https://cloud.githubusercontent.com/assets/4872125/25940195/95b610ae-3635-11e7-9447-b74088dc8a48.png)

- First resquest without User-Agent header:
![requestwithoutuseragentheader](https://cloud.githubusercontent.com/assets/4872125/25940238/b79fd8b2-3635-11e7-8d7a-16aef011f9fa.png)

- Second response without Server header:
![responsewithoutserverheader](https://cloud.githubusercontent.com/assets/4872125/25940257/cdbebc26-3635-11e7-9c03-431385f23fba.png)

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio-4.4.5
```

* **Operating System**:

```
Linux test200 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Is there something that I'm doing wrong?

Thanks

**Comment by miconda** [comment]
Those headers are added by kamailio only when it is the origin of the request (adding user-agent) or the response (adding server). If kamailio is forwarding the request or response, it doesn't add any of these headers.

You can add them using append_hf(...) in the request_route{} or reply_route{}.

I am going to close this issue, if you need to seek further clarifications, use the sr-users@lists.kamailio.org for discussions.
