### ISSUE TITLE
KEMI Python exits when importing requests

### ISSUE THREAD

**Issue by verticelo** [kamailio/kamailio#1130]
Using the Python library "requests" makes all the worker processes quit.

In the KEMI file put:

`import requests`

The following errors will be thrown in the Kamailio log:

```
 0(2667) INFO: <core> [core/kemi.c:86]: sr_kemi_core_info(): [19:19:15.919278] ===== kamailio.child_init(0)
 0(2667) INFO: <core> [main.c:759]: handle_sigs(): terminating due to SIGCHLD
 1(2672) INFO: <core> [main.c:814]: sig_usr(): signal 15 received
```

Requests is a very common Python HTTP library.

Can be installed via (Debian):
apt-get install python-pip
pip install requests

**Comment by miconda** [comment]
Which version are you using? There was a patch recently pushed to master trying to address similar issues: 1c5e166001306a1a9d9d8412f0a54910093109cb

**Comment by verticelo** [comment]
Thanks for the quick reply. Running 5.0.1 but I will install latest from master and retest and report back.

**Comment by verticelo** [comment]
Yes, seems to be working now!

`0(9965) INFO: <core> [main.c:759]: handle_sigs(): SIGCHLD received, but no child has stopped, ignoring it`

Thank you!
