### ISSUE TITLE
KEMI Python: Possible bug in TM t_next_contacts

### ISSUE THREAD

**Issue by verticelo** [kamailio/kamailio#1131]
When using

`KSR.tm.t_next_contacts`

The following error is shown:

```
PYT {INVITE}:  5(11047) INFO: <core> [core/kemi.c:86]: sr_kemi_core_info(): [18:27:34.526536] Loading destination routes
PYT {INVITE}:  5(11047) ERROR: *** cfgtrace:request_route=[] c=[] l=0 a=26 n=append_branch
PYT {INVITE}:  5(11047) ERROR: *** cfgtrace:request_route=[] c=[] l=0 a=26 n=append_branch
PYT {INVITE}:  5(11047) INFO: <core> [core/kemi.c:86]: sr_kemi_core_info(): [18:27:34.692021] Test
PYT {INVITE}:  5(11047) ERROR: tm [t_fwd.c:1723]: t_forward_nonack(): no branches for forwarding
PYT {INVITE}:  5(11047) ERROR: sl [sl_funcs.c:362]: sl_reply_error(): stateless error reply used: I'm terribly sorry, server error occurred (1/SL)
PYT {INVITE}:  5(11047) INFO: <core> [core/receive.c:277]: receive_msg(): request-route executed in: 167884 usec
```

Replacing the line that doesn't work with:

`msg.call_function("t_next_contacts")`

makes the script run as expected. 

I'm running the master branch of Kamailio pulled yesterday.

**Comment by verticelo** [comment]
My bad, there is no bug here:

When using the line:

`KSR.tm.t_next_contacts()`

it works :) My apologies. So, a suggestion might be to throw some type of error on those kind of mistakes.

**Comment by miconda** [comment]
Good it was found -- I was just looking the code and the same function is used in both cases.

I am not sure what kind of error can be thrown in case of such config mistake. If you have suggestions, open a discussion on sr-users@lists.kamailio.org mailing list so other can comment.
