### ISSUE TITLE
Kamailio is not passing bye to client side.

### ISSUE THREAD

**Issue by rahmanafzal** [kamailio/kamailio#1145]
Dear,

kamailio running with rtp proxy not passing bye to UA side as calls disconnected from B- leg but still running at A-leg side client. attached trace for your reference.

Why kamailio not passing the bye to A side. Please guide !

Regards,
Rahman Afzal

[SIP Trace.txt](https://github.com/kamailio/kamailio/files/1047251/SIP.Trace.txt)

**Comment by linuxmaniac** [comment]
Start a discussion on sr-users@lists.kamailio.org so people can provide hints. This tracker is only for bugs in the code.
