### ISSUE TITLE
to tags generation

### ISSUE THREAD

**Issue by snen** [kamailio/kamailio#1164]
### Description
Not shure is this relevant issue.
according to rfc3261:

> When a tag is generated by a UA for insertion into a request or
>    response, it MUST be globally unique and cryptographically random
>    with at least 32 bits of randomness.

Kamailio has 16 instead and distribution is not good.
I look at tags for 419485 sip flows (different callid) and table below (top keys ordered by count): 
tag suffix; count for different flows with this suffix
ed54 6258
d118 5988
56ce 5923
a7a5 5220
de51 2150
82d8 1143
cf52 890
af92 740
7b5f 534
85f7 307
e553 163
7f7e 138
1d55 130
1afe 62
5a69 43
7caa 18
8474 18
9db2 18
11d3 18
f9ff 18
5420 17
dae6 17
908d 17
ede4 17
09ee 17
96be 17
25dc 17
af6d 16
2506 16
3da0 16
f161 16
1c29 16

#### SIP Traffic
To: <sip:039*101@host:5071>;tag=555d2c3eafafcba8ac92b676e91bb6ed.58eb

**Comment by miconda** [comment]
Probably those tag generation functions that are quite old need to be revised a bit. Anyone willing to propose an enhancement to it, is welcome to jump on board and discuss here/send a patch.

**Comment by henningw** [comment]
I implemented a improved version of the current to tag generation algorithm in git master by more or less doubling the output of the existing code and including the callid body as well. I think this should improve it considerable for now.

**Comment by henningw** [comment]
I implemented a similar improvement for uac requests from tm as well by doubling the output and also including some more data (request uri) in it. This should also help e.g. for outgoing REGISTER requests from uac module.

So the from-tag suffix is now as well 32 bits, the first half of the suffix stays the same as in the core part. If e.g. some other tools match to this suffixes, they should probably still continue to work.

I will look to it again in the next development cycle, as at least SHA1 should be used as a hash function for both prefix and suffix. But this will be a more risky change, so better do it later with more time for tests. I will create a new issue for this together with some other changes.

Close this one for now.
