### ISSUE TITLE
incorrect ACK BYE packets routing with topoh enabled on kamailio 5.0.2

### ISSUE THREAD

**Issue by slavrov** [kamailio/kamailio#1165]
### Description

After upgrading kamailio from 4.4.5 to 5.0.2 ACK/BYE packets are routed incorrectly. Instead of routing from KAMAILIO INT IP to SIP UAC #2 ACK/BYE packets are routed from KAMAILIO EXT IP to KAMAILIO INT IP.
I attached two diagrams. First is from kamailio 4.4.5 with correct routing. Second is from kamailio 5.0.2 with wrong routing.
One of improtant notice is when topoh module is disabled ACK/BYE packets are routed correctly on kamailio 5.0.2.
Also in kamailio 5.0.2  DURI and RURI of ACK/BYE packets are populated not by Contact value of OK packet from SIP UA #2 but Record-Route value from OK packet. In kamailio 4.4.5 DURI is not populated at all and RURI is correct one.

#### SIP Traffic

SIP trace diagram from kamailio 4.4.5: http://imgur.com/5J95spW
SIP trace diagram from kamailio 5.0.2: http://imgur.com/TDOGdgA

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 4.4.5 (x86_64/linux) f98162
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: f98162 
compiled on 03:47:31 Feb 27 2017 with gcc 4.8.5
```

* **Operating System**:

```
Red Hat Enterprise Linux Server release 7.3 (Maipo)
Linux 2.6.32-042stab113.21 #1 SMP Wed Mar 23 11:05:25 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Attach the pcap for 5.0.2 -- seeing the headers in all those sip messages are important to troubleshoot.

**Comment by slavrov** [comment]
I sent pcap to your email for privacy reason.

**Comment by miconda** [comment]
The issue was some safety checks introduced to detect the URI encoded with topoh, but in your case the device is not using exactly the same URI it receives in Contact header, but adds port 5060, making those tests to fail.

I pushed a patch to disable those checks by default. You have to try with the patch referenced above or use latest git. If still a problem, reopen this item.
