### ISSUE TITLE
Kamailio does not set the right advertised RR

### ISSUE THREAD

**Issue by verticelo** [kamailio/kamailio#1174]
Using latest master commit. Running on AWS EC2 with elastic IP.

If using advertised_address="ELASTICIP" the VIA headers etc get changed correctly but the record route header does not, it still uses the internal IP of the host.

If I add:
listen=udp:0.0.0.0:5060 advertise ELASTICIP:5060

The RR advertises the correct IP.

According to the documentation here:
https://www.kamailio.org/wiki/cookbooks/5.0.x/core#advertised_address

It should be enough with the advertised_address parameter. Hence, seems to be a problem with the advertised_address parameter.

**Comment by miconda** [comment]
Afaik, this config param was always only for Via headers. For Record-Route, there are some functions inside the rr module targeting this option.

Anyhow, I think `advertised_address` and `advertised_port` should be deprecated and removed, in favor of `advertise` option for `listen` parameter.

I updated the wiki to reflect that it applies only to Via and added note about doing advertise via listen parameter.
