### ISSUE TITLE
Hello, kamailio v4.1 would not start after installation. Throws the following error even when mysql is running:

### ISSUE THREAD

**Issue by uchepercynnoch** [kamailio/kamailio#1193]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by linuxmaniac** [comment]
use user mailing list for this. And provide useful information.
