### ISSUE TITLE
Incorret code example in pipelimit documentation

### ISSUE THREAD

**Issue by gostkov** [kamailio/kamailio#1201]
### Description

In the documentation documentation for module pipelimit https://www.kamailio.org/docs/modules/4.2.x/modules/ratelimit.html
has an error in example:

```# perform pipe match for authenticated user
$var(limit) = 20;
if (!pl_check("$au", "traildrop", "$var(limit)")) {
	pl_drop();
	exit;
}
```

If write algorithm "traildrop" in function pl_check, you every execution will get return code -2 and pipe not will be created.

### Possible Solutions

Change string "traildrop" on "TAILDROP"

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio 4.2.3
```

**Comment by miconda** [comment]
v4.2.x is out of maintenance, stable series maintained at this moment being 4.4.x and 5.0.x. I checked and recent versions have the example with correct value.

I also just pushed a patch to master branch to make the matching case insensitive.
