### ISSUE TITLE
Unable to capture the SIP DATA 

### ISSUE THREAD

**Issue by bharathg65** [kamailio/kamailio#1202]
Dear Team,
Any one pls help me , i have been struck with this more than 2 months , i have keep on changing the kamailio.cfg but nothing has worked .
Initially i had plan to user captagent but unfortunately i couldn't run in CentOS since its failing in init procedure , because document which is provided in github is only for other OS .

so planned to use kamailio as capture server .

When ever i tried to run sipgrep , its showing data running on my server .
And when i used command kamailio -c , i can see below interface is listening , but its not capturing any data and sending to mysql .

root@localhost kamailio]# kamailio -c
 0(6624) WARNING: <core> [ppcfg.c:221]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
Listening on
             udp: 172.16.5.158:9060
Aliases:
             udp: localhost.localdom:9060
             udp: localhost.localdomain:9060

And My sql is running fine without any issue .

Any one can pls audit my configuration and advise me .
because am New to Centos and homer .

Thanks in advance

**Comment by bharathg65** [comment]
kamailio

**Comment by bharathg65** [comment]
[kamailio-advanced .txt](https://github.com/kamailio/kamailio/files/1194203/kamailio-advanced.txt)
[kamailio-config.txt](https://github.com/kamailio/kamailio/files/1194204/kamailio-config.txt)
[kamailio-basic.txt](https://github.com/kamailio/kamailio/files/1194208/kamailio-basic.txt)

**Comment by bharathg65** [comment]
Pls help me

**Comment by miconda** [comment]
This tracker is used only for reporting bugs in the code or requests new features in the code.

To get assistance on using kamailio and issues related to kamailio.cfg, use the mailing list `sr-users@lists.kamailio.org`:

  - https://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-users
