### ISSUE TITLE
alias=forward.ng-voice.com doesn't work

### ISSUE THREAD

**Issue by ngvoice** [kamailio/kamailio#1207]
### Description

I am currently implementing a dynamic forwarding server in Kamailio. As a logic consequence, I wanted to name it "forward.ng-voice.com" and I added it as an Alias:

alias=forward.ng-voice.com

#### Reproduction

Add any Alias with the "forward" in it's domain-name (e.g. "ims.forward.ng-voice.com" fails too).

#### Log Messages

```
 0(20620) CRITICAL: <core> [core/cfg.y:3427]: yyerror_at(): parse error in config file forward.cfg, line 11, column 7-13: syntax error
 0(20620) CRITICAL: <core> [core/cfg.y:3427]: yyerror_at(): parse error in config file forward.cfg, line 11, column 7-13: hostname expected
 0(20620) CRITICAL: <core> [core/cfg.y:3430]: yyerror_at(): parse error in config file forward.cfg, line 11, column 14: 
```

### Possible Solutions

Use a different Domain-Name like "fwd" or "forwarder".

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.0-dev5 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2

```

* **Operating System**:

Debian 8

**Comment by miconda** [comment]
Try to enclose it in quotes and see if it works. I guess it matches a reserved keyword.

**Comment by SurendraPlivo** [comment]
i will try to reproduce it. but as i am checking the code on version: kamailio 5.1.0-dev5 (x86_64/linux)  there is nothing like matching keyword.will provide the fix for this also

**Comment by SurendraPlivo** [comment]
this error is reproduceable.
Aug  8 12:19:02 ip-172-31-11-83 kamailio: CRITICAL: <core> [core/cfg.y:3426]: yyerror_at(): parse error in config file /usr/local/etc/kamailio/kamailio.cfg, line 171, column 7-13: syntax error
Aug  8 12:19:02 ip-172-31-11-83 kamailio: CRITICAL: <core> [core/cfg.y:3426]: yyerror_at(): parse error in config file /usr/local/etc/kamailio/kamailio.cfg, line 171, column 7-13: hostname expected
Aug  8 12:19:02 ip-172-31-11-83 kamailio: CRITICAL: <core> [core/cfg.y:3429]: yyerror_at(): parse error in config file /usr/local/etc/kamailio/kamailio.cfg, line 171, column 14:

but use double quote that will help you.i checked it with double quote after that no error.

**Comment by ngvoice** [comment]
Sorry, my bad. The double quotes do the trick. Not an bug.
