### ISSUE TITLE
topos and dialog timeout conflict

### ISSUE THREAD

**Issue by dryvoip** [kamailio/kamailio#1216]
### Description

When topos is loaded and dialog is configured to timeout a call by sending BYE to each side, the Route: header is lost and one of the BYEs is not sent to the correct destination.

This problem does not exist when topos is not loaded.

#### Reproduction
```
modparam("dialog", "rr_param", "dv")
modparam("dialog", "profiles_with_value", "inbound_call ; outbound_call; timed_call")
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "dlg_flag", 4)
modparam("dialog", "send_bye", 1)
modparam("dialog", "timer_procs", 1)
modparam("dialog", "timeout_noreset", 1)
modparam("dialog", "default_timeout", 43200)

$avp(limit) = 15;
dlg_manage();
dlg_set_timeout_by_profile("timed_call", "1", "$avp(limit)");
dlg_set_timeout($avp(limit));
set_dlg_profile("timed_call", "1");
```
#### Log Messages

```
Aug 14 11:06:28 x /usr/sbin/kamailio[11925]: WARNING: dialog [dlg_req_within.c:216]: bye_reply_cb(): inconsitent dlg timer data on dlg 0x7fe5e0b162f8 [438:1408] with clid 'fPBP01fpFOA5Lq6aVwtZ6Q..' and tags '9f514a4f' 'as6e1fd9bc'
Aug 14 11:06:28 x /usr/sbin/kamailio[11925]: NOTICE: acc [acc_cdr.c:352]: log_write_cdr(): start_time=1502733971.701; end_time=1502733988.052; duration=16.351
Aug 14 11:06:28 x /usr/sbin/kamailio[11925]: WARNING: acc [acc_cdr.c:219]: db_write_cdr(): fallback to dlg_only search because of message doesn't exist.

```

#### SIP Traffic

Good bye (without topos loaded)
```
2017-08-14 10:06:29 -0800 : 10.10.10.180:5060 -> 10.10.10.177:5065

BYE sip:2505551234@10.20.20.224:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.180;branch=z9hG4bKbe16.c8c401b7000000000000000000000000.0
To: <sip:2505551234@mtl.dryvoip.ca;transport=UDP>;tag=as6e1fd9bc
From: <sip:1715033_123@mtl.dryvoip.ca;transport=UDP>;tag=9f514a4f
CSeq: 3 BYE
Call-ID: fPBP01fpFOA5Lq6aVwtZ6Q..
Route: <sip:10.10.10.177:5065;lr=on>
Content-Length: 0
User-Agent: kamailio (5.0.2 (x86_64/linux))
Max-Forwards: 70
```

Bad bye (with topos loaded)
```
2017-08-14 09:50:35 -0800 : 10.10.10.180:5060 -> 10.20.20.224:5060

BYE sip:2505551234@10.20.20.224:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.180;branch=z9hG4bK2409.87c78083000000000000000000000000.0
To: <sip:2505551234@mtl.dryvoip.ca;transport=UDP>;tag=as574ee653
From: <sip:1715033_123@mtl.dryvoip.ca;transport=UDP>;tag=df42e302
CSeq: 3 BYE
Call-ID: s1A7v71pjL_HNxHBscGpSg..
Content-Length: 0
User-Agent: kamailio (5.0.2 (x86_64/linux))
Max-Forwards: 70
```
### Additional Information

```
version: kamailio 5.0.2 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled on 12:04:13 Jun 26 2017 with gcc 4.4.7
```

**Comment by miconda** [comment]
Can you test with master branch (your config for 5.0.x should work) and use debug=3 in kamailio.cfg? Then attach all logs printed by kamailio when the BYEs are sent out.

**Comment by dryvoip** [comment]
I tried but couldn't compile master.

See my comment here: https://github.com/kamailio/kamailio/commit/4eec934a537551d78e833769c182f8020040a678

**Comment by miconda** [comment]
Are you sure you compile a fully fresh cloned master?

**Comment by dryvoip** [comment]
Deleted previous comment to keep this issue clean.

With head from yesterday, same results and here's the output.

[debug from head.txt](https://github.com/kamailio/kamailio/files/1226542/debug.from.head.txt)

**Comment by miconda** [comment]
From the logs, topos doesn't do anything for any of the BYEs (as it should, because they are generated by the server). Can you check if the dialog structures are the same with and without topos? You can dump them via rpc command once the call is answered -- important to see if record route headers are saved.

**Comment by dryvoip** [comment]
You are correct.  When topos is loaded, route_set is blank under callee.  With no topos the value does appear there.

**Comment by dryvoip** [comment]
Not sure if related but on call setup I'm seeing this logged

`Aug 17 16:35:25 lev /usr/sbin/kamailio[15994]: ERROR: topos [tps_storage.c:1254]: tps_db_update_dialog(): no valid dlg uuid`

**Comment by miconda** [comment]
Can you send me all log messages with debug=3 in kamailio.cfg for such a call setup?

**Comment by dryvoip** [comment]
I have sent you the logs direct to your gmail address as I don't want to make any errors redacting things that may confuse the issue.

**Comment by miconda** [comment]
Can you resend as zip or tgz (tar.gz / gz) instead of 7z? These are common formats that can be unarchived on mobile devices as well.

**Comment by dryvoip** [comment]
resent as a zip

**Comment by dryvoip** [comment]
Is there anything further I can do to assist with this?

**Comment by miconda** [comment]
Started to look at the logs at some point, but got distracted by other tasks ... and with no much spare time it got delayed. I will try to get back to it asap.

**Comment by miconda** [comment]
Got some time for it ... according to the logs the route set is seen empty by the dialog module (you can search for route_set in the logs).

I need more data to troubleshoot:

  * grab the pcap with sip packets for such a call
  * add following in your config before doing  the test.

At the top of request_route block add:

```
xlog("received request from $si with content [[$mb]]\n");
```

At the top of reply_route (add it if you don't have it):

```
xlog("received reply from $si with content [[$mb]]\n");
```

Also add the global parameter:

```
log_prefix="{$mt $hdr(CSeq) $ci} "
```

Put the pcap file and the logs file in a tarball or zip and send it to me.

**Comment by dryvoip** [comment]
Interestingly I cannot reproduce the problem with those added lines.  If I comment them out, I can still reproduce the problem.  Will experiment a little more but thought I'd provide that clue.

**Comment by dryvoip** [comment]
Just sent you the pcap and log file. 

So here's the fun part:

When I add `log_prefix="{$mt $hdr(CSeq) $ci} "` to the global section, the problem *no longer exists* but when I comment this out, the problem returns.

This seems to be perfectly reliable to fix & break the issue accordingly.

So needless to say the file I sent you does not include the log_prefix, but it does include the other requested changes.

**Comment by dryvoip** [comment]
Do you have everything you need from me for now?  Anything I can do to encourage effort on this issue?  Thanks

**Comment by miconda** [comment]
Need to get back to it, went out of my radar due to other tasks that popped up around here ... thanks for the reminder, it is always good to do it!

**Comment by miconda** [comment]
Finally back to it, I reviewed a bit based on your hint that issue was not exposed when `log_prefix` was set and I just pushed a patch to master and 5.0 branches. Can you try and report if all ok now?

**Comment by sergey-vb** [comment]
Hi All.
I have just make some tests and now Route header present.
So seems this issue was fixed with Daniel's latest commit.

But I have found one more little issue with topos...
When callee device not reachable kamailio tries to reach it, I have profile with 3 retries with 1second interval,

But Contact header present only in 1-st Invite. Next Invites are send without Contact header...

I will send dump with topos and topoh in private e-mail to you Daniel.

Can you look at this issue or better to create a new one in kamailio github?

Thank you.

**Comment by miconda** [comment]
I need also all log messages with `debug=3` in kamailio.cfg for such a call.

**Comment by dryvoip** [comment]
Confirmed is working now.  Thanks!

**Comment by sergey-vb** [comment]
I have send it via e-mail to you, Daniel.

Thank you in advance.

**Comment by sergey-vb** [comment]
Hi Daniel,
I think you can close this issue.
For Contact header in retries for initial INVITE I will open new one.

Thank you.
