### ISSUE TITLE
Document record-call option in rtpengine

### ISSUE THREAD

**Issue by aalba6675** [kamailio/kamailio#1221]
### Description
Document record-call option in rtpengine module

### Troubleshooting
rtpengine module has an undocumented option in rtpengine_manage and rtpengine_offer

```
rtpengine_manage("record-call=on")
```
The use case is to start the recording immediately so the recording structures are initialized in rtpengine. If we do not do this but use a sequence like

```
rtpengine_manage() /* A */
/* what happens is recording structures are not initialized so 
   metadata for caller's SDP is not written out
 */
start_recording()    /* B */
```
The metadata of the recording will omit the caller's SDP because this is written out during A but recording structures are only initialized in B.

https://github.com/sipwise/rtpengine/issues/385

**Comment by miconda** [comment]
Is `record-call=on` a replacement for `start_recording()` or the option has to be given to `rtpengine_manage()` and then the start recording function still needs to be used?

**Comment by aalba6675** [comment]
The are separate and orthogonal
Option 1:
```
rtpengine_manage('record-call=on')
## will start recoridng no need for start_recording()
```

Option 2:
```
rtpengine_manage()
### sometime later in route script

start_recording()
```

**Comment by miconda** [comment]
Docs enhanced with the commit referenced above.
