### ISSUE TITLE
when using db_text, can't use relative path, only full path is working in kamailio 4.4

### ISSUE THREAD

**Issue by os11k** [kamailio/kamailio#1224]
### Description

when using db_text, can't use relative path, only full path is working in kamailio 4.4

modparam("lcr", "db_url", "text://dbtext") -- do not work

modparam("lcr", "db_url", "text:///usr/local/etc/kamailio/dbtext") -- works as expected

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
 0(1) DEBUG: db_text [dbt_file.c:104]: dbt_load_file(): db is [/usr/local/etc/kamailio/]
 0(1) DEBUG: db_text [dbt_file.c:119]: dbt_load_file(): loading file [/usr/local/etc/kamailio/]
 0(1) DEBUG: db_text [dbt_tb.c:181]: dbt_table_new(): mtime is 1504165928
 0(1) ERROR: db_text [dbt_base.c:215]: dbt_query(): table version not loaded! (too few columns)
 0(1) ERROR: db_text [dbt_base.c:357]: dbt_query(): failed to query the table!
 0(1) ERROR: <core> [db.c:397]: db_table_version(): error in db_query
 0(1) ERROR: <core> [db.c:436]: db_check_table_version(): querying version for table lcr_rule
 0(1) ERROR: lcr [lcr_mod.c:649]: mod_init(): error during table version check
 0(1) ERROR: <core> [sr_module.c:967]: init_mod(): Error while initializing module lcr (/usr/local/lib64/kamailio/modules/lcr.so)

```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

use full path

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 4.4.6 (x86_64/linux) 897942
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 897942
compiled on 06:27:57 Aug 31 2017 with gcc 6.3.0

```

* **Operating System**:

```
Debian GNU/Linux 9 \n \l

4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 GNU/Linux

```

**Comment by miconda** [comment]
The complain is related to table `version` having too few columns. I pushed a patch to print number of columns, can you try with latest branch version (or apply the last patch from db_text - 2683b20d7b62f60ce53ed6692a42ed6b19fee972)?

**Comment by os11k** [comment]
Hi,

Same problem:

 0(1) DEBUG: <core> [sr_module.c:693]: find_mod_export_record(): find_export_record: found <db_bind_api> in module db_text [/usr/local/lib64/kamailio/modules/db_text.so]
 0(1) DEBUG: <core> [db.c:209]: db_bind_mod(): using db bind api for db_text
 0(1) DEBUG: <core> [usr_avp.c:882]: parse_avp_ident(): Parsing 'lcr_gw_uri'
 0(1) DEBUG: <core> [pvapi.c:293]: pv_cache_add(): pvar [$avp(lcr_gw_uri)] added in cache
 0(1) DEBUG: <core> [usr_avp.c:882]: parse_avp_ident(): Parsing 'lcr_ruri_user'
 0(1) DEBUG: <core> [pvapi.c:293]: pv_cache_add(): pvar [$avp(lcr_ruri_user)] added in cache
 0(1) DEBUG: <core> [usr_avp.c:882]: parse_avp_ident(): Parsing 'lcr_flag'
 0(1) DEBUG: <core> [pvapi.c:293]: pv_cache_add(): pvar [$avp(lcr_flag)] added in cache
 0(1) INFO: db_text [dbt_base.c:92]: dbt_init(): using database at: /usr/local/etc/kamailio/
 0(1) DEBUG: db_text [dbt_lib.c:125]: dbt_cache_get_db(): looking for db /usr/local/etc/kamailio/!
 0(1) DEBUG: db_text [dbt_lib.c:146]: dbt_cache_get_db(): new db!
 0(1) DEBUG: db_text [dbt_file.c:97]: dbt_load_file(): request for table [version]
 0(1) DEBUG: db_text [dbt_file.c:104]: dbt_load_file(): db is [/usr/local/etc/kamailio/]
 0(1) DEBUG: db_text [dbt_file.c:119]: dbt_load_file(): loading file [/usr/local/etc/kamailio/]
 0(1) DEBUG: db_text [dbt_tb.c:181]: dbt_table_new(): mtime is 1504173561
 0(1) ERROR: db_text [dbt_base.c:215]: dbt_query(): table version - too few columns (0 < 1)
 0(1) ERROR: db_text [dbt_base.c:358]: dbt_query(): failed to query the table!
 0(1) ERROR: <core> [db.c:397]: db_table_version(): error in db_query
 0(1) ERROR: <core> [db.c:436]: db_check_table_version(): querying version for table lcr_rule
 0(1) ERROR: lcr [lcr_mod.c:649]: mod_init(): error during table version check
 0(1) ERROR: <core> [sr_module.c:967]: init_mod(): Error while initializing module lcr (/usr/local/lib64/kamailio/modules/lcr.so)
ERROR: error while initializing modules

**Comment by miconda** [comment]
The patch was for a log message to see number of columns, which is shown as 0.

**Comment by os11k** [comment]
Hi Daniel,

Yes, it shows 0 columns, because it tries to find "version" table/file in /usr/local/etc/kamailio/, but it should look into /usr/local/etc/kamailio/dbtext...

kamailio probably loads empty file, cause it is not looking in correct directory and because of empty file there is 0 columns.

At least this is my understanding...

**Comment by miconda** [comment]
I just pushed a patch aiming to fix it. Try again and let's see the results.

**Comment by os11k** [comment]
Hi Daniel,

It is working now as expected! Thank you a lot!!!

Have a nice day!

**Comment by miconda** [comment]
Thanks for testing!
