### ISSUE TITLE
USRLOC JSONRPC ul.add - ability to set all entry fields

### ISSUE THREAD

**Issue by kbdfck** [kamailio/kamailio#1225]
Looking into code it seems RPC functions of USRLOC don't allow setting all fields for USRLOC entry, for example, Received and Socket.

It would be great if we can set these, because we need to have ability to transfer contacts from other server to Kamailio.

I think at present this can be done sending specially crafted fake REGISTER packets or calling special route from HTTP with some tricks for saving contact and received, but as for me it would be great to set it from RPC because we already have ul.add method.

It also would be cool if we can use named parameters in JSONRPC params: {} section with names corresponding to usrloc fields, like 'table', 'AOR', 'received' and so on. Maybe on specual key not to mix with current 'params'.

**Comment by miconda** [comment]
The order of parameters matters, it's how all rpc commands are implemented -- there are other RPC transports than jsonrpc (e.g., binrpc, xmlrpc) and the order is the common requirement that implementation relies on.

For jsonrpc it may work to provide params with names (iirc), but the order must be kept.

**Comment by miconda** [comment]
I just pushed the commit that allows setting received and socket fields via rpc ul.add. It is available in master branch.
