### ISSUE TITLE
cannot build acc_radius_mod on fedora

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1226]
### Description

On Fedora distr package `radiusclient-ng` is replaced by `freeradius-client`. [More info](https://src.fedoraproject.org/rpms/radiusclient-ng/commits/master)
After updating `spec` file build of `acc_radius_mod` is still not possible details of error
```
[  529s] In file included from acc_radius_mod.c:44:0:
[  529s] ../misc_radius/radius.h:38:12: fatal error: radiusclient-ng.h: No such file or directory
[  529s]    #include <radiusclient-ng.h>
[  529s]             ^~~~~~~~~~~~~~~~~~~
[  529s] compilation terminated.
[  529s] make[2]: *** [../../Makefile.rules:100: acc_radius_mod.o] Error 1
[  529s] make[1]: *** [Makefile:511: modules] Error 1
[  529s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/kamailio-5.0.3/src'
[  529s] make: *** [Makefile:27: every-module] Error 2
```

Think need use package `freeradius-client` and if this not installed then try to use `radiusclient-ng`.

**Comment by amessina** [comment]
radiusclient-ng was deprecated in favor of radcli.  You need BuildRequires: radcli-compat-devel

**Comment by sergey-safarov** [comment]
@amessina 
This is help. I will create PR to update SPEC file

**Comment by sergey-safarov** [comment]
Created pull request https://github.com/kamailio/kamailio/pull/1227

**Comment by miconda** [comment]
The radius client library can be selected by setting either `FREERADIUS` or `USE_RADCLI` to 1 when compiling radius modules, see `Makefile.radius`:

  * https://github.com/kamailio/kamailio/blob/master/src/Makefile.radius

Like:

```
make FREERADIUS=1 modules modules=src/modules/auth_radius
```

Should anyone have a way/ideas to improve this (either in Makefile or via docs), a pull request will be appreciated.
