### ISSUE TITLE
need some help about acc module

### ISSUE THREAD

**Issue by prashantvidja** [kamailio/kamailio#1229]
Hello,

I have some feature required changes in acc module.
In acc module we getting cdrs in database only which have
METHOD=INVITE
METHOD=BYE
but in my setup I also get 
METHOD=OPTIONS
so I need this entry also in acc table in kamailio database.

so which changes i need to do in kamailio acc module.... or other......
my cdrs log I paste below which have mehod=options

"Sep  7 07:16:53 sip /usr/local/sbin/kamailio[29264]: NOTICE: acc [acc.c:317]: acc_log_request(): ACC: request accounted: timestamp=1504783013;method=OPTIONS;from_tag=eUC9UgGrD;to_tag=j90H6yy5pU6Xc;call_id=2xJd0KCt-P;code=200;reason=OK;calling=46566464645;called=you;egressIP=kamailio.org;src_ip=1.0.0.127;to=<sip:+918866213320@sip.call.org>;tag=j90H6yy5pU6Xc;from=sip:918888888888@localhost;contact=;pai=;uri=sip:you@kamailio.org;onnet=0;rate=0.000333333"

Thanks.. # #

**Comment by miconda** [comment]
This is about configuring kamailio.cfg, the acc module can account a record for any kind of sip request.

You have to present more details about your config via sr-users@lists.kamailio.org mailing list and try to find the solution there.

The issue tracker here is used only for bugs in the C code and tracking feature requests. Therefore what you need to achieve doesn't belong here.

**Comment by prashantvidja** [comment]
Hello,

but acc module only billing those cdrs which have METHOD=BYE ....
please give me some guide about configuring kamailio.cfg so I can do billing for all calls....

Thanks
