### ISSUE TITLE
UAC module - registration not retried if there is no response to request

### ISSUE THREAD

**Issue by AndyJRobinson** [kamailio/kamailio#124]
Running Kamailio 4.2.3. When the UAC module sends a registration request, it sets the UAC_REG_ONGOING flag in reg->flags. If there is no response to the request, the flag is never cleared, so all future calls to uac_reg_update return without ever retrying the request. That is, the registration becomes "stuck" in the UAC_REG_ONGOING state forever.

**Comment by miconda** [comment]
Thanks for reporting, pushed patch to fix it in master and 4.2 branches. If the issue is not solved, reopen.

**Comment by AndyJRobinson** [comment]
Problem not solved... still seeing "stuck" registrations. Note that in this case, I'm not getting a timeout response back from the UAS. The case where I'm seeing the issue is when the UAS never responds at all.

I don't think adding the line to reset UAC_REG_ONGOING and UAC_REG_AUTHSENT at the error: label really changed anything, since the done: label, which immediately follows it, already reset those flags (and would be executed on the goto error).
