### ISSUE TITLE
How to enhance the "ASYNC Module" to support for SIP replies

### ISSUE THREAD

**Issue by rgmaddi** [kamailio/kamailio#1247]
Hi,

I am a newbie to kamailio, trying to understand how async module works.
It is working for request_route. 
I added ANY_ROUTE so as to allow for reply_route block as shown in the snippet below.
But the async_route function is not working for reply_route block. How can I achieve this.

static cmd_export_t cmds[]={
        {"async_route", (cmd_function)w_async_route, 2, fixup_async_route,
                0, REQUEST_ROUTE|FAILURE_ROUTE|ANY_ROUTE},
        {"async_sleep", (cmd_function)w_async_sleep, 1, fixup_async_sleep,
                0, REQUEST_ROUTE|FAILURE_ROUTE|ANY_ROUTE},
        {"async_task_route", (cmd_function)w_async_task_route, 1, fixup_async_task_route,
                0, REQUEST_ROUTE|FAILURE_ROUTE|ANY_ROUTE},
        {0, 0, 0, 0, 0, 0}
};

**Comment by miconda** [comment]
Use the mailing lists for how to use kamailio (sr-users@lists.kamailio.org) or getting help on understanding kamailio code (sr-dev@lists.kamailio.org). The tracker here is for bug reports and proposals for new features.
