### ISSUE TITLE
IPOPS is_in_subnet function doesn't return TRUE for host address in cidr notation

### ISSUE THREAD

**Issue by kbdfck** [kamailio/kamailio#1250]
### Description

is_in_subnet function requires subnet param to be network address and fails for host address in cidr notation despite it is contained in corresponding subnet.

For example, is_in_subnet("1.2.3.2", "1.2.3.0/30") returns true
but
is_in_subnet("1.2.3.2", "1.2.3.2/30") returns false, although 1.2.3.2 is present in 1.2.3.2/30 and 1.2.3.2 is a part of 1.2.3.0/30

Of course, "1.2.3.2/30" this is not actually a subnet specification and rather is IP in CIDR notation, but sometimes it is required to check if some IP matches specified IP with CIDR.

Btw, is_in_subnet("1.2.3.2", "1.2.3.2/32") returns TRUE, so I think it makes sense to match 1.2.3.2/30 too.

### Possible Solutions

It would be cool if is_in_subnet take such cases as matches. I think this should not break anything, because host IP and CIDR always define network containing specified host.
Another solution would be separate function with more relaxed behavior...

This happens on Kamailio 5.1 devel.

**Comment by miconda** [comment]
Implemented in latest master.
