### ISSUE TITLE
p_usrloc: location.sql missing RUID_COL and REG_ID_COL

### ISSUE THREAD

**Issue by asiplas** [kamailio/kamailio#1265]
## p_usrloc: location.sql missing columns

[location.sql](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/location.sql) should include columns corresponding to `RUID_COL` and `REG_ID_COL`) from [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65)

### Log Messages
```
kamailio: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Unknown column 'reg_id' in 'field list' (1054)
kamailio: ERROR: <core> [db_query.c:132]: db_do_query_internal(): error while submitting query
kamailio: ERROR: p_usrloc [ul_db_query.c:110]: db_exec_query(): could not query table location.
```
```
kamailio: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Unknown column 'ruid' in 'field list' (1054)
kamailio: ERROR: <core> [db_query.c:132]: db_do_query_internal(): error while submitting query
kamailio: ERROR: p_usrloc [ul_db_query.c:110]: db_exec_query(): could not query table location.
```
### Solutions
Adding columns referenced by [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65) to match `kamdbctl`'s [usrloc-create.sql](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/utils/kamctl/mysql/usrloc-create.sql#L3)

**Comment by asiplas** [comment]
`kamdbctl`'s [usrloc-create.sql](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/utils/kamctl/mysql/usrloc-create.sql#L3) already includes all of these columns plus others and indexes, is this file better completely removed?

**Comment by lbalaceanu** [comment]
Hello,

p_usrloc has not been kept up to date with latest usrloc and as such for now I cannot tell you if the seemingly superset of columns in the usrloc-create.sql does it.
If we only had one sql, the patching would also have to be done in the unlikely case that usrloc would delete fields in the usrloc-create.sql imho.

Thanks
