### ISSUE TITLE
Use NAT IP to keep DNS-loadbalance

### ISSUE THREAD

**Issue by abell-star** [kamailio/kamailio#1268]
I let two kamailio server processes run in two Nat IP , and DNS to keep loadbalance. but DNS can return two Nat IP,when the IP it returns is not the same as the account register,the server cann't deal with request,i wonder if i can use Nat IP to keep DNS loadbalance?

**Comment by mslehto** [comment]
Kamailio projects uses Github issues only for reporting bugs and tracking change requests.
For general discussion there is mailing list: https://www.kamailio.org/w/mailing-lists/
