### ISSUE TITLE
kazoo: amqp_connection parameter maximum length is too short

### ISSUE THREAD

**Issue by mlipscombe** [kamailio/kamailio#1269]
The 100 character hard-coded maximum length of the kazoo module's amqp_connection parameter is too short.  The limit was previously bumped from 50 to 100 following on from #529  but this is still too short.

Example use case, using Hashicorp's vault to dish out AMQP credentials yields a connection URL like this:

amqp://aws-ec2-13e1e70e-d4d3-abbe-5f3b-7b631f83def7:63b8d362-72d1-878e-81ca-d62667503495@rabbitmq.service.consul:5672

https://github.com/kamailio/kamailio/blob/48791fae1ba8508b18856d90e85a93df003b1e3b/src/modules/kazoo/kz_amqp.c#L682

**Comment by lazedo** [comment]
fixed by https://github.com/kamailio/kamailio/commit/33ecbbbaf8054220372637ac89ac4e4a7c7748d0
