### ISSUE TITLE
dispatcher "socket" feature crashes kamailio

### ISSUE THREAD

**Issue by neuhaus** [kamailio/kamailio#127]
Using the new "socket" feature of the dispatcher module causes a segmentation fault.

**Comment by neuhaus** [comment]
Pull request #128 fixes this bug.

**Comment by miconda** [comment]
Thanks! Pushed the patch manually to have the commit message following the recommended guidelines -- allows us to get a coherent changelog for releases:

  * http://www.kamailio.org/wiki/devel/git-commit-guidelines#commit_message
