### ISSUE TITLE
db_check_table_version(): invalid version 6 for table subscriber found, expected 7 (check table structure and table "version")

### ISSUE THREAD

**Issue by abell-star** [kamailio/kamailio#1270]
kamailio version：5.0.1

**Comment by SurendraPlivo** [comment]
i think you didn't go threw below documents before migrating to kamailio 5.x.x.
https://www.kamailio.org/wiki/install/upgrade/4.4.x-to-5.0.0

**Comment by mckaygerhard** [comment]
a stupid response @SurendraPlivo do you noted that kamailio does not have that table? its a asterisk table due realtime integration pufff

**Comment by joelsdc** [comment]
The subscriber table is used by kamailio, what does asterisk have to do here?

**Comment by surendratiwari3** [comment]
@mckaygerhard please have a look on below link:
https://kamailio.org/docs/db-tables/kamailio-db-5.1.x.html#gen-db-subscriber

Let me know if you need any specific help for this.

**Comment by mckaygerhard** [comment]
hi, @surendratiwari3 thanks for your answer, the suscriber doc table looks good but does not point any version chek related info..  

that by casuallity are in https://kamailio.org/docs/db-tables/kamailio-db-5.1.x.html#gen-db-version but this are no related info again! so then?

**Comment by surendratiwari3** [comment]
@mckaygerhard k so basically, Kamailio maintains the version tables correspondence to every table into version table.  so if any changes happen to the database table in particular upgrade version of that table also get changed.

**Comment by mckaygerhard** [comment]
related to #1780 .. kamailio as said in documentation must upgraded version of the tables.. BUT does not said nothing about the version of same counterpart in asteriks instegration.. a complete pain in the ass
