### ISSUE TITLE
Feature request: Increase number of "custom fields" in sipcapture-module

### ISSUE THREAD

**Issue by mihovilkolaric** [kamailio/kamailio#1278]
The module sipcapture provides the modparams "custom_field1_header" to "custom_field3_header", to store the content of up to three arbitrary header fields as separate columns in the database. They can be used as all other "standard" columns in homer.

However I found out that searching/filtering for even more (standardized, as well as private) header fields would be very helpful (I identified about ten interesting additional headers, but the number is constantly increasing ;-) ).

Could you thus please increase the number of custom fields? 
(I suppose the most flexible solution could be something as the db_extra in the acc-module, which is not fixed to certain columns (regarding number of columns, as well as their names) (see https://www.kamailio.org/docs/modules/5.0.x/modules/acc.html#acc.p.db_extra ).)

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
