### ISSUE TITLE
sanity() test passes on invalid uri

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#1289]
K master sanity() test passes URI hostpart that contains ` (back quote) character and possibly other invalid hostpart characters:

Config:

modparam("sanity", "default_checks", 1024) /* URI checks */
modparam("sanity", "uri_checks", 3)  /* RURI, From */

    xlog("L_INFO", "Checking $ru\n");
    if (!sanity_check())
        xlog("L_INFO", "Check failed\n");
    else
        xlog("L_INFO", "Check passed\n");

Syslog:

Oct 27 17:17:38 lohi /usr/bin/sip-proxy[31946]: INFO: Checking sip:jh at te`st.fi
Oct 27 17:17:38 lohi /usr/bin/sip-proxy[31946]: INFO: Check passed

According to RFC3261:

hostname         =  *( domainlabel "." ) toplabel [ "." ]
domainlabel      =  alphanum
                    / alphanum *( alphanum / "-" ) alphanum

**Comment by miconda** [comment]
I think this was fixed by commit 4994960324d5353222b3de08515bed07802ab7bc, if not, reopen.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> I think this was fixed by commit
> 4994960324d5353222b3de08515bed07802ab7bc, if not, reopen.

Yes, I didn't remember that I had opened an issue about it.

-- Juha
