### ISSUE TITLE
textops: Support  RFC3264 for is_audio_on_hold() function

### ISSUE THREAD

**Issue by JuliaBoud** [kamailio/kamailio#1292]
Function "is_audio_on_hold()" has support for rfc2543 only,
where "hold"  is indicated by setting  the "c" destination  addresses for the media streams to zero  (0.0.0.0).
Could you please add support for rfc3264 for this function, where "hold" is indicated by a=sendonly/inactive.

**Comment by ovidiusas** [comment]
is_audio_on_hold() will return the hold type:
````
if(is_audio_on_hold())
{
    switch ($rc) {
    case 1:
        # RFC2543 hold type
        # do interesting stuff here
        break;
    case 2:
        # RFC3264 hold type
        # do interesting stuff here
        break;
}
````
