### ISSUE TITLE
Memory leak fifo process

### ISSUE THREAD

**Issue by jmetivier-jive** [kamailio/kamailio#1295]
### Description

We experience the same issue as http://lists.opensips.org/pipermail/users/2015-September/032520.html

#### Log Messages
ERROR: regex [regex_mod.c:289]: load_pcres(): no more memory for patterns[10]
ERROR: regex [regex_mod.c:679]: mi_pcres_reload(): failed to reload pcres

### Possible Solutions

See their solution : https://github.com/OpenSIPS/opensips/commit/aa7429e0124478f999ba3737b10ae39900e16b2c

### Additional Information

kamailio -v
version: kamailio 4.2.0 (x86_64/linux) 36e695
flags: STATS: Off, USE_TCP, USE_TLS, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_F_MALLOC, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 36e695
compiled on 08:10:49 Sep  7 2016 with gcc 4.9.2

* **Operating System**:

uname -a
Linux abc 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64 GNU/Linux

**Comment by miconda** [comment]
Thanks for report and relevant troubleshooting hints!

I pushed a patch for it as part of commit 5940e759a754644d29e4145eea648ede45b4b356. This was backported to branch 5.0.

In branch 4.4 was a partial backport with commit 7a3f89954ef1d2daf49fb9a7b7e080c2edecc174. This one should be easy to cherry pick to older branches. At this moment we maintain only last two stable branches, respectively 5.0 and 4.4.
