### ISSUE TITLE
Possible issue with parameters

### ISSUE THREAD

**Issue by verticelo** [kamailio/kamailio#1333]
https://github.com/kamailio/kamailio/blob/f95fda89d4532ba333aed835c72f102a7c032980/src/modules/textops/textops.c#L3835

Hi, it seems that KEMI defines this method to accept one parameter but the ki_search_append seems to expect two arguments.

I might have misunderstood how KEMI is implemented but wanted to open this ticket in case it is an issue.

The same goes for: search_append_body

**Comment by miconda** [comment]
Thanks! Patch pushed is referenced above. Proof checking other exports is very appreciated...

**Comment by verticelo** [comment]
@miconda Hey, I did write a script that checked all other exports for a match on the quantity of parameters but these were the only faulty ones I found. (I didn't check core/hdr/pvx).

I haven't checked for a match between the types on any of them.
