### ISSUE TITLE
http_client module error to post the hdr part into http_client_query

### ISSUE THREAD

**Issue by SurendraPlivo** [kamailio/kamailio#1364]
### Description
There is problem with http_client module they don't have the 4 paramterized export function.

### Troubleshooting
we trouble shoot it and found problem with http_client module
#### Reproduction
http_client_query("http://tutpro.com/index.php", "{ "alert": "Alert text goes here" }", "Content-Type: application/json","$var(result)");

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
5.0.2
```
(paste your output here)
```

**Comment by linuxmaniac** [comment]
I think this is not correct:
```
http_client_query("http://tutpro.com/index.php", "{ "alert": "Alert text goes here" }", "Content-Type: application/json","$var(result)");
```

It should be:

```
http_client_query("http://tutpro.com/index.php",'{ "alert": "Alert text goes here" }', "Content-Type: application/json","$var(result)");
```

Please try. If it does not work, please provide the output with debug enabled

**Comment by miconda** [comment]
Besides having proper parameters format, note that the function with 4 parameters was mistakenly exported as `http_query` (an error propagated by the move from utils module), latest 5.0 branch has it correct now as `http_client_query`, so upgrade to use latest 5.0 branch.

**Comment by miconda** [comment]
Reopen if still an issue after the above comments.
