### ISSUE TITLE
permissions "trustedDump" outputs to strange characters

### ISSUE THREAD

**Issue by eschmidbauer** [kamailio/kamailio#137]
I'm running latest kamailio version (as of today) from the git
Using postgres 9.4 db backend.
When I do "trustedDump" output is strange.
Example:
root@ua01-proxy01:~# kamctl kamcmd permissions.trustedDump
{
        table: 27
        item: {
                ip: 10.10.5.112­úæ¼ÿÿÿÿÿÿÿÿ
                proto: 0
                pattern: NULL
                tag: peer
        }
        table: 31
        item: {
                ip: 10.10.1.112(‘¹‚÷ m»‚j ÉUŠ´'æ
                -_-+-: 0
                -a++e_+: NULL
                +ag: -ee_
        }
        +ab+e: 48
        i+e+: {
                i-: 192.168.159.10
                -_-+-: 0
                -a++e_+: NULL
                +ag: -ee_
        }
        +ab+e: 70
        i+e+: {
                i-: 192.168.157.10 
                -_-+-: 0
                -a++e_+: NULL
                +ag: -ee_
        }
        +ab+e: 74
        i+e+: {
                i-: 192.168.101.154
                -_-+-: 0
                -a++e_+: NULL
                +ag: f_01
        }
        +ab+e: 75
        i+e+: {
                i-: 192.168.101.155 
                -_-+-: 0
                -a++e_+: NULL
                +ag: f_02
        }
}

**Comment by oej** [comment]
The real problem is in the first two records. After that, the terminal seems to change mode. But the characters after the IP address should not be there.

**Comment by miconda** [comment]
I pushed a patch in master branch: 89642d3cddd90ba3e3f6d310e239492634fa6405

Can you test with it and see if it is solved?

**Comment by eschmidbauer** [comment]
Patch fixed it!
Thanks for the quick response.
