### ISSUE TITLE
erlang: fails to build on alpha

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#1373]
From 5.1.0 official Debian build https://buildd.debian.org/status/fetch.php?pkg=kamailio&arch=alpha&ver=5.1.0-1&stamp=1513356538&raw=0
```
/usr/bin/make every-module group_include="kerlang" quiet=verbose
make[1]: Entering directory '/<<PKGBUILDDIR>>'
/usr/bin/make -C src/ every-module 
make[2]: Entering directory '/<<PKGBUILDDIR>>/src'
config.mak loaded
Makefile.defs defs skipped
Makefile.defs defs skipped
Makefile.defs defs skipped
beam.smp: allocatestack.c:480: allocate_stack: Assertion `size != 0' failed.
Aborted
beam.smp: allocatestack.c:480: allocate_stack: Assertion `size != 0' failed.
Aborted
Makefile:16: *** Not found Erlang.  Stop.
```

**Comment by miconda** [comment]
Not using the module, so not familiar at all with dependencies here, but the files mentioned above are not part of kamailio. `beam.smp` is part of erlang, maybe there is an issue with erlang package on that cpu architecture.

**Comment by sergey-safarov** [comment]
Current kamailio [build on alpha](https://buildd.debian.org/status/fetch.php?pkg=kamailio&arch=alpha&ver=5.1.6-1%2Bb1&stamp=1541196482&raw=0) is correct.
Think we can close this ticket.
