### ISSUE TITLE
permissions "trustedReload" fails

### ISSUE THREAD

**Issue by eschmidbauer** [kamailio/kamailio#138]
I'm running latest kamailio version (as of today) from the git
Using postgres 9.4 db backend.
When I do "trustedReload" output is as follows:

root@ua01-proxy01:~# kamctl kamcmd permissions.trustedReload
error: 500 - Reload failed.

and kamailio log shows:

Apr 22 10:16:21 ua01-proxy01 /usr/sbin/kamailio[20252]: ERROR: permissions [trusted.c:78]: reload_trusted_table(): no connection to database
Apr 22 10:16:25 ua01-proxy01 /usr/sbin/kamailio[20252]: ERROR: permissions [trusted.c:78]: reload_trusted_table(): no connection to database}

Only way for me to reload database is to restart kamailio.
Thanks,
Emmanuel

**Comment by miconda** [comment]
Pushed a patch on master branch. Test and report if works now.

**Comment by eschmidbauer** [comment]
Thanks, that fixed it.
