### ISSUE TITLE
UAC trouble with REGISTER to provider

### ISSUE THREAD

**Issue by ovoshlook** [kamailio/kamailio#140]
Hello.
We use UAC for RGISTER some trunks

After fiew days normally work we have an issue that UAC not respond to 401 reply with WWW-Authenticate with reREGISTER with WWW. We have only 2 packets- REGISTR and 401.

IP 10.0.1.12.5068 > 1.2.3.4.5060: UDP, length 467
E.......@..F
...............REGISTER sip:provider.com SIP/2.0
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bKdb22.edd7eac5000000000000000000000000.0
To: <sip:login@provider.com>
From: <sip:login@provider.com>;tag=6a39af2190f8b2c99cc63bfeb3a3959c-bfba
CSeq: 10 REGISTER
Call-ID: 5e171580088d170a-9952@10.0.1.12
Max-Forwards: 70
Content-Length: 0
User-Agent: kamailio (4.3.0-dev5 (x86_64/linux))
Contact: <sip:login@my.service.com:5068>
Expires: 360

IP 1.2.3.4.5060 > 10.0.1.12.5068: UDP, length 571
Q.......-.
........C.NSIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bKdb22.edd7eac5000000000000000000000000.0;received=1.2.3.4
From: <sip:login@provider.com>;tag=6a39af2190f8b2c99cc63bfeb3a3959c-bfba
To: <sip:login@provider.com>;tag=as1550511c
Call-ID: 5e171580088d170a-9952@10.0.1.12
CSeq: 10 REGISTER
Server: FastTel SoftSwitch
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Supported: replaces
WWW-Authenticate: Digest algorithm=MD5, realm="provider.com", nonce="109104dc"
Content-Length: 0

We have another trunk and reREGISTER is correctly

REGISTER sip:another_prov.com SIP/2.0
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bK7fd1.3d7c2fd7000000000000000000000000.0
To: <sip:login_to_another_prov@another_prov.com>
From: <sip:login_to_another_prov@another_prov.com>;tag=6a39af2190f8b2c99cc63bfeb3a3959c-f8ba
CSeq: 10 REGISTER
Call-ID: 5e171580088d1edd-9952@10.0.1.12
Max-Forwards: 70
Content-Length: 0
User-Agent: kamailio (4.3.0-dev5 (x86_64/linux))
Contact: <sip:login_to_another_prov@my.service.com:5068>
Expires: 360

IP another_prov.com.5060 > 10.0.1.12.5068: UDP, length 544
E..<F...$.      .6...
........(..SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bK7fd1.3d7c2fd7000000000000000000000000.0;rport=5068;received=1.2.3.4
To: <sip:login_to_another_prov@another_prov.com>;tag=04e2a294d0728b89107e081a19babab4.d569
From: <sip:login_to_another_prov@another_prov.com>;tag=6a39af2190f8b2c99cc63bfeb3a3959c-f8ba
CSeq: 10 REGISTER
Call-ID: 5e171580088d1edd-9952@10.0.1.12
WWW-Authenticate: Digest realm="another_prov.com", nonce="VTifD1U4neNLMSYRoxNlOpD7hPSu3ET3"
Server: kamailio (4.2.1 (x86_64/linux))
Content-Length: 0

IP 10.0.1.12.5068 > another_prov.com.5060: UDP, length 690
E...uT..@...
...6...........REGISTER sip:another_prov.com SIP/2.0
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bK8fd1.ea73d070000000000000000000000000.0
To: <sip:login_to_another_prov@another_prov.com>
From: <sip:login_to_another_prov@another_prov.com>;tag=6a39af2190f8b2c99cc63bfeb3a3959c-f8ba
CSeq: 11 REGISTER
Call-ID: 5e171580088d1edd-9952@10.0.1.12
Max-Forwards: 70
Content-Length: 0
User-Agent: kamailio (4.3.0-dev5 (x86_64/linux))
Contact: <sip:login_to_another_prov@my.service.com:5068>
Expires: 360
Authorization: Digest username="login_to_another_prov", realm="another_prov.com", nonce="VTifD1U4neNLMSYRoxNlOpD7hPSu3ET3", uri="sip:another_prov.com", response="2ee14a437173700e88056279b854749f", algorithm=MD5

**Comment by miconda** [comment]
Is this related to the wrong realm discussed on mailing list?

**Comment by miconda** [comment]
Guessing it was related to the the wrong realm discussed on mailing list.
