### ISSUE TITLE
Feature/help android fcm and ios related push notification module

### ISSUE THREAD

**Issue by dipenpatel235** [kamailio/kamailio#1425]
Hello..
Now most sip soft client in required push wakeup phone.
So for that required android, ios push notifications module.

I have seen some one have developed some module but it is old.

So if possible so please write push notifications for wakeup phone module.

Thanks

**Comment by grumvalski** [comment]
Hi,
push notifications are already supported by kamailio by means of t_suspend/t_continue functions (http://www.kamailio.org/docs/modules/devel/modules/tmx.html#tmx.f.t_suspend) and tsilo module (http://www.kamailio.org/docs/modules/devel/modules/tsilo.html).
You can watch this video (https://youtu.be/4XIrR9bwUkM) and read the related presentation (http://www.kamailio.org/events/2015-KamailioWorld/Day2/20-Federico.Cabiddu-Kamailio-In-A-Mobile-World.pdf) to see how put all the pieces together.

**Comment by dipenpatel235** [comment]
Hello..
Thanks but I mean not that as per given.
My meaning is suppose sip phone application is not running so using android
FCM providing push wakeup app using device token.

So in our case when X user call to Y user then suppose Y user application
is not running in background then kamailio module send push notifications
to Y user using android/ios FCM service so app will wakeup and call will
reach to Y user.


Let me know about description enough to understand or required still more
details example so I can..

Thanks..

On Feb 3, 2018 12:26 AM, "Federico Cabiddu" <notifications@github.com>
wrote:

Hi,
push notifications are already supported by kamailio by means of
t_suspend/t_continue functions (http://www.kamailio.org/docs/
modules/devel/modules/tmx.html#tmx.f.t_suspend) and tsilo module (
http://www.kamailio.org/docs/modules/devel/modules/tsilo.html).
You can watch this video (https://youtu.be/4XIrR9bwUkM) and read the
related presentation (http://www.kamailio.org/events/2015-KamailioWorld/
Day2/20-Federico.Cabiddu-Kamailio-In-A-Mobile-World.pdf) to see how put all
the pieces together.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kamailio/kamailio/issues/1425#issuecomment-362668553>,
or mute the thread

**Comment by dipenpatel235** [comment]
Yes your tsilo module link is right but in that GCM is very old now.
So everyphone and app is now using android FCM for Android and iOS.

So for that required to upgrade that module only.

Thanks

**Comment by grumvalski** [comment]
It is exactly what I described. If you want a way to send directly the
request for the push service you can use one of the kamailio's HTTP modules
to send it to GCM or whatever service your application is using. The key is
not sending the push itself but being able to wait for the target device(s)
to be alive and send it the INVITE. As far as I know no SIP server
currently has a module to send directly the push request to GCM, APNS etc.

**Comment by dipenpatel235** [comment]
Yes now not in sip server that.
And using http request also not fast same as modules.

GCM is old technology now and almost outdated.

See right now I am doing using flexisip push gateway but it is not much
stable performance.

So if any kamailio developer integrate for kamailio module to it will game
changer..

I will explain if any details required to develope it. But i have not
experience in c programming..

Thanks

**Comment by miconda** [comment]
The sr-users@lists.kamailio.org mailing list should be used for further discussions on how to use kamailio or implement routing logic inside kamailio.cfg, including the integration with external systems.
