### ISSUE TITLE
[master] jsonrpcs doesn't work on AARCH64 ?!

### ISSUE THREAD

**Issue by BroWater** [kamailio/kamailio#1429]
### Description

I upgraded from 4.2 to latest commit on master branch.

During migrating, I found mi was replaced by RPC, 
(https://www.kamailio.org/wiki/install/upgrade/4.4.x-to-5.0.0)
and when I tested with command like `sh kamctl ps`,
it showed:

```
# sh kamctl ps
awk: bad regex '^{.+"id"[       ]*:[    ]*[0-9]+[       ]*}$': Invalid preceding regular expression
```
I also tested it in standard configuration on my PC according to the following steps:
```
make cfg
make all
make install
```

and it works

```
# sh kamctl ps
{
  "jsonrpc":  "2.0",
  "result": [
    {
      "IDX":  0,
      "PID":  30916,
      "DSC":  "main process - attendant"
    }, {
      "IDX":  1,
      "PID":  30917,
      "DSC":  "udp receiver child=0 sock=127.0.0.1:5060"
    }, {
      "IDX":  2,
      "PID":  30918,
      "DSC":  "udp receiver child=1 sock=127.0.0.1:5060"
    }, {
      "IDX":  3,
      "PID":  30919,
      "DSC":  "udp receiver child=2 sock=127.0.0.1:5060"
    ....
   
```

My configuration settings and install steps are like followings:

CC=/opt/toolchains/aarch64-thunderx/bin/aarch64-thunderx-linux-gnu-gcc make cfg ARCH=aarch64 LOCALBASE=/mnt/test/kamailio/
make all
make install

Any suggestion??

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
# ./kamailio -v
version: kamailio 5.2.0-dev3 (aarch64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT-NOSMP, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled on 14:28:54 Feb  7 2018 with /opt/toolchains/aarch64-thunderx/bin/aarch64-thunderx-linux-gnu-gcc 5.3.0
```

* **Operating System**:

```
Linux XXX 4.4.13 #1 SMP PREEMPT Fri Mar 24 10:50:44 CST 2017 aarch64 GNU/Linux
```

**Comment by BroWater** [comment]
Well , I solved it myself.

It's because the version of awk on my ARM platform is too old.
And after I updated it to version 4.2.0 , the RPC of kamailio works.
:)

**Comment by miconda** [comment]
Thanks for pointing out the solution.
