### ISSUE TITLE
Problem with transport=tcp and NATMANAGE

### ISSUE THREAD

**Issue by kelf47** [kamailio/kamailio#1439]
Hi! I'm working with kamailio and rtpproxy.
When I configure the clients to send sip messages through TCP adding the ";transport=tcp" in the sip message the rtpproxy is not working anymore. 

The code is never passing the point pasted below, inside route[NATMANAGE] in kamailio.cfg
```
if (!(isflagset(FLT_NATS) || isbflagset(FLB_NATB))) return;
```
Therefore,  ``` rtpproxy_manage("co");```  is never reached.

Could it be a parsing problem? ( ```check_route_param("nat=yes")``` )

Thanks!

**Comment by miconda** [comment]
This sounds more like a config issue, write `sr-users@lists.kamailio.org`mailing list  to describe your experience, eventually attach there your config as well as the sip traffic for such case (ngrep output or pcap).

This tracker has to be used when it is a clear issue in the code. Re-open later if it is the case, after the conclusion on the discussion about how your config file is used.

**Comment by kelf47** [comment]
The config file is exactly the same as the default one you provide in your repo.
