### ISSUE TITLE
dmq_usrloc: contacts not deleted while 0x04 flag set in save() function

### ISSUE THREAD

**Issue by gbour** [kamailio/kamailio#1445]
### Description

Hello,

kinda related to #265 ,
I can reproduce the issue, with kamailio 4.4.6+jessie from kamailio debian repository

- I have a pool of registrar servers, locations being replicated with dmq_usrloc
- 0x04 flag is set on save()
- old contacts are deleted on the server receiving the REGISTER message
- old contacts are not deleted on other servers being notified via DMQ
 

#### Reproduction

- Setup 2 servers with dmq & dmq_usrloc replication between each other, and both handling registrations
- Use 0x04 flag on save() function
- Register your softphones  on server1: registration is replicated on server2, contact is on both servers 
- Reregister (with different contact) on server2: 
  - previous contact is deleted on server2
  - new contact is replicated to server1
  - previous contact is *NOT* delete on server1

#### Log Messages

server2 (REGISTER message):

    DEBUG: usrloc [ucontact.c:1692]: update_ucontact(): exists callback for type= UL_CONTACT_UPDATE
    DEBUG: usrloc [ul_callback.h:84]: run_ul_callbacks(): contact=0x7f0096e0b548, callback type 2/15, id 0 entered
    DEBUG: dmq_usrloc [usrloc_sync.c:578]: dmq_ul_cb_contact(): Callback from usrloc with type=2
    DEBUG: dmq_usrloc [usrloc_sync.c:548]: usrloc_dmq_send_contact(): sending serialized data {"action":1,"aor":"+33564093848","ruid":"uloc-5a86b8c5-31e0-2","c":"sip:+33564093848@xxx:41502;ob","received":"","path":"","callid":"ntoWjs3R3WpP9Z5rsi7Npmr2rRGKstls","user_agent":"CSipSimple_porridge-23/r2457","instance":"","expires":1518779539,"cseq":55952,"flags":0,"cflags":0,"q":-1,"last_modified":1518778639,"methods":8159,"reg_id":0}
    DEBUG: dmq_usrloc [usrloc_sync.c:299]: usrloc_dmq_send(): sending dmq broadcast...

server1 (DMQ recipient):

    DEBUG: dmq_usrloc [usrloc_sync.c:327]: usrloc_dmq_handle_msg(): dmq message received from sip:usrloc@172.16.67.15:5060
    DEBUG: dmq_usrloc [usrloc_sync.c:429]: usrloc_dmq_handle_msg(): Received DMQ_UPDATE. Update contact info...
    DEBUG: dmq_usrloc [usrloc_sync.c:64]: add_contact(): aor: +33564093848
    DEBUG: dmq_usrloc [usrloc_sync.c:65]: add_contact(): ci->ruid: uloc-5a86b8c5-31e0-2
    DEBUG: dmq_usrloc [usrloc_sync.c:66]: add_contact(): aorhash: -1799456359
    DEBUG: dmq_usrloc [usrloc_sync.c:72]: add_contact(): Found contact
    DEBUG: usrloc [ucontact.c:1692]: update_ucontact(): exists callback for type= UL_CONTACT_UPDATE
    DEBUG: usrloc [ul_callback.h:84]: run_ul_callbacks(): contact=0x7f3900243bd0, callback type 2/15, id 0 entered
    DEBUG: dmq_usrloc [usrloc_sync.c:578]: dmq_ul_cb_contact(): Callback from usrloc with type=2
    DEBUG: dmq_usrloc [usrloc_sync.c:600]: dmq_ul_cb_contact(): Contact received from DMQ... skip
    DEBUG: usrloc [ucontact.c:1004]: db_update_ucontact_ruid(): ruid:uloc-5a86b8c5-31e0-2
    DEBUG: usrloc [ucontact.c:1133]: db_update_ucontact_ruid(): contact:sip:+33564093848@xxx:41502;ob
    DEBUG: dmq_usrloc [usrloc_sync.c:74]: add_contact(): Release record
    DEBUG: dmq_usrloc [usrloc_sync.c:76]: add_contact(): Unlock udomain

the recipient receive an UPDATE message only.
according to usrloc_sync.c:usrloc_dmq_handle_msg(), UPDATE message add the new contact only (execute add_contact()), but the other one is not deleted

and there is no DMQ_RM message generated from the emitter

 
### Additional Information

```
version: kamailio 4.4.6 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2
```

* **Operating System**:

```
3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
```

**Comment by gbour** [comment]
I finally found the delete event on server2 (generated by usrloc):
> DEBUG: usrloc [ul_callback.h:84]: run_ul_callbacks(): contact=0x7f87b6dd0de8, callback type 4/15, id 0 entered
> DEBUG: dmq_usrloc [usrloc_sync.c:578]: dmq_ul_cb_contact(): Callback from usrloc with type=4
> DEBUG: dmq_usrloc [usrloc_sync.c:600]: dmq_ul_cb_contact(): Contact received from DMQ... skip

I guess the problem comes from usrloc_sync.c, line 582:
> if (!(ptr->flags & FL_RPL)) [

My understanding is usrloc delete event is not propagated through DMQ if the contact was not not previously registered from the exact same server.
Why is it like that ?

**Comment by charlesrchance** [comment]
It looks like the new register has been received on server2 but the original one was received on server1 - therefore the presence of the FL_RPL flag is preventing the update from being replicated. This was intended behaviour at the time of 4.4.

As of b5f94a9 (currently only in 5.1 and above), FL_RPL has been removed and this behaviour modified so that updates made locally on any server are always replicated to others. Can you try with a later version and let me know if you still see the same?

**Comment by gbour** [comment]
thanks @charlesrchance. I'll check and let you know

**Comment by gbour** [comment]
Hello @charlesrchance. I confirm with kamailio 5.1, contact deletion is replicated also.
Could be useful to add a short notice on 4.4 documentation :)

Thanks for your help, and your very valuable module
