### ISSUE TITLE
rtpengine: add UDP/TLS/RTP/SAVP and UDP/TLS/RTP/SAVPF as valid transport protocols

### ISSUE THREAD

**Issue by jerzyptak** [kamailio/kamailio#1458]
### Description
UDP/TLS/RTP/SAVP and UDP/TLS/RTP/SAVPF should be recognised and handled as valid transport protocols, those should be used when DTLS is used for SRTP.

### Additional Information

```
version: kamailio 5.1.1 (x86_64/linux)
```

* **Operating System**:

```
Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Provide more details about you tried and what failed or you expected to happen. Attach relevant information such as log messages from kamailio and sip messages/sdp samples.

**Comment by jerzyptak** [comment]
For example calling from kamailio config file 
`rtpengine_answer("SDES-off ICE=remove trust-address replace-origin replace-session-connection UDP/TLS/RTP/SAVP");` will result in passing "UDP/TLS/RTP/SAVP" to rtpengine as an undefined flag instead of interpreting it as a valid transport protocol.
Relevant entry form rtpengine log:
`Feb 14 04:55:20 rtpengine[27464]: DEBUG: [ct5Atc9TLOVPwKPDYBHPdwDz@y94Z4s9yJ1MvK7XDiiI7vbC3]: Dump for 'answer' from 127.0.0.1:57578: { "sdp": "`
`		v=0`
`		o=- 3727601701 3727601702 IN IP4 10.10.1.145`
`		s=pjmedia`
`		c=IN IP4 162.253.31.67`
`		b=AS:1974`
`		t=0 0`
`		a=X-nat:0`
`		m=audio 18228 RTP/AVP 8 0 9 101`
`		c=IN IP4 162.253.31.67`
`		b=TIAS:64000`
`		a=rtcp:18229 IN IP4 162.253.31.67`
`		a=sendrecv`
`		a=rtpmap:9 G722/8000`
`		a=rtpmap:8 PCMA/8000`
`		a=rtpmap:0 PCMU/8000`
`		a=rtpmap:101 telephone-event/8000`
`		a=fmtp:101 0-15`
`		m=video 18344 RTP/AVP 99 34`
`		c=IN IP4 162.253.31.67`
`		b=TIAS:1800000`
`		a=rtcp:18345 IN IP4 162.253.31.67`
`		a=sendrecv`
`		a=rtpmap:34 H263/90000`
`		a=fmtp:34 CIF4=1;CIF=1;QCIF=1;SQCIF=1`
`		a=rtcp-fb:* nack pli`
`		a=rtcp-fb:* nack`
`		a=rtcp-fb:* ccm fir`
`		a=rtcp-fb:* ccm tmmbr`
`		a=rtpmap:99 H264/90000`
`		a=fmtp:99 profile-level-id=42001f; packetization-mode=1;max-br=1800`
`		m=text 0 RTP/AVP 105 102", `
`	"ICE": "remove", `
`	"flags": [ "SDES-off", "trust-address", "UDP/TLS/RTP/SAVP" ], `
`	"replace": [ "origin", "session-connection" ], `
`	"rtcp-mux": [ "demux" ], `
`	"call-id": "ct5Atc9TLOVPwKPDYBHPdwDz@y94Z4s9yJ1MvK7XDiiI7vbC3", `
`	"received-from": [ "IP4", "162.253.31.86" ], `
`	"from-tag": "g61LnUx6Lm5ZwUAp", `
`	"to-tag": "RCzLEby054b4GsK8OM5th2kArDosQ9N6", "command": "answer" `
`}`
`Feb 14 04:55:20 kammed-1-lv-103 rtpengine[27464]: WARNING: [ct5Atc9TLOVPwKPDYBHPdwDz@y94Z4s9yJ1MvK7XDiiI7vbC3]: Unknown flag encountered: 'UDP/TLS/RTP/SAVP' `

I know that rtpengine itself can correctly handle UDP/TLS/RTP/SAVP and UDP/TLS/RTP/SAVPF as long as kamailio rtpengine module passes them as transport protocol and not flags.

**Comment by jerzyptak** [comment]
I have created PR with a possible implementation.

**Comment by miconda** [comment]
PR was merged.
