### ISSUE TITLE
cfgutils: KEMI wrappers segfault as missing sip_msg_t* first argument

### ISSUE THREAD

**Issue by aalba6675** [kamailio/kamailio#1459]
### Description

Use KEMI cfgutils.lock() and cfgutils.unlock().

Expect native behaviour of lock() unlock().

Instead segfault.

### Troubleshooting
The KEMI wrappers do not have leading sip_msg_t* argument.

Wrapper for lock() is cfg_lock()

Prototype for cfg_lock() is static int cfg_lock(str *lkey). Notice the missing sig_msg_t * first argument.

#### Reproduction
Call cfgutils.lock() cfgutils.unlock() from scripting language

#### Debugging Data
#0  0x00007fdc6e7eff32 in core_case_hash (s1=0x7fdcb88ac1a0, s2=0x0, size=16) at ../../core/hashes.h:317
317                     v=(ch_icase(*p)<<24)+(ch_icase(p[1])<<16)+(ch_icase(p[2])<<8)

s1 is actually the sip_msg_t* not the lock key string.
*s1 can actually be deferenced as *(sip_msg_t\*) s1

### Possible Solutions
KEMI wrappers for cfgutils.c should include dummy sip_msg_t* argument.

Proposed fix:

```
static int cfg_lock(sip_msg_t* msg, str *lkey)
{
        return cfg_lock_helper(lkey, 0);
}

static int cfg_unlock(sip_msg_t* msg, str *lkey)
{
        return cfg_lock_helper(lkey, 1);
}
```
### Additional Information

  * 5.0 5.1 master - kamailio version

**Comment by aalba6675** [comment]
OMG @miconda  you are so fast. I just filed this ticket. Anyway the commits have fixed the issue in my testing. Thanks!

**Comment by miconda** [comment]
Thanks for the report, it was a quick one to fix :-)!
