### ISSUE TITLE
Add /var/run management to systemd script

### ISSUE THREAD

**Issue by udf2457** [kamailio/kamailio#1464]
Hi,

Would be nice if you could add `/var/run` management to the systemd script provided with the repo install.

You know, something along the lines of:
```
ExecStartPre=-/usr/bin/mkdir /var/run/kamailio
ExecStartPre=/usr/bin/chown -R kamailio:daemon /var/run/kamailio/
```

(`RuntimeDirectory`/`RuntimeDirectoryMode` might be an alternative syntax to consider... subject to support)

**Comment by aalba6675** [comment]
This should probably go into `/usr/lib/tmpfiles.d/kamailio.conf`. rtpproxy does this:
```
/cat /usr/lib/tmpfiles.d/rtpproxy.conf
d /var/run/rtpproxy 0755 rtpproxy rtpproxy
```

**Comment by miconda** [comment]
For which package specs? Debs, rpms?

**Comment by udf2457** [comment]
Well I am talking about systemd ;-)

http://download.opensuse.org/repositories/home:/kamailio:/v5.1.x-rpms/CentOS_7/

**Comment by miconda** [comment]
Well you were talking about systemd, that was clear, but there are also deb spec files and deb packages that include systemd options, it is not a single place and different people taking care of them.

In this case, maybe @sergey-safarov can check and see what can be done.

**Comment by udf2457** [comment]
@miconda Fair enough & thanks.

**Comment by linuxmaniac** [comment]
https://salsa.debian.org/pkg-voip-team/kamailio/blob/master/debian/kamailio.service

This is what I have in the Debian
```
# /var/run/kamailio in tmpfs
RuntimeDirectory=kamailio
RuntimeDirectoryMode=0750
```
relevant info https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837678

**Comment by sergey-safarov** [comment]
Hello @udf2457 
This folder `/var/run/kamailio` is created using [kamailio.tmpfiles](https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/obs/kamailio.tmpfiles) config and command [systemd-tmpfiles --create kamailio](https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/obs/kamailio.spec#L1121) durring installation and recreated by OS when server is restarted.

Could you clarify when you have issue. When rpm is installed or when server rebooted?

About folder `/var/run`. As I understand really you not want recreate this.

**Comment by udf2457** [comment]
The issue was noticed post-installation.  `/var/run/kamalio` was non-existent.

As for `/var/run` of course I meant `/var/run/kamailio` management.

**Comment by sergey-safarov** [comment]
[PR to master](https://github.com/kamailio/kamailio/pull/1469/files) is created
Later will create cherry-pick to 5.1 branch
In short time 5.1.2 rpm packages will be re created.

**Comment by sergey-safarov** [comment]
RPM files is recreated. I tested and now issue fixed.

**Comment by miconda** [comment]
@sergey-safarov thanks for prompt reaction and the patch!
