### ISSUE TITLE
KeepAlive Module

### ISSUE THREAD

**Issue by voztovoice** [kamailio/kamailio#1476]
Hello,

I'm using keepalive module with drouting module... the event route works fine:

```
NOTICE: <script>: Gateway up: OPTIONS sip:1.2.3.4
NOTICE: <script>: Gateway up: OPTIONS sip:5.6.7.8
```

but kamcmd command not:

`kamcmd keepalive.list`

```
foobar
42
foobar
42
{
        text: foobar
        number: 42
}
{
        list: {
                nn: 17
                nn: 22
        }
}
{
        uri: sip:1.2.3.4
        owner: drouting
        last checked: Wed Feb 21 11:20:12 2018
        last up: Wed Dec 31 19:00:00 1969
        last down: Wed Feb 21 11:20:13 2018
}
{
        uri: sip:5.6.7.8
        owner: drouting
        last checked: Wed Feb 21 11:20:12 2018
        last up: Wed Dec 31 19:00:00 1969
        last down: Wed Feb 21 11:20:12 2018
```

Thank you

Regards...

**Comment by miconda** [comment]
Maybe @gbour has some time to look at it soon, being the developer of keepalive module.

**Comment by gbour** [comment]
Hello @voztovoice 

This is some test code I forgot to remove.
I will clean it up this weekend. Which kamailio version are you using ?

**Comment by voztovoice** [comment]
Hello @gbour,
Kamailio version is 5.1.1
Regards

**Comment by gbour** [comment]
@miconda is it ok to backport the commit in 5.1 branch ?

**Comment by miconda** [comment]
@gbour, @voztovoice - can this be closed? I see a commit by @gbour referenced here.

**Comment by miconda** [comment]
@gbour - yes, it can be backported! I am closing this one.
