### ISSUE TITLE
IMC module doesn't know what to do with websocket based endpoints

### ISSUE THREAD

**Issue by donfanning** [kamailio/kamailio#148]
Got IMC working, able to create rooms/destroy rooms.  No output is fed back to the chat window.

When two people are in the same room, I can see it find the recipient list of the room, but then it calls TM for the next_hop which calls _dns_hash_find which then calls get_out_socket and that's where it all goes to pot...

IMC should just create a new SIP MESSAGE packet from the room or imc_manager and drop it into request route{} for it to route back to the destination.

**Comment by miconda** [comment]
You have to set the outbound proxy address to same server and you should get what you want:

  * http://kamailio.org/docs/modules/stable/modules/imc.html#idp18801640

**Comment by miconda** [comment]
I am going to close this issue due to no follow up after the last suggestion. If there is still an issue, re-open the item.
