### ISSUE TITLE
No OPTIONS packet was sent out when TCP transport was used

### ISSUE THREAD

**Issue by wavstudio** [kamailio/kamailio#1481]
I tested the NAT ping function with nathelp module,and i found that there was OPTIONS packet sent out when UDP transport was used, but if i change to TCP transport, no OPTIONS packet was sent out.

I read the document and seems ping packet was sent out only when UDP was used.
Am i right? How should i do for this issue if i make a mistake?

**Comment by miconda** [comment]
The nathelper module sends nat keepalive only for UDP contacts. It is how it was developed.

If you look for alternatives for TCP, write to sr-users@lists.kamailio.org, there might be some ideas to try to do in the config file. However, this is the tracker for bugs in the code, not discussions about using kamailio or building config files. So such discussion doesn't belong here.
