### ISSUE TITLE
kazoo: wrong BLF when used application/dialog-info+xml

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1489]
### Description

Yealink phones is subscribes using `application/dialog-info+xml`. In this case for many phones false reported `early` state. 

#### Reproduction

Not knows. Some phones is displayes properly, some is not.

#### Debugging Data

none

#### Log Messages

not yet done

#### SIP Traffic

In provided pcap. is subscribed two clients `yealink` phone and `x-lite` softphone.
Created call to extension 201 (sip login). For `x-lite` status is changed properly for `yealink` is not.
Filters
`udp.port==13322` caller leg
`udp.port==1025` callee legs
`udp.srcport==5060&&udp.dstport==5060` yealink phone
`udp.port==15502` xlite

[blf-test.pcap.gz](https://github.com/kamailio/kamailio/files/1849284/blf-test.pcap.gz)

packet 14 - kamailio reports 201 extension is Available to xlite
packet 25 - kamailio reports 201 is early to yealink (unexpected)
packet 108 - created call to 201 extension
packer 109 - ringing to caller
packet 118 - kamailio send ringing to caller
packet 119 - INVITE send to callee
packet 124 - callee send Trying
packet 127 - kamailio reports 201 is ringing to yalink
packet 129 - kamailio reports 201 is busy to xlite
packet 145 - kamailio send session progress to caller
packet 146 - callee send ringing
packet 154 - caller send cancel
packet 156 - kamailio send early to yealink (unexpected)
packet 156 - kamailio send Available to x-lite

### Possible Solutions

not known

### Additional Information

Kamailio installed from kazoo team repo

```
[root@kamailio01 ~]# kamailio -V
version: kamailio 5.0.3 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 11:07:05 Sep 23 2017 with gcc 4.8.5
[root@kamailio01 ~]# 
```

* **Operating System**:

```
[root@kamailio01 ~]# uname -a
Linux kamailio01.cloudpbx.ai.co.uk 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@kamailio01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@kamailio01 ~]# 
```

**Comment by lazedo** [comment]
@sergey-safarov this doesn't look like a kamailio issue. you may need to capture amqp packets from/to kamailio andalso look into kamailio logs. the items you're reporting as `unexpected` seem like an `expectation from user` rather than `unexpected because current state is ...`. what i mean is, the attached pcap is not enough to do an assessement of a possible issue that doesn't occur with other deployments of kamailio with kazoo.

**Comment by sergey-safarov** [comment]
@lazedo, I will create docker container using your repo and test on my servers

**Comment by sergey-safarov** [comment]
Hello Luis @lazedo
Kamailio and kazoo is updated
1) kamailio is kamailio-5.0.4j-3.1.x86_64 from your repo;
2) kazoo is 4.2.25 on alpine packaged to container.

I retake test and can see:
1) packet 2 received `INVITE`;
2) packet 27 send `early` to Yealink;
3) packet 28 send `busy` to X-Lite;
4) packet 112 send `ANSWER` to caller;
5) packet 121 send `early` to Yealink (unexpected);
6) packet 122 send `On the Phone` to X-Lite;
7) packet 185 received `BYE` from caller;
8) packet 196 send `early` to Yealink (unexpected);
9) packet 122 send `Available` to X-Lite.

Luis AMQP messages also captured in PCAP but i cannot read this. Could you look into pcap file
[test2- blf.pcap.gz](https://github.com/kamailio/kamailio/files/1987284/test2-.blf.pcap.gz)

**Comment by sergey-safarov** [comment]
Hello Luis @lazedo 
I found that kamailio is send BLF events to already disconnected Call-ID `bafd2f3d-d3a9-4c7d-be75-10fca3f358ca`.
Please looks packets 123, 125, 127, 196, 198.
And relevant CDR from kazoo
```
[root@node0 ~]# curl -s -S  'https://cust.ai.co.uk/v2/accounts/a9f80a9e89baec870641c904b45e8bdd/cdrs/201804-bafd2f3d-d3a9-4c7d-be75-10fca3f358ca'  -H 'X-Auth-Token: XXXXX' | jq -j '.data'
{
  "custom_channel_vars": {
    "account_id": "a9f80a9e89baec870641c904b45e8bdd",
    "authorizing_id": "dfa492e672c1c67d9c84d27415507a9f",
    "authorizing_type": "device",
    "bridge_id": "cad39f1f-be0f-1236-dba9-0242ac110006",
    "ecallmgr_node": "ecallmgr@kazoo-app02.cloudpbx.ai.co.uk",
    "inception": "442030263206@cust.ai.co.uk",
    "owner_id": "1ac8f140e6bf1662ca0c901a04e93b07",
    "realm": "ai.cust.ai.co.uk",
    "username": "user_x4a5hv"
  },
  "to": "201@ai.cust.ai.co.uk",
  "timestamp": 63691318804,
  "switch_url": "sip:mod_sofia@31.28.75.195:11000",
  "switch_uri": "sip:31.28.75.195:11000",
  "switch_nodename": "freeswitch@freeswitch01.cloudpbx.ai.co.uk",
  "ringing_seconds": "0",
  "request": "user_x4a5hv@ai.cust.ai.co.uk",
  "presence_id": "201@ai.cust.ai.co.uk",
  "other_leg_direction": "inbound",
  "other_leg_destination_number": "442030263206",
  "other_leg_caller_id_number": "03333444466",
  "other_leg_caller_id_name": "03333444466",
  "other_leg_call_id": "cad39f1f-be0f-1236-dba9-0242ac110006",
  "media_server": "freeswitch01.cloudpbx.ai.co.uk",
  "local_sdp": "v=0\r\no=FreeSWITCH 1524078566 1524078567 IN IP4 31.28.75.195\r\ns=FreeSWITCH\r\nc=IN IP4 31.28.75.195\r\nt=0 0\r\nm=audio 21038 RTP/AVP 0 101 13\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\na=rtcp:21039 IN IP4 31.28.75.195\r\na=rtpmap:13 CN/8000\r\na=ptime:20\r\na=sendrecv\r\n",
  "hangup_code": "sip:900",
  "hangup_cause": "NORMAL_UNSPECIFIED",
  "from": "03333444466@ai.cust.ai.co.uk",
  "duration_seconds": "0",
  "custom_sip_headers": {
    "x_kazoo_invite_format": "username",
    "x_kazoo_aor": "sip:user_x4a5hv@ai.cust.ai.co.uk"
  },
  "channel_state": "REPORTING",
  "channel_name": "sofia/sipinterface_1/user_x4a5hv@ai.cust.ai.co.uk",
  "channel_created_time": 1524099604028605,
  "channel_call_state": "HANGUP",
  "caller_id_number": "03333444466",
  "caller_id_name": "03333444466",
  "callee_id_number": "+442030263201",
  "callee_id_name": "Henry Merrett",
  "call_direction": "outbound",
  "billing_seconds": "0",
  "call_id": "bafd2f3d-d3a9-4c7d-be75-10fca3f358ca",
  "node": "ecallmgr@kazoo-app01.cloudpbx.ai.co.uk",
  "msg_id": "1524099604028605",
  "event_name": "CHANNEL_DESTROY",
  "event_category": "call_event",
  "app_version": "4.0.0",
  "app_name": "ecallmgr",
  "interaction_id": "63691318785-9b1a9e0e",
  "interaction_key": "9b1a9e0e",
  "interaction_time": 63691318785,
  "id": "201804-bafd2f3d-d3a9-4c7d-be75-10fca3f358ca"
}
```
This call is `outbound` (b-leg) and disconnected with error `NORMAL_UNSPECIFIED` finished about 3 weeks ago. Call `billing_seconds` and `duration_seconds` is 0.

As you can see in this pcap kamailio not get any events from `ecallmgr` related to Call-ID `bafd2f3d-d3a9-4c7d-be75-10fca3f358ca` this is mean dialog state is maintained inside kamailio.
I will try locate Call-ID `bafd2f3d-d3a9-4c7d-be75-10fca3f358ca` in sqlite dump file.

**Comment by sergey-safarov** [comment]
Luis I found that in `presentity` table dialog event is stored with `expires` equal 0.
Think if ecallmgr will set this value equal leg timeout then this will resolve this issue.

Could you also confirm that need add function to ecallmgr like `make_sure_dialog_is_removed_on_kamailio`?

**Comment by sergey-safarov** [comment]
As hot fix on kamailio hosts is created script
```
#!/bin/sh

DB_FILE=/etc/kazoo/kazoo-configs-kamailio/kamailio/db/kazoo.db

clean_dialogs() {
	local TIMESTAMP=$1
	sqlite3 $DB_FILE "update presentity SET expires=(received_time+900) where expires=0 and event='dialog' and instr(body, 'direction=\"recipient\"><state>early</state><local><identity display') > 0;"
}

TIMESTAMP=$(date +%s)
clean_dialogs "$TIMESTAMP"
exit 0
```
And added to `/etc/crontab` this record
```
0,15,30,45  *  *  *  * kamailio /usr/local/bin/clean_blf.sh
```

**Comment by lazedo** [comment]
@sergey-safarov hi, what you're reporting has nothing to do with kamailio & kazoo module. i'm closing this here.
