### ISSUE TITLE
UAC module - registration not retried if there is no response to request 

### ISSUE THREAD

**Issue by AndyJRobinson** [kamailio/kamailio#149]
Please refer to closed issue #124.

Problem not solved... still seeing "stuck" registrations. Note that in this case, I'm not getting a timeout response back from the UAS. The case where I'm seeing the issue is when the UAS never responds at all.

I don't think adding the line to reset UAC_REG_ONGOING and UAC_REG_AUTHSENT at the error: label really changed anything, since the done: label, which immediately follows it, already reset those flags (and would be executed on the goto error).

**Comment by miconda** [comment]
Indeed, the flag would be reset via done label, I overlooked there is no return for error label.

The same callback should be called when there is a local timeout. Do you get in the logs an error message like:

```
... got sip response 408 while registering ...
```

**Comment by AndyJRobinson** [comment]
In order to reproduce the issue, I added a firewall rule to drop the response from the UAS. I saw the 'got sip response 408 while registering' message in the log and the flags were reset, so there must be some other rare condition which is causing the flags to get stuck in UAC_REG_ONGOING. This seems to occur once every few days (with registration being done approximately every 60 to 90 seconds),  and even sometimes up to a week before I've seen the problem reoccur. I'll try to catch the next occurrence, and see what information is in the log when it occurs.

**Comment by miconda** [comment]
Can you check if you had any error related to shared memory, like "no more shm"?

I found a place where the flag was set and error with shm allocation would have left it set. I pushed a patch for it in master branch.

**Comment by AndyJRobinson** [comment]
I didn't save a copy of the logs from the last occurrence. I've been
waiting for the issue to occur again so I can gather more information, but,
of course, now that I want it to happen, it hasn't occurred over the last 5
days. I'll keep monitoring it and reply once it finally does occur again.

**Comment by miconda** [comment]
Closing this one for the moment, re-open if it appears again and you have more details.
