### ISSUE TITLE
Can't load tm.so when built from master

### ISSUE THREAD

**Issue by kmduk** [kamailio/kamailio#1517]
ERROR: <core> [core/sr_module.c:582]: load_module(): could not open module </usr/local/lib64/kamailio/modules/tm.so>: /usr/local/lib64/kamailio/modules/tm.so: undefined symbol: w_t_reply_wrp

Looks like the function was removed in commit a6c3b35dde900c718d8d010b0b8094b384b890d8

**Comment by miconda** [comment]
Thanks! I missed that the function was still needed. I just re-added it in a simplified version.
