### ISSUE TITLE
log_prefix do not work in failure_route

### ISSUE THREAD

**Issue by os11k** [kamailio/kamailio#1531]
### Description

log_prefix do not work in failure_route

#### Reproduction
log_prefix="{$mt $hdr(CSeq) $ci} "

...
...

failure_route[RTF_LCR_ROUTE]
{
        if (t_is_canceled()) {
                exit;
        }

        xlog("L_INFO", "--- SCRIPT: failure_route - RTF_LCR_ROUTE\n");
        if (t_check_status("408|50[0-4]") or (t_branch_timeout() and !t_branch_replied())) {
                if(!next_gw()) {
                        send_reply("503", "No more LCR gateways");
                        exit;
                }

                xlog("L_INFO", "flag $avp(lcr_flag) \n");
                t_on_failure("RTF_LCR_ROUTE");
                t_set_retr(0, 4000);
                route(RELAY);
                exit;
        }
}

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
INFO: <script>: --- SCRIPT: failure_route - RTF_LCR_ROUTE
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 4.4.7 (x86_64/linux) 35d8ab
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 35d8ab
compiled on 11:55:20 Mar 19 2018 with gcc 6.3.0
```

* **Operating System**:

```
Linux kamailio 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 GNU/Linux

```

**Comment by os11k** [comment]
Hi Daniel!

I tried on Master and seems issue is fixed now.

`{1 123247829 INVITE a8ea8408-0ced-49f6-945b-aef6ae3c66a7} 17(22) INFO: <script>: --- SCRIPT: failure_route - RTF_LCR_ROUTE`

Do you plan to backport to 4.4 version?

**Comment by miconda** [comment]
The 4.4 series are out of maintenance. You can backport in your local branch.

The patch was backported to 5.1 and it will be to 5.0.
