### ISSUE TITLE
sanity: Mistakes in the documentation article.

### ISSUE THREAD

**Issue by tiglat** [kamailio/kamailio#1542]
### Description

Wrong information in the documentation.
1. Default value of the parameter default_checks is 2791. In the documentation it is said that default is 999.
2. One check is not described - SANITY_CHECK_DUPTAGS. 

It was found in the version 4.4.7.

**Comment by miconda** [comment]
Looking at the codem I got the value 3047 for default_checks -- have I computed it wrong? I pushed a patch for it. SANITY_CHECK_DUPTAGS was already documented in the master branch, not sure about 4.4.x.
