### ISSUE TITLE
sanity: Doesn't sent reply when some checks are failed.

### ISSUE THREAD

**Issue by tiglat** [kamailio/kamailio#1543]
### Description

According the documentation the module will send reply if one of the checks is failed.
However it doesn't send reply if digest credentials, duplicated To/From tags or authorization header checks are failed.
I would like to propose to add a new parameter which will enable or disable auto sending of reply.

#### Reproduction

Send to kamailio request with empty nonce in Authorization header.

### Possible Solutions

Set autodrop to 0 and send the reply from configuration file. But in some cases this reply will be sent twice from module and from config.

### Additional Information

 kamailio version 4.4.7 and the latest 5.x

**Comment by tiglat** [comment]
I would like to update the information. In fact reply is sent rarely in case of  to all checks. Probably it would be better to remove sending reply from the module at all. It could be easily done from a config script.

**Comment by henningw** [comment]
Just an remark to your request: I noticed that the sanity module can't send a reply if the necessary header (e.g. To) to actually construct a reply are not present or corrupt. In this case sending a reply from the cfg will probably also not work.

**Comment by tiglat** [comment]
Thank for explanation. You are right.

**Comment by miconda** [comment]
Pushed some commits to master branch, among changes is also sending reply for the checks you mentioned above.

If you can test the master branch and report the results, it would be appreciated. If all ok, it will be backported.

**Comment by tiglat** [comment]
Will test in few days.

**Comment by miconda** [comment]
@tiglat ok, thanks! Reopen this ticket if it is same issue or open a new one if is something different. I am saying this because I just pushed more commits to sanity module, so it could be something else.
