### ISSUE TITLE
TLS module: different TLS parameters based on domain names for server role

### ISSUE THREAD

**Issue by VolodyaIvanets** [kamailio/kamailio#1570]
Sorry for not being specific in [#1567](https://github.com/kamailio/kamailio/issues/1567). I had to clarify that I was talking about server role only.

From what I understood server role configurations can be distinguish one from another only by socket, provided in their configuration. TLS module documentation says: 

> "... different TLS parameters can be specified on a per role (server or client) and domain basis (for now only IPs)".

Which hints that additional tests for matching incoming connections against configured server profiles were in mind. I would like to request a feature which could allow matching them against domain name if that's possible.

One of the options may be checking client's certificate CN if _require_certificate_ parameter is set to yes.

Thank you!

**Comment by miconda** [comment]
`server_name` is matched for servers, have you tried? If yes and not matching, reopen and attach all debug/log messages printed by kamailio with debug=3 in kamailio.cfg.

I will look at the docs and update where it is the case, if you search for server_name, there are notes that it is matched, but some parts might be outdated in this aspect.
