### ISSUE TITLE
continuously memory getting increases with app_lua

### ISSUE THREAD

**Issue by SurendraPlivo** [kamailio/kamailio#1575]
### Description

main memory continuously getting increases. used lua routing. 

#### Reproduction

load app_lua with kamailio route file. route file should load other lua module or custom modules

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.3 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 11:06:51 May 10 2018 with gcc 4.8.4
```

* **Operating System**:

```
Linux ip-172-31-4-160 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Making a report without relevant information is useless. Can you actually add proper details about the issue you are facing? What are those modules you are using? What kind of sip traffic you process? Is it system memory or kamailio pkg/shm memory?

**Comment by SurendraPlivo** [comment]
hey sorry did it in bit hurry. adding other information
