### ISSUE TITLE
re.subst cannot process sdp content-length of 2978

### ISSUE THREAD

**Issue by adil-mafzool** [kamailio/kamailio#1592]
While trying the following code with sdp content-length of 2978 : -
$var(telephone-event) = $(avp(sdp){re.subst,/.*a=rtpmap:([0-9]+) telephone-event.*/\1/s});

kamailio -v
version: kamailio 5.1.4 (x86_64/linux)

got the following errors: -
ERROR: textops [txt_var.c:80]: tr_txt_eval_re(): PV value too big 2978, increase buffer size
ERROR: <core> [core/lvalue.c:346]: lval_pvar_assign(): non existing right pvar
ERROR: <core> [core/lvalue.c:404]: lval_assign(): assignment failed at pos: (424,27-424,91)
ERROR: <script>: telephone-event: 0

This is due to the fixed size of 2048 modules/textops/txt_var.c at line 48 : - 

'''#define TR_TXT_BUF_SIZE	2048
	static char tr_txt_buf[TR_TXT_BUF_SIZE];'''

Please can anybody check..

**Comment by miconda** [comment]
I incremented the size of the buffer to 8196, the old value of 2048 being rather small for dealing with sip messages. In the future, this might be changed to allocated memory at startup based on pv buffer size.

However, in case of dealing with larger values, there are couple of options:

  * navigate line by line in sdp:

```
$var(lc) = $(rb{line.count});
$var(i) = 0;
while($var(i)<$var(lc)) {
  $var(line) = $(rb{line.at,$var(i)});
  # do you re here on $var(line) ...

  $var(i) = $var(i) + 1;
}
```
  * split operation on parts of the value:

```
$var(halflen) = $(rb{s.len}) / 2;
$var(firsthalf) = $(rb{s.substr,0,$var(halflen)});
$var(secondhalf) = $(rb{s.substr,$var(halflen),0});
```
This may have the risk of splitting on the line you want to match, but could be useful for other cases.

  * use an embedded interpreter, for example app_jsdk or app_sqlang have no external dependencies, but you can use also app_lua, app_python, ...

**Comment by adil-mafzool** [comment]
thanks Daniel!!
