### ISSUE TITLE
Module RTPPROXY param Timeout_Socket not Working

### ISSUE THREAD

**Issue by hamidrhashmi** [kamailio/kamailio#1597]
Kamailio didn't start listening on IP mentioned in Module RTPPROXY parameter [Timeout_Socket](https://kamailio.org/docs/modules/5.1.x/modules/rtpproxy.html#rtpproxy.p.timeout_socket). 

Below is my configuration file. 
```
loadmodule "rtpproxy.so"
modparam("rtpproxy", "rtpproxy_sock", "udp:127.0.0.1:7722")
modparam("rtpproxy", "rtpproxy_tout", 1)
modparam("rtpproxy", "rtpproxy_retr", 2)
modparam("rtpproxy", "timeout_socket", "tcp:127.0.0.1:7725")
```
when I type a commmand on linux 

```$ netstat -nlp```

it only shows SIP listening ports. Kamailio should start listening on ```tcp:1270.0.01:7725```

**Comment by miconda** [comment]
Kamailio should not start listening on the socket if timeout_socket param is set. As explained in the documentation, the value is passed to rtpproxy application, that's all done by rtpproxy module in kamailio.

At that socket can be kamailio if you provide an xmlrpc url (see the docs) and use xmlrpc module, or any other application that you may develop.

If you want to discuss more about, the right place is the sr-users@lists.kamailio.org mailing list.

**Comment by hamidrhashmi** [comment]
@miconda 
I tried with xmlrpc and took wireshark traces. 
```
#!ifdef WITH_NAT
# ----- rtpproxy params -----
modparam("rtpproxy", "rtpproxy_sock", "udp:127.0.0.1:7722")
modparam("rtpproxy", "timeout_socket", "xmlrpc:http://192.168.8.103:5060/RPC2")
```

![image](https://user-images.githubusercontent.com/14875110/44772975-c7c0bf80-ab88-11e8-841f-223e76c65875.png)

you can see that there is timeout information in the request

![image](https://user-images.githubusercontent.com/14875110/44773072-08b8d400-ab89-11e8-9e9d-8ee4a93c1835.png)

**Comment by hamidrhashmi** [comment]
@miconda Can you please comment on this.
