### ISSUE TITLE
add quotes on column names on MYSQL generated script files

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#160]
In order to avoid problems with reserved words We should quote the column names for auto-generated MySQL script files

Related to #159

**Comment by miconda** [comment]
I pushed several patches to fix sql scripts used to create database tables as well as the C code to quote table and column names.

@adombrovsky - would be good if you can test and report the results with latest master branch.

**Comment by adombrovsky** [comment]
@miconda  i will test it asap and report whether the issue is fixed or not

**Comment by adombrovsky** [comment]
Everything works fine. Thanks for the fast response
