### ISSUE TITLE
Broken Kamailio repository for CentOS 7

### ISSUE THREAD

**Issue by pwakano** [kamailio/kamailio#1604]
### Description

Centos RPM repo is generating Kamailio 5.0.7 packages that can't be installed

#### Reproduction

By using the repo 
https://download.opensuse.org/repositories/home:/kamailio:/v5.0.x-rpms/CentOS_7/home:kamailio:v5.0.x-rpms.repo
when trying to install Kamailio 5.0.7, yum returns this error:
```
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
kamailio-5.0.7-3.el7.centos.x8 FAILED                                          
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-5.0.7-3.el7.centos.x86_64.rpm: [Errno 14] HTTP Error 416 - Requested Range Not Satisfiable
Trying other mirror.
```

### Additional Information

* **Operating System**:

```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

**Comment by isaacpz** [comment]
+1

**Comment by gxovano** [comment]
+1

**Comment by sergey-safarov** [comment]
Hello Daniel @miconda 
I can handle this task. I can write script and implement others required staff.

I think more elegant solution is create repo server using [`pulp`](https://pulpproject.org/).
And deliver latest stable repo for CentOS via [keycdn](https://www.keycdn.com/).  KeyCDN offers sponsoring for open source projects.

All is need for me - server or virtual machine for this.

**Comment by pwakano** [comment]
Hello @sergey-safarov  and @miconda,
Was this task done?
Just tried today and the installation from the opensuse repo is not working....
Running the "clean metadata" does not solve the problem.....
Patrick Wakano
`Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
kamailio-auth-ephemeral-5.0.7- FAILED                                                      4% [===-                                                                            ]  0.0 B/s | 464 kB  --:--:-- ETA 
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-auth-ephemeral-5.0.7-7.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
`

**Comment by sergey-safarov** [comment]
Hello @pwakano
Think this is not started.
As workaround i have triggered rebuild for `5.0` branch.

**Comment by kamailio-sync** [comment]
Thanks Sergey!
I just tested and now it worked!
I don't know about the OBS, but is there a scheduled job that creates a new
package release version even tough the Kamailio version hasn't changed?
Since now this package works fine, can't we keep it like this and avoid
creating new packages?

Kind regards,
Patrick Wakano

**Comment by sergey-safarov** [comment]
Think we cannot. OBS servers is permanently is changed and think servers cannot store long time files.
Servers is outside of our control (but we can use this servers)

**Comment by kamailio-sync** [comment]
That's alright Sergey...
Thanks for the support!
Patrick Wakano

**Comment by sergey-safarov** [comment]
@kamailio-sync as suggested before need to define place where rpm repo will be stored.
I suggest to use [pulp](https://pulpproject.org/) and [keycdn](https://www.keycdn.com/) as `rpm` and `deb`  delivery method.

**Comment by miconda** [comment]
Closing this one, it was an OBS issue, in time we may build our own servers, but that is now a code issue to keep it here.
