### ISSUE TITLE
cancel_branch("this") not working

### ISSUE THREAD

**Issue by arheops** [kamailio/kamailio#1620]
Need add 
_tmx_tmb.prepare_to_cancel(t, &cancel_data.cancel_bitmap, 0);

into function static int t_cancel_branches_helper(sip_msg_t* msg, int n)

at case of 2( "this")

proposed changes:
```

                case 2:
                        /* prepare cancel for current branch (idx) */
                        if(msg->first_line.u.reply.statuscode>=200)
                                break;
                        cancel_data.cancel_bitmap = 1<<idx;
+                        _tmx_tmb.prepare_to_cancel(t, &cancel_data.cancel_bitmap, 0);
                        break;
```

### Additional Information

kamailio version 4.* to 5.*

```
```

Without this it can't cancel "this" transaction.

Rare case due to low use of "this".

**Comment by henningw** [comment]
Hello,
thank you for the report. I have applied your change to the git master and also will back-port it to 5.0 and 5.1 branches. It would be great if you could submit eventual further changes as git pull request, this makes it much easier to review and apply.
Best regards,
Henning
