### ISSUE TITLE
debian pkg missing dependency on docbook2x

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#1624]
Kamailio master build on Debian Stretch fails due to missing dependency on docbook2x.  See https://lists.kamailio.org//pipermail/sr-dev/2018-August/047549.html for more info.

**Comment by linuxmaniac** [comment]
We have no problems with the nightly builds, example:
https://kamailio.sipwise.com/job/kamailiodev-nightly-binaries/architecture=amd64,distribution=stretch,label=slave/1171/consoleText

**Comment by juha-h** [comment]
Victor Seva writes:

> We have no problems with the nightly builds, example:
> https://kamailio.sipwise.com/job/kamailiodev-nightly-binaries/architecture=amd64,distribution=stretch,label=slave/1171/consoleText

For sure you have.  Exactly the same problem that I described:

mkdir -p /tmp/buildd/kamailio-5.2.0~dev6+0~20180823005931.1186+stretch/debian/kamailio/usr/share/man//man5
s ../../../doc/stylesheets/serdoc2man.xsl auth.xml
make[3]: s: Command not found
../../Makefile.modules:283: recipe for target 'auth.7' failed
make[3]: [auth.7] Error 127 (ignored)
s ../../../doc/stylesheets/serdoc2man.xsl avp.xml
make[3]: s: Command not found
../../Makefile.modules:283: recipe for target 'avp.7' failed
make[3]: [avp.7] Error 127 (ignored)

**Comment by juha-h** [comment]
This clearly is a bug.  I don't understand why bug label was removed. Also, I my opinion this kind of error should not be ignored, but build should stop at it.

**Comment by miconda** [comment]
Overall this is not actually deb build specific issue, but something that happens during install, as I could spot during building and installing using git repo inside a docker container (for kamailio unit tests). I guess that was more an optional step, attempting to build man pages from docbooks for modules readmes.

I think this should be made optional properly. I do not think anyone was using manpage-style docs so far for modules and starting now to install/package them all makes no sense.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> I think this should be made optional properly. I do not think anyone
> was using manpage-style docs so far for modules and starting now to
> install/package them all makes no sense.

Optional is fine with me.  I just want the build to work without
errors.   Also, if an error occurs, the build must stop,  This is not
the case now.

-- Juha

**Comment by miconda** [comment]
Pushed a patch to catch when the tool from docbook to mack conversion is not available and just print an info message. I think this should do it for now, if one wants to start generating man pages, can do it by installing the tool.

I will close this issue and if one wants to package man pages for modules' readme, open a feature request. To my knowledge, so far they were never packaged. If some new issues after the patch, just reopen.

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> I will close this issue and if one wants to package man pages for
> modules' readme, open a feature request. To my knowledge, so far they
> were never packaged. If some new issues after the patch, just reopen.

Thanks, debian package now built OK without docbook2x.

-- Juha
