### ISSUE TITLE
passing argument to event_callback function 

### ISSUE THREAD

**Issue by SurendraPlivo** [kamailio/kamailio#1627]
### Description

Right Now, There is no way to pass the parameter to event_callback function to be executed by KEMI Interpreter.

This is required when we have to pass call_uuid for async call without suspending transaction. In callback we don't have anything refer to the previous transaction.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

We need to introduce parameter to event_callback with ;
Initially let's keep it to only single parameter.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
root@ip-172-31-3-45:~# kamailio -v
version: kamailio 5.1.3 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 15:16:50 Apr 24 2018 with gcc 4.8.4
```

* **Operating System**:

```
root@ip-172-31-3-45:~# uname -a
Linux ip-172-31-3-45 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
I do not really get what you need or what to achieve here?

Can you give an example with native kamailio.cfg `event_route[...]` that needs to be covered by what you try to ask here?
