### ISSUE TITLE
Feature request: Wanted support of Content-ID in append_body_part

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1632]
### Description
According [RFC6442](https://tools.ietf.org/html/rfc6442#section-5.1) multipart body may contain payload with `Content-ID` header.
Now `append_body_part` support only `Content-Disposition` optional header and not supports `Content-ID`.

Wanted `Content-ID` to implement RFC6442

**Comment by sergey-safarov** [comment]
I have test construction
```
append_body_part("<?xml version=\"1.0\" encoding=\"UTF-8\"?><root/>", "application/pidf+xml\r\nContent-ID: <target123@atlanta.example.com>");
```
This works for me. Also `Content-Disposition` header not generated as not wanted header.

We can close this ticket.
Or need to leave this open?

**Comment by sergey-safarov** [comment]
Kamailio now works but i can see in logs
```
135(139) CRITICAL: <core> [core/mem/q_malloc.c:502]: qm_free(): BUG: freeing already freed pointer (0x7f6b2991e638), called from core: core/data_lump.c: free_duped_lump_list(625), first free core: core/data_lump.c: free_lump_list(504) - aborting
```

**Comment by miconda** [comment]
The above solution should be good for now. I added a note in the docs about using this mechanism to add additional headers in a body part. If someone wants to add a different function, then it can be done separately. Closing it.
