### ISSUE TITLE
Bug in tls #1491

### ISSUE THREAD

**Issue by prabhat2k15** [kamailio/kamailio#1635]
Kamailio version 5.1
ubuntu os 16.04
i have installed all the dependencies.

when i am starting kamailio service i get this error

 sudo service kamailio status

● kamailio.service - LSB: Start the Kamailio SIP proxy server
   Loaded: loaded (/etc/init.d/kamailio; bad; vendor preset: enabled)
   Active: active (exited) since Wed 2018-09-05 12:40:48 UTC; 12min ago
     Docs: man:systemd-sysv-generator(8)

Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: WARNING: tls [tls_init.c:778]: init_tls_h(): **openssl bug #1491 (crash/mem leaks on low memory)** wo
Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: INFO: <core> [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold1 has been changed to 
Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: INFO: <core> [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold2 has been changed to 
Sep 05 12:40:48 ip-10-0-0-45 kamailio[2532]:  *  already running
Sep 05 12:40:48 ip-10-0-0-45 kamailio[2532]:    ...done.
Sep 05 12:40:48 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
Sep 05 12:43:35 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
Sep 05 12:43:50 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
Sep 05 12:44:28 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
Sep 05 12:48:39 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.

**Comment by echohes** [comment]
problem in  - crash/mem leaks on low memory


>Среда,  5 сентября 2018, 15:56 +03:00 от Prabhat Kumar <notifications@github.com>:
>
>Kamailio version 5.1
>ubuntu os 16.04
>i have installed all the dependencies.
>when i am starting kamailio service i get this error
>sudo service kamailio status
>● kamailio.service - LSB: Start the Kamailio SIP proxy server
>Loaded: loaded (/etc/init.d/kamailio; bad; vendor preset: enabled)
>Active: active (exited) since Wed 2018-09-05 12:40:48 UTC; 12min ago
>Docs: man:systemd-sysv-generator(8)
>Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: WARNING: tls [tls_init.c:778]: init_tls_h():  openssl bug  #1491 (crash/mem leaks on low memory) wo
>Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: INFO:  [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold1 has been changed to
>Sep 05 12:40:48 ip-10-0-0-45 /usr/local/sbin/kamailio[2553]: INFO:  [core/cfg/cfg_ctx.c:595]: cfg_set_now(): tls.low_mem_threshold2 has been changed to
>Sep 05 12:40:48 ip-10-0-0-45 kamailio[2532]:  *  already running
>Sep 05 12:40:48 ip-10-0-0-45 kamailio[2532]:    ...done.
>Sep 05 12:40:48 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
>Sep 05 12:43:35 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
>Sep 05 12:43:50 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
>Sep 05 12:44:28 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
>Sep 05 12:48:39 ip-10-0-0-45 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

------------------
С уважением Вадим Гайсин

**Comment by echohes** [comment]
how much RAM,  in your system?

**Comment by prabhat2k15** [comment]
1GB

**Comment by echohes** [comment]
You need to check the startup parameters of Kamailio:
SHM_MEMORY and PKG_MEMORY

**Comment by echohes** [comment]
And check yor RAM
`free -h`

**Comment by miconda** [comment]
This is just a warning to say that a protection against a crash due to an issue on low memory in an old libssl version has been activated. To increase the shared memory used by kamailio use `-m` parameter, e.g., start wit 256MB of memory: `kamailio -m 256 ...`.

Overall, this is not a bug in kamailio, just a warning about a workaround for a bug in libssl. If you want to discuss more, then send an email to sr-users mailing list.
