### ISSUE TITLE
How to config kamailio as pcscf with out RTP engine? like openimscore pcscf?

### ISSUE THREAD

**Issue by leechul** [kamailio/kamailio#1643]
### Description
How to config kamailio as pcscf with out RTP engine? like openimscore pcscf?

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Github issues is not used for how to use kamailio. Send your questions via email to sr-users@lists.kamailio.org mailing list.
