### ISSUE TITLE
ims_usrloc_scscf module lacks module documentation

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#1644]
The ims_usrloc_scscf module lacks module documentation in git master:

~/repositories/kamailio/src/modules/ims_usrloc_scscf> ls -la README doc*   
ls: cannot access 'README': No such file or directory
ls: cannot access 'doc*': No such file or directory

The purpose of this module and also its parameters that are exported should be documented in a doc/*.xml files like the other modules. This are the exported parameters from the source code:

    {"timer_interval",      INT_PARAM, &timer_interval  },
        {"desc_time_order",     INT_PARAM, &desc_time_order },
        {"matching_mode",       INT_PARAM, &matching_mode   },
        {"cseq_delay",          INT_PARAM, &cseq_delay      },
        {"fetch_rows",          INT_PARAM, &ul_fetch_rows   },
        {"hash_size",           INT_PARAM, &ul_hash_size    },
        {"subs_hash_size",      INT_PARAM, &subs_hash_size  },
        {"contacts_hash_size",  INT_PARAM, &contacts_hash_size  },
        {"nat_bflag",           INT_PARAM, &nat_bflag       },
        {"contact_delete_delay", INT_PARAM, &contact_delete_delay       },
        {"usrloc_debug_file",   PARAM_STR, &usrloc_debug_file},
        {"enable_debug_file",   INT_PARAM, &usrloc_debug},
    {"user_data_dtd",           PARAM_STRING, &scscf_user_data_dtd},
    {"user_data_xsd",           PARAM_STRING, &scscf_user_data_xsd},
    {"support_wildcardPSI",     INT_PARAM, &scscf_support_wildcardPSI},
    {"unreg_validity",          INT_PARAM, &unreg_validity},
    {"maxcontact_behaviour",INT_PARAM, &maxcontact_behaviour},
    {"maxcontact",                      INT_PARAM, &maxcontact},
        {"maxcontact_3gpp",     INT_PARAM, &maxcontact_3gpp},
        {"max_subscribes",              INT_PARAM, &max_subscribes},
    {"sub_dialog_hash_size",INT_PARAM, &sub_dialog_hash_size},
    {"db_mode",                         INT_PARAM, &db_mode},
    {"db_url",                          PARAM_STR, &db_url},
    {"timer_procs",             INT_PARAM, &ul_timer_procs},

**Comment by pan-christensen** [comment]
This undocumented module is required by both IMS_ISC and IMS_REGISTRAR_SCSCF modules.

**Comment by henningw** [comment]
Fixed in upstream with pull-request #1835

**Comment by VolodyaIvanets** [comment]
Branch **5.2** now has README file missing in ims_usrloc_scscf module.

This causes _kamailio-ims_ package built to fail:
```
Processing files: kamailio-ims-5.2.4-1.el6.x86_64
error: File not found: /builddir/build/BUILDROOT/kamailio-5.2.4-1.el6.x86_64/usr/share/doc/kamailio/modules/README.ims_usrloc_scscf

RPM build errors:
    File not found: /builddir/build/BUILDROOT/kamailio-5.2.4-1.el6.x86_64/usr/share/doc/kamailio/modules/README.ims_usrloc_scscf
```

**Comment by henningw** [comment]
You are right. Unfortunately it was not backported after the merge in the referenced ticket. I did it just now for 5.1 branch and 5.2 branch.
