### ISSUE TITLE
when using terminate_dlg via xmlrpc, not able to generate proper bye message, if request is behind nat.

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1689]
### Description

Using xmlrpc command to generate the bye using terminate_dlg request:

#### Reproduction

use xmlrpc request to terminate the dialog
```
curl --data @xmlrpc http://13.57.122.212:8080/RPC
```
xmlrpc file will have following things
```
<?xml version="1.0"?>
<methodCall>
<methodName>dlg.terminate_dlg</methodName>
<params>
<param><value><string>fe6361a2-52f0-1237-e5a2-06119108e458</string></value></param>
<param><value><string>07322vj6a8taa</string></value></param>
<param><value><string>gK09f669d8</string></value></param>
</params>
</methodCall>
```

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
**Bye message without xmlrpc**
BYE sip:gw+plivo.com@13.57.90.158:5080;transport=tcp;transport=tcp;gw=plivo.com;alias=13.57.90.158~49325~2 SIP/2.0.
Record-Route: <sip:13.57.122.212;lr;ftag=gK07d4ffc2>.
Record-Route: <sip:18.214.109.132:5060;lr;ftag=gK07d4ffc2>.
Via: SIP/2.0/UDP 13.57.122.212:5060;branch=z9hG4bK154c.8fa2a8729a68989c41230f0906bcd2bd.0.
Via: SIP/2.0/UDP 18.214.109.132:5060;rport=5060;branch=z9hG4bK154c.44759fe4.0.
Via: SIP/2.0/UDP 81.52.176.68:5060;branch=z9hG4bK07Badb05d2bebab0ac9.
From: <sip:+919967609476@81.52.176.68>;tag=gK07d4ffc2.
To: "919967609476" <sip:+919967609476@54.183.206.134>;tag=5SDBNUapcZv5m.
Call-ID: 237f21f0-52db-1237-e5a2-06119108e458.
CSeq: 29061 BYE.
Max-Forwards: 68.
Route: <sip:54.183.206.134:5060;r2=on;lr;ftag=5SDBNUapcZv5m;nat=yes>.
Route: <sip:54.183.206.134:5060;transport=tcp;r2=on;lr;ftag=5SDBNUapcZv5m;nat=yes>.
Reason: Q.850;cause=16.
Content-Length: 0.
.

**Bye message using xmlrpc request**
U 172.31.4.160:5060 -> 54.183.206.134:5060
BYE sip:gw+plivo.com@13.57.90.158:5080;transport=tcp;transport=tcp;gw=plivo.com SIP/2.0.
Via: SIP/2.0/UDP 13.57.122.212:5060;branch=z9hG4bK7841.79765615000000000000000000000000.0.
To: <sip:suren1002170622114516@54.183.206.134>;tag=Hv494Z9D8D9rH.
From: <sip:919967609476@54.183.206.134>;tag=gK0cf13bdd.
CSeq: 1 BYE.
Call-ID: 56783745-52ef-1237-e5a2-06119108e458.
Route: <sip:54.183.206.134:5060;r2=on;lr;ftag=Hv494Z9D8D9rH;nat=yes>, <sip:54.183.206.134;transport=tcp;r2=on;lr;ftag=Hv494Z9D8D9rH;nat=yes>.
Content-Length: 0.
User-Agent: kamailio (5.1.4 (x86_64/linux)).
Max-Forwards: 70.
.
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
root@ip-172-31-4-160:/etc/kamailio# kamailio -version
version: kamailio 5.1.4 (x86_64/linux) 6ebfda
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 6ebfda 
compiled on 11:48:26 Sep  7 2018 with gcc 4.8.4
```

* **Operating System**:

```
root@ip-172-31-4-160:/etc/kamailio# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

root@ip-172-31-4-160:/etc/kamailio# uname -a
Linux ip-172-31-4-160 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Can you reproduce the scenario and look into the dialog structure for such call, either with a rpc command or in the database dialog table, and see what are the values for contact fields?

**Comment by SurendraPlivo** [comment]
yes, i can reproduce this again. for sure , i will paste the dialog structure here.

**Comment by SurendraPlivo** [comment]
<?xml version="1.0"?>
<methodResponse>
<params>
<param>
<value><struct><member><name>h_entry</name><value><int>2084</int></value></member><member><name>h_id</name><value><int>7721</int></value></member><member><name>call-id</name><value><string>ab2248af-53e9-1237-dfaf-06119108e458</string></value></member><member><name>from_uri</name><value><string>sip:suren1002170622114516@54.183.206.134</string></value></member><member><name>to_uri</name><value><string>sip:919967609476@54.183.206.134</string></value></member><member><name>state</name><value><int>4</int></value></member><member><name>start_ts</name><value><int>1540576147</int></value></member><member><name>init_ts</name><value><int>1540576137</int></value></member><member><name>timeout</name><value><int>1540619347</int></value></member><member><name>lifetime</name><value><int>43200</int></value></member><member><name>dflags</name><value><int>643</int></value></member><member><name>sflags</name><value><int>0</int></value></member><member><name>iflags</name><value><int>0</int></value></member><member><name>caller</name><value><struct><member><name>tag</name><value><string>7pNv5Kt36jm2j</string></value></member><member><name>contact</name><value><string>sip:gw+plivo.com@13.57.90.158:5080;transport=tcp;transport=tcp;gw=plivo.com;alias=13.57.90.158~50188~2</string></value></member><member><name>cseq</name><value><string>129951879</string></value></member><member><name>route_set</name><value><string>&lt;sip:54.183.206.134:5060;r2=on;lr;ftag=7pNv5Kt36jm2j;nat=yes>,&lt;sip:54.183.206.134;transport=tcp;r2=on;lr;ftag=7pNv5Kt36jm2j;nat=yes></string></value></member><member><name>socket</name><value><string>udp:172.31.4.160:5060</string></value></member></struct></value></member><member><name>callee</name><value><struct><member><name>tag</name><value><string>gK09a0497e</string></value></member><member><name>contact</name><value><string>sip:+919967609476@81.52.176.68:5060</string></value></member><member><name>cseq</name><value><string>0</string></value></member><member><name>route_set</name><value><string>&lt;sip:18.214.109.132:5060;lr;ftag=7pNv5Kt36jm2j></string></value></member><member><name>socket</name><value><string>udp:172.31.4.160:5060</string></value></member></struct></value></member><member><name>profiles</name><value><array><data>
</data></array></value></member><member><name>variables</name><value><array><data>
<value><struct><member><name>call_answer_time</name><value><string>1540576147</string></value></member></struct></value><value><struct><member><name>call_ring_time</name><value><string>1540576145</string></value></member></struct></value><value><struct><member><name>carrier_id</name><value><string>737</string></value></member></struct></value><value><struct><member><name>carrier_uri</name><value><string>sip:+919967609476@81.52.176.68</string></value></member></struct></value><value><struct><member><name>dest_codecs</name><value><string>PCMA,telephone-event/8000</string></value></member></struct></value><value><struct><member><name>direction</name><value><string>outbound</string></value></member></struct></value><value><struct><member><name>cust_transport_protocol</name><value><string>udp</string></value></member></struct></value><value><struct><member><name>call_start_time</name><value><string>1540576137</string></value></member></struct></value><value><struct><member><name>dest_number</name><value><string>919967609476</string></value></member></struct></value><value><struct><member><name>call_uuid</name><value><string>71705c36-8942-41f2-a832-860550a73166</string></value></member></struct></value><value><struct><member><name>account_id</name><value><string>27298</string></value></member></struct></value><value><struct><member><name>src_codecs</name><value><string>PCMU,PCMA,telephone-event/8000</string></value></member></struct></value></data></array></value></member></struct>
</value>
</param>
</params>

**Comment by SurendraPlivo** [comment]
<member>contact</name><value><string>sip:gw+plivo.com@13.57.90.158:5080;transport=tcp;transport=tcp;gw=plivo.com;alias=13.57.90.158~50188~2</string></value></member>

**Comment by miconda** [comment]
The alias parameter of Contact should be handled internally by kamailio only if there is no Route set, but it is not the case here. I will look at the code.

**Comment by SurendraPlivo** [comment]
i just checked the code and found that https://github.com/kamailio/kamailio/blob/98ee25c6da118cadedd98621c580ed4df3a7e860/src/modules/dialog/dlg_req_within.c#L95
```
if(uri_restore_rcv_alias(&cell->contact[dir], &nuri, &duri)<0) {
		nuri.len = 0;
		duri.len = 0;
	}

```
This function is setting nuri, that is subsequently used as request uri. Problem here is nuri does not contains the alias parameters in uri.

**Comment by miconda** [comment]
While traveling earlier today I made the patch pushed with the commit referenced above. I saw you made a pull request  as well, but I decided to push mine because it avoids few extra assignments that are no longer necessary. If still an issue with the above patch, reopen.

**Comment by surendratiwari3** [comment]
@miconda thank you so much :-) yeah i just check that . no issue, at then end issue is resolved and that 's matter most 👍
