### ISSUE TITLE
Failed to parse mysql connection uri, when '@' operator is added in password section

### ISSUE THREAD

**Issue by debojitkakoti** [kamailio/kamailio#169]
I have added DBURL as
#!define DBURL "mysql://kamailio_test:kam@#sip@localhost/kamailio"
Where username is kamailio_test  and password is kam@#sip

So after the first '@' operator it is assuming it as host part which is not true in this case.

Error log:
'ERROR: db_mysql [km_my_con.c:114]: db_mysql_new_connection(): driver error: Unknown MySQL server host '#sip@localhost' (2)'

**Comment by miconda** [comment]
Can you try with commit c02e165cc7a44e525dd55714c4471f1236e96b43 ? It is now in master branch.

**Comment by debojitkakoti** [comment]
Issue is resolved. 
I was trying to remove the bug from kamailio/modules/db_mysql/my_uri.c file . 
Anyway thanks for your quick response.
