### ISSUE TITLE
HeartBeat Module

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1698]
### Description
Right now, kamailio did not generate the heartbeat events a call. It's very important to have heartbeat event in kamailio so billing solution can be built independent of kamailio.

Heartbeat module can be built separately with having following parameters:
modparam("heartbeat","duration",30) // this will describe at what pace heartbeat will get generated for every call.
modparam("heartbeat","signature",caller=$dlg_var(caller);callee=$dlg_var(callee);account_id=$dlg_var(account_id)) -- this will tell what data to send.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.4 (x86_64/linux) a1df59
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: a1df59 
compiled on 06:23:23 Oct 30 2018 with gcc 4.8.4
```

* **Operating System**:

```
root@ip-172-31-4-160:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

root@ip-172-31-4-160:~# uname -a
Linux ip-172-31-4-160 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
There are now rpc commands to get the call details using various filters. I guess for the moment it offers the foundation for external call controllers/billing systems to be built independently of Kamailio. If someone wants a different approach, just submit a PR.
