### ISSUE TITLE
rtpengine: stats for rtpengine command and reply from rtpengine

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1699]
### Description
rightnow, there is no stats about command sent to rtpengine and getting reply from rtpengine. There should be a stats that will tell that 
number of offer request sent:  
number of answer request sent:
number of delete request sent:
number of failed request for offer [after retry]:
number of failed request for answer [after retry]:
number of failed request for delete [after retry]:

This will help to identify actual number of failed request.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Two years of inactivity, if someone wants to implement something in this direction, just make a pull request.

Likely an alternative is to use exec module to call rtpengine-ctl tool and manage the result in the config. Or just use some embedded scripting language like lua or python.
