### ISSUE TITLE
evapi: if there is no evapi clients are connected to kamailio, evapi trying to send data.

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1700]
### Description
right now, evapi module trying to send data even if no clients are connected .in the case new transaction is created and even suspended also. kamailio should not create the transaction if no evapi client is connected to kamailio.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.4 (x86_64/linux) a1df59
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: a1df59 
compiled on 06:23:23 Oct 30 2018 with gcc 4.8.4

```

* **Operating System**:

```
root@ip-172-31-4-160:~# uname -a
Linux ip-172-31-4-160 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
The thing is that the communication with evapi clients is done from a dedicated process, not from SIP routing processes. So the sip router process is not aware of evapi clients. I will see how this can be implemented.

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
