### ISSUE TITLE
support usrloc handle_lost_tcp variable also in DB-Only scheme

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#171]

**Comment by miconda** [comment]
This should be possible now by using tcpops and sqlops modules -- delete in db tables using sqlops with connection id inside the event route for tcp connection close:

  * https://www.kamailio.org/docs/modules/stable/modules/tcpops.html#idp24331996

**Comment by juha-h** [comment]
Daniel-Constantin Mierla writes:

> This should be possible now by using tcpops and sqlops modules --
> delete in db tables using sqlops with connection id inside the event
> route for tcp connection close:
> 
>   * https://www.kamailio.org/docs/modules/stable/modules/tcpops.html#idp24331996

Thanks, Juha
