### ISSUE TITLE
Cannot build ims module on OpenSUSE

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1710]
### Description

`libmnl-devel` is present in OpenSUSE but build of ims module is failed.
This because headers files is located on other path then kamailio expects.
`libmnl-devel` package is designed to use pkgconfig.
I checked on CentOS dist `libmnl-devel` also have files for pkgconfig.

#### Reproduction

need to build ims module on openSUSE_Leap_42.3

#### Debugging Data

NA

#### Log Messages

```
[  333s] make[3]: 'libkamailio_ims.so.0.1' is up to date.
[  333s] LD (gcc) [M ims_ocs.so]		ims_ocs.so
[  333s] CC (gcc) [M ims_diameter_server.so]		ims_diameter_server.o
[  333s] CC (gcc) [M ims_diameter_server.so]		cJSON.o
[  333s] CC (gcc) [M ims_diameter_server.so]		avp_helper.o
[  334s] make[3]: 'libkamailio_ims.so.0.1' is up to date.
[  334s] LD (gcc) [M ims_diameter_server.so]		ims_diameter_server.so
[  334s] CC (gcc) [M ims_ipsec_pcscf.so]		ims_ipsec_pcscf_mod.o
[  334s] CC (gcc) [M ims_ipsec_pcscf.so]		ipsec.o
[  334s] ipsec.c:32:27: fatal error: libmnl/libmnl.h: No such file or directory
[  334s]  #include <libmnl/libmnl.h>
[  334s]                            ^
[  334s] compilation terminated.
[  334s] ../../Makefile.rules:100: recipe for target 'ipsec.o' failed
[  334s] make[2]: *** [ipsec.o] Error 1
[  334s] Makefile:511: recipe for target 'modules' failed
[  334s] make[1]: *** [modules] Error 1
[  334s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/kamailio-5.2.0/src'
[  334s] Makefile:27: recipe for target 'every-module' failed
[  334s] make: *** [every-module] Error 2
[  334s] error: Bad exit status from /var/tmp/rpm-tmp.Yi6mZQ (%build)
[  334s] 
```

#### SIP Traffic

NA

### Possible Solutions

Not known

### Additional Information

master branch

* **Operating System**:
openSUSE_Leap_42.3

**Comment by sergey-safarov** [comment]
on OpenSUSE files is located at `/usr/include/libmnl-1.0.3/libmnl/libmnl.h`

**Comment by miconda** [comment]
I pushed to master a patch to use pkg-config for libmnl -- try and if it works, I will backport.

**Comment by sergey-safarov** [comment]
tested latest master and fix works.
Ticket is still open, until commit backported.

**Comment by miconda** [comment]
Thanks for testing. Backported.
