### ISSUE TITLE
OBS Kamailio 5.0.7 RPM dependency on lib ims

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#1721]
### Description

It was reported that using the RPM for v5.0.7 from opensuse build service is getting an error on dependency for internal lib ims.

Getting the rpm from:

  * http://download.opensuse.org/repositories/home:/kamailio:/v5.0.x-rpms/RHEL_7/x86_64/kamailio-5.0.7-8.el7.x86_64.rpm

Then:

```
rpm -ivh kamailio-5.0.7-8.el7.x86_64.rpm
   warning: kamailio-5.0.7-8.el7.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 941fdbdd: NOKEY
   error: Failed dependencies:
          libkamailio_ims.so.0()(64bit) is needed by kamailio-5.0.7-8.el7.x86_64
```

#### Reproduction

See above.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
5.0.7, but can be the same for 5.1 or newer.
```

* **Operating System**:

```
RHEL 7, but can be the same for other OSes
```

**Comment by miconda** [comment]
@sergey-safarov -  is this something fixed after release of 5.0.7, or can it be still an issue?

I noticed also there is a pull request for OBS specs, but do not seem related.

**Comment by sergey-safarov** [comment]
I can see `imc.so` is wants `libkamailio_ims.so`.
As options i can move `imc.so` into `kamailio-ims` rpm package.
I will wait your suggestion about preferred option.

**Comment by miconda** [comment]
You can put the file in ims package, not needed by the core.

**Comment by sergey-safarov** [comment]
I have relocated module and triggered rebuild of RPM packages.
Could you test install [kamailio rpm](https://download.opensuse.org/repositories/home:/kamailio:/v5.0.x-rpms/CentOS_7/x86_64/kamailio-5.0.7-10.el7.centos.x86_64.rpm). As you do it before
If all good, then i will commit into GitHub repo.

**Comment by sergey-safarov** [comment]
To be clear.
`ims_ocs` is relocated  in commits
1) 6a7ea3d489175659cbfcca4088a8cd26b9352273 - master and 5.2 branches
2) d54d3244f9496b7963ff8b722ea04317774b7ad2 - 5.1 branch

Related ticket https://github.com/kamailio/kamailio/pull/1392

**Comment by miconda** [comment]
The d54d324 is cherry-pick -x  6a7ea3d, so this seems to be fixed.
