### ISSUE TITLE
siptrace: option ping from nathelper traffic do not get duplicated

### ISSUE THREAD

**Issue by rdissauer** [kamailio/kamailio#1722]
### Description

when using kamailio with mod siptrace in trace mode, option pings from nathelper module and tls encrypted packets do not get duplicated

#### Reproduction

version: kamailio 5.1.6 (x86_64/linux) 

modparam("nathelper", "ping_nated_only", 0)
modparam("siptrace", "trace_mode", 1)
modparam("siptrace", "duplicate_uri", "sip:10.1.1.1:5888")

when listening on sip:10.1.1.1:5888 all the duplicated sip packets arrive except option pings from nathelper and tls encrypted traffic (which should then be already decrypted by kamailio)

### Possible Solutions

seems that core triggers are not evaluated when using tls or nathelper option pings

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.6 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 6.3.0
```

* **Operating System**:

```
Linux AT1LKAM04 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

```

**Comment by miconda** [comment]
Are you getting any error log when sending out via TLS. The same function is executed for sending over UDP and TCP, so there is no reason not to duplicate it.

For nathelper, what Henning said applies, the module has low level functions for nat pings, having some variants where it can spoof source IP address. So C coding is needed, that being more an enhancement, while the TLS traffic should be there and if doesn't work is a bug.

**Comment by rdissauer** [comment]
sorry, siptrace module was not enabled on the tls machine. siptrace "trace_mode" "on" works fine with tls.

**Comment by rdissauer** [comment]
@miconda we would like to contribute some work for this, but it would be great to get some advice if it could actually work. And if it would work, is it wise to go through core triggers? I can imagine that this could stress kamailio unnecessarily.

**Comment by henningw** [comment]
@rdissauer The SREV_NET_DATA_OUT event is already used in in the msg_send_buffer, so this is ok performance wise. The main reason that this logic is placed in msg_send_buffer() is that it saves duplicated code - otherwise this logic needs to be added to the different protocol sending low level functions.
But it can be pushed one level down to udp_send(), tcp_send, and sctp_core_msg_send(). The logic for sending websocket is implemented with another event, this needs some more investigation.

**Comment by henningw** [comment]
@rdissauer Any update from your side regarding this issue or the implementation?

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
