### ISSUE TITLE
topos module seems to break re-SUBSCRIBE routing to downstream destinations

### ISSUE THREAD

**Issue by gedia** [kamailio/kamailio#1724]
### Description
Kamailio seems to fail to properly route in-dialog SUBSCRIBE with the topos module enabled. In this configuration, SUBSCRIBEs are expected to be delivered to a downstream UAS, an asterisk instance in the internal network.

record_route() is executed for all initial requests, including SUBSCRIBEs. Routing is performed correctly with the topos module disabled, no other modifications to config were needed. This problem does not manifest for re-INVITEs, which follow similar routing.

### Troubleshooting
I haven't been able to work around this issue in any other way other than disabling the topos module.
#### Reproduction
The configuration used is a heavily modified version of the example configuration file, but the handling of SUBSCRIBEs is generally simple. The initial SUBSCRIBE is subject to some tests, the R-URI is edited and dispatched to a farm of asterisk servers based on some criteria. Record Routing is enforced, so subsequent in-dialog re-SUBSCRIBEs are expected to be routed with loose_route(), which doesn't seem to handle things properly.

#### Debugging Data
I'm attaching kamailio logs with debug=4, cfg_trace

#### Log Messages
See attachments

#### SIP Traffic
Please see: https://www.cloudshark.org/captures/d2643aae7f2a

### Possible Solutions

Using topoh instead for topos, but unfortunately this will break communication for other reasons (messages too large/UDP fragmentation for some peers).

### Additional Information
  * **Kamailio Version**
Tried with kamailio 5.1.6 and kamailio 5.3.0-dev0
deb.kamailio.org repositories were used to acquire binaries for both versions

* **Operating System**:
Debian Stretch

[resubscribe.log](https://github.com/kamailio/kamailio/files/2586440/resubscribe.log)

**Comment by miconda** [comment]
The module was designed to track voip dialogs (created by INVITE) for interconnected services/servers. It will require some C development to make it work for presence dialogs (created by SUBSCRIBE), which are expected to be handled by local server, not sent to a foreign server.

Do you want to mask the topology for presence dialogs or it just breaks as you want to use it for INVITE? If not, you can skip applying topos for SUBSCRIBE by using the event_route executed by topos in 5.2 or master.

**Comment by gedia** [comment]
Thanks for the reply. I mostly opened this issue for tracking, and to investigate if a potential fix is trivial or requires substantial work.

We are currently considering the alternatives, that is either wait for 5.2 and use event_route to skip topos processing for subscribes, or deploy a separate kamailio instance with either no topology hiding at all, or topoh-enabled topology hiding instead...

**Comment by miconda** [comment]
Closing for long time inactivity, all the stable branches offer the possibility to skip handing subscribes. For handling them with topology stripping, a pull request can be made.
