### ISSUE TITLE
dialog: not able to set the hangup_reason , when we hangup calls using xmlrpc.

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1737]
### Description
We are using xmlrpc to terminate the calls once customer balance reaches to zero. call got terminated but we will not be able to set the dialog variable related to hangup_reason. There should be a way during dlg.terminate_dlg xmlrpc request that if i mention the some parameter then it should set before sending bye to callee and caller.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
root@ip-172-31-4-160:/etc/kamailio# kamailio -version
version: kamailio 5.1.4 (x86_64/linux) 6ebfda
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 6ebfda 
compiled on 11:48:26 Sep  7 2018 with gcc 4.8.4
```

* **Operating System**:

```
root@ip-172-31-4-160:/etc/kamailio# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

root@ip-172-31-4-160:/etc/kamailio# uname -a
Linux ip-172-31-4-160 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by miconda** [comment]
It is not clear what you would like to achieve, maybe you can describe with an example of rpc command and what should be available afterwards.

**Comment by surendratiwari3** [comment]
sure. we have a heartbeat service that continuously checking the kamailio dialog using dlg.dlg_list command in defined interval. in the same time heartbeat service will deduct the balance and if balance is not sufficient for continuing of call, it will send dlg.terminate_dlg request to kamailio. kamailio will generate the cdr. but in cdr we are not able to identify why this call get drop. so if we are able to add some dialog variable on dlg.terminate_dlg then we can easily populate that into cdr.

**Comment by surendratiwari3** [comment]
This feature request is managed by this pull request.

https://github.com/kamailio/kamailio/pull/1740

**Comment by miconda** [comment]
Long time without any activity, closing it. A PR can be made if anyone wants to implement it.
