### ISSUE TITLE
acc_json: Supporting multi_leg_info parameter

### ISSUE THREAD

**Issue by jklingenmeyer** [kamailio/kamailio#1745]
### Description

The recently-added **acc_json** module does not support the _multi_leg_info_ parameter from the main **acc** module.

### Expected behavior

**acc_json** module could add the extra leg info attributes in the JSON data, as the **acc_radius** module already does. Behavior could be the same for the JSON module.

**Comment by miconda** [comment]
Maybe @jchavanton can assert if it is feasible or not...

**Comment by jchavanton** [comment]
Sure, I will have a look when I have a chance.
Very soon hopefully.

**Comment by jchavanton** [comment]
tested a bit more and double check the logic used in acc.c

**Comment by jchavanton** [comment]
@jklingenmeyer please test and confirm this is what you needed

**Comment by jklingenmeyer** [comment]
@jchavanton many thanks for your quick addition. Behavior is the one I meant.
Sorry for my late feedback.
