### ISSUE TITLE
Module development - Best place for "km_log_func_set" logging call

### ISSUE THREAD

**Issue by luismartingil** [kamailio/kamailio#1753]
When using the "km_log_func_set" to configure a customized Kamailio logging function:

- **log_custom** module is setting this **per child** in the [child_init](https://github.com/kamailio/kamailio/blob/master/src/modules/log_custom/log_custom_mod.c#L99) function.

- **log_systemd** module is setting this in the [mod_register](https://github.com/kamailio/kamailio/blob/master/src/modules/log_systemd/log_systemd_mod.c#L209) function.

What is the best practice to follow?

**Comment by miconda** [comment]
The issue tracker is not used for discussions about using or developing Kamailio. Only for tracking bugs and requests for new features. Use mailing lists sr-dev or sr-users at lists.kamailio.org for such discussions.

Then: the right place is a matter of what is required behind: to have an initialization per worker/child, or one global is enough as well as how early it can be done (does it depend on a mod parameter or not, other module, ...)
