### ISSUE TITLE
New modules (app_ruby) missing from v5.2.0 RPM/DEB packages

### ISSUE THREAD

**Issue by fatihorhan** [kamailio/kamailio#1761]
### Description
Hello.
There is no app_ruby RPM package in https://build.opensuse.org/project/show/home:kamailio:v5.2.x-rpms. Based on my slack conversation with Victor Seva, new modules introduced in v5.2 seem to be missed and SPEC didn't get updated.

#### Reproduction
yum install kamailio
have loadmodule "app_ruby.so" in kamailio.cfg
try to start kamailio service, it doesn't start

#### Log Messages
```
ERROR: <core> [core/sr_module.c:487]: load_module(): could not find module <app_ruby> in </usr/lib64/kamailio/modules>
```

### Possible Solutions
Update kamailio.spec file to compile and package app_ruby.so

### Additional Information
```
version: kamailio 5.2.0 (x86_64/linux) 535e13
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 535e13
compiled on 10:26:34 Nov 28 2018 with gcc 4.8.5

```

* **Operating System**:
```
Linux servername 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by linuxmaniac** [comment]
kamailio-ruby-modules added https://github.com/kamailio/kamailio/commit/4698e97cd3985d3a7f51c709decb546e62b036c5 for master.
I will backport it to 5.2 branch afterwards

**Comment by fatihorhan** [comment]
Thank you @linuxmaniac for your swift fix.

Pardon my ignorance but I only see DEB packages in your commit, will RPMs be built too?
I'm waiting for packages in repository.

Thanks again.

**Comment by sergey-safarov** [comment]
@fatihorhan i now test RPM packages.
Maybe for CentOS this not created.

**Comment by sergey-safarov** [comment]
> wheezy (ruby1.9.1-dev) and precise(ruby1.8-dev) versions have no pkg-config info
Same error on CentOS6 and RHEL6. I have now disabled this package on this dist.

**Comment by miconda** [comment]
Closing it -- the package was added for supported linux OSes.

**Comment by fatihorhan** [comment]
I can confirm yum install method works on Centos 7.
Thank you all!

**Comment by sergey-safarov** [comment]
I forget to add on Alpine. Will open until added to Alpine

**Comment by sergey-safarov** [comment]
app_ruby added into Alpine packaging

**Comment by mckaygerhard** [comment]
how we can specify the parameters to not use pkg-config?
