### ISSUE TITLE
kamcmd app_ruby.reload returns error: 500 - command app_ruby.reload not found

### ISSUE THREAD

**Issue by fatihorhan** [kamailio/kamailio#1764]
### Description
Hello,

When I try to reload ruby scripts with (in linux CLI) :
`kamcmd app_ruby.reload`

This message is returned:
`error: 500 - command app_ruby.reload not found`

I double checked the command name, module status, and debug logs.
I can run other kamcmd commands and can use ruby scripts.
#### Reproduction
in linux CLI:
`yum install kamailio-ruby`

in kamailio.cfg
`loadmodule "app_ruby.so"`
`modparam("app_ruby", "load", "/etc/kamailio/ruby/myscript.rb")`

in linux CLI:
`kamcmd app_ruby.reload`

#### Log Messages

When I execute kamcmd, these debug lines appear:
```
Dec 13 14:57:30 servername /usr/sbin/kamailio[4479]: DEBUG: ctl [../../core/io_wait.h:380]: io_watch_add(): DBG: io_watch_add(0x7fc7ee451320, 19, 3, 0x2b70310), fd_no=1
Dec 13 14:57:30 servername /usr/sbin/kamailio[4479]: DEBUG: ctl [io_listener.c:442]: handle_new_connect(): handle_stream read: new connection (1) on /var/run/kamailio//kamailio_ctl
Dec 13 14:57:30 servername /usr/sbin/kamailio[4479]: DEBUG: ctl [io_listener.c:495]: handle_stream_read(): handle_stream read: eof on /var/run/kamailio//kamailio_ctl
Dec 13 14:57:30 servername /usr/sbin/kamailio[4479]: DEBUG: ctl [../../core/io_wait.h:602]: io_watch_del(): DBG: io_watch_del (0x7fc7ee451320, 19, -1, 0x10) fd_no=2 called
```

### Possible Solutions
I tried to read kamcmd and app_ruby source code but quickly got lost, so no leads there :)

Tried other combinations to no avail:
`kamcmd ruby.reload`
`kamcmd app_ruby_jsdt.reload`

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.0 (x86_64/linux) 535e13
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 535e13
compiled on 10:26:34 Nov 28 2018 with gcc 4.8.5
```

* **Operating System**:
Centos 7.2 64bit

```
Linux servername 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
The rpc command was not implemented yet, I will look at it during the next days.

**Comment by fatihorhan** [comment]
Thanks @miconda for your attention.

**Comment by miconda** [comment]
I just pushed a commit (28b54dc63c62ddef837a3f580ab97161b55f214e) implementing the command. It is in master branch only for the moment. Can you test and report the results?

**Comment by fatihorhan** [comment]
It works! 🎉 

```
kamcmd app_ruby.reload
{
        old: 0
        new: 1
}
```

`Dec 14 13:08:22 servername /usr/sbin/kamailio[30394]: INFO: app_ruby [app_ruby_api.c:1273]: app_ruby_rpc_reload(): marking for reload ruby script file: /etc/kamailio/ruby/myscript.rb (0 => 0)
`

I also tested if new code is in effect, it is!

Thank you very much.
I'll now wait for yum repo update so I can use this in production.

**Comment by miconda** [comment]
Great! Thanks for testing and reporting back!

I would also appreciate further feedback on using the module. It was requested at the last Kamailio World Conference, I implemented it, but those that requested it haven't reported back how it works. That was the reason having this rpc command was forgotten to be implemented. Not being a Ruby user, I did minimal testing while developing the module.

On the other hand, I don't think the rpm repos have nightly builds, likely they are released when a new Kamailio 5.2.x version is out (expected at the beginning of next year). You can of course build the rpms locally (e.g., in a virtual machine or using docker).

I am closing this one. Patches will be backported soon to the 5.2 branch.

**Comment by fatihorhan** [comment]
We are using Kamailio as a mid-registrar and reverse proxy to Freeswitch boxes (based on example cfg you shared, thanks BTW). I'm migrating our kamailio.cfg to ruby, where do you like me to report my experience? (like mailing list, direct mail or under this issue)

I'll build v5.2.0 branch from source until new release then. Thanks.

**Comment by miconda** [comment]
The best place for discussions is sr-users@lists.kamailio.org mailing list.
