### ISSUE TITLE
kamailio refuses custom global variable

### ISSUE THREAD

**Issue by mckaygerhard** [kamailio/kamailio#1773]
### Description

triying to config kamailio using default config file with proper parameters, and also aparte few other in kamailio-local.cfg.. en that second file i put a variable (for global) as  `kamailioip=10.10.10.10 ` but refuses to reconoce it

### Troubleshooting

kamailio seems does not reconoce it the global variable in kamailio-local.cfg file that are sourcered by the kamailio.cfg main file

#### Reproduction

download, configure and make build of kamailio
use the main config file
`touch kamilio-local.cfg` that will be sourcered by kamailio.cfg
in that file put only `kamailioip=10.10.10.10`
i tri also with "101.10.10.10" and same problem

#### Log Messages

```
 0(1542) DEBUG: <core> [core/modparam.c:83]: set_mod_param_regex(): 'debugger' matches module 'debugger'
 0(1542) DEBUG: <core> [core/sr_module.c:811]: find_param_export(): found <log_level_name> in module debugger [/usr/lib/x86_64-linux-gnu/kamailio/modules/debugger.so]
 0(1542) DEBUG: <core> [core/modparam.c:99]: set_mod_param_regex(): found <log_level_name> in module debugger [/usr/lib/x86_64-linux-gnu/kamailio/modules/debugger.so]
 0(1542) CRITICAL: <core> [core/cfg.y:3450]: yyerror_at(): parse error in config file kamailio-localmods.cfg, line 9, column 6: syntax error
 0(1542) CRITICAL: <core> [core/cfg.y:3450]: yyerror_at(): parse error in config file kamailio-localmods.cfg, line 9, column 6: unknown config variable
 0(1542) CRITICAL: <core> [core/cfg.y:3447]: yyerror_at(): parse error in config file kamailio-localmods.cfg, line 9, column 7-8: 
ERROR: bad config file (3 errors)
 0(1542) WARNING: <core> [core/ppcfg.c:221]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.6 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2
```

* **Operating System**:

```
Linux ip-10-101-2-78 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
```

**Comment by mckaygerhard** [comment]
seems related to #1159 but was closed

**Comment by SipSeb** [comment]
I think, in your case, the syntax could be wrong.

Try:
```config.kamailioip=10.10.10.10```

**Comment by miconda** [comment]
Like @SipSeb said, the syntax for custom varaibles is `group.name`:

  * https://www.kamailio.org/wiki/cookbooks/devel/core#custom_global_parameters

Closing it.
