### ISSUE TITLE
TSILO crashes kamailio on ts_store()

### ISSUE THREAD

**Issue by ForGuru** [kamailio/kamailio#1775]
I am getting following error when ts_store() is called 
```
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25676]: {1 2 INVITE 2d24732c962aa49859622eb9d214a115@192.168.2.7} DEBUG: tsilo [ts_store.c:80]: ts_store(): storing transaction 5967:208972607 for r-uri:
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/tcp_main.c:3279]: handle_tcp_child(): dead tcp child 2 (pid 25676, no 19) (shutting down?)
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/io_wait.h:602]: io_watch_del(): DBG: io_watch_del (0xa6cf40, 37, -1, 0x0) fd_no=37 called
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 34
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/tcp_main.c:3512]: handle_ser_child(): dead child 19, pid 25676 (shutting down?)
```

 ```
       if (lookup("location"))
        {
                xlog("L_INFO","PUSHASYNC: for new transaction [$T(id_index):$T(id_label)] $fU => $rU \n");
                if(t_newtran()) {
                        xlog("L_INFO","PUSHASYNC: storing transaction [$T(id_index):$T(id_label)] fU=[$fU] => rU=[$rU] ru=[$ru]  \n");
                        ts_store();
                        xlog("L_INFO","PUSHASYNC: stored transaction [$T(id_index):$T(id_label)] [$fU] => [$rU]\n");
                }
                $sht(vtp=>stored::$rU) = 1; 
                return;
        }
```
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```


Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25676]: {1 2 INVITE 2d24732c962aa49859622eb9d214a115@192.168.2.7} DEBUG: tsilo [ts_store.c:80]: ts_store(): storing transaction 5967:208972607 for r-uri:
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/tcp_main.c:3279]: handle_tcp_child(): dead tcp child 2 (pid 25676, no 19) (shutting down?)
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/io_wait.h:602]: io_watch_del(): DBG: io_watch_del (0xa6cf40, 37, -1, 0x0) fd_no=37 called
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 34
Dec 21 12:50:57 ejabberd /usr/local/kamailio-5.1/sbin/kamailio[25696]: DEBUG: <core> [core/tcp_main.c:3512]: handle_ser_child(): dead child 19, pid 25676 (shutting down?)

```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```

version: kamailio 5.1.4 (x86_64/linux) dbeab1
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: dbeab1 
compiled on 19:53:40 Jul 22 2018 with gcc 5.4.0

```

* **Operating System**:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial


Linux ejabberd 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by miconda** [comment]
Did you get a core dump? If yes, paste here the backtrace taken with gdb.

**Comment by ForGuru** [comment]
I was able to see this from core 

> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Core was generated by `/usr/local/kamailio-5.1/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /usr'.
> Program terminated with signal SIGABRT, Aborted.
> #0  0x00007f43f5c63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
> 54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by ForGuru** [comment]
> #0  0x00007f43f5c63428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
>         resultvar = 0
>         pid = 3131
>         selftid = 3131
> #1  0x00007f43f5c6502a in __GI_abort () at abort.c:89
>         save_stage = 2
>         act = {__sigaction_handler = {sa_handler = 0x7f43ebe3b3c0, sa_sigaction = 0x7f43ebe3b3c0}, sa_mask = {
>             __val = {8229927, 133143986226, 47244640269, 506806140935, 953482739718, 140728898420736, 0, 44373472, 
>               139929697103872, 17184162608, 4303193040, 139929863774160, 140730082576896, 8087364, 0, 2}}, 
>           sa_flags = -263151403, sa_restorer = 0x0}
>         sigs = {__val = {32, 0 <repeats 15 times>}}
> #2  0x00007f43f050a0f3 in locking_f (mode=9, n=1, file=0x7f43f000be5b "err.c", line=375) at tls_locking.c:106
>         __func__ = "locking_f"
> #3  0x00007f43eff5784f in ERR_load_ERR_strings () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
> No symbol table info available.
> #4  0x0000000300678ee3 in ?? ()
> No symbol table info available.
> #5  0x00000000007789f0 in ?? ()
> No symbol table info available.
> #6  0x00000000323e406d in ?? ()
> No symbol table info available.
> #7  0x0000000000418330 in ?? ()
> No symbol table info available.
> #8  0x00007ffe4694cde0 in ?? ()
> No symbol table info available.
> #9  0x0000000000000000 in ?? ()
> No symbol table info available.
>

**Comment by linuxmaniac** [comment]
@ForGuru can you please try that fix

**Comment by ForGuru** [comment]
@linuxmaniac Thanks for ur reply. After us suggested fix, crash is gone. but I see this in logs

> ERROR: tsilo [ts_store.c:75]: ts_store(): malformed aor from uri[sip:192.168.8.100:5090;transport=TCP;registering_acc=example.com]


What is the mistake on my side 

```
                ts_store();
                $sht(vtp=>stored::$rU) = 1;
```

**Comment by linuxmaniac** [comment]
I'm not the author of the module, so @grumvalski can explain in a better way. But looking into the code, the problem here is that the r-ruri has no user part, you are not passing a uri value so module is trying to get it from r-uri.

**Comment by ForGuru** [comment]
@grumvalski and @miconda Thanks for your support I have been able to get it working with this

```
$avp(ruri) = "sip:" + $tU + "@" + $td;
ts_store($avp(ruri));
```
