### ISSUE TITLE
unquoted value in global vars got segafult or error at cfg files

### ISSUE THREAD

**Issue by mckaygerhard** [kamailio/kamailio#1779]
### Description

due the behaviour of the variable "alias", the others that use dots inside are misinterpreted: seems ambiguity in the grammar with alias and listen respect other vars that have "dots" in values.

Both alias and listen can have an unquoted host list as value. An unquoted host is a list of
IDs separated by ‘.’. Since EOL is not taken into account, then `alias=foo.bar` followed by `myvar.msg=2.3.4.5` is interpreted as: `alias=foo.bar myvar.msg`

bug of course in issue #1773 nobody check that right?

### Troubleshooting

kamailio seems does not reconoce it the global variable in kamailio.cfg file **if no double quoted the value itselft! but if are not global variables, alias variable can be unquoted!**

prevousli done in isues:
* #1773 closed by a comment that does not make sense due i configured in right way
* after furter investigation seems due the alias variable that implies a "dot" inside the value

seems the "dots" are misinterperted due the presence of the aliases variable that already are present! and that generated a very very older problem!

#### Reproduction

download, configure and make build of kamailio
use the main config file
in that file put only one change, presicelly and adition:
`kamailio.bindip=10.101.10.10` 

**bur using doble coutes seems there no problem**  this are not documented and seems its and ancient bug

#### Log Messages

```
 0(1542) DEBUG: <core> [core/modparam.c:83]: set_mod_param_regex(): 'debugger' matches module 'debugger'
 0(1542) DEBUG: <core> [core/sr_module.c:811]: find_param_export(): found <log_level_name> in module debugger [/usr/lib/x86_64-linux-gnu/kamailio/modules/debugger.so]
 0(1542) DEBUG: <core> [core/modparam.c:99]: set_mod_param_regex(): found <log_level_name> in module debugger [/usr/lib/x86_64-linux-gnu/kamailio/modules/debugger.so]
 0(1542) CRITICAL: <core> [core/cfg.y:3450]: yyerror_at(): parse error in config file kamailio.cfg, line 9, column 6: syntax error
 0(1542) CRITICAL: <core> [core/cfg.y:3450]: yyerror_at(): parse error in config file kamailio.cfg, line 9, column 6: unknown config variable
 0(1542) CRITICAL: <core> [core/cfg.y:3447]: yyerror_at(): parse error in config file kamailio.cfg, line 9, column 7-8: 
ERROR: bad config file (3 errors)
 0(1542) WARNING: <core> [core/ppcfg.c:221]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.6 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2
```

* **Operating System**:

```
Linux ip-10-101-2-78 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
```

**Comment by miconda** [comment]
The **custom global variables** are defined as `groupname.varname=value desc text`, where you can choose pretty much any groupname and varname (iirc, apart of some predefined keywords). The value must be either string (in between quotes) or integer (number).

Because listen or aliases can accept unquoted values, is because those are global core parameters with a specific syntax. To avoid having them swallow next lines, you can use `;` after their value, like:

```
alias=myhostname.com;
```
It is a common practice to let global core parameters ended by end-of-line, because most of them are single value, but for some of them the value can span across lines, so you can use `;` to terminate it if you get a conflict with the next line.

So this is not an issue, but how some elements are defined.

**Comment by mckaygerhard** [comment]
an important question that can determine if are a issue: why that are not pointed so explained in the documentation? @miconda ? i research at the documentation and only said that can be unquoted or quoted no more info.. kamalio documentation seems it's the most ambogous in the world! so its an issue if so..

**Comment by joelsdc** [comment]
I’m sure the community would appreciate if you would send a PR to update the documentation and improve it. 

You could also just suggest that it’s incomplete, and someone might do it for you. 

I don’t see the need to attack the quality of the documentation of Kamailio.

There is also an email list where you could ask these questions... sr-users@lists.kamailio.org

Happy holidays :-)

**Comment by egarciahz** [comment]
well maybe in part have a point here, if i changed something and hide some important information, that's may cause troubles when users try to implement, in fact per see kamailio and asterisk are bit complicated to implement
