### ISSUE TITLE
rtpengine - get the rtp stats when using custom id for calls

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1788]
### Description
We are passing custom unique identifier as callid to rtpengine commands. We are not getting any stastics using rtpstats, as rtpstats is sending query using the actual callid not the one we are sending in answer, offer, delete command.

#### Reproduction
send different callid in offer,answer,delete and use rtpstats export variable to populate the stastics of rtpengine.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Try to use a short title for bug reports and feature requests, it is supposed to be a 'subject' like meaning, not the explanation of the issue. Add the full details of the issue or the feature request in the description of the issue.

I marked it as a feature request. One needs to add a new variable that would allow to specify the identifier, something like `$rtpestatsx(idvalue)`.

**Comment by surendratiwari3** [comment]
@miconda sure. :-)
