### ISSUE TITLE
kamailio can't support send Rx_AAR for origin call

### ISSUE THREAD

**Issue by lsm808** [kamailio/kamailio#1793]
Hi All,

When kamailio(kamailio-5.0) receive 200 OK message, we need to send Rx_AAR for origin and term call.

Rx_AAR("MT_aar_reply", "origin","",2); for origin call
Rx_AAR("MT_aar_reply", "term","",2); for term call.

But from source code ims_qos_mod.c, we see lots of part like below to not support for a request.
Even we comments them, there are still lots of issues, could we support the scenarios like below:

when kamailio receive 200 OK, we can send Rx_AAR for term and origin call.

 //We don't ever do AAR on request for calling scenario...
                if (msg->first_line.type != SIP_REPLY) {
                                 // Added by vlv
                                 // LM_DBG("Can't do AAR for call session in request\n");
                                 // return result;
                }

**Comment by miconda** [comment]
Maybe @ngvoice can check and see if anything can be done for it.

**Comment by lsm808** [comment]
Hi Daniel,

Is there any update for the request: 1793?

Thanks,
Victor

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
