### ISSUE TITLE
Cannot use AVPs with t_check_status

### ISSUE THREAD

**Issue by que273** [kamailio/kamailio#1795]
### Description
If an AVP containing a regex is passed to the t_check_status function, it does not match.
Example:
```
failure_route[DEFAULT]
{
  $avp(FAILURE_CODES) = "5[0-9][0-9]";
  xlog("L_WARN", "Status code: $T_reply_code\n");
  if ($avp(FAILURE_CODES) != $null)
  {
    xlog("L_WARN", "resp codes regex: $avp(FAILURE_CODES)\n");
    if (t_check_status("$avp(FAILURE_CODES)"))
    {
      xlog("L_WARN", "t_check_status matched\n");
    }
  }
}
```
#### Reproduction
Using the code above in a failure_route should match a 500 response, but it does not.

### Possible Solutions
The fixup_t_check_status in tm.c:663 attempts to match FPARAM_AVP/FPARAM_SELECT/FPARAM_REGEX parameter types.
If another check for the FPARAM_PVS parameter type then the issue appears fixed

**Comment by henningw** [comment]
After the merge of #1796 I think this can be closed?
