### ISSUE TITLE
Error while initializing module carrierroute

### ISSUE THREAD

**Issue by Gkpanda321** [kamailio/kamailio#1798]
Ubuntu 18.04 & Kamailio V 5.1

I am unable to start kamailio services due the below error.

● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-01-08 22:36:49 UTC; 12s ago
  Process: 12933 ExecStart=/usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY -u $USER -g $GROUP (code=exited, status=255)
 Main PID: 12877 (code=exited, status=0/SUCCESS)

Jan 08 22:36:49 kamatl03 kamailio[12933]:              udp: kamatl03:5060
Jan 08 22:36:49 kamatl03 kamailio[12933]:              udp: localhost:5060
Jan 08 22:36:49 kamatl03 kamailio[12933]:              udp: localhost.localdomain:5060
Jan 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: INFO: carrierroute [carrierroute.c:213]: mod_init(): use file as configuration source
Jan 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: ERROR: carrierroute [carrierroute.c:215]: mod_init(): can't stat config file
Jan 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: ERROR: <core> [core/sr_module.c:986]: init_mod(): Error while initializing module carrierroute (/usr/lib/x86_64-linu
Jan 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Jan 08 22:36:49 kamatl03 systemd[1]: kamailio.service: Control process exited, code=exited status=255
Jan 08 22:36:49 kamatl03 systemd[1]: kamailio.service: Failed with result 'exit-code'.
Jan 08 22:36:49 kamatl03 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.

***********************Here is the Module Selection in configuraiton file***************

####### Modules Section ########
# set paths to location of modules (to sources or installation folders)
#!ifdef WITH_SRCPATH
mpath="/usr/local/lib64/kamailio/modules"
#!else
mpath="/usr/lib/x86_64-linux-gnu/kamailio/modules/"
#!endif

**Comment by ycaner06** [comment]
Hello, 
you can use mailling list to help about it. 
https://www.kamailio.org/w/mailing-lists/

your error related to configuration that cannot find carrierroute config file

`an 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: INFO: carrierroute [carrierroute.c:213]: mod_init(): use file as configuration source
Jan 08 22:36:49 kamatl03 /usr/sbin/kamailio[12955]: ERROR: carrierroute [carrierroute.c:215]: mod_init(): can't stat config file`

Have a look at the documents [carrierroute](http://kamailio.org/docs/modules/5.2.x/modules/carrierroute.html#idm1031358476)

**Comment by miconda** [comment]
As pointed by @ycaner06, this is an issue in your configuration file, setting either wrong path to config file for carrierroute or that file doesn't have proper access permissions. And this kind of problems have to be discussed on sr-users mailing list (link to it in the web page pointer by @ycaner06), the tracker here is for bugs in the source code or asking for new features.
