### ISSUE TITLE
SIPTrace trace_mode=1 does not respect hep_capture_id

### ISSUE THREAD

**Issue by blakemckeeby** [kamailio/kamailio#1838]
### Description
If modparam("siptrace", "trace_mode", 1) then setting hep_capture_id is ignored. 
Running version: kamailio 5.2.1

root@ingress01-nyj:/usr/local/kamailio/etc/kamailio# uname -a
Linux ingress01-nyj 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Troubleshooting
If I manually call sip_capture() or setflag(22), the capture_id is sent properly but if I use trace_mode=1, capture_id is always set to 1.

**Comment by miconda** [comment]
Same function for sending the HEP message is used in all cases and hep_capture_id is set there. Is it 1 for both incoming and outgoing SIP messages? Can you provide here all the params for siptrace module?

**Comment by blakemckeeby** [comment]
Hey @miconda, 

Thanks for looking into this. I verified using hep wireshark dissector that siptrace module was sending capture-id properly. Turns out it was on the sipcapture side. Updated capture side to solve.
