### ISSUE TITLE
Cannot use db_flatstore with siptrace module

### ISSUE THREAD

**Issue by achris** [kamailio/kamailio#1850]
### Description

The siptrace module attempts to do a query to check the schema version on startup, however 

#### Reproduction

Load `siptrace` and `db_flatstore` modules and set siptrace `db_url` to a `flatstore:` url.  siptrace will fail to load due to the inability to query for the table version.

### Possible Solutions

Since siptrace module only writes data and never reads, it can safely skip the schema version check if the db driver doesn't expose `DB_CAP_QUERY` or `DB_CAP_RAW_QUERY` capabilities.  This might apply to other "write only" modules as well but I haven't checked.

**Comment by miconda** [comment]
Can you try with current master branch or the patch referenced above? If all ok, it can be considered for backporting to make it work with write only db drivers.

**Comment by achris** [comment]
I tried it out and it works, thanks!
