### ISSUE TITLE
Move not core modules to own packages

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#1862]
### Description

Current kamailio package (checked via RPM) is contains lot of modules. Some of this is not important to include in every kamailio installation. May be create own packages for this modules and other in next 5.3 branch?
Modules examples:
```
benchmark.so
db_cluster.so
db_text.so
rtpengine.so
rtpproxy.so
sipcapture.so
siptrace.so
sipt.so
sms.so
smsops.so
ss7ops.so
```

**Comment by henningw** [comment]
It was discussed some time ago on a meeting, I think. So far we only difference for modules with- and without external library dependencies, as you know.

One idea would be to create a list of rarely used modules and then bundle them in a "kamailio-optional-modules" package or something like this. Another idea would be to bundle similar modules together: kamailio-ops-modules, kamailio-rtp-modules etc..

**Comment by oej** [comment]
If possible, can we organise Debian and RPM packaging to use the same setup?

**Comment by sergey-safarov** [comment]
We do not change anything until this is accepted by team.
If you already found difference, please fill a GitHub ticket. Difference
will be removed.

Sergey

ср, 6 мар. 2019 г., 15:21 Olle E. Johansson <notifications@github.com>:

**Comment by sergey-safarov** [comment]
I close this.
If kamailio team request it, then open again.
