### ISSUE TITLE
Topos - Via Restore

### ISSUE THREAD

**Issue by nicoonline** [kamailio/kamailio#1865]
### Description
Topos don't restore the via on the correct position towards the caller.

#### Reproduction

SIP/2.0 200 OK.
From: "N" <sip:+111111111@proxy1>;tag=as68c113e4.
To: <sip:0000000@proxy1>;tag=DHpXgm46a8QgQ.
Call-ID: 09e5173225bed77e5cd7247550ee5b60
CSeq: 104 BYE.
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY.
Supported: path, replaces.
Content-Length: 0.
Via: SIP/2.0/UDP IP:10060;rport=10060;branch=z9hG4bK7e7ab41c.
Contact: <sip:atpsh-5c710f13-962-c@IP>.

Should be 

SIP/2.0 200 OK.
Via: SIP/2.0/UDP IP:10060;rport=10060;branch=z9hG4bK7e7ab41c.
From: "N" <sip:+111111111@proxy1>;tag=as68c113e4.
To: <sip:0000000@proxy1>;tag=DHpXgm46a8QgQ.
Call-ID: 09e5173225bed77e5cd7247550ee5b60
CSeq: 104 BYE.
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY.
Supported: path, replaces.
Content-Length: 0.
Contact: <sip:atpsh-5c710f13-962-c@IP>.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.1.7 (x86_64/linux) 567df3
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 567df3 
compiled on 07:05:54 Feb 21 2019 with gcc 4.4.7

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
There is only one Via header, so it does not matter where it is located. In SIP it matters only the order of the headers with the same name. So what Kamailio does here is according to the specs. It is not a bug.

You can start a discussion on sr-users@lists.kamailio.org mailing list if you want more clarification.
