### ISSUE TITLE
Phonenum not in the package for RHEL

### ISSUE THREAD

**Issue by nicoonline** [kamailio/kamailio#1867]
### Description

It seems that the phonenum module is not packaged right now in the fedora/rhel packages. The best would be to create an issue about that on our github tracker, that it can be investigated and fixed.

#### Reproduction
-

#### Debugging Data

Ask to build the phonenum package in the RHEL tree.

**Comment by sergey-safarov** [comment]
I looked into [debian libphonenumber packaging](https://packages.debian.org/stretch/libphonenumber7) and [lib source repo](https://github.com/googlei18n/libphonenumber).
Then i also checked [fedora devel repo](https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/SRPMS/Packages/l/).

Looks as libphonenumber is not RPM packaged now inf Fedora/RHEL.
Also I found spec for fedora.
https://gil.fedorapeople.org/libphonenumber.spec
https://gil.fedorapeople.org/

Could you open ticket on Fedora bugtracker to package libphonenumber. Example of speck already exist.
When it be done, then we can package this module for Fedora.
Think for RHEL libphonenumber not be packaged so fast as for Fedora. But you can try.

**Comment by nicoonline** [comment]
https://repology.org/project/libphonenumber/versions

**Comment by nicoonline** [comment]
i found that :+1: 
https://bugzilla.redhat.com/show_bug.cgi?id=1200115

https://gil.fedorapeople.org/libphonenumber-7.1.1-1.fc23.src.rpm

**Comment by sergey-safarov** [comment]
Please check [`Absent in repositories`](https://repology.org/project/libphonenumber/versions) section.
package that you add link for Fedora 23 version now supported [28 and 29](https://fedoraproject.org/wiki/End_of_life). Thats is mean we cannot build kamailio for Fedora 23.

Also important. This library must be packaged info main dist repo or EPEL repo. Because to build kamailio RPM we use OpenSUSE build service. On this service we not able connect external repos.

Also i think is not good idea to use not wide used repos.

Why not create ticket on Fedora bugtracker?

**Comment by sergey-safarov** [comment]
I looked into Fedora bugtracker.
Looks we cannot add this module into Fedora, RHEL and CentOS.

May be install server on Debian?

**Comment by sergey-safarov** [comment]
Also look who is opened ticket and close [ticket 1200115](https://bugzilla.redhat.com/show_bug.cgi?id=1200115).
Looks as reporter closed this ticket, not RedHat team.

You can make second attempt to add `libphonenumber` into Fedora dist.

**Comment by nicoonline** [comment]
A python version has been imported to fc26
https://bugzilla.redhat.com/show_bug.cgi?id=1462983

**Comment by nicoonline** [comment]
https://rpms.remirepo.net/rpmphp/zoom.php?rpm=python-phonenumbers

**Comment by henningw** [comment]
The phonenum module expect a c/c++ library, and can't work (right now) with the python library, I think

**Comment by sergey-safarov** [comment]
I will package this lib on our repo as OBS subproject. After it I can package kamailio module.

**Comment by sergey-safarov** [comment]
You can try install 5.2.1 version after hour. If all ok then i will commit into master and 5.2 branch.
libphonenumber is packaged for [CentOS7 and Fedora 28 and 29](https://build.opensuse.org/package/show/home:kamailio:v5.2.x-rpms/libphonenumber) dists.
If you want same on OpenSUSE, then need suggestion how to package libphonemuber on this dist.

On RHEL we cannot build, because required libs is not available on OBS servers.

**Comment by nicoonline** [comment]
Hi Sergey,

Thanks for this but I’m running Centos 6 ?


Le 26 févr. 2019 à 21:54, sergey-safarov <notifications@github.com<mailto:notifications@github.com>> a écrit :


You can try install 5.2.1 version after hour. If all ok then i will commit into master and 5.2 branch.
libphonenumber is packaged for CentOS7 and Fedora 28 and 29<https://build.opensuse.org/package/show/home:kamailio:v5.2.x-rpms/libphonenumber> dists.
If you want same on OpenSUSE, then need suggestion how to package libphonemuber on this dist.

On RHEL we cannot build, because required libs is not available on OBS servers.

**Comment by sergey-safarov** [comment]
EPEL 6 contains  `protobuf-2.3.0`
EPEL 7 contains `protobuf-2.5.0`
Fedora 29 contains `protobuf-3.5.0`

On `CentOS 6` we have `libphonenum` compilation error
```
[  117s] /usr/include/google/protobuf/repeated_field.h: In function 'i18n::phonenumbers::PhoneNumberUtil::ValidationResult i18n::phonenumbers::<unnamed>::TestNumberLength(const std::string&, const i18n::phonenumbers::PhoneMetadata&, i18n::phonenumbers::PhoneNumberUtil::PhoneNumberType)':
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'google::protobuf::RepeatedField<Element>::RepeatedField(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:334: error: within this context
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'google::protobuf::RepeatedField<Element>::RepeatedField(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:336: error: within this context
[  117s] /usr/include/google/protobuf/repeated_field.h:130: error: 'void google::protobuf::RepeatedField<Element>::operator=(const google::protobuf::RepeatedField<Element>&) [with Element = int]' is private
[  117s] /home/abuild/rpmbuild/BUILD/libphonenumber-8.10.6/cpp/src/phonenumbers/phonenumberutil.cc:359: error: within this context
```
If you can find 'libphonenum' that works on `CentOS 6` and also can be compiled on `Fedora 29` then i can add this version to OBS repo.

**Comment by nicoonline** [comment]
And this ?
Name : protobuf-devel

**Comment by sergey-safarov** [comment]
This package is build by "obs://build_opensuse_org/home:kalyaka".
 Tomorrow kalyaka user will delete this repo and kamailio users will get broken dependency for phonenum module.
This is reason why we cannot use not standard repos.
Are you able fix libphonenum compilation on CentOS 6 and Fedora 29? Need to compile same version.

**Comment by nicoonline** [comment]
I compiled all the libs on my  centos 6.
http://altf2.blogspot.com/2012/10/building-google-libphonenumber-on-linux.html

I copied the so file into kamailio and loaded it.
 0(27632) DEBUG: <core> [core/cfg.y:1659]: yyparse(): loading module topos.so
 0(27632) DEBUG: <core> [core/sr_module.c:575]: load_module(): trying to load </usr/lib64/kamailio/modules/topos.so>

 0(27632) DEBUG: <core> [core/cfg.y:1659]: yyparse(): loading module libphonenumber.so
 0(27632) DEBUG: <core> [core/sr_module.c:575]: load_module(): trying to load </usr/lib64/kamailio/modules/libphonenumber.so>
 0(27632) ERROR: <core> [core/sr_module.c:403]: version_control(): no version info in module </usr/lib64/kamailio/modules/libphonenumber.so>: /usr/lib64/kamailio/modules/libphonenumber.so: undefined symbol: module_version

Any ideas ? :)

**Comment by nicoonline** [comment]
i build myself the package but i cannot load it from kamailio.
Any suggestions ?

 0(22344) DEBUG: <core> [core/cfg.y:1659]: yyparse(): loading module /usr/local/lib64/libphonenumber.so
 0(22344) DEBUG: <core> [core/sr_module.c:575]: load_module(): trying to load </usr/local/lib64/libphonenumber.so>
 0(22344) ERROR: <core> [core/sr_module.c:403]: version_control(): no version info in module </usr/local/lib64/libphonenumber.so>: /usr/local/lib64/libphonenumber.so: undefined symbol: module_version

**Comment by henningw** [comment]
You need to load the phonenum.so module and not the libphonenumber.so library in Kamailio.

**Comment by sergey-safarov** [comment]
package is added at
1. 356f9a837470434923165b7e3c627658b0c56b60 for master branch;
2. 63b43167b053f485557f930b344ab4b95b24e0b8 for 5.2 branch.

I closing this.
I you still want `phonenum` module for `CentOS6`, please package `libphonenum` for `CentOS6` and latest `Fedora`.
