### ISSUE TITLE
dialog module: option to choose between OPTIONS or INVITE on keep-alive

### ISSUE THREAD

**Issue by Fernandojdk** [kamailio/kamailio#1876]
### Description

Enable dialog module to user choose between INVITE or OPTIONS on send Re-INVITE on keep-alive

### Expected behavior

Make the dialog keep-alive through INVITE or OPTIONS. A user choice.

### Possible Solutions

In function dlg_send_ka of dlg_req_within.c:445, provide an option to choose the value from module config var, pv value, dlg flag, etc.

```
File: dlg_req_within.c

435    /* send keep-alive
436     * dlg - pointer to a struct dlg_cell
437     * dir - direction: the request will be sent to:
438     * 		DLG_CALLER_LEG (0): caller
439     * 		DLG_CALLEE_LEG (1): callee
440     */
441    int dlg_send_ka(dlg_cell_t *dlg, int dir)
442    {
443    	uac_req_t uac_r;
444    	dlg_t* di;
445    	str met = {"INVITE", 6};
446    	int result;
447    	dlg_iuid_t *iuid = NULL;
```

### Additional Information

Just for local tests, i changed dlg_req_within.c:445 from {"OPTIONS",7} to {"INVITE",6} and worked like a charm. I don't know if this change will affect other parts of kamailio.
Let me know if this change affect something else.

Thanks.

**Comment by miconda** [comment]
In which scenario would this be useful? The goal of keepalive is to detect if the endpoint is still connected and it is aware of the dialog. It is not going to work like a session timer re-INVITE, if you are looking for such kind of feature. The keepalive requests are sent with "invalid" CSeq.

**Comment by miconda** [comment]
Let's discuss this on sr-users@lists.kamailio.org mailing list to sort out why is needed, what are the side effects and the way to move forward.
