### ISSUE TITLE
TLS: Consider what's new and what's supported in OpenSSL

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#1878]
Our current TLS docs says:

"Compression is fully supported if you have a new enough OpenSSL version
   (starting with 0.9.8). Although there are some problems with zlib
   compression in currently deployed OpenSSL versions (up to and including
   0.9.8d, see openssl bug #1468), the TLS module will automatically
   switch to its own fixed version."

0.9.8 is no longer "new".

Postfix 3.4.0 release notes says:

"Postfix 3.4 drops support for OpenSSL 1.0.1 (end-of-life was December 31, 2016) and all earlier releases. Postfix 3.3 and earlier still support older OpenSSL APIs."

Should we consider doing the same?

**Comment by sergey-safarov** [comment]
Are you want drop support `0.9.8` only? Or `1.0.1` too?
What is reason to drop `1.0.1` version?

**Comment by oej** [comment]
See the postfix notes. 

From https://www.openssl.org/policies/releasestrat.html

> The next version of OpenSSL will be 3.0.0.
> Version 1.1.1 will be supported until 2023-09-11 (LTS).
> Version 1.1.0 will be supported until 2019-09-11.
> Version 1.0.2 will be supported until 2019-12-31 (LTS).
> Version 1.0.1 is no longer supported.
> Version 1.0.0 is no longer supported.
> Version 0.9.8 is no longer supported.

A big question is what current Linux LTS distros support

**Comment by oej** [comment]
Debian stretch comes with openssl 1.1.0 that has end of life 2019-09-11. Would use deprecating support for old non-supported versions of OpenSSL harm our packaging?

**Comment by sergey-safarov** [comment]
If version is not supported by openssl community or by dist, then it a good reason to drop support in kamailio.

**Comment by oej** [comment]
This is something we would implement only in next release, keeping backwards compatibility.
