### ISSUE TITLE
KSR.tm.t_load_contacts(): not able to clear the destination set (set before append_branch_uri_q)

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#1879]
### Description
We are using KEMI t_load_contacts to clear the destination set .
core.append_branch_uri_q(host2, "0.5")
core.append_branch_uri_q(host1, "0.6")
KSR.tm.t_load_contacts()
 KSR.tm.t_next_contacts()

But its retrying on 3 in failure route
first host1
second host2
third what we get in the initial request uri

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.2 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 7.3.0
```

* **Operating System**:

```
root@ip-10-130-74-111:/etc/kamailio# uname -a
Linux ip-10-130-74-111 4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ip-10-130-74-111:/etc/kamailio# 
```

**Comment by miconda** [comment]
R-URI is always the first branch and append_branch() functions add additional destinations. So if you do 2 append_branch(), you end up with 3 destinations.

If you want to modify r-uri, assign to $ru or use sbranch functions from pv module.

If you want to discuss further on this topic, write a message to sr-users@lists.kamailio.org mailing list.
