### ISSUE TITLE
Phonenum module not initialized with KEMI framework

### ISSUE THREAD

**Issue by balajeesv** [kamailio/kamailio#1883]
### Description
phonenum module is not working with KEMI framework, when debugged I found phonenum module functions "pv_parse_phonenum_name" "sr_phonenum_add_item" are not invoked with KEMI framework. With default config file these modules are invoked from config parser. 

I am using lua KEMI framework and included phonenum module

#### Reproduction
1. Any KEMI Framework
2. Include phonenum module
3. Test to validate phonenum

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
The function to parse phonenum pv name is called when the pv is looked up in the cache of pvs. Maybe you can describe what you actually get, eventually run kamailio with debug=3 in cofig and paste here all log messages printed by kamailio when you try to use the phonenum vars in kemi.

**Comment by miconda** [comment]
Closing, as the code looks ok and no follow up so far. If still an issue for you, reopen and attach additional debug info as requested in the previous comment.

**Comment by balajeesv** [comment]
Sorry for the delay response. I still have the same issue. I have kamailio.cfg file for configuration and Lua files for processing messages. What I observed is PHONUM module is not initialized during startup. And when using phonenum module it fails. I am invoking phonenum module in lua with "KSR.phonenum.match". Below are the logs

Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1655]: sr_kemi_lua_exec_func_ex(): param[0] for: isflagset is int: 1
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1651]: sr_kemi_lua_exec_func_ex(): param[0] for: match is str: +919876543210
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1651]: sr_kemi_lua_exec_func_ex(): param[1] for: match is str: src
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: phonenum [phonenum_pv.c:312]: phonenum_update_pv(): **container not found**: +919876543210
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:934]: lua_sr_pv_get_val(): pv get: $rc
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: <core> [core/pvapi.c:371]: pv_cache_add(): pvar [$rc] added in cache
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:934]: lua_sr_pv_get_val(): pv get: $phn(src=>valid)
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: phonenum [phonenum_pv.c:162]: pv_parse_phonenum_name(): phonenum [src] - key [valid]



In kamailio.cfg if I add some dummy route(as below) then Phonenum module is initialized and it is working as expected.
route[PHONENUM] {
        if($phn(src=>valid)==1) {
                xlog("dummy route\n");
        }
}

Please check this and let me know any further logs required.
