### ISSUE TITLE
Kamailio restarts.

### ISSUE THREAD

**Issue by aleczmw** [kamailio/kamailio#1896]
### Description
Reinstall HOMER, kamailio restart twice with ERR logs.

Scenario:
step1: Helm install homer. homer goes well.
step2: helm delete homer.
step3: helm install homer.
kamailio restarts twice, then kamailio goes well.

#### Reproduction
Scenario:
step1: Helm install homer. homer goes well.
step2: helm delete homer.
step3: helm install homer.
kamailio restarts twice, then kamailio goes well.

#### Debugging Data

```

Kamailio container detected MySQL is running & bootstrapped
config file doesn't exist, may not connect to SMTP SERVER
 0(19) INFO: <core> [core/sctp_core.c:75]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
 0(19) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
config file ok, exiting...
loading modules under config path: //usr/local/lib64/kamailio/modules/
Listening on
             udp: 0.0.0.0:9060
Aliases:

 0(20) INFO: <core> [core/sctp_core.c:75]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
 0(20) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
 0(20) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
 0(20) INFO: <core> [core/tcp_main.c:4671]: init_tcp(): using epoll_lt as the io watch method (auto detected)
loading modules under config path: //usr/local/lib64/kamailio/modules/
Listening on
             udp: 0.0.0.0:9060
             tcp: 0.0.0.0:39060
Aliases:

 0(20) INFO: sipcapture [sipcapture.c:459]: parse_table_names(): INFO: table name:sip_capture
 0(20) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 0(20) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 0(20) INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
 0(20) INFO: <core> [core/udp_server.c:203]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
 4(24) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 4(24) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 3(23) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 4(24) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 3(23) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 2(22) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 2(22) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 2 rank: 2 desc: [udp receiver child=1 sock=0.0.0.0:9060])
 1(21) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 1(21) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 2, pid 22, "udp receiver child=1 sock=0.0.0.0:9060"
 1(21) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 2(22) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 1(21) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 1 rank: 1 desc: [udp receiver child=0 sock=0.0.0.0:9060])
 1(21) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 1, pid 21, "udp receiver child=0 sock=0.0.0.0:9060"
 1(21) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 4(24) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 4 rank: 4 desc: [udp receiver child=3 sock=0.0.0.0:9060])
 3(23) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 4(24) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 4, pid 24, "udp receiver child=3 sock=0.0.0.0:9060"
 3(23) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 3 rank: 3 desc: [udp receiver child=2 sock=0.0.0.0:9060])
 7(27) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 7(27) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 5(25) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 7(27) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 7(27) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 7 rank: -1 desc: [timer])
 7(27) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 7, pid 27, "timer"
 7(27) CRITICAL: <core> [main.c:1688]: main_loop(): cannot fork timer process
 5(25) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 6(26) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 6(26) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 6(26) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 6(26) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 6 rank: -1 desc: [slow timer])
 6(26) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 6, pid 26, "slow timer"
 6(26) CRITICAL: <core> [main.c:1672]: main_loop(): cannot fork "slow" timer process
 5(25) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 5(25) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 5 rank: 5 desc: [udp receiver child=4 sock=0.0.0.0:9060])
 5(25) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 5, pid 25, "udp receiver child=4 sock=0.0.0.0:9060"
 5(25) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 9(29) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 9(29) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 9(29) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 9(29) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 9 rank: -1 desc: [RTIMER EXEC child=0 timer=ta])
 8(28) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 9(29) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 9, pid 29, "RTIMER EXEC child=0 timer=ta"
 9(29) ERROR: rtimer [rtimer_mod.c:171]: child_init(): failed to start timer routine as process
 9(29) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module rtimer (//usr/local/lib64/kamailio/modules/rtimer.so) (idx: 9 rank: 0 desc: [RTIMER EXEC child=0 timer=ta])
 9(29) ERROR: <core> [main.c:1706]: main_loop(): error in init_child
 8(28) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 8(28) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 8(28) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 8 rank: -1 desc: [secondary timer])
 8(28) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 8, pid 28, "secondary timer"
 8(28) ERROR: <core> [core/timer_proc.c:418]: sr_wtimer_start(): wtimer starting failed
 8(28) CRITICAL: <core> [main.c:1698]: main_loop(): Cannot start wtimer
 3(23) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 3, pid 23, "udp receiver child=2 sock=0.0.0.0:9060"
 4(24) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
15(35) CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 6
15(35) CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 7
 3(23) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
11(31) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
12(32) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
11(31) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 21 exited normally, status=255
 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 22 exited normally, status=255
12(32) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool11(31) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 26 exited normally, status=255
11(31) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 11 rank: 7 desc: [tcp receiver (generic) child=1])
 0(20) INFO: <core> [main.c:768]: handle_sigs(): terminating due to SIGCHLD
12(32) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
11(31) ERROR: <core> [core/pt.c:477]: fork_tcp_process(): init_child failed for process 11, pid 31, "tcp receiver (generic) child=1"
12(32) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 12 rank: 8 desc: [tcp receiver (generic) child=2])
 4(24) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 8(28) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
13(33) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 3(23) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 7(27) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
15(35) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
14(34) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
10(30) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 0(20) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
```

#### Log Messages

Kamailio container detected MySQL is running & bootstrapped
config file doesn't exist, may not connect to SMTP SERVER
 0(19) INFO: <core> [core/sctp_core.c:75]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
 0(19) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
config file ok, exiting...
loading modules under config path: //usr/local/lib64/kamailio/modules/
Listening on
             udp: 0.0.0.0:9060
Aliases:

 0(20) INFO: <core> [core/sctp_core.c:75]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
 0(20) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
 0(20) WARNING: <core> [core/socket_info.c:1314]: fix_hostname(): could not rev. resolve 0.0.0.0
 0(20) INFO: <core> [core/tcp_main.c:4671]: init_tcp(): using epoll_lt as the io watch method (auto detected)
loading modules under config path: //usr/local/lib64/kamailio/modules/
Listening on
             udp: 0.0.0.0:9060
             tcp: 0.0.0.0:39060
Aliases:

 0(20) INFO: sipcapture [sipcapture.c:459]: parse_table_names(): INFO: table name:sip_capture
 0(20) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 0(20) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 0(20) INFO: <core> [core/udp_server.c:153]: probe_max_receive_buffer(): SO_RCVBUF is initially 212992
 0(20) INFO: <core> [core/udp_server.c:203]: probe_max_receive_buffer(): SO_RCVBUF is finally 425984
 4(24) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 4(24) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 3(23) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 4(24) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 3(23) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 2(22) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 2(22) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 2 rank: 2 desc: [udp receiver child=1 sock=0.0.0.0:9060])
 1(21) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 1(21) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(22) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 2, pid 22, "udp receiver child=1 sock=0.0.0.0:9060"
 1(21) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 2(22) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 1(21) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 1 rank: 1 desc: [udp receiver child=0 sock=0.0.0.0:9060])
 1(21) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 1, pid 21, "udp receiver child=0 sock=0.0.0.0:9060"
 1(21) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 4(24) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 4 rank: 4 desc: [udp receiver child=3 sock=0.0.0.0:9060])
 3(23) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 4(24) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 4, pid 24, "udp receiver child=3 sock=0.0.0.0:9060"
 3(23) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 3 rank: 3 desc: [udp receiver child=2 sock=0.0.0.0:9060])
 7(27) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 7(27) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 5(25) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 7(27) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 7(27) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 7 rank: -1 desc: [timer])
 7(27) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 7, pid 27, "timer"
 7(27) CRITICAL: <core> [main.c:1688]: main_loop(): cannot fork timer process
 5(25) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 6(26) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 6(26) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 6(26) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 6(26) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 6 rank: -1 desc: [slow timer])
 6(26) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 6, pid 26, "slow timer"
 6(26) CRITICAL: <core> [main.c:1672]: main_loop(): cannot fork "slow" timer process
 5(25) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 5(25) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 5 rank: 5 desc: [udp receiver child=4 sock=0.0.0.0:9060])
 5(25) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 5, pid 25, "udp receiver child=4 sock=0.0.0.0:9060"
 5(25) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
 9(29) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 9(29) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 9(29) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 9(29) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 9 rank: -1 desc: [RTIMER EXEC child=0 timer=ta])
 8(28) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
 9(29) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 9, pid 29, "RTIMER EXEC child=0 timer=ta"
 9(29) ERROR: rtimer [rtimer_mod.c:171]: child_init(): failed to start timer routine as process
 9(29) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module rtimer (//usr/local/lib64/kamailio/modules/rtimer.so) (idx: 9 rank: 0 desc: [RTIMER EXEC child=0 timer=ta])
 9(29) ERROR: <core> [main.c:1706]: main_loop(): error in init_child
 8(28) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 8(28) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 8(28) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 8 rank: -1 desc: [secondary timer])
 8(28) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 8, pid 28, "secondary timer"
 8(28) ERROR: <core> [core/timer_proc.c:418]: sr_wtimer_start(): wtimer starting failed
 8(28) CRITICAL: <core> [main.c:1698]: main_loop(): Cannot start wtimer
 3(23) ERROR: <core> [core/pt.c:340]: fork_process(): init_child failed for process 3, pid 23, "udp receiver child=2 sock=0.0.0.0:9060"
 4(24) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
15(35) CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 6
15(35) CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 7
 3(23) CRITICAL: <core> [main.c:1611]: main_loop(): Cannot fork
11(31) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
12(32) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"
11(31) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 21 exited normally, status=255
 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 22 exited normally, status=255
12(32) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool11(31) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
 0(20) ALERT: <core> [main.c:740]: handle_sigs(): child process 26 exited normally, status=255
11(31) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 11 rank: 7 desc: [tcp receiver (generic) child=1])
 0(20) INFO: <core> [main.c:768]: handle_sigs(): terminating due to SIGCHLD
12(32) ERROR: sipcapture [sipcapture.c:1150]: child_init(): unable to connect to database [mysql://homer_user:homer_password@10.254.123.234:3306/homer_data] from capture_mode param.
11(31) ERROR: <core> [core/pt.c:477]: fork_tcp_process(): init_child failed for process 11, pid 31, "tcp receiver (generic) child=1"
12(32) ERROR: <core> [core/sr_module.c:925]: init_mod_child(): error while initializing module sipcapture (//usr/local/lib64/kamailio/modules/sipcapture.so) (idx: 12 rank: 8 desc: [tcp receiver (generic) child=2])
 4(24) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 8(28) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
13(33) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 3(23) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 7(27) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
15(35) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
14(34) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
10(30) INFO: <core> [main.c:823]: sig_usr(): signal 15 received
 0(20) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```

version: kamailio 5.0.6 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled on 09:47:19 Mar 18 2019 with gcc 4.8.5

```

* **Operating System**:

```
Centos7
```

**Comment by sergey-safarov** [comment]
Are you speak about `sipcapture.service`?
Please update this strings https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/obs/sipcapture.service#L3-L4 on your local unit
to value
```
Wants=network-online.target mariadb,service
After=network-online.target mariadb,service
```
Then you can start sipcapture
```
systemctl daemon-reload
systemctl start sipcapture.service
```
After this please give feedback

**Comment by aleczmw** [comment]
Thanks for your reply.

Kamailio is started in container.
In docker/container, there is no sipcapture.service.

What reason for Kamailio restart twice (always twice)?
What info can we find from the log?

**Comment by sergey-safarov** [comment]
What is docker image you tested?
Could you test image without embedded MySQL database? With external container database.

**Comment by aleczmw** [comment]
the testing is without embedded mysql.
external db is maridb.
maridb pod is always running, 
step1, helm install homer, step 2, helm delete homer. step3 helm install homer. we saw kamailio restarts twice.


kamailio docker image
build docker image via kamailo source code.
cp kamailio src to container,
run make in container
make clean, make all, make install

**Comment by sergey-safarov** [comment]
please make test using `kamailio/kamailio-ci:master-alpine.debug` image.
And please paste here diff to default config. I expect you testing using default kamailio config.

**Comment by aleczmw** [comment]
we modified kamailio.cfg to use nosip module.
at the same time, we developped h248 parser and store in nosip module.

the image mentioned above, may not meet our requirement.

kamailio.cfg diff should be uploaded later.

**Comment by sergey-safarov** [comment]
In this ticket we troubleshooting MySQL database connections issue.
To solve is want use only default config images.
When we fix MySQL than you can add other other modules and retest.
Please make test using standard image and default config.

**Comment by aleczmw** [comment]
Thanks for your infomation.
i will have a try based on your input.

my consion：

Is the issue ‘kamailio restart twice’ related to mysql connection?

we can see SIG 15 in kamailio log. who triggers it, connection failure?

Although kamailio starts twice, it goes to work at last.  looks like it connects mysql sucessfully at last. does connection failure trigger kamailio restart（or trigger sig 15）?

**Comment by sergey-safarov** [comment]
I prefer solve errors at start of log file. Error at end of log is related to prevision in many cases.
Also related to this string
```
4(24) CRITICAL: [main.c:1611]: main_loop(): Cannot fork
```
you may try sart kamailio using command
```
kamailio -DD -E
```

**Comment by miconda** [comment]
This does not look as an issue with kamailio code or with included tools.

If it is just a discussion about how to use kamailio inside docker, then use the sr-users@lists.kamailio.org mailing list.

If it is an issue with how the docker image for kamailio is built, then the projects are:

  * https://github.com/kamailio/kamailio-docker
  * https://github.com/kamailio/kamailio-ci

Discussing on issue tracker about using kamailio results unrelated traffic to sr-dev mailing list.

I am closing this one here. If I am wrong with my understanding of what has been discussed here so far and you think it is an issue that belongs here, then reopen and give more details about what you think it is an issue related to kamailio code or its tools.
