### ISSUE TITLE
crash in slow timer

### ISSUE THREAD

**Issue by lazedo** [kamailio/kamailio#1897]
### Description

slow_timer proc exited with crash, kamailio kept running but tm transaction kept accumulating which will lead to shared memory exhaustion and crash.

in line 1131 `ret=tl->f(*ticks, tl, tl->data);` f is null, reason of crash

#### Reproduction

happens from time to time, not a way to reliably reproduce it.

#### Debugging Data

```
#0  0x0000000000000000 in ?? ()
#1  0x000000000049f648 in slow_timer_main () at core/timer.c:1131
#2  0x0000000000424b84 in main_loop () at main.c:1685
#3  0x000000000042b9d3 in main (argc=16, argv=0x7ffe568bcd08) at main.c:2663
(gdb) frame 1
#1  0x000000000049f648 in slow_timer_main () at core/timer.c:1131
1131						ret=tl->f(*ticks, tl, tl->data);
(gdb) list
1126	#ifdef TIMER_DEBUG
1127					tl->expires_no++;
1128	#endif
1129					SET_RUNNING_SLOW(tl);
1130					UNLOCK_SLOW_TIMER_LIST();
1131						ret=tl->f(*ticks, tl, tl->data);
1132						/* reset the configuration group handles */
1133						cfg_reset_all();
1134						if (ret==0){
1135							/* one shot */
(gdb) p *tl
$1 = {next = 0x0, prev = 0x0, expire = 938928580, initial_timeout = 80, data = 0x0, f = 0x0, flags = 768, slow_idx = 45488}
(gdb) info locals
n = 12
ret = 4294967295
tl = 0x7fb2d3c860d0
i = 432
__func__ = "slow_timer_main"

```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
5.1.7
```

* **Operating System**:

```
centos 7
```

**Comment by miconda** [comment]
This could be the effect of the issue fixed by commit 7e78723d8f34d5f459417742f56d38c93566d47d (pushed in 5.1 couple of days ago, while in master had it since end of February). Can you try using the latest 5.1 branch? A new release in that branch will be done soon.

**Comment by lazedo** [comment]
@miconda we are trying the commit and haven't seen more crashes but these were very random.

**Comment by miconda** [comment]
Reopen if occurs again, adding new details based on used source code. Closing now as it gets aged here.
