### ISSUE TITLE
OpenSUSE RPMs don't create the kamailio group

### ISSUE THREAD

**Issue by que273** [kamailio/kamailio#1898]
### Description
The RPMs provided at https://download.opensuse.org/repositories/home:/kamailio:/v5.1.x-rpms/CentOS_7/ use a different spec file from the other RPM based OS's which does not create the "kamailio" group and uses "daemon" instead.
This does not match the tmpfiles.d and other service files that assume files are owned by the "kamailio group". This means the /run/kamailio directory is deleted periodically.

Can this spec file be updated?

### Additional Information

kamailio-5.1.7-4.el7

* **Operating System**:

CentOS 7

**Comment by sergey-safarov** [comment]
i back ported four commits into 5.1 branch.
56e558a6242d033c8372ce6559578339795d940c
3ba84422d02d21e88d18b7bc7b70d3061d532f11
41316c29677b6a6eac25bda6383f72905a4a32bc
863a91854eb65c8b5bc49ef62f01dcf9a8b586d0

And regenerated RPMs on OBS.

Please make test on clean VM.
If issue exist please reopen.
