### ISSUE TITLE
event_route[dialog:end] is not exec'd on dialog terminated by dlg.end_dlg

### ISSUE THREAD

**Issue by krieger-od** [kamailio/kamailio#190]
We want it for CDR fields setting. Currently CDR is written or such forcefully terminated calls, but it lacks some post-processing which we have in event_route[dialog:end].
Whoever is going to work on this - please leave your wallet info (e.g. paypal) for my thanksgiving.

**Comment by miconda** [comment]
Should be implemented by #246.
