### ISSUE TITLE
Listen addresses longer than 72 chars.

### ISSUE THREAD

**Issue by niallmcandrew** [kamailio/kamailio#1901]
### Description

Providing Kamailio with a listen address longer than 72 chars will cause Kamailio to crash with an error in `fix_sock_str`. Looking at the code it appears that the `fix_sock_str` function only assumes it is being passed IP addresses so the buffer length is configured for the length of an IPv6 address represented as a string. (`MAX_SOCKET_STR`)

It appears to include the portion of the string representing the port as can be seen in the two example config lines below.

Domain names can be up to 256 chars long and can contain labels up to 63 chars long so the current implementation doesn't align with the DNS spec.

#### Reproduction

The problem can be reproduced by adding the following line to the `kamailio.cfg` and running `kamailio` with the `-c` config check option.
```
listen=tcp:eth0:5060 advertise "example.example.example.example.example.example.example.example.exa":50
listen=tcp:eth0:5061 advertise "example.example.example.example.example.example.example.example.e":5060
```

#### Debugging Data
N/A

#### Log Messages

```
 0(100) ERROR: <core> [core/socket_info.c:376]: socketinfo2str(): Destionation buffer too short
 0(100) BUG: <core> [core/socket_info.c:443]: fix_sock_str(): fix_sock_str: Error in socket to str
 0(100) ERROR: <core> [core/socket_info.c:1841]: fix_all_socket_lists(): fix_socket_list tcp failed
failed to initialize list addresses
```

#### SIP Traffic
N/A

### Possible Solutions
Don't use listen addresses longer than 70 chars.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.2 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 6.3.0
```

* **Operating System**:
Debian container running on Arch Linux host.
```
Debian GNU/Linux 9 (stretch)
Linux 75dbf08c8303 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
I pushed commit e6a551a913023421af6f5a4dacb87c989f4e95df to allow advertised address to be longer. It is in master branch only.

No time to test and see if works fine. If you can do it, report the results here to see if anything else needs to be done.

**Comment by niallmcandrew** [comment]
For the examples above I can confirm this is now working when building from master. Thanks.
