### ISSUE TITLE
kamailio log format

### ISSUE THREAD

**Issue by aleczmw** [kamailio/kamailio#1902]
^[[0;39;49m^[[0;31;49m **_5_****(25)** ERROR: nosip 
^[[0;39;49m^[[0;31;49m **_4_****(24)** ERROR: nosip

Hello,

There is a kamailio log format consultancy.

what does the highlighted 5, 4 and (25) (24) mean?

Thanks.

**Comment by aleczmw** [comment]
More question.

i developed megaco parser and store in nosip module.
when kamailio receives a msg, it prints the number of messages received by kamailio.


My question is that why the number of message count is printed 5 times?
Is that mean one message is handled by 5 processes at same time?
 

 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[**234**]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[**234**]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[**234**]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[**234**]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[**234**]!
 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[235]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[235]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[235]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[235]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[235]!
 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[236]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[236]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[236]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[236]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[236]!
 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[237]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[237]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[237]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[237]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[237]!
 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[238]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[238]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[238]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[238]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[238]!
 1(21) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[239]!
 2(22) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[239]!
 5(25) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[239]!
 3(23) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[239]!
 4(24) ERROR: nosip [megaco_capture.c:745]: megaco_capture(): megaco msg[239]!

**Comment by miconda** [comment]
This kind of questions belong either to sr-dev or sr-users mailing lists. The tracker here is intended only for bug reports of Kamailio code or requests for new features.

Then, to close this one: first value is the index of the process and the second is the pid. See `kamctl ps`. For further questions, use mailing lists.
