### ISSUE TITLE
Run kamcmd failed.

### ISSUE THREAD

**Issue by aleczmw** [kamailio/kamailio#1909]
#### Reproduction

[root@kamailio-665b74f766-sv4mx /]# kamcmd
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]

#### Debugging Data

```
[root@kamailio-665b74f766-sv4mx /]# kamcmd
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]
```

#### Log Messages
[root@kamailio-665b74f766-sv4mx /]# kamcmd
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[root@kamailio-665b74f766-sv4mx /]# kamailio -v
version: kamailio 5.0.6 (x86_64/linux)
flags: STATS: Off, EXTRA_DEBUG, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 4194304, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled on 06:55:33 Mar 27 2019 with gcc 4.8.5
```

* **Operating System**:

```
Kamailio docker container.
[root@kamailio-665b74f766-sv4mx /]# uname -a
Linux kamailio-665b74f766-sv4mx 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by sergey-safarov** [comment]
How kamailio is installed?
Source, rpm, deb.

**Comment by aleczmw** [comment]
source（make install）in container

**Comment by aleczmw** [comment]
I'd like to use kamcmd to check one script counter via kamcmd.
The following is all of the cmd execution results, look like not all of the commands runs sucessfully. 

[root@kamailio-665b74f766-whhfv /]# cd /usr/local/sbin/
[root@kamailio-665b74f766-whhfv sbin]# ls
kamailio  kamcmd  kamctl  kamdbctl
**[root@kamailio-665b74f766-whhfv sbin]# ./kamcmd
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]**
**[root@kamailio-665b74f766-whhfv sbin]# ./kamdbctl
ERROR: database engine not specified, please setup one in the config script**
**[root@kamailio-665b74f766-whhfv sbin]# ./kamctl
which: no gdb in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/)**
./kamctl 5.0.0

Existing commands:

 -- command 'start|stop|restart|trap'

 trap ............................... trap with gdb Kamailio processes
 restart ............................ restart Kamailio
 start .............................. start Kamailio
 stop ............................... stop Kamailio

**Comment by miconda** [comment]
This is either an access error (not enough privileges) or kamailio is not running. Anyhow, all these above messages are related to use of kamailio and related tools, not to bugs of kamailio or tools code. Address your questions to sr-users@lists.kamailio.org mailing list.
