### ISSUE TITLE
[htable] some sht indexes and values gets duplicated

### ISSUE THREAD

**Issue by fr6nco** [kamailio/kamailio#191]
Hello,

I have noticed, that indexes with special chars gets duplicated in htables-es.

When I insert to htable a value with index like:
`1335199467::3339-516-53201517440-VM1-1-212.232.17.91::to:: some_value`

then I dump the elements using fifo sht_dump I see the same entry duplicated with slightly modfied index:
`1335199467::3339-516-53201517440-VM1-1-212.232.17.91::to:: some_value`
`1335199467::3339-516-53201517440-VM1-1-212_232_17_91::to:: some_value`

So to be clear.
Only 1 value is inserted and when I dump it I see 2 values in the htable. This happens when indexes with a dot are inserted to a htable and makes me some trouble when doing replication over multiple kamailios.

I consider it as a bug as using htable.sets I cant insert the both values to another node when doing manual replication of htableses.

**Comment by miconda** [comment]
What is the command you use to insert the items?

From the dump, I see that the second key has '_' (underline) instead of '.' (dot).

**Comment by fr6nco** [comment]
Hello Daniel,

actually found out, it was my fault.
When sending the htable data to the second kamailio proxy via PHP (source kamailio htable.dump -> second kamailio htable.sets), dots were replaced by a _ and the "new" indexes created by the php script were inserted to the second kamailio and those were replicated via dmq back to the source kamailio proxy.

Thats the reason why indexes were duplicated on the source kamailio.

Not a bug, sorry, its solved :)
Tomas Boros
