### ISSUE TITLE
How to add timestamp when kamailio dumps?

### ISSUE THREAD

**Issue by aleczmw** [kamailio/kamailio#1920]
here is the current kamailio log example.

### 0(20) INFO: sipcapture [sipcapture.c:459]: parse_table_names(): INFO: table name:sip_capture
 0(20) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"

could we add timestamp for printing log?
example:
0(20) **### Y/M/D/H/M/S** INFO: sipcapture [sipcapture.c:459]: parse_table_names(): INFO: table name:sip_capture
 0(20) ERROR: db_mysql [km_my_con.c:129]: db_mysql_new_connection(): driver error: Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 "Connection timed out"

**Comment by aleczmw** [comment]
Could we add the log timestamp by configuration?

**Comment by sergey-safarov** [comment]
As workarroud you can start kamailio (or docker container) as service unit. Then systemd logs will contain timestamp.
Example
```log
[root@node0 ~]# journalctl -flu kamailio-docker
-- Logs begin at Mon 2019-04-01 00:27:18 GMT. --
Apr 03 01:50:11 node0.docker.rcsnet.ru sh[17746]: 68(76) INFO: <script>: 6F3E-C434-46684819C4E9AF592AFC-001@SipHost|log|from sip:1471@client-1143.rcsnet.ru
Apr 03 01:50:11 node0.docker.rcsnet.ru sh[17746]: 68(76) INFO: <script>: 6F3E-C434-46684819C4E9AF592AFC-001@SipHost|log|to sip:1471@client-1143.rcsnet.ru
Apr 03 01:50:11 node0.docker.rcsnet.ru sh[17746]: 68(76) INFO: <script>: 6F3E-C434-46684819C4E9AF592AFC-001@SipHost|log|originated from external sources
Apr 03 01:50:11 node0.docker.rcsnet.ru sh[17746]: 68(76) INFO: <script>: 6F3E-C434-46684819C4E9AF592AFC-001@SipHost|end|issued auth challenge to new registration for sip:1471@client-1143.rcsnet.ru 94.45.179.35:5060
Apr 03 01:50:11 node0.docker.rcsnet.ru sh[17746]: 62(70) INFO: <script>: 6F3E-C434-46684819C4E9AF592AFC-001@SipHost|start|received udp request REGISTER sip:client-1143.rcsnet.ru:5060
```

**Comment by aleczmw** [comment]
@sergey-safarov 
thanks for your response.

we use kubectl log to get kamailo container's log

kubectl logs kamailio-665b74f766-kqjtp

logs show as below:

**10(29) DEBUG: <core> [db_res.c:138]: db_free_result(): freeing result set at 0x7f12fa02cb88
10(29) DEBUG: <core> [db_res.c:120]: db_new_result(): allocate 56 bytes for result set at 0x7f12fa02cb88
10(29) DEBUG: sqlops [sql_api.c:271]: sql_do_query(): no result after query
10(29) DEBUG: <core> [db_res.c:79]: db_free_columns(): freeing 0 columns
10(29) DEBUG: <core> [db_res.c:138]: db_free_result(): freeing result set at 0x7f12fa02cb88
10(29) DEBUG: <core> [core/select.c:412]: run_select(): Calling SELECT 0x7f12fa0851c8
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/usr_avp.c:631]: destroy_avp_list(): destroying list (nil)
10(29) DEBUG: <core> [core/xavp.c:446]: xavp_destroy_list(): destroying xavp list (nil)**


It is hard for us to debug issues without log timestamp.

In order to print log timestamp, is it available to add ctime()/gtime() for LM_DBG, LM_ERR (all kinds of log MACRO)?

**Comment by sergey-safarov** [comment]
you can try `--timestamps` options
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Comment by aleczmw** [comment]
@sergey-safarov 
thanks for your response.
