### ISSUE TITLE
git master siptrace regression in sip_trace function

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#1942]
Tracking ticket for the discussion on sr-dev list "current git master branch issue with the siptrace module".

It seems that the changes from #1912 introduced a regression. The sip_trace() should work without duplicate uri because it can write directly to the database. It should be fixed to work without those parameters for module or function.

Error message from logs:
/usr/bin/sip-proxy[1659]: ERROR: siptrace [siptrace.c:908]: w_sip_trace3(): no duplicate_uri modparam nor duplicate uri sip_trace() argument provided!

**Comment by ionutionita92** [comment]
sorry for this, will fix it.

**Comment by miconda** [comment]
Closing, expected to be fixed after the last commits. If not, a new issue should be opened with the symptoms of the master branch.
