### ISSUE TITLE
KEMI: htable.sht_setxs() ignores expiration parameter on 5.2.2

### ISSUE THREAD

**Issue by towe75** [kamailio/kamailio#1943]
### Description

The KEMI function htable.sht_setx() allows us to set a expiration parameter "exval":

`int sht_setxs(str "htname", str "itname", str "itval", int exval)`

Setting "exval" shows no effect, however.

### Possible Solutions

It seems that the "exval" parameter is not passed into ht_set_cell() at all:

`if(ht_set_cell(ht, itname, AVP_VAL_STR, &isval, 1)!=0) {`

So it should be enough to fix this function call. 

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.2 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 5.3.1
```

**Comment by miconda** [comment]
Should be now fixed in master and 5.2 branches. If not, reopen.
