### ISSUE TITLE
RFE: RHEL 8 builds in openSUSE build service with app_python3

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#1949]
Consider this as a placeholder for requesting RHEL 8 / CentOS 8(TBD - not yet released) builds in OBS.

RHEL 8 now ships with Python 3.6 so `app_python3` can be included the the RPMs.

Thank you.

**Comment by sergey-safarov** [comment]
Hi Daniel @miconda
This ticket depends of other. Could you look https://github.com/kamailio/kamailio/issues/1959

**Comment by sergey-safarov** [comment]
app_python3 is packaged on:

1. CentOS 7;
1. Fedora 28, 29, 30;
1. OpenSUSE all supported version.

RHEL cannot be build, because some deps is not present on OBS service.
But you can build by self using this [instruction](https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/rhel/README.md).

Kamailio for RHEL 8 will be packaged when RHEL 8 will be available on OBS service.

**Comment by systemcrash** [comment]
CentOS 8 currently seems to be out of action:

https://build.opensuse.org/project/monitor/home:kamailio:v5.3.x-rpms
https://download.opensuse.org/repositories/home:/kamailio:/v5.3.x-rpms/CentOS_8

**Comment by sergey-safarov** [comment]
Now OBS we still have error

> nothing provides mysql-devel, nothing provides python2, nothing provides python2-devel, nothing provides python3, nothing provides python3-devel, nothing provides ruby-devel, nothing provides python2-rpm-macros needed by epel-rpm-macros

Looks as some important packages not exist on `CentOS8 baseos` repo

**Comment by systemcrash** [comment]
CentOS 8 

dnf search python2-devel.x86_64 (exists)
dnf search mysql-devel.x86_64 (exists)
dnf search python2.x86_64 (exists)
dnf search python3... 
dnf search python36.x86_64 (exists)
dnf search python3-devel...
dnf search python36-devel.x86_64 (exists)
dnf search ruby-devel.x86_64 (exists)
dnf search python2-rpm-macros.noarch (exists)

Deps only need to update 2 things and everything will 'work'

**Comment by sergey-safarov** [comment]
Looks as you checked package availability using your PC.
Please check `OBS` logs
https://build.opensuse.org/package/show/home:kamailio:v5.3.x-rpms/kamailio53

**Comment by systemcrash** [comment]
Yes - which means those packages are available via standard CentOS 8 repos. 

I see no logs other than the same as what you pasted. (?) login required?

**Comment by sergey-safarov** [comment]
`OBS` use own repo mirrors.
To check build status need move mouse over red build status message.
On page thti provided. No login required.

**Comment by systemcrash** [comment]
What's the difference - it says EPEL packages - with EPEL enabled, I can access all of those packages, except for:

python3-devel
python3

neither exist, those should be instead:

python36
python36-devel

**Comment by sergey-safarov** [comment]
Please try download or install `python3-devel` or `python3`.
You will find that packages `python3-devel` and `python36-devel` is same.
Same about `python3` and `python36`.

I closing ticket comments.
Please track ticket 2084
