### ISSUE TITLE
Siptrace patch review

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#1955]
### Description

A patch was pushed to master branch to enable use of trace_type in the ki_sip_trace_dst_cid_flag(), following the latest additions to the module. It seemed that the trace type was used only for kamailio.cfg functions, because inside ki_sip_trace_dst_cid_flag() the trace_type was parsed and stored in local variable, but it was not used further.

I open this issue for review, to be sure something was not overlooked, the commit is:

  * e8d765610c6926cc6cb4dfa490595214a3680f97

@ionutionita92 - can you have a look and eventually do some tests to be sure it still works as expected for kamailio.cfg functions?

There is one more aspect to clarify. The trace info structure is alocated in shared memory, but some of its fields (duplicate uri and correlation id) were set to addresses of function parameters/local variables. The code was relocated and now is at the following lines:

  * https://github.com/kamailio/kamailio/blob/master/src/modules/siptrace/siptrace.c#L867-L875

Is it safe to do it like this? Are the fields used in this case only in current process and the callbacks use the variant stored in AVP?

Speaking of serializing to a string stored in AVP, it might be better to just have a structure compacted with all content in shared memory and stored in an XAVP -- the xavp can store a pointer and also have in its structure the callback to free the pointer.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
Git Master Branch
```

* **Operating System**:

```
(paste your output here)
```

**Comment by ionutionita92** [comment]
I've looked over, everything looks fine. I'll run some tests just to make sure everything is fine. Regarding your concerns, in-dialog requests are ok since string values are taken from dlg_val, but there's a bug for current transaction messages that may end up in a different process. I will fix it. Also nice to hear about xavp.

**Comment by miconda** [comment]
For reference, an example of adding an XAVP with data pointing to share memory and a callback to free it is at:
  * https://github.com/kamailio/kamailio/blob/master/src/modules/rtjson/rtjson_routing.c#L159-L166

Data struct being constructed a bit above there:
  * https://github.com/kamailio/kamailio/blob/master/src/modules/rtjson/rtjson_routing.c#L147-L148
