### ISSUE TITLE
How to define IP Trunk in kamailio

### ISSUE THREAD

**Issue by maryamb99** [kamailio/kamailio#1960]
Hello everyone,

I install and setup an IMS Network by kamailio-5.2.2 . I have p-cscf, i-cscf and s-cscf in three different systems . my Hss is Fokus. Registration and call between subscribers of network works successfully . now I want to define IP Trunk in my network which can pass transfer and external subscribers calls through my IMS network. I don't know how to define IP Trunk

**Comment by miconda** [comment]
This is the tracker for bugs in the C code and proposed new features. For support and questions on how to use kamailio, join the sr-users mailing list and start there the discussion:

  * https://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-users
