### ISSUE TITLE
[Low Priority] Build warning with gcc-9.1.1

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#1965]
Building on Fedora 30 x86_64, the following warning appears: `
BUILDSTDERR: Makefile.defs:1014: You are using an old and unsupported gcc version  (9.1.1), compile at your own risk!`

**Comment by sergey-safarov** [comment]
Build log [example](https://build.opensuse.org/public/build/home:kamailio:v5.2.x-rpms/Fedora_30/x86_64/kamailio52/_log)

**Comment by miconda** [comment]
Try with master branch, I just pushed a patch for it. If still an issue, reopen.

Patch will be backported.

**Comment by sergey-safarov** [comment]
I looked this commit
Think missed ',' in some stirngs

**Comment by miconda** [comment]
Those parts are comments, being after `#`, to know the corresponding `if...` for the respective `endif`, so it is not breaking the Makefile. Commas can be added, if someone wants.
