### ISSUE TITLE
t_set_fr only works with UDP

### ISSUE THREAD

**Issue by bpbp-boop** [kamailio/kamailio#1966]
### Description
Using t_set_fr within the LOCATION section of a slightly modified default kamailio.cfg only works if the contact is using UDP and not TCP.

```
# ----- tm params -----
# auto-discard branches from previous serial forking leg
modparam("tm", "failure_reply_mode", 3)
# default retransmission timeout: 30sec
modparam("tm", "fr_timer", 30000)
# default invite retransmission timeout after 1xx: 120sec
modparam("tm", "fr_inv_timer", 30000)

# User location service
route[LOCATION] {
        [...]
        # per subscriber ring time
        if ($avp(s:ring_time) != $null) {
                # xlog("setting time out to $avp(s:ring_time)");
                t_set_fr($avp(s:ring_time) * 1000);
        }
}
```

#### Reproduction
register an contact with UDP, set the timer to 5 seconds. observe kamailio terminates the invite after 5 seconds.
then with TCP observe kamailio terminates the invite after 30 seconds (the default)

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
```
version: kamailio 5.2.1 (x86_64/linux) 947769
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 947769
compiled on 20:48:14 Feb 26 2019 with gcc 4.8.5
```

* **Operating System**:
CentOS 7

**Comment by bpbp-boop** [comment]
debug with mysql stuff removed:
https://gist.github.com/bpbp-boop/1ed530f73164a9737803ab2bcd1dca24

**Comment by henningw** [comment]
Thank you for the report. This was reported some time ago on the list [link](https://sr-users.sip-router.narkive.com/z4u3HZWr/t-set-fr-different-behavior-whether-transport-is-udp-or-tcp) but also did not came to a conclusion.

**Comment by bpbp-boop** [comment]
I found a work-around - I assume there is a new branch created when the contact is using TCP because the following fixes it

```
# User location service
route[LOCATION] {
        [...]
        # per subscriber ring time
        if ($avp(s:ring_time) != $null) {
                # xlog("setting time out to $avp(s:ring_time)");
                t_set_fr($avp(s:ring_time) * 1000);
                t_set_max_lifetime($avp(s:ring_time) * 1000, 0);
        }
}
```

**Comment by henningw** [comment]
I can reproduce this with current git master, also your workaround.

**Comment by amessina** [comment]
Is there a workaround for TCP/TLS contacts and combined parallel/serial forking (https://kamailio.org/docs/modules/stable/modules/tm#tm.serial_forking)? Should `t_set_max_lifetime()` be increased for each loop (in failure_route) of `t_next_contacts()`?

**Comment by miconda** [comment]
Closing being an aged item, with an workaround. Should anyone want to implement a different approach, just do a PR.
