### ISSUE TITLE
app_java.so: kamailio 5 crash (might be a double free)

### ISSUE THREAD

**Issue by xevilstar** [kamailio/kamailio#1969]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by xevilstar** [comment]
kamailio -v
version: kamailio 5.2.1 (x86_64/linux) 947769
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 947769 
compiled with gcc 8.2.0


operating system Debian buster

**Comment by xevilstar** [comment]
kamailio configuration snippet
# module app_java
loadmodule "app_java.so"
modparam("app_java", "class_name", "Kamailio")
modparam("app_java", "child_init_method", "child_init")
modparam("app_java", "java_options", "-Djava.compiler=/usr/lib/jvm/java-11-openjdk-amd64/bin/javac -Djava.class.path=/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/kamailio.jar  -verbose:gc,jni")
modparam("app_java", "force_cmd_exec", 1);

**Comment by xevilstar** [comment]
echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64/

**Comment by xevilstar** [comment]
I have installed kamailio using apt-get and then downloaded the same version kamailio sources.
I have then compiled app_java and copied the app_java.so into my kamailio modules path

**Comment by xevilstar** [comment]
#extract from kamailio.log
May 30 13:10:30 PROXY-TEST-01 kamailio: ERROR: <core> [core/sr_module.c:498]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so: undefined symbol: JNI_CreateJavaVM
May 30 13:10:30 PROXY-TEST-01 kamailio: CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 359, column 12-24: failed to load module
May 30 13:10:30 PROXY-TEST-01 kamailio: WARNING: <core> [core/ppcfg.c:220]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
May 30 13:10:30 PROXY-TEST-01 kamailio: ERROR: <core> [core/sr_module.c:498]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so: undefined symbol: JNI_CreateJavaVM
May 30 13:10:30 PROXY-TEST-01 kamailio: CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 359, column 12-24: failed to load module
May 30 13:10:30 PROXY-TEST-01 kamailio: WARNING: <core> [core/ppcfg.c:220]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
May 30 13:10:30 PROXY-TEST-01 kamailio: ERROR: <core> [core/sr_module.c:498]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so: undefined symbol: JNI_CreateJavaVM
May 30 13:10:30 PROXY-TEST-01 kamailio: CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 359, column 12-24: failed to load module
May 30 13:10:30 PROXY-TEST-01 kamailio: WARNING: <core> [core/ppcfg.c:220]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
May 30 13:10:30 PROXY-TEST-01 kamailio: ERROR: <core> [core/sr_module.c:498]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so: undefined symbol: JNI_CreateJavaVM
May 30 13:10:30 PROXY-TEST-01 kamailio: CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 359, column 12-24: failed to load module
May 30 13:10:30 PROXY-TEST-01 kamailio: WARNING: <core> [core/ppcfg.c:220]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1
May 30 13:10:31 PROXY-TEST-01 kamailio: ERROR: <core> [core/sr_module.c:498]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/app_java.so: undefined symbol: JNI_CreateJavaVM
May 30 13:10:31 PROXY-TEST-01 kamailio: CRITICAL: <core> [core/cfg.y:3507]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 359, column 12-24: failed to load module
May 30 13:10:31 PROXY-TEST-01 kamailio: WARNING: <core> [core/ppcfg.c:220]: pp_ifdef_level_check(): different number of preprocessor directives: N(#!IF[N]DEF) - N(#!ENDIF) = 1

**Comment by henningw** [comment]
Indeed gcj was removed from gcc compiler suite for the release 7.1. The openjdk compiler should be used instead.
I managed to build the module on opensuse by setting gcj = no in the Makefile, and set a proper JAVA_HOME on the command line. The module seems to initialize ok:

 0(20759) DEBUG: <core> [core/sr_module.c:909]: init_mod(): app_java
 0(20759) INFO: app_java [app_java_mod.c:131]: mod_init(): Initializing Java VM with options: -Djava.compiler=/usr/lib64/jvm/java/bin/javac -D/usr/lib64/jvm/java/jre/lib/:/home/henning/repositories/kamailio/src/modules/app_java/Kamailio.jar -verbose:gc,jni
 0(20759) INFO: app_java [app_java_mod.c:150]: mod_init(): app_java: Java VM initialization OK
 0(20759) ERROR: app_java [java_support.c:180]: handle_exception(): app_java: Exception:
Exception in thread "main" java.lang.NoClassDefFoundError: Kamailio

Your installation method by trying to match the proper kamailio version of a downloaded version to a package version is not recommended and might produce strange errors.

I would suggest to compile the complete kamailio all together, you will find a tutorial e.g. in our wiki.

**Comment by xevilstar** [comment]
I recompiled the module forcing the header path in the sources (the version matches since the source is the orig from which debian builds the package):
#include "/usr/lib/jvm/java-11-openjdk-amd64/include/jni.h"

now the error changed:
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: WARNING: dispatcher [dispatch.c:1007]: ds_load_db(): no dispatching data in the db -- empty destination set
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: pike [pike.c:97]: pike_init(): PIKE - initializing
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: pike [ip_tree.c:81]: init_lock_set(): probing 256 set size
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: app_java [app_java_mod.c:131]: mod_init(): Initializing Java VM with options: -Djava.compiler=/usr/lib/jvm/java-11-openjdk-amd64/bin/javac -Djava.class.path=/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/kamailio.jar  -verbose:gc,jni
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: app_java [app_java_mod.c:150]: mod_init(): app_java: Java VM initialization OK
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: app_java [app_java_mod.c:199]: mod_init(): app_java: module initialization OK
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: cfgutils [cfgutils.c:831]: mod_init(): no hash_file given, disable hash functionality
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: INFO: <core> [main.c:2648]: main(): processes (at least): 20 - shm size: 134217728 - pkg size: 134217728
May 31 09:55:04 PROXY-TEST-01 /usr/sbin/kamailio[6191]: CRITICAL: <core> [core/mem/q_malloc.c:144]: qm_debug_check_frag(): BUG: qm: prev. fragm. tail overwritten(5558198d1830, abcdefed)[0x7feaa938ecb0:0x7feaa938ece8]! Memory allocator was called from xlog: xlog.c:498. Fragment marked by core: db_res.c:88. Exec from core/mem/q_malloc.c:384.
May 31 09:55:05 PROXY-TEST-01 kamailio: ERROR: <core> [core/daemonize.c:303]: daemonize(): Main process exited before writing to pipe

it occurs only when app_java.so is loaded

**Comment by xevilstar** [comment]
is there something that is not managing memory right ?

**Comment by xevilstar** [comment]
i'd prefer to keep the paths as those are now because I hate things like /usr/local/etc/kamailio/etc around the servers

**Comment by xevilstar** [comment]
it would be nice to have an official kamailio debian repo with all the debs of all the modules in the right paths

**Comment by henningw** [comment]
As commented in the other issue: http://deb.kamailio.org/

**Comment by henningw** [comment]
About the other memory related bug - could you maybe try with the packages from the kamailio repository, if you get the same error here?

**Comment by xevilstar** [comment]
kamailio-java ... where is it ?
apt-cache search kamailio
kamailio-autheph-modules - authentication using ephemeral credentials for the Kamailio SIP server
kamailio-berkeley-bin - Berkeley database module for Kamailio - helper program
kamailio-berkeley-modules - Berkeley database module for the Kamailio SIP server
kamailio-cnxcc-modules - cnxcc modules for the Kamailio SIP server
kamailio-cpl-modules - CPL module (CPL interpreter engine) for the Kamailio SIP server
kamailio-ims-modules - IMS module for the Kamailio SIP server
kamailio-json-modules - Json parser and Json-RPC modules for the Kamailio SIP server
kamailio-memcached-modules - interface to the memcached server, for the Kamailio SIP server
kamailio-mongodb-modules - mongodb modules for the Kamailio SIP server
kamailio-mysql-modules - MySQL database connectivity module for Kamailio
kamailio-perl-modules - Perl extensions and database driver for the Kamailio SIP server
kamailio-phonenum-modules - phonenum modules for the Kamailio SIP server
kamailio-postgres-modules - PostgreSQL database connectivity module for the Kamailio SIP server
kamailio-presence-modules - SIP presence modules for Kamailio
kamailio-python3-modules - The app_python3 module for the Kamailio SIP server
kamailio-rabbitmq-modules - RabbitMQ and AMQP integration modules for the Kamailio SIP server
kamailio-radius-modules - RADIUS modules for the Kamailio SIP server
kamailio-redis-modules - Redis database connectivity module for the Kamailio SIP server
kamailio-ruby-modules - The app_ruby module for Kamailio Ruby support
kamailio-sctp-modules - SCTP SIP transport module for the Kamailio SIP server
kamailio-snmpstats-modules - SNMP AgentX subagent module for the Kamailio SIP server
kamailio-sqlite-modules - SQLite database connectivity module for the Kamailio SIP server
kamailio-systemd-modules - systemd logging modules for the Kamailio SIP server
kamailio-tls-modules - TLS support for the Kamailio SIP server (authentication, transport)
kamailio-unixodbc-modules - unixODBC database connectivity module for the Kamailio SIP server
kamailio-utils-modules - Utility functions for the Kamailio SIP server
kamailio-websocket-modules - WebSocket module for the Kamailio SIP server
kamailio-xml-modules - XML based extensions for Kamailio's Management Interface
kamailio-xmpp-modules - XMPP gateway module for the Kamailio SIP server
kamcli - Kamailio Command Line Interface Control Tool
resource-agents - Cluster Resource Agents
kamailio - very fast, dynamic and configurable SIP server
kamailio-dbg - very fast and configurable SIP server [debug symbols]
kamailio-erlang-modules - Erlang modules for the Kamailio SIP server
kamailio-extra-modules - Extra modules for the Kamailio SIP Server
kamailio-geoip-modules - The geoip module for the Kamailio SIP Server
kamailio-geoip2-modules - The geoip2 module for the Kamailio SIP Server
kamailio-kazoo-modules - kazoo modules for the Kamailio SIP server
kamailio-ldap-modules - LDAP modules for the Kamailio SIP server
kamailio-lua-modules - The app_lua module for Kamailio Lua support
kamailio-mono-modules - The app_mono module for the Kamailio SIP server
kamailio-nth - Kamailio SIP server - package for "nice to have" utilities
kamailio-outbound-modules - SIP Outbound module for the Kamailio SIP server
kamailio-python-modules - The app_python module for the Kamailio SIP server

**Comment by xevilstar** [comment]
I am using 
deb     http://deb.kamailio.org/kamailio51 buster main
deb-src http://deb.kamailio.org/kamailio51 buster main
yes I did apt-get update and imported the key

**Comment by miconda** [comment]
Afaik, the official debian repo as well as the deb.kamailio.org have same packages. Not all modules are packaged due to missing dependencies or licensing constraints. app_java was removed because the gcc compiler suite removed the one for java. Nobody took the time to look for a proper alternative, I only made some small changes to try to other compiler options.

Maybe @linuxmaniac wants to add more details.

Otherwise, you can make a pull request to package app_java to debian specs located in `pkg/kamailio/deb`.

**Comment by xevilstar** [comment]
I don't think there might be licensing problems using openjdk 11.0.3 2019-04-16
please make the deb

**Comment by miconda** [comment]
The licensing remark was in general, referring to the fact that `not all modules are packaged` ... read carefully what I wrote.

Also, note the remark that you can also contribute by making a pull request to the packaging specs. After all, this is an open source collaboration project, everyone has to put efforts to improve the aspects/components they needs. Your pull request will be reviewed and once merged, the packages will be built as you need.

As for myself, I compile from sources, not a debian packaging person.

**Comment by xevilstar** [comment]
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: pike [pike.c:97]: pike_init(): PIKE - initializing
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: pike [ip_tree.c:81]: init_lock_set(): probing 256 set size
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: app_java [app_java_mod.c:132]: mod_init(): Initializing Java VM with options: -Djava.compiler=/usr/lib/jvm/java-11-openjdk-amd64/bin/javac -Djava.class.path=/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/:/usr/lib/x86_64-linux-gnu/kamailio/java/kamailio.jar  -verbose:gc,jni
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: app_java [app_java_mod.c:151]: mod_init(): app_java: Java VM initialization OK
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: app_java [app_java_mod.c:200]: mod_init(): app_java: module initialization OK
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: cfgutils [cfgutils.c:831]: mod_init(): no hash_file given, disable hash functionality
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: INFO: <core> [main.c:2669]: main(): processes (at least): 20 - shm size: 67108864 - pkg size: 8388608
May 31 13:07:05 PROXY-TEST-01 /usr/sbin/kamailio[5924]: CRITICAL: <core> [core/mem/q_malloc.c:144]: qm_debug_check_frag(): BUG: qm: prev. fragm. tail overwritten(55e774aac2a0, abcdefed)[0x7f95d5452cb0:0x7f95d5452ce8]! Memory allocator was called from xlog: xlog.c:498. Fragment marked by core: db_res.c:88. Exec from core/mem/q_malloc.c:384.
May 31 13:07:05 PROXY-TEST-01 kamailio: ERROR: <core> [core/daemonize.c:303]: daemonize(): Main process exited before writing to pipe
root@PROXY-TEST-01:/usr/src/kamailio-5.2.3+buster/src/modules/app_java/kamailio_java_folder/java#

**Comment by xevilstar** [comment]
> The licensing remark was in general, referring to the fact that `not all modules are packaged` ... read carefully what I wrote.
> 
> Also, note the remark that you can also contribute by making a pull request to the packaging specs. After all, this is an open source collaboration project, everyone has to put efforts to improve the aspects/components they need. Your pull request will be reviewed and once merged, the packages will be built as you need.
> 
> As for myself, I compile from sources, not a debian packaging person.

I am trying to contribute. I need this module. If only just this module would be a deb I would be happy. If I manage to compile it I would be of course able to make a deb myself

**Comment by xevilstar** [comment]
core> [core/route.c:872]: fix_actions(): fixing xlog()
May 31 15:15:03 PROXY-TEST-01 /usr/sbin/kamailio[16509]: CRITICAL: <core> [core/mem/q_malloc.c:144]: qm_debug_check_frag(): BUG: qm: prev. fragm. tail overwritten(55c775816cd0, abcdefed)[0x7f64aa9c9d80:0x7f64aa9c9db8]! Memory allocator was called from xlog: xlog.c:498. Fragment marked by core: db_res.c:88. Exec from core/mem/q_malloc.c:384.

**Comment by linuxmaniac** [comment]
@xevilstar good to know that You want to contribute. First try to make app_java work again. From what I know it was not possible to build it with gcj so I removed the package.

I'm not the maintainer of that module and I have any interest in it. If you manage to fix it and make it work properly I can add the package for sure.

**Comment by xevilstar** [comment]
> @xevilstar good to know that You want to contribute. First try to make app_java work again. From what I know it was not possible to build it with gcj so I removed the package.
> 
> I'm not the maintainer of that module and I don't have any interest in it. If you manage to fix it and make it work properly I can add the package for sure.

I managed to compile it without gcj using openjdk the memory leak problem is beyond my skills.
I'd just need someone like the mantainer to intervene. Is there anyone that can contact him ?

**Comment by xevilstar** [comment]
@linuxmaniac  here's the makefile
`include ../../Makefile.defs
auto_gen=
NAME=app_java.so

USE_GCJ ?= no

#DEFS += -DEXTRA_DEBUG

DIST = $(shell if [ -f "/etc/redhat-release" ]; then cat /etc/redhat-release | sed "s/.*\([0-9]\)\.[0-9].*/\1/g"; fi)
ifeq ($(DIST),6)
JVM_PATH = $(shell dirname `find /usr/lib/jvm/java/ -name "libjvm.so"`)
DEFS += $(shell pkg-config libgcj-4.4 --cflags)
LIBS += $(shell pkg-config libgcj-4.4 --cflags) -L$(JVM_PATH) -ljvm
else
# try to detect JAVA_HOME
ifeq ($(USE_GCJ),yes)
JAVA_HOME ?= $(shell readlink -f /usr/bin/javac | sed "s:bin/javac::")
DEFS += $(shell pkg-config libgcj --cflags) -I$(JAVA_HOME)/include
LIBS += $(shell pkg-config libgcj --libs) -L$(JAVA_HOME)/lib  -ljvm
else
ifeq ($(ARCH),i386)
ATYPE=i386
else ifeq ($(ARCH),x86_64)
ATYPE=amd64
endif
JAVA_HOME = /usr/lib/jvm/java
DEFS += -I/usr/lib/jvm/java-11-openjdk-amd64/include
LIBS += -L/usr/lib/jvm/java-11-openjdk-amd64/server -ljvm
endif

# On Debian 7.5 there is a bug with JAVA_HOME detection.
# $(shell readlink -f /usr/bin/javac | sed "s:bin/javac::") points to perl wrapper script (/usr/bin/gcj-wrapper-4.7)
# whereas the real compiler is at /usr/bin/gcj-4.7. As the result, JAVA_HOME will not be a directory, that is incorrect.
# At this point I don't see any universal method as explicit setting this variable at the compile phase.
# -- ez
ifeq ($(USE_GCJ),yes)
ifeq ($(shell [ -d "${JAVA_HOME}" -a -f "$(JAVA_HOME)/include/jni.h" -a -f "$(JAVA_HOME)/lib/libjvm.so" ] && echo 1 || echo 0),0)
ifneq ($(DOCBUILD),yes)
JAVA_HOME = /usr/lib/jvm/java
DEFS += -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux
LIBS += -L/usr/lib/jvm/java-11-openjdk-amd64/server -ljvm
endif
endif
else
ifeq ($(shell [ -d "${JAVA_HOME}" -a -f "$(JAVA_HOME)/include/jni.h" -a -f "$(JAVA_HOME)/jre/lib/$(ATYPE)/server/libjvm.so" ] && echo 1 || echo 0),0)
ifneq ($(DOCBUILD),yes)
JAVA_HOME = /usr/lib/jvm/java
DEFS += -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux
LIBS += -L/usr/lib/jvm/java-11-openjdk-amd64/server -ljvm
endif
endif
endif

ifeq ($(OS), freebsd)
LIBS+=-pthread
endif
ifeq ($(OS), linux)
DEFS += -I/usr/lib/jvm/java-11-openjdk-amd64/include -I /usr/lib/jvm/java-11-openjdk-amd64/include/linux
endif
endif

# disable optimisation for segfaults debugging
ifeq ($(USE_GCJ),yes)
INCLUDE += -O0 -g
INCLUDES += -O0 -g
endif

include ../../Makefile.modules
`

**Comment by xevilstar** [comment]
@linuxmaniac I think that if you try to rebuild the debs and reinclude app_java with this makefile with openjdk as dep what we'll obtain could be something workable. and I could test it

**Comment by xevilstar** [comment]
@linuxmaniac by the way I tried to send it to you through irc dcc transfer on the kamailio freenode channel

**Comment by xevilstar** [comment]
[june-kamailio.log](https://github.com/kamailio/kamailio/files/3253204/june-kamailio.log)

**Comment by xevilstar** [comment]
bump ?

**Comment by miconda** [comment]
The gcc support for java compiler was discontinued. Likely the app_java has to be deprecated if nobody takes over updating it to work with another java lib. For now it can be tracked with #1984 .
