### ISSUE TITLE
KEMI - Missing PVX functions in app_ruby

### ISSUE THREAD

**Issue by WhiteyDude** [kamailio/kamailio#1987]
### Description

Only the following PVX methods are available on app_ruby:

:sbranch_set_ruri, :sbranch_append, :sbranch_reset, :pv_var_to_xavp, :pv_xavp_to_var, :pv_xavp_print, :xavp_params_explode, :xavp_params_implode, :evalx, :freeze

However pvx.xavp.get() etc are documented:

https://kamailio.org/docs/tutorials/devel/kamailio-kemi-framework/modules/#ksrpvxxavp_get

#### Reproduction

`KSR.info(KSR::PVX.methods.to_s)`

### Additional Information

kamailio 5.3.0-dev4 (x86_64/linux) 6d43ea

Can be potentially worked around by using `:pv_xavp_to_var` and `KSR::PV.gete()`, however this feels a bit messy

**Comment by miconda** [comment]
Those functions are in master branch only, the current version being 5.3.0-dev6, so -dev4 is a bit old. Can you upgrade to latest master branch and try again? If still not getting them, reopen.
