### ISSUE TITLE
uac module documentation should be honor s: prefix for kamcmd

### ISSUE THREAD

**Issue by khorsmann** [kamailio/kamailio#1988]
Many sr-users seems to have the same problem with the documentation 
of uac module for requesting the actuall state of upstream sip-registrations.

### Description

kamcmd uac.reg_enable auth_username 12345678
Not working

kamcmd uac.reg_enable auth_username s:12345678
Working

### Expected behavior

Documentation should meantion the kamcmd s: prefix for converting - in the examples.
Meanfull if you are using a mysql-db. Dont testet all backends that are possible.

https://lists.kamailio.org/pipermail/sr-users/2019-June/105993.html
https://lists.kamailio.org/pipermail/sr-users/2017-August/098168.html

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio -v
version: kamailio 5.2.3 (x86_64/linux) c36229
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: c36229
compiled on 11:28:11 May 22 2019 with gcc 4.8.
```

* **Operating System**:

```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
```

**Comment by miconda** [comment]
Added such examples in docs.
