### ISSUE TITLE
mongoDB module in kamailio/kamailio-cli docker image 

### ISSUE THREAD

**Issue by gbmotra** [kamailio/kamailio#1995]
Addl mongoDB module in kamailio/kamailio-cli doker image.

**Comment by sergey-safarov** [comment]
I looked current `mongo-c-driver` packaging in alpine dist.
Now `mongo-c-driver` not packaged.
I leave issue open until `mongo-c-driver` merged into [`alpinelinux/aports`](https://github.com/alpinelinux/aports/) repo.

**Comment by sergey-safarov** [comment]
[PR for alpine dist](https://github.com/alpinelinux/aports/pull/9273) is created.
Also packaged MongoDB Kamailio module.

**Comment by sergey-safarov** [comment]
Module compiled into images with `master` in tag name.
When next alpine release is out, then I merge this commit into 5.2 and 5.3 branches.

Ticket leave open until merged into stable branches.

**Comment by gbmotra** [comment]
hi 
thanks for update 
can you plz ... tel me what are the modules are included in this image ?
thank you

**Comment by sergey-safarov** [comment]
included modules
```
db_mongodb.so
ndb_mongodb.so
```

**Comment by gbmotra** [comment]
hi thanks for reply 
is dispacher and tls module included ?

**Comment by sergey-safarov** [comment]
list of all modules you can get using command
```sh
docker run \
       -it \
       --rm \
       --entrypoint sh \
       kamailio/kamailio-ci:master \
       -c "ls -l /usr/lib/kamailio/modules"
```

**Comment by gbmotra** [comment]
hi
i need Db_cassandra in kamailio/kamailio-cli docker image but it is not
there , can you update it for Db_cassandra
thank you



Regards :
Gaurav Kumar

**Comment by sergey-safarov** [comment]
I tried build `db_cassandra` module and get error
```
Compiling dbcassa_base.cpp
g++ -fPIC -DPIC -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -Wall -Os -fomit-frame-pointer -g -D_GNU_SOURCE -Wno-write-strings -Wno-deprecated -Wno-unused-function -Wno-sign-compare -Wno-strict-aliasing -fPIC -DPIC -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -Wall -Os -fomit-frame-pointer -g -D_GNU_SOURCE -DNAME='"kamailio"' -DVERSION='"5.3.0-pre1"' -DARCH='"x86_64"' -DOS='linux_' -DOS_QUOTED='"linux"' -DCOMPILER='"gcc 9.2.0"' -D__CPU_x86_64 -D__OS_linux -DVERSIONVAL=5003000 -DCFG_DIR='"/etc/kamailio/"' -DSHARE_DIR='"/usr/share/kamailio/"' -DRUN_DIR='"/var/run/kamailio/"' -DPKG_MALLOC -DSHM_MMAP -DDNS_IP_HACK -DUSE_MCAST -DUSE_TCP -DDISABLE_NAGLE -DHAVE_RESOLV_RES -DUSE_DNS_CACHE -DUSE_DNS_FAILOVER -DUSE_DST_BLACKLIST -DUSE_NAPTR -DWITH_XAVP -DMEM_JOIN_FREE -DF_MALLOC -DQ_MALLOC -DTLSF_MALLOC -DDBG_SR_MEMORY -DUSE_TLS -DTLS_HOOKS -DUSE_CORE_STATS -DSTATISTICS -DMALLOC_STATS -DUSE_SCTP -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DCC_GCC_LIKE_ASM -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_SCHED_SETSCHEDULER -DHAVE_IP_MREQN -DUSE_RAW_SOCKS -DHAVE_EPOLL -DHAVE_SIGIO_RT -DSIGINFO64_WORKARROUND -DUSE_FUTEX -DHAVE_SELECT  -I/usr/include/thrift -DMOD_NAME='"db_cassandra"' -c dbcassa_base.cpp -o dbcassa_base.o
dbcassa_base.cpp:37:10: fatal error: protocol/TBinaryProtocol.h: No such file or directory
   37 | #include <protocol/TBinaryProtocol.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:41: dbcassa_base.o] Error 1
```
Looks as this module requires [TBinaryProtocol.h](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/protocol/TBinaryProtocol.h) from [apache/thrift](https://github.com/apache/thrift) repo.

This software not packaged for Alpine dist.
I not ready to deep into `apache/thrift` and how to package this software for Alpine dist.
Could you create this software package by self, then we continue on `db_cassanda` module packaging.

**Comment by miconda** [comment]
From comments, I understand mongodb modules were added to docker. db_cassandra is noy working with a supported thrift library -- anyhow it is something different that this issue.
