### ISSUE TITLE
db_redis: add support for native redis cluster

### ISSUE THREAD

**Issue by gedia** [kamailio/kamailio#1997]
The db_redis module seems to only support connecting with a single redis instance. It is not evident from the documentation if it implements support for native redis cluster by honouring 'MOVED' replies.

ndb_redis seems to have support for native redis clusters, and supports both automatic (see allow_dynamic_nodes parameter of ndb_redis) and manual configuration of redis nodes.

Since both modules are based on the hiredis library, is it safe to assume this support could be easily implemented, with some code sharing between the two modules perhaps?

If db_redis supports clusters with automatic configuration only (by processing MOVED replies), perhaps the module's documentation should be updated to reflect that.

**Comment by miconda** [comment]
The two modules were developed independently. Maybe @agranig can comment if `db_redis` already supports or not processing MOVED replies.

**Comment by agranig** [comment]
Hey, unfortunately it doesn’t support it yet, and it’s not clear yet when I can address this, as I don’t have immediate needs for it.

**Comment by henningw** [comment]
@gedia as there seems no interest from in implementing this feature right now, this issue will be closed. If somebody wants to work on this, please re-open.
