### ISSUE TITLE
TCP ACK is going to different IP then original invite sent 

### ISSUE THREAD

**Issue by SurendraPlivo** [kamailio/kamailio#1998]
### Description
We are converting udp call to tcp call in kamailio. kamailio sending out an invite to a destination. Before sending, kamailio resolving that destination domain to IP. After receiving invite request, Destination send 180 and 200 OK . 200 Ok contact contains the domain name of destination. After this kamailio forward those request to next route. kamailio recieved the ack from upstream. After reciving the ack from upstream it resolves again the domain name to different IP, as domain name have 2 IP's behind.

### Troubleshooting
For TCP calls, connection should be reused.

#### Reproduction
Send domain name in contact for 200 ok instead of IP.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by grumvalski** [comment]
I'm afraid that this is perfectly legitimate proxy behavior as per RFC.
If your 200 OK contact contains a FQDN as domain part, the ACK will have it
in the R-URI and Kamailio will forcefully have to resolve it before
relaying and there is no guarantee that the result will be the same.
Also don't forget that ACK is a transaction on its own, if you want to
track down things between INVITE transaction and ACL transaction you have
to use an "external" mechanism, like can using dialog module or htable
module.

**Comment by SurendraPlivo** [comment]
yeah right now we are using dialog module for tracking those things but there should be an option to use same tcp connection across the call if connection is alive.

**Comment by grumvalski** [comment]
that's already the case if you use IP addresses in 200 OK => ACK. 
The parameter you are speaking can not be implemented in core modules like tm, because that would mean implementing a tracking between transactions which is totally out of scope for those modules. Again, mechanisms external external to transactions need to be used.

**Comment by miconda** [comment]
Like mentioned by comments here, the behavior is as expected by specs, the proxy has to resolve the R-URI address for forwarding. The ACK following 200ok is independent of INVITE transaction (can have also different path than the INVITE, a matter of Record-Route headers).

Use other variants if you want to keep the ip/port of the callee, like a dialog variable, or htable value based on call id and to-tag, or even use set_contact_alias()/handle_ruri_alias() for a solution that doesn't require storage inside kamailio.

I am closing this one, if you want to discuss further about possible solutions, write to sr-users mailing list.
