### ISSUE TITLE
5.2.x RPM Issue - Fails to install on fresh CentOS 7 Minimal Install

### ISSUE THREAD

**Issue by Jeremybk** [kamailio/kamailio#2004]
Kamailio 5.2.x repo for CentOS 7 fails to install with the error listed below.  The same thing happens with the 5.1.x repo.

`
Total download size: 5.6 M
Installed size: 25 M
Downloading packages:
kamailio-5.2.3-6.el7.centos.x8 FAILED                                               98% [========================================================================- ] 350 kB/s | 5.5 MB  00:00:00 ETA
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.2.x-rpms/CentOS_7/x86_64/kamailio-5.2.3-6.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.2.x-rpms clean metadata
Trying other mirror.

Error downloading packages:
  kamailio-5.2.3-6.el7.centos.x86_64: [Errno 256] No more mirrors to try.`

**Comment by sergey-safarov** [comment]
Repo is refreshed. After hour you can retry again.
Daniel @miconda, can we get new VM or existent VM with docker for RPM repo?

**Comment by henningw** [comment]
@Jeremybk - did you tested it again, does it works now?

**Comment by Jeremybk** [comment]
Yes, it did work after you refreshed the repo.  Thank you!

**Comment by sergey-safarov** [comment]
That issue rise again, and again several times. About 4-6 times peer year.
May be create dedicated RPM repo?

**Comment by henningw** [comment]
Sure, this could be created, if somebody volunteer to work on this CentOS repository. About the VM question, can you send an email with more details what you need to our kadmin list: kadmin.hq@...

**Comment by miconda** [comment]
@sergey-safarov  asked me a while ago for a system to create a platform for generating RPMS, but somehow I kept forgetting about it. I wrote @fredposner who allocated 3 boxes from lod.com to kamailio project to give one for this purpose.

For now, I am closing this one and we can discuss via direct emails, being now more admin stuff than development matter.
