### ISSUE TITLE
kamailio service starting trigger 

### ISSUE THREAD

**Issue by rccess** [kamailio/kamailio#2005]
Hello all , 

kamailio Service not starting , through error of hostname , even hostname is correct 

Please advise

![image](https://user-images.githubusercontent.com/32220165/61097393-d3ebfd80-a478-11e9-9c55-d1826b29429d.png)

**Comment by henningw** [comment]
Have a look to your cfg for the hostname "trunks" - this can't be resolved. For further discussion please use the sr-users e-mail list, as this is not a bug in Kamailio.
