### ISSUE TITLE
Registration URI issue

### ISSUE THREAD

**Issue by rccess** [kamailio/kamailio#2007]
Hello all 

I am facing a different kind of problem

my SIP provider getting registered with sip.conf

![image](https://user-images.githubusercontent.com/32220165/61198001-554fc400-a6f5-11e9-8826-de25ffb1857b.png)

but when i am doing same configuration in kamailio with PJSIP 

sip registry getting timeout

![image](https://user-images.githubusercontent.com/32220165/61198012-6993c100-a6f5-11e9-9225-7f58a41f7161.png)

below the sip configuration which i am using in sip.conf and getting registered
------------------------------------------------------------------------------------------

[general]

;register => +911XXXXX12100:XXX56:+911XXXX2100@dxxxhi.rexxxxeims.in/91141xxxxx2100

register => +9114xxxxx100@xxxhi.relxxxims.in:1xxxxxx56:+9114xxxxx100@dxxxxhi.relixxxms.in@10.237.252.225/+911xxxxx2100

username=+91xxx4xxx00
secret=xxxxxx56
type=friend
host=dxxxxxhi.rxxxxxxms.in
dtmfmode=rfc2833
nat=no
canreinvite=no
fromuser=+911xxxxxx100
disallow=all
allow=ulaw
allow=alaw
allow=gsm
context=default
defaultexpiry = 1900

**Comment by henningw** [comment]
About the first quesiton - sorry, but we can't help you with Asterisk issues here, please contact the asterisk list. About the second question, what do you mean with "same configuration in kamailio with PJSIP"? I don't understand this.

**Comment by rccess** [comment]
here are the logs

getting timeout with same sip configuration with kamailio uac register module 
------------------------------------------------------------
, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8673]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8671]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8670]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8672]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8662]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:50 vdserver.telcob.live /usr/sbin/kamailio[8657]: INFO: rtpengine [rtpengine.c:2421]: rtpp_test(): rtp proxy <udp:127.0.0.1:22223> found, support for it enabled
Jul 15 13:28:55 vdserver.telcob.live /usr/sbin/kamailio[8647]: ERROR: uac [uac_reg.c:1032]: uac_reg_tm_callback(): got sip response 408 while registering [1563088710049]

------------------------------------------------------------
please advise

**Comment by miconda** [comment]
@rccess - watch the sip traffic with ngrep and see where the register request is sent:

```
ngrep -d any -qt -W byline "sip" port 5060
```

Are you using event_route[tm:local-request]? It seems that a log message is printed from there, if yes, be sure you don't modify the address of the destination to some invalid target.

**Comment by rccess** [comment]
thanks for your reply mate

here are the logs
-----------------------------------------------------------------------
root@vdserver.telcob.live:~# ngrep -d any -qt -W byline "sip" port 5060
interface: any
filter: (ip or ip6) and ( port 5060 )
match: sip

U 2019/07/17 11:08:42.785139 122.161.88.226:63134 -> 43.231.124.208:5060
INVITE sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---83c6286a7131d18f;rport.
Max-Forwards: 70.
Contact: <sip:bob@122.161.88.226:63134;transport=UDP>.
To: <sip:+919468673014@43.231.124.208;transport=UDP>.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 1 INVITE.
Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE.
Content-Type: application/sdp.
User-Agent: Z 5.2.10 rv2.8.75.
Allow-Events: presence, kpml, talk.
Content-Length: 604.
.
v=0.
o=Z 0 0 IN IP4 122.161.88.226.
s=Z.
c=IN IP4 122.161.88.226.
t=0 0.
m=audio 8000 RTP/AVP 106 9 3 111 0 8 97 110 112 98 101 100 99 102.
a=rtpmap:106 opus/48000/2.
a=fmtp:106 minptime=20; cbr=1; maxaveragebitrate=40000; useinbandfec=1.
a=rtpmap:111 speex/16000.
a=rtpmap:97 iLBC/8000.
a=fmtp:97 mode=20.
a=rtpmap:110 speex/8000.
a=rtpmap:112 speex/32000.
a=rtpmap:98 telephone-event/48000.
a=fmtp:98 0-16.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=rtpmap:100 telephone-event/16000.
a=fmtp:100 0-16.
a=rtpmap:99 telephone-event/32000.
a=fmtp:99 0-16.
a=rtpmap:102 G726-32/8000.
a=sendrecv.


U 2019/07/17 11:08:42.785589 43.231.124.208:5060 -> 122.161.88.226:63134
SIP/2.0 407 Proxy Authentication Required.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---83c6286a7131d18f;rport=63134;received=122.161.88.226.
To: <sip:+919468673014@43.231.124.208;transport=UDP>;tag=d8e430b9bd318ed850c95c7eb2dfd6f4.b9d4.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 1 INVITE.
Proxy-Authenticate: Digest realm="43.231.124.208", nonce="XS61jl0utGIqJbEDypejRPgeo4Z//XQv".
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:42.936109 122.161.88.226:63134 -> 43.231.124.208:5060
ACK sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---83c6286a7131d18f;rport.
Max-Forwards: 70.
To: <sip:+919468673014@43.231.124.208;transport=UDP>;tag=d8e430b9bd318ed850c95c7eb2dfd6f4.b9d4.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 1 ACK.
Content-Length: 0.
.


U 2019/07/17 11:08:42.947580 122.161.88.226:63134 -> 43.231.124.208:5060
INVITE sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---2a215301449952f6;rport.
Max-Forwards: 70.
Contact: <sip:bob@122.161.88.226:63134;transport=UDP>.
To: <sip:+919468673014@43.231.124.208;transport=UDP>.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 INVITE.
Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE.
Content-Type: application/sdp.
Proxy-Authorization: Digest username="bob",realm="43.231.124.208",nonce="XS61jl0utGIqJbEDypejRPgeo4Z//XQv",uri="sip:+919468673014@43.231.124.208;transport=UDP",response="79f2e67a1da3d0a56bb517e054bd3a79",algorithm=MD5.
User-Agent: Z 5.2.10 rv2.8.75.
Allow-Events: presence, kpml, talk.
Content-Length: 604.
.
v=0.
o=Z 0 0 IN IP4 122.161.88.226.
s=Z.
c=IN IP4 122.161.88.226.
t=0 0.
m=audio 8000 RTP/AVP 106 9 3 111 0 8 97 110 112 98 101 100 99 102.
a=rtpmap:106 opus/48000/2.
a=fmtp:106 minptime=20; cbr=1; maxaveragebitrate=40000; useinbandfec=1.
a=rtpmap:111 speex/16000.
a=rtpmap:97 iLBC/8000.
a=fmtp:97 mode=20.
a=rtpmap:110 speex/8000.
a=rtpmap:112 speex/32000.
a=rtpmap:98 telephone-event/48000.
a=fmtp:98 0-16.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=rtpmap:100 telephone-event/16000.
a=fmtp:100 0-16.
a=rtpmap:99 telephone-event/32000.
a=fmtp:99 0-16.
a=rtpmap:102 G726-32/8000.
a=sendrecv.


U 2019/07/17 11:08:42.952465 43.231.124.208:5060 -> 43.231.124.208:5060
PUBLISH sip:102@43.231.124.208 SIP/2.0.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bK119f.b72192b3000000000000000000000000.0.
To: <sip:102@43.231.124.208>.
From: <sip:102@43.231.124.208>;tag=4286a703488bb0cde043eeb2ff298716-d177.
CSeq: 10 PUBLISH.
Call-ID: 796c464916725da6-12576@43.231.124.208.
Content-Length: 619.
User-Agent: Irontec IvozProvider v2.11.
Max-Forwards: 70.
Event: dialog.
Expires: 10801.
Content-Type: application/dialog-info+xml.
.
<?xml version="1.0"?>
<dialog-info xmlns="urn:ietf:params:xml:ns:dialog-info" version="0" state="full" entity="sip:bob@43.231.124.208;transport=UDP">
  <dialog id="lHbCe0C_nm8AeSIRTVRYww.." call-id="lHbCe0C_nm8AeSIRTVRYww.." direction="initiator">
    <state>Trying</state>
    <remote>
      <identity>sip:+919468673014@43.231.124.208;transport=UDP</identity>
      <target uri="sip:+919468673014@43.231.124.208;transport=UDP"/>
    </remote>
    <local>
      <identity>sip:bob@43.231.124.208;transport=UDP</identity>
      <target uri="sip:bob@43.231.124.208;transport=UDP"/>
    </local>
  </dialog>
</dialog-info>


U 2019/07/17 11:08:42.955006 43.231.124.208:5060 -> 43.231.124.208:5060
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bK119f.b72192b3000000000000000000000000.0;rport=5060.
To: <sip:102@43.231.124.208>;tag=11fc9c5d7e5ef251c2d9322be13a0025-365a.
From: <sip:102@43.231.124.208>;tag=4286a703488bb0cde043eeb2ff298716-d177.
CSeq: 10 PUBLISH.
Call-ID: 796c464916725da6-12576@43.231.124.208.
Expires: 3600.
SIP-ETag: a.1563340218.12577.1.0.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:42.959519 43.231.124.208:5060 -> 122.161.88.226:63134
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---2a215301449952f6;rport=63134;received=122.161.88.226.
To: <sip:+919468673014@43.231.124.208;transport=UDP>.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 INVITE.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:42.960791 43.231.124.208:5060 -> 127.0.0.1:6060
INVITE sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Record-Route: <sip:43.231.124.208;lr;ftag=b849df7c;did=816.dc22>.
X-Info-Logtag: b1.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bKc469.592c1b03472236bc382a52f19e1a530d.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;received=122.161.88.226;branch=z9hG4bK-524287-1---2a215301449952f6;rport=63134.
Max-Forwards: 69.
Contact: <sip:bob@122.161.88.226:63134;transport=UDP>.
To: <sip:+919468673014@43.231.124.208;transport=UDP>.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 INVITE.
Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE.
Content-Type: application/sdp.
User-Agent: Z 5.2.10 rv2.8.75.
Allow-Events: presence, kpml, talk.
Content-Length: 706.
.
v=0.
o=Z 0 0 IN IP4 43.231.124.208.
s=Z.
c=IN IP4 43.231.124.208.
t=0 0.
m=audio 17188 RTP/AVP 106 9 3 111 0 8 97 110 112 98 101 100 99 102.
a=rtpmap:106 opus/48000/2.
a=rtpmap:9 G722/8000.
a=rtpmap:3 GSM/8000.
a=rtpmap:111 speex/16000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:97 iLBC/8000.
a=rtpmap:110 speex/8000.
a=rtpmap:112 speex/32000.
a=rtpmap:98 telephone-event/48000.
a=rtpmap:101 telephone-event/8000.
a=rtpmap:100 telephone-event/16000.
a=rtpmap:99 telephone-event/32000.
a=rtpmap:102 G726-32/8000.
a=fmtp:106 minptime=20; cbr=1; maxaveragebitrate=40000; useinbandfec=1.
a=fmtp:97 mode=20.
a=fmtp:98 0-16.
a=fmtp:101 0-16.
a=fmtp:100 0-16.
a=fmtp:99 0-16.
a=sendrecv.
a=rtcp:17189.


U 2019/07/17 11:08:42.965099 127.0.0.1:6060 -> 43.231.124.208:5060
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 43.231.124.208;received=43.231.124.208;branch=z9hG4bKc469.592c1b03472236bc382a52f19e1a530d.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;rport=63134;received=122.161.88.226;branch=z9hG4bK-524287-1---2a215301449952f6.
Record-Route: <sip:43.231.124.208;lr;ftag=b849df7c;did=816.dc22>.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
From: <sip:bob@43.231.124.208>;tag=b849df7c.
To: <sip:+919468673014@43.231.124.208>.
CSeq: 2 INVITE.
Server: Irontec IvozProvider v2.11.
Content-Length:  0.
.


U 2019/07/17 11:08:43.534779 127.0.0.1:6060 -> 43.231.124.209:5060
INVITE sip:+919468673014@trunks.ivozprovider.local SIP/2.0.
Via: SIP/2.0/UDP 127.0.0.1:6060;rport;branch=z9hG4bKPj430e6cd5-87a7-447e-8f70-4581c4e6bddb.
From: "Bob Bobson" <sip:+911413812100@127.0.0.1>;tag=5017db79-0e39-4174-a8ef-325de5f34b2c.
To: <sip:+919468673014@trunks.ivozprovider.local>.
Contact: <sip:asterisk@127.0.0.1:6060>.
Call-ID: 36674ab6-3a0b-4451-b1ed-29e943e846c3.
CSeq: 17823 INVITE.
Allow: OPTIONS, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, REGISTER, REFER.
Supported: timer, replaces, norefersub.
Session-Expires: 1800.
Min-SE: 90.
X-Call-Id: lHbCe0C_nm8AeSIRTVRYww...
X-Info-BrandId: 1.
X-Info-CompanyId: 1.
X-Info-Type: vpbx.
Max-Forwards: 70.
User-Agent: Irontec IvozProvider v2.11.
Content-Type: application/sdp.
Content-Length:   289.
.
v=0.
o=- 935383770 935383770 IN IP4 43.231.124.208.
s=Asterisk.
c=IN IP4 43.231.124.208.
t=0 0.
m=audio 10686 RTP/AVP 8 0 18 101.
a=rtpmap:8 PCMA/8000.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 G729/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-16.
a=ptime:20.
a=maxptime:150.
a=sendrecv.


U 2019/07/17 11:08:43.539864 43.231.124.209:5060 -> 127.0.0.1:6060
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 127.0.0.1:6060;rport=6060;branch=z9hG4bKPj430e6cd5-87a7-447e-8f70-4581c4e6bddb;received=127.0.0.1.
From: "Bob Bobson" <sip:+911413812100@127.0.0.1>;tag=5017db79-0e39-4174-a8ef-325de5f34b2c.
To: <sip:+919468673014@trunks.ivozprovider.local>.
Call-ID: 36674ab6-3a0b-4451-b1ed-29e943e846c3.
CSeq: 17823 INVITE.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:48.524484 43.231.124.209:5060 -> 127.0.0.1:6060
SIP/2.0 503 No gateways.
Via: SIP/2.0/UDP 127.0.0.1:6060;rport=6060;branch=z9hG4bKPj430e6cd5-87a7-447e-8f70-4581c4e6bddb;received=127.0.0.1.
From: "Bob Bobson" <sip:+911413812100@127.0.0.1>;tag=5017db79-0e39-4174-a8ef-325de5f34b2c.
To: <sip:+919468673014@trunks.ivozprovider.local>;tag=ea9b3830ad1ed0babae580634b1bc0a5-dd97.
Call-ID: 36674ab6-3a0b-4451-b1ed-29e943e846c3.
CSeq: 17823 INVITE.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:48.528761 127.0.0.1:6060 -> 43.231.124.209:5060
ACK sip:+919468673014@trunks.ivozprovider.local SIP/2.0.
Via: SIP/2.0/UDP 127.0.0.1:6060;rport;branch=z9hG4bKPj430e6cd5-87a7-447e-8f70-4581c4e6bddb.
From: "Bob Bobson" <sip:+911413812100@127.0.0.1>;tag=5017db79-0e39-4174-a8ef-325de5f34b2c.
To: <sip:+919468673014@trunks.ivozprovider.local>;tag=ea9b3830ad1ed0babae580634b1bc0a5-dd97.
Call-ID: 36674ab6-3a0b-4451-b1ed-29e943e846c3.
CSeq: 17823 ACK.
Max-Forwards: 70.
User-Agent: Irontec IvozProvider v2.11.
Content-Length:  0.
.


U 2019/07/17 11:08:48.529830 127.0.0.1:6060 -> 43.231.124.208:5060
SIP/2.0 503 Service Unavailable.
Via: SIP/2.0/UDP 43.231.124.208;received=43.231.124.208;branch=z9hG4bKc469.592c1b03472236bc382a52f19e1a530d.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;rport=63134;received=122.161.88.226;branch=z9hG4bK-524287-1---2a215301449952f6.
Record-Route: <sip:43.231.124.208;lr;ftag=b849df7c;did=816.dc22>.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
From: <sip:bob@43.231.124.208>;tag=b849df7c.
To: <sip:+919468673014@43.231.124.208>;tag=b3bf97c8-2b8e-4c90-b3ee-80d70893b3e1.
CSeq: 2 INVITE.
Server: Irontec IvozProvider v2.11.
Reason: Q.850;cause=34.
P-Asserted-Identity: <sip:+919468673014@43.231.124.208>.
Content-Length:  0.
.


U 2019/07/17 11:08:48.530143 43.231.124.208:5060 -> 127.0.0.1:6060
ACK sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bKc469.592c1b03472236bc382a52f19e1a530d.0.
Max-Forwards: 69.
To: <sip:+919468673014@43.231.124.208>;tag=b3bf97c8-2b8e-4c90-b3ee-80d70893b3e1.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 ACK.
Content-Length: 0.
.


U 2019/07/17 11:08:48.532783 43.231.124.208:5060 -> 43.231.124.208:5060
PUBLISH sip:102@43.231.124.208 SIP/2.0.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bK211d.0d6721f5000000000000000000000000.0.
To: <sip:102@43.231.124.208>.
From: <sip:102@43.231.124.208>;tag=4286a703488bb0cde043eeb2ff298716-b1bb.
CSeq: 10 PUBLISH.
Call-ID: 796c464916725da6-12580@43.231.124.208.
Content-Length: 629.
User-Agent: Irontec IvozProvider v2.11.
Max-Forwards: 70.
Event: dialog.
Expires: 11.
SIP-If-Match: a.1563340218.12577.1.0.
Content-Type: application/dialog-info+xml.
.
<?xml version="1.0"?>
<dialog-info xmlns="urn:ietf:params:xml:ns:dialog-info" version="0" state="full" entity="sip:bob@43.231.124.208;transport=UDP">
  <dialog id="lHbCe0C_nm8AeSIRTVRYww.." call-id="lHbCe0C_nm8AeSIRTVRYww.." direction="initiator">
    <state>terminated</state>
    <remote>
      <identity>sip:+919468673014@43.231.124.208;transport=UDP</identity>
      <target uri="sip:+919468673014@43.231.124.208;transport=UDP"/>
    </remote>
    <local>
      <identity>sip:bob@43.231.124.208;transport=UDP</identity>
      <target uri="sip:bob@122.161.88.226:63134;transport=UDP"/>
    </local>
  </dialog>
</dialog-info>


U 2019/07/17 11:08:48.532831 43.231.124.208:5060 -> 122.161.88.226:63134
SIP/2.0 500 Service Unavailable.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---2a215301449952f6;rport=63134;received=122.161.88.226.
To: <sip:+919468673014@43.231.124.208;transport=UDP>;tag=11fc9c5d7e5ef251c2d9322be13a0025-f265.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 INVITE.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:48.534851 43.231.124.208:5060 -> 43.231.124.208:5060
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 43.231.124.208;branch=z9hG4bK211d.0d6721f5000000000000000000000000.0;rport=5060.
To: <sip:102@43.231.124.208>;tag=11fc9c5d7e5ef251c2d9322be13a0025-e6c1.
From: <sip:102@43.231.124.208>;tag=4286a703488bb0cde043eeb2ff298716-b1bb.
CSeq: 10 PUBLISH.
Call-ID: 796c464916725da6-12580@43.231.124.208.
Expires: 11.
SIP-ETag: a.1563340218.12583.1.1.
Server: Irontec IvozProvider v2.11.
Content-Length: 0.
.


U 2019/07/17 11:08:48.580324 122.161.88.226:63134 -> 43.231.124.208:5060
ACK sip:+919468673014@43.231.124.208;transport=UDP SIP/2.0.
Via: SIP/2.0/UDP 122.161.88.226:63134;branch=z9hG4bK-524287-1---2a215301449952f6;rport.
Max-Forwards: 70.
To: <sip:+919468673014@43.231.124.208;transport=UDP>;tag=11fc9c5d7e5ef251c2d9322be13a0025-f265.
From: <sip:bob@43.231.124.208;transport=UDP>;tag=b849df7c.
Call-ID: lHbCe0C_nm8AeSIRTVRYww...
CSeq: 2 ACK.
Content-Length: 0.
.

**Comment by henningw** [comment]
@rccess - any comment on the feedback to your trace?

**Comment by rccess** [comment]
Issue was resolved

**Comment by henningw** [comment]
Thanks for the feedback
