### ISSUE TITLE
Enabling message forwarding in sip_trace 

### ISSUE THREAD

**Issue by Shyamtechm** [kamailio/kamailio#201]
Hi all,

I am able to log the SIP messages to database using sip_trace module of kamailio.
But when i tried to forward the SIP messages to duplicate uri ..I am not getting any log file have SIP messages.

Basically i am not able to dump the messages to a log file using duplicate url.

Please suggest.

Thank you,
Shyam

**Comment by adubovikov** [comment]
Hi,

do you use Homer project and duplicate messages in HEP ?

Wbr,
Alexandr

**Comment by Shyamtechm** [comment]
no...I am using only sip_trace module in kamailio and enabling hep mode  in kamailio config.

Please elaborate more on ur suggestions..

Thanks,
Shyam

**Comment by adubovikov** [comment]
you have to use Homer project and configure the destination kamailo to be a capture server.

more info is here:

http://www.sipcapture.org
http://github.com/sipcapture/homer

**Comment by Shyamtechm** [comment]
Ok...One more question...

If I give the CAPTURE_NODE as 127.0.0.1:9060,
the sip_trace module is still forwarding it to 127.0.0.1:4060.
But as per my knowledge, it should forward it to 9060.

I will be having both source and destination kamailio on same machine,
in that  case, which ports will be used.

All above ports mentioned are UDP ports.

Thanks,
Shyam

**Comment by adubovikov** [comment]
can you pastebin your kamailio's config somethere ?

**Comment by Shyamtechm** [comment]
I am copying below kamailio cfg contents related to sip_trace.

# Destination, where to send the traffic
modparam("siptrace", "duplicate_uri", sip:127.0.0.1:9060)
# Trace all traffic
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_to_database", 1)
modparam("siptrace", "trace_flag", 22)
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 2)
modparam("siptrace", "traced_user_avp", "$avp(i:2)")
modparam("siptrace", "traced_user_avp", "$avp(s:root)")


The sip_trace module is still forwarding SIP messages to 127.0.0.1:4060.
But as per my knowledge, it should forward it to 9060, then another Kamailio can listen on 9060.

Please suggest.

Thanks,
Shyam

**Comment by adubovikov** [comment]
you didn't escape url:

have to be something like this:

modparam("siptrace", "duplicate_uri", "udp:127.0.0.1:9060")

**Comment by Shyamtechm** [comment]
I have given that...u can see my last comment again...

**Comment by Shyamtechm** [comment]
instaed of udp:127.0.0.1:906 i have given sip:127.0.0.1:906

**Comment by Shyamtechm** [comment]
I got it...I will correct it.

**Comment by Shyamtechm** [comment]
Actually, I am using 

modparam("siptrace", "duplicate_uri", CAPTURE_NODE)

where CAPTURE_NODE is set to "sip:127.0.0.1:9060"

**Comment by Shyamtechm** [comment]
Can u please ans this?...

**Comment by Shyamtechm** [comment]
r u there?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Examples%3A-Kamailio

**Comment by linuxmaniac** [comment]
Not a code issue here. Move this to sr-users@lists.sip-router.org please
