### ISSUE TITLE
Using PATH makes nathelper to send the SIP ping to itself

### ISSUE THREAD

**Issue by pwakano** [kamailio/kamailio#2011]
### Description

When using the PATH header option to keep track of original Kamailio node that received the REGISTER, if nathelper is also used with SIP ping enabled, the SIP OPTIONS is sent to itself following the PATH header and not sent directly to the destination.
The nathelper/user location modules should have a flag similar to the "path_check_local" of the registrar module, which is meant to avoid looping the message to itself in case the next hop pointed by the PATH header is "myself".

#### Reproduction
Configure the registrar module to support PATH and before saving the contact info add the PATH header with the local Kamailio information. Also make sure to have the nathelper and usrloc modules configured to send the keepalive SIP OPTIONS to the registered extensions.
By the time the SIP OPTIONS is sent, Kamailio sends to itself, then the message has to be loose_route'd to the final destination.
This could be avoided by having the nathelper module to identify the next hop is Kamailio itself skipping this destination as a call to "lookup()" does for the registrar module when the flag path_check_local is true.

#### SIP Traffic

172.128.128.10 is the Kamailio IP and 172.128.128.20 is the extension IP
```
11:51:07.224713 IP (tos 0x60, ttl 64, id 64497, offset 0, flags [none], proto UDP (17), length 518)
    172.128.128.10.5060 > 172.128.128.10.5060: SIP, length: 490
	OPTIONS sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP SIP/2.0
	Via: SIP/2.0/UDP 172.128.128.10:5060;branch=z9hG4bK2540713
	Route: <sip:172.128.128.10:5060;received=sip:172.128.128.20:5060;lr;cluster_node=192.168.156.10:5060>
	From: sip:sbc@mydomain.com;tag=uloc-5d2e6499-2fb5-1-0-c15309d2
	To: sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP
	Call-ID: 40ee1573-7506bba3-5e30c05@172.128.128.10
	CSeq: 1 OPTIONS
	Content-Length: 0
	
	
11:51:07.226132 IP (tos 0x60, ttl 64, id 44359, offset 0, flags [none], proto UDP (17), length 502)
    172.128.128.10.5060 > 172.128.128.20.5060: SIP, length: 474
	OPTIONS sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP SIP/2.0
	Via: SIP/2.0/UDP 172.128.128.10;branch=z9hG4bKb958.b807e80b742db62504a45220d8f0e974.0
	Via: SIP/2.0/UDP 172.128.128.10:5060;branch=z9hG4bK2540713
	From: sip:sbc@mydomain.com;tag=uloc-5d2e6499-2fb5-1-0-c15309d2
	To: sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP
	Call-ID: 40ee1573-7506bba3-5e30c05@172.128.128.10
	CSeq: 1 OPTIONS
	Content-Length: 0
	
	
11:51:07.303474 IP (tos 0x0, ttl 128, id 10816, offset 0, flags [none], proto UDP (17), length 786)
    172.128.128.20.5060 > 172.128.128.10.5060: SIP, length: 758
	SIP/2.0 200 OK
	Via: SIP/2.0/UDP 172.128.128.10;branch=z9hG4bKb958.b807e80b742db62504a45220d8f0e974.0
	Via: SIP/2.0/UDP 172.128.128.10:5060;branch=z9hG4bK2540713
	Contact: <sip:172.128.128.20:5060>
	To: <sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP>;tag=bb0c1f2d
	From: sip:sbc@mydomain.com;tag=uloc-5d2e6499-2fb5-1-0-c15309d2
	Call-ID: 40ee1573-7506bba3-5e30c05@172.128.128.10
	CSeq: 1 OPTIONS
	Accept: application/sdp, application/sdp
	Accept-Language: en
	Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE
	Supported: replaces, norefersub, extended-refer, timer, outbound, path, X-cisco-serviceuri
	User-Agent: Z 3.15.40006 rv2.8.20
	Allow-Events: presence, kpml, talk
	Content-Length: 0
	
	
11:51:07.306821 IP (tos 0x60, ttl 64, id 64570, offset 0, flags [none], proto UDP (17), length 727)
    172.128.128.10.5060 > 172.128.128.10.5060: SIP, length: 699
	SIP/2.0 200 OK
	Via: SIP/2.0/UDP 172.128.128.10:5060;branch=z9hG4bK2540713
	Contact: <sip:172.128.128.20:5060;alias=172.128.128.20~5060~1>
	To: <sip:345671002@172.128.128.20:5060;rinstance=d1eb3444a5cec5a1;transport=UDP>;tag=bb0c1f2d
	From: sip:sbc@mydomain.com;tag=uloc-5d2e6499-2fb5-1-0-c15309d2
	Call-ID: 40ee1573-7506bba3-5e30c05@172.128.128.10
	CSeq: 1 OPTIONS
	Accept: application/sdp, application/sdp
	Accept-Language: en
	Allow: INVITE, ACK, CANCEL, BYE, NOTIFY, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE
	Supported: replaces, norefersub, extended-refer, timer, outbound, path, X-cisco-serviceuri
	User-Agent: Z 3.15.40006 rv2.8.20
	Allow-Events: presence, kpml, talk
	Content-Length: 0
```

### Possible Solutions

Not found.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
# kamailio -v
version: kamailio 5.2.2 (x86_64/linux) 67f967
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 67f967 
compiled on 11:40:41 Mar 11 2019 with gcc 4.8.5
```

* **Operating System**:

```
# uname -a
Linux kamailio-1 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by henningw** [comment]
Thank you for the report. Just to clarify - the current routing works, but is of course not optimal because of the local loop? So basically you are suggesting to add a path_check_local functionality also to the nathelper module.

**Comment by pwakano** [comment]
Yes. As long as the script actually expects OPTIONS to an external domain, calling a loose_route() will route it properly.
I usually do not allow OPTIONS passing through my Kamailio to external users but had to add this exception for this case, reason why I think a flag can be added to avoid this local loop and the extra logic in the script.

**Comment by pwakano** [comment]
This change is a very nice to have and shouldn't be closed.

**Comment by miconda** [comment]
If an item on tracker is wanted to stay open, the `Stale` label has to be removed.

On the other hand, this is a free collaboration project. If nobody has time or financial resources to support the development of the new features, then it does not seem worth enough. This particular request is more than 4 years old.
