### ISSUE TITLE
unistr.h: No such file or directory

### ISSUE THREAD

**Issue by winsnlife** [kamailio/kamailio#2020]
### Description
when i make websocket module:

ws_frame.c:32:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
make: *** [ws_frame.o] Error 1

OS:
centos7

and i try reinstall libunistring,Still failed

**Comment by ngvoice** [comment]
You need "libunistring-dev" instead of just "libunistring".

**Comment by ljql2001** [comment]
Also, should install "libunistring-devel" instead of "libunistring-dev" on CentOS

**Comment by kamailio-sync** [comment]
I think yes, required install "libunistring-devel"

https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/obs/kamailio.spec#L1097-L1101
