### ISSUE TITLE
topos module does not update topos_d timestamp at re-INVITE

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#2024]
The topos module fails to update the dialog data in the topos_d table after the processing of re-INVITEs.

I have setup a call at 11:55, and triggered a re-INVITE at 12:08. The respective topos_d table entry is not updated.

This causes the entry to expire after topos dialog_timeout value.

I would expect that the timestamp of the call in the topos_d table is updated. Is this assumption correct? If the current behavior is expected, it should documented in the module README.

No error messages from topos module in kamailio.log. Output from tables:

```
MariaDB [kamailio]>  select id, rectime, s_method, a_callid from topos_t; select id, rectime, s_method, a_callid from topos_d;
+-----+---------------------+----------+----------------------------------+
| id  | rectime             | s_method | a_callid                         |
+-----+---------------------+----------+----------------------------------+
| 305 | 2019-08-04 12:08:12 | INVITE   | q0Jeh9g49GeYdJXqcjCo-G0CW4dQ0iav |
| 306 | 2019-08-04 12:08:12 | ACK      | q0Jeh9g49GeYdJXqcjCo-G0CW4dQ0iav |
| 307 | 2019-08-04 12:08:14 | INVITE   | q0Jeh9g49GeYdJXqcjCo-G0CW4dQ0iav |
| 308 | 2019-08-04 12:08:14 | ACK      | q0Jeh9g49GeYdJXqcjCo-G0CW4dQ0iav |
+-----+---------------------+----------+----------------------------------+

+-----+---------------------+----------+----------------------------------+
| id  | rectime             | s_method | a_callid                         |
+-----+---------------------+----------+----------------------------------+
| 156 | 2019-08-04 11:55:22 | INVITE   | q0Jeh9g49GeYdJXqcjCo-G0CW4dQ0iav |
+-----+---------------------+----------+----------------------------------+
```

**Comment by henningw** [comment]
$ kamailio -v
version: kamailio 5.2.3 (x86_64/linux)

**Comment by miconda** [comment]
That is supposed to be the lifetime of the dialog, not updated on re-INVITE or other requests within dialog.

You can add a new param to control this behaviour if you want to change this value on requests within dialog.

**Comment by henningw** [comment]
Thanks Daniel. So basically something like the dialog timeout_noreset [parameter](https://kamailio.org/docs/modules/5.2.x/modules/dialog.html#dialog.p.timeout_noreset)

Ok, I have added some documentation for now:

```
Keep in mind that the module does not update the dialog timestamp after the initial call
setup on re-INVITEs or other in-dialog messages. So set a large enough value
(according your longest call duration) to prevent problems in re-writing messages.
```
If somebody likes to contribute an enhancement, please re-open.
