### ISSUE TITLE
Radius misc MAX_EXTRA

### ISSUE THREAD

**Issue by alexey-khabulyak** [kamailio/kamailio#2025]
Radius extra parameter are limited by MAX_EXTRA (only 4)
Can u make it configurable by kamailio.conf or incrase?
https://github.com/kamailio/kamailio/blob/master/src/modules/misc_radius/extra.c#L81

**Comment by miconda** [comment]
Probably the easy one for now would be to increase, what would be the value you would need there?

**Comment by alexey-khabulyak** [comment]
I need at least 10.
Is there a strong reason to limit? What value is optimal? i am worrying because as i can see misc module creates static buffer regardless extra parameters from config file.
Thnx

**Comment by sgmarc** [comment]
@miconda, Kamailio has its own RADIUS dictionary and attributes.  But we need to send custom auth request. Here is example from Cisco VoIP:

User-Name = "74951011123"
Calling-Station-Id = "74951011123"
 Called-Station-Id = "74951234567"
Service-Type = 30
Acct-Session-Id = "93F51D6D 1FD111E0 99AD0014 F26ABCA0"
Cisco-AVPair = "xpgk-remote-id=kamailio"
Cisco-AVPair = "xpgk-src-number-in=74951011123"
Cisco-AVPair = "xpgk-dst-number-in=74951234567"
h323-conf-id = "93F51D6D 1FD111E0 99AD0014 F26ABCA0"
h323-call-origin = "originate"
h323-call-type = "VoIP"
NAS-Port = 0
NAS-IP-Address = 192.168.1.1

And thought to do it with auth_extra string. But faced with a limitation MAX_EXTRA.To make it universal I propose to make a sufficiently large number. Then it will be possible to write a request and emulate the request from any equipment. Also be able add custom dictionaries from FreeRADIUS to Kamailio: radis_dictionary_add('custom_dict_file'). Then the request can be made using the fields of custom dictionaries.

**Comment by miconda** [comment]
In increased MAX_EXTRA to 32 for both auth_/misc_radius modules.

A contribution to make it configurable via a modparam would be nice, I am not using those modules myself, so if someone wants to pick this up and make a pull request, definitely it will be something worth merging.
