### ISSUE TITLE
[Feature Request] Add reload capability for geoip2 module

### ISSUE THREAD

**Issue by joelsdc** [kamailio/kamailio#2029]
### Description

Currently, the `geoip2` module loads the IP database at startup and keeps it in cache and there is no way to tell Kamailio to reload the database without a full restart.

### Possible Solutions

To keep this module inline with other modules that use external datasources, I would suggest to implement a new RPC command and a new geoip2 function to reload the database defined in the `path` geoip2 modparam without the need of a restart.

I'm not aware of the effort required for implementing either of them, but only having an RPC command would effectively solve this issue as you can call RPC commands from within Kamailio conf, thus, the reload function would not be something strictly required but more of a nice-to-have.

### Examples:

Function:
```
geoip2_reload()
```

RPC command:
```
kamctl rpc gip2.reload / kamctl rpc geoip2.reload
```

Kamcmd command:
```
kamcmd geoip2.reload
```

**Comment by joelsdc** [comment]
Hello, 

It's been a while so I thought I'd re-ask to see if this is something that can be implemented?

Thanks!

**Comment by henningw** [comment]
@joelsdc this has been implemented in the commit referenced above. If you can, give it a try, close this issue.
