### ISSUE TITLE
UAC

### ISSUE THREAD

**Issue by Antoineb2s** [kamailio/kamailio#2036]
Hi,

I'm trying to register to a SIP provider (v5.2.4), so I added in kamailio.cfg: 

...
loadmodule "uac.so"
...

modparam("rr", "append_fromtag", 1)
modparam("uac", "credential", "user:host_provider_ip:password")
modparam("uac", "reg_retry_interval", 300)

Seems that nothing happens after a service restart.

I also tried : 
`kamcmd uac.reg_dump`
`error: 500 - command uac.reg_dump not found`

Is there something I misunderstood ?

Thanks in advanced !

**Comment by miconda** [comment]
Run `kamctl rpc core.modules` and see if uac is listed there -- maybe you have some parts of config between `#!ifdef ... #!endif` or something else missing there.

Anyhow, it looks like a config issue, not a bug in the code. For such discussions, use `sr-users@lists.kamailio.org` mailing list.
