### ISSUE TITLE
topos_d and topos_t database varchar(128) too short for IPv6 

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#2043]
With the default `*_contact ` address columns as `varchar(128)`, TOPOS is unable to handle inserting values into the database when using IPv6, which often has contact information hitting or exceeding 256 chars (tested with PostgreSQL).  Perhaps these columns can be switched to the `text` type.

**Comment by henningw** [comment]
Thanks for the report.
Currently the *_contact columns are "uri_len" define, which is indeed 128 chars long.
So I suggest to switch this to "contact_len" define - which is 512 chars long. This is also used in the location table and was changed for similar reasons in 2017.

**Comment by henningw** [comment]
Looking if there are other suggestions or objections about this change.. If not I would change this by the middle of the week.

**Comment by miconda** [comment]
I am fine with this change, but I think uri_len should be also increased to at least 256 if people found that 128 is not enough for specific cases when ipv6 is used.

**Comment by henningw** [comment]
Ok, I will investigate this as well - would be a bit more extensive change, but better to change it now before 5.3 then later.

**Comment by henningw** [comment]
The topos change were done, uri_len change as well - close this one.

**Comment by henningw** [comment]
Just to add - I did not bumped the table versions of the changed tables, as this were a non-breaking changes. The old code should work with the new table definitions and vice-versa.
