### ISSUE TITLE
Phonenum module not working when invoked from other than cfg file

### ISSUE THREAD

**Issue by balajeesv** [kamailio/kamailio#2052]
### Description
 I have kamailio.cfg file for configuration and Lua files for processing messages. What I observed is PHONUM module is not initialized during startup. And when using phonenum module it fails. I am invoking phonenum module in lua with "KSR.phonenum.match". This is in continuation to issue [1883](https://github.com/kamailio/kamailio/issues/1883), which i cannot reopen.Please check this and let me know any further logs required.

#### Reproduction
1. cfg file only have configuration 
2. Invoke phonemun module through KEMI "KSR.phonenum.match" in other file
3. Test to validate phonenum

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1655]: sr_kemi_lua_exec_func_ex(): param[0] for: isflagset is int: 1
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1651]: sr_kemi_lua_exec_func_ex(): param[0] for: match is str: +919876543210
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:1651]: sr_kemi_lua_exec_func_ex(): param[1] for: match is str: src
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: phonenum [phonenum_pv.c:312]: phonenum_update_pv(): container not found: +919876543210
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:934]: lua_sr_pv_get_val(): pv get: $rc
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: [core/pvapi.c:371]: pv_cache_add(): pvar [$rc] added in cache
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: app_lua [app_lua_sr.c:934]: lua_sr_pv_get_val(): pv get: $phn(src=>valid)
Aug 29 08:33:27 ip-10-130-74-105 /usr/local/sbin/kamailio[2157]: DEBUG: phonenum [phonenum_pv.c:162]: pv_parse_phonenum_name(): phonenum [src] - key [valid]
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions
In kamailio.cfg if I add some dummy route(as below) then Phonenum module is initialized and it is working as expected.
route[PHONENUM] {
if($phn(src=>valid)==1) {
xlog("dummy route\n");
}
}

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by sergey-safarov** [comment]
Please paste information about kamailio version and used operation system.

**Comment by miconda** [comment]
I  just added `resid` parameter that allows registering the container result via modparam, see:

  * https://github.com/kamailio/kamailio/commit/d2bac426192c074368bf78014e0d1d0ca97f3274

You have to use the git master branch. I didn't have an option to test, so feedback if it works or not would be appreciated.

For older version, try the workaround of getting the value or printing `$phn(src=>valid)` from KEMI script, before using the `KSR.phonenum.match()` function, like:

```
KSR.xdbg("$phn(src=>valid)\n");
```

**Comment by balajeesv** [comment]
Minor issue in fetching value of resid parameter, raised review [2054](https://github.com/kamailio/kamailio/pull/2054) please check. 

Working in master with this minor fix.

**Comment by henningw** [comment]
close this one - according to report it works not. The fix was also merged.
