### ISSUE TITLE
dialog database varchar(128) too short for IPv6

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#2053]
Related to #2043.

When using the database for dialogs, the `caller_contact` and `callee_contact` columns are too short.

The following seems to help.
```
ALTER TABLE kamailio.dialog ALTER COLUMN caller_contact TYPE varchar(255);
ALTER TABLE kamailio.dialog ALTER COLUMN callee_contact TYPE varchar(255);
```

**Comment by henningw** [comment]
It was actually already increased in git master:

henning@linux:~/repositories/kamailio> grep contact utils/kamctl/mysql/dialog-create.sql 
    `caller_contact` VARCHAR(255) NOT NULL,
    `callee_contact` VARCHAR(255) NOT NULL,

**Comment by henningw** [comment]
Therefore it should be already addressed, if not please re-open.
