### ISSUE TITLE
Db_cassandra module in kamailio/kamailio-cli docker image

### ISSUE THREAD

**Issue by gbmotra** [kamailio/kamailio#2071]
hi please 
Add Db_cassandra module in kamailio/kamailio-cli doker image.

**Comment by sergey-safarov** [comment]
I tried build `db_cassandra` module and get error
```
Compiling dbcassa_base.cpp
g++ -fPIC -DPIC -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -Wall -Os -fomit-frame-pointer -g -D_GNU_SOURCE -Wno-write-strings -Wno-deprecated -Wno-unused-function -Wno-sign-compare -Wno-strict-aliasing -fPIC -DPIC -funroll-loops -Wcast-align -m64 -minline-all-stringops -falign-loops -ftree-vectorize -fno-strict-overflow -mtune=generic -Wall -Os -fomit-frame-pointer -g -D_GNU_SOURCE -DNAME='"kamailio"' -DVERSION='"5.3.0-pre1"' -DARCH='"x86_64"' -DOS='linux_' -DOS_QUOTED='"linux"' -DCOMPILER='"gcc 9.2.0"' -D__CPU_x86_64 -D__OS_linux -DVERSIONVAL=5003000 -DCFG_DIR='"/etc/kamailio/"' -DSHARE_DIR='"/usr/share/kamailio/"' -DRUN_DIR='"/var/run/kamailio/"' -DPKG_MALLOC -DSHM_MMAP -DDNS_IP_HACK -DUSE_MCAST -DUSE_TCP -DDISABLE_NAGLE -DHAVE_RESOLV_RES -DUSE_DNS_CACHE -DUSE_DNS_FAILOVER -DUSE_DST_BLACKLIST -DUSE_NAPTR -DWITH_XAVP -DMEM_JOIN_FREE -DF_MALLOC -DQ_MALLOC -DTLSF_MALLOC -DDBG_SR_MEMORY -DUSE_TLS -DTLS_HOOKS -DUSE_CORE_STATS -DSTATISTICS -DMALLOC_STATS -DUSE_SCTP -DFAST_LOCK -DADAPTIVE_WAIT -DADAPTIVE_WAIT_LOOPS=1024 -DCC_GCC_LIKE_ASM -DHAVE_GETHOSTBYNAME2 -DHAVE_UNION_SEMUN -DHAVE_SCHED_YIELD -DHAVE_MSG_NOSIGNAL -DHAVE_MSGHDR_MSG_CONTROL -DHAVE_ALLOCA_H -DHAVE_TIMEGM -DHAVE_SCHED_SETSCHEDULER -DHAVE_IP_MREQN -DUSE_RAW_SOCKS -DHAVE_EPOLL -DHAVE_SIGIO_RT -DSIGINFO64_WORKARROUND -DUSE_FUTEX -DHAVE_SELECT  -I/usr/include/thrift -DMOD_NAME='"db_cassandra"' -c dbcassa_base.cpp -o dbcassa_base.o
dbcassa_base.cpp:37:10: fatal error: protocol/TBinaryProtocol.h: No such file or directory
   37 | #include <protocol/TBinaryProtocol.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:41: dbcassa_base.o] Error 1
```
Looks as this module requires [TBinaryProtocol.h](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/protocol/TBinaryProtocol.h) from [apache/thrift](https://github.com/apache/thrift) repo.

This software not packaged for Alpine dist.
I not ready to deep into `apache/thrift` and how to package this software for Alpine dist.
Could you create this software package by self, then we continue on `db_cassanda` module packaging.

**Comment by sergey-safarov** [comment]
you can find packaging rules for Debian dist [here](https://github.com/apache/thrift/blob/master/debian/control) and for Fedora dist [here](https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/t/thrift-0.10.0-19.fc32.src.rpm) (need extract spec file)

**Comment by miconda** [comment]
The db_cassandra module is practically not supported at this moment, requires very old library version only to compile, then should be also tested. Probably this should be added to the documentation.

It is kept in the hope that someone will pick it up and upgrade it.

If someone needs to interact with cassandra, but not as a database connector, then look at ndb_cassandra module, that should be more actual.

I am closing this one, because packaging of this module is out of scope given the current state of it.
