### ISSUE TITLE
Problem Parsing Route Header

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#2079]
Problem : 
    Route header doesn't seem to be behaving correctly when it contains more than one URI.
    This issue seems to affect uac_restore mechanics and routing mechanics.

In order to test this i've created a test call with a in-dialog "OPTIONS" request. In one scenario, the OPTIONS contains two Route headers with one URI each. In the other scenario, the OPTIONS contains one Route header with two URIs. In the last scenario, there is a failure routing the request to it's destination (404 - Not here). In both scenarios the URIs used are the same and the remaining of the call beahviour is the same.

Find attached to this report two pcap files with the two scenarios. 
2Routes.pcap - Two Route headers with one URI each
2URIs.pcap - One Route Header with two URI.

[Captures.zip](https://github.com/kamailio/kamailio/files/3662300/Captures.zip)

If needed i can do more testing.

Best Regards, 

Duarte Rocha

**Comment by miconda** [comment]
One of scenarios is with ACK and OPTIONS without any Route headers, so not with two headers.

You also have to take the pcap on kamailio, to see what kamailio adds as record route headers and the sip traffic on both sides with caller and callee.

With a quick check here, all is working fine with one Route header having two addresses. Verify your scenarios and if you get the sip traffic with proper headers and the issue is still there, reopen and add pcaps taken on kamailio with the sip traffic in both sides.

**Comment by duarterocha91** [comment]
Hello Daniel,

Thank you for your answer.

In both scenarios there is Route headers. You sure you're looking at the
correct Options?

The OPTIONS request is based on the 200 Ok received by the callee, so it
has everything that Kamailio added. The capture is taken on the Kamailio.

I also have another scenario where i have 2 uris in one route, where
Kamailio routes correctly but uac_replace fails. But i wasn't able to
reproduce it for testing yet. Are you able to try two adresses in one route
with a uac_restore on auto mode to a different number?

Best regards


A sexta, 27/09/2019, 11:52, Daniel-Constantin Mierla <
notifications@github.com> escreveu:

**Comment by duarterocha91** [comment]
Sorry, in the previous email i meant to say that the uac_restore fails, and
not the replace.

A sexta, 27/09/2019, 12:10, Duarte Rocha <duarterocha91@gmail.com> escreveu:

**Comment by miconda** [comment]
Well, the wireshark couldn't follow the streams, anyhow, I looked on the plain text represenation and  the one that fails seems to has a broken Route header because it has `\r\n` as four characters at the end.

**Comment by duarterocha91** [comment]
Greetings,



Sorry about the confusion, the Routing works perfectly with multiple
addresses in one header. I think i have a better scenario now.



So, i have this SBC with 2 IPs (212.13.40.205 and 212.13.40.209) where in
INVITES i use uac_replace_from() and uac_replace_to(). Kamailio UAC’s
module is set for “AUTO” restore.



In this scenario, the original call arrives at Kamailio like this
(Restore.pcap) :

                From: 351211450093

To : 351258064574





The call is routed to my client and the packet leaves Kamailio like this
(Restore.pcap) :

                From: +351211450093

To : +351258064574





The info is stored in the “vst” and “vsf” parameters in Record-Route header
 ( Note :  Kamailio has 2 IPs) (Restore.pcap):







Later, i receive a BYE request from the client with To and From like this
(Restore.pcap) :



The To Header has “I2116446I_500” as user part which i think it’s still RFC
compliant. Regarding this i couldn’t find anything proving that wrong.



Here is where the problem  starts. If the auto restore is activated, the To
header end result is malformed  (Restore.pcap) :



If i deactivate the restore and a similar test, the headers are unchanged
 (NotRestore.pcap):







I have a couple questions about this :

                Are the vsf and vst alone enough to do a proper restore ?
If not, what inputs does it take ?

                Does the “AUTO” restore works if the client sends me a
different user than i sent him ?



Please find the captures mentioned in annex.



Thanks a lot for your help.



Best Regards,





[image: g9telecom]

*Duarte Rocha*
Desenvolvimento de software
T.: 351 211 450 050
F.: 351 221 450 059
www.g9telecom.pt

[Download vCard] <http://public.g9telecom.pt/vCards/tec45er-duarte.vcf>

[image: certif]



Esta mensagem (incluindo anexos) pode conter informação confidencial para
uso exclusivo do destinatário. Se não for o destinatário pretendido não
deverá usar, distribuir ou copiar este e-mail, devendo eliminá-lo e
informar o emissor imediatamente. Obrigado.

This message (including any attachments) may contain confidential
information for the exclusive use of the recipient. If you are not the
intended recipient, you should not use, distribute or copy this email, and
you must delete it and inform the issuer immediately. Thank you.

**Comment by henningw** [comment]
Please create a new issue with the problems you mentioned regarding the auto restore mode if you think there is an error in Kamailio.
About the other questions - the auto mode will work if the vsf and vst headers are in the message. No manual interventions are necessary.
About the changing of the user on the client side - it depends how it was exactly changed (e.g. including tags etc..). This scenario should be discussed on sr-users list, as the tracker is not the right place for discussions.
