### ISSUE TITLE
Allow more options on dispatcher.set_state

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#2085]
Greetings,

Dispatcher RPC command allows to change the runtime state of a GW using its Group ID and the IP.  

In my implementation i have 2 Kamailio machines in an HA setup and, as such, i have the GW configured twice with same group_id and different sockets (Different HA adressess - one for each machine). 
I would like to be able to disable on runtime GWs that are configured with an HA adress that isn't present yet on that machine. To be able do that, the combination of GroupID + IP is not enough, but Socket + IP would be enough. 

Is this possible to implement ?

Best Regards

**Comment by miconda** [comment]
Pushed a commit (referenced abive) with a new rpc command allowing to set the state by matching on `duid` attribute, which is intended to be sort of unique identifier per destination record.
