### ISSUE TITLE
Proposed: Consolidate example kamailio.cfg files

### ISSUE THREAD

**Issue by tuxd00d** [kamailio/kamailio#209]
- There are relatively few differences between the example configuration files.
- The time needed to maintain three separate files doesn't match the benefit.
- The power of the #!define and #!ifdef system negates the need for separate examples.
- It is simple enough to remove #!ifdef sections if one wishes to slim down the file size.
- I'll do a consolidation if no valid argument against it is raised.

**Comment by miconda** [comment]
The kamailio-oob.cfg can get new features as much as wanted. But the other two, kamailio.cfg and kamailio-basic.cfg should stay rather simple. Even the defines can enable/disable features, having a big file is preventing from learning it quickly.

I agree that examples need to be reviewed and consolidated somehow, but again, not affecting kamailio-basic.cfg and kamailio.cfg that much.

**Comment by foucse** [comment]
IMHO, configuration file consolidation in one single file will make the learning curve much steeper for beginners and newcomers. I found it rather difficult to read and understand one big file with alot of #!ifdef blocks.

Multiple, but simple and very specialized configuration files have the benefit of demonstrating quickly some simple functionalities which is the main goal of an "example configuration".

Autogeneration of make files using some templating language can ease their maintenance and this doesn't remove the need to have one single "most complete and standard-compliant" example configuration file.

**Comment by miconda** [comment]
The folder examples has a set of configuration files for various use cases (e.g., ims nodes). Mabe some of them need updates, but looks like what @foucse is asking -- new samples can be added there.

The config file can be split in many files, then have kamailio.cfg use *include_file" to build a complete configuration from the pieces.
