### ISSUE TITLE
centos7 rpm for evapi

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2098]
Please package evapi into centos7 rpm.

**Comment by sergey-safarov** [comment]
Could anybody help me update `make every-module` command to build `evapi` module
I simple added `kevapi` but this not help. Module not compiled.

https://github.com/sergey-safarov/kamailio/commit/4cca3e3a21b5a49a59445f3aa8136754cdf84082

**Comment by henningw** [comment]
@sergey-safarov is this still valid, or do you managed by now to build the module?

**Comment by sergey-safarov** [comment]
Yes, it is actual.
Need look why module not compiled after `kevapi` argument addition into `make` command.

**Comment by henningw** [comment]
Thanks. One question, where is the "k" prefix coming from, is the module not named evapi?

henning@static:~/repositories/kamailio$ make modules modules=modules/evapi
make -C src/ modules
make[1]: Entering directory '/home/henning/repositories/kamailio/src'
CC (gcc) [M evapi.so]           evapi_mod.o
[...]

**Comment by sergey-safarov** [comment]
Thanks Henning @henningw 
Could you look make command for other modules
https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/obs/kamailio.spec#L1236-L1309

Looks as all modules compiled using `k`  prefix.

**Comment by henningw** [comment]
Ok, I see. Can you try "kev":
# pkg libev modules
module_group_kev

**Comment by sergey-safarov** [comment]
Thanks Henning @henningw
That is help me package module.

On OpenSUSE dist module cannot be packaged. I got error
```
Problem: libevent-devel-2.1.11-2.1.x86_64 conflicts with libev-devel provided by libev-devel-4.27-1.2.x86_64
 Solution 1: deinstallation of libev-devel-4.27-1.2.x86_64
 Solution 2: do not install libevent-devel-2.1.11-2.1.x86_64
```
New module available formaster branch on [CentOS repo](http://rpm.kamailio.org/centos/).

As libevent used in several kamailio modules I cannot remove this package. To build both on OpenSUSE need use one of `libevent` or `libev` library by `evapi` and other modules.
