### ISSUE TITLE
uac: allow ha1 to be used in uac_reg_request_to

### ISSUE THREAD

**Issue by covalschi** [kamailio/kamailio#2102]
### Description

I'm using uac module to remote authenticate to a trunk. With the addition of ha1 used instead of plaintext password it is also would be nice to be able to use uac_reg_request_to with it.

### Expected behavior
There should be auth_ha1_avp for uac module, which will use ha1 instead of plaintext to build the request
#### Actual observed behavior
auth_password_avp is set to empty string or dot respectively of how you specify it in database, ha1 is not used in uac_reg_request_to

### Possible Solutions

Well logically auth_ha1_avp should be prioritized over auth_password_avp

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.0-dev1 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 6.3.0
```

* **Operating System**:

```
Debian 10 in docker
```

**Comment by miconda** [comment]
Feature added in master using mode parameters for uac_reg_request_to() and uac_auth() -- see the readme of the module. In this way, the uac_auth() has support for ha1 passwords even when using the credentials modparam.

I haven't tested, therefore feedback with the results of testing are appreciated.
