### ISSUE TITLE
Store full JSON output of rtpengine_query in avp

### ISSUE THREAD

**Issue by hrant-ian** [kamailio/kamailio#2130]
### Description

Currently the rtpengine_query function stores some values in predefined avps. I would like to have access to the whole output returned by the query to rtpengine. Sample provided at: https://github.com/sipwise/rtpengine#query-message

### Possible Solutions / Expected behavior

Introduce a new avp which stores the full output in json format.

**Comment by miconda** [comment]
https://www.kamailio.org/docs/modules/devel/modules/rtpengine.html#rtpengine.f.rtpengine_query_v
