### ISSUE TITLE
Allow function set_advertised_address to receive variable as parameter

### ISSUE THREAD

**Issue by pwakano** [kamailio/kamailio#2137]
### Description

Currently the functions set_advertised_address and set_advertised_port only accept strings as parameters. Trying to use it with variable causes an error. 
Having the function using a hard coded value is not a good practice and in order to add flexibility to the script in different installations it would be nice to have this function accepting variables.
Also, the 'advertise' option on the 'listen' parameter is not always desired because it apply for all messages sent via the socket, and there are situations where different advertised IP for the same interface are necessary.

### Expected behavior
set_advertised_address should receive a variable as parameter and use its value to change the SIP headers.

### Actual observed behavior
Kamailio won't start if set_advertised_address is used with a variable due to script parse error or it will set the SIP message with the literal string "$var(test)" for example, instead of using the value of $var(test).

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
# kamailio -v
version: kamailio 5.2.2 (x86_64/linux) 67f967
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 67f967 
compiled on 11:40:41 Mar 11 2019 with gcc 4.8.5

```

* **Operating System**:

```
# uname -a
Linux voice-conn-kamailio-1 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by pwakano** [comment]
After reading the purpose of the corex module, I think the idea can be changed to add a new function in the corex module which would do the same as the set_advertised_address, but accepting variables as parameters. Then there is no need to modify the old function.

**Comment by negbie** [comment]
+1

modparam("corex", "alias_subdomains", "example.org")
and set_advertised_address with private variables would be quite convenient compared to using functions from rr module and xavp_via_params.

**Comment by beneditomarques** [comment]
Hi,
    Its possible to use set_advertised_address with variable as parameter in any kamailio version? I've been trying the solution mentioned by @negbie before in last comment, but it doesn't work. I'm using kamailio 5.4.4.

**Comment by pwakano** [comment]
Has anyone figured out a clean alternative for this problem?

**Comment by akam-it** [comment]
> Has anyone figured out a clean alternative for this problem?

unfortunately no, only using the different sip proxy server :(

**Comment by henningw** [comment]
In the end this is a free collaboration project. If nobody has time or financial resources to support the development of this new feature, then its probably not that important. This particular request is from 4 years ago. If you need some support in creating a PR, please ask on our sr-dev mailing list.

**Comment by miconda** [comment]
Actually is possible to set the address and port in Via added by Kamailio using variables for quite some time, see the example at:

  - https://www.kamailio.org/docs/modules/stable/modules/corex.html#corex.f.via_use_xavp_fields

That should offer the same functionality as set_advertised_address()/set_advertised_port(). If anyone wants to enhance the two functions as well, just make a PR.
