### ISSUE TITLE
Unable to pass Extra parameter to IMS_CHARGING module

### ISSUE THREAD

**Issue by harishyadav1465** [kamailio/kamailio#2138]
**Version**  : kamailio 4.2
**platform** : linux

**Description**

Currently I am using **ims_charging** module ...so from  the script we are calling **RO_CCR(6 param)** function ..Until this point it is working fine But the problem occurs when i am passing extra parameter in **RO_CCR(7 param)** function,we are getting **Too many arguments error** from the script **BUT** we made appropriate changes in ims_charging for this.please see the below code changes for more info.

**static int **w_ro_ccr****(struct sip_msg *msg, str* route_name, str* direction, str* charge_type, str* unit_type, int reservation_units, char *_d,char *cpaas);

static cmd_export_t cmds[] = { 
                { "Ro_CCR",     (cmd_function) **w_ro_ccr**,7, ro_fixup, 0, REQUEST_ROUTE },
                { 0, 0, 0, 0, 0, 0}
};

**Comment by miconda** [comment]
The config file interpreter supports functions with max 6 parameters. Changing that will require updates of the code in the core. However, adding support for more parameters is not optimal also from coding best practices point of view.

A solution is to serialize the parameter in a format that you can parse internally (e.g., json, or name=value1;name2=value2, or with separator param1;param2). Or maybe you can split the function in two, each with fewer parameters. If you want to discuss more, use sr-users mailing list.

**Comment by harishyadav1465** [comment]
Thanks for the answer...i will try your suggestions
