### ISSUE TITLE
Kamailio sending CCR TERMINATE request without waiting for the CCR INITIAL request response 

### ISSUE THREAD

**Issue by harishyadav1465** [kamailio/kamailio#2143]
**Description**

We are using ims_charging module and Freediameter as diameter server for billing process....recently we faced one issue...For Initial **INVITEs**  kamailio sending **CCR request (INITIAL_REQUEST)** to **diameter server** but if we receive Immediate **CANCLE** for the **INVITE**, kamailio sending **CCR request ( TERMINATE_REQUEST )** without waiting for the **CCR request (INITIAL_REQUEST) response** from the **Diameter server.**..

**Expected behavior**
Kamailio has to send **CCR request ( TERMINATE_REQUEST )**  after getting the **response** from the **INITIAL_REQUEST.**

 **Additional Info**
 kamailio server :  4.2
 platform            :  linux

**Comment by henningw** [comment]
Thanks for the report. Unfortunately the version 4.2 is long end of life and is not supported anymore. Please update to a version from the 5.2.x or 5.3.x releases.

**Comment by harishyadav1465** [comment]
is it working as expected in 5.2.x or 5.3.x version ?

**Comment by henningw** [comment]
I don't know, but then it could be analysed and if its not working also fixed in our code.

**Comment by WaledEzzi** [comment]
Hello Team,

I am facing the same issue here ,could you please help us how can we resolve this issue..

My version as below:
root@550815e90f7a:/# kamailio -v
version: kamailio 5.3.2 (x86_64/linux) 87e8a1

Kindly to help us and thank you so much in advance ..

Should you need any info please let me know ..

Waled

**Comment by henningw** [comment]
Please don't comment at closed issues. I would suggest to update to a more recent version, e.g. the latest 5.6.x or 5.7.x. There were some bugfixes in this module regarding the state machine.
