### ISSUE TITLE
force_send_socket with pseudo variable

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2145]
### Description

I have listeners on multiple ports. (5060, 5080, 7000)
I want force change port to 5060 for outbound messages. To do this i use
```
force_send_socket($Ri:5060);
```
When I check config using `kamailio -c`, then I get error message
```
syntax error, unexpected AVP_OR_PVAR
```
Could you add support of pseudo variable as argument of `force_send_socket` function

**Comment by pwakano** [comment]
Sergey, you can use the $fs variable for this purpose:
$fs = $proto + ":" + $Ri + ":5060"

But anyway, many old functions are string only and not all have an equivalent method that supports pseudo variables.... I think all legacy functions need a rework allowing pseudo-variables as parameter.

**Comment by ycaner06** [comment]
there is a function  set_send_socket instead of  force_send_socket  that supports p-variables.

https://kamailio.org/docs/modules/devel/modules/corex.html#corex.f.set_send_socket

**Comment by miconda** [comment]
The alternatives are there, as given by above comments. Closing.

**Comment by henningw** [comment]
I've added a short note about it to the 5.3 and devel cookbook.
IMHO we should think about removing this old redundant functions, at least if there are several newer implementation, where one is functional equivalent.
I was already discussed one year ago, without conclusion: [link](http://sip-router.1086192.n5.nabble.com/force-send-socket-fs-behaviour-when-binding-to-INADDR-ANY-td140353.html)
