### ISSUE TITLE
enforce REGISTER with AKAv1  (IMS)

### ISSUE THREAD

**Issue by moshe-av** [kamailio/kamailio#2150]
Can kamailio enforce client to REGISTER with AKAv1?

Here our setup:
1. kamailio version 4.3.4 for IMS
2. Boghe IMS client v1.0.58.550
3. scscf.cfg is configure with:
	#!define REG_AUTH_DEFAULT_ALG "AKAv1-MD5"

a. First REGISTER fails with 401 Unauthorized
b. Second REGISTER 200 OK, but the REGISTER is MD5 and not AKAv1
	Authorization: 
	Digest username="bob@net1.test",
	realm="net1.test",
	nonce="XdzPaF3czjz0oMKPeNLScpKAfb9prE7x",
	uri="sip:net1.test",
	response="854d9c2f3fe3dd3c96c14f8a2d20c2f9",
	algorithm=MD5

Thank you,

**Comment by miconda** [comment]
The issue tracker is used for reporting bugs or requests for new features related to kamailio C code.

Questions related to use of kamailio have to be addressed to sr-users@lists.kamailio.org mailing list.
