### ISSUE TITLE
http_client: Plumbing of CURL errors through $curlerror seems incorrect

### ISSUE THREAD

**Issue by abalashov** [kamailio/kamailio#2154]
On Kamailio 5.3.0 (`ad1905`) on CentOS 7, with `libcurl` 7.29.0-46, an `http_connect()` request to an unresponsive server...

```
http_connect("stuff", "/url", "$var(http_res)");
```

.. correctly sets `$var(http_res)` to `28`, which is an operation timeout per https://curl.haxx.se/libcurl/c/libcurl-errors.html.

However, `$curlerror($var(http_res))` returns the value `"No error"`. This is not quite as promised in https://kamailio.org/docs/modules/5.3.x/modules/http_client.html#idm480.

Thanks in advance!

-- Alex

**Comment by oej** [comment]
$curlerror is basically a wrapper around curl_easy_strerror

I will try to test this, but wonder if there's a way to check if error 28 is defined in your version of curl.

**Comment by henningw** [comment]
@abalashov - did you managed to have a look to your CURL installation about the mentioned error (probably somewhere in /usr/include/..)

**Comment by miconda** [comment]
@abalashov - was this sorted out in your side, or still needs investigation? If so, provide the details requested above to try to fix it.

**Comment by miconda** [comment]
Closing this one, no troubleshooting data provided for 2 months. Reopen if it is still valid and troubleshooting data is provided.
