### ISSUE TITLE
kamdbctl has bashism ("test ==")

### ISSUE THREAD

**Issue by gdt** [kamailio/kamailio#2157]
### Description

utils/kamctl/kamdbctl contains syntax beyond the POSIX sh stnadard.  Specifically, there are multiple instances of "==" in test(1), which should be "="

#### Reproduction

In the 5.3.1 release, see line 156.

### Possible Solutions

Change == to = (multiple places).

### Additional Information

5.3.1 source tarball

This was detected by pkgsrc which has checks for various portability issues.

**Comment by miconda** [comment]
Can you make a pull request with the changes, so it can be reviewed and merged if all fine with it?

**Comment by gdt** [comment]
Sure, will do.

**Comment by henningw** [comment]
Thanks, pull request #2159 was merged
