### ISSUE TITLE
Debian package version don't support distribution upgrades

### ISSUE THREAD

**Issue by sebastic** [kamailio/kamailio#2160]
When upgrading from stretch to buster the kamailio packages aren't upgraded because the 5.3.1+stretch version is greater than 5.3.1+buster:
```
$ dpkg --compare-versions 5.3.1+stretch gt 5.3.1+buster ; echo $?
0
```

The package version should include the release version instead of its codename, e.g. 5.3.1+deb9u1 & 5.3.1+deb10u1 like done for [stable updates](https://www.debian.org/doc/manuals/developers-reference/pkgs.en.html#upload-stable):
```
$ dpkg --compare-versions 5.3.1+deb10u1 gt 5.3.1+deb9u1 ; echo $?
0
```

**Comment by henningw** [comment]
I've noticed the same problem as well for the 5.2.5 packages.

**Comment by linuxmaniac** [comment]
There's a problem too with the nightly and stable versions:
```
$ dpkg --compare-versions 5.3.3+0~20200417092406.72+bionic gt 5.3.3+bionic; echo $?
1
```

**Comment by linuxmaniac** [comment]
Changed our version schema and triggered new builds for 5.2|5.3|master nightly builds already,
new builds for 5.1|5.2|5.3 tagged versions in the oven right now

**Comment by linuxmaniac** [comment]
5.2.7 and 5.3.4 already released with the new versioning schema
