### ISSUE TITLE
dispatcher: select using IP proto

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2170]
### Description

Some daemon not able to handle IPv4 and IPv6 calls simultaneously. As example `FreeSwitch`. Need to create two dispatcher records for IPv4 and IPv6 FreeSwitch sockets. Each socket will be able to handle appropriate call type. Mixing not allowed.

Could you add `dispatcher` module options to compare used IP version for incoming call and for dispatcher backend sip uri. And select backend only if IP versions matched.

**Comment by henningw** [comment]
What about just checking the IP version in the cfg script and then calling the appropriate dispatcher group?

**Comment by henningw** [comment]
https://www.kamailio.org/docs/modules/5.2.x/modules/ipops.html#ipops.f.is_ip_type

**Comment by sergey-safarov** [comment]
Thanks Henning.
Looks as this will be enough for my needs.
