### ISSUE TITLE
KEMI record_route_preset requires 2 parameters instead of 1

### ISSUE THREAD

**Issue by WhiteyDude** [kamailio/kamailio#2171]
### Description

Hi all!

It looks like in https://github.com/kamailio/kamailio/pull/2051 `record_route_preset` was exposed to KEMI, which is awesome (thank you @aalba6675 !). However the second parameter in this function should be optional (see https://kamailio.org/docs/modules/devel/modules/rr.html#rr.f.record_route_preset).

### Troubleshooting

When using with a single parameter, the following error is thrown:

`Dec  9 13:24:13 ip-10-0-0-1 /usr/local/sbin/kamailio[15828]: ERROR: app_ruby [app_ruby_api.c:499]: sr_kemi_ruby_exec_func_ex(): invalid str parameter type 2 (1)`

#### Reproduction

(ruby Kemi)

```ruby
# Failure
KSR::RR.record_route_preset('1.2.3.4:5060')
# Success
KSR::RR.record_route_preset('1.2.3.4:5060', '')
# Success
KSR::RR.record_route_preset('1.2.3.4:5060', '1.2.3.4:5060')
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.0-dev2 (x86_64/linux) 283e46-dirty
```

**Comment by miconda** [comment]
Just exported in master branch the variant with one parameter:

```
KSR::RR.record_route_preset_one('1.2.3.4:5060')
```
Test and see if ok. It will be backported.
