### ISSUE TITLE
number of websocket connections

### ISSUE THREAD

**Issue by swuy** [kamailio/kamailio#218]
Hello!
I have kamailio installed as a part of kazoo server (kamailio server and server with other apps) with enabled websocket role. As I see in .cfg file there is default restriction for connection from one IP - 50, so 51st client from the same IP address get 403 error. So

1) How can I see how many websocket connections from one IP I have? (Except log messages in kamailio.log)

2) Our kamailio work fine for week and a half, after that I see messages in kamailio log: 
"[Some_IP_address] is at the maximum allowable sockets per IP, rejecting request for another websocket"

I checked connections from OS and saw that there is one connection not fifty.
lsof -ni TCP:8080 | grep [Some_IP_address]
kamailio 30673 kamailio  132u  IPv4 4667683      0t0  TCP [Some_IP_address]:webcache->[Some_IP_address]:57688 (ESTABLISHED)

After restarting kamailio all work fine for another week and a half and repeat.
Is it some bug?

**Comment by kamailio-sync** [comment]
Hi,

"kamctl fifo ws.dump" shows you all websocket connections kamailio knows 
about.

**Comment by miconda** [comment]
The point 2) seems to be specific to Kazoo configuration (as I searched for the log message on the web and pointed there),  so it is not inside kamailio code but in that config file you are using. On a quick look, there is a counter of connections stored in a hash table that might not be properly managed. You have to address the issue to kazoo project.

**Comment by swuy** [comment]
thank you!
