### ISSUE TITLE
[kamailio 5.2.5] Wrong send socket on a multi homed proxy

### ISSUE THREAD

**Issue by vitalikvoip** [kamailio/kamailio#2181]
### Description
Kamailio fails to forward in-dialog request over TCP/TLS/WS/WSS connection.

### Troubleshooting

kamailio 5.2 branch has a commit 
09ac3e47ef79dbd599b7dec5b84ae3b792f025ed cherry picked from master branch.
It makes sense for master because get_send_socket2() behavior has 
changed and function became smarter and also there were some patches to 
propagate connection it to the uac structure.

After applying this patch to 5.2.x kamailio searches for an outgoing socket, receives the first one due to limitations of get_send_socket2() and SND_F_FORCE_SOCKET flag. Then it fails to find an existing TCP connection by destination ip:port since it searches for a connection associated with a wrong socket.

#### Log Messages

```

Dec 11 21:33:49  kamailio[17999]: WARNING: <core> [core/msg_translator.c:2832]: via_builder(): TCP/TLS connection (id: 0) for WebSocket could not be found
Dec 11 21:33:49  kamailio[17999]: ERROR: tm [t_msgbuilder.c:1372]: assemble_via(): via building failed
Dec 11 21:33:49  kamailio[17999]: ERROR: tm [t_msgbuilder.c:1540]: build_uac_req(): error while assembling Via
Dec 11 21:33:49  kamailio[17999]: ERROR: tm [uac.c:517]: t_uac_prepare(): Error while building message
Dec 11 21:33:49  kamailio[17999]: ERROR: presence [notify.c:1798]: send_notify_request(): in function tmb.t_request_within
Dec 11 21:33:49  kamailio[17999]: ERROR: presence [notify.c:1897]: notify(): sending Notify not successful
Dec 11 21:33:49  kamailio[17999]: ERROR: presence [notify.c:1491]: publ_notify(): Could not send notify for message-summary
```

### Possible Solutions

Delete mentioned commit from the 5.2 branch.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
5.2.5
```

* **Operating System**:

```
linux
```

**Comment by miconda** [comment]
Somehow this issue report was not addressed yet ... does this happen for all calls in mutli homed deployment? Have you tried with the patch of commit 09ac3e4 reverted?

**Comment by vitalikvoip** [comment]
Yes, it happened to all calls in multi homed deployment and reverting  [09ac3e4](https://github.com/kamailio/kamailio/commit/09ac3e47ef79dbd599b7dec5b84ae3b792f025ed) helped to fix it.

**Comment by miconda** [comment]
Commit reverted in branch 5.2.

Did you have any chance to test with 5.3 to see if there was any side effect of the same commit?

**Comment by dmitry-sinina** [comment]
@miconda We faced same issue.
Commit https://github.com/kamailio/kamailio/commit/8d608d1c3ed0fe4c69cb02868b746cd0497dd1f5 broke tcp connections lookup in kamailio 5.3.2 as well

**Comment by miconda** [comment]
I reverted in master and 5.3 branches. I am closing this one, if any new problem reopen or create a new issue.
