### ISSUE TITLE
Kemi: Support for KSR.notice()

### ISSUE THREAD

**Issue by SipSeb** [kamailio/kamailio#2193]
### Description

The Kemi framework supports `KSR.info()` and `KSR.warn()`, but the level in between is missing. Our legacy systems use INFO logging in our dev systems and NOTICE logging in production environment. So everytime we replace some legacy Kamailio config with Kemi code, we stumble upon then missing `KSR.notice()` method or the missing "notice" level parameter to `KSR.log()`.

**Comment by miconda** [comment]
It should be there, what version do you run?

  * https://github.com/kamailio/kamailio/blob/master/src/core/kemi.c#L1369

**Comment by SipSeb** [comment]
Oh, it really is there. On this system we are still at 5.1.x, but nevertheless it is there. It is just missing in the docs, which is why I thought it was not implemented.
