### ISSUE TITLE
Request for new RPC  htable.flush to DB

### ISSUE THREAD

**Issue by zeusca** [kamailio/kamailio#2201]
### Description

Ability to flush on-demand htable from memory to DB.
 
### Possible Solutions

Implement a new RPC  `htable.flush` command

Flush hash table to database.

Name: dhtable.flush

Parameters:

    htable : Name of the hash table to flush

Example:

...
kamcmd htable.flush ipban
...

**Comment by miconda** [comment]
The htable.flush command existed for removing all items in an htable.

I pushed a commit adding htable.store rpc command, which saves the content of the htable to database. Test and if any problems, open a new bug report.

**Comment by miconda** [comment]
For reference:

  * https://www.kamailio.org/docs/modules/devel/modules/htable.html#htable.rpc.store
