### ISSUE TITLE
Kamailio 5.2.6 not able to parse uri with host part having underscore '_'

### ISSUE THREAD

**Issue by balajeesv** [kamailio/kamailio#2204]
### Description
Kamailio 5.2.6 not able to parse uri with host part having underscore '_'. 
This was working in 5.1

Migrated from 5.1 to 5.2.6 and started observing uri parse issue
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: <core> [core/pvapi.c:371]: pv_cache_add(): pvar [$avp(gw)] added in cache
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: app_lua [app_lua_sr.c:934]: lua_sr_pv_get_val(): pv get: $(avp(gw){uri.host})
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: <core> [core/usr_avp.c:887]: parse_avp_ident(): Parsing 'gw'
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: <core> [core/pvapi.c:371]: pv_cache_add(): pvar [$(avp(gw){uri.host})] added in cache
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: <core> [core/parser/parse_uri.c:1264]: parse_uri(): bad host in uri (error at char _ in state 5) parsed: <sip:+123456@long>(16) /<sip:+123456@long_duration.sample.com;timeout=60;carrierid=1212> (62)
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: ERROR: pv [pv_trans.c:1276]: tr_eval_uri(): invalid uri [sip:+123456@long_duration.sample.com;timeout=60;carrierid=1212]
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: ERROR: app_lua [app_lua_sr.c:947]: lua_sr_pv_get_val(): unable to get pv value for [$(avp(gw){uri.host})]
Jan 25 08:02:51 ip-10-130-74-93 /usr/local/sbin/kamailio[4055]: DEBUG: app_lua [app_lua_sr.c:1651]: sr_kemi_lua_exec_func_ex(): param[0] for: is_pure_ip is str:
#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by sergey-safarov** [comment]
Underscore symbol not allowed in hostname
http://domainkeys.sourceforge.net/underscore.html

**Comment by sergey-safarov** [comment]
"_" not allowed as prepend of hostname.
But looks as really not allowed in middle of hostname too.

**Comment by henningw** [comment]
Hello, thanks for the report. The hostname parsing was made more strict in 2018 (commit 4994960324d5353222b), so far we only received two reports about it. 
In git master branch there is a now a core parameter "uri_host_extra_chars" to customize this behaviour. You can easily cherry-pick this also in your 5.2 branch (you need to compile it thought):
henning@linux:~/repositories/5.2> git cherry-pick -x 038158c99da96933c2
