### ISSUE TITLE
Building a skype like software

### ISSUE THREAD

**Issue by ugintl** [kamailio/kamailio#2205]
Is it possible to use this software to create skype like features or even better? I can use linphone as the clients.

**Comment by miconda** [comment]
The tracker here is for reporting bugs in the C code of Kamailio. For discussions about how to use or configure Kamailio, use the sr-users@lists.kamailio.org mailing list.

To get started, here is the link to an old tutorial: http://kb.asipto.com/kamailio:skype-like-service-in-less-than-one-hour

If you need further assistance, then use the mailing list.
