### ISSUE TITLE
Kamailio Service error 

### ISSUE THREAD

**Issue by ratssingh** [kamailio/kamailio#2210]
Hi There!
Can anyone help on this why this error occurring. 

 Active: active (running) since Thu 2017-10-05 21:52:21 IST; 26min ago
 Main PID: 19657 (kamailio)
   CGroup: /system.slice/kamailio.service
           ├─19657 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19659 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19660 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19661 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19662 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19663 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19664 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19665 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19666 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19667 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19668 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19669 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19670 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19671 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19672 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19673 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19674 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19675 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19676 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19677 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19678 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19679 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19680 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19681 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19682 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           ├─19683 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4
           └─19684 /usr/sbin/kamailio -DD -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 4

Oct 05 22:15:55 localhost.localdomain /usr/sbin/kamailio[19681]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Oct 05 22:15:55 localhost.localdomain /usr/sbin/kamailio[19681]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Oct 05 22:16:55 localhost.localdomain /usr/sbin/kamailio[19682]: INFO: <core> [core/parser/parse_fline.c:87]: parse_first_line(): ERROR: parse_first_line: me...short: 4
Oct 05 22:16:55 localhost.localdomain /usr/sbin/kamailio[19682]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad mes...fset: 0)
Oct 05 22:16:55 localhost.localdomain /usr/sbin/kamailio[19682]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Oct 05 22:16:55 localhost.localdomain /usr/sbin/kamailio[19682]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Oct 05 22:17:55 localhost.localdomain /usr/sbin/kamailio[19683]: INFO: <core> [core/parser/parse_fline.c:87]: parse_first_line(): ERROR: parse_first_line: me...short: 4
Oct 05 22:17:55 localhost.localdomain /usr/sbin/kamailio[19683]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad mes...fset: 0)
Oct 05 22:17:55 localhost.localdomain /usr/sbin/kamailio[19683]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<PING>
Oct 05 22:17:55 localhost.localdomain /usr/sbin/kamailio[19683]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by linuxmaniac** [comment]
The tracker here is for reporting bugs in the C code of Kamailio. For discussions about how to use or configure Kamailio, use the sr-users@lists.kamailio.org mailing list.
