### ISSUE TITLE
[FEATURE REQUEST] - Add RTT metric to usrloc for measuring subscriber latency

### ISSUE THREAD

**Issue by joelsdc** [kamailio/kamailio#2223]
### Add RTT metric to usrloc for measuring subscriber latency

This has been discussed several times in the mailing list. As I personally need this too I though it would be a good idea to open this issue for tracking. Unfortunately I'm not aware of the complexity of implementing this and I cannot code it myself, I'm happy to do any testing though or help with any other tasks.
 
Some threads were this has been commented and some solutions proposed by @miconda:

https://lists.kamailio.org/pipermail/sr-users/2015-April/088031.html (1st post, see complete thread)
https://lists.kamailio.org/pipermail/sr-users/2019-January/104291.html (1st post, see complete thread)

Thanks!

**Comment by miconda** [comment]
This feature is now in master branch, see ka_* parameters:

  * https://www.kamailio.org/docs/modules/devel/modules/usrloc.html#usrloc.p.ka_mode

Still some work planned to be done (e.g., keepalive in db only mode, to be full alternative for nathelper keepalive -- but no roundtrip time to be stored in this mode), anyhow the RTT is already available and can be seen via rpc ul.dump command.

To give a bit more specific technical details, the keepalives are sent in stateless mode, storing the send time in the message and measuring the difference when reply is processed. A tm based solution would have been added quite some extra load to transactions management. The keepalive can be sent to all types of contact (nathelper does it only for UDP contacts).

Should there be any issues discovered, open new bug reports.
