### ISSUE TITLE
configure IMS with fedora 20

### ISSUE THREAD

**Issue by louivans** [kamailio/kamailio#223]
Hello,

I would like to do an IMS configuration to generate some calls with several smartphones. Currently, i had installed kamaillio 4.2 but i didn't found tutorials about how to configure IMS with Fedora 20, it is always for a debian distribution like this one:
http://www.kamailio.org/wiki/tutorials/ims/installation-howto 

Do have any advice about how to configure it with Fedora 20 ?
Thanks

Robert

**Comment by linuxmaniac** [comment]
Not a code issue. Please move discussion to the mailing list
sr-users@lists.sip-router.org
