### ISSUE TITLE
configure apns push notification in kamailio

### ISSUE THREAD

**Issue by masterhydra** [kamailio/kamailio#2232]
Hello,

I need to configure apns push notification in kamailio kindly help. I have a file push.php It is capable to push notification on ios device know i want to implement in kamailio when the user is offline then push notification fire kindly help in this.

Think Out of the Box

**Comment by miconda** [comment]
This is a question for sr-users@lists.kamailio.org, not being related to a bug in kamailio code, but how to use and configure kamailio.
