### ISSUE TITLE
Fedora 32/Rawhide build error: modules/sms: multiple definition of 'queued_msgs', 'use_contact', 'sms_report_type'

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#2236]
Similar to #2235.  After this one, I can try to collect them up rather than reporting an issue for each module--it's only that the build is killed, so I only see the first one that errors out.  I'll see what I can do about that.

```
make[2]: Entering directory '/builddir/build/BUILD/kamailio-5.3.2/src/modules/sms'
gcc -shared  -Wl,-O2 -Wl,-E   -pthread -rdynamic -ldl -Wl,-Bsymbolic-functions libsms_getsms.o libsms_putsms.o libsms_modem.o sms_funcs.o sms.o sms_report.o libsms_charset.o     -o sms.so
make[2]: Leaving directory '/builddir/build/BUILD/kamailio-5.3.2/src/modules/sms'
/usr/bin/ld: sms.o:(.bss+0x40): multiple definition of `queued_msgs'; sms_funcs.o:(.bss+0x11a0): first defined here
/usr/bin/ld: sms.o:(.bss+0x48): multiple definition of `use_contact'; sms_funcs.o:(.bss+0x11a8): first defined here
/usr/bin/ld: sms.o:(.bss+0x4c): multiple definition of `sms_report_type'; libsms_modem.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [../../Makefile.rules:191: sms.so] Error 1
make[1]: *** [Makefile:511: modules] Error 1
make: *** [Makefile:34: every-module] Error 2
```

**Comment by sergey-safarov** [comment]
I added codefresh CI builds for master branch on Fedora 32 and Fedora 33.
So you can look builds online
![CodeFresh CI](https://user-images.githubusercontent.com/2562241/75659971-ffc42980-5c7b-11ea-8417-d5410532a0d5.png)

**Comment by miconda** [comment]
Fixed for sms module.

@sergey-safarov - what is the link to the portal to see the build reports?

**Comment by sergey-safarov** [comment]
Build logs public available on link. Screenshot above.

If you want get full access, then need login via https://g.codefresh.io/login.
Login using your GitHub account.
Think need also assign your account into "kamailio team" on CodeFresh. Think Victor can help.

**Comment by sergey-safarov** [comment]
Need click stage icon and scroll up log
Like on this screenshot.
https://prnt.sc/ra8x18

**Comment by miconda** [comment]
Ahh, ok, was integrated and shown on github commit history of kamailio repo. I thought is an extern clone repo somewhere on codefresh.io.

**Comment by miconda** [comment]
Last build shows clean results.

**Comment by sergey-safarov** [comment]
I will configure `5.2` and `5.1` branches tracking to be sure that back-port fix all.

**Comment by henningw** [comment]
5.1 is end of life and will not receive the backports, you mean probably 5.3  and 5.2. :-)

**Comment by miconda** [comment]
Do not do it for stable branches, some patches do not apply clean, as I tried. We will backport as we can (I did most of 5.3 backports)

**Comment by sergey-safarov** [comment]
yes, @henningw i mean `5.2` and `5.3`
@miconda, ok I will simple disable master branch tracking on codefresh

**Comment by amessina** [comment]
Thank you all.
