### ISSUE TITLE
TLS write buffer too small

### ISSUE THREAD

**Issue by Natzy** [kamailio/kamailio#2240]
### Description

We're trying to connect the same subscriber with Kamailio for load testing. Sometimes it registers successfully but sometimes it throws the following error. 

### Troubleshooting

From my understanding by checking the source code, TLS_WR_MBUF_SZ is set as 65536 by default. This is the reason for "write buffer too small". Can someone help me with how to change that? 

#### Reproduction

I don't exactly know how to reproduce as some the clients pass and some fail. 

#### Log Messages

BUG: tls [tls_server.c:849]: tls_encode_f(): write buffer too small (65536/65536 bytes)
ERROR: websocket [ws_frame.c:300]: encode_and_send_ws_frame(): sending WebSocket frame
ERROR: websocket [ws_frame.c:800]: ws_frame_transmit(): sending message
NOTICE: <script>: WebSocket connection from a.b.c.d:1234 has closed
ERROR: registrar [reply.c:745]: reg_send_reply(): failed to send 200 OK
ERROR: <core> [core/tcp_main.c:3502]: handle_ser_child(): received CON_ERROR for 0x7f9472eec990 (id 100), refcnt 4, flags 0x4018
NOTICE: <script>: Error in saving location data
WARNING: sl [../../core/forward.h:173]: msg_send_buffer(): TCP/TLS connection for WebSocket could not be found
ERROR: sl [sl_funcs.c:362]: sl_reply_error(): stateless error reply used: I'm terribly sorry, server error occurred (1/SL)
WARNING: <core> [core/tcp_read.c:1716]: handle_io(): F_TCPCONN connection marked as bad: 0x7f9472eec990 id 100 refcnt 1

### Possible Solutions

Need to increase the default tls write buffer size from 65536. I think it is set as 
"#define TLS_WR_MBUF_SZ	65536"

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.0.8 (x86_64/linux) c35e69
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: c35e69 
compiled on 05:04:45 Nov 25 2019 with gcc 4.8.5

* **Operating System**:

Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.7.1908 (Core)

**Comment by henningw** [comment]
This is a compile time variable right now. You can try to change the define in the code and recompile the module.

src/modules/tls/tls_server.c
70:#define TLS_WR_MBUF_SZ       65536

**Comment by Natzy** [comment]
> This is a compile time variable right now. You can try to change the define in the code and recompile the module.
> 
> src/modules/tls/tls_server.c
> 70:#define TLS_WR_MBUF_SZ 65536

What is maximum value that can be set for this? And I'm assuming this is in bytes.

**Comment by henningw** [comment]
It is a unsigned char array, yes. Increasing it too much should only waste some memory, but I would not increase it to much as there might be some run time effects (like processing the data etc..).
I would try to double it, e.g. to 131072 (2^17) to see if its helps.

**Comment by Natzy** [comment]
> It is a unsigned char array, yes. Increasing it too much should only waste some memory, but I would not increase it to much as there might be some run time effects (like processing the data etc..).
> I would try to double it, e.g. to 131072 (2^17) to see if its helps.

Thank you for the reply.
