### ISSUE TITLE
need to create docker registry for rpm images

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2259]
As embedded [Codefresh registry is deprecated](https://codefresh.io/codefresh-news/deprecation-of-the-codefresh-private-registry/) need move all RPM build artifacts to other registry.
I suggest create `kamailio/kamailio-store` on Docker hub.

Could you create new docker registry for rpm artifacts build on codefresh.

**Comment by miconda** [comment]
@sergey-safarov - repo created:

  * https://hub.docker.com/repository/docker/kamailio/kamailio-store

If anything else needed, write here.
