### ISSUE TITLE
IMS server with a core network

### ISSUE THREAD

**Issue by arbalete** [kamailio/kamailio#227]
Hello,

I have installed Kamailio 4.2 and I would like to use it as IMS server but I don't have any ideas how to do this. I have a LTE core network which includes HSS ans PCRF. I saw on this page ( http://www.kamailio.org/w/2013/05/ims-kamailio/ ) that is apparently easy, just need to take the P-CSCF, S-CSCF and I-CSCF Kamailio and Diameter config files in the examples folder  and run kamailio  but I don't know how to use them and I didn't find any tutorials about it.

Could you help me please ?

Marc

**Comment by kamailio-sync** [comment]
Hi,

you should actually send such messages sr-users and not to the tracker, as
this is not a bug.

Please check the following links:
- http://www.kamailio.org/wiki/tutorials/ims/installation-howto
- https://www.youtube.com/watch?v=rbNP-PN6BOY

Thanks,
Carsten

2015-07-02 11:16 GMT+02:00 arbalete <notifications@github.com>:

> Hello,
>
> I have installed Kamailio 4.2 and I would like to use it as IMS server but
> I don't have any ideas how to do this. I have a LTE core network which
> includes HSS ans PCRF. I saw on this page (
> http://www.kamailio.org/w/2013/05/ims-kamailio/ ) that is apparently
> easy, just need to take the P-CSCF, S-CSCF and I-CSCF Kamailio and Diameter
> config files in the examples folder and run kamailio but I don't know how
> to use them and I didn't find any tutorials about it.
>
> Could you help me please ?
>
> Marc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamailio/kamailio/issues/227>.
>
> _______________________________________________
> sr-dev mailing list
> sr-dev@lists.sip-router.org
> http://lists.sip-router.org/cgi-bin/mailman/listinfo/sr-dev
>
>


-- 
Carsten Bock
CEO (Geschäftsführer)

ng-voice GmbH
Schomburgstr. 80
D-22767 Hamburg / Germany

http://www.ng-voice.com
mailto:carsten@ng-voice.com

Office +49 40 5247593-0
Fax +49 40 5247593-99

Sitz der Gesellschaft: Hamburg
Registergericht: Amtsgericht Hamburg, HRB 120189
Geschäftsführer: Carsten Bock
Ust-ID: DE279344284

Hier finden Sie unsere handelsrechtlichen Pflichtangaben:
http://www.ng-voice.com/imprint/

**Comment by ngvoice** [comment]
Should go to sr-users instead.

**Comment by arbalete** [comment]
ok thank you I will see the link you have gived

**Comment by arbalete** [comment]
so I tried first to follow the tutorial video but when I tried to install the ngcp-mediaproxy-ng and openimscore-fhoss packages. 
I also tried the second tutorial but i Have some difficulties whit this part:
 For I-CSCF you will also need a database structure:

mysql -uroot -p < icscf.sql

When I execute this command line, it is say that icscf.sql is not found, what does this command do exactly ?
