### ISSUE TITLE
Ability to reload location attributes at runtime

### ISSUE THREAD

**Issue by zeusca** [kamailio/kamailio#2299]
### Description

Looking for a mechanism to reload Location attributes at runtime.

Having both registered and permanent Contacts under AoR, with Attributes from `usrloc` to be used for various routing decisions. 

This is about attributes of permanent Contacts. Registered ones have `xavp_contact` of `usrloc` to store attributes during registration.
  
**Problem:** 

Only way to make it work is: 
1. adding a permanent Contact using `rpc ul.add`
2. assigning attributes in DB `location_attr` per RUID (can't find an rpc function for attributes)
3. restart Kamailio

modparam("usrloc", "db_mode", 1)
modparam("usrloc", "db_load", 1)

This however is far from ideal, having to restart Kamailio for every change in attributes of a Contact.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.3.3 (x86_64/linux) 44ccb9

* **Operating System**:

```
(paste your output here)
```

**Comment by henningw** [comment]
Hello, have you tried this function already:
https://kamailio.org/docs/modules/5.3.x/modules/registrar.html#registrar.f.reg_fetch_contacts

**Comment by zeusca** [comment]
Hi @henningw ,

I certainly do use `reg_fetch_contacts` to fetch all the Contacts of a caller/callee, it provides access to all the `location` parameters of a Contact (aor, addr, path, received, e.t.c) and that works fine. 

Here's the general Lookup flow I use:
1. reg_fetch_contacts("location"); exposes Contact's profile in $ulc pseudo-variable
2. registered("location"); exposes extra attributes from `location_attr` in $xavp(ulattrs)

The name of XAVP storing the attributes per Contact
modparam("tm|usrloc", "xavp_contact", "ulattrs")

My quarrel is with the extra attributes. I can't find a way to reload/refresh them at runtime. I have to alter the records in DB table `location_attrs` then restart Kamailio.

Having `db_load=1` loads all Contacts & Attributes on restart, so I thought - may be the function that does that on restart can do the same thing on-demand in some rpc?

Thanks.

**Comment by henningw** [comment]
I see, does it work in db_mode = 3?

**Comment by zeusca** [comment]
> I see, does it work in db_mode = 3?

Yes Sir it does work! Somehow it didn't cross my mind...

Does it mean that db_mode=3 is my only choice? Clearly a `performance killer`, besides the idea was to later use DMQ to replicate `usrloc` & `ulattrs` across nodes 😢

**Comment by henningw** [comment]
Well, the design of the usrloc db_mode 2 is that the memory is used as write-back cache. So it is not expected to be changed from database. If you are just looking for some variables from a DB, maybe just using sqlops, htable or avpdbops (just to name a few possibilities) are available.

**Comment by zeusca** [comment]
I see. Been using `avpops` for preferences and alike till now. Surely can be done with sqlops. But it's all DB-driven.

Lately, I thought I could unify everything around usrloc, including attributes. In the end - isn't location attributes designed specifically for this purpose? If there was a rpc to add/delete location attributes - I'd gladly use it instead of relying on DB, but it seems like there is no such?

**Comment by henningw** [comment]
If you want to go the dmq route - htable can be synchronized with it as well. And it provides setting functions over RPC already. And with usrloc_dmq you could go without DB as well.
About a RCP to add usrloc attributes, it could be also added, e.g. with a pull request.

**Comment by miconda** [comment]
Closing it, long time without any activity. A PR can be made if anyone wants to implement it.
