### ISSUE TITLE
rtpengine: Unknown flag encountered: 'auto-bridge'

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2301]
### Description
According Kamailio rtpengine module supported auto-bridge flag. I added this flag in Kamailio config and get rtpengine warning
```
Unknown flag encountered: 'auto-bridge'
```
Then I make search in rtpengine commit history and cannot commits with auto-bridge string.
Think need remove `'auto-bridge` flag from Kamailio rtpengine module.

**Comment by henningw** [comment]
The flag is not documented at https://github.com/sipwise/rtpengine either.
Maybe the kamailio docs are outdated. The commit that introduced this parameter is 7c1b8e768d from 2014.

**Comment by ngvoice** [comment]
The docs state clearly:
"auto-bridge - this flag an alternative to the “internal” and “external” flags in order to do automatic bridging between IPv4 on the "internal network" and IPv6 on the "external network". Instead of explicitly instructing the RTP proxy to select a particular address family, the distinction is done by the given IP in the SDP body by the RTP proxy itself. **Not supported by Sipwise rtpengine**."

**Comment by ngvoice** [comment]
I've added the "auto-bridge" feature some years (!!) ago and when the RTPEngine protocol was updated, this feature was not added as well (and by now, I would also remove it). Likely, we should simply update the docs.
https://www.kamailio.org/docs/modules/devel/modules/rtpengine.html#rtpengine.f.rtpengine_offer

**Comment by sergey-safarov** [comment]
As mentioned in rtpengine module doc
> RFC6157 which suggest ICE for Dual-Stack implementations

So, think we can use `ICE` instead of `auto-bridge`

**Comment by miconda** [comment]
ICE requires client side support. And the ipv4-to-ipv6 bridge has anyhow the purpose to cover the cases when one device is on ipv4-only and the other in ipv6-only, so they cannot communicate directly anyhow, not matter they would support the other ipvX version.

As @ngvoice mentioned, should be removed, being inherited from rtpproxy module and not something available in rtpengine.

**Comment by henningw** [comment]
done
