### ISSUE TITLE
sr_kemi_modules_add(sr_kemi_kazoo_exports)

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#2302]
### Description

// kamailio 5.3.3
// kazoo.c

static sr_kemi_t sr_kemi_kazoo_exports[] = 

int mod_register(char *path, int *dlflags, void *p1, void *p2)
{
	if(kz_tr_init_buffers()<0)
	{
		LM_ERR("failed to initialize transformations buffers\n");
		return -1;
	}

	//	
	sr_kemi_modules_add(sr_kemi_kazoo_exports);

	return register_trans_mod(path, mod_trans);
}

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

Debian9

```
(paste your output here)
```

**Comment by miconda** [comment]
This is an incomplete report, no proper details are offered. If you wanted to report that kazoo module doesn't export it functions to kemi, then indeed there are still a group of modules not having those exports (e.g, ims_*). It is a matter of developers availability and priorities. You can make a pull request and it will be merged if all ok.
