### ISSUE TITLE
PID file permissions

### ISSUE THREAD

**Issue by arsenx** [kamailio/kamailio#231]
ENV: Debian 8
So on most Linux systems the /var/run folder is a tmpfs and after which clears after each reboot
As I try to start up kamailio after a reboot through kamctl I get the following error.
"ERROR: PID file /var/run/kamailio.pid does not exist -- Kamailio start failed"
Because kamailio does not have the permission to write to the /var/run folder as the kamailio user.
Would it be possible to add in the "kamctl" code a section where the SPECIFIED PID LOCATION (/var/run/kamailio) is checked and if it does not exist create it as the root user and chown it to the SPECIFIED USER (kamailio)? The way I have patched it for now is to create a init script that creates a /var/run/kamailio folder and chmods it to kamailio:kamailio

Thanks everyone!

**Comment by arsenx** [comment]
Never mind, the issue was being caused by the newly updated location of the fifo file

**Comment by linuxmaniac** [comment]
7cf6368591b630ddf19b32e1218fdbc10490442c should fix that

/var/run/kamailio is created by /etc/init.d/kamailio script

**Comment by miconda** [comment]
Re-open if there is still some issue related to the topic.

**Comment by CristianAlvear** [comment]
Hi, I have this problem with version 4.4.2 that can help me solve this problem please
INFO: Starting Kamailio : 

ERROR: PID file /var/run/kamailio.pid does not exist -- Kamailio start failed

**Comment by GhanshyamVariya** [comment]
I have Kamailio v4.4.x
but 

[root@ubuntu sbin]# kamctl start
WARNING: no control engine found - tried 'RPCFIFO'

INFO: Starting Kamailio : 

ERROR: PID file /var/run/kamailio.pid does not exist -- Kamailio start failed
You have new mail in /var/mail/root
[root@ubuntu sbin]#



Any solution for this ??
Please ....

**Comment by GhanshyamVariya** [comment]
and now i got error in log using this command ... also 
kamailio -M 8 -E -e -dd

error like : 
[root@ubuntu log]# kamailio -M 8 -E -e -dd
 0(14461) INFO: <core> [main.c:1930]: main(): private (per process) memory: 8388608 bytes
loading modules under config path: /usr/local/kamailio-4.4/lib64/kamailio/modules/
 0(14461) ERROR: <core> [core/sr_module.c:431]: version_control(): module version mismatch for /usr/local/kamailio-4.4/lib64/kamailio/modules/mi_fifo.so; core: kamailio 5.1.0-dev1 (x86_64/linux); module: kamailio 4.4.5 (x86_64/linux)
You have new mail in /var/mail/root

**Comment by miconda** [comment]
This issue is closed and your questions are not related to its topic. For questions about using kamailio, use the mailing list sr-users@lists.sip-router.org, the bug tracker is used only for reporting bugs and tracking requests of new features.

**Comment by GhanshyamVariya** [comment]
Okay Thank you :)

**Comment by am2f5q** [comment]
I have the same issue like @arsenx: "ERROR: No PID file found (/var/run/kamailio.pid)! Kamailio probably not running", regardless of chmoding or chowning. The error hint points to the /var/run/kamailio.pid but on my system (Debian Jessie 8.9) the location of the pid-file is /var/run/kamailio/kamailio.pid. Is this ok? Every time when I try to restart or stop kamailio (via kamctl), I get the error. I've tested with kamailio 5.0, 4.4 and 4.2 releases and nothing changes. The init-script is already patched (see the post from @linuxmaniac).

**Comment by miconda** [comment]
This issue is closed, do not add new comments to it. This looks like a config issue inside kamctlrc for the path to the pid file. For issues about using or configuring kamailio, use sr-users@lists.kamailio.org mailing list,
