### ISSUE TITLE
No reply on dispatcher ping with asterisk 16.10.0 

### ISSUE THREAD

**Issue by MazueraAlvaro** [kamailio/kamailio#2320]
Hi, I am implementing a sip proxy with kamailio and multiple asterisk servers, when kamailio send the OPTIONS asterisk don´t reply, and i see with sngrep tool that in the asterisk servers the SIP message OPTIONS arrives, but has no reply from asterisk, and enabling the sip debug nothing occurs, but the OPTIONS message between asterisk servers is all ok.

On kamailio logs get:

dispatcher [dispatch.c:3159]: ds_options_callback(): OPTIONS-Request was finished with code 408 (to sip:172.20.20.4, group 1)

The SIP traffic arrives the asterisk servers, but asterisk don´t reply the message, (I know this because i can see it with the sngrep tool, because the sip debug on asterisk doesn't show it) . However when the message is from another asterisk all is ok.

Sip kamailio OPTIONS message on asterisk 
```
OPTIONS sip:172.20.20.3 SIP/2.0
Via: SIP/2.0/UDP 172.16.10.195;branch=z9hG4bKef0b.b1358
To: <sip:172.20.20.3>
From: <sip:kamailio@172.20.20.6>;tag=3393f0703fb0ccaca7
09ff37de39f5-b7044ca5
CSeq: 10 OPTIONS
Call-ID: 791b966c5d00cd60-24281@127.0.0.1
Max-Forwards: 70
Content-Length: 0
User-Agent: kamailio (5.3.4 (x86_64/linux))
```

### Additional Information

```
version: kamailio 5.3.4 (x86_64/linux) 117ff9
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 117ff9
compiled on 13:37:37 May  6 2020 with gcc 8.2.1
```

**Comment by goharahmed** [comment]
Just to be sure can you check these.
1 - No iptables on the asterisk instance.
2 - The Asterisk instance listening on that interface confirm port as well.(172.20.20.4 )

**Comment by MazueraAlvaro** [comment]
Hi, 
1. The asterisk instance has no firewall problems, because i can register a softphone connecting directly to it.

2. Yes, I had a mistake pasting the incorrect log, but is the same, because are two asterisk servers, one on x.x.x.3 and other on x.x.x.4, with both occurs the same.

**Comment by MazueraAlvaro** [comment]
Aditionally, I can see the SIP message from kamailio with [sngrep](https://github.com/irontec/sngrep) tool on the asterisk server, but not on the asterisk sip debug.

**Comment by miconda** [comment]
Sniffing tools use kernel hooks before the firewall or other system limits (e.g., imposed by selinux, conntrack, ...), so you can see the traffic on the network but it doesn't get to the application. You have to review those settings.

Because Kamailio is sending the keepalive, this is clearly not a bug in Kamailio code. If you need to discuss further to troubleshoot, then use the mailing list sr-users@lists.kamailio.org. This issue tracker is for bugs in Kamailio code and send notifications to sr-dev, which is not the appropriate place to discuss how to use kamailio.
