### ISSUE TITLE
kamdbctl create Issue

### ISSUE THREAD

**Issue by rodrigocuadra** [kamailio/kamailio#2328]
### Description

```
When I am installed Kamailio and send to create the database with the command:
kamdbctl create
It gives me an error
```

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[root@localhost ~]# kamailio -version
version: kamailio 5.3.4 (x86_64/linux) 117ff9
```

* **Operating System**:

```
Centos 7.8
```

```
MySQL password for root:
INFO: test server charset
INFO: creating database kamailio ...
INFO: granting privileges to database kamailio ...
INFO: creating standard tables into kamailio ...
INFO: Core Kamailio tables succesfully created.
Install presence related tables? (y/n): y
INFO: creating presence tables into kamailio ...
INFO: Presence tables succesfully created.
Install tables for imc cpl siptrace domainpolicy carrierroute
                drouting userblacklist htable purple uac pipelimit mtree sca mohqueue
                rtpproxy rtpengine secfilter? (y/n): y
INFO: creating extra tables into kamailio ...
ERROR 1067 (42000) at line 1: Invalid default value for 'action'
ERROR: Creating extra tables failed at secfilter!
```

**Comment by henningw** [comment]
Have a look to this commits:
- b0f1486f8a656922aac02020c9e3141639f2ecb9
- 59c49af039f468466b0d853a4ceab8fe7f566215
They are already backported in 5.3 branch, but came to late for 5.3.4 release.

**Comment by sudo-riyad** [comment]
Hi , I am finding this similar issue while creating database in version 5.3.4

**Comment by rodrigocuadra** [comment]
Just do that
Go to path where mysql scrip is there, in my case is:
cd /usr/share/kamailio/mysql/
rm -rf secfilter-create.sql
wget
https://raw.githubusercontent.com/kamailio/kamailio/master/utils/kamctl/mysql/secfilter-create.sql

and then, try to create againg.

Best Regards,

Rodrigo Cuadra
