### ISSUE TITLE
RPC Command tm.clean

### ISSUE THREAD

**Issue by Maratk1n** [kamailio/kamailio#2329]
Hello.

I have a philosophical question about [tm.clean](https://kamailio.org/docs/modules/5.1.x/modules/tm.html#tm.rpc.clean) command.

Unfortunately, I don’t understand what this command is for, because in my view, expired transactions are automatically deleted.

This is all I could find:

> pc command tm.clean to clean long time expired transactions (for troubleshooting purposes) [[1]](https://www.kamailio.org/wiki/features/new-in-5.1.x)

So, can you give an example when a transaction can remain in memory?

Thanks!

**Comment by miconda** [comment]
Use sr-users@lists.kamailio.org mailing lists for discussions about using kamailio and purpose of some functions/control commands. The issue tracker is for reporting bugs in the C code.
