### ISSUE TITLE
Siptrace Module is ignoring force_send_sock parameter

### ISSUE THREAD

**Issue by iliesh** [kamailio/kamailio#2330]
### Description

Trying to duplicate TLS SIP messages to the remote host directly from Kamailio by using Siptrace Module. Those are the parameters used by the module:

```
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "force_send_sock", "sip:192.168.1.1:5000")
modparam("siptrace", "trace_mode", 0)
modparam("siptrace", "trace_flag", 22)
modparam("siptrace", "duplicate_uri", "sip:192.168.1.100")
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "hep_mode_on", 0)
modparam("siptrace", "xheaders_write", 1)
modparam("siptrace", "trace_local_ip", "MY_EXTERNAL_IP_ADDR")
modparam("siptrace", "trace_sl_acks", 0)
```
But seems that Kamailio is ignoring the parameter "force_send_sock" and keep sending from the first listen interface from the configuration file.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.7 (x86_64/linux) 9ea54f
```

* **Operating System**:

```
CentsOS 7 3.10.0-1127.el7.x86_64
```

**Comment by miconda** [comment]
In 5.2 the socket could be forced only for hep.

The master branch has already this feature extended for sip mirroring.
