### ISSUE TITLE
KSR.is_MESSAGE()  Not implemented

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#2331]
### Description

KSR.is_MESSAGE()  Not implemented.
kamailio v5.3.4

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Thanks, I pushed the implementation in master branch, to be backported soon.

There is also the alternative of using KSR.is_method_in("m")
