### ISSUE TITLE
kamailio packages for Ubuntu 20.04

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#2338]
It would be great if on deb.kamailio.org new packages for the new Ubuntu 20.04 could be added.

**Comment by linuxmaniac** [comment]
precise needs to go away to left room to focal

from https://wiki.ubuntu.com/Releases:
Ubuntu 12.04.5 LTS | Precise Pangolin EOL was April 28, 2017

**Comment by henningw** [comment]
Thanks for looking into it. Fine for me, precise is pretty old and already long time EOL.

**Comment by miconda** [comment]
Fine to remove it from building debs ourselves on deb.kamailio.org, but maybe we can still keep the specs folder in `pkg/kamailio/deb/`, in case someone wants to build by themselves.

Maybe also worth sending a notification on users mailing list to make everyone aware and eventually see if someone is still using that repo.

**Comment by henningw** [comment]
Is this still open? I just checked on deb.kamailio.org, seems to be not there yet.

**Comment by linuxmaniac** [comment]
Yes, still in my TODO list

**Comment by linuxmaniac** [comment]
* Removed precise from 5.2, 5.3, 5.4 and master builds. Repositories are still there but I removed the link from the list [0]
* Disabled build jobs for no longer supported versions 5.0, 5.1
* adding focal support work started

[0] deb.kamailio.org

**Comment by linuxmaniac** [comment]
* wheezy is EOF since 31st May 2018 [0]
* removed wheezy from 5.2, 5.3, 5.4 and master builds. Repositories are still there but I removed the link from the list [0]

[0] https://wiki.debian.org/LTS

**Comment by linuxmaniac** [comment]
FTR, focal for master successfully built 
https://kamailio.sipwise.com/job/kamailiodev-nightly-repos/architecture=amd64,distribution=focal,label=master/

Be aware, Ubuntu doesn't support i386 since 19.10
