### ISSUE TITLE
topos and 183 replies without Contact header

### ISSUE THREAD

**Issue by flantel** [kamailio/kamailio#2344]
Further to the changes made in https://github.com/kamailio/kamailio/issues/1720 I am opening a new ticket regarding https://github.com/kamailio/kamailio/issues/1720#issuecomment-638158699 

It is my understanding that 1xx replies do not require a Contact header, but commit https://github.com/kamailio/kamailio/commit/3b586d554740ae578283024c1508e91b6ad886a2 specifically excludes 183 replies from passing without a Contact header.

This is causing us some issues and I am wondering why 183 is set to require the Contact header.

Thanks

**Comment by miconda** [comment]
Should be fixed by 785326cdfbee849a8436e7c07003ff0539d259cd . It will be backported till the next point release, maybe you can test meanwhile and report if works ok.
