### ISSUE TITLE
PDB return wrong values

### ISSUE THREAD

**Issue by Earn330** [kamailio/kamailio#2345]
### Description

After installing the latest update of Kamailio 5.3 and Kamailio 5.2 the pdb module stops working

#### Reproduction

After creating a mmap file and query it with pdbt you get the correct prefix. A query with Kamailio results in a wrong prefix. It seems like pdb.c returns pointer positions instead of pointer values

### Possible Solutions

Reverting commit 86ebb4e of #2298

### Additional Information

```
version: kamailio 5.3.4 (x86_64/linux) a35a2f-dirty
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: a35a2f -dirty
compiled with gcc 4.9.2
```

* **Operating System**:

```
Debian GNU/Linux 8
Linux voip-lab-proxy02 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by henningw** [comment]
related to #2298

**Comment by miconda** [comment]
@Earn330 - can you try with the patch referenced above?

**Comment by Earn330** [comment]
Hi Daniel,
your patch is working. The results of a pdb_query are as expected. 
Many thanks for this.

BR
Björn

**Comment by miconda** [comment]
@Earn330 - thanks for testing, I will backport.
