### ISSUE TITLE
acc: skip cdr generation for certain calls

### ISSUE THREAD

**Issue by cruzccl** [kamailio/kamailio#2348]
### Description

I haven't found a way to skip CDR generation per call once [cdr_enable modparam](http://kamailio.org/docs/modules/devel/modules/acc.html#acc.p.cdr_enable) is enabled.

### Expected behavior

I have implemented via irontec/kamailio@38964a31d6c0158b7c9bb3abb4e9eb72aa8cd960 adding a new modparam with the dlg_var name that will prevent CDR generation for calls with that dlg_var set.

#### Actual observed behavior

Once CDR generation is enabled with [cdr_enable modparam](http://kamailio.org/docs/modules/devel/modules/acc.html#acc.p.cdr_enable) all calls generate CDR.

### Additional Information

I can make a PR adapting that patch and documenting new modparam, as long as there is no way of achieving it that I have missed and if you find it useful.

Thank you and regards,

**Comment by henningw** [comment]
Hello, thanks for the request. This sounds useful, please create a Kamailio github pull request, also include the documentation (doc XML) as mentioned.
