### ISSUE TITLE
Help for register kazoo to kamailio registrar server

### ISSUE THREAD

**Issue by mohammaddehnavi** [kamailio/kamailio#2378]
### Description

I integrate a Kamailio and asterisk with together(Kamailio fo registrar server) as a sip trunk and  I have a kazoo server that doesn't send a register message to Kamailio and I want to register this kazoo manually to my Kamailio location and asterisk sipregs with fixed values and send an incoming call to kazoo from another hosted PBXs.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.0.8 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 6.3.0
```

* **Operating System**:

```
Linux trunk2-sbc 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Comment by henningw** [comment]
Hello, this tracker is for bugs and feature requests, not for general user support. Please contact our users list for this kind of questions at: Kamailio (SER) - Users Mailing List <sr-users@lists.kamailio.org> You might need to subscribe before, if you not already on the list.
