### ISSUE TITLE
Introduce a permanent usrloc entry with kamctl

### ISSUE THREAD

**Issue by mohammaddehnavi** [kamailio/kamailio#2379]
### Description

Introduce a permanent usrloc entry with kamctl not working, but introduce a temporary usrloc entry with  expires date is ok for me. 

#### Debugging Data
`kamctl ul add +982191079726 sip:+982191079726@172.22.132.230:5060`

#### Log Messages
{
  "jsonrpc":  "2.0",
  "error":  {
    "code": 500,
    "message":  "Not enough parameters or wrong format"
  },
  "id": 107809
}

When I try with introduce a temporary usrloc entry every thing is ok. 

`kamctl ul add +982191079723 sip:+982191079723@172.22.132.235 2020-07-30 08:51:40`

```
{
  "jsonrpc":  "2.0",
  "result": {
  },
  "id": 107852
}
```

### Additional Information

```
version: kamailio 5.0.8 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 6.3.0

```

* **Operating System**:

```
Linux trunk2-sbc 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

```

**Comment by henningw** [comment]
Hello, you can use a dot "." for parameters that should be not set. 
http://sip-router.1086192.n5.nabble.com/usrloc-rpc-command-ul-add-td165240.html 
Please use the sr-users list for discussion of usability problems, the tracker is for tracking issues or feature requests in the code.

**Comment by mohammaddehnavi** [comment]
@henningw 
Hello dear,
Thank you very much.
