### ISSUE TITLE
Digest authentication on a DB side

### ISSUE THREAD

**Issue by andr-04** [kamailio/kamailio#2384]
Hello. I'm new with Kamailio. I have a stored function in a database which accepts `username`, `realm`, `ha2`, `nonce` and `digest_response`. Basing on this and the raw password stored in a database, it calculates inside `ha1` and `digest_reference` to compare with `digest_response` and returns the verdict: passed or not.

This approach gives a high-security level as a benefit. How it can be used with Kamailio? Thanks.

**Comment by miconda** [comment]
The issue tracker is used for bugs in the code or requests for new features. To discuss about how to use Kamailio, you have to join the email list sr-users@lists.kamailio.org. Check sqlops module and if it is not what you look for, then start the discussion on the referred mailing list.
