### ISSUE TITLE
Kamailio 5.1.10 crash in EVP_DecryptUpdate()

### ISSUE THREAD

**Issue by SipSeb** [kamailio/kamailio#2394]
### Description

We replaced a legacy wheezy system running Kamailio 5.1.4 with a Debian Buster system running Kamailio 5.1.10. (We currently can't update to 5.3.x because the configuration file is shared across multiple machines. 🙄 ) This new system has crashed upon us even before getting real traffic (except maybe some random scanners driving by), and even more frequently after sending traffic to it. The core dump looks the same with or without traffic.

#### Debugging Data

We have collected the gdb output as requested.

[kamailio_crash1.log](https://github.com/kamailio/kamailio/files/4884682/kamailio_crash1.log)

#### Log Messages

```
Jul  5 22:20:18 sip-tcploadbalancer01 /usr/sbin/kamailio[15531]: ERROR: tls [tls_util.h:42]: tls_err_ret(): TLS read:error:24067044:random number generator:rand_pool_add:internal error
Jul  5 22:20:18 sip-tcploadbalancer01 /usr/sbin/kamailio[15531]: ERROR: <core> [core/tcp_read.c:1505]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f31ec06a3e8 r: 0x7f31ec06a468 (-1)
Jul  5 22:20:19 sip-tcploadbalancer01 /usr/sbin/kamailio[15534]: CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 76
Jul  5 22:20:21 sip-tcploadbalancer01 /usr/sbin/kamailio[15479]: ALERT: <core> [main.c:744]: handle_sigs(): child process 15530 exited by a signal 11
Jul  5 22:20:21 sip-tcploadbalancer01 /usr/sbin/kamailio[15479]: ALERT: <core> [main.c:747]: handle_sigs(): core was generated
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.1.10 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0
```

* **Operating System**:

```
Linux hostname 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```

**Comment by miconda** [comment]
If tls module is compiled against libssl 1.1, the options are:

  * downgrade OS back to a version shipping libssl 1.0 
  * install somehow libssl 1.0 and compile kamailio against it
  * upgrade kamailio to use at least latest kamailio 5.2.x


The libssl did major internal changes in libssl 1.1, older kamailio versions were released earlier than libssl 1.1 became shipped by stable linux distros, so they do not support libssl 1.1 properly. Kamailio 5.1 is out of maintenance, but you can try to backport from 5.2, however there were a lot of changes related to support of libssl 1.1 that I do not think it worth doing it compared with just upgrading kamailio config for a newer version.

**Comment by miconda** [comment]
To have it clear: Kamailio version less than 5.2.7 (or a few minor release before) is incompatible with libssl 1.1.

I am waiting to confirm tls.so is linked against libssl 1.1 before closing this one -- you can do `ldd tls.so` to see it.

**Comment by SipSeb** [comment]
```
root@sip-tcploadbalancer02.live.sipgate.net:/usr/lib/x86_64-linux-gnu/kamailio# ldd modules/tls.so
	linux-vdso.so.1 (0x00007ffef73a7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7cc66c6000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f7cc6634000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7cc6613000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7cc6452000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7cc6760000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f7cc6169000)
```

Okay, then this might be the first step to upgrading our Kamailio loadbalancers.

**Comment by henningw** [comment]
Confirmed, close this one.
