### ISSUE TITLE
Broken kamailio repo

### ISSUE THREAD

**Issue by jbartak** [kamailio/kamailio#2407]
### Description
Centos RPM repo is generating Kamailio 5.0.8 packages that can't be installed
Looks like same issue as: #1604 

### Troubleshooting
By using the repo
https://download.opensuse.org/repositories/home:/kamailio:/v5.0.x-rpms/CentOS_7/home:kamailio:v5.0.x-rpms.repo
when trying to install Kamailio 5.0.8, yum returns this error:
```
Downloading packages:
kamailio-5.0.8-2.el7.centos.x8 FAILED                                          =================================================          ] 2.0 MB/s | 4.3 MB  00:00:00 ETA 
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-5.0.8-2.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=Kamailio clean metadata
Trying other mirror.


Error downloading packages:
  kamailio-5.0.8-2.el7.centos.x86_64: [Errno 256] No more mirrors to try.
```

### Additional Information
CentOS Linux release 7.8.2003 (Core)

**Comment by kamailio-sync** [comment]
RPM rebuild triggered.
You can check after hour
