### ISSUE TITLE
could not find module <http_client> in </usr/lib/x86_64-linux-gnu/kamailio/modules

### ISSUE THREAD

**Issue by amen160** [kamailio/kamailio#2408]
Please help me. I get error when loadmodule "http_client.so"
ERROR: <core> [core/sr_module.c:486]: load_module(): could not find module <http_client> in </usr/lib/x86_64-linux-gnu/kamailio/modules>

**Comment by sergey-safarov** [comment]
I assume, used Debian and Kamailio installed from packages?

**Comment by miconda** [comment]
This is an "how-to-use" type of question, you have address it to sr-users@lists.kamailio.org mailing list. This tracker is for bugs in the code or discussing requests for new features.

As a quick hint, if you install from packages, the module is in an extra package, if you install from sources, you have to add the module to include_modules make variable (see wiki install guide). For further discussions, email to sr-users as advised above.
