### ISSUE TITLE
HEPv3 packets stop tracing if Homer server goes down briefly

### ISSUE THREAD

**Issue by lukeescude** [kamailio/kamailio#2411]
### Description

We send all traffic to a Homer (HEPv3) server for monitoring and SIP diagnostics, using the siptrace module. Config below:

modparam("siptrace", "duplicate_uri","sip:IP_ADDR:9060")
modparam("siptrace", "hep_mode_on",1)
modparam("siptrace", "trace_to_database",0)
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "trace_flag",22)
modparam("siptrace", "trace_mode", 1)

It works just fine of course, but the moment the Homer server goes down or needs to be rebooted, Kamailio doesn't seem to want to "reconnect" to the HEP server - It just stops reporting packets altogether. Kamailio requires a restart.

#### Reproduction

Set up a Homer server with kamailio tracing HEP packets to it. Then, restart Homer. You will no longer receive packets, until the next time you restart Kamailio. 

We're using CentOS 7 x64 on all servers. There is no log information I can provide to assist with this.

Thanks!

**Comment by lukeescude** [comment]
Additionally I have confirmed this happens in Kamailio 4, as well as the newest production version 5.3

**Comment by lukeescude** [comment]
Forgot to mention:

kamcmd siptrace.status off
kamcmd siptrace.status on

Does not fix the issue. Restarting kamailio is necessary.

**Comment by miconda** [comment]
What is the kamailio version (kamailio -v output)?

**Comment by lukeescude** [comment]
version: kamailio 5.3.5 (x86_64/linux) 9e70e8
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 9e70e8 
compiled on 14:35:46 Jun 22 2020 with gcc 4.8.5

**Comment by lukeescude** [comment]
Well, it appears as though data is coming through again... It just takes a while it seems.

So, there may not be a  bug here.

**Comment by miconda** [comment]
I looked at the code and does not seem to be anything that could prevent sending the hep packets, because they are sent over UDP, there is no connection at any time and by that kamailio is not aware when homer server is down.

**Comment by miconda** [comment]
I am closing this one based on code investigation. Should something new be founds that indicates a possible bug in the code, then reopen.
