### ISSUE TITLE
kamailio not receive bye requests

### ISSUE THREAD

**Issue by amen160** [kamailio/kamailio#2417]
I use ec2 ubuntu on aws. But kamailio not receive bye requests.
But when I install Kmailio in vultr is OK.
can you help me? 💯

**Comment by linuxmaniac** [comment]
Hello, this tracker is for bugs and feature requests, not for general user support. Please contact our users list for this kind of questions at: Kamailio (SER) - Users Mailing List sr-users@lists.kamailio.org You might need to subscribe before, if you not already on the list.
