### ISSUE TITLE
How to kamailio connect to Sip trunk with credentials (username & password)

### ISSUE THREAD

**Issue by amen160** [kamailio/kamailio#2418]
Please help me.
How to kamailio connect to Sip trunk with credentials (username & password)

**Comment by linuxmaniac** [comment]
Hello, this tracker is for bugs and feature requests, not for general user support. Please contact our users list for this kind of questions at: Kamailio (SER) - Users Mailing List sr-users@lists.kamailio.org You might need to subscribe before, if you not already on the list.
