### ISSUE TITLE
Redundancy of Progress Call using Kamailio

### ISSUE THREAD

**Issue by amitpaltech** [kamailio/kamailio#2423]
Hello Team,

I need one info, Can Kamailio recover ringing call in redundancy ?. Problem with Ringing call as calls continue to ring after floating ip shifting.

Can we achieve it by Kamailio or not ?

Thanks in advance.

**Comment by miconda** [comment]
This is the tracker used for reporting bugs in the code of kamailio or tracking the proposals for new features.

Write an email to sr-users@lists.kamailio.org if you have questions about how to use kamailio and what you can do with it.
