### ISSUE TITLE
Problem Storing USRLOC Additional Attributes

### ISSUE THREAD

**Issue by mule979** [kamailio/kamailio#243]
As detected on [SR-Users] July 2015 Thread 'Problem Storing USRLOC Additional Attributes' (see it for details) [http://lists.sip-router.org/pipermail/sr-users/2015-July/088961.html]

it seems that when xavp structure (xavp_contact) carring USRLOC Additional Attributes is stored in memory, just first and last elements are inserted.

**Comment by miconda** [comment]
I just pushed a patch to master (4efb386ebf47fc89446f57f2faf6f5cddfb7bff7) and backported to 4.3 (f5d11d18f9d483c5fc731ff36f30fbbe1204f9ff) branch. Let us know if it fixes the issue.

**Comment by mule979** [comment]
Sorry for late reply (I missed your commit and then last week I was traveling):
I tested on 4.2 and 4.3 and I can confirm that your fix solved the problem.
From my point of view You can close this issue.

Thank You very much

Luca

**Comment by miconda** [comment]
Thanks for reporting back the results.
