### ISSUE TITLE
Redirect to freeswitch after answer kamailio UA.

### ISSUE THREAD

**Issue by amitpaltech** [kamailio/kamailio#2434]
Hello,
I am newbie to Kamailio, after a lot searching kamailio doc , I am unable to find change in configuration file (kamailio.cfg).  Which  redirect the call from kamailio to freeswitch if the call is answered in kamailio. 

Thanks.

**Comment by miconda** [comment]
The issue tracker here is to report bugs in Kamailio code or propose/discuss new features.

Questions about how to use Kamailio have to be addressed to sr-users@lists.kamailio.org mailing list.
