### ISSUE TITLE
sqlops sql_query() function result value has not been documented in README

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#2454]
README should tell that:

- 1 is returned when query succeeds and result set is not empty
- 2 is returned when query succeeds but result set is not empty
- 3 is returned when result set is not empty, but result param was not given
- -1 is returned in case of error

**Comment by miconda** [comment]
@juha-h - just add this information to the xml docs of the sqlops module. Many functions do not document return codes, it would be good to be done for all of them, so whenever a developer finds such information missing and sorts out that in the code, no need to open issues, just update the docs.

**Comment by juha-h** [comment]
Actually, return values were described in the beginning of functions section.  One value was missing and I added it.
