### ISSUE TITLE
NATHELPER: fix_nated_sdp does not support a=rtcp headers

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#2459]
### Description

fix_nated_sdp() function with an IP address as argument supports modifying the media line and the connection line but not a=rtcp. It would be helpful if it did that line too.

### Expected behavior

a=rtcp:<port> IN ip4 <new IP>
#### Actual observed behavior
No modification

**Comment by miconda** [comment]
This should be implemented, with the commits referenced above.
