### ISSUE TITLE
[kamdbctl] db_text incorrect version table in 5.4

### ISSUE THREAD

**Issue by igorolhovskiy** [kamailio/kamailio#2463]
### Description

`Version` table in default `db_text` creation has incorrect structure.

### Troubleshooting

version table is 

#### Reproduction

Installing Kamailio 5.4 from Debian repos. Tuning **kamdbctl** to DBTEXT.
Running `kamdbctl create`

Check `version` table.

Shows something like
```
id(int,auto) table_name(string) table_version(int)
version:1
...
```
Should be
```
table_name(string) table_version(int)
version:1
```
or with `id` index

### Possible Solutions

Manually delete `id(int,auto)` from `version`

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
/# kamailio -v
version: kamailio 5.4.1 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0
```

* **Operating System**:

Debian 10/Docker image
```
# uname -a
Linux 9b7efa852274 5.3.18-lp152.36-default #1 SMP Tue Aug 18 17:09:44 UTC 2020 (885251f) x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Should be fixed now in master in 5.4 branches. It was a side effect of adding id column, which is auto-filled by sql servers, but for dbtext the file is generated from makefile.
