### ISSUE TITLE
[db_text]  In a case of using dispatcher from db_text, only first entry in table is processed

### ISSUE THREAD

**Issue by igorolhovskiy** [kamailio/kamailio#2465]
### Description

I have list of dispatchers in `db_text`.  But only first is processed.

#### Reproduction

Create `dispatcher` table in a case of db_text
```
id(int,auto) setid(int) destination(string) flags(int) priority(int) attrs(string) description(string)
2:1:sip\:asterisk_2\:5060:2:0::asterisk_2
1:1:sip\:asterisk_1\:5060:2:0::asterisk_1
```
Start Kamailio

Run `kamctl dispatcher dump`

```
# kamctl dispatcher dump
{
  "jsonrpc":  "2.0",
  "result": {
    "NRSETS": 1,
    "RECORDS":  [{
        "SET":  {
          "ID": 1,
          "TARGETS":  [{
              "DEST": {
                "URI":  "sip:asterisk_2:5060",
                "FLAGS":  "AP",
                "PRIORITY": 0
              }
            }]
        }
      }]
  },
  "id": 124
}
```
Only the first entry is processed.

On running
```
# kamctl dispatcher reload
```
nothing is changed.

### Possible Solutions

Adding other dispatchers via `kamcmd`

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
/# kamailio -v
version: kamailio 5.4.1 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0
```

* **Operating System**:

Debian 10/Docker.

```
# uname -a
Linux 9b7efa852274 5.3.18-lp152.36-default #1 SMP Tue Aug 18 17:09:44 UTC 2020 (885251f) x86_64 GNU/Linux
```

**Comment by grumvalski** [comment]
Which mode are you using for db_test? http://www.kamailio.org/docs/modules/devel/modules/db_text.html#idm136
If you're using the default 0 then the tables are only read once at startup so a dispatcher.reload would not have any effect.

**Comment by igorolhovskiy** [comment]
I'm using mode '0', but only one dispatcher is created on Kamailio start.
Also just tested with mode `1` - same effect.

**Comment by igorolhovskiy** [comment]
As a future investigation
```
kamcmd> db_text.query 'select * from version'
error executing sql statement
```
But `usloc` module successfully writes into it.

**Comment by miconda** [comment]
Provide all logs printed by kamailio at startup with `debug=3` in kamailio.cfg.

**Comment by igorolhovskiy** [comment]
https://pastebin.com/GtgBdzn5

dispatcher:
```
id(int,auto) setid(int) destination(string) flags(int) priority(int) attrs(string) description(string)
2:1:sip\:asterisk_2\:5060:2:0::asterisk_2
1:1:sip\:asterisk_1\:5060:2:0::asterisk_1
```

**Comment by igorolhovskiy** [comment]
Ok. I think I found an issue. 
Mandatory CRLF at the end of 2nd string

**Comment by miconda** [comment]
Indeed, I was leading to it by looking at log messages, a row ends by end of line.
