### ISSUE TITLE
SIP Header 'Replaces' Support in Module RTPENGINE for 3GPP SRVCC functionality

### ISSUE THREAD

**Issue by hamidrhashmi** [kamailio/kamailio#2473]
Do Module  RTPENGINE Supports 'Replaces' header (RFC 3891), if yes then how to use this feature, if no then will module RTPEngine will have support for 'Replaces' in the near future? I have been using Freeswitch for this functionality but facing many difficulties in it.

**Comment by oej** [comment]
Please use the mailing list for questions. This is where you go to report issues in the software.
