### ISSUE TITLE
Minor doc changes to Registrar module

### ISSUE THREAD

**Issue by whosgonna** [kamailio/kamailio#2477]
### Description

Use of acronym "HF" (header field) in the REGISTRAR is a bit obscure.  It probably makes sense to experienced Kamailio admins, but it's not immediately apparent to beginners.  Since there is little gained by using the acronym in this document it would be more friendly to use "header field".

Also, there is a double negative in section 4.1/flags/0x01:

```
0x01 - save the contacts only in memory cache without no DB operation;
```

The literal meaning of this sentence is that it performs a DB operation. This should be changed to  "with no" or possibly just "without", or even "with no".

### Expected behavior

Use 'header field' instead of 'HF'.  Use "with" instead of "without no".

#### Actual observed behavior

As indicated above

#### Debugging Data

Not applicable

#### Log Messages

Not applicable

#### SIP Traffic

Not applicable

### Possible Solutions

Use 'header field' instead of 'HF'.  Use "with" instead of "without no".

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

Exists in most recent code branch.

* **Operating System**:

Not applicable.

**Comment by henningw** [comment]
Thanks, should be fixed with referenced pull-request. Re-open if there are still issues.
