### ISSUE TITLE
Permissions module does not check if hash table exists

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#248]
We have a 4.3 Kamailio with Permissions, trying to use address* functions.The table is in a text file with db_text with some error in it, so Kamailio fails to load a hash table. The server starts, but if we run a RPC command or call a function in the routing script, we get a core dump.

The permissions module checks should always check if the address table exist before accessing it.

**Comment by miconda** [comment]
Pushed patches to master branch with safety checks for rpc and address functions. If there are other such cases, re-open.
