### ISSUE TITLE
kamailio-3.3.x-freeswitch-1.2.x-sbc  I encountered 488 when using public network

### ISSUE THREAD

**Issue by yuexiajiayan** [kamailio/kamailio#2487]
i'm use it on freeswitch public ip 47.xx.xx.xx and private ip 172.31.239.38 
i'm test it http://kb.asipto.com/freeswitch:kamailio-3.3.x-freeswitch-1.2.x-sbc   (freeswitch.bindip= 47.xx.xx.xx  )
and 101 to 100 and return 488 
There seems to be no problem using it on the intranet
and log:
 8(21255) NOTICE: {2 26129640 INVITE b1b6df17-7ccd-1239-9990-00163e05779b} acc [acc.c:279]: acc_log_request(): ACC: call missed: timestamp=1601366864;method=INVITE;from_tag=t7jr1405ee9gp;to_tag=dGSi5k2;call_id=b1b6df17-7ccd-1239-9990-00163e05779b;code=488;reason=Not acceptable here;src_user=101;src_domain=172.31.239.38;src_ip=47.xxx.xx.xx;dst_ouser=100;dst_user=100;dst_domain=220.207.94.221

fs log:
2020-09-29 17:05:31.370421 [DEBUG] switch_core_media.c:12301 sofia/internal/101@47.xx.xx.xx.xx:6060 Patched SDP
---
v=0
o=FreeSWITCH 1601363255 1601363256 IN IP4 47.xxx.xx.xx
s=FreeSWITCH
c=IN IP4 47.xxx.xx.xx
t=0 0

+++
v=0
o=FreeSWITCH 1601363255 1601363257 IN IP4 172.31.239.38
s=FreeSWITCH
c=IN IP4 172.31.239.38
t=0 0

2020-09-29 17:05:31.370421 [DEBUG] sofia_glue.c:1619 sofia/internal/101@47.xx.xx.xx:6060 sending invite version: 1.10.3-release  64bit
Local SDP:
v=0
o=FreeSWITCH 1601363255 1601363257 IN IP4 172.31.239.38
s=FreeSWITCH
c=IN IP4 172.31.239.38
t=0 0

to 100 ask return   INCOMPATIBLE_DESTINATION error

Do you need to modify anything in the public network？
I can't find any information. Please help me? thinks

**Comment by miconda** [comment]
Questions about how to use kamailio have to be asked on sr-users mailing list (see kamailio.org website). This tracker is for reporting bugs in kamailio source code.
