### ISSUE TITLE
app_python: Missing documentation

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#249]
The App_python README has too many sections with just "TBD" as documentation. Needs to be fixed.

http://kamailio.org/docs/modules/4.3.x/modules/app_python.html

**Comment by ezdev128** [comment]
@oej Thank you Olle. i'm working on it already.

**Comment by oej** [comment]
Reminder. A module with "TBD" in the doc for such a long time doesn't look good.

**Comment by miconda** [comment]
To get something for a starting point, I added some short notes in the docs based on a quick look at the code. However, not being the developer, nor the user of app_python module, anyone feel free to amend or enhance.

For now I am closing this issue. Anything wrong to current content can be reported as a new bug.
