### ISSUE TITLE
Run your own SIP VoIP service on both IPv4 and IPv6 (RTPproxy)

### ISSUE THREAD

**Issue by amen160** [kamailio/kamailio#2490]
Hi Everybody.
I try setup call from one Device Ipv6 to device Ipv4, but the audio is one way. I use the example here (it quite old)
http://kb.asipto.com/kamailio:kamailio-mixed-ipv4-ipv6.
Does anyone see the error or can someone give me a tip?

**Comment by linuxmaniac** [comment]
Kamailio Project uses GitHub Issues only for bugs in the code or feature requests.

If you have questions about using Kamailio or related to its configuration file, ask on sr-users mailing list:

  * http://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-users

If you have questions about developing extensions to Kamailio or its existing C code, ask on sr-dev mailing list:

  * http://lists.kamailio.org/cgi-bin/mailman/listinfo/sr-dev
