### ISSUE TITLE
permissions: RPC AddressDump doesn't include mask size

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#250]
The new RPC command doesn't output the mask, only the IP.

**Comment by miconda** [comment]
iirc, what is returned by this command are only full ips, there should be another command subnetDump or so to return networks addresses. At least it is the way with mi commands.

Somehow confusing, maybe the two commands should be merged.

**Comment by miconda** [comment]
Given the subnetDump command, shall this be still open? Or at least, not labeled as bug.

**Comment by oej** [comment]
I removed the bug label and will remind myself about this.

**Comment by miconda** [comment]
This was not picked up for long time. subnetDump offers the requested behaviour. Anyone can start implementing new rpc commands and combine existing behaviours of current rpc commands, but this doesn't feel any longer like a missing feature. I am closing this one.
