### ISSUE TITLE
UAC Module replaces Contact Header so Replies not Relayed Back

### ISSUE THREAD

**Issue by ForGuru** [kamailio/kamailio#2504]
### Description

 Kamailio (UAC) ---> Asterisk 

Call comes from DID Trunk and UAC module is used as per some fixed mapping in DB so we use that user to make call Asterisk through UAC as shown below.
```
$var(original_ru) = $rU;
if (uac_reg_request_to("$avp(auser)", 1)) {

			$var(status) = uac_reg_status("$rU"); 
			$rU = $var(original_ru) ;
t_on_failure("REMOTE_AUTH");
}


failure_route[REMOTE_AUTH] {
    if (t_check_status("401|407")) {
	    xlogl("L_INFO", " Remote asked for authentication");
    	t_drop_replies();
		# - remove preloaded route headers
		remove_hf("Route");		
		record_route();
		$avp(authed) = 1;
		
		# Drop replies so that they are not sent back to the UAC
		uac_auth();
		route(RELAY);
    }
}
```
in all this activity Contact Header also replaced by UAC_AUTH so Replies from Asterisk reaches to Kamailio but does not relay back to DID Trunk.
-->

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Contact header is not touched by uac_auth(), likely you have some other operation in kamailio.cfg that updates Contact, if that happens.

For the moment, it looks like a problem related to use of kamailio, not an issue in the code. Therefore you have to address further questions to sr-users@lists.kamailio.org mailing list. This issue tracker is not for Kamailio use support and assistance questions. If it proves to be any bug in the code, then the issue can be reopened.
