### ISSUE TITLE
rtp_media_server: declare extern dialog_list_mutex and tmb in header file

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#2522]
Similar to #2235 

Better logs...
```
/usr/bin/ld: rtp_media_server.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:42: multiple definition of `dialog_list_mutex'; rms_dialog_info.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:42: first defined here
/usr/bin/ld: rtp_media_server.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:54: multiple definition of `tmb'; rms_dialog_info.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:54: first defined here
/usr/bin/ld: rms_media.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:42: multiple definition of `dialog_list_mutex'; rms_dialog_info.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:42: first defined here
/usr/bin/ld: rms_media.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:54: multiple definition of `tmb'; rms_dialog_info.o:/builddir/build/BUILD/kamailio-5.4.1/src/modules/rtp_media_server/rtp_media_server.h:54: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by amessina** [comment]
Thank you @miconda. The build is now possible for Fedora 32/33 x86_64.

**Comment by jchavanton** [comment]
Thanks folks, 

Very cool that you are able to build this module given the dependencies required, I was thinking it was not in the default module group.

**Comment by amessina** [comment]
> Thanks folks,
> 
> Very cool that you are able to build this module given the dependencies required, I was thinking it was not in the default module group.

I started building the Fedora packages here https://messinet.com/rpms/browser (bcunit, bctoolbox, ortp, and mediastreamer2) -- challenging to say the least and I probably need to update the packages to "include" more of the functionality from the underlying deps.  Working through testing now and getting segfaults.  Probably need to move testing to a separate simpler box.

**Comment by miconda** [comment]
Declaration were moved to .c files, but I reopen because the lock should be pointer and allocated in shared memory lock_alloc() to be properly used.

**Comment by amessina** [comment]
Thank you. @jchavanton, I'm going to open another issue where `rms_bridge()` doesn't seem to work properly.

**Comment by jchavanton** [comment]
This should fix the lock problem
https://github.com/kamailio/kamailio/pull/2529
