### ISSUE TITLE
Wrong callid in ACK for negative reply(hop by hop ACK)

### ISSUE THREAD

**Issue by korithi** [kamailio/kamailio#2525]
Hello guys,

My kamailio version is:

version: kamailio 5.1.1 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.

I am facing a strange bug with TM in case of negative replies.

A party sends the invite 
B party connects the call
B party after a few time sends in dialog invite with t38 media.
A party rejects the in-dialog invite with 488
Kamailio send ACK to A party(since it is an ACK for negative replies it is build in each hop)
The problem in this case is that the ACK sent by kamailio to A party has the callid of kamailio - B party.
Since it has a different callid the A party does not recognize the ACK.

How can I resolve this issue?

Thanks and regards,
Rafael

**Comment by henningw** [comment]
Kamailio will usually not (but some corner cases aside) alter the Call-ID of a call.
Please update to a more recent version (e.g. from 5.3.x or 5.4.x) to see if your problem is still there.
Close this one as it is for a really old kamailio version, long end of life.

**Comment by korithi** [comment]
Hello,

Thank you for your prompt feedback!
I am not able to make the upgrade at the moment. 
Can you please suggest if there is any case to resolve it in the actual version?
Is this known as an issue from you, when you say "(but some corner cases aside)"?

Thanks,
Rafael

**Comment by henningw** [comment]
You can e.g. change the callid with the topoh module, and of course also just alter the header with textops operations etc..
Feel free to ask on sr-users list with more details, it might be more related to the actual setup/user agents involved etc..
