### ISSUE TITLE
[RFE]: Allow NULL for acc db_extra and multi_leg_info

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#2531]
### Description

Just as in #1378, allowing nullable entries for SQL would be appreciated in acc `db_extra` and acc `multi_leg_info`.

### Expected behavior
Empty/NULL values should be inserted with `NULL`.  For example, I can't create a `timestamp without time zone` to be used with multi-leg-accounting as follows.
```
modparam("acc", "multi_leg_info",
        "leg_dst_user=$avp(leg_dst_user);"
        "leg_dst_domain=$avp(leg_dst_domain);"
        "leg_sip_code=$avp(leg_sip_code);"
        "leg_time=$avp(leg_time);"
        "leg_to_tag=$avp(leg_to_tag)")

$avp(leg_time)=$timef(%F %T)

```

#### Actual observed behavior
Emplty/NULL values are inserted with `''` which fails as `''` is invalid input for a `timestamp without time zone` column.

#### Log Messages

```
db_postgres [km_dbase.c:266]: db_postgres_submit_query(): 0x7f26f7fb6cc8 PQsendQuery Error: ERROR:  invalid input syntax for type timestamp: ""
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
ersion: kamailio 5.4.1-8.gitd43872c11e.fc32.2 (x86_64/linux) 09fd6a
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 09fd6a 
compiled on 00:00:00 Oct 22 2020 with gcc 10.2.1
```

* **Operating System**:

```
Linux host 5.8.15-201.fc32.x86_64 #1 SMP Thu Oct 15 15:56:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Pushed the feature with the commit referenced above, but no tests done. Test and if there are problems, open a bug, otherwise quickly confirm here it works to mark the case closed.

**Comment by amessina** [comment]
@miconda, I can confirm your fix works.  Thank you.  It might be best to update the schema creation scripts for acc, acc_cdrs, and missed_calls to remove the `NOT NULL` and `''::VARCHAR` declarations, since enabling the associated modparams without changing the schema will result in insertion errors.

**Comment by henningw** [comment]
@amessina I understand the acc_extra_nullable is not active by default. The DB schema script is targeted for the default case, but document this e.g. in the module readme would be probably good. Maybe you could create a pull request for that.

**Comment by amessina** [comment]
@henningw ok. I am working through F32 -> F33 upgrades now, but will then turn my attention to creating a documentation pull request.

**Comment by amessina** [comment]
I have more testing to do, apparently -- there are times where `multi_leg_info` variables are all set to `NULL` in the DB (without error), although they are defined and printed properly in the syslog.  I've tried moving the modparam `multi_leg_info` above and below modparam `acc_extra_nullable`, but the results seem random.  I'll see what else I can find and report back, but so far this only seems to affect the `multi_leg_info` variables -- the `db_extra` ones are always inserted properly.
