### ISSUE TITLE
Dump Configuration and Exit (new flag -C [filename])

### ISSUE THREAD

**Issue by CrazyTux** [kamailio/kamailio#2546]
### Description

Add runtime flag -C [filename] which takes the given file name and dumps its compiled configuration (including include and import files)

### Expected behavior
Dump complete configuration after inclusions to terminal / stdout and exit.

#### Actual observed behavior
Flag does not exist

#### Debugging Data
N/A

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.5.0-dev3 (x86_64/linux) 76bb9b
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 76bb9b 
compiled on 02:45:06 Oct 24 2020 with gcc 8.3.0

**Comment by miconda** [comment]
Just added `--cfg-print` that should do what you were looking for, to the extent of evaluating `include_file/import_file` and `ifdef/ifndef` conditions.

It does not replace the tokens defined with `define`, `subst` or the other token defining variants. If someone needs to go further into this, then a pull request is more than welcome.

Basic tests were done with default config file and an imported file. If there are issues, open a bug report.

As a side note, to be aware of, the empty lines are kept, so the output may have sequences of several empty lines, if the `#!ifdef ... #!endif` blocks had empty lines before and after.

**Comment by miconda** [comment]
Very important - for now the `--cfg-print` works if the main configuration file has the first line:

```
#!KAMAILIO
```

**Comment by kamailio-sync** [comment]
Daniel-Constantin Mierla writes:

> Very important - for now the `--cfg-print` works if the main
> configuration file has the first line: 

> #!KAMAILIO

Can there be other stuff on the line after #!KAMAILIO?

For example emacs can be told about the major mode used in the file by
checking if first non-blank line contains  -*-<something>-*-.

So I would like the definition go like this:

`--cfg-print` works if the main configuration file starts with

#!KAMAILIO

-- Juha

**Comment by CrazyTux** [comment]
Thank you!

**Comment by CrazyTux** [comment]
I've confirmed this is working as expected, thanks again!
