### ISSUE TITLE
unregister account for the uac module

### ISSUE THREAD

**Issue by ceedius** [kamailio/kamailio#2549]
The unregister functionality for the UAC module is missing.
Some sip providers do not allow you to register an account from another node with the current active registration. Accordingly it is difficult to transfer registration from one kamailio to another kamailio.
 
Can I implement sending a REGISTER sip message with Expires: 0 when executing kamcmd uac. reg_disable or the additional kamcmd uac.reg_ unregister command

**Comment by miconda** [comment]
I pushed the commit with implementation of `uac.reg_unregister` rpc command. Besides unregistration, the record will end up in disabled state, with expires=0 in the memory structure, so activating it may require to refresh the record.

I haven't tested the new command, if you discover problems, open a bug report.
