### ISSUE TITLE
Broken kamailio repo

### ISSUE THREAD

**Issue by jbartak** [kamailio/kamailio#2552]
Hi, looks like same issue as #2407 and #1604   is present.
Again i cant install kamailio. 
![image](https://user-images.githubusercontent.com/9643757/99236216-34bae100-27f7-11eb-99d1-59361b4c8e09.png)

**Comment by henningw** [comment]
Hello, did you already tried http://rpm.kamailio.org/ ? I think this is the new RPM packaging host.

**Comment by miconda** [comment]
The repo at https://rpm.kamailio.org/ has to be used, although it has only the stable braches and 5.0 is out of maintenance for very long time. So it should upgrade to 5.3 or 5.4. For more details see:

  * https://www.kamailio.org/wiki/packages/rpms

The opensuse build service repo is used only for basic testing of packaging and must not be used anymore for production. Moreover, the Kamailio project has no control to opensuse build service infrastructure, so if their servers are down, then wait or report to that web service.
