### ISSUE TITLE
Keep several last versions at Kamailio build infrustructure

### ISSUE THREAD

**Issue by arkadiam** [kamailio/kamailio#2557]
### Description

When a new version in released, built and made available it'll be great to preserve at least one previous build.

E.g. for Ubuntu/Debian repos:

deb http://deb.kamailio.org/kamailio53 bionic main
deb-src http://deb.kamailio.org/kamailio53 bionic main

As of today these repos have 5.3.7 builds only. It not possible to downgrade to a previous version 5.3.6 using native
package management tools.

### Expected behaviour

apt list -a kamailio
...have kamailio 5.3.6 option here...
apt install kamailio=5.3.6+ubuntu18.04

#### Actual observed behaviour

apt list -a kamailio
Listing... Done
kamailio/unknown,now 5.3.7+ubuntu18.04 amd64 [installed]
kamailio/bionic 5.1.2-1ubuntu2 amd64

#### Other notes

This will be helpful in cases when quick downgrade is required. After the last upgrade to 5.3.7 by some reason Kamailio stopped processing ACKs after the call was answered and 200 OK was sent. We had to rebuild 5.3.6 from sources and rollback to our build to restore the service. I'll try to figure out what was the issue and provide more details in a separate issue.

**Comment by henningw** [comment]
This is apparently a limitation from the current automated build infrastructure, as documented [here](https://github.com/sipwise/kamailio-deb-jenkins/issues/9). Its probably more appropriate to discuss this there, so I am closing this one.
One workaround is to build your own packaging infrastructure, as we did.

About the ACK issue, yes please provide more details about this in a separate issue.
