### ISSUE TITLE
CSeq is not being updated for ACK messges after upgrade to 5.3.7.  Dialog + UAC module

### ISSUE THREAD

**Issue by arkadiam** [kamailio/kamailio#2559]
### Description

After updating from 5.3.6 to 5.3.7 Kamailio is no longer increments CSeq for ACK when used together with UAC module.

Usage scenario:
<pre>
|EP1                   | Kamailio             | PBX
|    ->INVITE ->       |                      |
|    <- 407 -          |                      |
|    - ACK ->          |                      |
| -> INVITE SDP AUTH-> |                      |
|    <- 100 Trying -   |                      |
|                      | - INVITE SDP ->      |
|                      | <- 407 -             |
|                      | -> ACK ->            |
|                      | - INVITE SDP AUTH -> |
|                      | <- 100 Trying -      |
|                      | <- 200 OK -          |
|    <- 200 OK -       |                      |
|    - ACK ->          |                      |
|                      | - ACK ->             |
...
</pre>

Kamailio is configured to use dialog module and calling "dlg_manage();"
UAC module is used to authenticate request on the PBX.
Because of the authentication against the PBX the CSeq is being incremented independently between Kamailio & PBX.
ACK that is send to the PBX after 200 OK usually is CSeq + 1 from EP1 ACK message.

After update, Cseq is no longer incremented in ACK which cause re-transmission of 200 OK by the PBX and eventually in 30 sec PBX drops the call because 200 is not being acknowledged.

Dialog configured as:
modparam("dialog", "dlg_flag", FLD_TRACKDLG)
modparam("dialog", "track_cseq_updates", 1)
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "timeout_avp", "$avp(dlgtimeout)")
modparam("dialog", "default_timeout", 43200)

UAC configured as:
modparam("uac", "reg_db_url", DBURL)
modparam("uac", "reg_contact_addr", REG_CONTACT)
modparam("uac", "reg_timer_interval", 10)
modparam("uac", "restore_from_avp","$avp(original_uri_from)")
modparam("uac", "restore_to_avp","$avp(original_uri_to)")
modparam("uac", "restore_dlg", 1)
modparam("uac", "auth_username_avp","$avp(auser)")
modparam("uac", "auth_password_avp","$avp(apass)")
modparam("uac", "auth_realm_avp","$avp(arealm)")
modparam("uac", "restore_mode","manual")

### Possible Solutions

After reverting this commit   a973882b064c758972ce40e9ac3a83440c613be1 CSeq started to update properly.
"dialog: skip non-INVITE initial request for cseq update processing"

**Comment by miconda** [comment]
The commit you reverted introduced a regression, fixed in a follow up commit done after release of 5.3.7: 5ffe28d4b83b1a75b1706bd851b76575b3d09c45

If use use debian/ubuntu packages from deb.kamailio.org, then you should use the nightly builds for branch 5.3. 

If you use sources, just install from latest branch 5.3.

Closing this one, being fixed in the branch -- if doesn't work for you, reopen.
