### ISSUE TITLE
cannot load ims_dialog-create.sql into mysql

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2575]
### Description

When I try to load kamailio schema into MySQL database I get an error "Duplicate entry 'dialog_vars' for key 'PRIMARY'".
I have checked the duplicated `dialog_vars` table definition at
1. [dialog-create.sql#L32-L38](https://github.com/kamailio/kamailio/blob/master/utils/kamctl/mysql/dialog-create.sql#L32-L38)
2. [ims_dialog-create.sql#L41-L49](https://github.com/kamailio/kamailio/blob/master/utils/kamctl/mysql/ims_dialog-create.sql#L41-L49)

#### Reproduction
Load schemas from dialog-create.sql and from ims_dialog-create.sql.

### Possible Solutions
Remove `dialog_vars` table definition from `ims_dialog-create.sql` shema file.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
@safarov-dell:/usr/share/kamailio$ kamailio -v
version: kamailio 5.5.0-dev3 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 12:51:16 Dec  4 2020 with gcc 10.2.1
```

* **Operating System**:

```
@safarov-dell:/usr/share/kamailio$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0_alpha20200917
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by sergey-safarov** [comment]
Also version different for `dialog_vars` in schemas files.

**Comment by miconda** [comment]
The schema file for ims modules are not in the `src/lib/srdb1/schema`, which is the right way to have corresponding sql files generated using `make dbschema`.

The solution here is to rename the default table name for the ims_dialog module. Likely it was expected not to be used in the same deployment with the dualog module, but it is better to use different default table names anyhow.
