### ISSUE TITLE
kamailio.cfg calling t_check_trans() without using the result?

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#2578]
### Description

Why does the sample script call `t_check_trans()` without using the result?

```
if (!is_method("ACK")) {
		if(t_precheck_trans()) {
			t_check_trans();
			exit;
		}
		t_check_trans();
	}
```
This function call doesn't seem to have any side effects according to the documentation of the tm
module.

### Troubleshooting
N/A
#### Reproduction
N/A view the kamailio.cfg script at https://github.com/kamailio/kamailio/blob/master/etc/kamailio.cfg
#### Debugging Data
N/A
### Additional Information

master branch
* **Operating System**:
N/A

**Comment by miconda** [comment]
For questions related to use of Kamailio and its configuration file, write to sr-users@lists.kamailio.org. The issue tracker here is only for bugs in source code or proposing new features.
