### ISSUE TITLE
Microsoft Teams and Survivable Branch Appliance (SBA) 

### ISSUE THREAD

**Issue by MarkMasiak** [kamailio/kamailio#2580]
Support for Teams Survivable Branch Appliance Direct Routing 

Occasionally, a customer site using Direct Routing to connect to Microsoft Phone System may experience an internet outage.

Assume that the customer site--called a branch--temporarily cannot connect to the Microsoft cloud through Direct Routing. However, the intranet inside the branch is still fully functional and users can connect to the Session Border Controller (SBC) that is providing PSTN connectivity.

https://docs.microsoft.com/en-us/microsoftteams/direct-routing-survivable-branch-appliance

--

**Comment by henningw** [comment]
This issue is about a specific feature of a proprietary product. Its to unspecific to be kept here in the tracker, therefore i am closing it.
If you want to discuss details about this functionality regarding its implementation with Kamailio, just do it e.g. on the sr-users list.
