### ISSUE TITLE
Passing Listening Socket details through Environment Variables

### ISSUE THREAD

**Issue by sido420** [kamailio/kamailio#2585]
I am not 100% sure if its a bug or feature request. And, I have already asked this question in mailing list.

### Description

I was  trying to pass environment variables to Kamailio that are definitely there in the container. Also, I am trying to use the environment variables to specify ports for Kamailio to listen on. I have already tried passing variables through -A option but to no avail.

### Expected behavior
Please note that these values are known at start time so should work. 

#### Actual observed behavior
Errors

#### Debugging Data
I have tried:

```
#!define TLS_TO_LISTEN tls:TLS_IP:$env(TLS_PORT)
```

I have also tried using in EVAPI `bind_addr` modparam but that throws errors:
```
#!define EVAPI_LISTEN "0.0.0.0:EVAPI_PORT"
..
modparam("evapi", "bind_addr", EVAPI_LISTEN )  // IP and port to listen on for incoming TCP connections.
```
Error:
```
 ERROR: evapi [evapi_mod.c:156]: mod_init(): invalid port: 0
```

### Additional Information

```
version: kamailio 5.4.2 (x86_64/linux) f8885c
```

* **Operating System**:
Docker Container:
```
Linux fe1933ee6208 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 GNU/Linux 
```

**Comment by miconda** [comment]
The `#subst` or `#!substdef` can be used to get values from vars like `$env(NAME)`. I master branch there is now `#!defenv`, see the core cookbook in the wiki for more details, or ask more specific questions on sr-users mailing list.
