### ISSUE TITLE
cfgutils: sleep and usleep with pseudovariables support

### ISSUE THREAD

**Issue by zolia** [kamailio/kamailio#259]
Hello, 

i would like to propose a support for pseudovariables in sleep and usleep functions. 
I know that there is such function as async_sleep, but it accepts only integer numbers (seconds) as a value. 
Delay in range of seconds for some SIP messages is way too long in some circumstances.

**Comment by miconda** [comment]
I just pushed a patch to allow vars in sleep() and usleep() -- try with latest master branch and if there are problems, open an issue on tracker.

**Comment by zolia** [comment]
That was fast!

just tried, looks like it works.
