### ISSUE TITLE
Dispatcher SNI support

### ISSUE THREAD

**Issue by nakchak** [kamailio/kamailio#2591]
Is it possible to specify a specific server name/server id for dispatcher to use to send pings with (and in outgoing requests) 

It seems I can't (or haven't noticed in the docs) an event route I could use to set the xavp, as tm:local-request happens to late to use there.  As an aside why isn't there a "last chance before send" event route? 

This is probably a feature request more than a bug, as the ideal solution from my point of view would be an additional dispatcher attrs value to be able to set it per destination in the underlying dispatcher data

Judging by the output from tls module dbg the tls xavps are checked, before the ping is sent..

I've had a cursery glance at dispatch.c and it seems easy enough to add an extra attr parameter but I'm ata loss as to how I would preset the server name/id xavp... (I'm no c dev, but can Google quick enough to follow along mostly, and happy to fiddle away if anyone can be kind enough to give me some pointers in the right direction)

**Comment by grumvalski** [comment]
Did you check 'ping_from' (http://www.kamailio.org/docs/modules/devel/modules/dispatcher.html#dispatcher.ex.attributes)? Could it cover your needs?

**Comment by nakchak** [comment]
No afraid not, I need to send all traffic to a destination using a specific tls client config, including dispatcher pings, that only sets the from header of the options message, in a request route I just set the tls xavp with suitable values to force a specific tls client profile.

**Comment by miconda** [comment]
I added the function `tls_set_connect_server_id(srvid)` in tls module trying to cover this kind of need to specify the server id for next tls connect in the event_route[tm:local-request], where you can set its value from the dispatcher route attributes.

Testing and feedback would be appreciated. I am closing this issue, in case of a problems, open a new one reporting what happens.
