### ISSUE TITLE
dialog flag vs dlg_manage() - flag doesn't store uac_replace_* dialog variables

### ISSUE THREAD

**Issue by zeusca** [kamailio/kamailio#2593]
### Description
When invoking dialog tracking by flag instead of dlg_manage(), dialog doesn't store uac_replace_* variables. As a result, uac restore functionality doesn't work.

#### Reproduction
#!define FLT_DIALOG 4
...
modparam("dialog", "dlg_flag", FLT_DIALOG)
...
request_route {
  if (is_method("INVITE"))
    setflag(FLT_DIALOG);
...
}

Make a call. 
List dialogs (kamcmd dlg.list)
You'll notice the dialog has no _uac_ variables

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.3.8 (x86_64/linux) a58155
```

* **Operating System**:

```
NAME="Debian GNU/Linux"
VERSION="8 (jessie)"
```

**Comment by miconda** [comment]
The use of dialog flag was planned to be deprecated, but nobody got the time to clean it up and remove that option. Newer functions are relying on dlg_manage() being used in config file.

**Comment by zeusca** [comment]
Noted. Case closed.
