### ISSUE TITLE
starting kamailio with carrierroute takes too long

### ISSUE THREAD

**Issue by kristina258** [kamailio/kamailio#2613]
### Description

Hi,

I am migrating from Kamailio 4.4.7 (debian 8.1) to 5.4.3 (debian 10.7).
I changed the neccessary changes in configuration (replaced MI with RPC) and I tried to start the kamailio. The issue is that it takes about 3minutes to start. On the older version 4.4.7 it started aproximetly in 20s.

The modules I am using are:
```
"cfgutils.so","db_mysql.so","kex.so","tm.so","tmx.so","sl.so","rr.so","pv.so","maxfwd.so","textops.so","siputils.so","xlog.so","sanity.so","ctl.so","jsonrpcs.so","exec.so","carrierroute.so","avpops.so","sqlops.so","dmq.so","htable.so","dialog.so","acc.so","acc_radius.so","dispatcher.so","dialplan.so","textopsx.so","statsd.so","app_perl.so","http_async_client.so".
```

I assume the issue is caused by carrierroute module. It takes also about 3 minutes to reload routes (when the kamailio service is running) using rpc command cr.reload_routes.
I did not change anything in configuration related to carrierroute module.

```
modparam("carrierroute", "config_source", "db")
modparam("carrierroute", "db_url", DBURL)
modparam("carrierroute", "match_mode", 128)
modparam("carrierroute", "avoid_failed_destinations", 0)
modparam("carrierroute", "carrierroute_table", "carrierroute_view")
```

Carrierroute module loading on version 4.4.7 needed: 

- INFO: carrierroute [cr_db.c:317]: load_route_data_db():  **took  1s**
- INFO: carrierroute [cr_carrier.c:100]: add_domain_data(): and INFO: carrierroute [cr_data.c:414]: get_domain_data_or_add(): **took 8s**
- INFO: carrierroute [cr_data.c:655]: rule_fixup(): **took 3s**

Carrierroute module loading on version 5.4.3 needed: 

- INFO: carrierroute [cr_db.c:317]: load_route_data_db():  **took  1s**
- INFO: carrierroute [cr_carrier.c:100]: add_domain_data(): and INFO: carrierroute [cr_data.c:414]: get_domain_data_or_add(): **took 2min 23s**
- INFO: carrierroute [cr_data.c:655]: rule_fixup(): **took 17s**

I have also compiled kamailio version 5.0 on both (debian 8.1 and debian 10.7), but it also took so long to start on both machines.

### Additional Information

```
version: kamailio 5.4.3 (x86_64/linux) 06bd17
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 06bd17
compiled on 16:10:30 Jan 25 2021 with gcc 8.3.0

```

* **Operating System**:

```
Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
Debian 10.7

```

Thank you for your help.

**Comment by kamailio-sync** [comment]
did you see

3.10. fetch_rows (integer)

The number of the rows to be fetched at once from database when loading the
routing data. This value can be used to tune the load time at startup. For
1MB of private memory (default) it should be below 3750. The database
driver must support the fetch_result() capability. This parameter is
tunable via the ser cfg framework.

*Default value is “2000”.*

*Example 1.10. Set fetch_rows parameter*

...
modparam("carrierroute", "fetch_rows", 3000)
...


 ?

Regards,

David Villasmil
email: david.villasmil.work@gmail.com
phone: +34669448337

**Comment by miconda** [comment]
I am not using carrierroute, so I cannot comment on it, but similar situations happened in the past because of a different database server that was slower. Are you using same db server in the two scenarios? Or each version of kamailio is using a different database server?

**Comment by kristina258** [comment]
@kamailio-sync I saw that, but I was just wondering why different kamailio versions have different behavior when loading data. Anyway thanks, I will give it a try.

@miconda Yes, I am using the same DB server in scenario. 
On the old server I am curently running 4.4.7 and the loading of carrierroute data is well, but when I compile on the same server kamailio version 5.0 loading of the carrierroute data is too slow.

Thank you.

**Comment by kristina258** [comment]
I have tried with the following parameter:
```
modparam("carrierroute", "fetch_rows", 3000)
```

but loading of the carrierroute data was as slow as before.

**Comment by miconda** [comment]
The same issue was reported in #2653 - let's track it further there, the developers of the module were referred on that item.
