### ISSUE TITLE
lookup_to_dset should be documented in registrar module docs

### ISSUE THREAD

**Issue by Ozzyboshi** [kamailio/kamailio#2623]
The function lookup_to_dset() is a config command implemented inside the registrar module.

https://github.com/kamailio/kamailio/blob/351efd29d332703e79104a106ade08c9d1df6e20/src/modules/registrar/registrar.c#L183

As you can see from the link above, It triggers w_lookup_to_dset() and it ends up calling lookup_helper() with the mode flag set to zero that causes lookup_helper() to not overwrite the request uri (and destination uri if it's the case).

IMHO it's worth documenting lookup_to_dset() inside modules/registrar/README file, this function turned out very useful to me and I found out about it only digging into the code.

Thanks

**Comment by miconda** [comment]
Quite old function, somehow the docs were forgotten to be added. Fixed with the commit referenced above. Thanks!
