### ISSUE TITLE
register using uac module is getting send even if send_socket is not in this listening list of kamailio

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#2624]
### Description
I am uac module with database. uacreg table have the send_socket column. i do have 2 kamailio server running. i want only kamailio-1 should send register to uacreg entries. for this i have used send_socket column with socket of kamailio-1. After this we can see both kamailio server sending registration and that's the problem.

#### Reproduction
loadmodule "uac.so"
modparam("uac","auth_username_avp","$avp(auser)")
modparam("uac","auth_password_avp","$avp(apass)")
modparam("uac","auth_realm_avp","$avp(arealm)")
modparam("uac", "reg_contact_addr", "EXTERNAL_IP:5060")
modparam("uac", "reg_db_url", DBURL)

and use send_socket into uacreg with kamailio-1 socket.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.3.8 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0
```

* **Operating System**:

```
root@ip-10-0-12-135:/etc/kamailio# uname -a
Linux ip-10-0-12-135 5.3.0-1019-aws #21~18.04.1-Ubuntu SMP Mon May 11 12:33:03 UTC 2020 x86_64 GNU/Linux
```

**Comment by surendratiwari3** [comment]
@miconda please suggest. I can make a pull request against this but need your suggestion on this?

**Comment by oej** [comment]
Since you are not indicating a specific bug or propose a code change, please take your issue to the mailing list. Thank you.

**Comment by surendratiwari3** [comment]
@oej I have said very specific to bug and also shared reproducing steps. Please review the complete issue ticket. This should not be closed like this.

**Comment by oej** [comment]
Where in the documentation is it documented that it should behave as you expect? If you tell two kamailio servers to register, both will register. Please discuss how to solve this on the mailing list as it is the expected behaviour even though you may want another behaviour.

**Comment by surendratiwari3** [comment]
https://kamailio.org/docs/db-tables/kamailio-db-5.1.x.html#gen-db-uacreg - yes its documented. check uacreg table socket field. It should use that socket only. i can discuss over mailing list but let this issue to be open if anyone else have idea over this they can comment on this.

**Comment by oej** [comment]
I agree that documentation is unclear on the behaviour of what happens when the suggested socket does not exist. It is in most cases named "default socket" which suggests that if it does not exist, Kamailio will use another socket. Which is what happens in your case. You want kamailio to drop the request if the suggested socket does not exist, which I think may require code changes. It should not be the default behaviour as that may break installations, but it may be configured with a mod param.

**Comment by miconda** [comment]
@surendratiwari3 - we do not use issue tracker for discussions to give ideas of how to configure kamailio for specific cases. The description of the field in database is not saying that it must use that socket only. Once discussions on mailing list conclude on ways to do it using the current version or what new feature has to be implemented, then an issue here can be open for feature request and the dicussion on tracker can focus on implementation details, c code review, etc ...

Everyone tends to open issue on the tracker for something they need in their config/deployment, hoping to get help here. It is not what we use the tracker for. Discuss always on sr-users mailing list if you are not sure it is a bug. And connecting many instances to the same database, expecting that one instance behaves  different that the others is definitely not a clear bug. When many instances share database, they are expected to behave more or less the same.

**Comment by tiniyoadmin** [comment]
@oej agree on this. also please don't mind on my previous replies.

@miconda sure, i will use the channel for ideas, as this perticular instance i was sure that it was bug. but as @oej last comment clearify this. i will start discussing on mail chain.

**Comment by AlexeyLilichenko** [comment]
Was this problem solved? I have exctly same issue.
For now, I have not found a way to activate Sip-registration only on one server, and avoid doing so on 2nd server.
Making same SIp-registration on both server makes no sense.

I have tried to set 
` modparam("uac", "default_socket", "udp:<invalid IP>:5060")`
to drop SIP registration if in DB uacreg.socket not specified one of servers, but it does not work.

SIp-registartion still sent from both servers.

**Comment by henningw** [comment]
Please move the discussion to the mailing list, as already mentioned. If you want to disable registrations on certain servers, there are RPC commands to do this. https://kamailio.org/docs/modules/5.5.x/modules/uac.html#uac.r.uac.reg_disable
