### ISSUE TITLE
keepalive.add hangs

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#2625]
Trying to add first item to keepalive list using rpc command hangs, for example
```
kamailio_ctl> keepalive.add sip:example.com:5060 test
```

**Comment by miconda** [comment]
@juha-h - can you try with latest master again? I found an issue in ctl module that ws introduced in master branch a while ago, but after 5.4. it may be that one. If it is not fixed, then get the `kamctl trap` after it hangs, to see where the processes are stuck (you need gdb installed).

**Comment by kamailio-sync** [comment]
Daniel-Constantin Mierla writes:

> @juha-h - can you try with latest master again? I found an issue in
> ctl module that was introduced in master branch a while ago, but after
> 5.4. It may be that one. If it is not fixed, then get the `kamctl
> trap` after it hangs, to see where the processes are stuck (you need
> gdb installed).

Thanks, it works now:
```
# sip-proxy_ctl keepalive.list
# sip-proxy_ctl keepalive.add sip:username@domain listname
# sip-proxy_ctl keepalive.list
{
	uri: sip:username@domain
	owner: listname
	last checked: Thu Feb 11 10:39:22 2021

	last up: Thu Jan  1 02:00:00 1970

	last down: Thu Jan  1 02:00:00 1970

	state: 0
}
```
