### ISSUE TITLE
mod kazoo: wrong kazoo_publish example

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2627]
### Description

Example 1.21. kazoo_publish usage
contains string
```
$var(amqp_payload_request) = "{'Event-Category' : 'directory', 'Event-Name' : 'reg_success', 'Contact' : '" + $var(fs_contact) + "', 'Call-ID' : '" + $ci + "', 'Realm' : '" + $fd +"', 'Username' : '" + $fU + "', 'From-User' : '" + $fU + "', 'From-Host' : '" + $fd + "', 'To-User' : '" + $tU +"', 'To-Host' : '" + $td + "', 'User-Agent' : '" + $ua +"' ," + $var(register_contants)+ " }";
```

This example did not work because the string generates broken JSON:
1. here present value ` $var(register_contants)` but key is not present
2. JSON key and value must be started and terminated by `"` symbol (not by `'`)

**Comment by miconda** [comment]
@sergey-safarov - you can make a pull request to solve the syntax problems. I think that json specify use of double quotes, but I pretty sure I noticed that some libs/programming languages can deal with both styles (maybe python?!?).

On the other hand, the examples next to parameters or functions are supposed to give an idea of how to use it in terms of parameters format, etc ... they are not complete configuration snippets. The presence of a variable can indicate that such statement supports variables, it is not necessary to give the values for all variables. Maybe in this case the variable is supposed to contain the "key: value". My remark is generic, might not be the case here, just want to say that it can happen to see examples with variables, without seeing the assignment of that variable.

**Comment by miconda** [comment]
@sergey-safarov - can you push a fix for it as you tested the example?

**Comment by sergey-safarov** [comment]
I will assign this for me.

**Comment by miconda** [comment]
@sergey-safarov - is this still actual or not?

**Comment by sergey-safarov** [comment]
I rewrote example and make DocBook formatting.
As an example, I take the [current config](https://github.com/2600hz/kazoo-configs-kamailio/blob/master/kamailio/registrar-sync-role.cfg#L16) used in kazoo project.
