### ISSUE TITLE
authentificated INVITE badly managed when topos is activated

### ISSUE THREAD

**Issue by fgaisnon** [kamailio/kamailio#2629]
### Description

If topos is activated and kamailio responds a 407 "proxy authentication required" to an initial INVITE, INVITE received after with credentials (MD5 response in Proxy-Authorization header) is badly managed. Credentials are never validated and kamailio responds 407 again. If topoh is used instead topos all works fine and credential are validated.

#### Reproduction
Always.

### Additional Information
I have tested with official kamailio 5.4.3-0.

* **Operating System**:
centos 7 (3.10.0-693.11.1.el7.x86_64)

**Comment by miconda** [comment]
To understand properly what you want to achieve and see if it is a bug or a design limitation, email to sr-users@lists.kamailio.org describing the network topology for your voip platform, give more details about what kamailio is supposed to do. This tracker is used only to solve bug reports or track implementation of new features.
