### ISSUE TITLE
update libphonenum

### ISSUE THREAD

**Issue by bpbp-boop** [kamailio/kamailio#2635]
### Description
update libphonenum for the latest metadata please (currently v8.12.18)

### Additional Information
OS is CentOS 8 Stream

```# dnf list installed | grep phone
kamailio-phonenum.x86_64             5.4.3-0.el8.centos                      @kamailio
libphonenumber.x86_64                8.12.11-2.el8                           @kamailio
```

**Comment by sergey-safarov** [comment]
Please check the `master` branch (daily builds) and release `5.4.4` tomorrow.
If not fixed please reopen.

**Comment by bpbp-boop** [comment]
Thank you, used the master branch!
