### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2636]
**core/receive.c:300 - CentOS 7** 
```
CC (gcc) [kamailio]		core/ip_addr.o
CC (gcc) [kamailio]		core/rvalue.o
CC (gcc) [kamailio]		core/receive.o
core/receive.c: In function 'receive_msg':
core/receive.c:300:2: warning: missing braces around initializer [-Wmissing-braces]
  sr_net_info_t netinfo = {0};
  ^
core/receive.c:300:2: warning: (near initialization for 'netinfo.data') [-Wmissing-braces]
CC (gcc) [kamailio]		core/timer_proc.o
CC (gcc) [kamailio]		core/lock_ops.o
CC (gcc) [kamailio]		core/counters.o
```

**Comment by miconda** [comment]
I think this is related to a bug in some old gcc:

  * https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119

It should be ignored, like suggested at:

  * https://stackoverflow.com/a/13758286

I do not plan to go for the non-standard `{{0}}` variant just for this case, the initialization with `{0}` is what C standard specify.

**Comment by sergey-safarov** [comment]
Thanks, @miconda. I will ignore this error in future.
