### ISSUE TITLE
kamctl ul show/xmlrpc ul.lookup not find valid AOR (Kamailio v4.3.1)

### ISSUE THREAD

**Issue by 00Asgaroth00** [kamailio/kamailio#264]
For some registered users the kamctl ul show subscriber@domain does not find the AOR, however in a full listing it shows up, the ul.lookup rpc method has the same issue.

Kamailio version is 4.3.1

For example, here is a full listing:

```
Domain:: location table=1024 records=4 max_slot=1
        AOR:: subscriber1@domain.com
                Contact:: sip:subscriber1@192.168.1.238:32989;alias=212.2.160.202~37476~1;rinstance=5e040b71a89dace0;transport=UDP Q=
                        Expires:: 45
                        Callid:: Q9tQDalSnHzw78gSlpDC6g..
                        Cseq:: 783
                        User-agent:: Z 3.7.30891 r30851
                        Received:: sip:212.2.160.202:37476
                        Path:: <sip:10.7.0.109;lr;received=sip:212.2.160.202:37476>
                        State:: CS_NEW
                        Flags:: 0
                        Cflag:: 64
                        Socket:: udp:10.7.0.175:5060
                        Methods:: 5087
                        Ruid:: uloc-55b11002-2df0-82a2
                        Reg-Id:: 0
                        Last-Keepalive:: 1437721166
                        Last-Modified:: 1437721166
        AOR:: subscriber2@domain.com
                Contact:: sip:subscriber2@172.16.0.110:5060;alias=78.143.152.30~21183~1 Q=
                        Expires:: 107
                        Callid:: 7c5fd25f-c2583f1d63761b4f099e0080f0d14465@172.16.0.110
                        Cseq:: 7
                        User-agent:: BFH_IE_Panasonic_KX-UT133X/01.278 (0080F0D14465)
                        Received:: sip:78.143.152.30:21183
                        Path:: <sip:10.7.0.109;lr;received=sip:78.143.152.30:21183>
                        State:: CS_NEW
                        Flags:: 2
                        Cflag:: 64
                        Methods:: 6815
                        Ruid:: uloc-55b10ff9-1f87-45
                        Reg-Id:: 0
                        Last-Keepalive:: 1437721228
                        Last-Modified:: 1437721228
```

if I lookup subscriber1, then kamctl ul show works:

```
# kamctl ul show subscriber1@domain.com
Contact:: <sip:subscriber1@192.168.1.238:32989;alias=212.2.160.202~37476~1;rinstance=5e040b71a89dace0;transport=UDP>;q=;expires=21;flags=0x0;cflags=0x40;state=0;socket=<udp:10.7.0.175:5060>;methods=0x13DF;received=<sip:212.2.160.202:37476>;user_agent=<Z 3.7.30891 r30851>;path=<<sip:10.7.0.109;lr;received=sip:212.2.160.202:37476>>;reg-id=0
```

However, if I lookup sibscriber2, then it cannot find it:

```
# kamctl ul show subscriber2@domain.com
404 AOR not found
```

I have masked the subscriber information, but if it is of use for you, I can send the actual data directly to you.

**Comment by miconda** [comment]
Does this happen always?

Any other pattern/detail? E.g., the second entry is not show...

**Comment by 00Asgaroth00** [comment]
It always happens, there are a couple subscriber names that I query that respond back with a 404 Not Found.

I will send on an example directly to you as I dont want to expose valid usernames. Hopefully that may show the issue in a little more detail.

**Comment by miconda** [comment]
Can you share the parameters for registrar and usrloc modules? db_url is not important, so you can skip that one.

**Comment by 00Asgaroth00** [comment]
Sure, here they are:

```
modparam("registrar", "method_filtering",  1)
modparam("registrar", "case_sensitive",    1)
modparam("registrar", "append_branches",   0)
modparam("registrar", "use_path",          1)
modparam("registrar", "path_mode",         0)
modparam("registrar", "path_use_received", 1)
modparam("registrar", "path_check_local",  1)
modparam("registrar", "default_expires",   113)
modparam("registrar", "min_expires",       113)
modparam("registrar", "max_expires",       113)
modparam("registrar", "max_contacts",      1)
```

```
modparam("usrloc", "db_mode",              0)
modparam("usrloc", "use_domain",           1)
modparam("usrloc", "timer_interval",       60)
modparam("usrloc", "timer_procs",          4)
modparam("usrloc", "nat_bflag",            NAT_BFLAG)
```

**Comment by miconda** [comment]
The issue is caused by case_sensitive=1, which is in registrar module but the mi/rpc command is in usrloc module. I will try to find a solution for it.

**Comment by 00Asgaroth00** [comment]
Thanks for looking in to it, let me know if you need any more info from me.

**Comment by 00Asgaroth00** [comment]
Hi,

Just a freindly 'bump' to remind you of this issue, please let me know if you need me to provide any more info on this one.

Thanks

**Comment by miconda** [comment]
Hello, thanks for reminding, they are really useful, especially in holidays season.

A short update: somehow made my mind on how to fix it, by propagating the case_sensitive from registrar to the core, and check it from there in usrloc module. My concern is that other places might need this (e.g., presence), but for now I will do a fix for usrloc, then review and decide what to be done overall.

**Comment by 00Asgaroth00** [comment]
Thanks for the update, I'd be happy to test the patch when you have it available.

**Comment by miconda** [comment]
Can you test with master or by backporting the patches 06e36989b2c5332b3ca377ec8098d8f2d953a5b6 , acf0432cafdaa4b464f1069996e46d54ab0c22e4 , e319a22f80d425f39611857fddc1e948e76ebe87 ?

**Comment by 00Asgaroth00** [comment]
I'll try test those patches against 4.3.1 and get back to you in the next day or two, thanks for the patches.

**Comment by 00Asgaroth00** [comment]
Hi,
I did some tests this morning and I still get the "404 AOR not found message" using the "kamctl ul show <AOR>" command, I have not tested the xml-rpc command yet, but I believe they make the same call right?

**Comment by miconda** [comment]
Could be the same code, I haven't had the time to look at mi commands.

However, you can test the rpc command without xmlrpc, simply running the equivalent kamcmd -- don't know it by hard for 'ul show', might be 'ul.show', see 'kamcmd help'.

**Comment by 00Asgaroth00** [comment]
ok, i'll give kamcmd a go shortly

**Comment by 00Asgaroth00** [comment]
Hi, I can confirm that the "kamcmd ul.lookup <table> <AOR>" command does work with this patch, I also tried the curl xmlrpc equivilent call to ul.lookup and it also works now. 

Just to re-iterate, the kamctl ul show <AOR> does not work at the moment.

Thanks for you time looking into this so far.

**Comment by miconda** [comment]
Just pushed a patch for mi commands (a10d8b133edef697ec3bd40e5babd76dc881b2cb). Reopen if the issue is still there.
