### ISSUE TITLE
Issue with new memory-only presence feature in 5.4.3

### ISSUE THREAD

**Issue by jmordica** [kamailio/kamailio#2642]
### Description

I've been trying the new in-memory only presence feature in 5.4.x but have run into an issue:
```
ERROR: presence [presence_dmq.c:109]: pres_dmq_init_proc(): dmq_worker_init: database not bound
kamailio[8404]: segfault at 0 ip 00007f4f8419c4d7 sp 00007ffd68ef0130 error 4 in presence.so[7f4f8418d000+fe000]
CRITICAL: <core> [core/pass_fd.c:277]: receive_fd(): EOF on 31
ALERT: <core> [main.c:777]: handle_sigs(): child process 8411 exited by a signal 11
```

I have this set `modparam("presence", "publ_cache", 2)` but had to comment it out in order to prevent kamailio from crashing. I have reverted back to using mysql for storing presentity records for now.

#### Reproduction

Starting kamailio with these mod params can re-produce the issue.
```
#!ifdef WITH_PRESENCE
# ----- presence params -----
modparam("presence", "db_url", DBURL)
modparam("presence", "server_address", "sip:EXTERNAL_LISTEN_IP:EXTERNAL_UDP_PORT")
modparam("presence", "subs_db_mode", 0)
modparam("presence", "publ_cache", 2)
modparam("presence", "clean_period", 40)
modparam("presence", "max_expires", 3600010)
modparam("presence", "enable_dmq", 1)

# ----- presence_xml params -----
modparam("presence_xml", "db_url", DBURL)
modparam("presence_xml", "force_active", 1)

# ----- presence_dialoginfo params -----
modparam("presence_dialoginfo", "force_dummy_dialog", 1)
#!endif
```

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.3 (x86_64/linux) e19ae3
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: e19ae3 
compiled on 18:17:25 Dec 14 2020 with gcc 4.8.5
```

* **Operating System**:

```
CentOS 7 - Linux hostname 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
It looks like a crash happening on shutdown, because the log message from pres_dmq_init_proc() is preventing kamailio to start. You can try to get a core dump, you need to start as a root and enable core dumping -- some guidelines at:

  * https://www.kamailio.org/wiki/tutorials/troubleshooting/coredumpfile

Then attach here the output for `bt full`.

It seems that enabling dmq for the module requires database, can you try with:

```
modparam("presence", "enable_dmq", 0)
```

**Comment by jmordica** [comment]
Commenting out `modparam("presence", "enable_dmq", 0)` allows the memory-only presence module to function properly and not crash/lock.

I don't actually need the dmq to work for presence module so that's ok for me but if you need additional testing I can try to help out.

**Comment by jmordica** [comment]
So I was kind of wrong here. Kamailio runs ok with memory-only presence as long as there are only a handful of subscriptions happening. I noticed that running memory-only presence with `modparam("presence", "enable_dmq", 0)` kamailio will not complain about the originally posted issue but will still crash with this kernel error in the logs:
```
kamailio[13043]: segfault at 0 ip 00007f9f75d624d7 sp 00007ffd11cf7ee0 error 4 in presence.so[7f9f75d53000+fe000]
```

Do you still need a coredump to go further or is this enough info?

**Comment by miconda** [comment]
Yes, get the core dump file and then grab the output of `bt full` with gdb.

**Comment by jmordica** [comment]
Actually since this was on a production machine and the issue relies on lots of subscription traffic I haven’t had time to reproduce it outside of a production environment. In order to let it crash id have to put the traffic back on the kamailio node and let it crash. I’ll have to pick a night soon and do this.

**Comment by miconda** [comment]
@jmordica: ok, I understand. I just pushed a commit to fix the originally reported issue, related to db initialization for dmq worker.

The second one does not seem related, therefore I think it is better to open a new issue for that case, when you are going to catch it again. I am closing this one.
