### ISSUE TITLE
unsupported sip invite request-uri format

### ISSUE THREAD

**Issue by lglhust** [kamailio/kamailio#2646]
In sip register:  Request-URI: sip:ims.mnc001.mcc460.3gppnetwork.org  ,  sip register is ok. 
In sip invite:    Request-URI: tel:460010120073501;phone-context=ims.mnc001.mcc460.3gppnetwork.org,   return 478 Unresolvable destination . 

I saw issue #2287 and #1173 . #2287 deals with register, and  #1173 has no result.
I want to know how to support such  RURI in sip invite,  does it need a patch in code ? If so , where and how to modified it .
Thanks a lot.

**Comment by henningw** [comment]
Kamailio will return 478 if it can not resolve the destination e.g. by DNS. Please check your routing script that you end up with a proper request URI that contains a hostname/domain part (or set $du etc..) that Kamailio can route the request accordingly.

Please discuss the details of your issue on the sr-users list, as the issues are used for tracking issues in the code or more concrete feature requests.

**Comment by lglhust** [comment]
Thanks a lot.
In sip register: Request-URI: sip:ims.mnc001.mcc310.3gppnetwork.org , sip register is ok.In sip invite: Request-URI: tel:310010120073501;phone-context=ims.mnc001.mcc310.3gppnetwork.org, return 478 Unresolvable destination .Should i modified kamailio.cfg such as bellows ??? I don't know how modified the kamailio.cfg .if (is_method("INVITE")) {$ru = "sip:ims.mnc008.mcc460.3gppnetwork.org"; # rewrite the "Request-URI"$du= "sip:ims.mnc008.mcc310.3gppnetwork.org"; }
----- 原始邮件 -----
发件人：Henning Westerholt <notifications@github.com>
收件人：kamailio/kamailio <kamailio@noreply.github.com>
抄送人：lglhust <lgl_hust@sina.com>,  Author <author@noreply.github.com>
主题：Re: [kamailio/kamailio] unsupported sip invite request-uri format (#2646)
日期：2021年02月23日 16点02分


Kamailio will return 478 if it can not resolve the destination e.g. by DNS. Please check your routing script that you end up with a proper request URI that contains a hostname/domain part (or set $du etc..) that Kamailio can route the request accordingly.
Please discuss the details of your issue on the sr-users list, as the issues are used for tracking issues in the code or more concrete feature requests.
