### ISSUE TITLE
KEMI paython3 Error

### ISSUE THREAD

**Issue by dave-greeko** [kamailio/kamailio#2671]
Hello All,
I am able to successfully make a call through Kamailio with no issues but I am getting 2 errors through KEMI paython3.

`SystemError: <built-in function t_relay> returned a result with an error set`
`AttributeError: 'kamailio' object has no attribute 'ksr_onsend_route'`

I am running Debian 10 with python 3.7.3. 
Please find attached all supporting logs & configs

**Your help is extremely appreciated!**
Dave,

[log_level_warning.txt](https://github.com/kamailio/kamailio/files/6120269/log_level_warning.txt)
[log_level_debug.txt](https://github.com/kamailio/kamailio/files/6120268/log_level_debug.txt)
[kamailio_version.txt](https://github.com/kamailio/kamailio/files/6120267/kamailio_version.txt)
[kamailio.cfg.txt](https://github.com/kamailio/kamailio/files/6120277/kamailio.cfg.txt)
[kamailio.py.txt](https://github.com/kamailio/kamailio/files/6120279/kamailio.py.txt)

**Comment by miconda** [comment]
The bug tracker is for reporting issues in the C code, your logs indicate it is a configuration file issue.

In short: either define the method ksr_onsend_route() or see the core cookbook for kemi related parameters. For more discussions, write email to sr-users@lists.kamailio.org, which is the right place to discuss about how to configure and use kamailio.

**Comment by dave-greeko** [comment]
Thank you so much Daniel for your feedback and valuable time. Your suggestion fixed both issues by explicitly adding:
`kemi.onsend_route_callback=""`
to the kamailio.cfg file without doing anything to the python script.

Thank you so much again!
Dave,
