### ISSUE TITLE
[Question] About softphone for VoLTE

### ISSUE THREAD

**Issue by s5uishida** [kamailio/kamailio#2673]
Hi all,

I have one question.

What softphones can I use when trying VoLTE (not VoIP) with Kamailio? I would like to verify VoLTE of private LTE with Open5GS and Kamailio.

I'm sorry to ask you a question without much understanding of Kamailio, VoIP and VoLTE.

Thank you very much in advance.

--Shigeru

**Comment by miconda** [comment]
The issue tracker is for reporting bugs in the C code of Kamailio. If you have questions about how to use Kamailio, write to sr-users@lists.kamailio.org mailing list.
