### ISSUE TITLE
kamailio register over time change failure

### ISSUE THREAD

**Issue by MEGNXIANGING** [kamailio/kamailio#2688]
### Description

My English is not very good, please have a look patiently,sorry
In the useing FreeSwitch Press machine  register to kamailio ,at over time change failure

![image-20210324115027523](C:\Users\guozhengming\AppData\Roaming\Typora\typora-user-images\image-20210324115027523.png)
- 

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by MEGNXIANGING** [comment]
[https://www.yuque.com/docs/share/59c445c3-31d9-46f6-bd1e-fd9556f1c531?# 《kamailio抓包图》](url)

**Comment by miconda** [comment]
If you have questions about how to configure/use kamailio, write to sr-users@lists.kamailio.org mailing list. This tracker is only for reporting bugs in the c code, with the appropriate details as described in the template.
