### ISSUE TITLE
Kamailio 5.2 /  ims_registrar_scscf's  NOTIFY message on registration

### ISSUE THREAD

**Issue by ErhanOnur** [kamailio/kamailio#2692]
Hi 

When I register to my IMS core (Kamailio version 5.2),  ims_registrar_scscf modul sends notification with XML body showing all contacts with expires "0".

I noticed that , in ims_registrar_scscf module,  the notify_subscribers function is as shown below:

```
int notify_subscribers(impurecord_t* impurecord, str *explit_dereg_contact, int num_explit_dereg_contact) {
    event_reg(0, impurecord, IMS_REGISTRAR_CONTACT_UNREGISTERED, 0, 0, explit_dereg_contact, num_explit_dereg_contact);

    return 0;
}
```

IMS_REGISTRAR_CONTACT_UNREGISTERED parameter is hardcoded.

I  noticed that in upper version of Kamailio this changed like that:

```
int notify_subscribers(impurecord_t* impurecord, ucontact_t* contact, str *explit_dereg_contact, int num_explit_dereg_contact, int event_type) {
    event_reg(0, impurecord, contact, event_type, 0, 0, 0, explit_dereg_contact, num_explit_dereg_contact);

    return 0;
}

```

Also noticed that in upper version of Kamailio notify_subscribers is only called on de-registration.  But in version 5.2 it is called on registration and re-registration also. (This leads strange cases)

Could you please advise on this issue?

Best regards
Erhan

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[stack@ims-test2 ~]$ /usr/local/sbin/kamailio -v
version: kamailio 5.2.0 (x86_64/linux) 40c16b
```

* **Operating System**:

```
[stack@ims-test2 ~]$ uname -a
Linux ims-test2.novalocal 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by miconda** [comment]
Kamailio 5.2.x is out of maintenance, here you have to report bugs for maintained versions, currently being 5.3.x and 5.4.x.

If you need assistance with using Kamailio, you have to write to sr-users@lists.kamailio.org mailing list.
