### ISSUE TITLE
siptrace: duplicate_uri with multiple values

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2693]
### Description

As admin, I want check TLS encrypted call signaling on local Kamailio.
To do this I can use [this instruction](https://voipembedded.wordpress.com/2021/03/22/troubleshooting-kamailio-encrypted-sip-traffic/).
Here used `siptrace` module.
But at the same time, I need to send the same call signaling to the company `Homer` server.
So I need to send a copy of the call signaling in two directions.

Could you add the ability to allow specify multiple values in `duplicate_uri` param like.
```
modparam("siptrace", "duplicate_uri", "<sip:127.0.0.1:9060>,<sip:homer.example.com:9060>")
```

**Comment by ovidiusas** [comment]
In the config, you can make another call to sip_trace and specify there the new destiantion:
`sip_trace("sip:127.0.0.1:9060", "", "t");`
HEP traffic will be sent to the new destination (127.0.0.1:9060) in addition to the default one (sip:homer.example.com:9060).

**Comment by sergey-safarov** [comment]
Thanks, @ovidiusas.
Sure this will help in my use case.

**Comment by miconda** [comment]
@sergey-safarov: is it enough for what you need? Or do you want to keep this as a feature request for a while and see if there is interest to implement it?

**Comment by sergey-safarov** [comment]
I closing this and add the tag `wontfix`.
So this can be easily found in the future using tags `feature-request` and `wontfix`

**Comment by miconda** [comment]
I do not see the reason to add wontfix. I see wontfix tag as a result of a decision not to fix a behaviour because it is intended that way. Here was about whether the proposed solution by ovidiu sas satisfies what you need or not. If someone wants to implement it, there is no problem to add it as a new feature now or in the future.

**Comment by sergey-safarov** [comment]
Maybe we can introduce another label, that will allow easy search feature requests closed but may be useful for implementation in the future?
