### ISSUE TITLE
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]

### ISSUE THREAD

**Issue by hamdanfadi** [kamailio/kamailio#2697]
I'm having this error when I try to run: kazoo-kamailio status

ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]

May I know what is the solution for this error?

**Comment by linuxmaniac** [comment]
The issue tracker is for reporting bugs in the C code of Kamailio. If you have questions about how to use Kamailio, write to sr-users@lists.kamailio.org mailing list.

**Comment by sergey-safarov** [comment]
For RPM dist this fixed at 468ec8f26ff8496bdf62a7bfbbb1b1e2e3452c0f
For any other dist that use systemd you can make similar change.
