### ISSUE TITLE
pua_dialoginfo publishing confirmed for an early call

### ISSUE THREAD

**Issue by nbruning** [kamailio/kamailio#2700]
### Description

When updating from Kamailio 5.2.2 to 5.4.4, we're encountering an issue: the pua_dialoginfo module publishes a `confirmed` state for the dialog, even though it's still ringing.

It turns out this commit introduces the problem since 5.3.0: 4efe19f

So since 5.3.0, the dialog module (i think correctly?) sends out state updates for PRACK dialog updates as `DLGCB_REQ_WITHIN` events. But the `pua_dialoginfo` module seems to see that as a signal to mark the dialog confirmed (see [here](https://github.com/kamailio/kamailio/blob/master/src/modules/pua_dialoginfo/pua_dialoginfo.c#L311)). 

One easy fix would be to simply remove `DLGCB__REQ_WITHIN` from the case list in pua_dialoginfo?

OpenSER [seems to](https://github.com/OpenSIPS/opensips/blob/master/modules/pua_dialoginfo/pua_dialoginfo.c#L353) ditch the `DLGCB_REQ_WITHIN` messages altogether, for specific messages...

#### Reproduction

- Use the pua_dialoginfo module
- Make sure your device uses PRACK
- See that the dialog is confirmed even before you pick up; watch for log lines: `__dialog_sendpublish(): dialog confirmed`

#### Debugging Data

N/A

#### Log Messages

With 5.4.4:

```
2021-04-02T16:49:44.453339+02:00 debug proxy[17964]: DEBUG: pua_dialoginfo [pua_dialoginfo.c:295]: __dialog_sendpublish(): dialog confirmed, from=sip:220@188.166.42.37
```

#### SIP Traffic

Just a regular invite with prack.

### Possible Solutions

See above.

### Additional Information

Reproduced with Kamailio 5.4.4, but probably all versions from 5.3.0 are affected.

**Comment by miconda** [comment]
Thanks for the report! I pushed the patch referenced above in the master branch, can you try it and see if all ok? It will be backported to stable branches.

**Comment by nbruning** [comment]
Yes, I can confirm this patch fixes our problem. Thanks!
