### ISSUE TITLE
volte：401 Unauthorized

### ISSUE THREAD

**Issue by King-Osmond** [kamailio/kamailio#2703]
Hello!

I have a problem about volte.

>  4(4467) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
>  4(4467) NOTICE: <script>: PCSCF REGISTER: 
>  Destination URI: <null>
>  Request URI: sip:ims.mnc007.mcc460.3gppnetwork.org
>  4(4467) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
>  4(4467) NOTICE: <script>: Source IP and Port: (10.45.0.6:5060)
>  Route-URI: 
>  4(4467) NOTICE: <script>: Received IP and Port: (192.168.107.6:5060)
>  4(4467) NOTICE: <script>: Contact header: <sip:460070000000001@10.45.0.6:5060>;+sip.instance="<urn:gsma:imei:86772304-493882-0>";+g.3gpp.accesstype="cellular2";audio;video;+g.3gpp.smsip;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
>  4(4467) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No sec urity-verify parameters found
![1617780139(1)](https://user-images.githubusercontent.com/65008453/113834050-f41b2e80-97bc-11eb-8ebb-c669f2fee210.png)
![1617780742(1)](https://user-images.githubusercontent.com/65008453/113834075-fa110f80-97bc-11eb-951c-9a75283ff69a.png)
![1617781355(1)](https://user-images.githubusercontent.com/65008453/113834098-04330e00-97bd-11eb-8dd3-3ff310df2e7c.png)
[open5gs.tar.gz](https://github.com/kamailio/kamailio/files/6270079/open5gs.tar.gz)

Can you help me see where the problem is？

Thanks!

Tips：About SQN, the SQN is the same at the beginning of the test (Open5GS, FOHSS), but when it is found that the sip registration fails, the SQN is inconsistent.  If this situation is normal? If it is not normal, how to solve it?

open5gs：v2.2.3
kamailio：5.3

**Comment by miconda** [comment]
For questions about using kamailio and configuring it, you have to write to sr-users@lists.kamailio.org mailing list. The issue tracker is only for reporting bugs in the C code.
