### ISSUE TITLE
username based lookup in uac_reg_lookup

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#2714]
### Description

Currently uac_reg_lookup don't have provision to pass the mode parameter but its implement in core fuction:
https://github.com/kamailio/kamailio/blob/951c9ac9adaccc1c35e152593cb3c2e7f6e7af6f/src/modules/uac/uac_reg.c#L1602

This should be imported to kemi as well as cfg function.

### Expected behavior

lookup in uacreg should be supported using username based also, currently uuid based support is only there.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
5.4.5
```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
Function uac_reg_lookup_uri() added with 7cee6518421ed16b715d32a8b2ff6d222eac038b.
