### ISSUE TITLE
TLS Client Verification OpenSSL 1.1.1(P-256) to OpenSSL 1.0.2 (P-521) is failing

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#2716]
### Description
I am connecting two kamailio (5.4.5) using TLS with client cert verification. When one side is OpenSSL 1.1.1 (CentOS 8) + P-256 cert and the other side is OpenSSL 1.0.2 (CentOS 7) + P-521 cert *and* `cipher_list` is set(e.g., `DEFAULT`) on OpenSSL 1.1.1, the ClientHello fails because the only supported curve sent is P-256 (server has P-521).

If OpenSSL 1.1.1 is the TLS Server, the handshake also fails with `Alert Illegal Parameter 47`.

### Troubleshooting

1. If `cipher_list` is *not* set at all in `[client:default]`, then the ClientHello sends 4 supported EC groups and the handshake succeeds.
1. If `cipher_list` is set in `[client:defaut]` (e.g. `DEFAULT` or `ANY`) then the ClientHello sends only 1  supported EC group P-256 (I guess because the client is using a P-256 cert), then the handshake will fail.
1. In the reverse scenario if `cipher_list` is not set in `[server:default]` then the handshake will succeed, otherwise the handshake will fail.

This is so weird because if `cipher_list` is not set. then the value of `DEFAULT` (or maybe `DEFAULT:!KRB51`) is used. But if you explicitly enter that in the `tls.cfg` then the ClientHello is narrowed to only send one Supported Group(P-256). 

#### Reproduction

1. Connect two kamailos one on CentOS 8 sending SIP to one on CentOS 7, enable TLS, with client cert verification. Put a P-256 cert on CentOS 8 and a P-521 cert on CentOS 7.

#### Debugging Data

1. `cipher_list` is not set: TLS ClientHello Supported Groups is  4 groups: secp256r1 secp521r1 secp384r1 secp256k1
2. `cipher_list` is set to `DEFAULT`: TLS ClientHello Supported Groups is  1 group: secp256r1.
 

#### Log Messages

```
ERROR: tls [tls_util.h:42]: tls_err_ret(): TLS accept:error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
```

#### SIP Traffic
NA - couldn't complete TLS handshake so no SIP was transferred.

### Possible Solutions

1. Don't set cipher_list at all; the moment you set cipher_list to anything(`ANY`, `DEFAULT` etc), the ClientHello will narrow the supported groups to P-256 and the server will reject.

I have a thought: does `setup_ecdh()` in `tls_domain.c` behave differently on OpenSSL 1.1.1? Maybe it is forcing the handshake to send only the curve of the client.

### Additional Information

1. kamailio version is 5.4.5
2.  The handshake also fails in the reverse direction: OpenSSL 1.1.1(CentOS 8) + P-256 is TLS server and `cipher_list` is set; OpenSSL 1.0.2(CentOS 7) + P-521 is TLS client. If `cipher_list` is *not set* then the handshake works.
3. If OpenSSL 1.1.1(CentOS 8)+P-256 kamailio is the TLS server, the error can be trigger with 'openssl s_client`

```
    # on a CentOS 7 machine with a P-521 cert and key
    openssl s_client -connect server:5061 -CAfile kamailio-calist.pem -cert kamailio-cert.pem -key kamailio-privkey.pem
```

**Comment by space88man** [comment]
I have done the following test:

In `tls_domain.c`, comment out the usage of a P-256 curve

```C
/*
 * ECDHE is enabled only on OpenSSL 1.0.0e and later.
 * See http://www.openssl.org/news/secadv_20110906.txt
 * for details.
 */
#ifndef OPENSSL_NO_ECDH
static void setup_ecdh(SSL_CTX *ctx)
{
   EC_KEY *ecdh;

   if (SSLeay() < 0x1000005fL) {
      return;
   }

   // ecdh = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
   SSL_CTX_set_options(ctx, SSL_OP_SINGLE_ECDH_USE);
   // SSL_CTX_set_tmp_ecdh(ctx, ecdh);

   // EC_KEY_free(ecdh);
}
#endif
```

In this case everything works as expected; I can set `cipher_list` in both `[server:default]` and `[client:default]` and the TLS handshake will succeed in both directions.

**Comment by space88man** [comment]
I have google'd Python issue which looks the same; it suggests that the initialization in `setup_ecdh` should be diffeerent than 1.1.1.
https://bugs.python.org/issue29697

**Comment by miconda** [comment]
Closing, the related PR was merged and it will be backported.
