### ISSUE TITLE
Default config and options for Kamailio 5.5.0

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#2719]
With several days before releasing v5.5.0, let's see if there is any tuning that should be done to default kamailio.cfg.

Note that the proposals and discussions must focus around current config, if any loaded module should have different values for parameters, if the routing blocks should be adjusted to cope better with common use cases.

This is not for asking refactoring or adding major changes/features. In such cases, the option is to make PR to add to `misc/examples/` (new files or to existing files).

From the discussions done for 5.4.0, the next were considered for the future, however I haven't seen much activity on the community forums related to them during past months, so I am not sure they worth at this moment, but let list them for a starting point:

  * keepalive to be done with usrloc module to get round trip timer, etc
  * dlgs module loaded to see the basic stats about active calls

**Comment by manwe** [comment]
Hi Daniel

In the pike ban I'd add a reason instead of a 1 to the htable key value. Something like

if (!pike_check_req()) {
			xlog("L_ALERT","ALERT: pike blocking $rm from $fu (IP:$si:$sp)\n");
			$sht(ipban=>$si) = "pike";
			exit;
		}

This is because you can ban IP addresses lfor other reasons and it's nice to see what it is. In the default config file only if they key exists is checked so having a 1 or another thing doesn't alter the behaviour.

Another ban reason example I use (copied from Fred Postner I think):

if($au =~ "(\=)|(\-\-)|(')|(\#)|(\%27)|(\%24)" && $au!=$null) {
                        xlog("L_WARNING","AU SQL injection $au from $si:$sp R=$ru\n");
                        $sht(ipban=>$si) = "sql";
                        exit;
                }

**Comment by miconda** [comment]
@manwe - the value itself does not matter in matching banned IPs. The `integer` `1` is chosen for size (4 bytes), any `string` has `char*` (4-bytes), `length` (4 bytes) plus the number of bytes in the value. The default config has a single banning mode and you can set a different value on other cases that you add. I guess you find it useful for checking via RPC, however one can know that 1 is pike, the others are how you set them. You can also change 1 to something else as you prefer, but I think the current version is better for the default config.
