### ISSUE TITLE
CORE_TLS option in 5.4

### ISSUE THREAD

**Issue by drTr0jan** [kamailio/kamailio#2720]
### Description

There's a `CORE_TLS` option in _Makefile.defs_. But Kamailio isn't build with the option. 
https://github.com/kamailio/kamailio/blob/cf105d5af78963759825f5eaf9feb767c047a49c/src/main.c#L104
There is no `core/tls/tls_init.h` for include.

### Additional Information

Kamailio 5.4.5

* **Operating System**:

FreeBSD 12.2

**Comment by miconda** [comment]
At some point tls implementation was part of the core, then it was moved to a dedicated module. Apparently the option for core was left, just in case someone needed/preferred to use it that way. At this moment, probably one would need to take code of tls module and adapt it again to compile inside the core.

Relevant comments from `src/Makefile.defs`:

```
# -DUSE_TLS
#		compiles in tls support, requires -DUSE_TCP. Note: this is only
#		generic support (parsing a.s.o.), it does not include the actual
#		"tls engine". If you really want tls you need also either
#		-DCORE_TLS and a tls/ subdir with the tls code or -DTLS_HOOKS and
#		the tls module loaded.
# -DCORE_TLS
#		compiles tls in-core support. Requires -DUSE_TLS, conflicts
#		-DTLS_HOOKS. Please use make CORE_TLS=1 instead  (it will set all the
#		needed defines automatically and extra libraries needed for linking).
# -DTLS_HOOKS
#		compile tls module support (support for having the "tls engine" in a
#		module). Requires -DUSE_TLS, conflicts -DCORE_TLS.
#		Please use make TLS_HOOKS=1 (or TLS_HOOKS=0 to for disabling) instead
#		of setting -DTLS_HOOKS (it will set all the needed defines
#		automatically)
```

This mode is no longer officially supported by developers, if you want to try it, you are on your own.

I am going to close this issue, there are several other define switches in the core that need to be reviewed and eventually removed.
