### ISSUE TITLE
Setting notifier_processes to 1 or more seems to cause memory leak

### ISSUE THREAD

**Issue by itlevel3** [kamailio/kamailio#2733]
Hello,
We use Kamailio with KAZOO. We have set notifier_processes as follows:

modparam("presence", "notifier_processes", 1)

A value  of 1 or greater seems to be required to avoid race conditions when multiple notify's need to be sent.
We've noticed noticed what seems to be a memory leak in Kamailio process. After several days, Kamailio will crash after consuming all system memory.
I have not found any other reports of this happening to others.
Does this seem familiar to anyone?

**Comment by henningw** [comment]
Thanks for the report.
Please specify the version of Kamailio that you are using ("kamailio -v")

Are you using the "official" kamailio version of some version with kazoo specific patches? If the latter, then you should report this issue to the kazoo vendor.

**Comment by itlevel3** [comment]
Hi Henning,
Sorry about that. Should have been included in my OP. See below.
We are using official Kamailio with mod_kazoo.

[root@proxy01-central ~]# kamailio -v
version: kamailio 5.2.5 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled on 01:14:59 Nov 19 2019 with gcc 7.3.1

**Comment by henningw** [comment]
Thanks. Please update to a maintained version of kamailio, 5.2.x is already end of life. Your bug might be already fixed in a newer version. My suggestion would be to use the latest 5.4.x or 5.5.0 version. Please re-open if the bug is still present there.

**Comment by itlevel3** [comment]
Thanks Henning. Does a memory leak with notifier_processes ring a bell by any chance?
The closest thing I've found seems to be the one below, but I don't know if we use RPC commands. Any suggestions in regards?

commit b97bb77265e7bfc5562a664e8a510692ed68b2f8
Author: Victor Seva <linuxmaniac@torreviejawireless.org>
Date:   Fri Jun 28 17:06:54 2019 +0200

    usrloc: fix memory leak on DB_ONLY mode on RPC commands
