### ISSUE TITLE
mtree: Missing docs of params "pv_dstid", "pv_weight", "pv_count"

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#2750]
The mtree_mod.c file has three pv param settings that is not documented in the README
https://kamailio.org/docs/modules/devel/modules/mtree.html

* pv_dstid
* pv_count
* pv_weight

I see that pv_dstid and pv_weight is set in the code.

I can't really guess what they are, so I can't add docs myself...

**Comment by oej** [comment]
In addition I don't know if this is correct:
mtree_mod.c line 206

```
	if(pv_parse_spec(&count_param, &pv_count) < 0
			|| !(pv_is_w(&pv_weight)))
```
Should pv_weight be used there or pv_count?

**Comment by miconda** [comment]
Hmm, these params seems to be from the initial version of the module, I even forgot about them, although git blames me from back in 2010. I will look into the code and document.

**Comment by oej** [comment]
Sometimes history gets back and starts hunting us...

**Comment by miconda** [comment]
Should be now in master.
