### ISSUE TITLE
evapi: Evapi MAX clients set to 8 can it be made configurable parameter?

### ISSUE THREAD

**Issue by balajee-plivo** [kamailio/kamailio#2762]
### Description
Evapi max client is set to 8 in [evapi module](https://github.com/kamailio/kamailio/blob/master/src/modules/evapi/evapi_mod.c#L56) 
Can this be increased or can be made as configuration parameter?

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
There is already a modparam for it:

  * https://www.kamailio.org/docs/modules/stable/modules/evapi.html#evapi.p.max_clients
