### ISSUE TITLE
db_redis connection broken after idle serveral minutes if redis server with timeout setting

### ISSUE THREAD

**Issue by FredWH** [kamailio/kamailio#2764]
### Description

db_redis connection broken after idle several minutes if redis server with timeout setting

#### Reproduction

1. configure Redis server with timeout 600. (10 minutes)
2. configure Kamailio with db_redis module and usrloc module 
modparam("usrloc", "db_url", "REDIS_CONNECT")
3. at client side, try to register, then close client tool.
4. after idle for 10+ minutes, no any registion, reopen client tool and try to register, <- register failed.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

db_redis [redis_dbase.c:2504]: db_redis_insert(): Failed to fetch type entry: Broken pipe
db_redis [redis_dbase.c:2568]: db_redis_insert(): failed to do the insert
usrloc [ucontact.c:687]: db_insert_ucontact(): inserting contact in db failed 1001 (uloc-60b45e88-1c5d-d)
usrloc [urecord.c:601]: insert_ucontact(): failed to insert in database
registrar [save.c:537]: insert_contacts(): failed to insert contact
sl [sl_funcs.c:414]: sl_reply_error(): stateless error reply used: I'm terribly sorry, server error occurred (1/SL)

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.5.0 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0
PS: 5.4.5 has the same issue.

* **Operating System**:

Debian 10.9
Linux test1 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by miconda** [comment]
Closing, related PR was merged.
