### ISSUE TITLE
uac: allowing sending register for uacreg using rpc command and function

### ISSUE THREAD

**Issue by surendratiwari3** [kamailio/kamailio#2766]
### Description
Right now there is no way that allows users to control sending register packet using rpc command based on l_uuid .

### Expected behavior
There should be an rpc command :
uac.reg_send l_uuid

This command will immediately send re-register if extension already registered or send new registration if its not already registered.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[root@mind-bridge19 modules]# kamailio -v
version: kamailio 5.4.5 (x86_64/linux) 327548
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 327548 
compiled on 13:05:14 May 25 2021 with gcc 4.4.7

```

* **Operating System**:

```
[root@mind-bridge19 modules]# uname -a
Linux mind-bridge19 2.6.32-696.el6.x86_64 #1 SMP Tue Mar 21 19:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by henningw** [comment]
Have you already tried https://kamailio.org/docs/modules/devel/modules/uac.html#uac.f.uac_reg_refresh ?

**Comment by surendratiwari3** [comment]
yeah i check that too using kamcmd uac.reg_refresh s:l_uuid but its reloading from database to kamailio memory but registraton part is missing from it. so we need a rpc that allows us to register on our wish without waiting for timer process to run.
