### ISSUE TITLE
[pv] tr_init_buffers() does malloc but memory is never freed

### ISSUE THREAD

**Issue by andywolk** [kamailio/kamailio#2776]
### Description

tr_init_buffers() does malloc 512kb and this memory is never freed

https://github.com/kamailio/kamailio/blob/master/src/modules/pv/pv_trans.c#L78

Compare with kazoo which does have `kz_tr_clear_buffers()`
https://github.com/kamailio/kamailio/blob/master/src/modules/kazoo/kz_trans.c#L105

Nothing like that in the pv mod.

**Comment by miconda** [comment]
The buffers are allocated once, at startup and reused during runtime many times, till kamailio is stopped. They are per process and, while we have a destroy module callback on shutdown, that's executed only on main process to clean the shared resources. The process private resources as cleaned up when the application exits.

So, it is not a memory leak, if that was your concern.

An as a matter of fact, kazoo module has the function with code to free the buffers, but never executes it:

```
# ag kz_tr_clear_buffers

src/modules/kazoo/kz_trans.h
42:void kz_tr_clear_buffers(void);

src/modules/kazoo/kz_trans.c
105:void kz_tr_clear_buffers(void)
```

If you haven't observed a behaviour that indicates a leak and can provide more details, then this one will be closed.

**Comment by andywolk** [comment]
Hah. `json_tr_clear_buffers(void)` is never called as well

**Comment by miconda** [comment]
Closing it.
