### ISSUE TITLE
[stirshaken] RCD (Rich Call Data) support in STIR/SHAKEN module

### ISSUE THREAD

**Issue by ccppprogrammer** [kamailio/kamailio#2780]
### Description

It would be nice to have RCD (Rich Call Data) support in STIR/SHAKEN module.

**Comment by miconda** [comment]
You have to provide references to IETF specs or the documents describing what is expected to happen.

Then, if no developer commits to implement it in about one month or so, then it will be closed, meaning nobody has interest at this moment in such extension.

Obviously, you can also implement it and make a pull request -- contributions are really appreciated.

**Comment by ccppprogrammer** [comment]
Hello Daniel!
Thanks for your prompt reply as always, greatly appreciated!

First of all I've checked the signalwire's `libstirshaken` library, which the `stirshaken` module is based on and who was the author of the `kamalio` module, and it seems that the library doesn't support `RCD` yet, so need to add `RCD` support to the library first.

I just didn't want to post external links, but if you ask then
* IETF draft: https://datatracker.ietf.org/doc/draft-ietf-stir-passport-rcd/?include_text=1
* a short description of how it works: https://transnexus.com/whitepapers/rich-call-data/

**Comment by miconda** [comment]
In Kamailio we have also `secsipid` module for same purpose, which was even added before stirshaken module, and I maintain it:

   * https://www.kamailio.org/docs/modules/stable/modules/secsipid.html

**Comment by ccppprogrammer** [comment]
I know and have already tested it with `STIR/SHAKEN`, but AFAIK this module doesn't support `RCD` either.
And that's just my preference, but I prefer C libraries from a performance standpoint more than libraries written in Go like secsipidx.

**Comment by miconda** [comment]
For the records, to `secsipid` module I added a generic function to sign any JSON headers and payload:

  * https://www.kamailio.org/docs/modules/devel/modules/secsipid.html#secsipid.f.secsipid_sign

It may help building Identity with RCD.
