### ISSUE TITLE
JSON CEE structured logging

### ISSUE THREAD

**Issue by dpocock** [kamailio/kamailio#2797]
### Description

Kamailio recently added JSON logging support, described on these two pages:
https://www.kamailio.org/w/2020/04/structured-json-logging/
https://www.kamailio.org/wiki/cookbooks/devel/core#log_engine_cli_parameter

Structured logging is particularly useful when:

1. there are multiple applications involved in a call (e.g. Kamailio, Kurento, coTurn, Apache)
2. all the applications create JSON logs using identical field names

I recently made contributions to reSIProcate, GStreamer and Kurento to support the JSON CEE field names.  It would be very easy to replicate in Kamailio.
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/847
https://github.com/Kurento/kurento-media-server/pull/17
https://github.com/resiprocate/resiprocate/commit/d1df9aeb956be79253560fe3628b3f37a4ef94f2

Notice that ```rsyslog``` can receive legacy Syslog events from VoIP hardware, Cisco and Polycom phones and it can convert them to JSON CEE and push them into the document store where they will meet the records from Kamailio.  This is another case where it is really useful if all the JSON from different applications is using CEE.

Here are the JSON CEE field names:

https://cee.mitre.org/language/1.0-beta1/core-profile.html

### Expected behavior

Extend the config setting so that people can request CEE on the command line.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by dpocock** [comment]
Here are some of the commits and filenames relevant to the current implementation:

https://github.com/kamailio/kamailio/search?q=json+log&type=commits

**Comment by henningw** [comment]
As the pull request(s) were merged, i think this issue can be closed. Please re-open if you want to continue to work on this area.
