### ISSUE TITLE
kamailio log socket error

### ISSUE THREAD

**Issue by nihaomatmat** [kamailio/kamailio#2806]
I have some problems。the kamailio version is 5.3.0. My linux version is centos 7. the kamailio log:

```
ERROR: <core> [core/tcp_main.c:3508]: send_fd_queue_run(): send_fd failed on socket 63 , queue entry 1, retries 90, connection 0x7ff46e6b1b60, tcp socket 218, errno=11 (Resource temporarily unavailable)
ERROR: <core> [core/kemi.c:94]: sr_kemi_core_err(): 202->408
CRITICAL: <core> [core/tcp_main.c:4218]: send2child(): tcp child 6, socket 65: queue full, 291 requests queued (total handled 10665748)
```

This problem does not happen every time。When the number of user registrations increases significantly, errors will appear。I tried to set the parameter tcp_children is adjusted to 8, it will not appear frequently, but when the number of user registrations increases to about 5000, errors will still appear. My kamailio.cfg global parameters are set as follows：tls_max_connections=65536,tcp_max_connections=65536,open_max_files=65536。

**Comment by henningw** [comment]
Beside from the usual hint to upgrade your kamailio to at least the latest version of the 5.3.x branch, i would have a look to other limits on the system (like limits of file descriptor and also port limits, e.g. on ulimit).

**Comment by nihaomatmat** [comment]
> Beside from the usual hint to upgrade your kamailio to at least the latest version of the 5.3.x branch, i would have a look to other limits on the system (like limits of file descriptor and also port limits, e.g. on ulimit).

I have adjusted the number of files opened in the system to 65535。unlit -a  open files 65535.What other problems could it be?

**Comment by miconda** [comment]
Do you have any time consuming operation in your configuration file? Like db queries, http requests, dns queries, ...?

If you are not sure, look in the core cookbook for latency related parameters and configure them to get reports on slow actions and db operations. It can be that your processes are stuck in specific tasks and cannot handle the sip traffic -- at this moment I incline to say that's the reason.

Also, it may help to get `kamctl trap` when the errors are printed to see what kamailio processes are doing, there can be some hints on what's going on.
