### ISSUE TITLE
RTPEngine: Async connection/communication between Kamailio and RTPEngine

### ISSUE THREAD

**Issue by mitesht** [kamailio/kamailio#2807]
### Description

Can we have async connection/communication between Kamailio and RTPEngine

#### Actual observed behavior

Currently, if there is a network latency or unstable network between Kamailio and RTPEngine, the Kamailio is keep waiting/polling on RTPEngine. That can be overcome if we have async connection.

-Miteshkumar

**Comment by sergey-safarov** [comment]
Think this question is for the Kamailio mailing list
sr-users@lists.kamailio.org

Please ask via maillist.

**Comment by miconda** [comment]
You may be able to achieve what you look for using async or sworker modules. For further discussions, email to sr-users@lists.kamailio.org as suggested above.

If you want to change the rtpengine code, you are welcome to make a pull request.
