### ISSUE TITLE
make ruxc build optional

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2808]
### Description

I during master compilation I see an error
```
[root@safarov-dell kamailio]# make -C src/modules/ruxc/ 
make: Entering directory '/tmp/kamailio/src/modules/ruxc'
CC (gcc) [M ruxc.so]		ruxc_mod.o
ruxc_mod.c:28:10: fatal error: ruxc.h: No such file or directory
   28 | #include <ruxc.h>
      |          ^~~~~~~~
compilation terminated.
```
I was not able to figure out how to install the required dependency on CentOS dist and Fedora.
Could you make build this module build optional

**Comment by miconda** [comment]
It should be optional. Did you compiled on an exiting clone where you did a git pull/fetch? If yes, the makefile config files where generated before, when you compiled first time. Do a `make pure`, `make include_modules=... cfg`, `make all`, ...

**Comment by sergey-safarov** [comment]
Yes, Daniel.
After cleaning git repo build completed successfully without `ruxc`.
