### ISSUE TITLE
DB_UNIXODBC always reports errors for sql queries with no result set

### ISSUE THREAD

**Issue by kdanderso** [kamailio/kamailio#2810]
### Description

SQL queries that do not return a result set (such as INSERT, DELETE, UPDATE) always report errors when using db_unixodbc.  The query succeeds, but the log indicates a failure.

#### Reproduction

Use db_unixodbc.so for sql queries.
Issue a valid query such as INSERT that is not expected to return a result set.

#### Log Messages

ERROR: db_unixodbc [res.c:52]: db_unixodbc_get_columns(): no columns returned from the query
ERROR: db_unixodbc [res.c:253]: db_unixodbc_convert_result(): getting column names failed
ERROR: db_unixodbc [dbase.c:271]: db_unixodbc_store_result(): failed to convert result
ERROR: <core> [db_query.c:197]: db_do_raw_query(): error while storing result
ERROR: sqlops [sql_api.c:297]: sql_do_query(): cannot do the query [DELETE FROM mytable WHERE id = 1]

### Additional Information

Kamailio Version 5.5.0

This issue was also reported to SR-users, but that user did not open an issue. (See https://lists.kamailio.org/pipermail/sr-users/2018-March/100581.html)

**Comment by miconda** [comment]
Are you using the db_unixodbc with sqlops or the errors show up when using module like acc, usrloc, ... that do INSERT or DELETE from the C code?

**Comment by kdanderso** [comment]
The issue occurs when using sqlops.  Other modules such as usrloc seem to be ok.

Thank you.

**Comment by miconda** [comment]
I pushed a patch to master, referenced above. If you can test and report back the results, then I can backport if all ok.

In case of problems, reopen.

**Comment by kdanderso** [comment]
This patch appears to resolve the issue.  I am not seeing the log errors and the queries I'm using complete successfully.

Thanks.
