### ISSUE TITLE
TLS module missing from 5.5 Debian repository

### ISSUE THREAD

**Issue by LookedPath** [kamailio/kamailio#2816]
### Description

I've installed Kamailio 5.5 from the Debian 10 repository and added the WITH_TLS flag to default config file but Kamailio refuses to start.
Looking at the logs I found out that the tls.so file in the modules folder is missing. I checked the docs and it seems that the package has been compiled with the right flags but I'm no Kamailio expert so I decided to open this issue to have it checked.

#### Log Messages

```
kamailio kamailio: ERROR: <core> [core/sr_module.c:504]: ksr_locate_module(): could not find module <tls> in </usr/lib/x86_64-linux-gnu/kamailio/modules>
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.5.1 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0
```

* **Operating System**:

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux kamailio 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

**Comment by henningw** [comment]
You probably also need to install the kamailio "tls" module debian package, please check that you have done this.

**Comment by miconda** [comment]
If @henningw's comment does not solve it, then email to sr-users@lists.kamailio.org, looks like it is an issue of installation/configuration, not a C code problem -- closing it here.
