### ISSUE TITLE
ruxc connection debugging messages

### ISSUE THREAD

**Issue by nakchak** [kamailio/kamailio#2819]
### Description

Would it be possible to have the debug messages from libruxc entered into the kamailio logs, as thats much more useful than -1 for diagnosing connection failures, as well as the uri of the failing request?

### Expected behavior
Some diagnostic data passed up from libruxc detailing connection failure.

#### Actual observed behavior
`ERROR: ruxc [ruxc_mod.c:151]: ki_ruxc_http_get_helper(): failed to perform http get - retcode: -1 uri: https://someservice.somewhere.com`

**Comment by miconda** [comment]
There is a debug option to print messages to stdout, it is a modparm to ruxc module, kamailio has to be started with logging to terminal, which is not the usual option for production, but can help troublesooting a bit. The plan is to add syslog support in libruxc, to be independent of Kamailio. However, this is better discussed in the ruxc project (https://github.com/miconda/ruxc), what the lib should offer for logging.

Not being related to kamailio code, I am closing this one here -- just open a new issue for the ruxc project if you want to discuss more, beyond syslog support.
