### ISSUE TITLE
kazoo error

### ISSUE THREAD

**Issue by nihaomatmat** [kamailio/kamailio#2833]
ERROR: kazoo [kz_amqp.c:2238]: kz_amqp_send_ex(): Failed to publish -9 : a socket error occurred
ERROR: kazoo [kz_amqp.c:2707]: kz_amqp_publisher_send(): error sending publish to zone : local , connection id : 1, uri : amqp://admin

Recently, I encountered a problem. The connection between kamailio and rabbitmq was interrupted, which caused the queue of MQ to be blocked and the message could not be consumed。
Above is kamailio's error log。

**Comment by miconda** [comment]
For questions about using kamailio and sorting out operational issues, write email to sr-users@lists.kamailio.org mailing list.

If, after discussing on mailing list, it proves to be a problem in the code, then you can open an issue here, but do follow the template and provide all details requested.
