### ISSUE TITLE
NATPING ERROR

### ISSUE THREAD

**Issue by JoelBorrego** [kamailio/kamailio#2835]
we trying to configurate the pcscf.cfg  file  and we the following error

Do you have an idea of the reason of this error?, 

78(12285)ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[NATPING] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=836 a=5 n=route
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[preload_pcscf] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=895 a=16 n=if
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[preload_pcscf] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=894 a=2 n=return
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[NATPING] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=838 a=26 n=sht_iterator_start
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[NATPING] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=848 a=23 n=while
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[NATPING] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=839 a=25 n=sht_iterator_next
78(12285) ERROR: *** cfgtrace:dbg_cfg_trace(): request_route=[NATPING] c=[/etc/kamailio_pcscf/kamailio_pcscf.cfg] l=849 a=25 n=sht_iterator_end

**Comment by henningw** [comment]
Hello, please use the sr-users list mailing list for questions regarding configuration behavior. This are no error log messages, but messages related to the usage of the cfgtrace feature. Just deactivate this feature if you do not like the messages.

**Comment by JoelBorrego** [comment]
Thank u!
