### ISSUE TITLE
OpenSSL 1.1.1 and HSM keys incoming patches

### ISSUE THREAD

**Issue by aalba6675** [kamailio/kamailio#2839]
### Description

To clarify: this only the affects the use of OpenSSL engine private keys; soft(PEM) keys are not affected

When using HSM keys (via OpenSSL engine) the engine and private keys are loaded in the child processes since PKCS#11 modules rarely survive `fork()`.

With master branch/5.5.x branches and calls to `OPENSSL_init_ssl()` in `tls_init.c` the engine linked-list is now initialized in the parent process. Subsequently the technique used in `tls_init.c:660 CONF_modules_load_file()` will fail as each child process attempts to manipulates the &ldquo;shared&rdquo; linked-list. Even if the linked-list manipulation itself is protected by global locks traversing the linked-list will encounter corruption as the nodes are inserted by various siblings. The result is SIGSEGV in one or more child processes.

This issue is filed as a marker; I will be providing patches to change the way HSM private keys are loaded in the child process to avoid linked-list corruption.

### Troubleshooting

- use soft (PEM) keys — no issue as OpenSSL engine is not relevant in this context

#### Reproduction

- configure TLS with OpenSSL engine key(e.g pkcs11 engine with SoftHSM keys)

### Additional Information

Root cause: the function `CONF_modules_load_file()` will configure OpenSSL engines from a OpenSSL configuration file but it also adds each engine to the  global linked-list — really we want this engine to be private to the child not shared at all. 

Unfortunately there is no OpenSSL function to reset the linked-list in the child process. It is initialized once at start-up: the linked-list head/tail pointers are static variables and their (re-)initialization is protected by OpenSSL's `RUN_ONCE` mechanisms, so they cannot be reset after `fork()`.

The workaround I am considering is this: the `dynamic` engine is at the head of the linked-list; obtaining a reference to this engine is always to a new copy, so the dynamic engine is valid in the child process. The (copy of) dynamic engine can then be configured as desired without being added back to the global linked list. This involves not using `CONF_load_modules_file()` but lower level APIs.

**Comment by aalba6675** [comment]
Background:

Our current code running in child:

```C
                ENGINE_load_builtin_engines();
                OPENSSL_load_builtin_modules();
                if (strncmp(tls_engine_settings.engine_config.s, "NONE", 4)) {
                        err = CONF_modules_load_file(tls_engine_settings.engine_config.s, "kamailio", 0);
                        if (!err) {
                                LM_ERR("OpenSSL failed to load ENGINE configuration file: %*s\n", tls_engine_settings.engine_config.len, tls_engine_settings.engine_config.s);
                                goto error;
                        }
                }
```

**Comment by miconda** [comment]
PR was merged.
