### ISSUE TITLE
dispatcher: socket atribute usage for initial OPTIONS

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2853]
### Description

I use TCP sockets to relay calls to backend servers.
Also, I have enabled `tcp_reuse_port` and enabled `socket` attribute in dispatcher settings.
INVITE messages to backend servers are now properly send from port 5060.

### Expected behavior
For all messages are used the same TCP socket and same source port for all messages (including  OPTIONS).

#### Actual observed behavior
But initial OPTIONS (before the first call send) uses a random source port.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

used current c503d2bd31a580138a67f1d4a265ccde5791d271 with small customization.

* **Operating System**:
aarch64
```
[root@sbc-a0 ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

**Comment by miconda** [comment]
Closing because of long time without activity. If anyone wants to work on it, just make a PR.
