### ISSUE TITLE
`rpc dispatcher.add group address  flags` not work 

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#2854]
### Description

kamcmd dispatcher add 1 sip:1.2.3.4  # work

kamcmd dispatcher add 1 sip:1.2.3.4  8 maxload=20 # work

but, kamcmd dispatcher add 1 sip:1.2.3.4 8  # not work

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
 kamailio 5.5.2
```
(paste your output here)
```

* **Operating System**:
Debian10

```
(paste your output here)
```

**Comment by miconda** [comment]
Can you try with master branch or the patch referenced in the commit above?

If works, it will backported.

**Comment by hance2010** [comment]
`kamcmd dispatcher.add 1 sip:1.2.3.4 8` afer <https://github.com/kamailio/kamailio/commit/7894fb470e707622b077d565763c9cfb7c654da5>


ERROR: <core> [core/parser/parse_param.c:517]: parse_param2(): Invalid character, ; expected
ERROR: dispatcher [dispatch.c:440]: pack_dest(): cannot set attributes!
WARNING: dispatcher [dispatch.c:2609]: ds_add_dst(): unable to add destination sip:1.2.3.4 to set 1

**Comment by hance2010** [comment]
it works very welll, thank you very much!
