### ISSUE TITLE
How to get $fU and $tU from MSRP module?

### ISSUE THREAD

**Issue by w415384914** [kamailio/kamailio#2857]
Hello!
I want to get $fU and $tU from event_route[msrp:frame-in] in order to filter out MSRP messages sent by a specific sender and received by a specific receiver, I know I can get message content from $msrp(buf), the message content is like this:

> MSRP 7a57f552155926c0 SEND
> To-Path: msrp://172.18.0.14:6060/9d8da4a34dc2102959e7;tcp msrp://172.18.0.12:5060/msrp-6142fc2b-84-1;tcp msrp://172.18.0.2:34862/2a67b54ae0750b7d82aa;tcp
> From-Path: msrp://172.18.0.14:6060/c71ae3675e114d08216b;tcp msrp://172.18.0.12:5060/msrp-6142fc2b-83-1;tcp msrp://172.18.0.2:34858/8baea7c52ba8755322fd;tcp
> Byte-Range: 1-197/197
> Failure-Report: yes
> Success-Report: yes
> Message-ID: c792c94039b8a969
> Content-Type: message/cpim
> 
> From: <sip:alice@ims.mnc001.mcc001.3gppnetwork.org>
> To: <sip:bob@ims.mnc001.mcc001.3gppnetwork.org>
> DateTime: 2021-09-16T09:23:49.339805+00:00
> 
> MIME-Version: 1.0
> Content-Type: text/plain
> 
> hello
> -------7a57f552155926c0$

I want to get alice and bob from the content below：
> From: <sip:alice@ims.mnc001.mcc001.3gppnetwork.org>
> To: <sip:bob@ims.mnc001.mcc001.3gppnetwork.org>
> DateTime: 2021-09-16T09:23:49.339805+00:00

someone can suggest some method. In other route like request_route we can use $fU and $tU to access them.

Regrads
HANG LI

**Comment by miconda** [comment]
For questions about how to use kamailio and its configuration file, you have to email to sr-users@lists.kamailio.org mailing list.

The tracker here is for reporting bugs in the code.
