### ISSUE TITLE
how to choose 2 different rr heads

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#2861]
### Description

how to choose 2 different rr heads when relay a public call to lan? Thanks!

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio 5.5.1
```

* **Operating System**:

```
debian10
```

**Comment by oej** [comment]
This is a bug tracker, not a support system. Please post your question to the sr-users mailing list to get quick help.
If you've found an actual bug, please don't hesitate to open another issue here. Thanks.
