### ISSUE TITLE
cscf_get_ue_via does not return UE via 

### ISSUE THREAD

**Issue by ErhanOnur** [kamailio/kamailio#2864]
### Description

I put a dispatcher between PCSCF and UE.  When I tried to register,  Pcscf's save function saved dispatcher's via IP and via port  instead of UE's via IP and via port.

When I checked save function of ims_registrar_pcscf module , I saw that cscf_get_ue_via function is used for that. And It gives wrong via value. Instead of giving last via , it gives the first via in the via list.

Here is the function:

https://github.com/kamailio/kamailio/blob/master/src/lib/ims/ims_getters.c

```
/**
 * Looks for the UE Via in First Via header if its a request
 * or in the last if its a response and returns its body
 * @param msg - the SIP message
 * @returns the via of the UE
 */
struct via_body* cscf_get_ue_via(struct sip_msg *msg)
{
	struct via_body *vb=0;

	if (msg->first_line.type==SIP_REQUEST) vb = cscf_get_first_via(msg,0);
	else vb = cscf_get_last_via(msg);

	if (!vb) return 0;

	if (vb->port == 0) vb->port=5060;
	return vb;	
}
```

### Troubleshooting

I corrected the code as below:

```
/**
 * Looks for the UE Via in Last Via header and returns its body
 * @param msg - the SIP message
 * @returns the via of the UE
 */
struct via_body* cscf_get_ue_via(struct sip_msg *msg)
{
	struct via_body *vb=0;

	vb = cscf_get_last_via(msg);

	if (!vb) return 0;

	if (vb->port == 0) vb->port=5060;
	return vb;	
}
```

#### Reproduction

Try to put a dispatcher between PCSCF and UE. save function of ims_registrar_pcscf module saves dispatcher's IP and port as UE's IP and port.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by kamailio-sync** [comment]
Hi,
It's not OK to modify the method in that way. That will cause problems with
standard implementation. As you cat see function returns explicitly the
first via for REQUESTs and the last via for RESPONSEs.
You should extend the method with parameters or modify it in another way.

BR,
Aleksandar Yosifov

**Comment by ErhanOnur** [comment]
Hi Aleksandar,

According to Kamalio naming, top via is the first via, and bottom via header is the last via. 
For each request, UAC puts its via header to the top of the list.  And for each response,  UAC deletes the top via header. 
So the bottom via  (last via) always belongs to the UE's UAC (it doesn't matter if it is Request or Response).
Why we use first Via header to identify the UE?

BR,
Erhan Sendag
