### ISSUE TITLE
dialog: set $rs when failed TCP send

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2867]
### Description

I use TCP transport to relay SIP messages.
When Kamailio cannot connect to another server then Kamailio generates response `408 Request Timeout`.
inside `event_route[dialog:failed]` route block I check error code `$rs` but this value is `null`.
This happens because Kamailio does not able to relay SIP messages and is not able to receive responses.
But `tm` module generates a response `408 Request Timeout` and will be fine to init `$rs` pseudo-variable using tm module response.

### Expected behavior
`$rs` pseudo-variable contains `tm` module response when kamailio does not receive a response from another server.

#### Actual observed behavior
`$rs` pseudo-variable contains `null` value when kamailio does not receive a response from another server.

To check you can use 
```
event_route[dialog:failed]
{
    $var(code_xxx) = $(rs{re.subst,/([0-9])[0-9]{2}/\1xx/});
    xlog("L_INFO", "websocket|log|dialog failed $rs; $var(code_xxx)\n");
}
```
And relay SIP message to host that reachable.

**Comment by henningw** [comment]
Thanks for the report. So you are saying that the $rs is not working for locally generated replies (e.g. the 408) in the dialog:failued route in all cases or only when you use TCP transport?

**Comment by miconda** [comment]
Closing it due to long inactivity time. A PR can be made if someone decides to implement it.
