### ISSUE TITLE
ims_usrloc_pcscf can not read protocol field from mysql DB's location table

### ISSUE THREAD

**Issue by ErhanOnur** [kamailio/kamailio#2871]
### Description

Kamailio's ims_usrloc_pcscf module fetches all contact informations from location table at startup.
I noticed that it fails to fetch protocol information. I checked the function which reads the contact row:

https://github.com/kamailio/kamailio/blob/c3629f877500373028d2c7cdefd976cddda31c15/src/modules/ims_usrloc_pcscf/udomain.c#L831

I saw that it is read the value as INT. Then checked database table and saw that protocol field is CHAR(5).
https://github.com/kamailio/kamailio/blob/master/utils/kamctl/mysql/ims_usrloc_pcscf-create.sql

```
CREATE TABLE `location` (
...
  `protocol` char(5) DEFAULT NULL,
...
);
```

The protocol fields needs to be INT in location table as well. 

This bug leads to other bugs because protocol information is used in aor_hash calculation. 

Best regards
Erhan Sendag

#### Reproduction

Put a record in location table with protocol value as 1.  
Set  ims_usrloc_pcscf module parameter db_mode as 1.
After kamailio startup, on debug log, protocol information will be seen as a big integer value.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

The protocol fields can be defined as INT in location table. 

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by ErhanOnur** [comment]
Hi,

There is one more issue. ims_usrloc_pcscf's  db_insert_pcontact function is not able to write protocol value into database.

https://github.com/kamailio/kamailio/blob/c3629f877500373028d2c7cdefd976cddda31c15/src/modules/ims_usrloc_pcscf/usrloc_db.c#L243

In db_insert_pcontact function, Value array's length is 16, but while inserting, this value is given as 15. So contact's protocol value which is the last item of the array is not being written to the database.

```
int db_insert_pcontact(struct pcontact* _c)
{
....
	db_key_t keys[16] = {
				&domain_col,
				&aor_col,
				&received_col,
				&received_port_col,	&received_proto_col,
				&path_col,		&rinstance_col,
                                &rx_session_id_col,	&reg_state_col,
				&expires_col,		&service_routes_col,
				&socket_col,		&public_ids_col, &host_col, &port_col, &protocol_col
	};
	db_val_t values[16];
...
...
	if (ul_dbf.insert(ul_dbh, keys, values, 15) < 0) {
		LM_ERR("inserting contact in db failed\n");
		return -1;
	}

	return 0;
}
```

**Comment by miconda** [comment]
You can propose changes to the code via pull requests, the ims modules are not used by many developers, so your contribution could help.
