### ISSUE TITLE
Ability to use Publish/subscribe mechanism for N-to-N media forwarding using kamailio

### ISSUE THREAD

**Issue by NaveenKhannaBM** [kamailio/kamailio#2874]
### Description

Recently rtpengine has introduced Publish/subscribe mechanism for N-to-N media forwarding and recording. Is it already on Kamailio?

I have gone through the document or rtpengine module in Kamailio and could not find anything that suggests the feature has been incorporated.

 

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.3 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0
```

* **Operating System**:

```
Linux secondary 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
```

**Comment by rfuchs** [comment]
It's not available in Kamailio as these methods (AFAICT) aren't really well suited to be used in a SIP proxy. A better use case would be from a UA. Do you have a vision of how these methods could be used in a SIP proxy?

**Comment by oej** [comment]
Please use the mailing list for further discussion. Thanks. The issue tracker is for solving problems. The mailing list is a good platform for discussion of new ideas and proposals.

**Comment by NaveenKhannaBM** [comment]
Sure.

Thanks
