### ISSUE TITLE
ims_usrloc_pcscf: new callbacks and some fixes 

### ISSUE THREAD

**Issue by ErhanOnur** [kamailio/kamailio#2882]
### Description

Other modules use ims_usrloc_pcscf's callback calls for following operations:

```
#define PCSCF_CONTACT_INSERT      (1<<0)
#define PCSCF_CONTACT_UPDATE      (1<<1)
#define PCSCF_CONTACT_DELETE      (1<<2)
#define PCSCF_CONTACT_EXPIRE      (1<<3)
```

ims_usrloc_pcscf's register_ulcb  checks if the type is insert then it adds the request to a global linked list. But if it is not then it saves it to contact's data structure's linked list as shown below. 

```
int register_ulcb( struct pcontact *c, int types, ul_cb f, void *param )
{
...
	if ( types==PCSCF_CONTACT_INSERT ) {
		LM_DBG("TODO: check for registering callback before/after init\n");
		/* link it into the proper place... */
		cbp->next = ulcb_list->first;
		ulcb_list->first = cbp;
		ulcb_list->reg_types |= types;
	} else {
		/* link it into pcontact structure */
		cbp->next = c->cbs.first;
		c->cbs.first = cbp;
		c->cbs.reg_types |= types;
	}

	return 1;
}
```

Here you can not add generic DELETE callback

It needs to be like this:

```
int register_ulcb( struct pcontact *c, int types, ul_cb f, void *param )
{
...
	if (c == NULL && types | PCSCF_CONTACT_INSERT ) {
		LM_DBG("TODO: check for registering callback before/after init\n");
		/* link it into the proper place... */
		cbp->next = ulcb_list->first;
		ulcb_list->first = cbp;
		ulcb_list->reg_types |= types;
	} else {
		/* link it into pcontact structure */
		cbp->next = c->cbs.first;
		c->cbs.first = cbp;
		c->cbs.reg_types |= types;
	}

	return 1;
}
```

And I did  fixes for the following lines:

```
	if (exists_ulcb_type(PCSCF_CONTACT_DELETE)) { 
		run_ul_callbacks(PCSCF_CONTACT_DELETE, _c);
	}
```

For example, this code wont work because  exists_ulcb_type function checks ulcb_list->reg_types value but run_ul_callbacks has not relation with this value at all. run_ul_callbacks runs contact's registered callbacks..

Can I send PR for that. I am developping dmq_ims_usrloc_pcscf module. It worked fine.

#### Reproduction

When you develop a new module and if you try to call following code , your program will crash.

```
if(dmq_ul.register_ulcb(NULL,  PCSCF_CONTACT_INSERT | PCSCF_CONTACT_UPDATE | PCSCF_CONTACT_DELETE, dmq_ul_cb_contact,  0) < 0)
```

Because you gave first argument as NULL. But how will I get a callback for any operation on ims_usrloc_pcscf without giving contact? 

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
You are welcome to send pull requests.

We look forward for getting dmq_ims_usrloc_pcscf  in the repo as well, should you decide to share it.

I am closing this one, discussions about the changes can be done on PR when it is made.
