### ISSUE TITLE
Allow setting AMQP-Headers when publishing messages

### ISSUE THREAD

**Issue by mihovilkolaric** [kamailio/kamailio#2895]
### Description
I am using kazoo-module for connecting Kamailio to RabbitMQ and publishing messages to several consumers.

Now I´d like to extend my setup to a more sophisticated routing based on a consistent hash-exchange (https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange), while retaining also existing topology based on routing keys.

This can be achieved by using ["Routing on a Header" (hash-header)](https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange#routing-on-a-header). However, [kazoo_publish](https://kamailio.org/docs/modules/5.0.x/modules/kazoo.html#idp30289164) does not allow setting such header.

### Expected behavior
Please extend publish-functions of the kazoo-module with the possibility to (optionally) supply AMQP-headers.

**Comment by henningw** [comment]
Pull request was merged, close this issue.
