### ISSUE TITLE
Anyone thinking about adding JWT (JSON Web Token) support to Kamailio

### ISSUE THREAD

**Issue by mading087** [kamailio/kamailio#29]
It seems a good idea to support JWT as a new SIP authorization method. Wonder if anyone is interested? Think auth_db would be the best spot to add support for JWT.

**Comment by miconda** [comment]
auth_db is intended for providing the authentication functions with database backend. It is better to write a new module for JWT. Such module can be useful to use in the context of webrtc.

**Comment by kamailio-sync** [comment]
On 12 Jan 2015, at 21:34, mading087 <notifications@github.com> wrote:

> It seems a good idea to support JWT as a new SIP authorization method. Wonder if anyone is interested? Think auth_db would be the best spot to add support for JWT.
> 
Please check the work that is ongoing with OAuth - there is an IETF draft on that.

/O

**Comment by pdunkley** [comment]
I have been considering this for some time.

I think there should be a new auth_jwt module, probably based on auth_ephemeral (which is similar in concept).  For SIP over WebSockets this can then be used to authenticate the client during the WebSocket handshake.

There should be a “Private Claim Name” defined to contain the identity of the calling/registering party.  This can be cached during the WebSocket handshake and then used to valid the To-URI (REGISTER/PUBLISH) and From-URI (other requests without To-tags).  The “Expiration Time Claim” should be cached too.

auth_jwt should contain helper functions for checking URIs and whether the token is still valid - similar to those in auth_ephemeral.

Regards,

Peter

— 
Peter Dunkley
http://www.dunkley.me.uk/ <http://www.dunkley.me.uk/>
http://www.linkedin.com/in/pdunkley <http://www.linkedin.com/in/pdunkley>

**Comment by mading087** [comment]
Thanks for the comments. Think a new module auth_jwt is a better way. Will take a closer look at auth_ephemeral. The two IETF draft I was looking at are http://www.ietf.org/id/draft-ietf-oauth-json-web-token-32.txt <http://www.ietf.org/id/draft-ietf-oauth-json-web-token-32.txt> and http://www.ietf.org/id/draft-ietf-jose-json-web-signature-40.txt <http://www.ietf.org/id/draft-ietf-jose-json-web-signature-40.txt>. OAuth 2.0 is a nice framework to handle auth and issue web tokens. But maybe the first step is to use configured public keys to verify the token and then use info from the token to validate SIP messages. Another thing is that it seems we need a new SIP header to send the JWT token. Cannot find an existing header that is suitable for JWT.

**Comment by mading087** [comment]
Daniel, Peter

I have developed the auth_jwt module, which can parse and validate SIP JSON tokens signed with SHA256 and RSA. Tested it for SIP REGISTER. I'd consider the implementation a preliminary module at this point. I haven't implemented the WebSocket handshake Peter described as our business case is more for SIP apps on mobile devices. 
I'd like to know the process to become a Kamailio developer so I can post the auth_jwt module for review. Hope more experienced Kamailio developers can point out my errors and provide ideas for enhancements.

**Comment by linuxmaniac** [comment]
>I'd like to know the process to become a Kamailio developer so I can post the auth_jwt module for >review. Hope more experienced Kamailio developers can point out my errors and provide ideas for >enhancements.

You just have to fork and send a pull-request to get auth_jwt reviewed. No need to become KD for that.

**Comment by miconda** [comment]
To give more details about the procedure to get a new module and access as developer:
* fork kamailio repository and put your new module inside it (recommended as you are already on github, otherwise we can retrieve the code on sr-dev mailing list)
* make pull request so we can review the module to be sure it follows the rules of the project (e.g., GPLv2 or license compatible with it, coding style is acceptable, exiting functions from core are used instead of a duplicated implementation, the new module has the required xml docbook documentation)
* if all is ok, then you are granted write access to kamailio repository and you can develop and push directly to this repository in the future

If you need other details, write here and we can assist. Looking forward to see the new module!

**Comment by mading087** [comment]
Just came back from Spring break. Thanks for the info. Some questions about module document and management interface. I was not sure if there is a common xml docbook tool, so I just made a text README file. Is this OK? Wonder if there is an xml tool I can use to convert the text file to xml docbook. 
I have read that the Kamailio MI interface is considered deprecated and should be supported only for backwards compatibility. New development should use RPC interface. Haven't written the management interface for the auth_jwt module, as I'm not sure if there are any guidelines on how to develop a RPC interface. Can someone point out such guidelines or an existing module with a good RPC interface implementation. Thanks

**Comment by linuxmaniac** [comment]
old devel guide:
http://www.asipto.com/pub/kamailio-devel-guide/#c10rpc

**Comment by miconda** [comment]
I am not aware of tools converting from text to docbook xml, maybe google can reveal some.

The other way is the usual - write docbook files and then run:
```
make modules-readme modules=modules/auth_jwt
```
You need docbook tools/utils and xsl schemas installed. If not available for you, no problem, we can generate the readme and push to git repository.

Writing in docbook is rather simple, you can easily see the format from other modules -- look into the doc/ subfolder of each module. You need the Makefile from there, updated to reflect the name of your module. The look at the modulename.xml for the base file for the docbook of the module. Besides the author info and some other details, this file includes other files, the most common being modulename_admin.xml .

Thinking of a module that doesn't have large docbook and can be a good starting point: async

Some other notes about docbook files:

  * http://www.kamailio.org/wiki/devel/module-docbook-readme

Regarding the RPC, do you need to add such commands?

Besides the link from Victor, check also the RPC API -- it might not be really up to date (maybe some new stuff missing), but what is there should be still valid: 

  * http://www.kamailio.org/docs/docbooks/4.2.x/rpc_api/rpc_api.html

**Comment by miconda** [comment]
A short note to say that development for 4.3 will be frozen on April 22, next week Wednesday. If you want to get the module in the next major version, make a pull request by that time. Once the code is reviewed and is clean, you will get developer access to maintain the module.

**Comment by mading087** [comment]
Thanks for letting me know. I'll try my best. Have to go through internal
review process to get anything published. Just in case I cannot get this
out in time, we can try the next release. This module will be constantly
changed when we start to get feedback from field trials.

**Comment by mading087** [comment]
Looks like we'll have to wait for the release after 4.3. Cannot get the internal code review through as we're busy developing a redundancy solution at the moment. Thanks

**Comment by oej** [comment]
Any update?

**Comment by mading087** [comment]
Yes, we have made a new auth_jwt module that works with RSA256 tokens. The internal code review and licensing type of things are moving slow. Hope we can post it for review soon.

**Comment by miconda** [comment]
No follow up for more than an year from @mading087 on the JWT module. I am closing this one. If somebody is considering to add a auth jwt module, then it can go ahead and just push a pull request.

**Comment by bwiles-vysk** [comment]
I am writing a JWT module now.  I'll create a pull request when it's ready.

**Comment by ekoome** [comment]
+1

**Comment by poldon** [comment]
I am actually finished writing the JWT module and just need to write up the documentation before I post a pull request.

**Comment by mading087** [comment]
Great. I have developed/tested a JWT module while working in previous company. But I left before the legal review to release the code could be completed. So I cannot release my code but I can help you review and make changes if needed.

**Comment by ValentinOzanne** [comment]
Hi @poldon & @bwiles-vysk  ! I am interested in your pull request status. Could you give a feeback about it ?
Thanks

**Comment by phil-lavin** [comment]
Did the source for this ever get published?

**Comment by mading087** [comment]
I didn’t as I left the company where I developed the code.

**Comment by karimhm** [comment]
OpenSIPS have **[AUTH_JWT](https://opensips.org/docs/modules/3.1.x/auth_jwt.html) module** now if any one is interested.

**Comment by henningw** [comment]
Thanks. There seems to be interest as shown from the individual private implementation, but not enought to actually getting it into the Kamailio repository. If somebody wants to take this up, just let us know.
