### ISSUE TITLE
Uac module , disable registration with l_uuid , value type problem on RPC

### ISSUE THREAD

**Issue by ycaner06** [kamailio/kamailio#290]
Hello;
when i test to uac module , can't disable registration . after long time , i found the problem that rpc gives wrong value or uac module gives wrong value type so it nevers matches where trt to find so it never can disable registration. 
``
file : modules/uac/uac_reg.c 
``
``
function : rpc_uac_reg_update_flag
``
``
line : if(rpc->scan(ctx, "S.S", &attr, &val)<2)
``
rpc scan gives that value is "18446744073622652910"  but must be 85030AXXXX like this.
i tried to change "S.S" value but couldn't be success.

``
kamailio V 4.2.6
``

``
Centos 6.6 2.6.32-431.23.3.el6.x86_64 #1
``

calling command like `` kamcmd uac.reg_disable l_uuid  85030AXXXX `` on shell 

Could you check it.
Thanks.

**Comment by miconda** [comment]
This could be automatic conversion of the kamcmd -- it might detect is an hexa and use it as number.

Can you try with:

```
kamcmd uac.reg_disable l_uuid s:85030AXXXX
```

Note the s: before the value, that will force interpreting it as string.

**Comment by ycaner06** [comment]
Hello Daniel;
it is worked as you wrote it
Thanks.
