### ISSUE TITLE
nats module subscriber issue when connected to more "nats_urls"

### ISSUE THREAD

**Issue by smititelu** [kamailio/kamailio#2916]
### Description, Troubleshooting, Reproduction

I have 3  go nats servers running and the following kamailio config for nats:
```
modparam("nats", "nats_url", "nats://127.0.0.1:4222")
modparam("nats", "nats_url", "nats://127.0.0.2:4222")
modparam("nats", "nats_url", "nats://127.0.0.3:4222")

modparam("nats", "subject_queue_group", "foo:2020")
...

event_route[nats:foo]
{
                xlog("L_ERR", "==============> received $natsData");
}
```
I try to publish using some nats publisher (e.g. nats.c example/libuv-pub.c), and nothing gets printed in event route:
```
./pub -s nats://127.0.0.1:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log NOT printed
./pub -s nats://127.0.0.2:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log NOT printed
``` 

However, if I try to publish on the last server "127.0.0.3", log *is* printed:
```
./pub -s nats://127.0.0.3:4222 -txt "aaaaaaaaaaaa" -count 1 // event route log IS printed
```

I expected to see 1 log message for each of the above publish(es). Found this while implementing and testing #2915 

Thanks,
Stefan

**Comment by smititelu** [comment]
Found in nats.h file, from nats.c git repo:
```
 * By default, #natsConnection_Connect() attempts to connect to a server
 * specified in provided list of servers. If it cannot connect and the list has been
 * fully tried, the function returns an error.
```
So the lib behavior is to connect to **a single server** from the list, not to all servers in the list.

Closing this, as it is expected lib behavior. Will document this in "nats_url" modparam.

Thanks,
Stefan

**Comment by eschmidbauer** [comment]
This sounds like a nice improvement, I submitted a PR to move the connection handling into a new struct. We can extend it into a linked-list by doing something like this:
![image](https://user-images.githubusercontent.com/7139998/141700502-a56de086-7d5d-4b50-91bc-c22695a9773c.png)

I think we should leave the default behavior of relying on libnats to do connection failover based on the server list it is given, and define a "name" on the connection to create simultaneous connections. 
perhaps using something similar to htable like
```
modparam("nats", "nats_url", "nats://127.0.0.1:4222;name=connection1")
modparam("nats", "nats_url", "nats://127.0.0.1:5222;name=connection1")
modparam("nats", "nats_url", "nats://127.0.0.1:6222;name=connection2")
```

This would create two sets of connections.
"connection1" would contain server list of `nats://127.0.0.1:4222` and `nats://127.0.0.1:5222`
"connection2" would contain server list of `nats://127.0.0.1:6222`
We could then reference the connections by name in other modparams or functions.
