### ISSUE TITLE
working with a file.

### ISSUE THREAD

**Issue by ihsinme** [kamailio/kamailio#2924]
Good afternoon.
Do I understand correctly that the file is opened without restricting access rights (0666).

https://github.com/kamailio/kamailio/blob/4e827b30dfc393caf17e2fce28b5eea460aa51f7/src/modules/sipdump/sipdump_write.c#L191

it might be worth limiting them to at least 0644.

thanks for taking the time to answer

**Comment by henningw** [comment]
Thanks for the report. Right now the effective rights are probably defined from the kamailio process umask setting. 
It would be probably a good idea to make it configurable similar to e.g. jsonrpcs module (fifo_mode parameter).

**Comment by miconda** [comment]
Discussions about the behaviour of Kamailio have to be done on mailing list sr-users@lists.kamailio.org . As pointed, it can be controlled in the OS with umask. A pull request can be also proposed to change current code and add new features.
