### ISSUE TITLE
Get log formatting a way to add metadata into it's JSON

### ISSUE THREAD

**Issue by ErvalhouS** [kamailio/kamailio#2927]
We currently can output our logs in a JSON format which gives us the ability to pump that into ELK just fine.

The thing is those logs would be a lot more useful if we were able to inject more context metadata into it, i.e.:

- Request original IP
- Request original User Agent
- Response status code
- Response timing(?)
- Other request/response miscellaneous headers

This would be appliable to get dashboards built for Pike rate limiting and it's blocked IPs, or for mapping out geolocations based on general requests IPs, or even performance monitoring.

**Comment by henningw** [comment]
You should be able to log everything in the Kamailio configuration, have a look to the xlog module. The output should end up in the json as well.
For more general questions how to use and/or configure kamailio, please use our user mailing list. The issue tracker is for reporting issue in the code or pull requests. Thank you.
