### ISSUE TITLE
device keeps deregister

### ISSUE THREAD

**Issue by riccardospeggiorin-centropaghe** [kamailio/kamailio#2929]
I have a Kazoo installation with Kamailio. I have to VM, one with +700 devices regged and the other with +300 devices.
The problem is that the devices registered on the first machine keeps randomly unregistered. I have 3 unregistrations happening every minute.

If I reboot the machine the problem get solve fora couples of days and after that starts again.

What I should check?

**Comment by henningw** [comment]
You can start by checking kamailio log files for error messages, or by doing some SIP traces with ngrep/sngrep.
Please note that the issue tracker is for tracking problems in the code and not for discussing problems using Kamailio. Please contact our users mailing list for this.
