### ISSUE TITLE
add socket activation support

### ISSUE THREAD

**Issue by zabbal** [kamailio/kamailio#293]
Having (optional) support for socket activation in Kamailio would bring several benefits:
- Security: systemd can listen on privileged ports or socket paths and start Kamailio with privileges already dropped.
- Major upgrades or reconfigurations of Kamailio requiring a full restart are possible without having the listening socket(s) ever go away.
- Any service dependent on Kamailio doesn't have to wait for it to finish starting (or start at all).
- We can be absolutely sure that we always bind to existing IP addresses on all desired network interfaces - no race conditions with network bring-up, systemd takes care of that for us.

Here is some useful documentation: 
http://0pointer.de/blog/projects/socket-activation.html
http://0pointer.de/blog/projects/socket-activation2.html

**Comment by sergey-safarov** [comment]
Think that is useful Kamailio enhancement.
Here is example how use systemd activated sockets.
[Example 1](https://github.com/apache/httpd/blob/969e885f2e8707ae7c5330ab24c626f7154e8f8e/server/listen.c#L296-L322)

Then need to get received socket info and map to `listen` directive in kamailio config for advertised IP info.
If no listen directive is provided, then one of option may be applied.
1) use socket as is, without advertised IP info;
2) generate error like "systemd activated sockets not match to listen directives in kamailio config file".

**Comment by sergey-safarov** [comment]
If `sd_listen_fds` returned 0 value, then bind directly to `proto:ip_address:port`

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
