### ISSUE TITLE
RFE app_python3: future EL8 packages switch to Python 3.9

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#2938]
### Description
RHEL8 and rebuilders (Oracle Linux, AlmaLinux, Rocky Linux et al) now include Python 3.9 in base system.

This RFE is for &ge; 5.6.x: can we switch the `app_python3` module to use the Python 3.9 packages - 
no external repos will be required for switch.

This will allow newer Python 3.9 features in the routing script and keep up to date with improvements
in the Python language.

Furthermore Python 3.6 is EoL  on 23 Dec 2021.

I don't propose this for 5.5.x as it may be too intrusive but perhaps the switch could be made on master
in anticipation for 5.6.x.

### Expected behavior
`app_python3` module will now use system Python 3.9 packages instead of Python 3.6 packages

#### Actual observed behavior
`app_python3` module in 5.5.x now uses system Python 3.6.

**Comment by space88man** [comment]
Thought experiment: does the build system allow to build the module twice with Python 3(3.6) the default, and Python 3.9 - then create two packages `app_python3-36` and `app_python3-39` both of which `Provides: app_python3`.

**Comment by miconda** [comment]
The packages are built using the dependencies versions available in the OS, to my knowledge, there is no custom package installed from external libraries. If there is Python 3.9, then that is going to be used when packages are built.

@sergey-safarov - if you see something to fix here for rpm building, reopen.
