### ISSUE TITLE
SQLOPS Module

### ISSUE THREAD

**Issue by iliesh** [kamailio/kamailio#2950]
### Description

By using module 'sqlops' would be nice to pass also the database name as an argument to the function "sql_query" along with the connection name and SQL statement. 
This would be very useful when you have few database hosts and an SQL Proxy which is routing all queries based on the database name, for example:

customer_1 -> db_host_1 -> db_name_c1
customer_2 -> db_host_2 -> db_name_c2

So instead of: 

```
if($var(customer) == "customer_1") {
    sql_query("ca", "SELECT name from demo where id=1", "ra");
} else {
    sql_query("cb","SELECT name from demo where id=1", "ra");
}
```
use just a single connection to the Proxy:

```
sql_query("ca", "$var(db_name)", "SELECT name from demo where id=1", "ra");
```

**Comment by miconda** [comment]
The way database connector modules are designed require the database name to be provided as part of db connection url. There is a generic API that makes it possible to switch from mysql, to postgress, to sqlite or mongodb without changes in modules. sqlops also relies on this internal DB API, although it targets the use with SQL backends.

In other words, making it specific to a use case of SQL proxy may require consistent change of code. Maybe you can leverage here a KEMI module and use extensions of Lua/Python/... to do the connections and queries you want in the script.

**Comment by iliesh** [comment]
Make sense now, Thank you @miconda.
