### ISSUE TITLE
cannot adopt OIDs in KAMAILIO-SIP-COMMON-MIB

### ISSUE THREAD

**Issue by abonela** [kamailio/kamailio#2955]
Please try to fill this template as much as possible for any issue. It helps the developers to troubleshoot the issue.
 we have configured snmp module following https://www.kamailio.org/dokuwiki/doku.php/utils:kamailio-and-snmp

### Description

we could able to poll or snmpwalk most of the OIDs in KAMAILIO-REG-MIB , KAMAILIO-SIP-SERVER-MIB but having issues below from KAMAILIO-SIP-COMMON-MIB
snmpd[358730]: Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatsMethod ::= { kamailioSIPMethodStatsEntry 1 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatsOutbounds ::= { kamailioSIPMethodStatsEntry 2 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatsInbounds ::= { kamailioSIPMethodStatsEntry 3 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatusCodeMethod ::= { kamailioSIPStatusCodesEntry 1 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatusCodeValue ::= { kamailioSIPStatusCodesEntry 2 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatusCodeIns ::= { kamailioSIPStatusCodesEntry 3 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatusCodeOuts ::= { kamailioSIPStatusCodesEntry 4 }
 Cannot adopt OID in KAMAILIO-SIP-COMMON-MIB: kamailioSIPStatusCodeRowStatus ::= { kamailioSIPStatusCodesEntry 5 }

### Troubleshooting
root@host# snmpwalk -v2c -c public localhost .1.3.6.1.4.1.34352.3.1.1.1.4.1.1.2.0
SNMPv2-SMI::enterprises.34352.3.1.1.1.4.1.1.2.0 = No Such Object available on this agent at this OID
root@host# snmpwalk -v2c -c public localhost .1.3.6.1.4.1.34352.3.1.1.1.4.1.1.2
SNMPv2-SMI::enterprises.34352.3.1.1.1.4.1.1.2 = No Such Object available on this agent at this OID
#### Reproduction
using snmpwalk or snmget to any of the above mentioned kamailioSIPStats* OIDs will do

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.5.1 (x86_64/linux) 307af8-dirty
```

* **Operating System**:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by miconda** [comment]
Address your questions about configuration and use of Kamailio to sr-users@lists.kamailio.org mailing list.

This tracker is used for reporting bugs in the C code.
