### ISSUE TITLE
OpenSSL:It(PTHREAD_PROCESS_SHARED) is not initialized, which may cause the Kamailio worker process to block

### ISSUE THREAD

**Issue by chenqingyy** [kamailio/kamailio#2956]
why the process sharing option (PTHREAD_PROCESS_SHARED) was not used for initialization, which might cause the Kamailio worker process to block

**Comment by miconda** [comment]
Questions about stable releases of Kamailio have to be addressed to sr-users@lists.kamailio.org mailing list.

This is not a discussion forum, but a bug tracker.
