### ISSUE TITLE
 Config errors

### ISSUE THREAD

**Issue by SerhiiZahuba** [kamailio/kamailio#2957]
Perhaps I am doing something wrong? New installation, new config file and when starting the server I see an error
1) parse error in config file /usr/local/etc/kamailio/kamailio.cfg, line 165, column 1-5: syntax error

 164 / * LOG Levels: 3 = DBG, 2 = INFO, 1 = NOTICE, 0 = WARN, -1 = ERR, ... * /
 165 debug = DBGLEVEL
 166

2) /usr/local/etc/kamailio/kamailio.cfg, line 34, column 1-9: syntax error

  32 # *** To enable authentication execute:
  33 #mysql
  34 WITH_AUTH

Where can there be an error if this file is downloaded from your server? Please tell me this is driving me crazy.

**Comment by henningw** [comment]
Thanks for the report, can you specify the version you installed and source (from source or packaging)?

**Comment by SerhiiZahuba** [comment]
From source 
git clone --depth 1 --no-single-branch https://github.com/kamailio/kamailio kamailio
git checkout -b 5.5 origin/5.5

I did not find the 5.5 packaging, if there is one, I will install it from the packaging. thanks

**Comment by henningw** [comment]
I can not reproduce it:

henning@app01:~/repositories/5.5/src$ ./kamailio -f ../etc/kamailio.cfg -L modules -Y /tmp/
Listening on
             udp: 127.0.0.1:5060
[..]
Aliases:
             tcp: localhost:5060
             udp: localhost:5060

henning@app01:~/repositories/5.5/src$ ps aux |grep kamailio
henning   599006  0.4  0.3  91408 12828 ?        S    18:34   0:00 ./kamailio -f ../etc/kamailio.cfg -L modules -Y /tmp/
henning   599007  0.0  0.1  91408  4252 ?        S    18:34   0:00 ./kamailio -f ../etc/kamailio.cfg -L modules -Y /tmp/
henning   599008  0.0  0.1  91408  4188 ?        S    18:34   0:00 ./kamailio -f ../etc/kamailio.cfg -L modules -Y /tmp/
[..]

henning@app01:~/repositories/5.5/src$ git status
On branch 5.5
Your branch is up to date with 'origin/5.5'.

You can find packages (e.g. for debian, ubuntu) on deb.kamailio.org

If you have more issues using Kamailio, please write to our sr-users mailing lists for more support. This bug tracker is for reporting bugs in the code, thanks.
