### ISSUE TITLE
Using undefined environmental variables with #!defenv 

### ISSUE THREAD

**Issue by whosgonna** [kamailio/kamailio#2967]
### Description

Currently, an undefined environmental variable with `#!defenv` results in Kamailio failing to start.  The proposal  here that if the environmental variable is not defined, then the macro value would be undefined as well.  For example:

```
!#KAMAILIO
loadmodule "xlog"
loadmodule "pv"

#!defenv FOO

request_route {
    #!ifdef FOO
        xlog("L_INFO","Environmental variable $$FOO is set\n");
    #!else
        xlog("L_WARN","Environmental variable $$FOO is NOT set\n");
    #!endif
    forward();
}
```

Currently this configuration will fail to load if environmental variable is not set.  My proposal is to either allow `#!envdef` to accept an undefined environmental variable and have the preprocessor macro undefined, or to add a new keyword (`#!envdefn` perhaps?) to allow this behavior.

**Comment by whosgonna** [comment]
Proposed changes are in https://github.com/whosgonna/kamailio/tree/iss2967

**Comment by whosgonna** [comment]
As indicated by @miconda, I've refactored the keywords from `defenvn` to `trydefenv` and from `defenvs` to `trydefenvns`.

**Comment by whosgonna** [comment]
@miconda indicated in the Kamailio mailing list that they code for `#!defenvs` would be pushed.  Once that's done, I'll merge to my fork, then submit a PR.

**Comment by miconda** [comment]
PR was merged.
