### ISSUE TITLE
Kamailio with dmq stop processing SIP

### ISSUE THREAD

**Issue by tfspire** [kamailio/kamailio#2974]
### Description
Hi,

I have been doing some load testing on kamailio 5.4.7 running in podman.
 
Kamailio is using dmq to share dialogs and htable with a backup Kamailio also running 5.4.7.

I tested with 100 CPS and during the first minutes all calls are being processed correctly but then all the messages start to be retransmitted. 
Kamailio is not processing any sip messages anymore but still replies to HTTP requests, is still possible to run kamctl/kamcmd commands on it but for example, if running the command "kamcmd dlg.list" nothing happens.

Also, I did a load test with the backup Kamailio turn off so that there is no replication between them, and in that case, I can run the 100 CPS without any issue.

In kamcmd trap file I can see a lot of "<error: Cannot access memory" errors.

In order for Kamailio to start processing again sip,  I need to restart it.

Any extra logs that I can try to collect when the problem happens?

#### Debugging Data

[trap.txt](https://github.com/kamailio/kamailio/files/7705076/trap.txt)

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.4.7 (x86_64/linux) a19fe1
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: a19fe1
compiled on 14:06:57 Dec 13 2021 with gcc 10.2.1
```

* **Operating System**:

```
Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Try with:

  * https://www.kamailio.org/docs/modules/stable/modules/dmq.html#dmq.p.worker_usleep

And if there are problems, then email to sr-users@lists.kamailio.org providing details such as config file and log messages printed in syslog. It may be a config issue. If proves to be a C code bug, an issue with corresponding description can be created.
