### ISSUE TITLE
 RPC command dlg.profile_get_size with per_value response

### ISSUE THREAD

**Issue by dvillaume** [kamailio/kamailio#2976]
Hello, 

I would like to suggest you an implementation of the rpc command dlg.profile_get_size (on a valued profile) that would return a list of values and the number of current dialogs  for any of them .
This could  be usefull if you want to get stats per customer_id/trunks/ips or whatever and don't want to get the whole table but only the size.

Regards,
David

**Comment by miconda** [comment]
Adding the usual note that if no developer commits to implement this feature request in one month time frame, it may be closed. Of course, anyone can send PRs, not only existing devs.

**Comment by miconda** [comment]
Closing due to long time inactivity.
