### ISSUE TITLE
db_redis: cluster support

### ISSUE THREAD

**Issue by Riccardo-78** [kamailio/kamailio#2977]
### Description

At the moment db_redis driver does not support interfacing with a redis cluster. This is a proposal to add support to it.
The db_redis module will get a new module parameter to enable cluster support (with default 0 - disabled):

```
modparam("db_redis", "cluster", 1)
```

The redis url used by other modules needs to specify all nodes in the cluster, and must NOT include redis database number (since it's not supported in cluster mode):

```
#!define DBURL_USRLOC "redis://10.0.1.1:6379,10.0.1.2:6379,10.0.1.3:6379"
```

The implementation is going to use the [hiredis-cluster](https://github.com/Nordix/hiredis-cluster) library (BSD license). If cluster mode is not enabled the module will behave like before, i.e. all calls to redis will use hiredis library directly.

If you find this proposal sensible, I'll start coding it.

Feedback is welcome, of course!

**Comment by miconda** [comment]
Contributions are welcome!

Is `hiredis-cluster` library packaged on main Linux distros (e,g, Debian/Ubuntu and CentOS/RedHat)? If not, probably it is good to use defines to enable this enhancement, in order to be able to still package it as it is now.

**Comment by sergey-safarov** [comment]
This library does not present in RPM dists, checked via Fedora, CentOS.
If community or core devs are interested in Redis cluster support, then I can package `Nordix/hiredis-cluster` into RPM and use it during Kamailio packaging.

**Comment by Riccardo-78** [comment]
Yes, that would be very helpful, I've already created a simple [spec](https://gist.github.com/Riccardo-78/9ec4648d03d1f0fbfbeb767929670c74) file for hiredis-cluster.

**Comment by miconda** [comment]
Related PR was merged a while ago.
