### ISSUE TITLE
How to change language in siremis web interface?

### ISSUE THREAD

**Issue by Mohammadb06** [kamailio/kamailio#2979]
Hello everyone
I’m new in siremis as web interface of kamailio and I immediately need your help,I installed kamailio and siremis and login in siremis web interface,I can work with it but now I have a problem.
I want to change menu language there is an option in(setting->translate->manage languages) add my desired language and click save and i see this error:
Error message: #2, count(): Parameter must be an array or an object that implements Countable
Script name and line number of error: /var/www/siremis-5.3.x/siremis/modules/translation/lib/LangPackCreator.php
![Screenshot from 2021-12-19 12-46-52](https://user-images.githubusercontent.com/84019067/146672269-4734ee62-bccb-4a59-af8d-a6c2926c2ef8.png)

what’s wrong and what should I do to resolve it?
thank you for your help and I am pleased to receive your response

**Comment by miconda** [comment]
The language support was offered by the framework used to build siremis, but not done for siremis.

Anyhow, if you want to report bugs for siremis, use its project tracker:

  * https://github.com/asipto/siremis/issues

If you want to discuss about using siremis with kamailio, use sr-users@lists.kamailio.org mailing list.
