### ISSUE TITLE
Add new parameter to $uac_req

### ISSUE THREAD

**Issue by neimaravila** [kamailio/kamailio#2982]
### Description

If possible, add a new parameter, where you can choose between sending the password in ha1 or plain text.

### Expected behavior

```
route[REGFWD] {
        if(!is_method("REGISTER"))
        {
                return;
        }
        $uac_req(method)="REGISTER";
        $uac_req(auser)=$fU;
        $uac_req(apasswd)="4850730cadc0250e9fa951eae583ace9";
         $uac_req(passtype)="ha1";
         ...
         uac_req_send();
...
}
```

#### Actual observed behavior
It is currently not possible to send the password in ha1 format

### Possible Solutions
Create an additional field.

### Additional Information

version: kamailio 5.5.2 (x86_64/linux) 55e232
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 55e232
compiled on 14:20:31 Aug 25 2021 with gcc 4.8.5

* **Operating System**:

CentOS Linux release 7.9.2009 (Core)
Linux vsphone-proxy-srv1.virtualsistemas.local 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by henningw** [comment]
You are right, its currently possible to do this for the uac registration functionality, but not for $uac_req(..)

**Comment by miconda** [comment]
Pushed a commit to master branch, try it now with:

```
        $uac_req(apasswd)="4850730cadc0250e9fa951eae583ace9";
        $uac_req(flags)=1;
```

If fails, open a new bug report.

**Comment by neimaravila** [comment]
It's OK. Thanks a lot.
