### ISSUE TITLE
cannot use ring_insert_callid when defined log_prefix

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#2989]
### Description

I want to convert 183 messages to 180 using the `ring_insert_callid` function.
This does not work when used `log_prefix`. Generated error like
> siputils [ring.c:300]: conv183(): 183 message got parsed too far!

#### Reproduction

you can start kamailio using config file like
```
log_prefix="{$mt $hdr(CSeq) $ci} "

listen=udp:eth0:5060
loadmodule "xlog.so"
loadmodule "pv.so"
loadmodule "sl.so"
loadmodule "siputils.so"
modparam("siputils", "ring_timeout", 30)

request_route {
  xlog("L_ERR", "Test1: $rc\n");

  if (is_request()) {
    ring_insert_callid();
  }

  $du = "sip:192.168.0.1;tranport=udp";
  forward();
}
```

**Comment by henningw** [comment]
Thanks for the report. So you are saying that it works without setting log_prefix?

**Comment by sergey-safarov** [comment]
That is correct, `ring_insert_callid` works without
```
log_prefix="{$mt $hdr(CSeq) $ci} "
```

**Comment by miconda** [comment]
Looking briefly at the code, it seems that the function was designed to be used before parsing the reply too much, which is done for log prefix before executing config. It is a function I never used and if the git log tracked it properly, it was introduced in a commit by @henningw back in 2008.

You can probably change the reply using functions from textops/textopsx to achieve a similar behaviour, eventually plus htable to track when to do it.

I added a note in the docs of the function, if nobody wants to work on changing the code of the function, then the issue will be closed with a known limitation.

**Comment by henningw** [comment]
Indeed this is pretty old code, i think it was developed before e.g. htable was available. Maybe @smititelu can comment on this if its still in use on their side, maybe it can be removed.

**Comment by sergey-safarov** [comment]
Thanks, Daniel, Henning.
I will test [`change_reply_status`] (https://www.kamailio.org/docs/modules/devel/modules/textopsx.html#textopsx.f.change_reply_status) function and provide feedback.

**Comment by smititelu** [comment]
hi @henningw ! No, we don't need the log_prefix anymore.

Thank you,
Stefan

**Comment by henningw** [comment]
Thanks for the feedback, i have removed the code. As suggested from Daniel, it can be easily be replaced by textops/htable and/or reply routes. Thus this functionality is not needed anymore.

**Comment by miconda** [comment]
@smititelu's comwent was about no longer needing the `log_prefix`, but maybe it was a mistyping and they don't use the `ring_insert_callid`()`, because `log_prefix` is not going to be removed, even if removing `ring_insert_callid()` is going to be reverted..

**Comment by henningw** [comment]
Hi Daniel, yes you are right i missed it. But I think its a typo. But lets wait for the confirmation. The log_prefix will be not removed, for sure :)

**Comment by henningw** [comment]
Just to provide some background, the ring_insert_callid() was added as a legacy feature for 1&1 many years ago, when there was no htable or other flexible textops functions available. But it seems to be never used that often, i only remember a few discussions about it on the list in all the years.

**Comment by smititelu** [comment]
Thank you for the background info. Indeed, we are not using ring_insert_callid() function anymore.

Thanks,
Stefan

**Comment by henningw** [comment]
Thanks for the confirmation
