### ISSUE TITLE
pua : default_expires parameter is not used in code

### ISSUE THREAD

**Issue by adita76** [kamailio/kamailio#2994]
### Description
pua : default_expires parameter is not functionally used in code

It is not used neither in pua module, nor in others pua_* modules.

### Troubleshooting

Its presence is confusing if it does nothing, but it is described in documentation. 

### Possible Solutions

Can it be used as default expires for subscriptions related to pua events ? Otherwise it should be removed.

**Comment by miconda** [comment]
Thanks for reporting! I pushed a commit for it (referenced above). If you can test and tell if works ok, then it can be backported.
