### ISSUE TITLE
add parameter   presence : default_expires 

### ISSUE THREAD

**Issue by adita76** [kamailio/kamailio#2996]
### Description
Similar to pua:default_expires (see #2994), a default expire value should be added for subscriptions.
The default expiration values are now hard coded for presence modules, in presence_*/add_events.c files.

### Expected behavior
Default expiration value that is configurable.

#### Actual observed behavior
Default expiration value is 3600.

### Possible Solutions
Adding a parameter presence : default_expires and use it in all presence_*/add_events.c files.
I can implement this myself.

**Comment by henningw** [comment]
If you can implement it by yourself, you can just go ahead and create a pull request when you have done it. It will be reviewed and then usually applied to the git repository.
