### ISSUE TITLE
Setting rtpengine DTLS flags on specific user agents only?

### ISSUE THREAD

**Issue by devryan** [kamailio/kamailio#3025]
Hello, 

I need to enable DTLS (e.g. add "SDES-off DTLS" to my $var(rtpengine_flags), but only on specific endpoint device types.  So far, on an inbound call, the SDP comes from Asterisk, and once it hits this specific endpoint, if no encryption is enabled, the endpoint rejects the call and I get "488 Not Acceptable Here".  If I statically enable the DTLS options in kamailio, then the endpoint accepts it and the call connects.

I need to do conditional logic in the kam config, so unless there is a way to reinvite a second time, adding DTLS, I am now trying to figure out a way to determine the destination user agent, potentially via the most recent sip registration or contact/location data saved, then based on the user agent that was registered, I can decide to enable or disable DTLS.  Open to any and all ideas on the right way to do this! Thanks! 

Ryan

**Comment by henningw** [comment]
Hello, this is more a question on the usage of Kamailio. Please address this to our "sr-users" list, this is for tracking bugs and feature requests in the code.

Regarding figuring out the registered (b-side) user-agent, have a look to the $ulc variable that can give you access to the user location attributes.
