### ISSUE TITLE
SIP server cannot changes port service

### ISSUE THREAD

**Issue by bayupmail** [kamailio/kamailio#3026]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```
Hello Experts,

please help me to change port service from default 5060 port into other port due to security reason. Since I have change port in kamailio.cfg file, but services cannot fly normally that shown client unable login online (status not online).
![image](https://user-images.githubusercontent.com/76675592/154027407-24ab423b-302b-435e-bad4-5dcb22a5ad3d.png)

Besides, I need to run the kamailio services after install default kamailio, I have not found where procedure found in this installation process. 

Thanks 
Bp

**Comment by miconda** [comment]
Question related to configuration and use of Kamailio have to be addressed to sr-users@list.kamailio.org mailing list. This tracker is for reporting issues in the C code of Kamailio.
