### ISSUE TITLE
Kamailio Activation Failed

### ISSUE THREAD

**Issue by LeoM30** [kamailio/kamailio#3027]
kamailio[20903]: ERROR: <core> [core/tcp_main.c:3101]: tcp_init(): bind(2d, 0x7f7cff0ff610, 16) on xxx.xxx.xx.xx:5060 : Address already in use

#Sudo kamailio status 
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory

Thanks

**Comment by miconda** [comment]
Question related to configuration and use of Kamailio have to be addressed to sr-users@list.kamailio.org mailing list. This tracker is for reporting issues in the C code of Kamailio.
