### ISSUE TITLE
Error when running kamdbctl create

### ISSUE THREAD

**Issue by lcph** [kamailio/kamailio#3055]
When running kamdbctl create, it fails. The error is as show below. Can someone with knowledge please help me solve this.

/usr/share/kamailio/mysql$ kamdbctl create

MySQL password for root: 
-e database engine 'mysql' loaded
-e \E[37;33mINFO: test server charset
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1682 (HY000) at line 1: Native table 'performance_schema'.'session_variables' has the wrong structure
mysql: [Warning] Using a password on the command line interface can be insecure.
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
/usr/sbin/kamdbctl: 117: [: =: unexpected operator
-e \E[37;33mINFO: creating database kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
-e \E[37;31mERROR: Creatin

**Comment by miconda** [comment]
This looks like a dependency or incompatibility issue, not something related to the code.

Write to sr-users@lists.kamailio.org mailing list providing details about your kamailio version and the operating system you are using and maybe there are users running in the same environment and can provide further hints.

Then, if it is something to add to kamdbctl, it will be pushed to the repo.
