### ISSUE TITLE
{param.value,name[, delimiter]}, and delimiter is comma

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#3060]
### Expected behavior

$var(s) = "a=1,b=2,c=3";
$var(s1) = $(var(s){param.value,b,,});   /* 2 */

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio 5.5.4
```

* **Operating System**:

```
debian11
```

**Comment by miconda** [comment]
Questions about kamailio.cfg have to be sent to sr-users@lists.kamailio.org mailing list.
