### ISSUE TITLE
More than TCP 800 concurrent calls, slows Kamailio (LUA FILE API REQUESTS)

### ISSUE THREAD

**Issue by giofrigo** [kamailio/kamailio#3068]
### Description

Hello Guys I am having this issue where kamailio is receiving requests from SIPp (we are currently testing the platform and doing QA) but if we do more than 800 concurrent calls kamailio starts failing and slowing the requests, The scenario is the following:

I am sending 5000 calls at 100 CPS on TCP and I am having this route in the configuration file:

```
# Handle the calls to api
route[CALL_API] {
    xlog("L_NOTICE"," Call request $var(call_request) method: $rm \n");
    $var(loop_true)=1;
    while ($var(loop_true)) {
        if(!lua_run("call_request","$var(call_request)","$sht(token=>new_token)")) {
            xlog("L_NOTICE", "SCRIPT: failed to execute lua function!\n");
        }
        if ($var(loop_true)){
            sleep("1");
        }
    }
    xlog("L_NOTICE", "SCRIPT: Sucess to execute lua function!\n");
}
```

So I am executing a LUA script for the requests and the API response will tell the destination of the call.

At 800 concurrent calls, I can notice SLOWLINESS in the SIPp testing tool, and then I will start receiving 408 timeouts.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.3.8 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 8.3.0

```

* **Operating System**:

```
BUT KAMAILIO IS RUNNING IN A DOCKER CONTAINER
Linux ip-10-10-0-27.us-west-1.compute.internal 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
This sounds like a load issue or something because I believe there's a time that it's been added every time we hit the backend and wait for the response.

any help will be appreciated

Regards

Gio

**Comment by fredposner** [comment]
Looks like you already requested help for this on the support mailing list, where this support request belongs. We use github for bugs. Thank you.

**Comment by giofrigo** [comment]
oh, sorry about that, thanks for the fast response Fred, I think I should be receiving an email from the support mailing list if someone responds to my post, right? Sorry, this is my first post 

thanks
