### ISSUE TITLE
When using t_relay to convert sip message udp to tcp, the source port changes 

### ISSUE THREAD

**Issue by buzhaodi** [kamailio/kamailio#3069]
My cfg file is written like this ：
$du = "sip:"+$rd+":"+$rp+";transport=tcp";
![image](https://user-images.githubusercontent.com/16113837/160795856-945514d5-b36b-4b1a-95a1-41d60bf0de7a.png)

when i use 
$du = "sip:"+$rd+":"+$rp+";transport=udp";
the sip message will be normal 
![image](https://user-images.githubusercontent.com/16113837/160796099-0d498eb2-e6a8-4703-9f4a-0e7d9b069bef.png)
excuse me, can you tell me the reason ?

**Comment by miconda** [comment]
This is a question about how tcp is designed and the OS/kernel deals with them, what config options could help eventually, but not a bug in kamailio code. Therefore you have to address this questions to community mailing list sr-users@lists.kamailio.org .
