### ISSUE TITLE
Compilation warning with gcc-12

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#3073]
When building for Fedora 36 with gcc-12.0.1:
```
Makefile.defs:1683: You are using an old and unsupported gcc version (12.0.1), compile at your own risk!
```

**Comment by henningw** [comment]
Thanks for the report, could you please try with the commit references above and report back if it fixes the issue?

**Comment by henningw** [comment]
Close this issue, please re-open if the problem still happens for you.

**Comment by amessina** [comment]
> Close this issue, please re-open if the problem still happens for you.
Sorry for the delay on feedback... just backported to the 5.5 branch (on which I'm building) and your fix works.  Thanks @henningw!
