### ISSUE TITLE
Does Kamailio process each SIP message in a separate process?

### ISSUE THREAD

**Issue by kingluo** [kamailio/kamailio#3075]
I check the codes and it seems that in `udp_rcv_loop()`, each incoming message got processed in the same process, so may it get blocked by some module function? For example, when the script calls `rtpengine_manage()`, it opens a new socket, sends a message, and receives the reply in blocking way, then it blocks the whole `udp_rcv_loop()`. Is it the expected design goal? why not consider new process or threading?

**Comment by henningw** [comment]
Kamailio uses a multi-process model. So there are a group of UDP receiver who all process SIP messages from UDP. Each individual process can block during processing, but as there are several of them, the server will continue to process traffic.
Please contact the developer list (sr-dev) for further questions, the tracker is for tracking bugs and enhancements.
