### ISSUE TITLE
LCR function from_gw

### ISSUE THREAD

**Issue by Antoineb2s** [kamailio/kamailio#3077]
Hi,

Kamailio 5.5.4 from deb packages

I tried to use the lcr function from_gw(lcr_id[, ip_addr, proto])

I've declared several gws with different lcr_id 

Unfortunately from_gw doesn't work with lcr_ids > 1 

For example : 
if (from_gw(2,$si,1)) {
....
}
...

ki_from_gw(): invalid lcr_id parameter value 2

**Comment by kamailio-sync** [comment]
Wrong list, use sr-users for questions.

-- Juha
