### ISSUE TITLE
Kamailio tries to parse HTTP replies as SIP ?

### ISSUE THREAD

**Issue by sigxcpu76** [kamailio/kamailio#3081]
### Description

This is a longstanding error when using websockets or the HTTP client (this one is a bit newer, didn't see it for long).
Searching the net has led me here: https://lists.kamailio.org/pipermail/sr-users/2018-January/099881.html
It looks like Kamailio cannot parse HTTP responses, but that message is ambigous. Why would it try to parse them in the first place?

```
32(203) ERROR: <core> [core/parser/msg_parser.c:748]: parse_msg(): ERROR: parse_msg: message=<HTTP/1.1 100 Continue
```

```
47(89) ERROR: <core> [core/parser/msg_parser.c:681]: parse_msg(): ERROR: parse_msg: message=<HTTP/1.1 101 Switching Protocols
```

### Troubleshooting

Except confirming that the messages are legit, there is nothing else that I can do.

#### Reproduction

The first error is generated by making HTTP requests using the HTTP client embedded in Kamailio.
The second error happens on each WebRTC call served by Kamailio.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

HTTP responses should not go through the core message parser. Not sure if this can be described as a "solution".

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

For the 100 parsing error. The used HTTP clients are `http_client` and `http_async_client` modules.

```
# kamailio -v
version: kamailio 5.5.4 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0
```

For the 101 parsing error. Kamailio is a WebRTC server for `sipML5` library.

```
# kamailio -v
version: kamailio 5.4.4 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0

```

* **Operating System**:

```
# uname -a
Linux gke-dev-1-sbc-out-dbbddabc-amiw 5.4.0-1054-gke #57-Ubuntu SMP Fri Oct 1 03:16:03 UTC 2021 x86_64 GNU/Linux
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

```

**Comment by miconda** [comment]
If you use modules that re/parse the replies sent by kamailio (e.g., topology hiding), you may need to set:

  * https://www.kamailio.org/wiki/cookbooks/5.5.x/core#http_reply_parse

Being a matter of your config, in case you need to discuss further, email to sr-users@lists.kamailio.org to get assistance from community.
