### ISSUE TITLE
Failing Audio stream on Kamailio+webrtc with integration to asterisk server.

### ISSUE THREAD

**Issue by kelvinpressone** [kamailio/kamailio#3105]
Summary:

We have a kamailio server as our sip proxy server, sip firewall with websocket and RTP engine configured on it (the Kamailio Server). But we experience one way audio, no audio, hang up after 30s, when we try making calls between internal extensions (eg extension 100 to call extension 105) and external calls (eg extension 100 to call mobile number 09056925668) as well. The call flow is as:

Webrtc client<------->Kamailio1+rtpengine<-----Asterisk+rtpengine---->Kamailio2<-------->Telco Provider

The asterisk communication between all three boxes is via local IP (All ports open between them). The Kamailio 1 box where we have our sip registration cache, has rtp ports and wss port open on the internet. 

Asterisk 18.9.0
Kamailio 5.5.3 + RTPengine 10.4.0.0
Debian 11 bullseye

Kindly see attached below a diagram depicting the voip network flow and also attached are logs files for the webrtc client and server side.

![MrOpee](https://user-images.githubusercontent.com/105465203/168183786-c10a822b-402b-4666-be10-b2bc5ad98e85.png)
[ServersideWebrtc-external2.txt](https://github.com/kamailio/kamailio/files/8683103/ServersideWebrtc-external2.txt)
[Clientside(webrtc2external)__III.txt](https://github.com/kamailio/kamailio/files/8683104/Clientside.webrtc2external.__III.txt)

Thank you.

@rfuchs @doublec @ibc @fredposner @linuxmaniac @miconda

**Comment by miconda** [comment]
Questions about how to use/configure Kamailio or troubleshoot it have to be addressed to sr-users@lists.kamailio.org mailing list. The tracker here is for bugs in the c code.

**Comment by kelvinpressone** [comment]
Thank you @miconda , I will do that now.
