### ISSUE TITLE
Added an equal 0 on TLS test on kemi t_relay_to_proto functions.

### ISSUE THREAD

**Issue by hallthmann** [kamailio/kamailio#3111]
### Description

module: tm
kemi proto relay functions fails on TLS:
- ki_t_relay_to_proto
- ki_t_relay_to_proto_addr

#### Debugging Data

```
```

#### Log Messages

```
13(19) ERROR: {1 1 REGISTER 184193281845942-18001879945554@192.168.1.135} tm [tm.c:2934]: ki_t_relay_to_proto(): bad protocol specified <TLS>
13(19) ERROR: {1 1 REGISTER 184193281845942-18001879945554@192.168.1.135} sl [sl_funcs.c:414]: sl_reply_error(): stateless error reply used: I'm terribly sorry, server error occurred (1/SL)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

It's missing an equal zero (== 0) on TLS test.
Code: tm.c

       if (strncasecmp(sproto->s, "UDP", 3) == 0) { 
            proto = PROTO_UDP;
        } else if (strncasecmp(sproto->s, "TCP", 3) == 0) { 
            proto = PROTO_TCP;
        } else if (strncasecmp(sproto->s, "TLS", 3)) {
            proto = PROTO_TLS;
        } else {
            LM_ERR("bad protocol specified <%s>\n", sproto->s);
            return E_UNSPEC;
        }

Fix:

       if (strncasecmp(sproto->s, "UDP", 3) == 0) { 
            proto = PROTO_UDP;
        } else if (strncasecmp(sproto->s, "TCP", 3) == 0) { 
            proto = PROTO_TCP;
        } else if (strncasecmp(sproto->s, "TLS", 3) == 0) {
            proto = PROTO_TLS;
        } else {
            LM_ERR("bad protocol specified <%s>\n", sproto->s);
            return E_UNSPEC;
        }

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.5.0 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2
```

* **Operating System**:

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

Linux routersip 4.18.0-348.el8.0.2.x86_64 #1 SMP Sun Nov 14 00:51:12 UTC 2021 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Thanks for the report! Commit 1f7e894f5b293f97dc99e1b7e5d06159f91a96f7 was pushed and it will be backported.

**Comment by hallthmann** [comment]
Thanks!
