### ISSUE TITLE
Kamailio 5.5.4 siputils doesn't validate long Austrian numbers as valid e164

### ISSUE THREAD

**Issue by LookedPath** [kamailio/kamailio#3117]
### Description

When using the [is_e164 function](https://kamailio.org/docs/modules/5.5.x/modules/siputils.html#siputils.f.is_e164) on a long Austrian number it doesn't seem to return true even if it's in e164 format.

#### Reproduction

The number in question, with some digits obfuscated for privacy, is +4322367108xxxxxx.
I can confirm that the number exists and is a valid one.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.5.4 (x86_64/linux)
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 10.2.1
```

* **Operating System**:

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye


Linux kamailio-primary 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

```

**Comment by miconda** [comment]
For future releases, there is now a mod param to specify the max len for e164 numbers -- commit referenced above.

**Comment by kamailio-sync** [comment]
Does it have more than 15 digits?

https://en.m.wikipedia.org/wiki/E.164
