### ISSUE TITLE
Add file support to user blocklist for feeding caller numbers list

### ISSUE THREAD

**Issue by soroshsabz** [kamailio/kamailio#3132]
ITNOA

### Description

I think for non-db deployment of Kamailio it is very useful to add support static data (like another configurations) for caller numbers list in user blocklist module. because if we do not have this feature we cannot use this module in non-db deployment of Kamailio.

### Expected behavior

We have a configuration files (like dispatcher file) that contains below information in format of space separated list (like dispatcher file format)

```
+----+----------------+-------------+-----------+-----------+
| id | username       | domain      | prefix    | whitelist |
+----+----------------+-------------+-----------+-----------+
| 23 | 49721123456788 |             | 1234      |         0 |
| 22 | 49721123456788 |             | 123456788 |         1 |
| 21 | 49721123456789 |             | 12345     |         0 |
| 20 | 494675231      |             | 499034133 |         1 |
| 19 | 494675231      | test        | 499034132 |         0 |
| 18 | 494675453      | test.domain | 49901     |         0 |
| 17 | 494675454      |             | 49900     |         0 |
+----+----------------+-------------+-----------+-----------+
```

and user blocklist module read this file and load it, and apply this data for blocking call

**Comment by miconda** [comment]
There is `db_text` module that could be used in this case. If you want to add support for dedicated file with a specific format, then you are welcome to make a PR.
