### ISSUE TITLE
Add 5.6 branch packages for Ubuntu 22.04

### ISSUE THREAD

**Issue by compuwizz** [kamailio/kamailio#3147]
Is it possible to add the 5.6 branch deb/ubuntu packages to https://deb.kamailio.org/ for Ubuntu 22.04? I see Ubuntu 22.04 native repos have kamailio 5.5 in them but I'd like to use 5.6.

**Comment by henningw** [comment]
I think support for jammy/22.04 will be added, sure. Maybe @linuxmaniac can share some information as well, if/when its planned.

**Comment by miconda** [comment]
Specs are in the source tree for devel branch:

```
ls -l pkg/kamailio/deb/jammy/

total 264
-rw-r--r--  1 saturnx  staff    145 Jun 30 19:34 changelog
-rw-r--r--  1 saturnx  staff      2 Jun 30 19:34 compat
...
```

And listed for nightly builds at:

  * https://deb.kamailio.org/

Not sure if there are plans for backporting to stable releases.

**Comment by linuxmaniac** [comment]
We added support for jammy in the infrastructure at https://github.com/sipwise/kamailio-deb-jenkins/commit/db92d02fae7e1c1d9d8a0d5d36edea4357701428 and I added support for jammy in trunk with https://github.com/sipwise/kamailio-deb-jenkins/commit/ddcc65bf579bd7b910d7b3a7a507bc2e9f9a21c3 and https://github.com/kamailio/kamailio/commit/ecbe90524165cf2fd8081ec5fe81d674f7a3334a

Sadly we are having an issue [0] and we are working on it.

[0] https://kamailio.sipwise.com/job/kamailiodev-nightly-repos/architecture=amd64,distribution=jammy,label=master/2061/console

```
03:34:18 + reprepro -b /srv/repository/kamailiodev-nightly -v --waitforlock 1000 --ignore=wrongdistribution --ignore=uploaders --ignore=surprisingbinary include jammy /var/lib/jenkins/jobs/kamailiodev-nightly-repos/workspace/architecture/amd64/distribution/jammy/label/master/binaries/kamailio_5.7.0~dev0+ubuntu22.04.20220701005455.2245_amd64.changes
03:34:18 Could not find a suitable control.tar file within '/srv/repository/kamailiodev-nightly/pool/main/k/kamailio/kamailio_5.7.0~dev0+ubuntu22.04.20220701005455.2245_amd64.deb'!
```

**Comment by linuxmaniac** [comment]
FTR, the issue is related to our version of reprepro not supporting zstd compression

It was introduced at:
```
reprepro (5.3.0-1.3) experimental; urgency=medium

  * Non-maintainer upload.
  * Add support for Zstd compressed debs. (LP: #1923845)

 -- Dimitri John Ledkov <xnox@ubuntu.com>  Mon, 21 Jun 2021 10:16:53 +0100
 ```

**Comment by henningw** [comment]
Just as a note for other people running into this issue, there are also official Yammy packages for 5.4.4 available
https://packages.ubuntu.com/jammy/kamailio

@linuxmaniac You closed the issue, but there are still no packages for Yammy on deb.kamailio.org available?

**Comment by linuxmaniac** [comment]
yes, nothing really to be done here. We are still missing some infrastructure changes in order to accomplish yammy builds
