### ISSUE TITLE
shm_malloc to align on 16 bytes for large allocations

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#3157]
### Description
This is a future-proofing feature request.

I am creating a module that uses a 3rd party library(wolfSSL), that depending on build flags,
requires alignment of memory blocks to be ~~the same as `malloc`, i.e.,~~ 16 bytes on gcc/AMD64 for certain large structs.

It seems that `shm_malloc` returns memory aligned to 8 bytes.

Since system malloc always returns 16-byte aligned memory(for large allocations) it might be good to match that behaviour in `shm_malloc` in case future kamailio modules use libraries that expect this.

[UPDATE] I modify this issue to apply only to object allocations >= 16 where malloc, jemalloc, and tcmalloc all agree. I.e., the kamailio allocators should align on 16 bytes for size >= 16.

It is common practice for small allocations (< 16) that the allocator may choose
smaller alignments for performance reasons:  [N2293](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2293.htm).

### Expected behavior

`shm_malloc` returns memory aligned on `__alignof__(max_align_t) == 16` when `size`
requested is large (>=16).

#### Actual observed behavior

`shm_malloc` returns blocks aligned on 8-bytes

#### Debugging Data
When allocating `WOLFSSL_CTX` and `WOLFSSL ` structs by tls_wolfssl module they will
have 8 byte and not necessarily 16-byte alignments. This can be viewed by logging the returned pointer values. 

### Possible Solutions

* The custom memory allocators in  WIP `tls_wolfssl/` could try to wrap around `shm_malloc` and align up to 16-bytes
* have a static build of wolfSSL that does not require 16-byte alignment

### Additional Information

The default `./configure` build of wolfSSL has structs that require 16-byte alignment.
wolfSSL has a configure flag `--enable-aligndata=no` that relaxes this requirement.

The current deb package in Debian did not turn off this flag so expects malloc'ed memory to be aligned on 16 bytes.

[Update] How does OpenSIPS handle this issue? OpenSIPS contains a vendored copy of wolfSSL 
(git submodule https://github.com/wolfSSL/wolfssl/tree/95b91d89133a712a3d0f389442924612c103da24) that points to a commit that predates the new aligned data feature.

[Update] SO: &ldquo;Why is malloc 16 byte aligned&rdquo; https://stackoverflow.com/questions/70692795/why-is-malloc-16-byte-aligned
[Update] SO: &ldquo;Why is dynamically allocated memory always 16 bytes aligned&rdquo; https://stackoverflow.com/questions/59098246/why-is-dynamically-allocated-memory-always-16-bytes-aligned

**Comment by space88man** [comment]
The qm allocator has a `ROUNDTO` of `16UL` so naturally provides 16-byte aligned memory.

However the flag `DBG_SR_MEMORY` causes `ROUNDTO` to be reduced to `sizeof(void *)`.

**Comment by miconda** [comment]
I see that's for q_malloc, but f_malloc and tlsf_malloc have `sizeof(void*)` or `2^3`. The memory managers can be selected with -x cli parameter.

Overall I am fine to increase it, but I see there are some comments about constraints with round value and size of some structs, so probably needs some checks to detect when it gets broken. Then some proper testing would be needed to catch eventual side effects.

**Comment by space88man** [comment]
I am closing the issue for now as it is too intrusive to alter the allocators for one module.

One future possiblity is to add a xx_malloc16 xx_realloc16 to explicitly request for 16-byte alignment for each allocator.

* For `tls_wolfssl` I will think of other strategies (bundling perhaps like OPENSIPS)
* wrappers for `ser_*` functions that will internally align to 16: for realloc this costs one `memmove` if the returned array has different alignment from the alternative array
