### ISSUE TITLE
utils module - http_query - Empty first response line

### ISSUE THREAD

**Issue by debackel** [kamailio/kamailio#317]
Hi,
I am using http_query to retrieve content served by an http web server.
Unfortunately, the http server tends to output an empty first line in the response.
As http_query only retrieves the first line, the result of the http_query is empty.
Would it be possible to ignore empty lines in the http response (trim the response)?

Thanks for the response,
Laurent.

**Comment by miconda** [comment]
Implemented in the last master branch.

**Comment by debackel** [comment]
Many thanks!
