### ISSUE TITLE
Socket name ignored when sending to HEP server

### ISSUE THREAD

**Issue by manticode** [kamailio/kamailio#3174]
When **trace_mode** is set to 1, then **send_sock_name** is not used (it uses the unexpected socket listen socket).

However, when **trace_mode** is set to 4, then **send_sock_name** works correctly.

Also, in both cases, **send_sock_addr** works correctly.

```
listen=udp:SIP_IPADDRESS:SIP_PORT
listen=udp:SIPCAPTURE_IPADDRESS:SIP_PORT name "siptrace_socket"
modparam("siptrace", "duplicate_uri", "sip:10.218.31.205:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "hep_capture_id", 110)
modparam("siptrace", "send_sock_name", "siptrace_socket")
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_mode", 1)
modparam("siptrace", "trace_to_database", 0)
```

This is tested on Kamailio 5.5.1 and 5.5.3.

**Comment by miconda** [comment]
You can try the patch from the commit reference above to see if makes any difference.

**Comment by manticode** [comment]
@miconda thanks for the fast reply.

Unfortunately this does not resolve it, and it seems to now cause **send_sock_addr** to no longer work either.

**Comment by miconda** [comment]
Hmm, strange, maybe you can set debug=3 and paste all logs printed to see if it reports something on this case.

**Comment by miconda** [comment]
Can you try with the commit referenced above? As I looked in the code, only hlog() seemed to use socket name, not hep mirroring.

**Comment by miconda** [comment]
Closing, reopen if the above commit is not working.
