### ISSUE TITLE
modify 'rpc uac.reg_add'

### ISSUE THREAD

**Issue by hance2010** [kamailio/kamailio#3179]
### Description

rpc uac.reg_add 

Use a dot (.) if no value should be set for auth_password, auth_ha1, contact_addr, realm,or socket

### Expected behavior

https://github.com/kamailio/kamailio/blob/master/src/modules/uac/uac_reg.c#L2186

```
	if(reg.realm.len==1 && reg.realm.s[0] == '.') {
		reg.realm.s = NULL;
		reg.realm.len = 0;
	}

	if(reg.socket.len==1 && reg.socket.s[0] == '.') {
		reg.socket.s = NULL;
		reg.socket.len = 0;
	}
```

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
Master
```

* **Operating System**:

```
Debian11
```

**Comment by miconda** [comment]
Just make a PR with the proposed changes and it will be reviewed and merged if all ok.
