### ISSUE TITLE
trailing comma left on exclude_hf_value function

### ISSUE THREAD

**Issue by patrickarton** [kamailio/kamailio#3180]
### Description
when using exclude_hf_value  function to exclude values on Supported header there is a comma left after applying the exclude

### Troubleshooting

Before exclude_hf_value  call :  **Supported: 100rel, path, replaces**

After exclude_hf_value  call    : **Supported: 100rel,**

#### Reproduction

simple with sipp 

```
route {
        exclude_hf_value("Supported", "replaces");
        exclude_hf_value("Supported", "path");
}
```

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
tested on kamailio 5.5.4 and kamailio 5.6.0
```

* **Operating System**:

```
debian bullseye
```

**Comment by miconda** [comment]
See:

  - https://www.kamailio.org/wikidocs/tutorials/faq/main/#why-changes-made-to-headers-or-body-are-not-visible-immediately

For more discussions, use sr-users@lists.kamailio.org mailing list.
