### ISSUE TITLE
Disable GRUU 

### ISSUE THREAD

**Issue by adyryavko** [kamailio/kamailio#3181]
### Description

Hello.

Sip client Grandstream NT-XXX sends default registration request with "reg-id" and "instance"

> REGISTER sip:kamailio3.telecom.ru SIP/2.0
> Via: SIP/2.0/UDP 172.17.0.252:5060;branch=z9hG4bK1645839794;rport
> From: "7777" <sip:7777@kamailio3.telecom.ru>;tag=53756161
> To: <sip:7777@kamailio3.telecom.ru>
> Call-ID: 308071885-5060-1
> CSeq: 2031 REGISTER
> Contact: <sip:7777@172.17.0.252:5060>;reg-id=1;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>"
> Authorization: Digest username="7777", realm="kamailio3.telecom.ru", nonce="Ysv842LL+7dABGNcyuYZhl1L2QTPgzFq", uri="sip:kamailio3.telecom.ru", response="0ef43a754a7422dd9d8ed36f91aa546
> , algorithm=MD5
> Max-Forwards: 70
> User-Agent: Grandstream HT-502  V2.0A 1.0.9.1  chip V2.2
> Supported: path
> Expires: 1800
> Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, SUBSCRIBE, NOTIFY, INFO, REFER, UPDATE
> Content-Length: 0
> 
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 172.17.0.252:5060;branch=z9hG4bK1645839794;rport=5060;received=172.17.0.252
> From: "7777" <sip:7777@kamailio3.telecom.ru>;tag=53756161
> To: <sip:7777@kamailio3.telecom.ru>;tag=5bf75eb19869d3e257cd1fde2cbf92c4.7224507f
> Call-ID: 308071885-5060-1
> CSeq: 2031 REGISTER
> Contact: <sip:7777@172.17.0.252:5060>;expires=1800;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>";reg-id=1, <sip:07777@172.17.0.250:5060>;expires=101, <sip:7777@172.1
> 0.250:5061>;expires=101, <sip:7777@172.17.0.252:5062>;expires=607;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>";reg-id=2
> Server: kamailio (5.4.8 (x86_64/linux))
> Content-Length: 0
> 
> REGISTER sip:kamailio3.telecom.ru SIP/2.0
> Via: SIP/2.0/UDP 172.17.0.252:5062;branch=z9hG4bK212965390;rport
> From: "7777" <sip:7777@kamailio3.telecom.ru>;tag=1540711120
> To: <sip:7777@kamailio3.telecom.ru>
> Call-ID: 1127299103-5062-1
> CSeq: 2031 REGISTER
> Contact: <sip:7777@172.17.0.252:5062>;reg-id=2;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>"
> Authorization: Digest username="7777", realm="kamailio3.telecom.ru", nonce="Ysv862LL+78cGZE/vXJnQfemhCMiBilm", uri="sip:kamailio3.telecom.ru", response="6c3333159d41ae0fcaabfbbd8c5026e
> , algorithm=MD5
> Max-Forwards: 70
> User-Agent: Grandstream HT-502  V2.0A 1.0.9.1  chip V2.2
> Supported: path
> Expires: 1800
> Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, SUBSCRIBE, NOTIFY, INFO, REFER, UPDATE
> Content-Length: 0
> 
> 
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP 172.17.0.252:5062;branch=z9hG4bK212965390;rport=5062;received=172.17.0.252
> From: "7777" <sip:7777@kamailio3.telecom.ru>;tag=1540711120
> To: <sip:7777@kamailio3.telecom.ru>;tag=5bf75eb19869d3e257cd1fde2cbf92c4.451b5a53
> Call-ID: 1127299103-5062-1
> CSeq: 2031 REGISTER
> Contact: <sip:7777@172.17.0.252:5060>;expires=1792;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>";reg-id=1, <sip:7777@172.17.0.250:5060>;expires=93, <sip:7777@172.17
> .250:5061>;expires=93, <sip:7777@172.17.0.252:5062>;expires=1800;+sip.instance="<urn:uuid:00000000-0000-1000-8000-000B82566BBB>";reg-id=2
> Server: kamailio (5.4.8 (x86_64/linux))
> Content-Length: 0

Later, when I use branching (with q=-1.0), the kamailio sends an Invite to only one Contact from 7777@172.17.0.252:5062

If I use another Sip client without "instance" , such as Linksys-PAP2T, branching works fine.

GRUU is always disabled
 modparam("registrar", "gruu_enabled", 0)

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

How can I disable GRUU support completely?

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
kamailio -v
version: kamailio 5.4.8 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0
```

* **Operating System**:

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by miconda** [comment]
The reply does not indicate that gruu was enabled. It might be actually outbound-extension that you are facing.

Being about kamailio usage and kamailio.cfg, this should be discussed further on sr-users@lists.kamailio.org till it gets a resolution of an issue in the code or a feature request.
