### ISSUE TITLE
rtpengine module error with new masterbranch

### ISSUE THREAD

**Issue by ovoshlook** [kamailio/kamailio#32]
Hello. We Build 4.3 masterbranch (latest branch) . We install it today and not changed config from old build (4.3 masterbranch) that builded december 26. IT means - keys of rtpengine module the same for all configs.

Jan 14 05:09:58 Kamailio rtpengine[482]: [7dd25def58ced3
786f99894d1c34e18a@10.0.1.17:50600 port 30080] Error parsing RTP header: invalid header version
Jan 14 05:09:58 Kamailio rtpengine[482]: [7dd25def58ced3786f99894d1c34e18a@10.0.1.17:50600 port 30081] Error parsing RTCP header: invalid header version

Sorry. Different versions of rtpengine
3.7 and 3.8 with new build. I thnk it is rtpengine. Not module.

**Comment by linuxmaniac** [comment]
Closing, not related to kamailio then
