### ISSUE TITLE
Typo in src/modules/siputils/doc/siputils_admin.xml doc

### ISSUE THREAD

**Issue by arkadiam** [kamailio/kamailio#3200]
### Description

Typo in function example at src/modules/siputils/doc/siputils_admin.xml:

Instead of: 

...
if(is_first_hop()) { ... }
...
if(is_first_hop_mode("1")) { ... }
...

example should be:

...
if (is_first_hop()) { ... }
...
if (is_first_hop("1")) { ... }
...

**Comment by henningw** [comment]
Thanks, should be fixed with the comment referenced above.
