### ISSUE TITLE
set_contact_alias() doesn't work as promised

### ISSUE THREAD

**Issue by gaaf** [kamailio/kamailio#3201]
### Description

The docs for `set_contact_alias()` says: 
> **The new contact URI is immediately visible to other modules** in the way the fix_nated_contact() does it.

I don't know exactly what is meant by the last part of that sentence as that isn't documented, but the first part certainly doesn't hold:

The following snippet:
```
xlog("L_INFO", "  Received Contact: $ct");
if (set_contact_alias()) {
    xlog("L_INFO", "  Aliassed Contact: $ct");
}
```

Causes these log entries:
```
2022-07-26T15:41:57.351148+02:00 proxydev001 prx1[12116]: INFO:   Received Contact: sip:sipp@unknowndomain;transport=udp
2022-07-26T15:41:57.351148+02:00 proxydev001 prx1[12116]: INFO:   Aliassed Contact: sip:sipp@unknowndomain;transport=udp
```

Which clearly shows that the changed uri is **not visible** to the `pv` module (which exports `$ct`).

**Comment by patrickarton** [comment]
both set_contact_alias() and fix_nated_contact() use lumps to insert new contact uri so its not immediatly visible unless you call  msg_apply_changes() juste immediatly after those functions

**Comment by miconda** [comment]
Indeed is not changing the buffer, but internally signals that contact header was updated. I pushed a commit to docs to clarify.
