### ISSUE TITLE
v5.3.8  register over tcp but invite over udp

### ISSUE THREAD

**Issue by lglhust** [kamailio/kamailio#3203]
ubuntu 18.04 , kamailio v5.3.8 :

UE A and B register sucess on  kamailio server over tcp. When UE A calls UE B,  kamailio server receive the INVITE over tcp from UE A, then it send invite to UE B. But the invite sent by kamailio to UE B is over UDP. Then call fails, for UE B returns ICMP Destination unreachable(Port unreachable) error.

Is the error  configuration related or a bug? 

Any kind of help is highly appreciated.

Best Regards,

**Comment by henningw** [comment]
I would suggest updating to a supported release, e.g. one of the latest 5.5.x or 5.6.x. You can use the deb.kamailio.org as package source for the system. It also looks more like a configuration error, please use our sr-users list to discuss it. Close the issue.
