### ISSUE TITLE
SMSOPS: body < 3 characters not transmitted (empty)

### ISSUE THREAD

**Issue by gmaruzz** [kamailio/kamailio#3211]
Hello,

seems to me that if cellphone sends an SMS shorter than 3 characters (eg: "aa") it is sent as empty string

this maybe because of some snafu in PDU "payload" management in smsops_impl.c , pointer arithmetic between different characters' coding (ASCII, UTF8, UCS2, etc)

(tested with OnePlus 5t, 6t, Open5GS, SRSRAN)

**Comment by gmaruzz** [comment]
I'm using Kamailio 5.3

I see after 5.3 there are at least 3 new commits related to payload management...
maybe is already fixed? can you check it out?

**Comment by henningw** [comment]
What about just giving a newer version (e.g. 5.6.x) a try? :-)

**Comment by gmaruzz** [comment]
[sms.zip](https://github.com/kamailio/kamailio/files/9290354/sms.zip)
in the zip file two SMSs, one with payload "A" and one with payload "ABC"

**Comment by gmaruzz** [comment]
(I'll check with newer version, if fixed would be nice to backport as bug)

**Comment by gmaruzz** [comment]
I confirm, is fixed in 6.1
would be nice to backport the fix
[sms_one_character_fixed_in_6.1.zip](https://github.com/kamailio/kamailio/files/9291084/sms_one_character_fixed_in_6.1.zip)

**Comment by henningw** [comment]
You probably mean 5.6.x? Thanks for the confirmation. Regarding backporting the fix, please note that 5.3.x is end of life since about a year. Please consider using a newer release.
