### ISSUE TITLE
Missing documentation of deprecated ring_insert_callid in siputils

### ISSUE THREAD

**Issue by pnlarsson** [kamailio/kamailio#3212]
### Description
Upgraded to 5.6 from 5.5, looked through docs (https://www.kamailio.org/wikidocs/features/new-in-5.6.x/#siputils and https://www.kamailio.org/wikidocs/install/upgrade/5.5.x-to-5.6.0/) - and no mention of removal of ring_insert_callid - so upgrade failed. 

Found https://github.com/kamailio/kamailio/issues/2989

### Possible Solutions
Add documentation that the function is removed, and how to replace it with textops/htable and/or reply routes

**Comment by henningw** [comment]
Yes, this is indeed missing. Basically  you can do something like this, to give you the idea:

```
route {
...
  t_on_reply("manage_18X");
  t_relay()
...
}

onreply_route[manage_18X] {
  if (t_check_status("183")) {
    # drop or alter message
    change_reply_status_code("180");
    remove_body()
  }
}
```

**Comment by miconda** [comment]
Added to the upgrade page in the wiki:

  - https://github.com/kamailio/kamailio-wiki/blob/main/docs/install/upgrade/5.5.x-to-5.6.0.md#siputils

If anyone wants to add more (e.g., examples), a commit/PR can be made to the wiki project.

If further discussions are needed for sorting out config solutions, the sr-users@lists.kamailio.org mailing list can be used.
