### ISSUE TITLE
[stirshaken] copy identity header and forward

### ISSUE THREAD

**Issue by baloian** [kamailio/kamailio#3214]
### Description
I am using STIR/SHAKEN as a third party service and wanted to know if there is a function to copy the Identity header from the 302 response into the original INVITE and then forward it. The Contact header from the 302 will make Kamailio server forward the INVITE to the SBC.

Ideally having one function which does everything in one place would be a nice feature to have.

**Comment by fredposner** [comment]
This is pretty easy to grab in the reply route using the existing $hdr features

**Comment by baloian** [comment]
True, but sometimes you need to grab more than one property of the header. For example, `Identity`, `Date`, `Contact`,...
Having a function which does copy would make easy and most cases error free.
