### ISSUE TITLE
[pua] reginfo_increase_version does nothing

### ISSUE THREAD

**Issue by xadhoom** [kamailio/kamailio#3234]
### Description

The reginfo notifications sent via pua_reginfo + presence_reginfo contains the version fixed to `0`.
The pua docs report the param `reginfo_increase_version` which should increase the version if enabled, but currently does nothing.
Looking into the code seems to confirm that, param is read from `pua` module but is not used anywhere. While the param `dlginfo_increase_version` seems to be used for the intended scope.

#### Reproduction
Setup pua + pua_reginfo to publish registration informations and observe that version param of reginfo is always 0, not respecting pua `reginfo_increase_version` setting.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.6.1 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 9.4.0

```

* **Operating System**:
```
Linux Debian bullseye/sid
```

**Comment by henningw** [comment]
Will have a look, its probably not a large extension.

**Comment by henningw** [comment]
@xkaraman

**Comment by xkaraman** [comment]
Hey @xadhoom,

A commit has been made in 4c93985 that probably fixes this, can you maybe help and confirm it works?

Thanks

**Comment by xadhoom** [comment]
Sure, I'll be able to test it in the very beginning of the new year, will keep you posted.

**Comment by xadhoom** [comment]
Sorry for the late reply, but seems good to me!
