### ISSUE TITLE
The "--cfg-print" CLI option is not documented in Kamailio 5.6 Cookbook

### ISSUE THREAD

**Issue by leonid-xorcom** [kamailio/kamailio#3239]
Hi,
The "--cfg-print" CLI option is not documented in Kamailio 5.6 Cookbook.
I'm sorry but I don't know how to add it by myself...

Leonid

**Comment by henningw** [comment]
Hello, you can simply make a pull request with the extension against the https://github.com/kamailio/kamailio-wiki repository. Close this issue here, as its already documented in the build in help:

$ ./kamailio -h |grep "cfg"
    --cfg-print  Print configuration file evaluating includes and ifdefs
