### ISSUE TITLE
packaging: cannot merge config files on system with ostree

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3252]
On Fedora Core when installed Kamailio and then installed additional packages then receive error

```
[root@caloes-1 ~]# journalctl -flu ostree-boot-complete.service -o cat
Starting ostree-boot-complete.service - OSTree Complete Boot...
error: ostree-finalize-staged.service failed on previous boot: During /etc merge: Modified config file newly defaults to directory 'kamailio', cannot merge
ostree-boot-complete.service: Main process exited, code=exited, status=1/FAILURE
ostree-boot-complete.service: Failed with result 'exit-code'.
Failed to start ostree-boot-complete.service - OSTree Complete Boot.
ostree-boot-complete.service - OSTree Complete Boot was skipped because all trigger condition checks failed.
ostree-boot-complete.service - OSTree Complete Boot was skipped because all trigger condition checks failed.
ostree-boot-complete.service - OSTree Complete Boot was skipped because all trigger condition checks failed.
```

Suggestion place default Kamailio config into dedicated package "kamailio-config-default".

**Comment by miconda** [comment]
Can you present in more details what exactly the problem is? From the logs (and not a fedora user) is hard to figure out.

**Comment by miconda** [comment]
IMO, at least the default config should be part of main kamailio package, it is how most packages do afaik (ok, on debian/ubuntu). Maybe that is going to be changed, but for the moment it seems to be the norm.

On the other hand, I am not leveraging the packages that much, if something new is required by recent distros, then I am open to changes if there are not objections from others or better proposals.
