### ISSUE TITLE
Building Alpine APKs fail due to sunsetting of Python2

### ISSUE THREAD

**Issue by whosgonna** [kamailio/kamailio#3257]
### Description

Issues building `PYTHON` module on Alpine Linux due to [sunsetting of Python2](https://www.python.org/doc/sunset-python-2/).  The `python2` package (apk) has been removed from the current Alpine linux.  The APKBUILD file in the current Kamailio branches includes build settings for installing the Python (python2) module.  While I'm guessing it's possible to build python2 in the current Alpine container it was a conscious decision to no longer have a package for it.  Given this, what is the opinion about not building this by default within the APKBUILD file?

### Troubleshooting

Running `abuild -r` fails due to lack of python2 libraries.

#### Reproduction

Running `abuild -r` fails due to lack of python2 libraries.

#### Debugging Data

N/A

#### Log Messages

N/A

#### SIP Traffic
N/A

### Possible Solutions

In `APKBUILD`  remove references to `python2` and  `python` (but not `python3`).  I'll submit a pull request to do this.

### Additional Information

Kamailio 5.7 

* **Operating System**:

Alpine Linux  latest

**Comment by henningw** [comment]
Closed, as PR has been merged.
