### ISSUE TITLE
htable: bogus error while trying to iterate over an empty htable

### ISSUE THREAD

**Issue by ovidiusas** [kamailio/kamailio#3260]
### Description
While trying to iterate over an empty htable, this erro is printed:
```
ERROR: htable [ht_api.c:1847]: ht_iterator_end(): iterator not found [HTABLE_NAME]
```

There error log should be removed, it is normal to not find an iterator on an empty table.
This error is printed only on version 5.6.x and up.

**Comment by miconda** [comment]
Actually that log message should be printed if the iterator is not found (like in: not defined) or there is no space for a new iterator (there is a limited number of iterators that can be created). Also, I think it can happen if the htable is not defined at all.

And the log message should contain iterator name, not the htable name.

**Comment by ovidiusas** [comment]
My bad: I was calling sht_iterator_end() and passing the htable name as an argument instead of the actual iterator.
This didn't raise any error logs in previous versions of kamailio and the error popped up during an upgrade.
Closing as invalid ...
