### ISSUE TITLE
kamailio sip  out of order when sip transfer too fast

### ISSUE THREAD

**Issue by buzhaodi** [kamailio/kamailio#3262]
I found a problem when I tested again. When the interval between the transmission of two info messages is too short, the forwarding of kamailio will be confused. Can this be solved please?
<img width="1077" alt="3212f45cd3f97e395065c8a109eaa9d" src="https://user-images.githubusercontent.com/16113837/195576921-dafc0511-5b8e-45a8-879c-a28c194fa857.png">

![image](https://user-images.githubusercontent.com/16113837/195575863-b245c8f0-94ad-440c-9fe7-0301d037739c.png)

**Comment by miconda** [comment]
For questions about using Kamailio and routing SIP messages, use sr-users@lists.kamailio.org mailing list. The tracker is for reporting issues in the c code.
