### ISSUE TITLE
kamailio KEMI sipt module

### ISSUE THREAD

**Issue by skainz92** [kamailio/kamailio#3264]
Hi, 

maybe im wrong, but it seems the sipt module is not implemented in KEMI Framework. 
Is it planned? :)

**Comment by miconda** [comment]
There is no task to export old functions to KEMI, it is mainly done based on the needs of the developers. I exported most of the functions to the common modules and the ones I use. But there are still modules without exports to kemi.

The only exceptional rule is that an export to KEMI of an old function can be backported to latest stable branch (obviously if it is not very intrusive by changing radically the internals of the module, which should not be the case probably for 99% of the functions).

If you want to help exporting sipt to kemi, it will be appreciated, just make a PR and it will be reviewed and merged if al ok. Developers will help you along the way with comments and suggestions for the PR.
