### ISSUE TITLE
ipops Documentation Error

### ISSUE THREAD

**Issue by rdboisvert** [kamailio/kamailio#327]
There is a small error in the [srv_query ()](http://kamailio.org/docs/modules/4.3.x/modules/ipops.html#ipops.f.srv_query) documentation.  The xlog statements put the closing quotes in the wrong location.  They should be as shown below.

xlog ("port[$var(i)] $srvquery(udp=>port[$var(i)])\n");
xlog ("priority[$var(i)] $srvquery(udp=>priority[$var(i)])\n");
xlog ("target[$var(i)] $srvquery(udp=>target[$var(i)])\n");
xlog ("weight[$var(i)] $srvquery(udp=>weight[$var(i)])\n");

**Comment by miconda** [comment]
Thanks, pushed a commit to fix it on master and it will be backported soon.
