### ISSUE TITLE
Unable to use the KEMI Python async module

### ISSUE THREAD

**Issue by grant-mb** [kamailio/kamailio#3272]
### Description

Using the KEMI async module in Python is not possible, since the `async` word is a reserved word in Python3. This leads to a syntax error. 

#### Reproduction

```python
import KSR

KSR.async.task_route("")
```

### Possible Solutions

The below code works, but not sure if this is a right approach to this issue. 

`KSR.__dict__["async"].task_route("my_route")`

### Additional Information

```
version: kamailio 5.6.1 (x86_64/linux) b36a13
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: b36a13 
compiled on 10:06:47 Oct 25 2022 with gcc 10.2.1
```

```
Linux b0fe2a764c5e 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022 x86_64 GNU/Linux
```

**Comment by miconda** [comment]
Not a python user here, but leveraging `getattr()` could be a variant:

  - https://docs.python.org/3/library/functions.html#getattr

Otherwise `__dict__` should be good enough.

Should anyone have more suggestions, can still add a comment.

I will add a note in the docs.
