### ISSUE TITLE
pua_usrloc doesn't send PUBLISH requests when a AOR has been removed by usrloc keepalive timeout

### ISSUE THREAD

**Issue by admin-toneca** [kamailio/kamailio#3273]
Hello, 

module pua_usrloc doesn't send PUBLISH with status closed when AOR has been removed by nathelper or usrloc keepalive timeout.

modparam("usrloc", "timer_interval", 30)
modparam("usrloc", "timer_procs", 1)
modparam("usrloc", "use_domain", MULTIDOMAIN)
/* enable DB persistency for location entries */
#!ifdef WITH_USRLOCDB
modparam("usrloc", "db_url", DBURL_USRLOC)
modparam("usrloc", "db_mode", 1)
#!endif
modparam("usrloc", "ka_mode", 1)
modparam("usrloc", "ka_from", KEEPALIVE_FROM)
modparam("usrloc", "ka_timeout", 120)

modparam("presence", "db_url", FSDBURL)
modparam("presence", "presentity_table", "sbc_presentity")
modparam("presence", "active_watchers_table", "sbc_active_watchers")
modparam("presence", "watchers_table", "sbc_watchers")

modparam("presence_xml", "db_url", FSDBURL)
modparam("presence_xml", "force_active", 1)
modparam("presence_xml", "disable_bla", 0)
modparam("presence_dialoginfo", "force_dummy_dialog", 1)
modparam("presence_dialoginfo", "force_single_dialog", 1)

modparam("pua", "db_url", FSDBURL)
modparam("pua", "db_table", "sbc_pua")
modparam("pua_usrloc", "default_domain", HOSTNAME)
modparam("pua_dialoginfo", "include_callid", 0)
modparam("pua_dialoginfo", "include_tags", 0)
modparam("pua_dialoginfo", "include_localremote", 0)

### Additional Information

```
version: kamailio 5.6.2 (x86_64/linux) 54a9c1
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 54a9c1
compiled on 15:40:44 Nov  1 2022 with gcc 9.4.0
```

* **Operating System**:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

```

**Comment by henningw** [comment]
According to the docs it should work for db_mode 1, write through. Are you getting any errors in the logs about this topic? If you can you reproduce it in a lab, it could be interesting to see log with debugging enabled (for only a few contacts, otherwise the logging is probably to verbose).
