### ISSUE TITLE
Make command in Kamailio rtpengine module asynchronous

### ISSUE THREAD

**Issue by adityagupta-9900** [kamailio/kamailio#3283]
We need to make commands in rtpengine module asynchronous just like it is in evapi module which improves efficiency. I need help in it.
Firstly I need to know which all commands in rtpengine has to be supported by asynchronous complementary functions.
Secondly I was trying to understand the async functionality in evapi. I understood the suspend and continue process used to implement this. But I couldn't see anywhere we are trying to continue the suspended processes. 
Thank you.

**Comment by henningw** [comment]
Hello, in case of more detailed questions for an module extension its better to discuss on our developer mailing list (sr-dev). 
Regarding the asynchronous topic, so far there has not been a need for that. Usually rtpengine can be quite good scaled, its used in installation with several ten thousands concurrent calls.

**Comment by adityagupta-9900** [comment]
@henningw 
Hi! I've mailed on that mailing list, but no moderator seems to accept my mail so I'm letting you know here.  Also I got further update that I only need to make offer, answer and delete asynchronous for now.

**Comment by miconda** [comment]
@adityagupta-9900: you have to subscribe first to the mailing list, only the members can post there to prevent spams.

There is no moderation for members, messages go through. For non-members, sometimes the messages can be let in if a devel with admin rights has the time to review the on-hold list, otherwise all are discarded, after several days, the on-hold list can be large, full of spams, being waste of time to look at each of them.

**Comment by adityagupta-9900** [comment]
@miconda
Yeah I understand all of it. I filled that form to subscribe to the mailing list but I haven't received any confirmation mail or anything for so long. I can't get access.

**Comment by henningw** [comment]
@adityagupta-9900 I have seen a post on the sr-dev list yesterday. Are you receiving emails from the sr-dev list? Otherwise the subscription reply from the mailing list might get end up in a spam folder, consider to subscribe again.

**Comment by adityagupta-9900** [comment]
@henningw yeah I just checked, it was there in spam folder. 
Thank you for the assistance provided here so far. Looking forward to a propitious collaboration.

**Comment by miconda** [comment]
There is a PR on this, any further discussions should be done there.
