### ISSUE TITLE
To stop automatic creation of RabbitMQ queues by kazoo module

### ISSUE THREAD

**Issue by sharmilas123** [kamailio/kamailio#3285]
Hello Team,

**Description**
Automatic queue creation with Kazoo module in kamailio.

Noticed that , amqp_max_channels parameter creates automatic queues in Rabbitmq-server based on the channel number provided.
Expecting that , it should create only channels not queues.

**Parameter Used**
modparam("kazoo", "amqp_max_channels", 10)

**Additional Information**
Kamailio Version - output of kamailio -v
kamailio 5.5.1 (x86_64/linux) 

Can any one help on this issue as why the kazoo module creates an automatic queue based on amqp_max_channels param ?

Thanks

**Comment by miconda** [comment]
Answer on sr-users mailing list, further discussions should be done there:

  - https://lists.kamailio.org/pipermail/sr-users/2022-November/115813.html
