### ISSUE TITLE
Does Kamailio supports Voice and Video call support for 5G Core?

### ISSUE THREAD

**Issue by p00jaY** [kamailio/kamailio#3293]
Hi Kamailio community,

We just want to check does Kamailio IMS supports the functionality of Voice and Video call support (Vo5G) with 5G core?
If yes, please share the document reference. Else, please guide us when it will be available.
Any plans in upcoming release to support HTTP2 based SBI interface between P- CSCF and PCF.

Your inputs will be highly appreciated.

Thanks & Regards,
Pooja Yadav

**Comment by p00jaY** [comment]
@Bharat0908

**Comment by oej** [comment]
The bug tracker is for bugs, not for general discussion. Please ask this question on the mailing lists. Thanks.

**Comment by p00jaY** [comment]
@oej, Can you please help me with the steps for raising query on mailing list.

**Comment by oej** [comment]
https://www.kamailio.org/w/mailing-lists/

**Comment by p00jaY** [comment]
@oej, I have shared an email yesterday at sr-users@lists.kamailio.org after subscribing to the same sr-users mailing list. But haven’t received any response from them. Can you help me with this. Am i missing something here. Please suggest, Thanks.

**Comment by miconda** [comment]
It is an open source community project, people respond if they have time or if they know what to answer. There is no commercial agreement/SLA that you can demand answers immediately. Not getting a response on mailing does not mean it is not the right place for the discussion, just nobody available  / knowing what to answer.
