### ISSUE TITLE
jsonrpc-c

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#33]
The jsonrpc-c module doesn't compile on OS/X

CC (gcc) [M jsonrpc-c.so]		jsonrpc_io.o
jsonrpc_io.c:31:10: fatal error: 'sys/timerfd.h' file not found
#include <sys/timerfd.h>
         ^
1 error generated.

**Comment by oej** [comment]
This is git trunk/head

**Comment by miconda** [comment]
This module seems to use linux specific code, unless someone will reimplement sys/timerfd.h api or another solution, this is not for usage in Mac OS X.

**Comment by oej** [comment]
Which we need to document.

**Comment by miconda** [comment]
Just did it -- pressed 'comment and close' by mistake in the first phase, but anyhow I will have been closed after my commit.
