### ISSUE TITLE
Must openssl_mutex_shared.so be preloaded?

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3304]
The documentation on using openssl_mutex_shared.so is contradicting.

https://github.com/kamailio/kamailio/blob/master/src/modules/tls/README#L293 says:

> For OpenSSL (libssl) v1.1.x, it is required to preload 'openssl_mutex_shared' library shipped by Kamailio. For more details see 'src/modules/tls/openssl_mutex_shared/README.md'.

https://github.com/kamailio/kamailio/blob/master/src/modules/tls/utils/openssl_mutex_shared/README.md says:

> IMPORTANT: the workaround of using this preloaded shared library is no longer needed starting with Kamailio v5.3.0-pre1 (git master branch after September 14, 2019). The code of this shared library has been included in the core of Kamailio and the same behaviour is now achieved by default.

It is unclear, if openssl_mutex_shared.so must be preloaded.

In case the library is not needed anymore, it shall not be compiled and installed.

**Comment by miconda** [comment]
This tracker is for reporting bugs, not support questions. Use sr-users mailing list for questions about using/configuring kamailio.
