### ISSUE TITLE
Extend documentation for conversion from number to boolean in core cookbook

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3315]
According to https://www.kamailio.org/wikidocs/cookbooks/devel/core/ (Core Cookbook) type boolean is documented as:

* boolean - aliases to 1 (true, on, yes) or 0 (false, off, no)

Moreover the if() and while() statement can accept a number as condition.  My expectation was that passing non-zero is always converted to true, but this is not correct.

Please document how numbers are converted to booleans in case of if() and while() conditions.

**Comment by henningw** [comment]
Thanks for the issue. I marked it as enhancement request, which will be closed after some time if no developer started to work on it.
If you want to generally discuss it, please use the sr-users mailing list.

**Comment by miconda** [comment]
See https://www.kamailio.org/wikidocs/tutorials/faq/main/#how-is-the-function-return-code-evaluated which is linked from IF docs section. To extend it, just make PRs to the docs. Further discussions should be done on mailing list.
