### ISSUE TITLE
Kamailio Performance issue with Radius module

### ISSUE THREAD

**Issue by ycaner06** [kamailio/kamailio#332]
Hello;
I am trying to incraese Kamailio performance with Radius Modules. After 2 day testing Kamailio i get that results;
  After 1000+ calls , kamailio cannot give response sip calls but couldn't find any error about  radius , still diggin'
  without radius module , it is easy to pass 2000+ calls and see no problem.
  all above calls sends between 2 and 155 ms . if increase call per seconds kamailio cannot give response.
changing child , pkg and shmem parameteres don't change anything. i will try later again.

With radius module , i used freeradius-client  instead of radiusclient-ng.to do run with it , need to fix Makefile.radius file

Now , it is testing  to udp_raw mode on. i am gonna share results here. there is a udp_raw_mtu parameter. what should be , how can i calculate this parameter?

i want to ask one more question. There is a flag DBG_F_MALLOC . is it effect kamailio performance.

Thanks

**Comment by miconda** [comment]
Perhaps radius server is not replying very fast. You can increase the number of workers with **children** global parameter, but if radius server is slow, it will still get call routing delays.

You can use benchmark module to see how long it takes to execute an action in kamailio.cfg -- do it for the ones involving radius.

DBG_F_MALLOC doesn't introduce a noticeable performance effect.

Anyhow, this is not a report of an issue, but rather discussion to see if there is an issue. Such conversation belongs to sr-users mailing list -- I am closing here, start a discussion on sr-users if you want more feedback on this topic.
