### ISSUE TITLE
uri_param_rm function not working

### ISSUE THREAD

**Issue by iliesh** [kamailio/kamailio#3321]
### Description

I have the following URI: 
```INVITE sip:123456789;phone-context=+1@192.168.1.1;transport=udp;user=phone SIP/2.0```

I want to remove the phone-context parameter from the URI, so I've tried to use the function:
```uri_param_rm``` from the siputils package:

```
if (uri_param_rm("phone-context")) {
    t_relay_to_udp("192.168.1.2", "5060");
    exit;
  }
```

But this doesn't change anything, this parameter is still present in the URI.

I tried to use ```msg_apply_changes``` (just in case) function before relaying it - the result it the same, the parameter is still there.

Also, I've noticed that this function is not working either:

```
if (uri_param_any("phone-context")) {
  xlog("L_INFO", "Phone Context");
}
```

while this one:
```get_uri_param("phone-context", "$var(phoneCtx)");``` - seems to be working fine.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.6.2 (x86_64/linux) e292ba
```

* **Operating System**:

```
CentOS 7 X64
```

**Comment by henningw** [comment]
Thanks for the report, do you see any error messages in the kamailio log?

**Comment by iliesh** [comment]
Hi @henningw ,
Not, I don't see any warnings or errors in the log file.

Thanks

**Comment by miconda** [comment]
The `phone-context` is not a URI parameter, but a user part parameter. The function you use is for URI parameters, which are the parameters after domain/port. You should try with subst_uri() or some transformations.
