### ISSUE TITLE
Invalid default transaction isolation level in p_usrloc

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3324]
The default transaction level in p_usrloc is `READ UNCOMMITED`.

Since the correct spelling is `commiTTed`, this default transaction level `read uncommiTed` is not accepted by databases.

**Comment by henningw** [comment]
Thanks for the report, fixed with above commit. As the transaction support is deactivated by default, it was probably not noticed from a lot of people.
