### ISSUE TITLE
Custom Headers are not forwarding on CANCEL Request to downstream

### ISSUE THREAD

**Issue by HimaBinduGrg** [kamailio/kamailio#3326]
### Description
When we send any custom header in the CANCEL Request.. same request is not forwarding to the down stream. Custom Header are missing in th request which is received by the downstream.

We are using t_relay() to forwards the request.

Please let me know if any parameters are required to be enabled for this issue.

Kamailio should forward the same request which is sent by the upstream.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

Upstream CANCEL Request Sent
----------------------------------------------
Session Initiation Protocol (CANCEL)
    Request-Line: CANCEL sip:inbound@192.168.2.200:5060;transport=UDP SIP/2.0
    Message Header
        Via: SIP/2.0/UDP 192.168.2.192:8000;branch=z9hG4bK-25588-1-0
        From: <sip:inbound@192.168.2.192:8000>;tag=1
        To: <sip:inbound@192.168.2.200:5060;user=phone>
        Call-ID: 1-25588@192.168.2.192
        [Generated Call-ID: 1-25588@192.168.2.192]
        CSeq: 1 CANCEL
        Max-Forwards: 70
        Session-ID: 357f74433c5454178cde3d5278b40ec6
        User-Agent: A175 Collaboration Tablet
        Content-Length: 0

Down Stream CANCEL Request received
----------------------------------------------------
Session Initiation Protocol (CANCEL)
    Request-Line: CANCEL sip:inbound@192.168.2.200:5060;transport=UDP SIP/2.0
    Message Header
        From: <sip:inbound@192.168.2.192:8000>;tag=1
        To: <sip:inbound@192.168.2.200:5060;user=phone>
        Call-ID: 1-25588@192.168.2.192
        [Generated Call-ID: 1-25588@192.168.2.192]
        CSeq: 1 CANCEL
        Via: SIP/2.0/UDP 192.168.1.200;branch=z9hG4bK561f.944ad825d740820aeb834f49c3cea1b7.0;rport
        Max-Forwards: 69
        Content-Length: 0

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 5.5.3 (x86_64/linux) d31ff9-dirty
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: d31ff9 -dirty
compiled on 10:08:08 May 24 2022 with gcc 8.5.0

* **Operating System**:

Red Hat Enterprise Linux release 8.6 (Ootpa)

**Comment by henningw** [comment]
The CANCEL is a so called hop-by-hop message. That means that the proxy reply to the first CANCEL and then creates a new one. Therefore it will not add the headers of the first CANCEL to the second one. In case of more questions related to that, please write to our sr-users mailing list.
