### ISSUE TITLE
problem with app_perl loading order

### ISSUE THREAD

**Issue by grumvalski** [kamailio/kamailio#333]
All the modules loaded after app_perl have their statistics go under "app_perl". When the mod_init function defined in the module's exports is called for any module after app_perl, exports.name is always "app_perl". Seems that the exports structure is fine in sr_module when we initialize the modules. I haven't been able to spot where the issue is.

**Comment by miconda** [comment]
It could be related to the fact that app_perl uses the flag for global exporting, as it is needed by the embedded interpreter. That may lead to naming conflict of exported structured by other modules.

In attempt to fix it, I pushed a commit to allow the structure to be prefixed with ```_modulename_```.

Try to change the name of ```exports``` structure in app_perl module to ```_app_perl_exports```.

**Comment by grumvalski** [comment]
Solved by commits 6c7d38ee0fcbd482ff0527178481345fc93a7fc8 and 2c736877.
