### ISSUE TITLE
dialog.dlg_filter_mode has ambiguous definition with double negation

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3336]
https://www.kamailio.org/docs/modules/devel/modules/dialog#dialog.p.dlg_filter_mode says for dialog.dlg_filter_mode (int)

> Set dialog fitering mode, which can specify what dialogs are processed. Its value can be a combination (the sum) of following flags:
>
>  1 - do not send keepalives and do not execute timeout function if dialog is not local (if the associated bind address is not a local socket).
>
> Default value is “0”. 

As you can see, the definition of 1 is a double negation and there is no definition for 0.  What means 0:

- do not send keepalives and do not execute timeout function if dialog is local
- send keepalives and execute timeout function if dialog is not local
- send keepalives and execute timeout function if dialog is local

Please document the meaning of the default value 0.

**Comment by miconda** [comment]
Not understanding the docs for a module is not a bug, you should discuss first on sr-users mailing list and you may get clarifications, then make a pull request to make it better.

The project is more than 20 years old, many developers over those years are no longer active, so a feature/modparam/function may have been added by someone who is not working anymore with the project. Therefore you cannot demand that something has to be documented by an active developer now.

What is requested nowadays is that a new modparam/function/rpc command/etc. has to be documented.

For old things, looking at figuring out from the source code is also a good option.

Opening an issue for each documentation piece can make tracking of and focus on real bugs too complex.
