### ISSUE TITLE
modparam("dialog", … for ims_dialog

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3337]
https://www.kamailio.org/docs/modules/devel/modules/ims_dialog.html contains examples how to configure the module:
```
modparam("ims_dialog", "dlg_extra_hdrs", "Hint: credit expired\r\n")
modparam("ims_dialog", "detect_spirals", 1)
modparam("dialog", "profiles_with_value", "caller ; my_profile")
modparam("dialog", "profiles_no_value", "inbound ; outbound")
modparam("dialog", "bridge_controller", "sip:ctd@kamailio.org")
```
and others.  As can be seen, the first parameter to modparam() is not consistent in the documentation.

In case really `dialog` shall be used, as the examples show, please spell explicitly in the documentation that `modparam("dialog"` is not a typo. Otherwise please adjust the examples.

**Comment by henningw** [comment]
Thanks for the report. The latter three examples are probably just a copy and paste error and should also read "ims_dialog"..

**Comment by miconda** [comment]
Updated in master.
