### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Jonnypleasehelp** [kamailio/kamailio#3343]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by henningw** [comment]
@Jonnypleasehelp If you are interested in commercial support, out [business directory](https://www.kamailio.org/w/business-directory/) provides information about providers in different world regions.
