### ISSUE TITLE
Unclear default value for mem_join

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3355]
According to https://www.kamailio.org/wikidocs/cookbooks/devel/core/#mem_join the default value for mem_join is `1 (enabled)`.

[https://github.com/kamailio/kamailio-wiki/blob/main/docs/tutorials/troubleshooting/memory.md](https://github.com/kamailio/kamailio-wiki/blob/main/docs/tutorials/troubleshooting/memory.md#monitoring-memory)  says:

>  In order to merge the free memory fragments one should enable memory join. Default is disabled (mem_join=0).

So depending on the source of information the default value of mem_join is different.

**Comment by henningw** [comment]
The second link regarding the troubleshooting is outdated, its default since several major releases.

**Comment by dilyanpalauzov** [comment]
Closing the ticket does not remove the contradictions imposed by the documentation.

**Comment by henningw** [comment]
Its fixed in the wiki already
