### ISSUE TITLE
typos https://kamailio.org/docs/db-tables/kamailio-db-devel.html

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3361]
https://kamailio.org/docs/db-tables/kamailio-db-devel.html#idm9040 contains:

* thay instead of they, (UID_AUTH_DB Module)
* `,if` without comma in between (in UAC Module)
* for table "uacreg" column realm is described as “Remote username”, it should be Remote realm

For table dbaliases indexes contains:
* alias_user_idx on column alias_username
* alias_idx composite index on columns  alias_username and alias_domain

I would say the composite index will also be used on queries only on the alias_username column, so the index alias_user_idx is redundant and should be deleted.

**Comment by miconda** [comment]
Those files are generated from xml schema files in the source tree at `src/lib/srdb1/schema/`.

While the first column on a composite index has some benefits on queries using it along with some database systems, it is not as efficient as with a dedicated index. I would not change that in the definition of the table, anyhow on database intensive systems, one should consult a database admin to tune properly the structure and the indexes.

**Comment by dilyanpalauzov** [comment]
Thanks for your answer.  Since December there is no `,if` without space in between in the source code, but on the above webpage `,if` does exist.

**Comment by miconda** [comment]
Those documents are not automatically generated, usually being done when a new major release is out.
