### ISSUE TITLE
pua_json module not compatible with library libjson-c-dev 0.15.2 

### ISSUE THREAD

**Issue by henningw** [kamailio/kamailio#3376]
There seems to be an incompatibility in the pua_json module related to the libjson-c-dev" version.
The module crashes after start on the first actions on version 0.15.2 (e.g. from Debian bullseye).

It works with version 0.12 (e.g. Debian buster).

Backtrace below:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6d265e5537 in __GI_abort () at abort.c:79
#2  0x00007f6d265e540f in __assert_fail_base (fmt=0x7f6d2675d6a8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f6d2322c091 "jso->_ref_count > 0",
   file=0x7f6d2322c064 "./json_object.c", line=308, function=<optimized out>) at assert.c:92
#3  0x00007f6d265f4662 in __GI___assert_fail (assertion=0x7f6d2322c091 "jso->_ref_count > 0", file=0x7f6d2322c064 "./json_object.c", line=308, function=0x7f6d2322c480 "json_object_put")
   at assert.c:101
#4  0x00007f6d23224732 in json_object_put () from /lib/x86_64-linux-gnu/libjson-c.so.5
#5  0x00007f6d25842362 in pua_json_publish (msg=0x7fffb3fffb20,
   json=0x7f6d25ff5778 "{\"Call-ID\":\"111\",\"Event-Category\":\"presence\",\"Event-Name\":\"update\",\"Event-Package\":\"message-summary\",\"Expires\":\"3600\",\"To\":\"sip:103@XXX.YYY.55.208\",\"To-User\":\"103\",\"To-Realm\":\"XXX.YYY.55.208\",\"From\":\""...) at pua_json_publish.c:383
#6  0x00007f6d2583e74a in w_pua_json_publish (msg=0x7fffb3fffb20, p1pjson=0x7f6d25ff5988 "xW\377%m\177", p2=0x0) at pua_json_mod.c:100
#7  0x0000563199d1c47e in do_action ()
#8  0x0000563199d29ae6 in run_actions ()
#9  0x00007f6d2324444e in ?? () from /usr/lib/x86_64-linux-gnu/kamailio/modules/xhttp.so
#10 0x00007f6d23246005 in ?? () from /usr/lib/x86_64-linux-gnu/kamailio/modules/xhttp.so
#11 0x0000563199e6cb10 in nonsip_msg_run_hooks ()
#12 0x0000563199ede538 in receive_msg ()
#13 0x0000563199cac4f2 in receive_tcp_msg ()
#14 0x0000563199caeb51 in tcp_read_req ()
#15 0x0000563199cb2028 in ?? ()
#16 0x0000563199c9da4f in ?? ()
#17 0x0000563199cb4f8c in tcp_receive_loop ()
#18 0x0000563199e2330b in tcp_init_children ()
#19 0x0000563199c8967f in main_loop ()
#20 0x0000563199c9446e in main ()
```

**Comment by eschmidbauer** [comment]
What version of kamailio are you running? I run 5.5.2 on bullseye with no issues. 
Just trying to reproduce this

**Comment by henningw** [comment]
Thanks for the reply. The version in question was Kamailio 5.6.3.

**Comment by henningw** [comment]
Just let me know if you need more information

**Comment by henningw** [comment]
@eschmidbauer anything I could do? Did you managed to have a look to it maybe? Thank you.

**Comment by eschmidbauer** [comment]
Hi @henningw can you give me more details on how to reproduce the crash? 
e.g. install from source, packages. 
I would be happy to take a look and fix it if I can reproduce the issue locally

**Comment by henningw** [comment]
Thanks for the fast reply. We observed some time ago on an environment, but right now I don't have the means to reproduce it, unfortunately. I just looked into the report from the time, and it was easy to reproduce by just installing e.g. 5.6.3 from github and using the libjson-c-dev version 0.15.2. The version 0.12 worked. 5.6.3 is of course also now a bit older.

**Comment by eschmidbauer** [comment]
ok, i will compile 5.6.3 on bookworm and test it out! 
give me some time to work on it
