### ISSUE TITLE
TLS module rpc commands not found

### ISSUE THREAD

**Issue by HimaBinduGrg** [kamailio/kamailio#3385]
We have loaded the tls.so module in the kamailio.cfg file and the kamailio process is up and running, however we are not sure whether the TLS module is loaded properly or not.

Here are a few configuration details.

#!ifdef WITH_TLS
loadmodule "tls.so"
#!endif

#!ifdef WITH_TLS
enable_tls=yes
#!endif

#!ifdef WITH_TLS
## ----- tls params -----
modparam("tls", "config", "/etc/kamailio/tls.cfg")
#!endif

$kamailio -v
version: kamailio 5.5.3 (x86_64/linux) d31ff9-dirty
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: d31ff9 -dirty
compiled on 10:08:08 May 24 2022 with gcc 8.5.0

# openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021

# ldd /usr/lib64/kamailio/modules/tls.so
        linux-vdso.so.1 (0x00007ffc0cbf2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2c3bcc1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2c3b93f000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f2c3b6ab000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f2c3b1c2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2c3afa2000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2c3abdd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2c3c170000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f2c3a9c5000)

When we try to check tls rpc cli's it shows command not found
# kamcmd [tls.info](http://tls.info/)
error: 500 - command [tls.info](http://tls.info/) not found
# kamcmd tls.reload
error: 500 - command tls.reload not found

We have compiled the kamailio-5.5.3 version using the kamailio.spec file.
kamailio-tls-5.5.3-5.el8.x86_64 rpm installed to load the tls.so module.

Operating System : Red Hat Enterprise Linux release 8.6 (Ootpa)

Please suggest to me anything we have missed to configure or compilation wise.
Also suggest to me how to verify the tls module and configuration is fine or not.

**Comment by miconda** [comment]
Questions about use of Kamailio and its configuration file have to be posted to sr-users@lists.kamailio.org mailing list.

The tracker here is for reporting bugs in the C code of Kamailio.
