### ISSUE TITLE
Crash with "F_TCPCONN connection marked as bad"

### ISSUE THREAD

**Issue by davidvoisonics** [kamailio/kamailio#3392]
We had a Kamailio 5.5.4 server crash. There were lots of the following errors repeated over and over in the Kamailio log:

Mar 10 14:59:14 px1 /usr/sbin/kamailio[1375]: WARNING: <core> [core/tcp_read.c:1840]: handle_io(): F_TCPCONN connection marked as bad: 0x7f48e97ecdc8 id 0 fd -1 refcnt 0 ([]:0 -> []:0)
Mar 10 14:59:14 px1 /usr/sbin/kamailio[1375]: CRITICAL: <core> [core/io_wait.h:596]: io_watch_del(): invalid fd -1, not in [0, 2) 

And in the syslog it said:

Mar 10 14:59:14 px1 kernel: [731786.728781] kamailio[1363]: segfault at 10 ip 00007f48e6dde42d sp 00007ffc2d23ef00 error 4 in tls.so[7f48e6d9c000+47000]
Mar 10 14:59:14 px1 kernel: [731786.728814] Code: 98 01 5c 24 28 41 29 dd 49 01 84 24 40 01 00 00 c7 44 24 6c 00 00 00 00 85 c9 0f 85 be 08 00 00 49 8b 94 24 90 01 00 00 31 
f6 <48> 8b 7a 10 31 d2 e8 38 10 fc ff 85 c0 0f 8e 90 0d 00 00 45 31 db

Is anyone able to advise whether this is a known issue, and if it's fixed in a more recent version? The only related bug report I found was issue #748 which was closed without resolution. Our Kamailio is installed from the Ubuntu 22.04 repository.

**Comment by davidvoisonics** [comment]
I see other issues have been replied to, but not this one. Just wanted to check when someone might be able to advise on it please?

**Comment by henningw** [comment]
The issue #748 was about an old version coming from a custom repository as well.
It usually make sense to update to the latest version in case of issues like this. The crash seems to related to the tls module. 
Are you observing this crash frequently, or does it happen one time?

**Comment by davidvoisonics** [comment]
It has happened once so far, after Kamailio had been running for a couple of months. Do you think we would be better to install from here instead?

deb http://deb.kamailio.org/kamailio56 jammy main
deb-src http://deb.kamailio.org/kamailio56 jammy main

**Comment by davidvoisonics** [comment]
Henning, is there a particular reason to think that Kamailio 5.6 will be better? Have there been improvements in the affected area? Thank you.
