### ISSUE TITLE
Add support for Linux kernel anyIP feature

### ISSUE THREAD

**Issue by pumper** [kamailio/kamailio#3394]
Hi

I have a kimailio box that receives messages from one interface and send it from another interface and I use dispatcher module successfully.

Now I assigned an I range to Linux loopback interface through Linux kernel anyip feature. And I can ping the range.

ip -4 route add local 192.168.0.0/24 dev lo

this linux kernel feature is described in [https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ab79ad14a2d51e95f0ac3cef7cd116a57089ba82](url) and [https://blog.widodh.nl/2016/04/anyip-bind-a-whole-subnet-to-your-linux-machine/](url)
 another linux kernel feature that is required is **Non-Local Binds in the Kernel** which van be found in [https://oswalt.dev/2022/02/non-local-address-binds-in-linux/](url) and after enabling that we must be able to send data with any ip address with kamailio this feature is described in [https://oswalt.dev/2022/02/non-local-address-binds-in-linux/](url)

I want to send messages from source of the ip in this range but kamailio cant do this in the right way.

I added this two directives to kamailio.cfg:

mhomed=yes

ip_free_bind = 1

and when I want to use an ip from the list I use

$fs=”udp:192.168.0.120:5060”;

With no luck

If I use

force_send_socket(udp:192.168.0.120:5060);

kamailio returns an error

bad force_send_socket argument: 192.168.0.120:5060 (kamailio doesn't listen on it)

and if I add listen directive for one ip like:

listen=udp:192.168.0.120:5060

everything works fine but I want to be able to use any ip from list not just one ip.

Thanks.

**Comment by pumper** [comment]
Thanks for quick response I know this linux feature is not supported in kamailio and because of that I put this feature request here.
Thanks.

**Comment by joelsdc** [comment]
Is there any limitation that stops you from using multiple `listen=` directives?

In fact, given enough resources, is there even a limit on the number of `listen=` directives that Kamailio can handle?

**Comment by jaybinks** [comment]
I'm really curious about the usecase you see here, and how it differs from
what is achievable with net.ipv4.ip_nonlocal_bind and or a bgp daemon on
your host .

I know they are not the same, but I can't (right now ) think of a reason
I'd want to bind to a whole subnet.

Maybe something TLS related, but in that case you have to do all the TLS
config, so is avoiding the listen line really a big advantage?

I'm honestly curious though

**Comment by sergey-safarov** [comment]
I think here is case like enterprise PBX in the cloud.
Many PBX should have own IP.
Example to create outbound call to another PBX required whitelist PBX IP
address.

Before somebody asked, what is prevents you to bind on 65536 IP addresses
(/16 network).
Could answer?

**Comment by henningw** [comment]
Sure, having a complete network on individual workers will waste a lot of memory. Just to add a bit more context to this request, this is the feature in question [link](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ab79ad14a2d51e95f0ac3cef7cd116a57089ba82). 

This blog post provides some good summary of the option and also explain the related IP_FREEBIND option: [link](https://oswalt.dev/2022/02/non-local-address-binds-in-linux/)

**Comment by sergey-safarov** [comment]
@pumper could you help me understand how to bind to `127.0.0.0/8`.
At [https://oswalt.dev/2022/02/non-local-address-binds-in-linux/](https://oswalt.dev/2022/02/non-local-address-binds-in-linux/) described use for bind to any IP
```c
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(("0.0.0.0", 0))
```
But not for network addr with mask.
Hope you can suggest.
