### ISSUE TITLE
[Possible bug] Strartup issues

### ISSUE THREAD

**Issue by mdziczkowski** [kamailio/kamailio#3410]
### Environment

- **OS**: Debian 11 (64-bit)

### Description

While attempting to start kamailio thu the `kamctl start` command, I had recieved a following output in the terminal:

**Note**: I had edited the PID_FILE variable and had set the value to: /run/kamailio.pid

```
-e database engine 'SQLITE' loaded
-e Control engine 'RPCFIFO' loaded

-e \E[37;33mINFO: Starting Kamailio : 

-e \E[37;31mERROR: PID file /run/kamailio.pid does not exist -- Kamailio start failed
```

In my opinion, it's strange that the server complains about missing PID file, while attempting to run it and no other Kamailio instance is running

**Comment by miconda** [comment]
Use the sr-users@lists.kamailio.org mailing list for discussing the use of kamailio and its tools, to get help related to log messages and figure out what could be wrong.
