### ISSUE TITLE
rtp routing issue with kamailo 5.6 + rtpengine + jssip webrtc client

### ISSUE THREAD

**Issue by mail4arunkr** [kamailio/kamailio#3413]
I have installed kamaillio 5.6 on debian 11, bullseye with RTP engine latest version 11.x. Using webrtc client as jssip to connect with kamailio and route the calls to asterisk server from kamailio.

in Local network everything working fine

When I connect JSSIP webrtc client from public internet I am getting no voice for both ends.  I have observed that the rtp is flowing from  the remote end to the client while IVR is playing from callee end. But the rtp doesnt know where to route to reach the webrtc client.
For normal UDP call everyting works fine from local and public internet. The issue is only for ws and wss calls

observations :
ICE options : trickle ICE
ICE candidates with sdp is there when calling from local network
ICE candidates are not with sdp when calling from publi internet. C IN and RTCP = 0..0.0.0:9
found RTP is routing to  ------- > 0.0.0.0:9 and not reaching anywhere
RTPengine interface is local ip and public ip is advertised, in kmailio also public ip is advertised

sip dumb has been investgated and found everything is observed as normal with only one difference, that is no ice candidates for wss client from public internet

**Comment by miconda** [comment]
Questions related to use of Kamailio and its configuration have to be posted to sr-users mailing list. The tracker here is for reporting bugs in the C code.
