### ISSUE TITLE
Does kamailio supports SIPREC?

### ISSUE THREAD

**Issue by laurnzdj** [kamailio/kamailio#3416]
Hi,

Currently studying SIPREC call recording, I just want to ask if Kamailio supports SIPREC or does it have modules that supports it similar to OpenSips?
https://opensips.org/docs/modules/3.4.x/siprec.html

If not supported is there a plan to support it just in case?

Thank you!

**Comment by henningw** [comment]
Support for the specific SIPREC protocol is AFAIK not available in Kamailio. But you could use e.g. rtpengine for recording calls, maybe together with one of the sip tracing modules. Please note that the github tracker should be only used for discussing bugs and pull requests related to the C code. Use our sr-users mailing list for questions like this.

**Comment by henningw** [comment]
previous discussed at #2874
