### ISSUE TITLE
Use www_challenge method via kemi on lua

### ISSUE THREAD

**Issue by nmazzon** [kamailio/kamailio#3423]
### Description

We would use **www_challenge** method of **auth** module on our kemi lua script. 
Function is not mapped on [auth kemi](https://kamailio.org/docs/tutorials/5.3.x/kamailio-kemi-framework/modules/#auth)
so we tried to use [modf](https://kamailio.org/docs/tutorials/5.3.x/kamailio-kemi-framework/kemimods/#ksrxmodf) but we have every time this log 

```
app_lua [app_lua_api.c:1725]: sr_kemi_lua_modf(): function 'www_challenge' has fixup - cannot be used
```

We tried this call to the method on lua script

```
KSR.x.modf("www_challenge", realm, 1);
```

The question is: 
are we calling method on a bad way or is not possible to call www_challenge method by kemi lua ? 

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by nmazzon** [comment]
No auth_challenge use Proxy-Authorization for INVITE messages but we need to use WWW-Authorization. 
A possible solution would be use [modf](https://kamailio.org/docs/tutorials/5.3.x/kamailio-kemi-framework/kemimods/#ksrxmodf) 

I do not understand why this peace of code 

```
KSR.x.modf("www_challenge", realm, 1);
```

gives error

```
app_lua [app_lua_api.c:1725]: sr_kemi_lua_modf(): function 'www_challenge' has fixup - cannot be used
```

**Comment by miconda** [comment]
Indeed, the function was not exposed to kemi. I pushed quickly a commit for it, referenced above. At some point it will be backported, if you have issues with it, open a new bug report.

**Comment by nmazzon** [comment]
Thank you so much
