### ISSUE TITLE
Early Media on Kamailio 5.X w/rtpengine

### ISSUE THREAD

**Issue by ibrahmgarip** [kamailio/kamailio#3429]
![Screenshot from 2023-04-28 19-30-37](https://user-images.githubusercontent.com/110819566/235204393-185d27b4-e8e1-4290-a723-3821410c4549.png)
![Screenshot from 2023-04-28 19-34-50](https://user-images.githubusercontent.com/110819566/235204399-67c10327-20e0-4cd6-8b49-05f268464f13.png)

Hi, I'm trying to build a script for early media. I've kamailio 5.6 and rtpengine 11.3.1 on my server. I just want to play local media when I get call to my server but its not working as I want.

I've configured kamailio to work with rtpengine and added this snippet to  " onreply_route[MANAGE_REPLY] " section.

if(status=="100") {
	rtpengine_manage();
	t_reply("183", "Session Progress");
	block_dtmf();
	play_media("from-tag=$fti file=/usr/share/rtpengine/decode_G711.wav");

I can see the RTP is playing successfuly but the kamailio is not creating SIP messaging with SDP to play on other side.

I couldn't figure out how should I configure, can you please advise me about that?
<!--

**Comment by miconda** [comment]
For questions about how to use Kamailio and its configuration file, use sr-users@lists.kamailio.org mailing list.

This tracker is for reporting issues related to the source code.
