### ISSUE TITLE
Slow service restart on FreeBSD

### ISSUE THREAD

**Issue by tbswork1** [kamailio/kamailio#3431]
### Description

Restarting kamailio service on FreeBSD takes a one minute to complete. With default config in place.

#### Reproduction
```
service kamailio restart
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`
5.5.4

```
 sudo service kamailio restart
Performing sanity check on kamailio configuration:
 0(14393) WARNING: <core> [core/socket_info.c:1480]: fix_hostname(): could not rev. resolve 192.168.0.18
 0(14393) WARNING: <core> [core/socket_info.c:1480]: fix_hostname(): could not rev. resolve 192.168.0.18
config file ok, exiting...
Stopping kamailio.
Waiting for PIDS: 14307.
Starting kamailio.

```

* **Operating System**:
FreeBSD

```
(paste your output here)
```

**Comment by miconda** [comment]
Maybe `-a no` helps, anyhow questions about use of Kamailio and how to configure it have to be addressed to sr-users@lists.kamailio.org mailing list.

This tracker is for reporting bugs in the code.
