### ISSUE TITLE
Getting error while configuring kamailio.

### ISSUE THREAD

**Issue by rutujasm** [kamailio/kamailio#3433]
### Description

I have installed kamailio and also mariadb server with mysql.I also updated kamctlrc file values with my actual hostname and the user ,database,tables its password .But grtting errors while configuring kamailio.
#### Reproduction

root@jigasi:/# sudo vi /etc/kamailio/kamailio.cfg 
root@jigasi:/# sudo systemctl restart kamailio.service 
Job for kamailio.service failed because the control process exited with error code.
See "systemctl status kamailio.service" and "journalctl -xeu kamailio.service" for details.
root@jigasi:/# sudo systemctl status kamailio.service 
× kamailio.service - Kamailio - the Open Source SIP Server
     Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-05-04 08:45:03 UTC; 10s ago
    Process: 29245 ExecStart=/usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY --atexit=no (code=exited, status=255/EXCEPTION)
        CPU: 32ms

May 04 08:45:03 jigasi.pune.cdac.in systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 5.
May 04 08:45:03 jigasi.pune.cdac.in systemd[1]: Stopped Kamailio - the Open Source SIP Server.
May 04 08:45:03 jigasi.pune.cdac.in systemd[1]: kamailio.service: Start request repeated too quickly.
May 04 08:45:03 jigasi.pune.cdac.in systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 04 08:45:03 jigasi.pune.cdac.in systemd[1]: Failed to start Kamailio - the Open Source SIP Server.
root@jigasi:/# kamailio -c
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <host> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 259, column 51: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <port> of type <2:int> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 260, column 34: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <dbname> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 261, column 42: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <table> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 262, column 43: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <username> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 263, column 44: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <password> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 264, column 47: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <db_url> of type <1:string> not found in module <db_mysql>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 265, column 91: Can't set module parameter
 0(29260) ERROR: <core> [core/modparam.c:175]: set_mod_param_regex(): parameter <username_column> of type <1:string> not found in module <auth_db>
 0(29260) CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 299, column 50: Can't set module parameter
ERROR: bad config file (8 errors) (parsing code: 0)
 0(29260) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```root@jigasi:/# kamailio -v
version: kamailio 5.5.6 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 9.4.0
root@jigasi:/# 


* **Operating System**:

<!--
Details about the operating system, the type: Linux (e.g.,: Debian 8.4, Ubuntu 16.04, CentOS 7.1, ...), MacOS, xBSD, Solaris, ...;
Kernel details (output of `lsb_release -a` and `uname -a`)
-->

```
(paste your output here)
```

**Comment by rutujasm** [comment]
https://dopensource.com/2019/05/15/kamailio-v52-debian-quick-install/
used this link for installation.

Also configured according to my mysql creadentials for new kamailio user:
## database read/write user
DBRWUSER="kamailio"

## password for database read/write user
DBRWPW="kamailiorw"

## database read only user
DBROUSER="kamailioro"

## password for database read only user
DBROPW="kamailioro"


I am stucked at this point :     /usr/sbin/kamdbctl create


my kamctlrc file looks
## the SIP domain
 SIP_DOMAIN=10.208.39.129

## chrooted directory
# CHROOT_DIR="/path/to/chrooted/directory"

## database type: MYSQL, PGSQL, ORACLE, DB_BERKELEY, DBTEXT, or SQLITE
## by default none is loaded
##
## If you want to setup a database with kamdbctl, you must at least specify
## this parameter.
 DBENGINE=MYSQL

## database host
 DBHOST=jigasi.pune.cdac.in

## database port
 DBPORT=3306

## database name (for ORACLE this is TNS name)
 DBNAME=kamailio

## database path used by dbtext, db_berkeley or sqlite
# DB_PATH="/usr/local/etc/kamailio/dbtext"

## database read/write user
 DBRWUSER="kamailio"

## password for database read/write user
 DBRWPW="kamailio123"

## database read only user
 #DBROUSER="kamailioro"

Could you please help me for resolving thuis issue.

**Comment by miconda** [comment]
Questions about use of Kamailio, how to be configured or errors of configuration have to be addressed to sr-users@lists.kamailio.org email list.

This tracker is for reporting bugs in the code.

**Comment by rutujasm** [comment]
Sorry for inconvinience from my side .As I was not able to send mail.
