### ISSUE TITLE
pipelimit module - typo in documentation

### ISSUE THREAD

**Issue by arkadiam** [kamailio/kamailio#3449]
Module doc says:
4.5. plp_limit_column (string)
Name of 'limit' column.
Default value is “limit”. 

According to source src/modules/pipelimit/pl_db.c  default value is  plimit
#define RLP_LIMIT_COL                   "plimit"

So the doc should say:
Default value is “plimit”.

**Comment by linuxmaniac** [comment]
Thanks!
