### ISSUE TITLE
integer overflow in 'core.shmmem' output still persists

### ISSUE THREAD

**Issue by juliusf** [kamailio/kamailio#3450]
Hi,

we've come around to test again what happens if we set 'core.shmem' to a size larger than 4G. The original issue has been reported here  #2824. We are running Kamailio 5.6 at commit `24989241cfc58c6ba47d48c9a86921251f4ba235`

We are querying the `core.shmen` parameter via RPC and getting the following response from the server:

```
<?xml version="1.0"?>
<methodResponse>
<params>
<param>
<value><struct><member><name>total</name><value><int>-80</int></value></member><member><name>free</name><value><int>-66333776</int></value></member><member><name>used</name><value><int>63570392</int></value></member><member><name>real_used</name><value><int>66333696</int></value></member><member><name>max_used</name><value><int>68268896</int></value></member><member><name>fragments</name><value><int>2560</int></value></member></struct>
</value>
</param>
</params>
</methodResponse>
```

As you can see, the issue still persists.

Thanks

**Comment by miconda** [comment]
There are couple of variants to print the shared memory details, the one from core was not upgraded, I just pushed a commit for it and backported to 5.7 branch for now. See the commit referenced above.
