### ISSUE TITLE
FHOSS  - java-8-openjdk-amd64 not passed & from run.sh - CLASSPATH=$CLASSPATH:log4j.properties:. making issue.

### ISSUE THREAD

**Issue by MD-star-cloud33** [kamailio/kamailio#3453]
FHOSS
DOCKER File

FROM debian:11
#MAINTAINER Yan Grunenberger <yan@grunenberger.net>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -o Acquire::Check-Valid-Until=false update
RUN apt-get -yq update
RUN apt-get -yq dist-upgrade 
RUN apt-get -yq install -f
RUN apt-get -qy install ant
RUN apt-get -qy install subversion
RUN apt-get -yq install libc6-i386
RUN apt-get -yq install dos2unix
RUN apt-get -yq install software-properties-common
RUN apt-get -yq install wget -y
RUN wget https://d3pxv6yz143wms.cloudfront.net/8.212.04.2/java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb && \
    apt-get update &&  apt-get install java-common && apt-get install -y --no-install-recommends apt-utils && \
    dpkg --install java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-amazon-corretto
ENV PATH $JAVA_HOME/bin:$PATH
RUN mkdir -p /opt/OpenIMSCore
WORKDIR /opt/OpenIMSCore
RUN svn checkout svn://svn.code.sf.net/p/openimscore/code/FHoSS/trunk FHoSS
WORKDIR /opt/OpenIMSCore/FHoSS
RUN JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 ant compile deploy 
ENTRYPOINT ["sh", "/root/run.sh"]

**run.sh**

#!/bin/bash
# Starting HSS
/bin/pwd -P 
cd /opt/OpenIMSCore/FHoSS/deploy || exit
echo "$PATH"
echo "$JAVA_HOME"
echo "Building Classpath"
CLASSPATH=$CLASSPATH:log4j.properties:.
for i in lib/*.jar; do CLASSPATH="$i":"$CLASSPATH"; done
echo "Classpath is $CLASSPATH."
$JAVA_HOME/bin/java -cp $CLASSPATH de.fhg.fokus.hss.main.HSSContainer $1 $2 $3 $4 $5 $6 $7 $8 $9

I'm getting below error.

ubuntu@ip-172-31-10-118:~/docker-IMS-VoLTE$ sudo docker logs 31f6119eb481
/bin/pwd: ignoring non-option arguments
/opt/OpenIMSCore/FHoSS
/usr/lib/jvm/java-1.8.0-amazon-corretto/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
**/root/run.sh: 27: Syntax error: end of file unexpected (expecting "done")**
/usr/lib/jvm/jdk-20
Building Classpath

Where Syntax seems okay & JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/" -> this was not passing directlt because of Debian version 11. 

Please Suggest.

**Comment by linuxmaniac** [comment]
Questions about use of Kamailio, how to be configured or errors of configuration have to be addressed to [sr-users@lists.kamailio.org](mailto:sr-users@lists.kamailio.org) email list.

This tracker is for reporting bugs in the code.
