### ISSUE TITLE
SCSCF - ob_load_api(): unable to import bind_ob  --> even after including "outbound" module || sctp_core_check_support(): SCTP API not enabled  --> even after including "sctp" module || db_check_table_version(): invalid version 4 for table presentity found, expected 5

### ISSUE THREAD

**Issue by MD-star-cloud33** [kamailio/kamailio#3455]
ob_load_api(): unable to import bind_ob  --> even after including "outbound" module
sctp_core_check_support(): SCTP API not enabled  --> even after including "sctp" module
db_check_table_version(): invalid version 4 for table presentity found, expected 5

Docker File 

FROM debian:11
#MAINTAINER Yan Grunenberger <yan@grunenberger.net>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -o Acquire::Check-Valid-Until=false update
RUN apt-get -yq update
RUN apt-get -yq dist-upgrade 
RUN apt-get -yq install git-core
RUN apt-get -yq install gcc
RUN apt-get -yq install flex
RUN apt-get -yq install bison
RUN apt-get -yq install default-libmysqlclient-dev
RUN apt-get -yq install make
RUN apt-get -yq install g++
RUN apt-get -yq install libssl-dev
RUN apt-get -yq install libcurl4-openssl-dev
RUN apt-get -yq install libsctp-dev lksctp-tools
RUN apt-get -yq install libxml2-dev
RUN apt-get -yq install libc6-i386
RUN apt-get -yq install libpcre3-dev
RUN apt-get -yq install build-essential libxslt-dev zip unzip expat zlib1g-dev curl libncurses5-dev libexpat1-dev 
RUN apt-get -yq install htmldoc rpm		
RUN mkdir -p /usr/local/src/kamailio-master
WORKDIR /usr/local/src/kamailio-master
RUN git clone https://github.com/kamailio/kamailio.git
WORKDIR /usr/local/src/kamailio-master/kamailio
RUN git checkout -b 5.6.2
#RUN make include_modules="db_mysql ims_usrloc_pcscf ims_registrar_pcscf" cfg
RUN make include_modules="db_mysql ims_usrloc_pcscf ims_registrar_pcscf xmlrpc cdp cdp_avp ims_icscf presence ims_usrloc_scscf ims_registrar_scscf ims_auth ims_charging ims_dialog ims_diameter_server ims_isc ims_ocs ims_qos outbound dispatcher" cfg
RUN make all
RUN make install
RUN apt-get -yq install default-mysql-client
#RUN apt-get -yq install mysql-client
ENTRYPOINT ["/usr/local/sbin/kamailio","-f","/usr/local/etc/kamailio/kamailio-scscf.cfg","-D"]

Getting Below error :

docker-IMS-VoLTE$ sudo docker logs 3e61c85f59b7
 0(1) INFO: <core> [core/sctp_core.c:74]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
WARNING: no fork mode
 0(1) INFO: rr [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
 0(1) INFO: rr [rr_mod.c:188]: mod_init(): outbound module not available
 0(1) ERROR: <core> [db.c:466]: db_check_table_version(): invalid version 4 for table presentity found, expected 5 (check table structure and table "version")
 0(1) ERROR: presence [presence.c:421]: mod_init(): Error during version check for db table: presentity, check database structure.
 0(1) ERROR: <core> [core/sr_module.c:993]: init_mod(): Error while initializing module presence (/usr/local/lib64/kamailio/modules/presence.so)
ERROR: error while initializing modules
 0(1) WARNING: <core> [core/mem/q_malloc.c:487]: qm_free(): WARNING: free(0) called from cdp_avp: cdp_avp_mod.c: cdp_avp_destroy(226)
 0(1) INFO: cdp [cdp_mod.c:255]: cdp_exit(): CDiameterPeer child stopping ...
 0(1) INFO: cdp [cdp_mod.c:257]: cdp_exit(): ... CDiameterPeer child stopped
 0(1) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
loading modules under config path: /usr/local/lib64/kamailio/modules/
Listening on
             udp: scscf.net1.test [172.18.0.3]:6060
Aliases:
             *: scscf.net1.test:*

**Comment by linuxmaniac** [comment]
Questions about use of Kamailio, how to be configured or errors of configuration have to be addressed to [sr-users@lists.kamailio.org](mailto:sr-users@lists.kamailio.org) email list.

This tracker is for reporting bugs in the code.
