### ISSUE TITLE
An old and unsupported gcc version  (1.3.0), compile at your own risk!

### ISSUE THREAD

**Issue by Sivanesh1992** [kamailio/kamailio#3463]
Hi I am following below link to enable voice call by using Kamailio Ims

https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/

I have Clone the Kamailio repository and checkout 5.3 version of repository

$ mkdir -p /usr/local/src/
$ cd /usr/local/src/
$ git clone https://github.com/herlesupreeth/kamailio
$ cd kamailio
$ git checkout -b 5.3 origin/5.3

and Generate build config files

$ cd /usr/local/src/kamailio
$ make cfg

while doing make command i am getting below error.

kamailio$ sudo make cfg
make -C src/ cfg 
make[1]: Entering directory '/usr/local/src/kamailio/src'
target architecture <x86_64>, host architecture <x86_64>
Makefile.defs:1052: You are using an old and unsupported gcc version  (1.3.0), compile at your own risk!
making config...
rm -f modules.lst
make --no-print-directory modules.lst
saving modules list...
make[1]: Leaving directory '/usr/local/src/kamailio/src'

my gcc version is 

$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Please help me to resolve the issue

**Comment by henningw** [comment]
The (old) Kamailio version 5.3.x probably does not recognize the newer gcc. But this is usually harmless, but you should consider using a newer Kamailio version. Please note that this tracker is for reporting bugs in the source code, and not user questions. These questions should be addressed to our "sr-users" list. I am closing this issue here.
