### ISSUE TITLE
mk_proxy(): could not resolve hostname

### ISSUE THREAD

**Issue by ajosebar** [kamailio/kamailio#3467]
I have Kamailio 5.6 on Debian 11.
I need to use the function forward within a routing block in my configuration file:
forward("udp:192.168.28.51:5060");
But when I start the kamailio service I got:
CRITICAL: <core> [core/proxy.c:264]: mk_proxy(): could not resolve hostname: "udp:192.168.28.51:5060"
The same occurs when I use the dns nane :
forward("udp:raspberry3.emtelco.co:5060");

Any ideas ?
Regards

**Comment by miconda** [comment]
Questions about kamailio.cfg have to be addressed to sr-users@lists.kamailio.org mailing list. This tracker is for reporting bugs in source code.
