### ISSUE TITLE
auto uac_restore_from() : Restore with errors 

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#3498]
### Description

Kamailio receives call and changes originating number to anonymous using uac_replace_from() with auto restore and password. Info is stored in vsf parameter of Record-Route

Original From Uri is sip:123456789@1.1.1.1:5060
New From Uri is "sip:anonymous@anonymous.invalid"

When originating IP sends an ACK after the 200 OK, it sends a different IP on the From header 

From Uri received on the ACK sent to Kamailio : sip:123456789@2.2.2.2:5070
From Uri sent by kamailio after restore :  sip:anonymous@bnlnzmlu4s.hnv2a'_lid

The Uri sent by Kamailio is variable and it's not always the same.

#### Reproduction

I've annexed to this issue two call XMS (Outgoing and Incoming) that creates this scenario. 

Kamailio is configured to change the From URI to sip:anonymous@anonymous.invalid with uac_replace_from() with auto restore and password

### Additional Information

version: kamailio 5.2.1 (x86_64/linux) 947769
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144 MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 16MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 947769
compiled on 11:41:21 Apr  5 2022 with gcc 4.8.5

* **Operating System**:
CentOS 7 
```
[Originating_XML.txt](https://github.com/kamailio/kamailio/files/11898066/Originating_XML.txt)
[Terminating_XML.txt](https://github.com/kamailio/kamailio/files/11898067/Terminating_XML.txt)

**Comment by henningw** [comment]
Thanks for the report. Please updating to a newer (supported) version of Kamailio, e.g. 5.6.x or 5.7.x. The 5.2.1 is really old. There have been several fixes and improvements related to the uac module in the last years. If the problem still can be reproduced with a newer version, please re-open the issue, thank you.
