### ISSUE TITLE
auto uac_restore_from() : Restore with errors

### ISSUE THREAD

**Issue by duarterocha91** [kamailio/kamailio#3500]
### Description

Kamailio receives call and changes originating number to anonymous using uac_replace_from() with auto restore and password. Info is stored in vsf parameter of Record-Route

Original From Uri is sip:123456789@1.1.1.1:5060
New From Uri is "sip:[anonymous@anonymous.invalid](mailto:anonymous@anonymous.invalid)"

When originating IP sends an ACK after the 200 OK, it sends a different IP on the From header

From Uri received on the ACK sent to Kamailio : sip:123456789@2.2.2.2:5070
From Uri sent by kamailio after restore : sip:[anonymous@bnlnzmlu4s.hnv2a](mailto:anonymous@bnlnzmlu4s.hnv2a)'_lid

The Uri sent by Kamailio is variable and it's not always the same.

#### Reproduction

I've annexed to this issue two call XMS (Outgoing and Incoming) that creates this scenario.

Kamailio is configured to change the From URI to sip:[anonymous@anonymous.invalid](mailto:anonymous@anonymous.invalid) with uac_replace_from() with auto restore and password

In order to rule out problems in the rest of my code i've used the base kamailio.cfg with minimum changes as possible and added this code right before PSTN being called :

```
    $var(New_From_uri) = "sip:anonymous@anonymous.invalid" ;
    uac_replace_from("","$var(New_From_uri)");
```

I have the following configurations for uac :

```
loadmodule "uac.so"
modparam("uac","restore_mode","auto")
modparam("uac","restore_from_avp","$avp(vsf)")
modparam("uac","restore_to_avp","$avp(vst)")
modparam("uac","restore_passwd","password123")

modparam("rr", "append_fromtag", 1)
```

### Additional Information

```
version: kamailio 5.7.1 (x86_64/linux) 4238e4
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 4238e4
compiled on 12:39:30 Jun 29 2023 with gcc 4.8.5
```

* **Operating System**:

CentOS7

Please let me know if i can be of any help on testing.

Cheers

[Originating_XML.txt](https://github.com/kamailio/kamailio/files/11914634/Originating_XML.txt)
[Terminating_XML.txt](https://github.com/kamailio/kamailio/files/11914635/Terminating_XML.txt)

**Comment by miconda** [comment]
The variant with parameters in Record-/Route headers relies on the fact that UAs use always the same From/To display and URI values. If that cannot be ensured, you can switch to the variant of using dialog module that keeps the values in dialog variables.

Alternative, if the UAs don't care of having always the same From/To content, you can just replace always without restoring.
