### ISSUE TITLE
Option to not add received via param

### ISSUE THREAD

**Issue by zusrut** [kamailio/kamailio#3515]
### Description
Hello. Probably I'm doing something wrong but I can't get rid of **received** parameter in the **Via** header in responses from kamailio by websocket transport.

According [RFC 7118](https://datatracker.ietf.org/doc/rfc7118/):
``
      When a SIP WebSocket Server receives a request, it MAY decide not
      to add a "received" parameter to the top Via header.  Therefore,
      SIP WebSocket Clients MUST accept responses without such a
      parameter in the top Via header regardless of whether the **Via**
      "sent-by" field contains a domain name.
``

### Expected behavior

For responses to websocket transport have a way to not add **received** parameter in **Via** header

#### Actual observed behavior

Responses to OPTION or REGISTER methods through websocket got **received** containing IP we want to not show to the end users.

### Possible Solutions

maybe add a param in **tm** module or something

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.2.1 (x86_64/linux) 
```
and
```
kamailio 5.6.1 (x86_64/linux) b36a13
```

**Comment by miconda** [comment]
Does the Via has `rport` parameter? Or did you use `force_rport()`?

**Comment by zusrut** [comment]
Hello. I tested different options: `force_rport()` adds `rport`, but `received` is still present w/o force_rport.

**Comment by zusrut** [comment]
it is still actual enhancement request

**Comment by HieuAnh87** [comment]
Did u have solution for this? got same issue.
