### ISSUE TITLE
SIP pinger does not use socket advertized address

### ISSUE THREAD

**Issue by neutrino38** [kamailio/kamailio#352]
When using Kamailio on a host with a natted address

listen=10.1.2.3 advertize 20.20.20.20

SIP options sent by NATHELPER module includes a via with the private IP address rather than the public one. It cause OPTIONS not to be answered by UAs.

**Comment by miconda** [comment]
A patch has been pushed to master branch, can you try it (4da31d56f4b1e18fc4232c5174637c858c75e9db)?

If the issue is still there, reopen this item.
