### ISSUE TITLE
failed to find command radius_www_authorize (params 1)

### ISSUE THREAD

**Issue by kachallah** [kamailio/kamailio#3525]
Hello everyone,
I'm trying to authenticate kamailio users using freeradius but I get the following error message when I try to start kamailio:
ERROR: <core> [core/cfg.y:3762]: yyparse(): cfg. parser: failed to find command radius_www_authorize (params 1).

l'm using this link : kamailio.org/docs/modules/devel/modules/auth_radius.html#idm46
Thanks for your help.

**Comment by miconda** [comment]
Discussions about use of Kamailio and its configuration file have to be done on sr-users@lists.kamailio.org mailing list.

This tracker is for reporting issues in the C code of the application.
