### ISSUE TITLE
Halo Experts,  really appreciated if I can get some assistance on the start failure issue when doing patching from kamailio 5.5.4 to 5.5.6 with the error, 'terminating due to SIGCHLD' . Thanks a lot! 

### ISSUE THREAD

**Issue by Binliu666** [kamailio/kamailio#3533]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by henningw** [comment]
Please address usage questions to our sr-users mailing list. The issue tracker is for reporting bugs in the code and providing extensions.

**Comment by henningw** [comment]
Mailing lists can be found e.g. here https://lists.kamailio.org/mailman3/postorius/lists/

**Comment by Binliu666** [comment]
Thanks for the help!
