### ISSUE TITLE
Makefile.radius : about radius library selection 

### ISSUE THREAD

**Issue by ycaner06** [kamailio/kamailio#354]
Hello;
    Makefile selects wrong radius library on make and then gives error. Makefile always select radiusclient-ng even if freeradius-client has been installed.i am not good at Makefile s so could you check Makefile.radius .

---------------- ERROR -------------
CC (gcc) [M acc_radius.so]              acc_radius_mod.o
In file included from acc_radius_mod.c:44:
../../lib/kcore/radius.h:35:30: warning: radiusclient-ng.h: No such file or directory
acc_radius_mod.c: In function âinit_acc_radâ:
acc_radius_mod.c:264: warning: implicit declaration of function â-rc_read_configâ-

------------------------------------

**Comment by miconda** [comment]
You have to set the variable FREERADIUS=1 before compiling the module:

```
FREEEADIUS=1 make modules modules=modules/auth_radius
```

Or:

```
export FREERADIUS=1
```
then the usual make commands.

I guess that is missing in the documentation, if you like to do a patch, I will merge it, I am traveling these days.

**Comment by ycaner06** [comment]
it is ok after set FREERADIUS . i changed documentations and added info about freeradius-client. But there is problem about radiusclients. if radius server delay to reply , that means kamailio's childs waits to response. after 1 minute , kamailio cannot response and all calls get 408 timeout. i am trying to solve this problem. radiusclient can cut kamailio's legs :)

**Comment by ycaner06** [comment]
Closing the issue. Thanks
