### ISSUE TITLE
关于acc_cdr的问题，请教一下

### ISSUE THREAD

**Issue by kqbi** [kamailio/kamailio#3541]
目前进行一通呼叫后，在acc表中可以看到Invite、ack及bye的记录详情并带有时间，acc_cdrs表中只有start_time及end_time,是对应invite和bye的。

现在我想在acc_cdrs中增加ack的时间我该如何去做呢？有没有大佬能解答一下？万分感谢！！！

**Comment by linuxmaniac** [comment]
Para preguntas debe utilizar el mailing list "sr-users" del projecto. Un saludo.
