### ISSUE TITLE
I need to test ISUP to SIP-I conversion Kamailio softswtich..I am sending 

### ISSUE THREAD

**Issue by vivekkirsh** [kamailio/kamailio#3542]
Hi All,
        I need to test ISUP to SIP-I conversion at Kamailio Softswitch .this SIP-I conversion need to verify SIpp-SIP end point.

**my architecure flow as below as:-**
                                          isup                                              sipi-i/sip-t
 MTG 200 Trunk Gatway -----------> Kamailio Softswitch ----------------> SIPP.

How to make it happend in via Kamailio Softswitch .and what are the configurations need to make in Kamailio Softswitch

**Comment by miconda** [comment]
If you need help with using/configuring Kamailio, you have to address your questions to sr-users@lists.kamailio.org mailing list.

This tracker is for reporting issues in the C code of Kamailio.

**Comment by vivekkirsh** [comment]
Okay.Thak you @miconda
