### ISSUE TITLE
Delete tag `orig`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3575]
I use command line completion when I work in git.  In all repositories I have, the upsteam is always called `origin`, as this is the default from git.  So typing `or<TAB>` does complete the things correctly.  Since Kamailio has a tag `orig` the completion completes to `orig`, not to `origin`.  This is disturbing.  If I use as upstream `upstream` only for Kamailio, then the problem is seemingly gone, until I forget that I have to use `upstream` and want to type `origin`.

As there is no use for the 20 years old `orig` tag in git, delete it.

**Comment by linuxmaniac** [comment]
Please use the sr-dev@lists.kamailio.org mail list for this kind of things
