### ISSUE TITLE
cdr_json_pre_encoded_prefix (string) wrong discribe

### ISSUE THREAD

**Issue by olegans1972** [kamailio/kamailio#3584]
I try to do

modparam("acc_json", "cdr_extra", "spx_resp=$avp(spx_resp)")
modparam("acc_json", "cdr_json_pre_encoded_prefix", "spx_resp")
 
 
do restart and get next mistakes:
 
sep 22 14:17:15 vms-vms-spx-1 kamailio[581922]: ERROR: <core> [core/modparam.c:169]: set_mod_param_regex(): parameter <cdr_json_pre_encoded_prefix> of type <1:string> not found in module <acc_json>

сен 22 14:17:15 vms-vms-spx-1 kamailio[581922]: CRITICAL: <core> [core/cfg.y:3686]: yyerror_at(): parse error in config file /etc/kamailio_vmsspx/modules.cfg, line 125, column 63: Can't set module parameter

sep 22 14:17:15 vms-vms-spx-1 kamailio[581922]: ERROR: bad config file (1 errors) (parsing code: 0)

sep 22 14:17:15 vms-vms-spx-1 systemd[1]: kamailio_vmsspx.service: Control process exited, code=exited status=255

sep 22 14:17:15 vms-vms-spx-1 systemd[1]: kamailio_vmsspx.service: Failed with result 'exit-code'.

### Troubleshooting

it's a bug at the documentation or in the code
I see next:
https://www.kamailio.org/docs/modules/devel/modules/acc_json.html#acc.p.cdr_json_pre_encoded_prefix

But in the code I see a litle bit another
https://github.com/kamailio/kamailio/blob/5.5/src/modules/acc_json/acc_json_mod.c#L95C5-L95C27

Please fix it either in the code or documentation 

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Possible Solutions

modparam("acc_json", "cdr_extra", "spx_resp=$avp(spx_resp)")
modparam("acc_json", "cdr_pre_encoded_prefix", "spx_resp")

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
[opodguyko@vms-vms-spx-1 ~]$ kamailio -version

version: kamailio 5.5.3 (x86_64/linux) b02728-dirty

flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED

ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB

poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.

id: b02728 -dirty

compiled on 15:35:46 Dec 15 2021 with gcc 8.3.1
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
It should be already fixed in the docs by:

  - https://github.com/kamailio/kamailio/pull/3582

Backports to active stable branches will follow, however 5.5.x series is out of maintenance time frame, you have to upgrade to 5.6.x or 5.7.x.
