### ISSUE TITLE
Kamailio Behind nat.   How  Record-Route should  be added ？

### ISSUE THREAD

**Issue by codenot** [kamailio/kamailio#3586]
UA1(192.168.0.1)  --> kamailio (internal:192.168.0.2  public:1.1.1.1) -->  UA2(2.2.2.2)
if in  UA1 INVITE, I write KSR.rr.record_route().  
so  UA2(2.2.2.2) received sip msg (Record-Route: <sip:1.1.1.1:7080>), so Kamailio can received BYE/ACK from UA2.
but，Kamailio can't received BYE/ACK  from UA1.

if in UA1 INVITE, i write KSR.rr.record_route_advertised_address("192.168.0.2"), then Kamailio can received  BYE/ACK  from UA1, but not from UA2.

what can i do, let Kamailio receive BYE/ACK  from both sides ？

**Comment by miconda** [comment]
Questions about using/configuring kamailio have to be addressed to sr-users mailing list (which it seems you did, so wait for answers there). The tracker is for issue related to the C code.
