### ISSUE TITLE
Typos at https://www.kamailio.org/docs/modules/devel/

### ISSUE THREAD

**Issue by dilyanpalauzov** [kamailio/kamailio#3596]
At https://www.kamailio.org/docs/modules/devel/ is spelled

CALL_CONTROL | Conector to call_control application
-- | --
EVREXEC | Execut event routes at startup on dedicated processes

It shall be co**NN**ector and execut**E**.

Likewise for https://www.kamailio.org/docs/modules/5.8.x/ , https://www.kamailio.org/docs/modules/5.7.x/, https://www.kamailio.org/docs/modules/5.6.x/ …

**Comment by miconda** [comment]
Thanks, fixed for 5.6, 5.7 and devel, the currently active versions.
