### ISSUE TITLE
cdp: Not possible to load module with older openssl version than 1.1.0

### ISSUE THREAD

**Issue by mtryfoss** [kamailio/kamailio#3600]
### Description

After adding TLS support to the CDP module, it's no longer possible to load on systems running a version of openssl older than 1.1.0.

#### Reproduction

Run on system with openssl older than 1.1.0.

#### Log Messages

```
ERROR: <core> [core/sr_module.c:599]: ksr_load_module(): could not open module </usr/local/kamailio-devel/lib64/kamailio/modules/cdp.so>: /usr/local/kamailio-devel/lib64/kamailio/modules/cdp.so: undefined symbol: SSL_CTX_set_max_proto_version
```

### Possible Solutions

I've made a local change based on the approach used in the tls module for different versions of openssl.
Do you want me to open a PR for this, or do you want this module clean?

Currently I do not have any possibility to test it's actually working, but at least it compiles/loads and makes to module possible to use without encryption.

Another solution might be to just include TLS support if the openssl version on the system is 1.1.1 or newer. Else, just do not support it.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
master
```

* **Operating System**:

```
CentOS 7.9
```

**Comment by miconda** [comment]
Supporting older version of libssl is an overhead that should be avoided, because those versions are out of maintenance. Enabling tls in cdp only if libssl is a supported version at this moment would be good, if you can make a PR for it would be great of course.

**Comment by mtryfoss** [comment]
PR created.

**Comment by miconda** [comment]
PR merged, thanks!
