### ISSUE TITLE
ubuntu 22.04 - kamailio 5.7.2 & master - compile tls_wolfssl error

### ISSUE THREAD

**Issue by badien** [kamailio/kamailio#3610]
Compile tls_wolfssl on ubuntu 22.04 error:
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
./configure: line 6164: syntax error near unexpected token `2.4.2'
./configure: line 6164: `LT_PREREQ(2.4.2)'
make[2]: *** [Makefile:21: ../../../misc/external/wolfssl/build/include/wolfssl/options.h] Error 2
make[1]: *** [Makefile:508: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio-5.7/src'
make: *** [Makefile:34: all] Error 2

Please check, thanks

**Comment by space88man** [comment]
> Compile tls_wolfssl on ubuntu 22.04 error: checking dependency style of gcc... gcc3 checking whether make supports nested variables... (cached) yes ./configure: line 6164: syntax error near unexpected token `2.4.2' ./configure: line 6164: `LT_PREREQ(2.4.2)' make[2]: *** [Makefile:21: ../../..

Do you have libtool installed?

**Comment by badien** [comment]
yes, i do, its version on ubuntu is 2.4.6

**Comment by badien** [comment]
tried to install wolfssl separately (master successful only, tags/v5.6.2/3-stable error script) then recompile kamailio, still have error above.

**Comment by space88man** [comment]
Here's a minimal development environment - if it works for you - then likely it is due to your main development environment:

-----
```
docker build  --tag ubuntu:devel.1 -f ./Dockerfile
# run the container
docker run -it --rm ubuntu:devel.1 /bin/bash

# ... an inside the container shell ...
#!/bin/bash

mkdir -p /builddir/build/wolfssl
cd /builddir/build/wolfssl/

git clone https://github.com/wolfSSL/wolfssl.git

cd wolfssl/

git checkout v5.6.3-stable

./autogen.sh
./configure \
        --enable-all --enable-pkcs11 --enable-static --enable-writedup \
        --disable-aligndata --disable-shared --disable-examples \
        --disable-jni --disable-crl-monitor
```


-----
```
# Dockerfile
# create a minimal development container
from ubuntu:22.04
run apt-get update -y; \
    apt-get install -y git gcc g++ flex bison libmysqlclient-dev make autoconf pkg-config \
    automake libtool libssl-dev libcurl4-openssl-dev libxml2-dev libpcre3-dev \
    bsdmainutils
```

**Comment by badien** [comment]
Thanks for help, i did it. I think the problem before is that i have installed libwolfssl-dev (5.2.0 only) on ubuntu and it is not compatible.

**Comment by faratell** [comment]
Hello badien. Can you solve this problem. I have such problem. Can you help me?
