### ISSUE TITLE
nat_traversal: Builds wrong URI for IPv6, bad URI parsing

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#362]
nat_traversal doesn't handle IPv6 keepalives. It doesn't add [ and ] around IPv6 addresses and there's some bad parsing of SIP URI's in the code, assuming the first colon after "sip:" (not sips or tel) is a separator for port numbers. A better parser would be nice to use.

**Comment by oej** [comment]
Right now it causes crashes and core dumps when using IPv6

**Comment by miconda** [comment]
nat_traversal was not much on focus during past years because initial developers are gone, and a lot of us are actually using nathelper for the nat traversal needs. If you have a fix, just push it to the repository.

**Comment by oej** [comment]
I think we can add to the documentation "Doesn't support IPv6" - because it requires a lot of work to do anything else. We have also focused on Nathelper now. - ok?

**Comment by oej** [comment]
Added a comment to the README about lacking IPv6 support.
