### ISSUE TITLE
Add function `secsipid_sign_privkey` to SECSIPID module

### ISSUE THREAD

**Issue by whosgonna** [kamailio/kamailio#3620]
### Description

Add a function `secsipid_sign_privkey(sheaders, spaypload, keyData)` that accepts a pseudovariable with the PEM data analagous to the difference between the following functions:

- `secsipid_build_identity(origTN, destTN, attest, origID, x5u, keyPath)`
- `secsipid_build_identity_prvkey(origTN, destTN, attest, origID, x5u, keyData)`

With the difference being that ``secsipid_build_identity()` takes a key file as it's argument, and ``secsipid_build_identity_privkey()` allows having the key data in a pseudovariable.

**Comment by miconda** [comment]
Should be now in master branch (development). It needs latest secsipid library.

**Comment by whosgonna** [comment]
Thank you. I think I'll be able to test tomorrow.
