### ISSUE TITLE
PLMN 31501 , VoLTE IMS Kamalio

### ISSUE THREAD

**Issue by nazib123** [kamailio/kamailio#3624]
Hi,
I was able to test the PLMN 00101 for VoLTE, but unable to test it with other PLMNs. I am specifically looking to have a successful test with PLMN31501. VoLTE is not enabling once I configure it.

I followed this https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/

Any one has experience for PLMN 315?

**Comment by linuxmaniac** [comment]
Questions about using/configuring kamailio have to be addressed to sr-users mailing list . The tracker is for issue related to the C code.
