### ISSUE TITLE
[RFC RPM Packaging] Rename libks to match FreeSWITCH el7 libks2

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#3625]
### Description
kamailio RPM repos include libks (v2)
FreeSWITCH for EL7 distributes libks (v1) libks2 (v2)  — the reason is to support their packages
signalwire-client-c(requires libks) and signalwire-client-c2(requires libks2).

RFC: rename the kamailio package libks to libks2 to be consistent 

### Expected behavior

Currently rebuilding FreeSWITCH signalwire-client-c and signalwire-client-c2 and installing mixing in the 
kamailio RPM can lead to confusion

**Comment by sergey-safarov** [comment]
For now Kamailio module [stirshaken](https://github.com/kamailio/kamailio/tree/master/src/modules/stirshaken) is not compatible with libks2.
So first we need update stirshaken Kamailio module first.

**Comment by space88man** [comment]
> For now Kamailio module [stirshaken](https://github.com/kamailio/kamailio/tree/master/src/modules/stirshaken) is not compatible with libks2. So first we need update stirshaken Kamailio module first.

I see the version in the kamailio repo as 2.0.2 - isn't that  same as Signalwire's libks2 (API wise)? FreeSWITCH has libks-1.8.2 and libks2-2.0.0. I assume it is from the same repo but starting at different tags.

**Comment by sergey-safarov** [comment]
I have tried to use libks2 and found incompatible issue.
Then I reverted to libks 1.8.4
Current lob version you can find at
https://rpm.kamailio.org/centos/9/master/master/x86_64/Packages/l/

**Comment by space88man** [comment]
The current supported version in kamailio master is libks-1.8.4 - this does not clash with Signalwire's naming convertion.
