### ISSUE TITLE
wrong code for new mod param of pdt module

### ISSUE THREAD

**Issue by doktorsip** [kamailio/kamailio#3626]
### Description

This new code in pdttree.c is not correct for this new pdt mode, it just print's a debug log instead of error. The return value should be 0 instead of -1 in case _pdt_mode is 1 otherwise it will still not start.

```
if(_pdt_mode & 1) {
			LM_DBG("prefix already allocated [%.*s/[%.*s] - ignoring\n",
					sp->len, sp->s, sd->len, sd->s);
			return -1;
		} else {
			LM_ERR("prefix already allocated [%.*s/[%.*s]\n", sp->len, sp->s,
					sd->len, sd->s);
			return -1;
		}
````

### Additional Information

 
* **Operating System**:

**Comment by miconda** [comment]
Thanks for spotting it. Fixed.
