### ISSUE TITLE
Sequential fork with different Call-Ids

### ISSUE THREAD

**Issue by vbatistela** [kamailio/kamailio#3630]
I have a scenario on wich requires sequential fork (up to 30 possible destinations) with different
Call-ID for each leg. I am using topoh module enabled, but it always puts the same Call-ID.
I think a possible solution would be to modify the callid prefix parameter of
topoh module.
Instead of storing a string, it could store the name of a variable that could then have
its content changed within the script. So within the "branch_route" I could modify
this variable by putting $tU  ( To URI Username of the outgoing Invite).
In this case the new Call-ID generated by topoh module would be a function of the
"To URI Username" that is different for each leg.
Is this proposal technically feasible or  is there  a different solution for this scenario?

Additional information:

kamailio Version - output of kamailio -v

version: kamailio 5.7.1 (x86_64/linux) 4238e4
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 4238e4
compiled on 13:26:58 Jun 28 2023 with gcc 8.5.0

 Operating System: CentOS Linux 8
 CPE OS Name: cpe:/o:centos:centos:8
 Kernel: Linux 4.18.0-348.7.1.el8_5.x86_64
 Architecture: x86-64

**Comment by linuxmaniac** [comment]
Questions about using/configuring kamailio have to be addressed to sr-users mailing list . The tracker is for issue related to the C code.
