### ISSUE TITLE
config file: defexps not working in modparam

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#3631]
### Description

When an ID is defined using `#!defexps` it cannot be used in modparam

### Troubleshooting

```
#!define TEST1 "key=s:value"
## this works
modparam("pv", "varset", TEST1)

# in shell: export TEST2='key=s:value'
#!defenvs TEST2
modparam("pv", "varset", TEST2)

# this does not work
#!defexps TEST3  "key=s:value"
modparam("pv", "varset", TEST3)

0(2437437) CRITICAL: <core> [core/cfg.y:3900]: yyerror_at(): parse error in config file kamailio.cfg, line 85, column 26-32: syntax error


```

#### Reproduction

* in config file, define ID with `#!defexps` then use in `modparam()`

```
#kamailio.cfg
loadmodule "pv.so"
#!define TEST1 "key=s:value"                                                                                             
#!defenvs TEST2                                                                                                          
#!defexps TEST3 "key3=s:value3"                                                                                          
modparam("pv", "varset", TEST1)
modparam("pv", "varset", TEST2)
modparam("pv", "varset", TEST3)

# in shell
export TEST2='"key2=s:value2"

kamailio -f kamailio.cfg -c
```

**Comment by linuxmaniac** [comment]
I would say you're missing the quotes. Does it work if you set the env variable using '\"whatever\"' ?

**Comment by space88man** [comment]
> I would say you're missing the quotes. Does it work if you set the env variable using '"whatever"' ?

The  env variable (`#!defenv ....`) works; it is (`#!defexps ...`) inline in the script that triggers the parsing error when passed to `modparam(....., TEST3`).

**Comment by miconda** [comment]
Indeed it was a problem enclosing the result in double quotes. I pushed a commit for it, reopen if still a problem.
