### ISSUE TITLE
kamailio 5.7.2 - tls_wolfssl - failed: Free fragment not found

### ISSUE THREAD

**Issue by badien** [kamailio/kamailio#3634]
tls_wolfssl falied:
Nov  9 18:56:32 server99 /usr/local/sbin/kamailio[199263]: ERROR: <core> [core/mem/q_malloc.c:297]: qm_find_free(): qm_find_free(0x7f1a9117a000, 3216); Free fragment not found!
Nov  9 18:56:32 server99 /usr/local/sbin/kamailio[199263]: ERROR: <core> [core/mem/q_malloc.c:430]: qm_malloc(): qm_malloc(0x7f1a9117a000, 3216) called from tls_wolfssl: tls_init.c: ser_malloc(220), module: tls_wolfssl; Free fragment not found!

### Description
- Ubuntu 22.04
- kamailio 5.7.2
- wolfssl 5.6.3-stable
- hardware: 
 + CPU(s) 28 -  Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
 + memory 32GB
- testing on some users: using JWT token (AWS cognito) authentication via header (may be message too large)
- don't have issue with 64GB memory (other server) yet

#### Log Messages

```
Nov  9 18:56:32 server99 /usr/local/sbin/kamailio[199263]: ERROR: <core> [core/mem/q_malloc.c:297]: qm_find_free(): qm_find_free(0x7f1a9117a000, 3216); Free fragment not found!
Nov  9 18:56:32 server99 /usr/local/sbin/kamailio[199263]: ERROR: <core> [core/mem/q_malloc.c:430]: qm_malloc(): qm_malloc(0x7f1a9117a000, 3216) called from tls_wolfssl: tls_init.c: ser_malloc(220), module: tls_wolfssl; Free fragment not found!
```
### Possible Solutions

i am trying to enable mem_join

### Additional Information

```
version: kamailio 5.7.2 (x86_64/linux) 7af9dc
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 7af9dc 
compiled on 20:15:34 Nov  9 2023 with gcc 11.4.0
```

* **Operating System**:

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by miconda** [comment]
Kamailio uses its own memory manager, so even you have a lot of memory in that system, you have to instruct Kamailio how much to use via `-m` and `-M` parameters. In this case `-m` is important, be sure you have at least 256 (if you have a lot of tls connections, then make it even higher).

If `-m` value was already higher or happens again later after making it higher, reopen.
