### ISSUE TITLE
not matching myself when using alt TLS port 

### ISSUE THREAD

**Issue by zeusca** [kamailio/kamailio#3638]
### Description
When having Kamailio listen for TLS on some alternative port other than 5061 - the `myself` condition doesn't match.

#### Reproduction

`kamailio.cfg`
enable_tls=yes
tls_port_no=9061
listen=tls:192.168.2.2:9061 advertise "mydomain.com":9061

```
request_route {
    if (uri==myself)
        xlog("L_INFO", "myself matched\n");
    else
        xlog("L_INFO", "myself didn't match\n");
}
```

Send a SIP request to Kamailio over TLS on port 9061 but RURI like `192.168.2.2;transport=tls` and observe the log output.

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
OPTIONS sip:192.168.2.2;transport=tls SIP/2.0
Via:SIP/2.0/TLS 10.10.10.10:8934;branch=z9hG4bKfhsdjh2478sdfh256
From:<sip:10.10.10.10>;tag=834848136-1699739
To:<sip:192.168.2.2>
Call-ID:SSE2150339541111236507
CSeq:100 OPTIONS
Max-Forwards:0
Content-Length:0
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.6.4 (x86_64/linux) 239d0a
```

* **Operating System**:

```
Debian GNU/Linux 11 (bullseye)
```

**Comment by zeusca** [comment]
Correction: listen should include transport, of course.

`listen=tls:192.168.2.2:9061 advertise "mydomain.com":9061`

**Comment by miconda** [comment]
You match using `uri` (request-uri) which does not match on port, as the default one for tls is 5061. For further discussions about using kamailio and its configuration file, use sr-users mailing list.
