### ISSUE TITLE
ims_qos - rx_avp.c: rx_add_framed_ip_avp call to inet_pton with IPv6 fails due to [<ip>] format

### ISSUE THREAD

**Issue by dschaafsma** [kamailio/kamailio#364]
This is an issue in 4.2, not sure about how 4.3+ currently handle this call path.
rx_add_framed_ip_avp() is called with an IP formatted as "[2001:db8::ff00:42:8329]"
This passes the INET6_ADDRSTRLEN check due to '::' compression, but inet_pton will fail to parse.

One possible hack/fix is:
 check for leading/trailing '[]' for V6 addrs and strip them prior to calling inet_pton

**Comment by miconda** [comment]
Hopefully @ngvoice, @jaybeepee or @richardgood can check it.

If you think you can have a patch to fix it, then just make a pull request here on github.

**Comment by miconda** [comment]
I pushed a patch for it in master branch. Testing is still needed.
