### ISSUE TITLE
group include ktls no longer works after 7f07a6ef9ae90baee4281394d0dcf505b30c8fcb

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#3660]
After 7f07a6ef9ae90baee4281394d0dcf505b30c8fcb, building the ktls group doesn't work as it's not  included in the #else statement.  I don't have a need for ktlsa at this point.

**Comment by linuxmaniac** [comment]
Thanks!

**Comment by amessina** [comment]
Thanks @linuxmaniac would this be ok to backport to 5.7?

**Comment by linuxmaniac** [comment]
already done! :-)
