### ISSUE TITLE
Redefine Advertised socket URI when used haproxy protocol

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3667]
### Description
When used haproxy protocol then from client perspetive TCP connection established to loadbalancer IP address.
Real Kamailio listener may be IPv6 and expected to see `$RAut` value with IP of load balancer IP.
Really I can see for first message from the client
```
sip:2600::6:45060;transport=tcp
```
For second message
```
Advertised socket URI: sip:[2600::6]:5060
```
For first case missed `[]` in the IP and expected to see loadbalancer IPv4 because client use IPv4 to establish connection to Kamailio.
 
### Expected behavior
Used loadbalancerserver IP from haproxy protocol for `$RAut` value and for `Record-Route` headers generation.

**Comment by miconda** [comment]
I don't really understand what you describe and what you want. The development version has the option to set also the protocol for advertised address in listen parameter, no longer taking it from local socket address. So you can even have `listen=udp.1.2.3.4:5060 advertise tls:3.4.5.6:8000`, you just have to take care that the network layer does the proper transmission.

I think this is covering everything needs in terms of listen socket and advertised address.

If you don't get what you need with master branch, then open a new issue where you put the relevant snippets of config, with some logging from config with xlog() to show what is printed for variables and what you expect, plus pcap file with corresponding traffic.
