### ISSUE TITLE
about accounting modules

### ISSUE THREAD

**Issue by ycaner06** [kamailio/kamailio#367]
Hello;
i realized that a call and acc module don't have any joint. even if acc is failed ,call continues. So that a accounting leak. i wonder that when accounting failed , can be trigger a event to log or something else. Maybe, we can stop the call dialog module. what do you think about it?

**Comment by linuxmaniac** [comment]
Please use mailing list for questions

**Comment by ycaner06** [comment]
Well, i think it isnt a question. it is a feature request for dont miss any accounting data.so try to find a solution to improve accounting modules.
For example , we can understand a function run or failed with " if()" in a transcation.
if a function failed , it can send error reply with sl_send_reply. but there isnt any control for acc modules.
