### ISSUE TITLE
max_branches settings are not effective

### ISSUE THREAD

**Issue by 2954456878** [kamailio/kamailio#3678]
![image](https://github.com/kamailio/kamailio/assets/88914706/c325af99-f556-497c-9bbb-47d6bfe61742)
max_branches=30
Following this route, the branch value will be doubled，only 15 branches can be created

**Comment by 2954456878** [comment]
After adjusting MAX_BRANCHES_LIMIT, I can create more than 30 branches, but I don't know if there are any other problems

**Comment by miconda** [comment]
This tracker is for reporting bugs in the C code, for questions about using or configuring Kamailio, use sr-users@lists.kamailio.org mailing list.
