### ISSUE TITLE
t_uac_send parser does not like exclamation or other non alphabetic characters in Contact header

### ISSUE THREAD

**Issue by xaled1** [kamailio/kamailio#3682]
Hi

there is an issue with the SIP parser for the t_uac_send function

https://www.kamailio.org/docs/modules/devel/modules/tm.html#tm.f.t_uac_send

If I call this function for example:

```
 t_uac_send("INVITE", "sip:test@123.123.123.123:5060", "", "" ,"Content-Type: text/plain\r\nContact: <sip:85951b3d-096c-95d6-5f05-4f38095aca9f@172.17.64.120:5060;transport=tcp>;+u.sip!devicename.ccm.cisco.com=\"SEP5486BC7F2BBC\"", "Testbody")
```

Then the resulting request is broken - it's probably due to a character (exclamation mark?) in the Contact header.... I tested it with a call from kemi, but it probably also occurs when you run it with a normal kamailio -script tests

**Comment by miconda** [comment]
If you run with debug=3 in kamailio.cfg, can you spot any hint in the syslog messages about what happens?

**Comment by xaled1** [comment]
Any plans to fix it?
