### ISSUE TITLE
sip_trace(address, "", "t") uses the duplicate_uri for replies from auth_challenge instead of address argument in sip_trace()

### ISSUE THREAD

**Issue by pnlarsson** [kamailio/kamailio#3700]
### Description

Using sip_trace() with different address arguments:
```
modparam("siptrace", "duplicate_uri", "sip:X.X.X.X:9060")

# siptrace till Homer
if(method == "REGISTER"){
	sip_trace("sip:X.X.X.X:9060", "", "t");
}

# siptrace till Voipmonitor
if (is_method("INVITE|BYE|UPDATE|CANCEL")) {
	sip_trace("sip:Y.Y.Y.Y:9060", "", "t");
}
```
Will send replies from auth_challenge to the address defined in duplicate_uri. So in the case above - no 407 are sent to "sip:Y.Y.Y.Y:9060", instead the are sent to "sip:X.X.X.X:9060" when challenging an Invite.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.6.5 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 8.3.0

```

**Comment by kamailio-sync** [comment]
Hi,

407 is a reply, so i guess, kamailio sends the duplicate message to default
target configured in modpraram.

You should configure something like

onreply_route {

      if 407
        sip_trace(sip:Y.Y.Y.Y)
}

Markus

**Comment by pnlarsson** [comment]
> Hi, 407 is a reply, so i guess, kamailio sends the duplicate message to default target configured in modpraram. You should configure something like onreply_route { if 407 sip_trace(sip:Y.Y.Y.Y) }

Unfortunately - I can see no traffic/messages in the onreply_route from auth_challenge - all other replies are visible there.

```
onreply_route {
	xlog("L_INFO", "[onreply_route] {$ci} - rm: $rm rs: $rs");
}
```

**Comment by miconda** [comment]
Likely the challenge for authentication is sent out stateless, not in a transaction. This is how the default config does it. You can try to create the transaction before the authentication challenge and see if solves it. If not, you can reopen here or continue the discussion on the mailing list for more help.
