### ISSUE TITLE
libbcg729-dev dependency of dpkg-checkbuilddeps can not install on ubuntu 18.04

### ISSUE THREAD

**Issue by faratell** [kamailio/kamailio#3703]
Hello to all.
I have tried to install VoLTE Setup with Kamailio IMS on Ubuntu 18.04 from https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/
in step 16,  Install RTPEngine, dpkg-checkbuilddeps have dependencies: libbcg729-dev, which is not in the repository of ubuntu 18.04 to install. How can install it?

dpkg-checkbuilddeps: error: Unmet build dependencies: libbcg729-dev
sudo apt install libbcg729-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libbcg729-dev

**Comment by miconda** [comment]
The dependency is for rtpengine, which works together with Kamailio but it is a separate project on `sipwise/rtpengine` repository. You have to address your reports to that project. Anyhow, iirc, there is an option to skip that dependency and build without it, just read the documentation more carefully.
