### ISSUE TITLE
error on module 

### ISSUE THREAD

**Issue by faratell** [kamailio/kamailio#3704]
Hello. I am trying to install Kamailio branch devel for using Volte on open5gs.
when compiled have this error:
gcrypt_mod.c:36:10: fatal error: gcrypt.h: No such file or directory
   36 | #include <gcrypt.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [../../Makefile.rules:100: gcrypt_mod.o] Error 1
make[2]: Leaving directory '/usr/local/src/kamailio-devel/kamailio/src/modules/gcrypt'
make[1]: *** [Makefile:508: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio-devel/kamailio/src'
make: *** [Makefile:34: all] Error 2

I have installed the dependencies of crypt : libcrypto and libssl-dev.

**Comment by miconda** [comment]
As instructed in another tracker item, for questions about installing or using kamailio, you have to use sr-users@lists.kamailio.org mailing list. The tracker is only for reporting bugs in the C code.
