### ISSUE TITLE
Error in make all

### ISSUE THREAD

**Issue by alijomeiy** [kamailio/kamailio#3705]
### Description
I've cloned Kamailio and tried to build with `make all` commands and the error below appeared:

```
module not found: modules/app_sqlang
make[1]: *** [Makefile:508: modules] Error 1
make[1]: Leaving directory '/usr/local/src/kamailio-devel/kamailio/src'
make: *** [Makefile:34: all] Error 2
```

the error wasn't occured before [9bb1976 "Makefile.groups: removed app_sqlang from modules list"](https://github.com/kamailio/kamailio/commit/9bb1976b4b7d52542a4de37144194bfc24649222) and just appered after pulling new commits.

### Troubleshooting

I could solve the issue by set `app_sqlang` as skip_modules or exclude_modules, it's also possible solve it by set in 

```
make skip_modules="app_sqlang" cfg
```

* **Ubuntu 22.04**

**Comment by miconda** [comment]
You have to do a 'make proper' or 'make pure' if you just pulled new commits and not cloned a fresh copy. For more assistance, write to sr-users mailing list.
