### ISSUE TITLE
UAC module ：uac_reg_tm_callback(): got sip response 408

### ISSUE THREAD

**Issue by 2954456878** [kamailio/kamailio#3707]
Register with remote，if there is no response to request，get in the logs an error message like:

ERROR: uac [uac_reg.c:1001]: uac_reg_tm_callback(): got sip response 408 while registering

How to get this timeout information in routing ?  event_route[ ] ？

**Comment by miconda** [comment]
For questions about using kamailio, you have to email to sr-users@lists.kamailio.org list. This tracker is for reporting bugs in the C code.
