### ISSUE TITLE
Docs: TLS module known limitations need clarifications

### ISSUE THREAD

**Issue by barryib** [kamailio/kamailio#3717]
### Description

We recently deployed successfully Kamailio with TLS certificates. Now we would like to use let's encrypt certificate which expire after 3 months. Means we need to renew certificate approximatively every 2 months. But while reading docs, in [known limitations](https://kamailio.org/docs/modules/devel/modules/tls.html#tls.known_limitations) it says :

> TLS specific config reloading is not safe, so for now better don't use it, especially under heavy traffic.

We struggle to understand if this behaviour is risky and not recommended under heavy traffic for certificate renewal. The doc has been added initially by @poandrei 18 years ago in Feb 21 2007 (see [commit](https://github.com/kamailio/kamailio/commit/32e4977cdb9c1c9ca24c140a493934f1d2e19fa1#diff-fd9201171a0a5a2ba38e0978db5be5228107718ee3704a21239faf181d71f72aR90))

While digging we came across few discussions Kamailio user groups which are saying "the opposite" (kind of):
- [Comments by a co-founder of Kamailio ](https://www.mail-archive.com/sr-users@lists.kamailio.org/msg16014.html)stating that the old connections shouldn’t be affected by reload.
- Comments by a Kamailio core developer stating that certificate reload is fine with the “reload” cmd ([link1](https://lists.kamailio.org/pipermail/sr-users/2022-February/114296.html), [link2](https://github.com/kamailio/kamailio/issues/3305))

Plus in another section in docs:
- [By definition :](https://kamailio.org/docs/modules/devel/modules/tls.html#tls.r.tls.reload) (the) existing active TLS connections are not terminated and they continue to use the old certificates. The new configuration will be used for new connections.

So 18 years after, Is it safe to use `tls.reload` command in production and in heavy traffic for **TLS certificate renewal** ? Because it sounds scary and confusing.

So the documentation as it is, really needs clarifications to let users know which risk they're taking when running the `tls.reload` command.

### Expected behavior

The document should  clearly documents risks, at least for certificate renewal.

#### Actual observed behavior

Docs and Kamailio user/dev groups are confusing.

**Comment by henningw** [comment]
@barryib Have a look to the referenced PR, it should address your concerns, feedback welcome of course.

**Comment by barryib** [comment]
> @barryib Have a look to the referenced PR, it should address your concerns, feedback welcome of course.

Thanks @henningw for the notification. Let's us have a look.

**Comment by barryib** [comment]
Closing since the doc has been updated.
Thanks
