### ISSUE TITLE
dialog module with broken defaults

### ISSUE THREAD

**Issue by zabbal** [kamailio/kamailio#372]
If I enable dialog module Kamailio will fail to start with following error:
 ERROR: dialog [dialog.c:498]: mod_init(): no dlg flag set!!

In the documentation this parameter is set to 4 as an example:
modparam("dialog", "dlg_flag", 4)

But no comments made as to why number 4 is used, which numbers are possible to use and most importantly - why such default value is chosen?

In any case - module should use default which does not break server's configuration.

**Comment by gaaf** [comment]
And on a related note, why is the flag necessary at all? I was trying a config which didn't set the flag, it only used dlg_manage() but I still had to define the flag for kamailio to start.

**Comment by miconda** [comment]
Regarding the value 4 -- that is an example, it can be any value from 0 to 31 -- the range of flags that can be used inside kamailio.cfg.

The parameter is mandatory from old times, when tracking dialogs was done by setting the respective flag for the invite transaction using setflag(N). Now there is the alternative (recommended) of using dlg_manage(), so I pushed a patch to master branch to remove the check of dlg_flag being not set and start without it.

**Comment by lgg** [comment]
@miconda 
`` ERROR: dialog [dialog.c:500]: mod_init(): invalid dlg flag -1!!``

kamailio 5.1.1, ubuntu xenial

**Comment by mckaygerhard** [comment]
same issue for me, invalid dialog flag -1

**Comment by m00zi** [comment]
same here 
`version: kamailio 5.2.1 (x86_64/linux) 69ec6f`

**Comment by mckaygerhard** [comment]
well i hope release 5.1.7 or 5.2.2 will have the fix, that must have commit https://github.com/kamailio/kamailio/commit/404f403786478a917637186446bb285e8e32cc59 or unless are not backported yet to those releases in Debian or the stupid winbuntu!

**Comment by henningw** [comment]
The commit has been backported and is included in release 5.1.7 and 5.2.1

**Comment by mckaygerhard** [comment]
thanks @henningw sorry i remenber that some time ago i use the strech debian and the 5.2.1 already fixed that problem..
