### ISSUE TITLE
failed to open database connection

### ISSUE THREAD

**Issue by faratell** [kamailio/kamailio#3721]
Hello.
I have installed Kamailio version devel on Ubuntu 22.04 and use the mysql database on the same machine.
when i run 

systemctl status kamailio.service
● kamailio.service - LSB: Start the Kamailio SIP proxy server
     Loaded: loaded (/etc/init.d/kamailio; generated)
     Active: active (exited) since Sat 2024-01-20 11:35:09 +0330; 21min ago
       Docs: man:systemd-sysv-generator(8)
        CPU: 48ms

/usr/local/sbin/kamailio[173481]: ERROR: usrloc [dlist.c:846]: register_udomain(): failed to open database connection
 /usr/local/sbin/kamailio[173481]: ERROR: registrar [registrar.c:767]: domain_fixup(): failed to register domain
 /usr/local/sbin/kamailio[173481]: ERROR: <core> [core/route.c:1193]: fix_actions(): fixing failed (code=-1) at cfg:/usr/local/etc/kamailio/kamailio.cfg:717
/usr/local/sbin/kamailio[173481]: ERROR: <core> [core/rvalue.c:3818]: fix_rval_expr(): failure in cfg at line: 717 col: 22
 /usr/local/sbin/kamailio[173481]: ERROR: <core> [core/rvalue.c:3818]: fix_rval_expr(): failure in cfg at line: 717 col: 22
 /usr/local/sbin/kamailio[173481]: ERROR: <core> [core/route.c:1193]: fix_actions(): fixing failed (code=-1) at cfg:/usr/local/etc/kamailio/kamailio.cfg:720
 /usr/local/sbin/kamailio[173481]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
 kamailio[173463]:  *  already running
kamailio[173463]:    ...done.
 systemd[1]: Started LSB: Start the Kamailio SIP proxy server.

In /usr/local/etc/kamailio/kamctlrc, I uncomment these lines:
SIP_DOMAIN=ims.mnc55.mcc999.farazNET.org
DBENGINE=MYSQL
 DBHOST=localhost
in  /usr/local/etc/kamailio/kamailio.cfg i apply this changes:
 auto_aliases=no
 alias="ims.mnc55.mcc999.farazNET.org"
listen=udp:192.168.75.185:5060
 listen=tcp:192.168.75.185:5060
 
how can i solved it?

**Comment by miconda** [comment]
Questions about using or configuring kamailio has to be addressed to sr-users@lists.kamailio.org mailing list. The tracker is for reporting issues in the C code.
