### ISSUE TITLE
db schemes - db_unixodbc, usrloc: MariaDB partition is a reserved word and not quoted

### ISSUE THREAD

**Issue by space88man** [kamailio/kamailio#3742]
### Description
partition is now a reserved word in MariaDB 10.
the column name is correctly quoted with native libmysqlclient/libmariadb so works

the column name is not quoted with unixodbc+(libmyodbc8|libmaodbc) and so fails

unixodbc will fail when enabled for registrar / usrloc

### Troubleshooting
try unquoted insert

-- fails unixodbc+libmaodbc
insert into location (partition) values (1000);  

-- works native libmysqlclient|libmariadb
insert into location (&#96;partition&#96;) values (1000);

#### Reproduction
1. config enable usrloc / registrar with unixodbc + MySQL/MariaDB connector

#### Debugging Data

SQL insert into statement fails

**Comment by space88man** [comment]
Technically can be solved using unixodbc quote_char param ; but we could consider renaming partition

**Comment by henningw** [comment]
Thanks for the report, I will take care of it. Probably its easier to use the same approach as for the mysql/mariadb, just quote it. Otherwise all the people need to change their databases at upgrade.

**Comment by miconda** [comment]
The quote_char param has this role, it is hard to avoid all keywords on various databases and changing the schema is not really recommended, in the future there can be other keywords that will conflict with existing names.

The only constraint is that all DBs used with db_unixodbc at the same time have to support same quoting character. A possible enhancement here would be to be able to specify the quoting char via the db url.

**Comment by space88man** [comment]
Thanks @miconda - closing now as not a bug.
