### ISSUE TITLE
RTPengine call was not terminated on BYE

### ISSUE THREAD

**Issue by sergey-safarov** [kamailio/kamailio#3749]
### Description

Via sngrep I can see call was terminated via BYE message but was not terminated on RTPengine hosts. The `rtpengine-ctl list sessions all` show calls that was terminated properly via BYE message.

In the kamailio config used `rtpengine_manage` function.
I do not have any idea how to troubleshoot this.
Could you suggest next step and I will add more details for this issue

### Additional Information

  * **Kamailio Version**
Used 5.6.4 with small customization.

```
version: kamailio 5.6.4 (aarch64/linux) 06ad45
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT-NOSMP, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 06ad45 
compiled on 16:37:11 Aug  7 2023 with gcc 8.5.0
```

* **Operating System**:

CentOS 8 Stream, aarch64
```
[root@sbc-a0 ~]# uname -a
Linux sbc-a0.nga911.com 4.19.113-300.el8.aarch64 #1 SMP Fri May 12 11:47:07 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
[root@sbc-a0 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by miconda** [comment]
At this phase this is something to discuss on users mailing lists (sr-users@lists.kamailio.org), it is not a clear report of a bug in the C code, but rather something to sort out how your config is written, whether the function is executed or not, in which block, what debug messages say, etc ... When it is clear discovered that it is about an issue in the C code, then the tracker can be used to describe it.
