### ISSUE TITLE
kamailio-mysql-modules on Ubuntu 14.04 not installable

### ISSUE THREAD

**Issue by btietzpanda** [kamailio/kamailio#376]
Hi,
I try to install kamailio-mysql-modules on Ubuntu 14.04 Trusty via latest repo:
deb http://deb.kamailio.org/kamailio trusty main

I want to use sipcapture for homer5 and need mysql 5.6 for that.

Now the problem:
Dependencies say I need mysql-client, which can't be installed because I have mysql-client-5.6 already installed but mysql-client points to mysql-client-5.5

This is mentioned as bug in:
https://bugs.launchpad.net/ubuntu/+source/mysql-5.6/+bug/1314555
https://wiki.debian.org/Teams/MySQL/virtual-mysql-server

Any options to change to virtual-mysql-client package as dependance for kamailio-mysql-modules?

**Comment by miconda** [comment]
Hopefully Victor will check whenever he gets a chance.

As alternative, you can change the spec files in the pkg/kamailio/deb/trusty and rebuild the packages. You will have to install dev packages or remove those packages you don't need. Eventually you can use OpenSuse Build Service to build the packages.

**Comment by btietzpanda** [comment]
Ok.
Cool. I hope Victor has some time soon :-)
