### ISSUE TITLE
Hello I am Facing issue while Installing Kamilio from Herulspreet brach. It is showing multiple definitions under CDP module.

### ISSUE THREAD

**Issue by Shailesh192** [kamailio/kamailio#3769]
#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
(paste your output here)
```

**Comment by linuxmaniac** [comment]
Kamailio Project uses GitHub Issues only for bugs in the code or feature requests. Please use this template only for bug reports.

If you have questions about using Kamailio or related to its configuration file, ask on sr-users mailing list:

  * https://lists.kamailio.org/mailman3/postorius/lists/sr-users.lists.kamailio.org/

If you have questions about developing extensions to Kamailio or its existing C code, ask on sr-dev mailing list:

  * https://lists.kamailio.org/mailman3/postorius/lists/sr-dev.lists.kamailio.org/
