### ISSUE TITLE
[FEATURE] mid-call self-redirect call to new nexthop

### ISSUE THREAD

**Issue by Jakihiko** [kamailio/kamailio#3773]
These below is sample diagram, where kamailio/rtpengine act as an SBC

<img width="1604" alt="image" src="https://github.com/kamailio/kamailio/assets/143789335/b9540fb3-c1bf-4a78-b1ad-78aaee8ea22a">

* There is an active call carrier, kamailio/rtpngine and Asterisk1
* Asterisk1 went down (power shortage, or network ..)
* What I want is kamailio self-redirect the call to  Asterisk2

**Describe the solution you'd like**
Ideally, kamailio provide the command line to tell which call will be self-redirect to the new destination, eg:
`kamcmd -x sefl_redirect_callid <call-id> <destionation-ip>`

Noted: I read the https://blog.opensips.org/2021/06/09/media-re-anchoring-using-opensips-3-2/ but re-INVITE to carrier seem not appropriate in my case due to call rate limit. I'm looking for a new solution where I don't need to use re-INVITE when Asterisk down.

**Comment by Jakihiko** [comment]
@miconda any comment on this proposal?

**Comment by henningw** [comment]
Maybe you can try to start a discussion about that on the users lists, to see if there is some interest about it.
