### ISSUE TITLE
PKG Memory Leak with RTPEngine Module with WebSocket

### ISSUE THREAD

**Issue by vijaykumar-exotel** [kamailio/kamailio#3777]
### Troubleshooting
- as checked further we particulartly tcp reciever process was consuming pkg memory , then further we checked from corex pkg_sumary for that process id, and found that rtpengine: rtpengine.c: send_rtpp_command was consuming highest memory.

#### Reproduction
console rtpengine url with ws endpoint.

this is reproducible, we can configure websocket in rtpengine module and then we can initate calls. and increase the number of calls over the period of time

#### Debugging Data
<img width="1399" alt="Screenshot 2024-03-06 at 4 30 16 PM" src="https://github.com/kamailio/kamailio/assets/115363081/0904892e-6a6e-4dc1-8501-a5bbad00d818">

kamcmd pkg.stats

	entry: 24
	pid: 378355
	rank: 17
	used: 7467640
	free: 24348320
	real_used: 9206112
	total_size: 33554432
	total_frags: 66
	desc: tcp receiver (generic) child=0

kamcmd corex.pkg_summary pid 378355
Mar  6 16:31:52 coreproxy-4 /usr/local/sbin/kamailio[378355]: ALERT: qm_sums: qm_sums():  count=  8075 size=   4638760 bytes from rtpengine: rtpengine.c: send_rtpp_command(3040)

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
version: kamailio 5.7.0 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 01:04:28 Jan 25 2024 with gcc 9.4.0
```

* **Operating System**:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Linux coreproxy-4 5.15.0-1045-oracle #51~20.04.1-Ubuntu SMP Fri Sep 22 14:25:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by miconda** [comment]
Can you test with latest version of 5.7 branch, there were many fixes since 5.7.0 in that branch and the logs messages do not match anymore the source code. Reproduce with latest 5.7.x and then paste again the relevant logs in order to be able to troubleshoot properly.

**Comment by vijaykumar-exotel** [comment]
Sure, will check with 5.7.x latest and confirm

**Comment by vijaykumar-exotel** [comment]
have verified with 5.7.4 , here also happening the same thing. @miconda

**Comment by henningw** [comment]
@vijaykumar-exotel Thanks for the confirmation, do you could also paste the updated log messages here?

**Comment by vijaykumar-exotel** [comment]
@miconda @henningw can you please review PR, after adding this fix, pkg memory is now getting available with this fix.
<img width="1427" alt="Screenshot 2024-04-13 at 2 28 11 AM" src="https://github.com/kamailio/kamailio/assets/115363081/f7548d0c-bc31-49bc-94d5-c86945e5b5df">
