### ISSUE TITLE
kamcmd keepalive.list   the last up and down time reversed 

### ISSUE THREAD

**Issue by suiyuemanbu** [kamailio/kamailio#3790]
kamailio  5.7.0
 kamcmd keepalive.list
{
        uri: sip:192.168.10.12:8877
        owner: drouting
        last checked: Mon Mar 18 17:45:39 2024

        last up: Mon Mar 18 17:45:59 2024     //err

        last down: Thu Jan  1 08:00:00 1970   //err

        state: 2
}
{
        uri: sip:192.168.10.124:5080
        owner: drouting
        last checked: Tue Mar 19 10:34:39 2024

        last up: Thu Jan  1 08:00:00 1970   //err

        last down: Tue Mar 19 10:34:39 2024    //err

        state: 1
}

**Comment by miconda** [comment]
Can you try with master branch or with the commit referenced above?

**Comment by suiyuemanbu** [comment]
> Can you try with master branch or with the commit referenced above?

yes, Your modifications are correct, thanks!

**Comment by suiyuemanbu** [comment]
miconda, thank you. You solved my problem.
