### ISSUE TITLE
sipdump.enable will not dump

### ISSUE THREAD

**Issue by 53c70r** [kamailio/kamailio#3798]
While testing I noticed a strange behavior.
Usually when activated, `sipdump.enable 1` for the specific interface will dump needed logs and captures to `/tmp/`.

After stopping the dump with `sipdump.enable 0` deleting all captures starting with `kamailio.*` under `/tmp/` and reactivating the dump with `sipdump.enable 1` without restarting kamailio, the service will not create new captures under `/tmp/`.

This behavior was reproducible.

**Comment by fredposner** [comment]
@53c70r -- are you deleting files and enabling within the rotation period?

The [default rotation period](https://www.kamailio.org/docs/modules/stable/modules/sipdump.html#sipdump.p.rotate) is 3600s.

I would assume the file is not recreated within the rotation period and you should either delete files outside the rotation period or wait until the period has passed.

**Comment by fredposner** [comment]
I've tested and this seems to be the issue. If I lower the rotation period, delete the files, and restart the new files are created **after** the rotation period has passed.

I don't believe this to be a bug and would recommend that you not delete the file within the rotation period if you wish to continue sipdump within that same period.

**Comment by fredposner** [comment]
Closing.
