### ISSUE TITLE
app_python module still needs Python 2

### ISSUE THREAD

**Issue by waarmond** [kamailio/kamailio#3805]
I'm trying to build current git sources on ArchLinux.

`make install-modules-all group_include="kpython"`

`modules/app_python/Makefile` still asks for python2:

```
which: no python2 in ($PATH)
which: no python2.7 in ($PATH)
  File "<string>", line 1
    import distutils.sysconfig;print distutils.sysconfig.get_config_var('LIBDIR')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
Is this intended?

How do I only let app_python3 be built?

**Comment by miconda** [comment]
Use app_python3/s if want python3. For more assistance to compile/use kamailio, use the sr-users@lists.kamailio.org mailing list.
