### ISSUE TITLE
Core parameters user_agent_header  fail to take effect

### ISSUE THREAD

**Issue by suiyuemanbu** [kamailio/kamailio#3816]
I want kamailio use  User-Agent header, not Server head

My setup is as follows:  kamailio.cfg
server_signature=no   
user_agent_header="User-Agent: carrierroute-kam"

the result is :
SIP/2.0 100 trying -- your call is important to us
Via: SIP/2.0/UDP xxx
From: xxxxxxtag=N856ZmNXa4S6D
To: xxx
Call-ID: 5ab0
CSeq: 82194 INVITE
Content-Length: 0

**not have User-Agent  header**
please help me,How to make it appear the User-Agent field? thank you

version: kamailio 5.7.0 (x86_64/linux) f1e91d

**Comment by henningw** [comment]
For replies generated from Kamailio you need to set the server_header parameter. The user_agent_header is for Kamailio generated requests. For questions like this please contact our sr-users lists, as this bug tracker is for bugs and issues in the code.
