### ISSUE TITLE
The tm.cancel function does not generate a “tm:local-request” event.

### ISSUE THREAD

**Issue by JuanPascual2** [kamailio/kamailio#3831]
Hello
The tm.t_uac_start function generates a “tm:local-request” event.
But the tm.cancel function doesn't generete “tm:local-request” event.

Is it possible to activate a parameter in the TM or TMX module to generate the event?

Thanks
Juan

**Comment by henningw** [comment]
Thanks for the report, it was probably not implemented yet for CANCEL generated from tm.

**Comment by henningw** [comment]
@JuanPascual2 a PR was merged that should fix the issue you reported, linked above. Maybe you can test and report back if your problem is solved.

**Comment by JuanPascual2** [comment]
Hello
I tested the correction.
Now ,  the tm.cancel function generete “tm:local-request” event.
But the pseudo variables correspond to the INVITE equest and not to the CANCEL request.
Example: $rm = INVITE
Can you reopen the issue?
BR
Juan

**Comment by JuanPascual2** [comment]
Hello
I tested it. The bug is fixed.
BR
Juan
