### ISSUE TITLE
kamailio re-INVITE

### ISSUE THREAD

**Issue by happytulubi** [kamailio/kamailio#3840]
Now there is a call scenario where freeswitch ->kamailio ->rtpengine ->webrtc (jsSIP) voice and video cannot be displayed. Is there a problem with my handling and how can I solve it?

1、Freeswitch INVITE to kamailio without video code
2、kamailio request to rtpengine(rtpengine_offer("record-call=off  force trust-address replace-origin replace-session-connection UDP/TLS/RTP/SAVPF"))and call to jsSIP
3、jsSIP response with "SIP/2.0 200 OK" to kamailio without video code
4、kamailio request to(rtpengine_answer("record-call=off replace-origin replace-session-connection DTLS=passive ICE=remove RTP/SAVPF"))and response to Freeswitch
5、jsSIP send re-INVITE to kamailio with video code
6、kamailio request to(rtpengine_offer("record-call=off  replace-origin replace-session-connection DTLS=passive ICE=remove SDES-off UDP/TLS/RTP/SAVPF"))and response to Freeswitch
7、Freeswitch response with "SIP/2.0 200 OK" to kamailio with video code
8、kamailio request to(rtpengine_answer("record-call=off  replace-origin replace-session-connection rtcp-mux-accept rtcp-mux-offer DTLS=passive SDES-off UDP/TLS/RTP/SAVPF"))and response to jsSIP
9、Freeswitch send re-INVITE to kamailio with video code
10、kamailio request to(rtpengine_offer("record-call=off  replace-origin replace-session-connection rtcp-mux-accept rtcp-mux-offer DTLS=passive SDES-off UDP/TLS/RTP/SAVPF"))and response to jsSIP
11、jsSIP response with "SIP/2.0 200 OK" to kamailio with video code
12、kamailio request to(rtpengine_answer("record-call=off  replace-origin replace-session-connection rtcp-mux-accept rtcp-mux-offer DTLS=passive SDES-off UDP/TLS/RTP/SAVPF"))and response to Freeswitch

**Comment by linuxmaniac** [comment]
This tracker is used for reporting bugs in the C code. For asking questions about using Kamailio and its configuration file, use [sr-users@lists.kamailio.org](mailto:sr-users@lists.kamailio.org) mailing list.
