### ISSUE TITLE
Usrloc keepalive: Not sending OPTIONS to UDP endpoints- 5.8.0 and 5.8.1

### ISSUE THREAD

**Issue by lukeescude** [kamailio/kamailio#3844]
Running compiled Kamailio 5.8.1 (previously 5.8.0) on Debian 12 64-bit

We're seeing an issue with UDP endpoints (this issue does not happen with TCP and TLS) where usrloc will not send OPTIONS packet keepalives.

Here are all of our usrloc parameters:

```
modparam("usrloc", "db_mode", 0)
modparam("usrloc", "ka_domain", "SIPDOMAIN") #-- SIPDOMAIN is a fqdn
modparam("usrloc", "ka_from", "sip:proxy-ping@SIPDOMAIN")
modparam("usrloc", "ka_mode", 1)
modparam("usrloc", "timer_interval", 20) #-- How often to qualify endpoints and clean mem tables?
modparam("usrloc", "timer_procs", 4)
modparam("usrloc", "ka_randomize", 10)
modparam("usrloc", "use_domain", 0)
modparam("usrloc", "server_id_filter", 1)
modparam("usrloc", "ka_filter", 0)
modparam("usrloc", "ka_timeout", 60) #-- How quickly to expire a contact if it does not reply to keepalive?
modparam("usrloc", "matching_mode", 0)
modparam("usrloc", "handle_lost_tcp", 1)
modparam("usrloc", "close_expired_tcp", 1)
modparam("usrloc", "desc_time_order", 1)
modparam("usrloc", "hash_size", 14)
```

It seems usrloc is not actually using timer_interval at all for UDP devices, and UDP devices don't receive any OPTIONS packets at all. However, it does seem to be sending OPTIONS every 60 seconds on TCP/TLS. (this is confirmed via packet capture on a SIP phone).

**Comment by lukeescude** [comment]
It does **_eventually_** start to send OPTIONS packets to endpoints, but it takes a very long time to begin.

**Comment by miconda** [comment]
Can you give an example value of what is `very long time`?

The interval of keepalive is defined by a new param:

  - https://www.kamailio.org/docs/modules/stable/modules/usrloc.html#usrloc.p.ka_interval

**Comment by lukeescude** [comment]
Even with ka_interval set to 40 seconds, it can take multiple minutes, or sometimes hours, for usrloc to begin sending OPTIONS packets.

**Comment by miconda** [comment]
I tried to reproduce, but keepalives are sent immediately to UDP contacts.

Can you try with Kamailio development version and see if all ok?

**Comment by lukeescude** [comment]
Yes I will try to recreate and get more data, thanks!

**Comment by henningw** [comment]
@lukeescude Do you were able to test with the development version as asked some months ago?
