### ISSUE TITLE
Lots of tcp_read_* errors in log, multi-transport server, lack of context in messages

### ISSUE THREAD

**Issue by krieger-od** [kamailio/kamailio#385]
Hi devs,
The logs of our Kamailio servers are rich for such lines:
```
Oct 28 06:57:35 ip-172-31-0-139 /usr/local/sbin/kamailio[31963]: ERROR: <core> [tcp_read.c:271]: tcp_read_data(): error reading: Connection reset by peer (104)
Oct 28 06:57:35 ip-172-31-0-139 /usr/local/sbin/kamailio[31963]: ERROR: <core> [tcp_read.c:1296]: tcp_read_req(): ERROR: tcp_read_req: error reading
```

The servers serve WS, WSS, UDP, TCP and TLS as connection transports. So we cannot figure what happens and if this is really a problem, but we get accused by whoever audits the servers.
What could be done to make this more trackable? Or maybe these messages should be suppressed, if there's no way to track them and they don't mean any problem?

**Comment by gled-rs** [comment]
Did you checked  what is happening at the time you get the logs, for example using tcpdump ?

**Comment by miconda** [comment]
I pushed a commit to print the source and destination ip of the connections in such log messages, maybe it will help to figure out what device was at the end of the connection and track better what happened. The patch is in master and 4.3 branches.

**Comment by krieger-od** [comment]
Thank you very much, will try it!

**Comment by miconda** [comment]
Reopen if you get new details to investigate here.
