### ISSUE TITLE
Problem loadmodule secsipid on kamailio 5.6.5

### ISSUE THREAD

**Issue by sondesbough** [kamailio/kamailio#3860]
failed to find command secsipid_build_identity (params 6)
parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?

parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?https://github.com/asipto/secsipidx/issues/12
May 24 11:26:36 vps-3471ad99 kamailio[70519]: ERROR: bad config file (2 errors)
May 24 11:26:36 vps-3471ad99 kamailio: INFO: [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:36 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 3.
May 24 11:26:36 vps-3471ad99 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:36 vps-3471ad99 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_build_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?https://github.com/asipto/secsipidx/issues/12
May 24 11:26:36 vps-3471ad99 kamailio: ERROR: [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:36 vps-3471ad99 kamailio[70521]: ERROR: bad config file (2 errors)
May 24 11:26:36 vps-3471ad99 kamailio: CRITICAL: [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?https://github.com/asipto/secsipidx/issues/12
May 24 11:26:36 vps-3471ad99 kamailio: INFO: [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:36 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:36 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:37 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 4.
May 24 11:26:37 vps-3471ad99 systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:37 vps-3471ad99 systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
May 24 11:26:37 vps-3471ad99 kamailio: ERROR: [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_build_identity (params 6)
May 24 11:26:37 vps-3471ad99 kamailio: CRITICAL: [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 799, column 125: unknown command, missing loadmodule?https://github.com/asipto/secsipidx/issues/12
May 24 11:26:37 vps-3471ad99 kamailio[70522]: ERROR: bad config file (2 errors)
May 24 11:26:37 vps-3471ad99 kamailio: ERROR: [core/cfg.y:3399]: yyparse(): cfg. parser: failed to find command secsipid_add_identity (params 6)
May 24 11:26:37 vps-3471ad99 kamailio: CRITICAL: [core/cfg.y:3539]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 802, column 125: unknown command, missing loadmodule?https://github.com/asipto/secsipidx/issues/12
May 24 11:26:37 vps-3471ad99 kamailio: INFO: [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
May 24 11:26:37 vps-3471ad99 systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION
May 24 11:26:37 vps-3471ad99 systemd[1]: kamailio.service: Failed with result 'exit-code'.
May 24 11:26:37 vps-3471ad99 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
May 24 11:26:37 vps-3471ad99 systemd[1]: kamailio.service: Scheduled restart job, restart counter is at 5.

**Comment by miconda** [comment]
Is the secsipid module loaded?

**Comment by sondesbough** [comment]
Yes, I've reinstalled Kamailio 5.6.5, and I'm not experiencing any problems now
