### ISSUE TITLE
Any web management tools suggestions

### ISSUE THREAD

**Issue by CzyerChen** [kamailio/kamailio#3881]
### Description

When I set up Kamailio, it is not easy to configure, monitor, and register visually.
There are compatibility issues with the older versions of Siremis components mentioned in the guide, and there are many problems in initialization and deployment that cannot be matched with the latest version.

Any other web management tools suggestions?

**Comment by miconda** [comment]
This tracker is for reporting issues in the C code of Kamailio, to discuss about configuring or using Kamailio, use the sr-users@lists.kamailio.org mailing list.
