### ISSUE TITLE
DNS google auto establish to kamailio service

### ISSUE THREAD

**Issue by itpanda2024** [kamailio/kamailio#3890]
I just study and work with Kamailio . I have a issue about listening port . Please help me.
I install kamailio in centos 9 stream  with version 5.6.5 when start call sometime, my system established connect from google dns (8.8.8.8:53) to kamailio with random port and  it do call fail (not reply when receive invite ). please help me and i attatch screenshot 
![kamailio issue](https://github.com/kamailio/kamailio/assets/154739080/d94aae72-e420-47be-8697-bc2887dff9cb)

**Comment by henningw** [comment]
This is probably related to DNS resolving. For general questions regarding the usage of kamailio, please contact our users mailing list at https://lists.kamailio.org/mailman3/postorius/lists/sr-users.lists.kamailio.org/ This tracker is for discussing issues in the code and enhancements.
