### ISSUE TITLE
[Warning] Aborted connection 203 to db: 'kamailio' user: 'kamailio' host: 'localhost'

### ISSUE THREAD

**Issue by hieunguyenm96** [kamailio/kamailio#3906]
After a period of use, this warning occurs continuously and affects the performance of the system. Is this the bug of the system?
Currently, I am using version 5.6 and MariaDB 10.5.25 + Galera Cluster.

**Comment by miconda** [comment]
Follow the provided template to report an issue (provide all the data requested in the template in the appropriate format) or use sr-users@lists.kamailio.org mailing list to figure out if it is something related to the configuration file.
