### ISSUE TITLE
kamailio 5.7.6 startup

### ISSUE THREAD

**Issue by alekamailio** [kamailio/kamailio#3908]
Hello,
Upgraded the kamailio version from 5.7.5 to 5.7.6 and after restart the service got the follow WARNING,
WARNING: db_mysql [km_my_con.c:179]: db_mysql_new_connection(): opt_ssl_ca option not supported by mysql version (value (null)) - ignoring,
when downgrade to 5.7.5 dindt happend.

Thanks

**Comment by miconda** [comment]
The warning can be ignored, has no relevant impact. Actually, it was changed to a debug message later, but somehow backporting was overlooked to 5.7 branch, I have just done it. You can use now latest git branch 5.7 (deb packages will build over the next night and be available in the nightly repos).
