### ISSUE TITLE
tls: Incompatible with the new openssl (wants an sslv3 object, which is no longer there)

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#391]
From Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804276

> Package: kamailio-tls-modules
> Version: 4.3.3-1+b1
> Severity: important
> Tags: security
> 
> Today's upgrade installs openssl 1.0.2 compiled w/o any ssl3 support
> and kamailio compiled against it, but the latter fails when run with:
> 
> [FAIL] Not starting Kamailio SIP Server: invalid configuration file! ... failed!
>  failed!
>  [....] 0(20886) ERROR: <core> [sr_module.c:576]: load_module(): could not open module </usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so>: /usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so: undefined symbol: SSLv3_client_method 0(20886) : <core> [cfg.y:3432]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 73, column 12-19: failed to load module 0(20886) ERROR: <core> [modparam.c:150]: set_mod_param_regex(): No module matching <tls> found 0(20886) : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 148, column 50: Can't set module parameter 0(20886) ERROR: <core> [modparam.c:150]: set_mod_param_regex(): No module matching <tls> found 0(20886) : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 149, column 45: Can't set module parameter 0(20886) ERROR: <core> [modparam.c:150]: set_mod_param_regex(): No module matching <tls> found 0(20886) : <core> [cfg.y:3435]: yyerror_
>  at(): parse error in config file /etc/kamailio/kamailio.cfg, line 150, column 35: Can't set module parameter ERROR: bad config file (4 errors) 0(20886)
> 
> As such and kama install with needs tls cannot run.
> 
> (All of the errors there are because the tls modules cannot load because of the load-time link failure.)
> 
> It will need a patch removing things like SSLv3_client_method.
> 
> It is unfortunate that this didn't result in a compile time failure but only in a dynamic-link-time failure...

**Comment by miconda** [comment]
I will look at it and fix it.

Probably for the moment I will disable SSL3 with defines -- over the time I guess will be removed, SSL3 is no longer considered secure.

I wonder if there is a define in libssl that can be used as a condition to detect if SSL3 is removed or not.

**Comment by miconda** [comment]
I pushed the patch b1c6c2af7e96c0bcbdee4ff46f6faf19fdc75d9f to master and backported to 4.3 branch.

If still an issue, re-open.
