### ISSUE TITLE
WolfSSL cipher_list

### ISSUE THREAD

**Issue by quinnmancsym** [kamailio/kamailio#3920]
Hi there,

I am currently using the tls_wolfssl module with kamailio and was wondering why the ability to set a cipher list was disabled.

From my own testing, uncommenting line 975 in tls_domain.c/ksr_tls_fix_domain adds the functionality and we haven't seen any issues with this so far.

Was there an issue with this when the module was first created? Should I be avoiding using this functionality? Thanks very much.

**Comment by space88man** [comment]
This was skipped in the MVP for the module: I will take a look at restoring this functionality.

**Comment by henningw** [comment]
@space88man Did you managed to have a look already? Thanks for the update.
