### ISSUE TITLE
[htable] db_sql    "key_value" length = 128  too small, what if change to 2048 ? 

### ISSUE THREAD

**Issue by gao114882** [kamailio/kamailio#3944]
### Expected behavior
large "key_value" can store to db_sql。 

#### Actual observed behavior
 the key_value = "{\"id\":1,\"in_port\":\"5263\",\"in_ptl\":\"udp\",\"rate_limit\":\"\",\"out_port\":\"5262\",\"out_ptl\":\"udp\",\"mode\":2,\"proxied_ip\":\"172.16.4.114\",\"proxied_port\":\"5080\",\"in_gateway_ip\":\"116.198.229.196\",\"in_gateway_port\":\"5080\",\"black_list\":{\"ip\":[\"127.0.0.1\"],\"user\":[]},\"white_list\":{\"ip\":[\"127.0.0.1\"],\"user\":[]},\"called_prefix\":[{\"match_num\":\"\",\"caller_rule\":{\"start_pos\":0,\"length\":2,\"new_num\":\"\",\"type\":2},\"called_rule\":{\"start_pos\":0,\"length\":0,\"new_num\":\"\",\"type\":0}}],\"caller_prefix\":[{\"match_num\":\"\",\"caller_rule\":{\"start_pos\":0,\"length\":2,\"new_num\":\"\",\"type\":1},\"called_rule\":{\"start_pos\":0,\"length\":0,\"new_num\":\"\",\"type\":0}}]}"

<img width="913" alt="企业微信截图_17234562508919" src="https://github.com/user-attachments/assets/ab0acd4b-980a-4dc5-95b3-8e8afb7a1232">

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
version: kamailio 5.8.2 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, MEM_JOIN_FREE, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_SEND_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id:  
compiled on 11:50:37 Aug  9 2024 with gcc 4.8.5
```

* **Operating System**:

```
(paste your output here)
```

**Comment by miconda** [comment]
The database table structure can be change, the limit is only in the definition of the table. Otherwise htable can handle any values in memory.

For further questions, use sr-users@lists.kamailio.org mailing list.
