### ISSUE TITLE
app_mono: maybe time to move it to archive repo?

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#3963]
### Description
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079882

```
From: "Chris Hofstaedtler" <zeha@debian.org>
Source: kamailio
Priority: wishlist
Control: block 1010445 by -1

Hi,

kamailio currently (build-)depends on mono libraries. Please drop
these relations, probably turning off mono support altogether.
The mono stack in Debian is not maintained in any way, so we'd like
to reduce packages relying on it.

Chris
```

I'll remove app_mono from sid and >= trixie builds

**Comment by miconda** [comment]
Fine for me!

Not sure if there are new versions of the mono libraries and if app_mono actually compiles with them, because the ones used when the module was developed should be rather old (more than 10 years, I guess) and the module didn't get much attention in between.
