### ISSUE TITLE
tls connection in kamailio use too many shared memories

### ISSUE THREAD

**Issue by JiangHai2011** [kamailio/kamailio#3980]
### Description

During our tls conn performance test for kamailio, we found fixed shared momory 700MB can only support around 9600 concurrent TLS connections. At the same time, we use nginx for comparison to do the same same tls conn performance test, and the result is 9600 concurrent TLS connections only cost 72MB virtual memory(nginx dont support global shared memory pool for each allocate. it use openssl internal allocate function)

Of course, we know, nginx does not use shared memory, and they are not much comparable.  Please check if there is any solution to save some shmmem SSL session takes.

### Expected behavior
kamailio use less shared memory for more TLS connections

#### Actual observed behavior

kamailio 's tls connection shared memory consists of tcpconn structure info and tcp_rd_buf and SSL session info, which are all in the same shared memory pool. As our observation, a ssl session info takes too many shmmem---around 130KB

#### Debugging Data

None

#### Log Messages

None

#### SIP Traffic

None

### Possible Solutions

None

### Additional Information

None

* **Operating System**:

Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by suiyuemanbu** [comment]
https://github.com/kamailio/kamailio/issues/3823

**Comment by linuxmaniac** [comment]
yes, seems duplicated.
