### ISSUE TITLE
t_relay failed when a user has several locations but some of them are stale

### ISSUE THREAD

**Issue by Kuanlin-Chen** [kamailio/kamailio#3985]
### Description

I followed the page 18~23 of this slide [20-Federico.Cabiddu-Kamailio-In-A-Mobile-World](https://www.kamailio.org/events/2015-KamailioWorld/Day2/20-Federico.Cabiddu-Kamailio-In-A-Mobile-World.pdf) to implement suspension & push notification, it worked well on mobile devices.

However, callee might have several location records on some occasions, for instance, they forcibly quit the app or kill the browser, meaning they don't de-register, the location hasn't expired and still exists, but it is stale and unreachable, this makes `t_relay` failed (return code is -2 and didn't trigger failure_route) since Kamailio `lookup` the stale location rather than the new one as they get push notification, below are some part of logs.

```
ERROR: tm [t_fwd.c:484]: prepare_new_uac(): could not build request
ERROR: tm [t_fwd.c:1764]: t_forward_nonack(): failure to add branches
ERROR: <script>: not t_relay by INVITE -2
ERROR: <script>: check status code is 100
```

The rest of Kamailio code triggers `sl_reply_error`, caller gets 500 and terminates.

### Expected behavior

When callee has several locations, even if some of them are stale, callee should not terminate the call and should find a valid location to ring the target.
 
#### Actual observed behavior

Caller finds invalid locations and gets 500 error msg.

#### Debugging Data

What I have tried
1. Run `suspend` when `t_relay` failed.
```
if (!t_relay()) {
    revert_uri();
    route(SUSPEND);
}
```
It doesn't work since `t_continue` still tries to recover the call with the stale location.

2. Run `append_branch` before `t_relay`.
```
if (!lookup("location")) {
    send_replay("100", "Trying");
    route(SUSPEND);
} else {
    append_branch($tu);
    t_relay();
    ts_store();
    $sht(vtp=>stored::$rU) = 1;
    xdbg("stored transaction [$T(id_index):$T(id_label)] $fU=> $rU\n");
}
```
This version of caller won't get 500 and terminate, but callee cannot finds the resumed call.

3. Use `t_load_contacts` and `t_next_contact`.
```
t_load_contacts();
while (t_next_contacts()) {
    xlog ("==== $ru\n");
}
```
t_next_contacts always return -2 (nothing to do), but I can see the new location via command `kamctl ul show`.

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
versionL kamailio 5.9.0-dev0 (x86_64/linux) 9a4363
```

* **Operating System**:

NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"

```
(paste your output here)
```

**Comment by henningw** [comment]
You could use something like this https://kamailio.org/docs/modules/5.8.x/modules/usrloc.html#usrloc.p.handle_lost_tcp to prevent the stale contacts from beeing used.

**Comment by Kuanlin-Chen** [comment]
> You could use something like this https://kamailio.org/docs/modules/5.8.x/modules/usrloc.html#usrloc.p.handle_lost_tcp to prevent the stale contacts from beeing used.

This method `handle_lost_tcp` works as my expectation! Thanks for saving my life!

**Comment by henningw** [comment]
Thanks for the feedback
