### ISSUE TITLE
relay to voip provider / sip trunk / path?

### ISSUE THREAD

**Issue by gentoosys** [kamailio/kamailio#3990]
hi. I am using https://github.com/havfo/WEBRTC-to-SIP to have a web sipcaller. it uses kamailio + rtpengine + web sipcaller (jssip)
right now it is working using internal account and can call to another sip.
But I need to use websipcaller to call to voip provider. I tried to register on my voip provider, and use just outbound websocket proxy, but it not working giving 401

the config I am using is https://github.com/havfo/WEBRTC-to-SIP/blob/master/etc/kamailio/kamailio.cfg

Please help adopt it to relay anything to external sip provider. I don't know what I need, relay, sip trunk or path module. 
kamailio configs are very hard for me to understand. 
So I need it just as websocket proxy to my voip provider, that doesn't support websocket. 
thanks!

**Comment by fredposner** [comment]
Hello @gentoosys -

Issues are for software bugs, etc. For help with configuration please use the mailing list or matrix: https://www.kamailio.org/w/support/

Thank you.

**Comment by gentoosys** [comment]
ok thanks
