### ISSUE TITLE
sipcapture: Repeating error message

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#40]
With the sip capture module loaded, but not activated, this error message is repeated many times - with no traffic.

 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled
 0(93552) ERROR: sipcapture [hep.c:61]: hep_msg_received(): sipcapture:hep_msg_received HEP is not enabled

**Comment by adubovikov** [comment]
are you sure about "no traffic" ? sipcapture has a trigger on ALL messages. Maybe in your case you are receiving some SIP messages ?

**Comment by oej** [comment]
You are right, I do have DMQ sending messages, but no external traffic. Should the error message be sent anyway for EVERY message?

**Comment by adubovikov** [comment]
I can make a bool value and show it only one time. Is it ok ?

**Comment by oej** [comment]
I think we need a general discussion on how to handle this  - I'm sure we have similar issues with other values (like my report on pipe limit/rate limit repeating messages)

In Asterisk we do set a boolean and either repeat a few times or just once.

**Comment by adubovikov** [comment]
ok, as quick workaround I will set a bool and we can change it later.

**Comment by adubovikov** [comment]
https://github.com/kamailio/kamailio/commit/cb8304f1f6be1eca3f9bd982265d5c3bed528189
