### ISSUE TITLE
Implementation of the timer_enable() function in Kemi

### ISSUE THREAD

**Issue by JuanPascual2** [kamailio/kamailio#4008]
Hello
The timer_enable() function does not exist in KEMI.
Can you implement the equivalent of this function in KEMI?
BR
Juan PASCUAL

**Comment by miconda** [comment]
Pushed a commit to export the function to the kemi. Testing and reporting  the result would be appreciated.

**Comment by JuanPascual2** [comment]
Hello
I tested:
KSR.timer.timer_enable("tmr4", 0) and KSR.timer.timer_enable("tmr4", 1)
It works.
Thanks
Juan
