### ISSUE TITLE
Documentation link is incorrect  on https://kamailio.org/docs/modules/5.8.x/ for python3s

### ISSUE THREAD

**Issue by whosgonna** [kamailio/kamailio#4022]
### Description

On https://kamailio.org/docs/modules/5.8.x/ the link for python3s actually links to python3 (https://kamailio.org/docs/modules/5.8.x/modules/app_python3.html).  It should link to https://kamailio.org/docs/modules/5.8.x/modules/app_python3s.html

**Comment by linuxmaniac** [comment]
It should be fixed now. Thanks
