### ISSUE TITLE
kamailio.cfg updates for v6.0.x series

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#4034]
Discuss and track updates to default kamailio.cfg for v6.0.x series.

If you want to add something new to or remove from kamailio.cfg, post a comment in this thread.

Commits to kamailio.cfg can also reference this tracker item.

**Comment by miconda** [comment]
I am considering to add to default `kamailio.cfg`:

  - `dlgs` module - to be able to see statistics about calls since the start time
  - `udp_receiver_mode` - example of use (in comments)

**Comment by henningw** [comment]
> I am considering to add to default `kamailio.cfg`:
> 
>     * `dlgs` module - to be able to see statistics about calls since the start time
Sounds good, but it should be probably added with a #define, similar to other modules.
> udp_receiver_mode - example of use (in comments)

Great

**Comment by miconda** [comment]
The other modules that are with ifdefs are mainly because they depend on other resources (e.g., database connection, external applications), or can prevent traffic from being processing (e.g., anti-flood). The `dlgs` is only for current runtime call stats, no other dependency, and I would rather avoid keep adding `#!ifdefs`, it makes the config complex and hard to follow.
