### ISSUE TITLE
kamcmd tm.t_uac_start  error

### ISSUE THREAD

**Issue by suiyuemanbu** [kamailio/kamailio#4042]
kamcmd tm.t_uac_start  INVITE   sip:1346@192.168.10.22:5080 . .  'From: <sip:1000@192.168.10.11>\r\n'  'To: <sip:1346@192.168.10.22:5080>\r\n'
error: 400 - Invalid headers

the log is :
/usr/bin/kamailio[2773]: ERROR: <core> [core/parser/msg_parser.c:260]: get_hdr_field(): no eol - bad body for <From> (hdr type: 4) [<sip:1000@192.168.10.11>\r\n]
/usr/bin/kamailio[2773]: ERROR: <core> [core/parser/msg_parser.c:339]: parse_headers(): bad header field [From: <sip:1000@192.168.10.11>\r\n]

kamailio -v
version: kamailio 5.7.0 (x86_64/linux) f1e91d

please help me, thank  you

**Comment by miconda** [comment]
Questions about using kamailio have to be addressed to sr-users@lists.kamailio.org. The tracker is for reporting issues in the C code.
