### ISSUE TITLE
rtp_proxy 'r' flag

### ISSUE THREAD

**Issue by snen** [kamailio/kamailio#405]
Inspired by commit
https://github.com/kamailio/kamailio/commit/ac31eb11cc4b194b2d7e9dddff63fd074f456005

in rtpproxy  doc module

```
r - flags that IP address in SDP should be trusted. Without this flag, rtpproxy ignores address in the SDP and uses source address of the SIP message as media address which is passed to the RTP proxy.
```
But it is possible to send media to SDP IP  without this flag. Here a little more details
https://github.com/sippy/rtpproxy/issues/34

**Comment by miconda** [comment]
I know that can send to any ip in sdp based on learning (waiting for first packet), but depending on what is at that node, it may wait for a packet as well.

It is not clear if you wanted to report an issue or just discuss. If it is a discussion, then use sr-users mailing list, we use tracker for bugs or requests for features. If it is an issue, then re-open here and provide more details about what bug you want to report.
