### ISSUE TITLE
general protection fault in kamailio 5.5 on RHEL 8

### ISSUE THREAD

**Issue by pgravet** [kamailio/kamailio#4057]
### Description

Hi, I am migrating a kamailio application from RHEL 7 / KAM 5.0 to RHEL 8 / KAM 5.5
kamailio installed from repo baseurl=https://rpm.kamailio.org/centos/...

Thanks for your return

### Troubleshooting
general protection fault

#### Reproduction

Each time an INVITE is received

#### Debugging Data

Core was generated by `/usr/sbin/kamailio --atexit=no -DD -P /run/kamailio/kamailio.pid -f /etc/kamail'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006e2be9 in qm_debug_check_frag ()
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-225.el8_8.6.x86_64 libblkid-2.32.1-42.el8_8.x86_64 libgcc-8.5.0-18.el8.x86_64 libmount-2.32.1-42.el8_8.x86_64 libselinux-2.9-8.el8.x86_64 libxcrypt-4.1.1-6.el8.x86_64 mariadb-connector-c-3.1.11-2.el8_3.x86_64 openssl-libs-1.1.1k-9.el8_7.x86_64 pcre2-10.32-3.el8_6.x86_64 perl-libs-5.26.3-422.el8.x86_64 systemd-libs-239-74.el8_8.5.x86_64 zlib-1.2.11-21.el8_7.x86_64
(gdb) bt
#0  0x00000000006e2be9 in qm_debug_check_frag ()
#1  0x00000000006e6dba in qm_free ()
#2  0x00000000006f13c9 in qm_shm_free ()
#3  0x00000000005e8a2f in xavp_free ()
#4  0x00000000005e9ed8 in xavp_destroy_list ()
#5  0x00000000005e9f4f in xavp_reset_list ()
#6  0x00000000005ff6a1 in ksr_msg_env_reset ()
#7  0x00000000005fefb4 in receive_msg ()
#8  0x00000000004ddb1a in udp_rcv_loop ()
#9  0x000000000042bf00 in main_loop ()
#10 0x0000000000437c69 in main ()
(gdb) info locals
No symbol table info available.
(gdb) list
1       dl-call-libc-early-init.c: No such file or directory.

#### Log Messages

Nothing in Syslog

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

version: kamailio 5.5.7 (x86_64/linux) 43eb13
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLOCKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 43eb13
compiled on 13:39:01 Jul 19 2023 with gcc 8.5.0

* **Operating System**:

RHEL 8.8

**Comment by henningw** [comment]
Hello, the Kamailio version 5.5.x is a already end of life for some time. Please use a more recent and supported version e.g. the latest 5.7.x or 5.8.x and test again.

**Comment by pgravet** [comment]
I closed this issue and I performed a new installation with 5.8.4 version.
