### ISSUE TITLE
Hope pv_www_authenticate in  Lua KEMI framework

### ISSUE THREAD

**Issue by CzyerChen** [kamailio/kamailio#4067]
### Description

When I rewrite from native to Lua syntax, I find that `pv_www_authenticate` has no corresponding implementation, can we add it?

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
(paste your sip traffic here)
```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
(paste your output here)
```

* **Operating System**:

```
Kamailio 5.8.2
Lua 5.1.4
```

**Comment by miconda** [comment]
pv_auth_check() is a wrapper around pv_www_authenticate() and pv_proxy_authenticate() (with some extra checks), if you need it for REGISTER, then is the same as pv_www_authenticate().

Anyhow, I exported the other functions as well with the commit referenced above.
