### ISSUE TITLE
Crashed happen when loading module cnxcc

### ISSUE THREAD

**Issue by andrewvmail** [kamailio/kamailio#407]
I'm on Kamailio version: kamailio 4.3.3 (x86_64/linux) 22e455

When booting up Kamailio I get a Nov 21 20:36:52 sipr kamailio[24460]: 0(24476) DEBUG: <core> [main.c:747]: handle_sigs(): terminating due to SIGCHLD

Kamailio log:
http://pastebin.com/7bHHyHqD
Redis log:
http://pastebin.com/jWyYnbRB

Any ideas is greatly appreciated thanks! :).

**Comment by andrewvmail** [comment]
Kam config module file: 
http://pastebin.com/aqKp9w8t

**Comment by miconda** [comment]
To see where it crashes, do:

```
ulimit -c unlimited
````

Eventually run also kamailio as root in order to get the core file.

If you didn't configure one core file per process, do:

```
echo "1" > /proc/sys/kernel/core_uses_pid
```

With the above commands run, start again kamailio and sent the 'bt full' from gdb for each core file.

**Comment by andrewvmail** [comment]
Closing, got latest Kam and its not happening anymore.
Thanks
