### ISSUE TITLE
dialog: wrong CSeq in BYE after PRACK

### ISSUE THREAD

**Issue by dunst0** [kamailio/kamailio#409]
When using the dialog module to end a dialog, the remote UA refusing the BYE after a PRACK in the dialog.

```
---- INVITE ( CSeq: 1 INVITE ) --->
<--- 100 ( CSeq: 1 INVITE ) -------
<--- 183 ( CSeq: 1 INVITE ) -------
---- PRACK ( CSeq: 2 PRACK ) ----->
<--- 200 OK ( CSeq: 2 PRACK ) -----
<--- 200 OK ( CSeq: 1 INVITE ) ----
---- ACK ( CSeq: 1 ACK ) --------->

{      Mi: dlg.end_dlg()      }

<--- BYE (CSeq: 1 BYE) 
     BYE ( CSeq: 2 BYE) ---------->
<--- 500 (Bad CSeq number) --------
```

error in the remote log "remote cseq lower than previous ones - refusing request".

**Comment by miconda** [comment]
Can you try with commit aab6547f39d723de6a01680cbd79b9365be8092f ?

You can get it in the branch 4.3 with git cherry-pick -x aab6547f39d723de6a01680cbd79b9365be8092f

If all ok, I will backport. It is rather a quick fix that can be backported, instead of keeping lots of other stats about PRACKs.

**Comment by dunst0** [comment]
Works, for me.

**Comment by miconda** [comment]
Great, will backport!
