### ISSUE TITLE
permissions: Core dump

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#41]
NO traffic, just starting Kamailio and letting it run for a while with a lot of modules loaded.
git head.

(gdb) bt full
#0  0x00007fff8a92e866 in __pthread_kill ()
No symbol table info available.
#1  0x00007fff86b1235c in pthread_kill ()
No symbol table info available.
#2  0x00007fff869e9b1a in abort ()
No symbol table info available.
#3  0x00000001081ebc67 in fm_free (qm=0x10a78a000, p=0x5c, file=0x109ee9295 "permissions: hash.c", func=0x109eea05c "free_subnet_table", line=845) at mem/f_malloc.c:588
	f = (struct fm_frag *) 0x10aa0a698
#4  0x0000000109eb9990 in free_subnet_table (table=0x10aa0c340) at hash.c:845
	i = 0
#5  0x0000000109ea8cfc in clean_addresses () at address.c:442
No locals.
#6  0x0000000109ec5c7e in mod_exit () at permissions.c:682
	i = 1
#7  0x00000001080fc089 in destroy_modules () at sr_module.c:788
	t = (struct sr_module *) 0x108553540
	foo = (struct sr_module *) 0x1085531b8
#8  0x0000000107f533cb in cleanup (show_status=1) at main.c:512
	memlog = 0
#9  0x0000000107f5ad2b in shutdown_children (sig=15, show_status=1) at main.c:654
No locals.
#10 0x0000000107f56394 in handle_sigs () at main.c:684
	chld = 0
	chld_status = 0
	memlog = 0
#11 0x0000000107f5adb7 in sig_usr (signo=2) at main.c:781
	memlog = 0
#12 <signal handler called>

**Comment by oej** [comment]
Another one when I tried to stop Kamailio with ctrl-c

(gdb) bt full
#0  0x00007fff8a92e866 in __pthread_kill ()
No symbol table info available.
#1  0x00007fff86b1235c in pthread_kill ()
No symbol table info available.
#2  0x00007fff869e9b1a in abort ()
No symbol table info available.
#3  0x000000010e5a0c67 in fm_free (qm=0x110b3f000, p=0x5c, file=0x11029e295 "permissions: hash.c", func=0x11029f05c "free_subnet_table", line=845) at mem/f_malloc.c:588
	f = (struct fm_frag *) 0x110dbf698
#4  0x000000011026e990 in free_subnet_table (table=0x110dc1340) at hash.c:845
	i = 0
#5  0x000000011025dcfc in clean_addresses () at address.c:442
No locals.
#6  0x000000011027ac7e in mod_exit () at permissions.c:682
	i = 1
#7  0x000000010e4b1089 in destroy_modules () at sr_module.c:788
	t = (struct sr_module *) 0x10e908540
	foo = (struct sr_module *) 0x10e9081b8
#8  0x000000010e3083cb in cleanup (show_status=1) at main.c:512
	memlog = 0
#9  0x000000010e30fd2b in shutdown_children (sig=15, show_status=1) at main.c:654
No locals.
#10 0x000000010e30b394 in handle_sigs () at main.c:684
	chld = 0
	chld_status = 0
	memlog = 0
#11 0x000000010e30fdb7 in sig_usr (signo=2) at main.c:781
	memlog = 0
#12 <signal handler called>

**Comment by oej** [comment]
In foreground mode

**Comment by miconda** [comment]
Both backtraces are from a shutdown. Pushed patch 165a3fc to handle such cases.
