### ISSUE TITLE
userblacklist (?) : Core dump

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#42]
As other cases, just starting Kamailio and trying to stop it. Config with a lot of modules and no messages. Git head.

(gdb) bt full
#0  0x00000001139744be in dtrie_delete (root=0x10fabdec0, node=0x40000000000, delete_payload=0, branches=10) at dtrie.c:82
	i = 0
#1  0x00000001139744d1 in dtrie_delete (root=0x10fabdec0, node=0x10fabdec0, delete_payload=0, branches=10) at dtrie.c:82
	i = 0
#2  0x0000000113974b10 in dtrie_destroy (root=0x11396e788, delete_payload=0, branches=10) at dtrie.c:104
No locals.
#3  0x000000011395c3ef in mod_destroy () at userblacklist.c:742
No locals.
#4  0x000000010d20a089 in destroy_modules () at sr_module.c:788
	t = (struct sr_module *) 0x10d671600
	foo = (struct sr_module *) 0x10d6712b0
#5  0x000000010d0613cb in cleanup (show_status=1) at main.c:512
	memlog = 0
#6  0x000000010d068d2b in shutdown_children (sig=15, show_status=1) at main.c:654
No locals.
#7  0x000000010d064394 in handle_sigs () at main.c:684
	chld = 0
	chld_status = 0
	memlog = 0
#8  0x000000010d068db7 in sig_usr (signo=2) at main.c:781
	memlog = 0
#9  <signal handler called>
No symbol table info available.

**Comment by oej** [comment]
In foreground mode

**Comment by miconda** [comment]
I pushed a patch that should catch not initialized vars used on destroy at startup.
