### ISSUE TITLE
Dialog module: statistics for dialog 0 after reboot

### ISSUE THREAD

**Issue by igorPot** [kamailio/kamailio#424]
I have rebooted my kamailio machine and now the value of kamailio dialogs is always 0:
```
KAMAILIO-MIB::kamailioCurNumDialogs.0 = Gauge32: 0
KAMAILIO-MIB::kamailioCurNumDialogsInProgress.0 = Gauge32: 0
KAMAILIO-MIB::kamailioCurNumDialogsInSetup.0 = Gauge32: 0
KAMAILIO-MIB::kamailioTotalNumFailedDialogSetups.0 = Counter32: 0
```
And also the status is:
```
KAMAILIO-MIB::kamailioDialogUsageState.0 = INTEGER: idle(0)
```
How can I change it to active(1)? I have dialog.so loaded as well as modparam("dialog", "dlg_flag", 4) and dlg_manage().

If I do 'kamctl stats dialog':
```
#kamctl stats dialog
dialog:active_dialogs = 498
dialog:early_dialogs = 57
dialog:expired_dialogs = 24
dialog:failed_dialogs = 73222
dialog:processed_dialogs = 539449
```
I have the same configruation of SNMPstats and kamailio in 2 other machines and it works perfectly. In this machine it worked until I rebooted the machine. 

I asked this question in th emailing list and I got the following response:

"Must be something in how the SNMP module reads the data from the statistics counters."

I don't know if this could help.

Thank you.

**Comment by oej** [comment]
Looking into the the code I see that we use the proper names. 
'''

**Comment by oej** [comment]
Are you sure you are using the MIB provided with the same release as the one you are using? (Just checking)

**Comment by oej** [comment]
Btw ,which version of Kamailio are you using?

**Comment by igorPot** [comment]
I am using version 4.2.3 of kamailio and yes, I am using the same MIBs provided with the release.

**Comment by igorPot** [comment]
Do you know what kind of problem could it be?

**Comment by oej** [comment]
Hmm. I am thinking that the dialog module doesn't update the counters after reloading dialogs from database at startup. Don't think this is really a SNMP issue - the counter is managed by the dialog module.

**Comment by oej** [comment]
I think I have solved the issue in master with the above patch. Can you please try it out? Thanks.

**Comment by miconda** [comment]
Closing as no update was done after pushing the commit with a potential fix. Reopen if the commit doesn't fix it.
