### ISSUE TITLE
Kamailio : warning message - WARNING: pike [pike_funcs.c:274]: refresh_node(): PIKE - UNBLOCKing node 0x7ff1a89c30b0

### ISSUE THREAD

**Issue by yboujraf** [kamailio/kamailio#426]
Dear,

This morning I got some errors and warnings with the Kamailio.

/usr/sbin/kamailio[3037]: WARNING: pike [pike_funcs.c:274]: refresh_node(): PIKE - UNBLOCKing node 0x7ff1a89c30b0

Is someone can decript for me which is this warning?

Best Regards,
Youssef

**Comment by miconda** [comment]
This is not a bug report, in the future, for discussions about operating Kamailio use the mailing list sr-users@lists.sip-router.org

The message means that pike blocked an IP address and now it unblocks it from internal structure.
