### ISSUE TITLE
Kamailio - error message - ERROR: <script>: NATMANAGE coie

### ISSUE THREAD

**Issue by yboujraf** [kamailio/kamailio#427]
Dear,

This morning I got some errors and warnings with the Kamailio.

 /usr/sbin/kamailio[3024]: ERROR: <script>: NATMANAGE M=INVITE OU=<null>  RURI=<null> RD=<null> F=sip:sme01@91.151.60.81 T=sip:codec5@91.151.60.81 NH=<null> IP=10.80.89.5 ID=ydEOk0BD1449045968@192.168.1.116
/usr/sbin/kamailio[3024]: ERROR: <script>: NATMANAGE coie

Is someone can decript for me which is this warning?

Best Regards,
Youssef

**Comment by miconda** [comment]
This doesn't present a the entire log message -- from the subject of the issue, seems to be an xlog() in config.

Anyhow, this is not a bug report, for such discussions use the mailing list sr-users@lists.sip-router.org
