### ISSUE TITLE
when assigned to $fd value it instead of replacing Kamailio just add that value to the end

### ISSUE THREAD

**Issue by os11k** [kamailio/kamailio#428]
Hi,

Not sure if this is a proper bug, but when I assign something to $fd after assigning something to $fu, instead of replacement it just add that value to the end:

Let assume we assign to $fu:
$fu = " sip:something@mydomain.com";
current $fd value is "mydomain.com"
if I do following after assigning to $fu: 
$fd = "newdomain.com";

$fd changed to "mydomain.comnewdomain.com", but it should be "newdomain.com"

I believe this is not proper behavior.

Thank you!

**Comment by miconda** [comment]
You need msg_apply_changes() for each operation that alters a SIP header, if you do another operation that is going to alter same part. Changes to headers are not applied immediately:

  * http://www.kamailio.org/wiki/tutorials/faq/main#why_changes_made_to_headers_or
