### ISSUE TITLE
If we print out $fu, $fU & $fd on onsend_route, it prints out incorrect values.

### ISSUE THREAD

**Issue by os11k** [kamailio/kamailio#430]
Hi,

When I'm trying to update $ru, $fu & $fd in Kamailio conf:
$rU = "1000"; 
$fu = "sip:something@mydomain.com";
$fd = "newdomain.com";

And later I'm trying to print out $rU, $fu, $fU & $fd in onsend_route:

        xlog("ALERT: From URI $fu \n");
        xlog("ALERT: From domain $fd \n");
        xlog("ALERT: From user $fU \n");
        xlog("ALERT: Request user $rU \n");

Kamailio 4.3.3 prints out following:
ALERT: From URI sip:2000@some_ip
ALERT: From domain some_ip
ALERT: From user 2000
ALERT: Request user 1000

But I believe it should:

ALERT: From URI sip:something@mydomain.com
ALERT: From domain mydomain.com
ALERT: From user something
ALERT: Request user 1000

I'm using default Kamailio config with minor changes, you can check it in attachment.

Thank you!
[kamailio.txt](https://github.com/kamailio/kamailio/files/51994/kamailio.txt)

**Comment by linuxmaniac** [comment]
please, send you questions to sr-users@lists.sip-router.org
