### ISSUE TITLE
Kamailio with MongoDB

### ISSUE THREAD

**Issue by JavaMachine** [kamailio/kamailio#431]
Hello dear fellow developers,

I am new to Kamailio and to get started I followed the guide (http://www.kamailio.org/wiki/install/4.3.x/git)...

On the 3rd stage of the guide (3.Tuning Makefiles)
I changed "include_modules= db_mongodb" instead of "include_modules= db_mysql" and sucessfully compiled Kamailio...

I skipped stage 7 and followed this guide instead (http://www.kamailio.org/wiki/tutorials/kamailio-and-mongodb)

But at the stage 10 where I should add new account using command:
kamctl add test testpasswd test@mysipserver.com

I received an error:
ERROR: This command requires a database engine - none was loaded

Where was my mistake? What I did wrong?

Thanks in advance

**Comment by linuxmaniac** [comment]
please, send you questions to sr-users@lists.sip-router.org

**Comment by miconda** [comment]
For further clarifications - we try to use the issue tracker only for bugs and new feature/enhancement requests. If you are not sure it is a bug, then first discuss on sr-users mailing lists. It keeps keeping the tracker focused on issues, not used as a discussions forum.

For sake of archiving this issue anyhow -- kamctl does not support mongodb, you have to insert records manually in mongodb table subscriber.
