### ISSUE TITLE
how to send BYE to outbound leg in kamailio?

### ISSUE THREAD

**Issue by DileepNunna** [kamailio/kamailio#437]
After credit limit reached(ims_charging), tried to send BYE to both legs in kamailo (modules/dialog_ng/dlg_req_within.c).Bye sent to caller, but when sending bye to callee it is failing.(it is considering record-routes from caller invite, not in 200 OK from callee).Is there any changes necessary?

**Comment by miconda** [comment]
If it is question related to how to write C code inside an existing module, then send an email to sr-dev@lists.sip-router.org.

If it is about configuration file, send an email to sr-users@lists.sip-router.org.

This is the bug tracker where we want to keep only the list of problems discovered in the code or requests for new features. We are not using the bug tracker as a generic discussions forum.

**Comment by DileepNunna** [comment]
send_bye(): failed to send the BYE request in dialog_ng module.when kamailio creating and sending BYE to callee, it has to take callee 200OK record routes - caller record routes - self record route.but it is taking all 200OK record routes.
