### ISSUE TITLE
failed to send the BYE request to callee.

### ISSUE THREAD

**Issue by DileepNunna** [kamailio/kamailio#444]
send_bye(): failed to send the BYE request in dialog_ng module.when kamailio creating and sending BYE request to callee, it has to take callee 200OK record routes - caller record routes - self record route.but it is taking all 200OK record routes.

**Comment by miconda** [comment]
Did you changed the source code? If yes, post here the patch.

Are you using ims modules, if not, then use dialg module.

**Comment by DileepNunna** [comment]
i did not change the source code. if changes done i will post. i am using ims_charging module.will it work in dialog module.

**Comment by miconda** [comment]
Any updates testing with dialog module?

**Comment by DileepNunna** [comment]
Added code for removing caller routes in dialog_ng module.find the attached file for removing caller routes.
can you guide me how to find self routes to remove.(how to get self route or routes if added by kamailio.)
[fix.txt](https://github.com/kamailio/kamailio/files/80021/fix.txt)

**Comment by miconda** [comment]
Can you make a github pull request with the patch you did? Then it will run through the travis ci and spot any compile time issue on many platforms, being also better to review and comment when needed.

**Comment by miconda** [comment]
Closing this issue -- if you have a patch that you think it fixes your issue, make a pull request in order to be reviewed and merged if all ok.
