### ISSUE TITLE
tcpops - event_route[tcp:closed] enhancements

### ISSUE THREAD

**Issue by miconda** [kamailio/kamailio#461]
Openend as a follow up of @camilleoudot comments (pasted next) to the pull request #454 by @armenb.

"""
if the tcpops module is loaded but no tcp:closed route is defined, a debug log line will complain about it. I think it would make sense to add a module parameter to globally enable or disable the event route lookup and execution.
Besides, as many of the tcpops function can act on a per-socket basis, it would be nice to have this event route called or not called depending on the socket (e.g. using a tcp_connection flag and defining a new tcpops function to set/reset this flag).
What do you think?
"""

**Comment by camilleoudot** [comment]
I made these few changes to implement the tiny enhancements on the tcp closed event route.

**Comment by miconda** [comment]
Closing the feature request being implemented by patches above.
