### ISSUE TITLE
kamailio sending update ccr request instead of terminate request for initial ccr response having final_unit_action flag.

### ISSUE THREAD

**Issue by DileepNunna** [kamailio/kamailio#464]
If final_unit_action flag is set in initial ccr response, kamailio need to send terminate request after time out but it is sending update request.but it is fine for intermediate requests.

Attached file for fixing the issue.
[fix.txt](https://github.com/kamailio/kamailio/files/80008/fix.txt)

**Comment by miconda** [comment]
The recommended way to submit a patch is via pull request using github. Clone the kamailio repository, apply the patch to your clone then make a pull request. In this way we can review your changes, comment on them if it is the case, but also benefit of automatic builds and see if compilation breaks.

For convenience, next is a link with resources about pull requests, although you can find lots of online tutorials on various blogs:

* https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/

**Comment by miconda** [comment]
Changes provided as pull request #467 .
