### ISSUE TITLE
Setting per module debug level causes deadlock

### ISSUE THREAD

**Issue by que273** [kamailio/kamailio#482]
If kamailio is compiled with DBG_QM_MALLOC, debug is printed in `mem/q_malloc.c:405`
When the set_mod_level RPC function is called, memory is allocated while the lock is held `debugger/debugger_api.c:1224`
This will cause a deadlock when setting the value of 'core'.

**Comment by miconda** [comment]
What version are you using? There was a fix recently on same kind of report.

**Comment by que273** [comment]
Indeed it was fixed in #463 . Sorry for the noise.
