### ISSUE TITLE
Registrar: kamailio update contact infomation failed but it sends 200-register message to client

### ISSUE THREAD

**Issue by shenya** [kamailio/kamailio#497]
Hi,

When client send register message that reg-id in contact is "0", kamailio failed to update contacts info， but it will send 200-register to client, this will cause one issue that no one can find this client(will always be 404 error).

reg-id in message:
Contact: <sip:2015@10.0.0.80:5060;ob>;reg-id=0
Related logs:
 /usr/local/sbin/kamailio[30325]: ERROR: registrar [save.c:402]: pack_ci(): invalid reg-id value
 /usr/local/sbin/kamailio[30325]: ERROR: registrar [save.c:685]: update_contacts(): failed to pack contact specific info

I think registrar should reply 4xx message when reg-id's value is 0.

Best Regards,
Shengy

**Comment by oej** [comment]
If I am not mistaken, Reg-ID 0 is invalid. RFC 5626 says

  c-p-reg        = "reg-id" EQUAL 1*DIGIT ; 1 to (2^31 - 1)

I think a 439 message, like a reg-id doesn't exist is appropriate. Sending 200 Ok is definitely wrong.

**Comment by shenya** [comment]
I‘m agree with oej's opinion.

**Comment by miconda** [comment]
439 seems to be associated with the fact that the server has no outbound support, which is not the case here. After some checking I ended up selecting 400 with custom response text -- see the commit linked above.

Testing and reporting the results would be very appreciated.

**Comment by shenya** [comment]
Sorry, please could anyone tell me how to download the patch and apply it to kamailio source project. I just want to test the patch, thank you.

**Comment by miconda** [comment]
@shenya the patch is now also in branch 4.3 and it will be part in v4.3.5 release. Otherwise, you can cherry pick it with git command if you clone the repository from github. If you look in sr-dev mailing list archive for the notification email of this commit, you will find the links to diff and patch variants of the commit.

**Comment by miconda** [comment]
Closing, the issue being fixed.
