### ISSUE TITLE
About Keep-alive method in nathelper and nat_traversal module...

### ISSUE THREAD

**Issue by BroWater** [kamailio/kamailio#498]
Hello,

I found in nathelper module the default value of sipping_method is OPTIONS,
and in nat_traversal module the default value of keepalive_method is NOTIFY.

What makes me confused is that I think sipping_method  and keepalive_method are equivalent,
if it is, why are they different in the SIP method used?

Thanks. :)

**Comment by miconda** [comment]
It was the choice of the developers at the time they wrote the code, in some cases I expect to be more than 10 years ago. However, the mod params gives the possibility to change to the one you like.

If you want to discuss more, use the sr-users@lists.sip-router.org mailing list, we use this tracker to register the bugs and request for features (not to forget them), but not as a forum for discussions.
