### ISSUE TITLE
Deadlock in pua_reginfo (v4.2.6)

### ISSUE THREAD

**Issue by bpetscho** [kamailio/kamailio#499]
Hi,

after receiving a register the kamailio process ends up in a deadlock when calling the function:
```
res = ul.get_urecord_by_ruid(domain, ul.get_aorhash(c->aor), &(c->ruid),
		&record, &_c);
(usrloc_cb.c:264)
```

System setup:
Kamailio version 4.2.6 together with postgres.
pua_reginfo module enabled (modparam publish_reginfo needs to be set to "1").
To reproduce it is enough to send a single registration.

According the change notes the function to get the record was changed from "ul.get_urecord" to "ul.get_urecord_by_ruid" in release 4.2.6.
http://www.kamailio.org/pub/kamailio/4.2.6/ChangeLog
> commit 547f1489cb51a3c72dba72adaa1f6df5429f425e
> Author: Victor Seva <linuxmaniac@torreviejawireless.org>
> Date:   Wed Jul 15 16:00:03 2015 +0200
> 
>     pua_reginfo: use ruid to fix comparation of contact
>     
>     (ptr == c) is always false. Using ruid instead.
>     
>     (cherry picked from commit 7d31d78e3ac861cddfcb70c9940242ec7f3f0dbc)
> 
> commit eb97d380a2fca3b9ce30596aad9493bc11cd5d8d
> Author: Victor Seva <linuxmaniac@torreviejawireless.org>
> Date:   Thu May 28 18:26:08 2015 +0200
> 
>     pua_reginfo: use ul.get_urecord_by_ruid instead of ul.get_urecord
>     
>     (cherry picked from commit 63bd356cc3c7aa64d64361283f630f88b8db88af)
> 

A similair change was done in 4.3.x and reverted short time later:
http://www.kamailio.org/pub/kamailio/4.3.4/ChangeLog
> commit cb644d50f76c80f0f24b34e5adf8723d89aab636
> Author: Victor Seva <linuxmaniac@torreviejawireless.org>
> Date:   Thu Aug 6 15:22:34 2015 +0200
> 
>     Revert "pua_reginfo: use ul.get_urecord_by_ruid instead of ul.get_urecord"
>     
>     This reverts commit 9a6d8d2bffe13b442ed5e880fb0dd2c6572c29e2.
> 

Just by the change notes I cannot find out, why the commit was reverted in 4.3.2.
As a workaround, we changed the used function back to "ul.get_urecord" and have now running tests to verify the functionality. At least the deadlock is fixed with this change.

**Comment by miconda** [comment]
To clarify properly what you describe -- the commit introducing the issue was reverted on 4.3 but not in 4.2?

If yes, @linuxmaniac may have an opinion.

**Comment by bpetscho** [comment]
yes correct - but based on the change notes I cannot say if the commit was reverted in 4.3 due to this issue or due to another reason.

**Comment by linuxmaniac** [comment]
yes, my mistake. This needs to be reverted at 4.2 too

**Comment by linuxmaniac** [comment]
Thanks!

**Comment by bpetscho** [comment]
Thanks as well :-)
