### ISSUE TITLE
kamailio/modules/presence_mwi.so: undefined symbol: eat_printable

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#502]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199630 for details and a proposed patch, but I get the same on Fedora 23 with gcc-5.3.1-2.fc23.x86_64
```
ERROR: <core> [sr_module.c:576]: load_module(): could not open module </usr/lib64/kamailio/modules/presence_mwi.so>: /usr/lib64/kamailio/modules/presence_mwi.so: undefined symbol: eat_printable
```

**Comment by miconda** [comment]
I declared those inline functions as static. Can you try with latest devel or 4.3 git version?

**Comment by amessina** [comment]
I confirm 619988ad6cf54d7e8154a9efb65ce2b9cb475e54 fixes the issue.  Thank you.

**Comment by miconda** [comment]
Thanks!
