### ISSUE TITLE
module http_client - support for preemptive authentication

### ISSUE THREAD

**Issue by filiplx** [kamailio/kamailio#515]
It would be nice if it was possible to configure the module to use preemptive authentication.

I forked the module to add it myself in a primitive way since I needed it only for Basic Authentication, but it would be better to have it configurable.

In functions.h

// Before:
res |= curl_easy_setopt(curl, CURLOPT_HTTPAUTH, (CURLAUTH_DIGEST|CURLAUTH_BASIC));
// After:
res |= curl_easy_setopt(curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

From: https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html

"If more than one bit is set, libcurl will first query the site to see which authentication methods it supports and then pick the best one you allow it to use. For some methods, this will induce an extra network round-trip" <===== this is what I needed to avoid

**Comment by oej** [comment]
Ok, we'll consider this a feature request. I do understand the need for it.

**Comment by oej** [comment]
Committed a patch in 4bf3a51 - please test if it works for you. There's a setting for authmetod in modparams and also in the config file.

**Comment by filiplx** [comment]
This works for me when I tested using modparams.

Thank you very much!

**Comment by oej** [comment]
Thank you for the feedback!
