### ISSUE TITLE
app_perl module - "use UNIVERSAL" is a fatal error starting with Pert 5.22

### ISSUE THREAD

**Issue by lemenkov** [kamailio/kamailio#516]
At least two places in Kamailio where "use UNIVERSAL" is used:

modules/app_perl/lib/perl/Kamailio/LDAPUtils/LDAPConnection.pm
55:use UNIVERSAL qw( isa );
if( isa($conf ,"Kamailio::LDAPUtils::LDAPConnection") ) {

modules/app_perl/lib/perl/Kamailio/VDB.pm
48:use UNIVERSAL qw ( can );
90: if (can($pkg, $3)) {
92: } elsif (can($v, "init")) {
95: } elsif (can($v, "new")) {

This should be fixed as according to this document it will throw a fatal error starting with Perl 5.22:

http://search.cpan.org/~shay/perl-5.21.11/pod/perl5213delta.pod#use%C2%A0UNIVERSAL%C2%A0%27...%27_is_now_a_fatal_error

**Comment by devjunix** [comment]
Hello,

Please consider to apply the attached patch from here:
http://bugs.debian.org/821039

Thanks in advance.
