### ISSUE TITLE
 log file not give response

### ISSUE THREAD

**Issue by patidarshiv3** [kamailio/kamailio#528]
how to get response in kamailio.log
i run client socket program in my pc and start kamailio 
then

i run vim /var/log/kamailio.log
then i got only  on terminal sig_usr(): signal 15 received
i am not got any response what i do please help me

**Comment by miconda** [comment]
This looks like a discussion about sorting out your config and running environment. We use the issue tracker for reporting/fixing bugs and hold new features proposals.

For free support, use the mailing list sr-users@lists.sip-router.org

As hint: in your email, describe how you run kamailio, eventually share you config and explain what happens and what you expect.
