### ISSUE TITLE
kazoo: connection url size to little (50 chars)

### ISSUE THREAD

**Issue by pnlarsson** [kamailio/kamailio#529]
The 50 char limit on the connection url is a bit little. Considering an url like:

amqp://kamailio_ngpbx:password@rabbit01.example.com:5672/virthost01

This is not unreasonable and this is 67 chars.

**Comment by phil-lavin** [comment]
The limit is 100 chars in the latest master - https://github.com/kamailio/kamailio/blob/master/modules/kazoo/kz_amqp.c#L623

You're presumably looking at the current stable.

**Comment by oej** [comment]
Can we backport that Patch

**Comment by miconda** [comment]
I couldn't identify a patch only for increasing the value, so I did a dedicated commit for it in 4.3 branch.
