### ISSUE TITLE
kazoo: missing documentation

### ISSUE THREAD

**Issue by pnlarsson** [kamailio/kamailio#530]
modparam("kazoo", "pua_mode", 0) - missing in docs

how to use an vhost in the connection url is missing: amqp://kamailio_ngpbx:password@rabbit01.example.com:5672/virthost01

**Comment by miconda** [comment]
If you want to add more examples in the docs about variants of urls, we welcome pull requests.

Hopefully @lazedo can fix the missing param in the docs.

**Comment by miconda** [comment]
Referenced in http://lists.sip-router.org/pipermail/sr-users/2016-April/092708.html

**Comment by miconda** [comment]
I pushed a patch to master branch with some docs about pua_mode as understood from mailing lists.
