### ISSUE TITLE
kamailio.log file not print log message

### ISSUE THREAD

**Issue by patidarshiv3** [kamailio/kamailio#532]
in kamailio.log file not print the log message please help me
i check in wireshark then user registraction is complete successfull

**Comment by ycaner06** [comment]
Hey;
Try to set " log_facility=LOG_LOCAL0" in .cfg . and check syslog.conf
and debug levels are important

send this problem to mail list like sr-users@lists.sip-router.org

**Comment by patidarshiv3** [comment]
i set  log_facility=LOG_LOCAL0 and chek but there is not any syslog.conf file (i have kamailio-4.3.4 version) 
and i still not gate log message in kamailio.log 
i configure according to this link       
http://nil.uniza.sk/sip/kamailio/kamailio-logging-how-debian-lenny    
http://lists.sip-router.org/pipermail/sr-users/2013-March/077217.html

**Comment by linuxmaniac** [comment]
Please, use the mail list sr-users@lists.sip-router.org
