### ISSUE TITLE
append_fromtag on upstream in-dialog requests

### ISSUE THREAD

**Issue by schoberw** [kamailio/kamailio#536]
Record-Routing in in-dialog request are not needed by RFC 3261. But there are many clients out there not sending initial route-set in in-dialog requests. To provided them with the initial route-set together with UAC modified requests the ;ftag parameter must be the to-tag on upstream requests.
append_fromtag parameter added the tag value from "from" header always, even on upstream. This is fixed here.

It is not done on record_route_preset(). This should not be called on record routing anyway.

[rr_record.c.patch.txt](https://github.com/kamailio/kamailio/files/164708/rr_record.c.patch.txt)

**Comment by miconda** [comment]
Can you make a pull request via github? In that way is easy to review and merge, plus Travis-CI will compile the patch to be sure it works fine on many distros.

**Comment by schoberw** [comment]
Hi!

It seems I’ve done it wrong. I did a fork and then a pull request. This is obviously not seen by others. Right?
https://github.com/schoberw/kamailio/pull/1

Can you pls help me doing it right?

Thanks!
Br
Walter

Von: Daniel-Constantin Mierla [mailto:notifications@github.com]
Gesendet: Mittwoch, 09. März 2016 09:09
An: kamailio/kamailio
Cc: Walter Schober
Betreff: Re: [kamailio] append_fromtag on upstream in-dialog requests (#536)


Can you make a pull request via github? In that way is easy to review and merge, plus Travis-CI will compile the patch to be sure it works fine on many distros.

**Comment by schoberw** [comment]
Thank you all! Done!
