### ISSUE TITLE
dialog module: dialog in 5 state is not removed

### ISSUE THREAD

**Issue by snen** [kamailio/kamailio#545]
in v4.2
i made  missconfiguration in kamailio.cfg, so kamailio send INVITE to itself: 
INVITE request: endpoint -> kamailio -> kamailio
sip 407: kamailio -> kamailio -> endpoint

alfter that, _dlg.profile_list _ return this dialog up to kamailio restart
```	"result":	[{
			"h_entry":	1185,
			"h_id":	1433,
			"call-id":	"1372913901@192.168.5.52",
			"from_uri":	"sip:000*094@xxxx:5068",
			"to_uri":	"sip:00018966@xxxxxx:5068",
			"state":	5,
			"start_ts":	0,
			"init_ts":	1457963062,
			"timeout":	0,
			"lifetime":	43200,
......................
```

**Comment by miconda** [comment]
What is the exact version you are running (kamailio -v)? There were some fixes in the minor releases in v4.2.x.

**Comment by snen** [comment]
4.2.7 (the latest  git)

**Comment by dragos-oancea** [comment]
Hi. 
Not sure if related but I experimented this with dialog_ng , the command dlg2.list was showing some dialogs in "Deleted" state after several hours after the actual dialogs finished.
Dragos

**Comment by snen** [comment]
as far as I know, in dialog module 5-state-dialiog have to be deleted up to "tm"."wt_timer" period.

**Comment by miconda** [comment]
The transaction is lost after restart -- I pushed a safety clean for aged terminated dialogs to deal with the case.

**Comment by miconda** [comment]
Following the comments on commit: I understood the issue appears is revealed after a restart, so this was a safety for such cases, because the transaction is not recovered afterwards. If the dialog will be destroyed when the response is received, then retransmitted messages won't be handled properly (e.g., uac module has some features relying on dialog module), that's the reason for destroying when transaction is destroyed.

**Comment by snen** [comment]
> Following the comments on commit:
sorry I did not write it here

> I understood the issue appears is revealed after a restart
Without commit  23a3481: there are  dialog in 5 state which alive while kamailio alive  (deleted after kamailio restart )

> If the dialog will be destroyed when the response is received, then retransmitted messages won't be handled properly
So may be it is a good idea  adding dialog status filter to "get_profile_size".

**Comment by miconda** [comment]
Not sure with 4.2, but in the latest version the dialog should be removed from profile immediately it gets to state terminated, not waiting for the dialog to be destroyed.

**Comment by snen** [comment]
ok. thanks
