### ISSUE TITLE
Error with has_body("application/media_control+xml")

### ISSUE THREAD

**Issue by fabiomargarido** [kamailio/kamailio#547]
Hi there.

When I try to add the following line to my config script:

```
if (is_method("INFO") && has_body("application/media_control+xml"))
```

Kamailio fails to start with these errors:

>  0(12) ERROR: <core> [parser/parse_content.c:370]: decode_mime_type(): ERROR:decode_mime_type: parse error near in [application/media_control+xml] char[95][_] offset=17
>  0(12) ERROR: textops [textops.c:2426]: fixup_body_type(): unsupported mime <application/media_control+xml>
>  0(12) ERROR: <core> [route.c:1154]: fix_actions(): fixing failed (code=-6) at cfg:/etc/kamailio/kamailio.cfg:549
>  0(12) ERROR: <core> [route.c:1154]: fix_actions(): fixing failed (code=-6) at cfg:/etc/kamailio/kamailio.cfg:556
>  0(12) ERROR: <core> [route.c:1154]: fix_actions(): fixing failed (code=-6) at cfg:/etc/kamailio/kamailio.cfg:568
>  ERROR: error -6 while trying to fix configuration

This is with the official Debian packages of Kamailio 4.3.5.

**Comment by miconda** [comment]
The '_' char was considered invalid for content type -- I relaxed the condition. You need to use git branch 4.3 to get the patch.

If the issue is still there, reopen.
