### ISSUE TITLE
permissions - database examples in 4.4  for postgresql and mysql is not updated to version 6

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#556]
The database schemas has version 5, the module requires version 6. It seems like the schemas in master is up-to-date

**Comment by oej** [comment]
I guess we need to cherry-pick commit 6b76de9f7d991ed3fdc5f2f28dde7bcb1962108b to 4.4

**Comment by miconda** [comment]
I see it also in branch 4.4, if you refer to sql creating scripts from kamctl/kamdbct. That change was before branching 4.4, iirc.

**Comment by oej** [comment]
Well, the module requires a database structure that we haven't got in /utils/kamctl :-)

**Comment by miconda** [comment]
This is from branch 4.4:

```
 CREATE TABLE `trusted` (
      `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
      `src_ip` VARCHAR(50) NOT NULL,
      `proto` VARCHAR(4) NOT NULL,
      `from_pattern` VARCHAR(64) DEFAULT NULL,
      `ruri_pattern` VARCHAR(64) DEFAULT NULL,
      `tag` VARCHAR(64),
      `priority` INT DEFAULT 0 NOT NULL
  );

  CREATE INDEX peer_idx ON trusted (`src_ip`);

  INSERT INTO version (table_name, table_version) values ('trusted','6');
```

If it is wrong, what shout it be there?

**Comment by oej** [comment]
We had two checkouts saying otherwise, but now mine says the same as yours. Arrrggghh.
