### ISSUE TITLE
Timeout param added in ndb_redis module

### ISSUE THREAD

**Issue by misaksen** [kamailio/kamailio#557]
The connection timeout was hardcoded to 1 sec. This can now be set from cfg file.

If the redis server became unresponsive kamailio would wait for the standard Linux TCP timeout for an answer (very long time).

This patch has added an timeout value for redis commands.

The default timeout is 1 sec.
[30-redis-timeout.txt](https://github.com/kamailio/kamailio/files/198503/30-redis-timeout.txt)

**Comment by misaksen** [comment]
We have found a few issues with this patch. I will send a new patch later.

**Comment by miconda** [comment]
It is better to make a pull request, in that way the patch can be reviewed directly on github and it is compiled to see if it rises any issues. After that, merging the patch is just one click.

**Comment by misaksen** [comment]
Hi Daniel,

OK. I will try to do that with the next patch.

/Morten

**Comment by misaksen** [comment]
Pull request #559 created.

**Comment by miconda** [comment]
Closing this one an continuing on the pull request if there is anything else to be discussed.
