### ISSUE TITLE
cfgt: wrong flow if route has no last action return

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#569]
The actual implementation is based on the cfg actions, so when there is no 'return' action defined the route flow detected is wrong.

**Comment by miconda** [comment]
Is still an issue, or it was fixed with latest devel cycles?

**Comment by henningw** [comment]
@linuxmaniac - any update on this?

**Comment by henningw** [comment]
No update since a few months. As the issue is from 2016 I am going to close this one. Please re-open with more details if the problem is still valid.
