### ISSUE TITLE
SIP Forking race condition

### ISSUE THREAD

**Issue by phil-lavin** [kamailio/kamailio#570]
Pcap that demonstrates this (I had to zip it for GitHub) is: [fork-fail-filtered.zip](https://github.com/kamailio/kamailio/files/221097/fork-fail-filtered.zip). In this example, Kamailio is a registration proxy.

If two phones answer the call at the same time, it is possible for the CANCEL to be received by one of the phones after it has entered the `completed` state. It will, thus, respond with a `481` or similar. Kamailio then continues to process the traffic sent by the cancelled phone.

Ideally, Kamailio should `ACK` and `BYE` in response to the `200` if it ends up in this state.

**Comment by miconda** [comment]
Actually this needs to be handled by the client side. If it has already answered with 200ok, should reject the CANCEL with a negative response. Kamailio is proxy and cannot generate requests on behalf o devices. This is a well known race and the resolution by SIP RFC is that in case of receiving 2 of 200ok, the proxy must send both to caller in order for the calling device to decide which call has the best attributes for communication (e.g., one may have video, the other not).

The two 200ok can happen also if the cancel is generated by the caller device itself. Think of a parallel forking to two devices that have auto-answer machine turned on. Both will just send 200ok immediately. Also, the caller can send the cancel before any device responds, kamailio forwards the cancel but at the same time called devices answer. The caller device should send the BYE for both 200ok.

If you are still not convinced, you can discuss on mailing lists or sip-implementors forum. This is not a bug in Kamailio anyhow.

**Comment by phil-lavin** [comment]
Thanks, Daniel. You've convinced me :D
