### ISSUE TITLE
Using registered() in event_route[usrloc:contact-expired] causes Kamailio to hang

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#577]
In the contact-expired event route I want to check if the expired AOR is registered elsewhere, by checking replicated location tables like "location-peer". Using the registered("location-peer", "<aor>") function causes Kamailio to go to sleep and not respond to rpc commands.

**Comment by miconda** [comment]
What is the db_mode you tried with?

**Comment by oej** [comment]
No DB at all

**Comment by miconda** [comment]
Using another function that tries to access the same location record that expired is trying to lock same slot in usrloc internal hash table. The solution would be implementing re-entrant locks there. I will try to do it when I get the first chance.

**Comment by miconda** [comment]
I pushed a commit to master to make the locks in usrloc reentrant. No testing for reported case, would be appreciated if you can give it a try.

The changes are to a critical module, so we may need to live with this limitation until 5.0.

**Comment by miconda** [comment]
Closing this item as a patch was fixed a while ago. If still an issue there, re-open or create a new item.
