### ISSUE TITLE
sca module

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#580]
The README needs to be up to date with the source code. I noted that the "Outbound proxy" modparam is not documented.

**Comment by oej** [comment]
There's also eleven RPC commands, and only five in the README.

**Comment by oej** [comment]
Also note that ALL error and debug messages needs to be terminated with a new line.

**Comment by TheGrandWazoo** [comment]
Thank you Olle.

**Comment by TheGrandWazoo** [comment]
In reference to the "Outbound Proxy" modparam, it is NOT used anywhere in the SCA module code base. I did a search for the outbound_proxy variable in the code base and it was only found in sca.c and sca.h. I commented out each reference in the sca.c and sca.h and compiled it without error. I believe it to be fictitious parameter at this time.

**Comment by miconda** [comment]
It seems, most of the items were addressed. RPC commands are indexed in a separate file (see wiki) -- we need to unify that, but is global across all modules, not specific here.

If anything forgotten, then a new report would be better.
