### ISSUE TITLE
kamailio v4.4.0-12.1 x86_64 RPM install user/group not added on Oracle Enterprise Linux 7.2

### ISSUE THREAD

**Issue by kvishnivetsky** [kamailio/kamailio#584]
Hi, All.

This scriplet will not do what we need:

preinstall scriptlet (using /bin/sh):
**/usr/sbin/groupadd** -r kamailio 2> /dev/null || :
**/usr/sbin/useradd** -r -g kamailio -s /bin/false -c "Kamailio daemon" \
                  -d /var/run/kamailio kamailio 2> /dev/null || :

The cause is, that utils **groupadd** and **useradd** are located under **/sbin** directory in OEL7.x
Solution: to add an **if** statement to determine which path to use, like:
if [ -e /sbin/useradd ]; then ......; else .....; fi
or use RPM macro to determine which EL is actually used.

**Comment by miconda** [comment]
You refer to the specs on opensuse build service, right?

I think we can remove the absolute path and just use the tools names, I expect both /sbin and /usr/sbin should be in the default path for well known linux distros.

**Comment by kvishnivetsky** [comment]
Hi, @miconda.
I installed from here:
http://download.opensuse.org/repositories/home:/kamailio:/v4.4.x-rpms/RHEL_7/home:kamailio:v4.4.x-rpms.repo

**Comment by miconda** [comment]
I updated the specs without absolute path and the rpms were build.

  * https://build.opensuse.org/package/show/home:kamailio:v4.4.x-rpms/kamailio44

Reopen this item if the issue is still there.

**Comment by kvishnivetsky** [comment]
Just tested you brand new packages.
it's very interesting:
On a already installed system %pre scriptlet work just fine.
On installing from an ISO system %pre scriptlet doest not work.
