### ISSUE TITLE
v4.4.0 tcp disabled?

### ISSUE THREAD

**Issue by lqxandxl** [kamailio/kamailio#585]
i used kamailio v4.1  

part of  kamailio.cfg 
for examples:

disable_tcp=no
auto_aliases=no

port=5085
enable_tls=yes
listen=udp:10.2.45.111:5085
listen=tcp:10.2.45.111:5085
listen=tls:10.2.45.111:5086
listen=tcp:10.2.45.111:5087
listen=tls:10.2.45.111:5088

and i excute
/etc/init.d/kamailio start
it can run

but when on ka v4.4.0 
the same contents in kamailio.cfg but can`t run 

both 4.1.x and 4.4.x when i change 
disable_tcp=yes 
it can run
but only listen on udp 5085 

v4.1 i change disable_tcp=no 
it can listen tls,tcp.udp

i use modules： dispatcher 
v4.4 i setup a new modules : evapi 

why tcp can`t run properly?

**Comment by miconda** [comment]
Look inside syslog file and see the error messages -- there might be something wrong in the new config. If you don't figureout the issue yourself, paste the log messages here.

Otherwise I do not recall any change on the disable_tcp behaviour for many years.

**Comment by lqxandxl** [comment]
there is nothing in /var/log/kamailio.log when i excute /etc/init.d/kamailio start 
what`s more when i set 
disable_tcp=no
enable_tls=no 
it run with tcp ,udp without tls

when set
disable_tcp=no
enable_tls=yes  
it can`t work 

tcp and tls can`t work together

**Comment by miconda** [comment]
Not very clear for me -- is kamailio starting or not? If not starting, then some error message must be there in syslog.

**Comment by lqxandxl** [comment]
you are right i set the loglevel too low

here is the problem seem like tls

Apr 27 05:14:11 localhost /home/liqixin/kamailio_proxy/sbin/kamailio[18444]: : tls [tls_init.c:557]: init_tls_h(): ERROR: tls: init_tls_h: installed openssl library version is too different from the library the Kamailio tls module was compiled with: installed "OpenSSL 1.0.1e-fips 11 Feb 2013" (0x1000105f), compiled "OpenSSL 1.0.2a 19 Mar 2015" (0x1000201f).#012 Please make sure a compatible version is used (tls_force_run in kamailio.cfg will override this check)

Apr 27 05:14:11 localhost /home/liqixin/kamailio_proxy/sbin/kamailio[18444]: CRITICAL: <core> [main.c:2577]: main(): could not initialize tls, exiting...

----------------------------------------------------------------------------------------------
[liqixin@localhost log]$ openssl version -a

OpenSSL 1.0.2a 19 Mar 2015
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl"

**Comment by lqxandxl** [comment]
tls`s solution way:
v4.1:tls`s key and pem is installed in kamailio_proxy
v4.4:not installed in


there still exists error in version 4.4  not in v4.1
-----------------------------------------------------------------------------------------------------------------------------

Apr 27 19:41:30 localhost /home/administrator/kamailio_proxy/sbin/kamailio[4068]: ERROR: dispatcher [dispatcher.c:787]: ds_warn_fixup(): failover functions used, but required AVP parameters are NULL -- feature disabled
Apr 27 19:41:30 localhost /home/administrator/kamailio_proxy/sbin/kamailio[4068]: ERROR: dispatcher [dispatcher.c:787]: ds_warn_fixup(): failover functions used, but required AVP parameters are NULL -- feature disabled

**Comment by miconda** [comment]
Thanks for describing what was wrong and how it was solved. It will help others facing same issues.
