### ISSUE TITLE
RPM mock build under Oracle Enterprise Linux 7.2 x86_64 failure (no modules in modules_k directory)

### ISSUE THREAD

**Issue by kvishnivetsky** [kamailio/kamailio#586]
Hi, People.

SPEC used: [https://github.com/kamailio/kamailio/blob/4.4/pkg/kamailio/rpm/kamailio.spec.SuSE](https://github.com/kamailio/kamailio/blob/4.4/pkg/kamailio/rpm/kamailio.spec.SuSE)
BRANCH: 4.4
I tried to build kamailio with mock and got errors on files to RPM packaging stage:
```
Processing files: kamailio-4.4.0-0.x86_64
error: File not found: /builddir/build/BUILDROOT/kamailio-4.4.0-0.x86_64/usr/share/doc/kamailio/modules_k/README.acc
...
File not found: /builddir/build/BUILDROOT/kamailio-4.4.0-0.x86_64/usr/share/doc/kamailio/modules_k/README.acc
...
```

Build command:
`mock --no-cleanup --no-cleanup-after -r oracle-7-x86_64 --configdir=. --resultdir=./mock-result /home/developer/rpmbuild/SRPMS/kamailio-4.4.0-0.src.rpm`

Here goes mock configuration file(without yum configuration section):

```
config_opts['basedir'] = '/home/developer/mock/base'
config_opts['cache_topdir'] = '/home/developer/mock/cache'

config_opts['root'] = 'oracle-7-x86_64'
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['chroot_setup_cmd'] = 'groupinstall buildsys-build Development'
config_opts['dist'] = 'el7'  # only useful for --resultdir variable subst
config_opts['macros']['%dist'] = '.el7'
config_opts['macros']['%el7'] = '1'
config_opts['macros']['%rhel'] = '7'

```

**Comment by miconda** [comment]
The specs from pkg/kamailio/rpm/ were not much maintained for many years, try to use the one from centos or fedora:

  * https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/centos/6/kamailio.spec
  * https://github.com/kamailio/kamailio/blob/master/pkg/kamailio/fedora/17/kamailio.spec

Or extract the corresponding parts from the one at opensuse build service:

  * https://build.opensuse.org/package/show/home:kamailio:v4.4.x-rpms/kamailio44

Practically, most of the modules from modules_k/ folder were moved to or merge into other modules from modules/ folder. You can try to replace the modules_k with modules and see if works fine.

If you want to contribute updated specs, you are more than welcome -- they will be accepted in the repo.

**Comment by kvishnivetsky** [comment]
Hi, @miconda .

Renaming **modules_k** to **modules** in **SPEC** helped, thanks for advice.
I'll contribute **SPEC** and some system files for **EL{6,7}**.
Those files will be located under **<SRCROOT>/pkg/kamailio/el/el{6,7}** .

**Comment by kvishnivetsky** [comment]
I successfully belt **kamailio** branch **4.4** with modified **kamailio.spec** file.
Which branch should I commit **kamailio.spec** file to?

**Comment by kvishnivetsky** [comment]
https://github.com/kamailio/kamailio/pull/588

**Comment by kvishnivetsky** [comment]
Just tested you brand new packages.
it's very interesting:
On a already installed system **%pre scriptlet** work just fine.
On installing from an ISO system **%pre scriptlet** doest _not_ work.

**Comment by kvishnivetsky** [comment]
Hi, @miconda .
I'm about to commit new patches, which will make **kamailio** project able to be belt for any **RHEL**-based distro in **mock** environment(build host stays **very** clear - minimal development enviromnet is needed for such build process).
The directory structure under <SRCROOT>/pkg need to be changed to satisfy following:
<SRCROOT>/pkg/kamailio(ser)/<target-distro-name>/el<target-distro-release-major-version>
There need to be stored following files under each such directory:
kamailio(ser).spec (with system specific files installation instructions)
kamailio.* (system specific files like sysconfig(defaults), service(systemctl))
<target-distro-name>-<target-distro-version>-<taget-distro-arch>.cfg - mock config for particular target distro
It is a subject for discussion, so I'm waiting for comments.

**Comment by miconda** [comment]
I think the patches were pushed, closing this item. If other issues with rpms, open a new bug.
