### ISSUE TITLE
unable to listen using eth interface

### ISSUE THREAD

**Issue by victoru** [kamailio/kamailio#602]
[According to the latest docs](http://www.kamailio.org/wiki/cookbooks/4.4.x/core#listen) kamailio should be able to listen on an address using the interface name of a local device. However, each time I try anything like:

    listen=eth2:5062

I get:

    0(1) ERROR: <core> [socket_info.c:1328]: fix_hostname(): could not resolve eth2

I also came across an older thread where someone else also noticed this: http://sip-router.1086192.n5.nabble.com/Listen-on-eth-alias-interface-td128206.html

**Comment by miconda** [comment]
Listen is with eth1, but the log message is with eth2. Is there a mistake somewhere?

**Comment by victoru** [comment]
sorry, that was just an example. it doesn't matter what I use as kamailio doesnt seem to recognize the value as an interface name.

**Comment by victoru** [comment]
I just upgraded from 4.3 to 4.4 and everything seems to be working normally
