### ISSUE TITLE
Implement method to selectively disable MSILO offline notification

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#61]
If Kamailio is globally configured to send offline notification replies using `modparam("msilo", "from_address", "sip:$rU@example.com")`, there is currently no way to disable the offline notification reply during script processing.

For example, a scenario where you might want to store the original MESSAGE but not send the offline notification reply is when you are also using the IMC module.  When `user@example.com` is part of an IMC chat, but goes offline for some reason, the MSILO module will store original MESSAGE, then generate the offline notification reply back to the IMC chat, which generates another MESSAGE with `user@example.com` as a recipient...  This instantly leads to thousands of MESSAGE generations.

I am thinking that it's a nice feature to have offline notification replies enabled when  `modparam("msilo", "from_address", "sip:$rU@example.com")` is defined, but that the MSILO module could check the existence (nor non-existence) of a flag to determine whether or not it would generate an offline notification reply, so the logic would be something like:

```
#!define FLT_MSILO_DISABLE_OFFLINE_REPLY 13
modparam("msilo", "from_address", "sip:$rU@example.com")
modparam("msilo", "disable_offline_reply_flag", FLT_MSILO_DISABLE_OFFLINE_REPLY)
```
Then m_store() checks that `from_address` is valid and that `disable_offline_reply_flag` is not set.

**Comment by miconda** [comment]
I pushed a commit implementing the feature in msilo. Testing and feedback is appreciated.

There is a way to get the functionality even with existing version, but is more complex, therefore went for this proposed option.
