### ISSUE TITLE
db_cassandra can't find table version

### ISSUE THREAD

**Issue by goharahmed** [kamailio/kamailio#618]
Hi devs,

I'm trying to make the db_cassandra work for my kamailio specifically userblacklist module.

I've cassanda keyspace and tables defined along with the db_schema directory structure defined as instructed however the debug logs keep telling me that table 'version' doesn't exist.

I've taken a look inside the dbcassa_table.c file 
https://github.com/kamailio/kamailio/blob/master/modules/db_cassandra/dbcassa_table.c#L441

Somewhere in this function it just doesn't get hold of "tbc" and hence it throws up error.

Here is how I've figured out this code.

```
        hash = core_hash(dbn, tbn, DBCASSA_TABLE_SIZE);
        **if(!hash)
                LM_ERR("hash  NOT FOUND\n");**
        hashidx = hash % DBCASSA_TABLE_SIZE;
        **if(!hashidx)
                LM_ERR("hashidx NOT FOUND\n");**
        ref_read_data(dbcassa_tbl_htable[hashidx].lock);

        tbc = dbcassa_tbl_htable[hashidx].dtp;
        **if(!tbc)
                LM_ERR("TBC NOT FOUND\n");**
        while(tbc) {
                LM_DBG("found dbname=%.*s, table=%.*s\n", tbc->dbname.len, tbc->dbname.s, tbc->name.len, tbc->name.s);
                if(tbc->hash==hash && tbc->dbname.len == dbn->len
                                && tbc->name.len == tbn->len
                                && !strncasecmp(tbc->dbname.s, dbn->s, dbn->len)
                                && !strncasecmp(tbc->name.s, tbn->s, tbn->len)) {

                        memcpy(full_path_buf + dbcassa_schema_path.len, dbn->s, dbn->len);
                        len = dbcassa_schema_path.len + dbn->len;
                        full_path_buf[len++] = '/';
                        memcpy(full_path_buf + len, tbn->s, tbn->len);
                        full_path_buf[len + tbn->len] = '\0';

                        if(dbcassa_check_mtime(&tbc->mt) == 0)
                                return tbc;
                        old_tbc = tbc;
                        break;
                }
                tbc = tbc->next;
        }
        unref_read_data(dbcassa_tbl_htable[hashidx].lock);
        **if(!old_tbc) {
                LM_ERR("OLD_TBC NOT FOUND\n");**
                return NULL;
        }
```

and upon starting of kamailio after recompiling the module I see these lines printed.

```
 0(15574) DEBUG: db_cassandra [dbcassa_base.cpp:149]: db_cassa_new_connection(): opening connection: cassa://xxxx:xxxx@127.0.0.1:9160/kamailio
 0(15574) DEBUG: <core> [mem/f_malloc.c:439]: fm_malloc(): fm_malloc(0x7f9c14f8a010, 48) called from db_cassandra: dbcassa_base.cpp: db_cassa_new_connection(155)
 0(15574) DEBUG: <core> [mem/f_malloc.c:514]: fm_malloc(): fm_malloc(0x7f9c14f8a010, 48) returns address 0x7f9c150055f0
 0(15574) DEBUG: db_cassandra [dbcassa_base.cpp:161]: db_cassa_new_connection(): 0x7f9c150055f0=pkg_malloc(48)
 0(15574) DEBUG: db_cassandra [dbcassa_base.cpp:117]: dbcassa_open(): Opened connection to Cassandra cluster  127.0.0.1:9160
 0(15574) DEBUG: db_cassandra [dbcassa_base.cpp:955]: db_cassa_query(): query table=version
 **0(15574) ERROR: db_cassandra [dbcassa_table.c:463]: dbcassa_db_get_table(): TBC NOT FOUND
 0(15574) ERROR: db_cassandra [dbcassa_table.c:486]: dbcassa_db_get_table(): OLD_TBC NOT FOUND**
 0(15574) ERROR: db_cassandra [dbcassa_base.cpp:449]: cassa_translate_query(): table version does not exist!
 0(15574) ERROR: db_cassandra [dbcassa_base.cpp:962]: db_cassa_query(): Failed to query Cassandra cluster
 0(15574) ERROR: <core> [db.c:397]: db_table_version(): error in db_query
 0(15574) ERROR: <core> [db.c:436]: db_check_table_version(): querying version for table userblacklist
 0(15574) ERROR: userblacklist [db_userblacklist.c:86]: userblacklist_db_init(): during table version check.
 0(15574) DEBUG: <core> [db_pool.c:100]: pool_remove(): removing connection from the pool
 0(15574) DEBUG: <core> [mem/f_malloc.c:575]: fm_free(): fm_free(0x7f9c14f8a010, 0x7f9c150055f0), called from db_cassandra: dbcassa_base.cpp: db_cassa_free_connection(203)
 0(15574) DEBUG: <core> [mem/f_malloc.c:594]: fm_free(): fm_free: freeing block alloc'ed from db_cassandra: dbcassa_base.cpp: db_cassa_new_connection(155)
 0(15574) DEBUG: <core> [mem/f_malloc.c:575]: fm_free(): fm_free(0x7f9c14f8a010, 0x7f9c15005318), called from core: db.c: db_do_close(356)
 0(15574) DEBUG: <core> [mem/f_malloc.c:594]: fm_free(): fm_free: freeing block alloc'ed from core: db.c: db_do_init2(298)
 0(15574) ERROR: <core> [sr_module.c:968]: init_mod(): Error while initializing module userblacklist (/usr/local/lib64/kamailio/modules/userblacklist.so)
ERROR: error while initializing modules
```

Kindly look into this and let me know how to make this work.

Thanks,
Sammy

**Comment by miconda** [comment]
Do you have other modules connecting to cassandra? Are they loaded before the userblacklist module?

**Comment by goharahmed** [comment]
Hi Daniel,
Yes I've db_mysql loaded all other modules loaded with default/sample kamailio.cfg these days. I added cassandra module just after the db_mysql and added userblacklist module at the end of module declarations.

I tried adding another module in cassandra and it didn't work too - same version table not found.

**Comment by miconda** [comment]
Never used cassandra myself, so I don't have an environment to test this myself. Would it be possible to get access to this system or a similar one where I could troubleshoot? I need also the sources of kamailio to do changes and try again in order to fix it.

**Comment by goharahmed** [comment]
I'll be happy to provide you with the access, this was all installed from sources ( as I did some recompilations for debugging purposes too) -
Let me know when and where so I can guide you through this setup.

**Comment by miconda** [comment]
Right now I am traveling, so we can attempt to do it sometime at the beginning of next week.

**Comment by goharahmed** [comment]
Sure, I'll wait up.

**Comment by miconda** [comment]
You can grant me ssh access with the key at:

  * https://www.kamailio.org/~daniel/sshkeys/miconda_id_rsa.pub

Send me the ip and username via email to miconda at gmail dot com.

You have to grant sudo operation to the ssh user.

**Comment by goharahmed** [comment]
Hi Daniel,

Sorry for being late, got distracted by other projects and work. I've the
server with cassandra stuff still intact. I left to use ndb_cassandra in
place of db_cassandra. Apparently there are so many things that are either
missing/not implemented or I don't have enough skills to fix them.for
example - Cassandra authentication is not implemented in ndb_cassandra, I
had to turn off authentication.

I've added your key to my server, please let me know when you intend to
join so I be able to join and assist

--
*GOHAR AHMED *


*Sr. VoIP Systems Software Engineer *

*Tel: *+1.519.807.2240 *|* *Skype: *scribedfor

www.saevolgo.ca

<http://www.linkedin.com/pub/gohar-ahmed/35/81b/107>
<https://www.facebook.com/saevolgo/>  <https://twitter.com/saevolgo>
<http://saevolgo.blogspot.com/>
<https://www.packtpub.com/virtualization-and-cloud/implementing-citrix-xenserver-quickstarter>

*- SaevolGo delivers reliable VoIP services - *

**Comment by henningw** [comment]
@goharahmed -there has been no updates to this issues in 2017 from you. I will close this issue - please re-open if you want to continue with debugging the issue.

**Comment by goharahmed** [comment]
Sure go ahead. Daniel got busy too and I didnt use the module again. It
would be nice however to look into the issues and improve Kamailio for
better of community.

Best regards.


On Mar 3, 2018 1:43 PM, "henningw" <notifications@github.com> wrote:

@goharahmed <https://github.com/goharahmed> -there has been no updates to
this issues in 2017 from you. I will close this issue - please re-open if
you want to continue with debugging the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kamailio/kamailio/issues/618#issuecomment-370170142>,
or mute the thread

**Comment by henningw** [comment]
You are of course right. But the original author of this module changed the company several years ago, there has been some extensions in 2012, and several patches in 2014. Otherwise it has been not that actively maintained. If other people have other issues in the module, we can re-open this bug as well.

**Comment by goharahmed** [comment]
Well by all means close this one and delete it. :)
It has been so long and nowadays there are so many alternatives available.
Im sure nobody would need it precisely for what I wanted to achieve.

**Comment by henningw** [comment]
I don't have any recent first-hand experience with this module. I would assume that it works generally, otherwise I would expect to see more bug reports about it. But lets really close this thread. :-) As mentioned, if you want to give it another try, just re-open or open a new bug report.
