### ISSUE TITLE
sipcapture README does not document sip_capture script function

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#63]

**Comment by miconda** [comment]
@adubovikov - it seems none of the sipcature functions for cfg are documented. Can you add some description to the module docs?

**Comment by adubovikov** [comment]
I will do it tomorrow.

**Comment by adubovikov** [comment]
https://github.com/kamailio/kamailio/commit/f302cc5b878a07b18ced0bc78db0cca14ca8d602

**Comment by miconda** [comment]
Thanks!
