### ISSUE TITLE
Enable compilation with gcc-6.1.1

### ISSUE THREAD

**Issue by amessina** [kamailio/kamailio#633]
In preparing RPMs for Fedora 24, I'm unable to compile...```Makefile.defs:980: You are using an old and unsupported gcc version  (6.1.1), compile at your own risk!```

**Comment by miconda** [comment]
Can you try with the commit referenced above? If all ok, it will be backported.

**Comment by amessina** [comment]
@miconda, 1975ebdf37b9ffd325a38960bc0bf417466b432f fixes the issue on.  Thank you.

**Comment by miconda** [comment]
Backported.

**Comment by amessina** [comment]
@miconda, I don't see this in the 4.4 branch.

**Comment by miconda** [comment]
Ohh, the push failed at that moment and I didn't check the output in the terminal tab. Re-done now and looks ok.
