### ISSUE TITLE
"flags" and "reg_delay" uacreg columns not read if database lacks DB_CAP_FETCH capability

### ISSUE THREAD

**Issue by AndyJRobinson** [kamailio/kamailio#640]
In both 4.4.1 and master, the recently added "flags" and "reg_delay" columns are not read if the database lacks DB_CAP_FETCH capability. uac.reg_dump shows them as some large random values.

The issue is in uac_reg.c:uac_reg_load_db().

`	if (DB_CAPABILITY(reg_dbf, DB_CAP_FETCH)) {
		if(reg_dbf.query(reg_db_con, 0, 0, 0, db_cols, 0, 12, 0, 0) < 0)`

... so if the database has DB_CAP_FETCH capability, 12 columns are read; however, if not...

`	} else {
		if((ret=reg_dbf.query(reg_db_con, NULL, NULL, NULL, db_cols,
						0, 10, 0, &db_res))!=0
				|| RES_ROW_N(db_res)<=0 )
		{` 

only 10 columns are read, missing the last two (flags and reg_delay)

**Comment by miconda** [comment]
Can push a pull request with the change you detailed above? it makes it easier to review and merge the fix.

**Comment by miconda** [comment]
Fixed with PR #642, to be backported.
