### ISSUE TITLE
[Support] Config SIP-I

### ISSUE THREAD

**Issue by xuansinhmedia** [kamailio/kamailio#641]
Hi,
I am a newbie here. i am using Kamailio version 4.4 on CentOS 6.
i need configuration to send INVITE encapsulate ISUP.
Please guide me about this configuaration.
Thank you.

**Comment by mslehto** [comment]
Please use mailing list for general queries. This tracker is for bug reports.
See sr-users on https://www.kamailio.org/w/mailing-lists/

**Comment by miconda** [comment]
As quick hint here -- the routing of sip-i/t should just work, if you need something more, then see sipt module. For more or further discussions, go to sr-users mailing list as per @mslehto suggestion.

**Comment by kamailio-sync** [comment]
If you need to modify ISUP, have a look at the sip-t module of kamailio.

Torrey
