### ISSUE TITLE
evapi_relay not working in resumed transaction

### ISSUE THREAD

**Issue by qmphan** [kamailio/kamailio#644]
If evapi_relay is called from a resumed transaction (in an event route), it doesn't send anything:

route[my_route] {
    evapi_relay("Blah blah blah"); # This sends nothing
}
...

event_route[evapi:message-received] {
     ....
     t_continue("$var(tindex)", "$var(tlabel)", "my_route");
}

**Comment by miconda** [comment]
Pushed a patch (referred above) that relocates the resetting of T_ASYNC_SUSPENDED. Can you test and see the results? If all ok, it can be considered for backporting.

**Comment by qmphan** [comment]
It works!!! Thank you for the fix @miconda !

**Comment by miconda** [comment]
@qmphan is it working or not? In #622 you say evapi doesn't work anymore.

**Comment by qmphan** [comment]
@miconda : The patch above (827ec4f) works great. The one in #622 (2d1a7e4) doesn't.

**Comment by miconda** [comment]
OK - confused as you closed then re-opened this issue. So this can be closed.

**Comment by qmphan** [comment]
Yeah, I closed it then I thought it should be left open as a reminder to backport :)
