### ISSUE TITLE
$dlg_var variables not available in event rotues

### ISSUE THREAD

**Issue by qmphan** [kamailio/kamailio#646]
I'm trying to have an external application to write CDR to a database by doing this:

```
event_route[dialog:start] {
        evapi_relay("{'cdr_id': $dlg_var(cdr_id), 'event': 'answered'}");
}
event_route[dialog:end] {
        evapi_relay("{'cdr_id': $dlg_var(cdr_id), 'event': 'ended'}");
}

event_route[dialog:failed] {
        evapi_relay("{'cdr_id': $dlg_var(cdr_id), 'event': 'failed'}");
}
```

$dlg_var(cdr_id) is set inside a request route. However, in these event routes, its value is always null. Its seems that $dlg_var variables are not available in those event routes.

**Comment by miconda** [comment]
Testing with latest 4.4 and 5.0 all seems ok. Reopen if there is still an issue.
