### ISSUE TITLE
comma delimiter overrides specified delimiter in param transformation

### ISSUE THREAD

**Issue by snen** [kamailio/kamailio#648]
i try script:

```
$var(some_string) = 'a=foo1;b=foo2;c=foo3,4,5;d=3';
$var(c_value) = $(var(some_string){param.value,c,;});
xlog("L_INFO", "'c' param from '$var(some_string)' is '$var(c_value)'");
```

in log:

>  'c' param from 'a=foo1;b=foo2;c=foo3,4,5;d=3' is 'foo3'

 Has this  behaviour any reason? or it's possible to delete comma from stop list (and use separator parameter for comma-delimited list)?

```
diff --git a/parser/parse_param.c b/parser/parse_param.c
index b9e0fbc..e7784c8 100644
--- a/parser/parse_param.c
+++ b/parser/parse_param.c
@@ -355,7 +355,6 @@ static inline int parse_token_param(str* _s, str* _r, char separator)
                case '\t':
                case '\r':
                case '\n':
-               case ',':
                             /* So if you find
                              * any of them
                              * stop iterating
```

**Comment by miconda** [comment]
The parser takes in consideration the delimiters for SIP headers and parameters. The comma is a delimiter of serialized header bodies, therefore ending the parameter value. You can enclose the value that has a comma in quotes.

An alternative params transformation that doesn't follow the sip grammar rules can be added - e.g., it can be named gparam (generic param).

**Comment by snen** [comment]
quotes are not OK in case of third party string generation.
may be adding new "gparam" is a good idea: no any reasons to be SIP compliant, while using string transformations

**Comment by miconda** [comment]
Marked it as an enhancement request. If anyone wants to go ahead and implement, it would be of course appreciated.

**Comment by miconda** [comment]
Closing this one as no interest shown for long time -- if someone wants it, just make a pull request.
