### ISSUE TITLE
keep new features in a file in the repository

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#668]
This will allow us to point https://www.kamailio.org/wiki/features/new-in-devel to the file and "force" developers to update that file with the new features when they are introduced in the repository

Remaining developers to upgrade the wiki seems pointless and anyone can create a PR for changes

**Comment by oej** [comment]
+2

My experience is that this works much better.

**Comment by albertollamaso** [comment]
You can map that file to a page in Dokuwiki in order to keep the wiki up to date automatically...even after a change of a PR.

**Comment by miconda** [comment]
Now kamailio-wiki is on github as well (https://github.com/kamailio/kamailio-wiki), all devs should have access and the others can make PRs, so I think this should be closed, it's long time without any activity.
