### ISSUE TITLE
dprint.h logging macros are not portable 

### ISSUE THREAD

**Issue by sjthomason** [kamailio/kamailio#678]
The logging macros make use of GCC (and compatible) variadic macros.  While there are ifdefs for Solaris Studio using C99 variadic macros, they don't compile and seem to be suffering from bit rot.

There are a couple ways to address this:
- rebase and fix the ```ifdef __SUNPRO_C``` portion which would introduce no changes for the GCC build but would have more longterm maintenance overhead
- replace the GCC extensions and ifdefs with C99 compliant ones which would not be as readable and require a few hacks to prevent trailing commas in the case of zero arguments.  This would remove the code maintenance burden and make the macros more portable.

I'll be happy to submit a pull request for either approach.

**Comment by miconda** [comment]
I would go for first option if it is the fastest at runtime by avoiding workarounds. I don't expect to be a very dynamic part in the future, so we ca live with two dedicated parts of code there.
