### ISSUE TITLE
Retransmission for uac_auth generated INVITEs do not include CSeq mangling (track_cseq_updates)

### ISSUE THREAD

**Issue by cruzccl** [kamailio/kamailio#679]
I am having issues using uac_auth function and dialog module track_cseq_update option. The issue is related to CSeq mangling done by dialog module to keep synced CSeq in both parties involved. 

It works fine when 1xx response is received for generated INVITE before retr_timer1 expires but, if not, the generated retransmission has the same CSeq as the original INVITE (the one without Authorization headers), instead of increasing CSeq by one again:

- INVITE sent by UAC (CSeq 100).
- 407 from UAS.
- INVITE generated by uac_auth (CSeq 101).
- (... no answer ...)
- Retransmission INVITE with Authorization header but with CSeq 100.

This is the minimal configuration file needed to test this behaviour:

```
loadmodule    "tm.so"
loadmodule    "pv.so"
loadmodule    "sl.so"
loadmodule    "avpops.so"
loadmodule    "dialog.so"
loadmodule    "uac.so"
loadmodule    "rr.so"

modparam("dialog", "dlg_flag", 1)
modparam("dialog", "track_cseq_updates", 1)
modparam("uac", "auth_realm_avp", "$avp(realm)")
modparam("uac", "auth_username_avp", "$avp(provideruser)")
modparam("uac", "auth_password_avp", "$avp(secret)")
modparam("tm", "retr_timer1", 100)

request_route {
    dlg_manage();
    $ru = "sip:test@**SIPSERVER**";
    t_on_failure("MANAGE_FAILURE");
    t_relay();
    exit;
}

failure_route[MANAGE_FAILURE] {
    if (t_is_canceled()) {
        exit;
    }

    if (t_check_status("(401)|(407)")) {
        $avp(realm) = '';
        $avp(provideruser) = 'foo';
        $avp(secret) = 'bar';

        uac_auth();
    }

    t_on_failure("MANAGE_FAILURE");
    t_relay();
    exit;}
```

This is the Kamailio version I am using on a amd64 machine (Debian 7):

```
version: kamailio 4.4.1 (x86_64/linux) 99e1c3
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 99e1c3 
compiled on 13:37:42 Jun 20 2016 with gcc 4.7.2
```

Is something wrong on my kamailio.cfg? Do you need any extra information?

Best regards.

**Comment by miconda** [comment]
Can you send me a pcap? It makes it easier to troubleshoot while not at the desktop (without an proper environment to reproduce).

**Comment by cruzccl** [comment]
Hi Daniel,

I sent you the pcap to your gmail address. Don't hesitate to ask me if you need anything else.

Thank you.

**Comment by miconda** [comment]
Thanks for pointing out -- the inbox on gmail gets very little attention. I will get back to this one in the next days.

**Comment by miconda** [comment]
Can you test with git master branch? I pushed a group of commits that should fix this issue -- if all ok, then I will backport to 4.4.

**Comment by cruzccl** [comment]
Hi Daniel,

I have tried master branch and the CSeq mangling mechanism does not adapt the CSeq now: INVITE with authorization header and its retransmissions have the same CSeq as the original INVITE.

The version I tried is:

```
version: kamailio 5.0.0-dev5 (x86_64/linux) fb3699
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: fb3699 
compiled on 11:47:40 Jul 11 2016 with gcc 4.7.2
```

Do I need to enable _track_cseq_updates_ setting in a different way now?

Thank you.

**Comment by miconda** [comment]
Can you send again a pcap with sip signaling for such case?

**Comment by cruzccl** [comment]
I have just sent the pcap to your gmail account.

Ask me if you need anything else :)

Regards.

**Comment by miconda** [comment]
Can you give it another try to the master branch? Pushed two more commits for this issue.

**Comment by cruzccl** [comment]
I have just sent you the pcap with the last pcap (using master branch, commit 5f5795a) to your gmail address.

I think the signalling is equal to previous tests: no SDP in invites with auth (and retransmissions) and no CSeq mangling.

Thank you.

**Comment by miconda** [comment]
OK, I setup a test environment to move this on. I fixed some of the bits with the last commit to master. But now it's incrementing cseq for each retransmission, which should be fine, but not nice. I don't have time to deal with it right now, but maybe this evening. Should not be a big fix to do.

**Comment by cruzccl** [comment]
I see what you mean, each retransmission has an increasing unique CSeq now.

But, shouldn't these INVITEs keep the SDP of the original INVITE?

Thank you for your time :)

**Comment by miconda** [comment]
Earlier today I pushed more commits to master to handle the increment issue. Can you try with it? in my tests, the sdp went out.

**Comment by cruzccl** [comment]
Hi Daniel,

Everything is fine now! The INVITE created by uac_auth increases CSeq by one and mantains the original SDP. Retransmissions of this INVITE are exact copies of this INVITE, so I think everything is perfect now :)

Thank you!

**Comment by miconda** [comment]
Thanks for testing, will backport if all smooth.

**Comment by imantaba** [comment]
thank u dan

> Earlier today I pushed more commits to master to handle the increment issue. Can you try with it? in my tests, the sdp went out.

Thank you Daniel it helped me too..
