### ISSUE TITLE
log_custom module doesn't redirect all log messages

### ISSUE THREAD

**Issue by logslie** [kamailio/kamailio#680]
Hi,

I'm using log_custom module and I have it configured with **log_stderror=no** and **log_engine_type="udp"**. As far as I understand this module should send all log messages using udp, right?

For instance:

```
request_route {
	
	log_udp("R-URI is $ru\n");
	xlog("L_INFO", "This is a test message\n");

	...
} 

```
The UDP listener should receive:

```
R-URI is sip:test201@10.22.22.201:5060
This is a test message
```

But in my case the UDP listener only receives:

```
R-URI is sip:test201@10.22.22.201:5060
```

This is, the messages sent using the method exported by the module (i.e **log_udp**). 
Am I doing something wrong?

Thanks,

Laura

**Comment by miconda** [comment]
Do you see the test message in syslog?

What is the value for **debug** global parameter? It has to be at least 2 to get the L_INFO level printed.

**Comment by logslie** [comment]
Yes, the debug parameter is 2 and I can see the message in syslog but the message is not sent to the UDP listener.

**Comment by miconda** [comment]
Can you test with git master branch setting debug=3 in kamailio.cfg? The make all log messages printed at startup available somewhere for read (e.g., patebin).

**Comment by logslie** [comment]
I found the error, it wasn't a module error. I run the kamailio using supervisor and the command used to start kamailio had the parameter -E which uses the staderr instead of syslog.

I'm sorry.

Thanks

**Comment by miconda** [comment]
No worries, good that it was sorted out!
