### ISSUE TITLE
Concurrency fprintf

### ISSUE THREAD

**Issue by logslie** [kamailio/kamailio#681]
Hi,

I'm developing a new module that writes logs in a log file using the function fprintf. 
My question is, do I have to implement any lock to write safely in the file? As far as I know fprintf is thread-safe, but even though it, I don't know if it is necessary or not.

Thanks,

Laura

**Comment by miconda** [comment]
You need to synchronise when writing to same file from many processes. Among options:

  * 1) lock a mutex; open file; append message; close file; unlock mutex
  * 2) each process writes to pipe and a dedicated process reads from the pipe and writes to the file

**Comment by miconda** [comment]
I am closing this issue -- we use the tracker on github for bugs or new feature requests. If you want to discuss more on this topic, use the mailing lists (e.g., sr-users at lists dot sip-router dot org).

**Comment by logslie** [comment]
Thank you Daniel.

Laura García Pérez
www.logslie.com <http://www.logslie.com/>
+34680923532
+12602069698
