### ISSUE TITLE
4.4.x TOPOS code/documentation mismatch for mask_callid

### ISSUE THREAD

**Issue by Doranku** [kamailio/kamailio#687]
[Documentation for TOPOS ](http://kamailio.org/docs/modules/4.4.x/modules/topos.html#topos.p.mask_callid)module mentions  the option to mash the Call-ID header.

This doesn't work and the reason is simple since it isn't implemented in modules/topos/tps_msg.c:
`
                       // ts_mask_callid(&msg);
`

ts_mask_callid doesn't exists, so for the time being removing the mask_callid from documentation might be a good idea.

**Comment by miconda** [comment]
Indeed, it is not implemented yet -- it was left there because the module aims to be in pair with topoh. I will add relevant note in docs about it.
