### ISSUE TITLE
Modify VIA header in replied message

### ISSUE THREAD

**Issue by baohq110** [kamailio/kamailio#690]
Hi all,

There is no any problem As title, i just want to ask how to modify VIA header with kamailio. 
example. REGISTER ==>  Kamailio ===> reply 200 OK. So in 200 OK message, i will add some additional parameters.
Thank in advance.

Brs/Bao

**Comment by miconda** [comment]
The tracker is used for reporting bugs or tracking the requests for new features.

Discussions about how to use kamailio and things that can be done in kamailio.cfg have to be done via mailing list sr-users@lists.sip-router.org:

  * http://lists.sip-router.org/cgi-bin/mailman/listinfo/sr-users

Send an email there describing what exactly you want to do -- what to add, where (top via, all vias...), etc, ...

The item here will be closed.
