### ISSUE TITLE
sipcapture/siptrace HEPv2 timestamp is endian specific

### ISSUE THREAD

**Issue by sjthomason** [kamailio/kamailio#695]
I guess this is known since HEPv3 uses network byte order but I wanted to create this placeholder to try to address HEPv2 in a minimally invasive way.

I first discovered this when setting up a capture server on a big endian machine with agents that are little endian.  Is there a published standard for HEPv2 or would it be safe to assume that the timestamps need to be little endian?  If so, maybe a quick fix is to add some macros to sipcapture and siptrace modules that are basically the reverse of ntohl.  I.e. they would only reverse the byte order on big endian machines.

**Comment by adubovikov** [comment]
hi, sure you can. Anyway we will apply a patch for HEPv3 to the siptrace module this month and we strongly recommend use HEPv3 in the future

**Comment by sjthomason** [comment]
Great!  I'm looking forward to it!  I'll work up a patch to byte swap on big endian machines.  From a style/namespace perspective how about:
```
#if defined __IS_BIG_ENDIAN
#define to_le(x) bswap32(x)
#else
#define to_le(x) (x)
#endif
```

**Comment by sjthomason** [comment]
Just an update here... PR #698 fixes this but is a slight behavior change on big endian hardware.
