### ISSUE TITLE
To make work user-agent for http_client module you need to load utils module too

### ISSUE THREAD

**Issue by os11k** [kamailio/kamailio#705]
Hi,

I found strange bug. When I load utils and http_client modules then user-agent are sent in http request using http_client module(http_connect funcion), but if I do not load utils module, then user-agent is not sent anymore.

Thank you!

**Comment by oej** [comment]
That sounds very strange, since there are no shared code at all.  If correct, it's a sign of issues using curl from many modules, something I want to avoid with the API to the http_client module. Can you produce a test configuration showing this to make it easier to track it down?

**Comment by os11k** [comment]
Sure, I will try to create simple configuration today and I will attach it here.

**Comment by os11k** [comment]
Actually http_connect do not add user-agent at all(in case if utils module loaded or not), but http_client_query adds user-agent in all cases. I'm not sure if this works as intended. Nevertheless you can find in attachment configuration how to reproduce this issue. I would like to emphasize one more time that utils do not affect http_connect anyhow.
[kamailio.txt](https://github.com/kamailio/kamailio/files/359070/kamailio.txt)

**Comment by miconda** [comment]
If you use master branch, note that I pushed the code for setting the user agent in the query function, to make it easier for upgrades from utils module. But should be no relation with utils module parameters.

**Comment by os11k** [comment]
Hi,

Sorry for false alarm. Utils module do not impact http_client, just rechecked.

http_client_query - adds user-agent header
http_connect - does NOT add user-agent header

**Comment by oej** [comment]
Ok. Thanks for reporting back.
