### ISSUE TITLE
pv needed to get access to X509v3 Subject Alternative Names of peer's SSL certificate

### ISSUE THREAD

**Issue by juha-h** [kamailio/kamailio#707]
A sip proxy may serve many domains listed in its SSL certificate X509v3 Subject Alternative Name field.   In order to find out if a peer sip proxy is serving a particular domain, access would be needed in config file to this list of domains.

**Comment by henningw** [comment]
Has this been implemented yet or is it still open?

**Comment by oej** [comment]
We have an event route in the TLS module where we can inspect the peers certificate.
$tls_peer_san_uri will get something - but I wonder how to get the list.
I don't find a select for SAN's but I may be wrong.

**Comment by miconda** [comment]
Closing old feature request. If still not implemented, the best is to make a PR.
