### ISSUE TITLE
SIP to SIP call not working in kamailio 

### ISSUE THREAD

**Issue by saigauravmehra91** [kamailio/kamailio#712]
i have just install fresh kamailio 4.3.4 , after create two extention 100 and 200 , both the extention Registered successfully but unable to make call .. when i dial from 100 to 200 it seem like call going to 200 but the other side no notification ...

plz help..

**Comment by miconda** [comment]
This is not an issue in Kamailio software, but a matter of kamailio configuration. The tracker here is for bugs in the code and requests for new features.

For sorting out troubles with configuration, ask your questions to users mailing list at sr-users@lists.sip-router.org -- you have to join it at:

  * http://lists.sip-router.org/cgi-bin/mailman/listinfo/sr-users

**Comment by saigauravmehra91** [comment]
Ok thanks
