### ISSUE TITLE
Kamailio can not start with TLS

### ISSUE THREAD

**Issue by ovoshlook** [kamailio/kamailio#714]
Hi installed yesterday and today on 2 different servers kamialio 4.4 

> kamailio -v
> version: kamailio 4.4.2 (x86_64/linux) 12777a
> flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
> ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
> poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
> id: 12777a
> compiled on 06:45:41 Jul 17 2016 with gcc 5.4.0

and today

> kamailio -v
> version: kamailio 4.4.2 (x86_64/linux) 12777a
> flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
> ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
> poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
> id: 12777a
> compiled on 14:34:16 Jul 18 2016 with gcc 5.4.0

start with TLS gives this error on both. Debug log gives nothing about tls. Just these strings.

ERROR: tls [tls_init.c:490]: tls_pre_init(): Unable to set the memory allocation functions
ERROR: <core> [sr_module.c:607]: load_module(): /usr/local/lib64/kamailio/modules/tls.so: mod_register failed

Saw you made some changes on TLS module. Suppose it is because of it.

Will give access to the server if it needs

**Comment by miconda** [comment]
Hmm, similar report was on sr-users mailing list. Can you install kamailio 4.4.1 from tarball or git tag (4.4.2) and try with it? Just to see if there was a regression introduced before 4.4.2.

I did some small patches trying to detect better libssl intialization while investigation a conflict with mongo-c-driver, let's see if those have unexpected side effects.

**Comment by ovoshlook** [comment]
Yes. Will do it in 2-3 hours. Let you know here.

**Comment by ovoshlook** [comment]
Same in kamailio 4.4.1

> 4.4.1 (x86_64/linux) 90be8b
> flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
> ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
> poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
> id: 90be8b
> compiled on 15:13:03 Jul 18 2016 with gcc 5.4.0

Will try now 4.4.0 because on this version one of my projects works well

**Comment by ovoshlook** [comment]
hmmm... at 4.4.0 same.
I suppose it conflicts with something else at the ubuntu 16.04 maybe?

there is part of output 4.4.1 DEBUG=4

 0(28129) DEBUG: <core> [cfg.y:1592]: yyparse(): loading module tls.so
 0(28129) DEBUG: <core> [sr_module.c:575]: load_module(): trying to load </usr/local/lib64/kamailio/modules/tls.so>
 0(28129) DEBUG: <core> [mem/f_malloc.c:323]: fm_malloc_init(): fm_malloc_init: F_OPTIMIZE=16384, /ROUNDTO=2048
 0(28129) DEBUG: <core> [mem/f_malloc.c:325]: fm_malloc_init(): fm_malloc_init: F_HASH_SIZE=2099, fm_block size=33912
 0(28129) DEBUG: <core> [mem/f_malloc.c:326]: fm_malloc_init(): fm_malloc_init(0x7f02653c5000, 67108864), start=0x7f02653c5000
 0(28129) ERROR: tls [tls_init.c:490]: tls_pre_init(): Unable to set the memory allocation functions
 0(28129) ERROR: <core> [sr_module.c:607]: load_module(): /usr/local/lib64/kamailio/modules/tls.so: mod_register failed

**Comment by ovoshlook** [comment]
Found that 4.4.0 works good on ubuntu 15.10
Will trinstall OS now and will try once again

**Comment by miconda** [comment]
I checked the commit log for tls between 4.4.0 and 4.4.2 and there were no relevant changes. Not even those I added for debugging, they are now only in master. I looked at libssl source code and there is a static variable which can prevent setting the memory manager functions if some crypto stuff was initialized -- but that should not be done by kamailio.

**Comment by ovoshlook** [comment]
Yes. I suppose that it is a bugg of Ubuntu 16.04
I will let you know in near time.
Downloading 15.10 for now.

**Comment by ovoshlook** [comment]
Yes. On Ubuntu 15.10 works fine

**Comment by miconda** [comment]
An option mentioned on sr-users mailing list is to downgrade libssl-dev version to 1.0.2d
