### ISSUE TITLE
4.4.x TOPOS - bad sip message or missing Contact hdr on OPTIONS messages

### ISSUE THREAD

**Issue by darencrew** [kamailio/kamailio#715]
topos is complaining about missing contact, but on an OPTIONS message, contact is not mandatory

23(12470) ERROR: topos [tps_storage.c:305]: tps_storage_link_msg(): bad sip message or missing Contact hdr

So, should "OPTIONS" be added to the exceptions in the code or is there a way to stop storing OPTIONS messages informations?

**Comment by miconda** [comment]
Can you try with the patch referenced above and see if works fine for OPTIONS? If all ok, then I will backport.

**Comment by darencrew** [comment]
The patch has worked.
Thank you!

**Comment by darencrew** [comment]
I reopen this issue as the same happens on BYE requests.
BYE requests (according to my understanding of RFC - page 161) doesn't require Contact header.

Do you mind adding METHOD_BYE in the condition? (it seems that Contact is only mandatory on INVITEs).

**Comment by miconda** [comment]
Pushed a patch to check only for INVITE. If the issue is still there, reopen.
