### ISSUE TITLE
$T_reply_last returns current reply status instead of previous

### ISSUE THREAD

**Issue by gaaf** [kamailio/kamailio#735]
The PV _$T_reply_last_ is supposed to return the _previous_ reply status. Since commit b7c588dff06 to fix #315 this PV returns the _current_ reply status.

**Comment by miconda** [comment]
Thanks for reporting, I will analyze as I get a chance.

**Comment by miconda** [comment]
Looking at the code, it seems that the last reply is the one returned now -- the name is a bit misleading if it expects the previous reply. I think it needs a dedicated field in the structure if one needs to get access to previous reply code. I would also suggest to add an alias like $T(prev_reply) for more suggestive name and obsolete $T_reply_last over the time, or let the one like it is now and add $T(prev_reply) for prev reply code.

**Comment by miconda** [comment]
Closing as being too old and no interest for long time. If still wanted, just make a pull request.
