### ISSUE TITLE
Problem when using http_async_client with a POST

### ISSUE THREAD

**Issue by AlainDubois78** [kamailio/kamailio#744]
On a Linux 64 bits Ubuntu, I'm trying to use the http_async_client to send a POST message but whatever I set, it always suspends the current route contrary to the content of the documentation.
When I look at the C code it seems to be done on purpose as the return for the POST is different than the return from the get:
static int w_http_async_get(sip_msg_t *msg, char *query, char* rt)
{
...
	return async_send_query(msg, &sdata, NULL, act);

}

static int w_http_async_post(sip_msg_t *msg, char *query, char* post, char* rt)
{
...
	if(async_send_query(msg, &sdata, &post_data, act)<0)
		return -1;

	/* force exit in config */
	return 0;
}

I was expecting the post function to work as the get one and to finish with something like:
return async_send_query(msg, &sdata, &post_data, act);

Based on the document it looks like a bug but the comment bothers me and let me think it might be done on purpose (which one?)

**Comment by kamailio-sync** [comment]
Definitely a bug, thanks for reporting!
I've just pushed a fix on master. If you could try and give feedback I'll
backport then.

**Comment by AlainDubois78** [comment]
I actually already tested as I made the proposed modification on my own PC.
I works just as expected
Thanks for the quick feedback

**Comment by grumvalski** [comment]
Ok, thank you, going to backport.
