### ISSUE TITLE
Permissions module RPC array issue

### ISSUE THREAD

**Issue by kelchy** [kamailio/kamailio#747]
using 4.4.2
on kamctl kamcmd permissions.addressDump

{
	table: 80
	group: 5
	item: {
		ip: 6x.x4.1x7.10
		port: 50060
		tag: 0
	}
	table: 120
	group: 8
	item: {
		ip: 1x8.1x4.1x6.19
		port: 50060
		tag: 0
	}
	table: 122
	group: 7
	item: {
		ip: 1x8.1x4.1x6.17
		port: 50060
		tag: 0
	}
	table: 122
	group: 6
	item: {
		ip: 1x8.1x4.1x6.17
		port: 50060
		tag: 0
	}
}

on jsonrpc-s

{ jsonrpc: '2.0',
  result: 
   { table: 122,
     group: 6,
     item: { ip: '1x8.1x4.1x6.17', port: 50060, tag: '0' } } }

**Comment by kelchy** [comment]
fixed. pull request

https://github.com/kamailio/kamailio/pull/751

**Comment by miconda** [comment]
Fixed by 20a4f7e029262a94c5c4bcdc68a90e404b506c98
