### ISSUE TITLE
move kamailio/utils/misc/vim/ to a git submodule

### ISSUE THREAD

**Issue by mMontu** [kamailio/kamailio#763]
The Vim plugin is very nice, and its use isn't restricted to machines where Kamailio is installed, as the config file can be edited via network (e.g.: using netrw plugin).

Currently the most common approach to retrieve a Vim plugin is to clone its GitHub repo and use some plugin manager, such as [pathogen](https://github.com/tpope/vim-pathogen).

But it clearly doesn't make sense to retrieve the complete Kamailio repo only to use the vim plugin; this probably caused the creation of [duplicates](https://github.com/eloycoto/vim-ser). I actually find that duplicate first, and then noticed on its README that there is an official (and newer) version here.

Do you find acceptable to move it to a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by eloycoto** [comment]
Totally agree in create different git repos for this.

**Comment by miconda** [comment]
I am fine with relocating it, even without keeping it as submodule in kamailio tree, because they are not really related. I can create kamailio.vim repository inside kamailio github organization and let people contribute there. Is it ok?

**Comment by eloycoto** [comment]
Yep, sounds perfect for me 👍

**Comment by mMontu** [comment]
Yes, perfect! Thanks!

It would also be nice to add a reference at [vim.org](http://www.vim.org/scripts/script_search_results.php?keywords=&script_type=&order_by=rating&direction=descending&search=search), because it is where most people look for Vim plugins
 (I searched there first for this plugin; I only found it through [awesome](http://vimawesome.com/?q=kamailio)).

**Comment by mMontu** [comment]
Only a minor suggestion:

>  I can create kamailio.vim

I noticed that lately some authors started creating vim plugins as `vim-<name>`, so maybe it should be vim-kamailio?

**Comment by miconda** [comment]
I have seen bot abc.vim and vim-abc. I am fine with any. So if anyone one else has a preference for one or the other, comment here.

The idea is to create the project inside https://github.com/kamailio/ and there we can grant access to contributors.

Once that is done, anyone is welcome to add reference to it on vim.org or other sites.

**Comment by miconda** [comment]
Btw, I guess we can integrate there also the autocomplete module

   * https://github.com/miconda/vim-extensions/tree/master/plugin/kamailio

Not only syntax highlighting:

**Comment by mMontu** [comment]
I think it is a good idea to also split the autocomplete module, but in a separated repo/plugin. Because although they are both related to kamailio.cfg they are intended for different tasks/purposes.

I have installed the syntax plugin but not the autocomplete, as there are several general purpose autocomplete plugins, and installing more than one is troublesome. 

As I'm already using Ultisnips I intended to check the snippets defined there later and then translate then for Ultisnips/Snipmate format when I have some spare time.

**Comment by miconda** [comment]
So then there should be two projects, named like:

  * vim-kamailio-syntax
  * vim-kamailio-autocomplete

Does anyone know if a subfolder of a github project can be moved to a standalone project and keep the commit history? If not, we can make fresh imports of latest versions.

**Comment by camilleoudot** [comment]
looks like something we could use here:
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by miconda** [comment]
Thanks @camilleoudot! It worked, new repositories are at:

  * https://github.com/kamailio/vim-kamailio-autocomplete
  * https://github.com/kamailio/vim-kamailio-syntax

If anyone wants to get write access to repos, let me know (you can add comments here, even I will close the issue).

**Comment by mMontu** [comment]
Thanks! I'll place some pull requests on those repositories for some small enhancements.
