### ISSUE TITLE
Unable to turn on TLS

### ISSUE THREAD

**Issue by lgg** [kamailio/kamailio#770]
os: Linux mydomain.com 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

kamctl version: 4.2.0

installation method:
`apt-get install kamailio kamailio-mysql-modules kamailio-tls-modules`

MySQL working excellent.
But when i try to add: `#!define WITH_TLS` to `/etc/kamailio/kamailio.cfg` i always get error:
```
Sep 06 23:06:28 mydomain.com kamailio[32437]: ERROR: <core> [sr_module.c:602]: load_module(): /usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so: mod_register failed
Sep 06 23:06:28 mydomain.com kamailio[32437]: : <core> [cfg.y:3432]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 279, column 12-19: failed to l
Sep 06 23:06:28 mydomain.com kamailio[32437]: ERROR: <core> [modparam.c:150]: set_mod_param_regex(): No module matching <tls> found
Sep 06 23:06:28 mydomain.com kamailio[32437]: : <core> [cfg.y:3435]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 438, column 50: Can't set modu
Sep 06 23:06:28 mydomain.com kamailio[32437]: ERROR: bad config file (2 errors)
Sep 06 23:06:28 mydomain.com kamailio[32437]: loading modules under config path: /usr/lib/x86_64-linux-gnu/kamailio/modules/
Sep 06 23:06:28 mydomain.com systemd[1]: kamailio.service: Control process exited, code=exited status=255
Sep 06 23:06:28 mydomain.com systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 06 23:06:28 mydomain.com systemd[1]: kamailio.service: Unit entered failed state.
Sep 06 23:06:28 mydomain.com systemd[1]: kamailio.service: Failed with result 'exit-code'.
```

in my kamailio.cfg enable_tls is set to yes
```
#!ifdef WITH_TLS
enable_tls=yes
```

line 279:
```
#!ifdef WITH_TLS
loadmodule "tls.so"
#!endif
```

and line 438:

```
#!ifdef WITH_TLS
# ----- tls params -----
modparam("tls", "config", "/etc/kamailio/tls.cfg")
#!endif
```

```
root@mydomain:/usr/lib/x86_64-linux-gnu/kamailio/modules# ll /usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so
-rw-r--r-- 1 root root 433872 Apr  5 16:39 /usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so
```

What i'm doing wrong? What i've missed?

**Comment by miconda** [comment]
If you use latest Ubuntu, there seems to be an issue in the libssl -- see #714

**Comment by linuxmaniac** [comment]
FTR fix for Debian jessie on the way https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836910

**Comment by miconda** [comment]
@linuxmaniac - it is a different issue, then one I was referring is not about the version comparison, which seems the one you point, but the fact that libssl in ubuntu 16.04 seems to initialize the memory manager for ssl functions before kamailio does it -- more or less, it doesn't allow setting memory manager anymore.

**Comment by linuxmaniac** [comment]
@miconda my bad. Thanks for clarifying

**Comment by lgg** [comment]
@miconda @linuxmaniac so, does it mean that i can't use TLS until developers of libssl will fix it in ubuntu 16.04?

**Comment by miconda** [comment]
You can use other version of libssl, I think there are options to downgrade it, as I understood from others reporting about same issue. My plan is to try to investigate deeper, but didn't get the time to install ubuntu 16.04 and libssl from sources in order to debug properly.

**Comment by lgg** [comment]
@miconda i just tried with openssl-1.1.0, built from source and got this:

```
Sep 13 05:14:49 myserver kamailio[29121]: DEBUG: <core> [route_struct.c:129]: mk_action(): ACTION_#24 #1/2: 3(3)/ (nil)
Sep 13 05:14:49 myserver kamailio[29121]: DEBUG: <core> [sr_module.c:688]: find_mod_export_record(): find_export_record: found <is_method> in module textops [/usr/lib/x86_64-linux-gnu/kamailio/modules/textops.so]
Sep 13 05:14:49 myserver kamailio[29121]: DEBUG: <core> [pvapi.c:320]: pv_cache_lookup(): pvar [$rU] found in cache
Sep 13 05:14:49 myserver kamailio[29121]: DEBUG: <core> [pvapi.c:320]: pv_cache_lookup(): pvar [$null] found in cache
Sep 13 05:14:49 myserver kamailio[29121]: ERROR: bad config file (2 errors)
Sep 13 05:14:49 myserver kamailio[29121]: loading modules under config path: /usr/lib/x86_64-linux-gnu/kamailio/modules/
Sep 13 05:14:49 myserver systemd[1]: kamailio.service: Control process exited, code=exited status=255
Sep 13 05:14:49 myserver systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 13 05:14:49 myserver systemd[1]: kamailio.service: Unit entered failed state.
Sep 13 05:14:49 myserver systemd[1]: kamailio.service: Failed with result 'exit-code'.

```

**Comment by miconda** [comment]
The issue is known by Ubuntu and an updated package seems under way, see:

  * https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1594748

In the discussion of the bug, there is a link to a ppa repository with libssl packages already built with the fix.
