### ISSUE TITLE
UAC reg_refresh for auth_username

### ISSUE THREAD

**Issue by danbogos** [kamailio/kamailio#771]
This is about the new feature we have discussed over mailing list.

Right now only the auth_password is refreshed and the only way to get the username changed is using reload which is a pain if you have 1000+ users (takes long time).

Ta
DanB

**Comment by miconda** [comment]
A lucky day -- but you need master branch -- see commit 5d83785e8c9ce939106aba579ec4773c50bed8c2 .

**Comment by danbogos** [comment]
Really lucky, many thanks Daniel for so fast implementation :)!

DanB

**Comment by miconda** [comment]
Forwarding the thanks to Alex (@gaaf)!

**Comment by danbogos** [comment]
Did not know, thanks @gaaf :)!

DanB
