### ISSUE TITLE
make syslog tag configurable

### ISSUE THREAD

**Issue by dpocock** [kamailio/kamailio#780]
In daemonize.c, the ```openlog``` statement uses the name of the binary to set the syslog tag name.

For people running multiple Kamailio instances on the same host, it is desirable to use different tag names for each.  E.g. if somebody is running an instance for HOMER, they might want to use a tag like ```homer-api``` for that instance.

This probably needs a new cfg parameter with a name like ```log_tag```

**Comment by miconda** [comment]
I think what you are looking for is the exiting **log_name** parameter:

  * https://www.kamailio.org/wiki/cookbooks/4.4.x/core#log_name

**Comment by dpocock** [comment]
that looks like the same thing, could you add a note in the documentation that this sets the syslog tag?  I searched for the word "tag" and didn't see that at all.

The Syslog RFC refers to it as tag too, although it becomes messy with RFC 5424
https://tools.ietf.org/html/rfc5424#page-35

**Comment by miconda** [comment]
Added more info to the docs.
