### ISSUE TITLE
sca: implement db_mode only

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#781]
Sipwise hat ON:

We have more than one server and we need to keep things in db in order to share sca subscription/appearance between servers

**Comment by linuxmaniac** [comment]
Any thoughts @TheGrandWazoo ?

**Comment by TheGrandWazoo** [comment]
I assume you mean more then one kamailio server in a load-balancing type environment?

If so, that was on my radar for future enhancements but I am glad someone is finally looking at this module and making some improvements. Thank you so much!!!! This module is one that I use at many customers and has been the bane of my existence with the hold seizes.

**Comment by linuxmaniac** [comment]
@miconda I'm thinking if ``sca`` can be redesigned and integrate the subscription part of it as a module like ``presence_sca`` using ``presence`` infrastructure.

The thing is that ``presence`` has support for process only the body not for the headers and ``sca`` is adding ``Call-Info`` header to a bodyless ``NOTIFY`` reply.

Is it worth the trouble to implement that in ``presence`` or should I just keep hacking into ``sca`` directly?
