### ISSUE TITLE
Missing files in IMS module examples.

### ISSUE THREAD

**Issue by OwaisAhmadJan** [kamailio/kamailio#785]
**Below files are missing from P-CSCF examples:**
include_file "route/register.cfg"
include_file "route/rtp.cfg"
include_file "route/mo.cfg"
include_file "route/mt.cfg"

Also, there is no specific sql database schema for P-CSCF

**Comment by ngvoice** [comment]
Hi,

Config:
just committed the missing files.

SQL-Schema:
Please use the Schema creation files in "utils/kamctl/mysql/".

Thanks,
Carsten
