### ISSUE TITLE
CSeqs following the auth transaction are not mangled properly (track_cseq_updates)

### ISSUE THREAD

**Issue by cruzccl** [kamailio/kamailio#787]
Hi Daniel,

This issue might be related to #679 and #752. 

On a "A endpoint" --- Kamailio ---- "B endpoint" scenario with track_cseq_updates enabled, I am having this issue:

- **A** sends INVITE with CSeq 101, **Kamailio** forwards it and gets 407 from **B**.

- **Kamailio** makes the SIP Auth with CSeq 102 using _uac_auth_.

- **A** sends a within-dialog transaction with Cseq 102.

- **Kamailio** does not mangle the Cseq (although it adds P-K-CSeq-Refresh: 103 header).

- **B** sends 200 OK with Cseq 102.

- **Kamailio** mangles it and forwards it to **A** with Cseq 101 (that doesn't match the expected CSeq).

I have tested both in master branch (commit d150d5a) and 4.4 branch (commit 5a21952).

I send you a pcap to your gmail account so that you can see what I mean :)

Thank you and tell me please if you need more testing!

**Comment by cruzccl** [comment]
Hi,

Sorry for that, this is the "kamailio -v" output:

```
# kamailio -v
version: kamailio 5.0.0-dev6 (x86_64/linux) d150d5
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: d150d5 
compiled on 16:09:08 Sep 19 2016 with gcc 4.7.2
```

Regards,

**Comment by miconda** [comment]
Can you grab all the log messages printed by kamailio with debug=3 when processing the request within dialog that doesn't get the cseq updated? Send them to me.

**Comment by cruzccl** [comment]
Hi,

Here they are:

- All the logs:
https://gist.github.com/cruzccl/c3c0aeede9304caf17708fd84cdcd754

- Just the failing request:
https://gist.github.com/cruzccl/ebcb593079a88c9cb3e9c9e3c5489162

Regards,

**Comment by miconda** [comment]
Can you try with latest master or 4.4 branch and see if works fine? I pushed few patches recently.

**Comment by cruzccl** [comment]
Hi Daniel,

Everything seems to work fine after 64a8927 :)

Tested with:

```
version: kamailio 4.4.3 (x86_64/linux) 64a892
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 64a892 
compiled on 18:07:03 Sep 29 2016 with gcc 4.7.2
```

Thank you and regards,

**Comment by miconda** [comment]
Thanks for testing and reporting back.
