### ISSUE TITLE
inserting contact into database failed 

### ISSUE THREAD

**Issue by sergey19** [kamailio/kamailio#791]
the registration error insert into location. 
version: kamailio 4.4.2 (x86_64/linux) 892ad6 

define(`DBASTURL', `"unixodbc://kamailioro:Barsa2015!@10.1.21.115/MySQL-asterisk"')

loadmodule "auth_db.so"
modparam("auth_db", "calculate_ha1", 1) 
modparam("auth_db", "password_column", "password")
modparam("auth_db", "db_url", DBASTURL) # CUSTOMIZE ME
modparam("auth_db", "load_credentials", "")
modparam("auth_db", "user_column", "name")
modparam("auth_db", "version_table", 0)

Sep 20 18:34:51 kamailio-test /usr/local/sbin/kamailio[30180]: ERROR: db_unixodbc [dbase.c:135]: db_unixodbc_submit_query(): rv=-1. Query= insert into location (username,contact,expires,q,callid,cseq,flags,cflags,user_agent,socket,methods,last_modified,ruid,reg_id,server_id,connection_id,keepalive,partition ) values ('9997','sip:9997@10.1.21.21:34577;rinstance=294f7936f4bd34b5;transport=UDP','2016-09-20 19:29:05',-1.000000 ,'OUZlrpcyEzb3VpwOJt-6Dw..',2,0,0,'Z 3.9.32144 r32121','udp:10.255.128.20:5060',5087,'2016-09-20 18:29:05','uloc-57e155b3-75d8-1',0,0,-1,0,0)
Sep 20 18:34:51 kamailio-test /usr/local/sbin/kamailio[30180]: ERROR: db_unixodbc [connection.c:220]: db_unixodbc_extract_error(): unixodbc:SQLExecDirect=42000:1:1064:[MySQL][ODBC 5.2(w) Driver][mysqld-10.0.23-MariaDB-wsrep]You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'partition ) values ('9997','sip:9997@10.1.21.21:34577;rinstan
Sep 20 18:34:51 kamailio-test /usr/local/sbin/kamailio[30180]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Sep 20 18:34:51 kamailio-test /usr/local/sbin/kamailio[30180]: ERROR: usrloc [ucontact.c:684]: db_insert_ucontact(): inserting contact in db failed 9997 (uloc-57e155b3-75d8-1)
Sep 20 18:34:51 kamailio-test /usr/local/sbin/kamailio[30180]: ERROR: usrloc [urecord.c:420]: wb_timer(): inserting contact into database failed (aor: 9997)

how to fix error?

**Comment by miconda** [comment]
I guess 'partition' is a reserved word for mariadb, but db_unixodbc is not quoting the column names.

Is there any reason not to use db_mysql, afaik, it should work fine for mariadb and it does proper quotation of column names.

As for db_unixodbc, it may need a mod param to set the quotation character, because it is not the same for database servers.

**Comment by miconda** [comment]
Commit 38038b90a7a3cc05fa7b248d6e16cfcdf29d25e7 adds support in master branch for quoting table and column names to db_unixodbc.
