### ISSUE TITLE
dmq_usrloc has "location" table name hardcoded

### ISSUE THREAD

**Issue by bayan9** [kamailio/kamailio#796]
dmq_usrloc has "location" hardcoded as the table name. If usrloc module is using a different table name for save() and lookup(), dmq_usrloc fails.

One potential solution could be to have a modparam for dmq_usrloc to specify the tables to sync

**Comment by charlesrchance** [comment]
Please try with b747d469e6c9d12be5e4541c41346b73f9bc1199, which introduces a new parameter "usrloc_domain".

I will try to enhance further at a later date to allow for multiple domains.

**Comment by miconda** [comment]
Closing -- after the commit referenced in previous comment, the name can be provided as mod param.
