### ISSUE TITLE
debugger: config test report

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#8]
In testing environment It would be nice to be able to append sip headers `X-Kamailio-test` and `X-Kamailio-test-ID` as a way to identify a collection of request/responses related to a a single test.

Be able to generate tests reports via debugger RPC command using the value of `X-Kamailio-test` as key.

The content of report could be:
* SIP message received
* SIP messages sended
* flow of config execution routes ( `start`, `end`, `exit` )
* list of the variable and its value

**Comment by miconda** [comment]
I assume this is the cfgt module. If not, reopen.
