### ISSUE TITLE
introduce RUN_DIR

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#80]
In order to get rid of any occurrence of ```/tmp``` in modules, introduce a ```RUN_DIR``` make option and every module should honor it

default could be ```/var/run/$(NAME)```

Related to #48

**Comment by miconda** [comment]
I added few patch for Makefile to define RUN_DIR at compile time. The folder is also created during install. If no PREFIX is provided, then the path is /var/run/kamailio/, otherwise is $(PREFIX)/var/run/kamailio/

Now need to be propagated in the modules using /tmp hardcoded.

**Comment by linuxmaniac** [comment]
This seems to be done for 4.3
