### ISSUE TITLE
track_cseq_updates does not update Rack SIP header in PRACK.

### ISSUE THREAD

**Issue by scfcplummy** [kamailio/kamailio#801]
Hi,

When using dialog module and track_cseq_updates when needing to update CSeq for authenticated invites, if early media is present the CSeq in the Rack header is not also incremented.

Kamailio version:

version: kamailio 4.4.2 (x86_64/linux) 892ad6
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: 892ad6
compiled on 11:18:36 Sep 28 2016 with gcc 5.4.0

**Comment by miconda** [comment]
Can you attach a pcap for such case?

**Comment by scfcplummy** [comment]
Sure attached.

packet 7 is the initial INVITE, this has Cseq of 17027

then there is a 401, using dialog module this increments the Cseq as expected to 17028 on packet 12 and the call proceeds.

There is 100rel required in the 183 with SDP as expected which has RSeq: 981875949 (packet 14)

The PRACK for this 183 is sent in packet 17 with RAck: 981875949 17027 INVITE

The Cseq inthe RAck header has not incremented and remains the same as the initial INVITE before authentication.

Many thanks
[trace-rack.zip](https://github.com/kamailio/kamailio/files/500149/trace-rack.zip)

**Comment by miconda** [comment]
For the moment, an workaeound will be to remove **Supported: 100rel** header from INVITE, so the caller doesn't provide RSeq and require RAck.

Overall, it will be considered as an enhancement to add in the future.

**Comment by effeks** [comment]
+1

Having a similar problem when we're using Kamailio to take a call from carrier 1 and broadcast the call to 2 different agents via carrier 2. If the first branch get's a 486 and the second sends a 183, the 183 results in a PRACK sent by carrier 1, but Kamailio always seems to send the PRACK for the first branch (which no longer exists) to carrier 2 and that results in an error sent back from carrier 2.

As suggested, we also resolved this by removing 100rel from the "Supported"-header.
