### ISSUE TITLE
rename sercmd to kamcmd

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#81]
Finish the migration from sercmd to kamcmd inside the code too, not only the name of the binary

**Comment by kamailio-sync** [comment]
how about utils/sercmd dir; should it be renamed to utils/kamcmd?

-- juha

**Comment by oej** [comment]
I think so

**Comment by linuxmaniac** [comment]
Implemented
de1eacfec21379f9a8f8bcfbc2ce6e0e7c999c97
f9e496f1fd25eb05f571f2e95c69c6c932692e33
5b65ebb807661daf7132e084bee609aff1af49d1
7fb52e66c37d9fe22448a085db461fd8e8c28711
