### ISSUE TITLE
consistency on name of main c file for a module

### ISSUE THREAD

**Issue by linuxmaniac** [kamailio/kamailio#82]
main file should be modulename.c or modulename_mod.c

**Comment by oej** [comment]
Include file name should follow name of main file with module interface.

**Comment by oej** [comment]
A few modules that needs renaming:
- ims_charging
- ims_qos
- ims_icscf
and friends.

**Comment by oej** [comment]
Websocket main file is ws_mod.c

**Comment by linuxmaniac** [comment]
[list.txt](https://github.com/kamailio/kamailio/files/63157/list.txt)

Modules without {module}.c or {module}_mod.c
* app_python
* auth_ephemeral
* auth_radius
* cdp
* cdp_avp
* cpl-c
* db2_ldap
* db_berkeley
* db_flatstore
* db_mysql
* db_postgres
* db_text
* dialog_ng
* erlang
* ims_auth
* ims_charging
* ims_icscf
* ims_isc
* ims_qos
* ims_registrar_pcscf
* ims_registrar_scscf
* ims_usrloc_pcscf
* ims_usrloc_scscf
* janssonrpc-c
* jsonrpc-c
* mohqueue
* outbound
* registrar
* uri_db
* websocket

**Comment by linuxmaniac** [comment]
refreshed list:
- ims_auth KO
- ims_charging KO
- ims_icscf KO
- ims_isc KO
- ims_ocs KO
- ims_qos KO
- ims_registrar_pcscf KO
- ims_registrar_scscf KO
- ims_usrloc_pcscf KO
- ims_usrloc_scscf KO
- mi_fifo KO
- mi_rpc KO

**Comment by linuxmaniac** [comment]
I think we are fine now! \o/
