### ISSUE TITLE
Statistics: Average duration of DNS requests

### ISSUE THREAD

**Issue by ngvoice** [kamailio/kamailio#821]
Hi,

we do a lot of DNS requests (ENUM, Domain-Lookups, etc.).
It would be quite awesome, if Kamailio would produce a statistic on the average duration of a DNS-Query.

Thanks,
Carsten

P.S.: It would also be nice, to have similar stats on MySQL-DB-Queries. One day, if I find time....

**Comment by jchavanton** [comment]
Very valuable indeed, since this can affect the server performance. 
I just implemented stats for dispatcher ping latency and I am interested in monitoring this more closely as well.

**Comment by henningw** [comment]
Just as a note, in git master there is now functionality to log slow DNS queries, introduced in  9a69321c5cc1

**Comment by miconda** [comment]
Closing this one based on remark from @henningw -- not exactly the same, but it is an alternative for this old request.
