### ISSUE TITLE
use_domain doesn't work on alias_db

### ISSUE THREAD

**Issue by khoegh** [kamailio/kamailio#826]
After commit a63f390d45d94cbef7cf310bcdaf362a958961f4 use_domain is broken.
The value from alias_db_use_domain/use_domain is used in alias_flags_fixup which isn't called unless a flag i set.

alias_db_lookup("table") doesn't work
alias_db_lookup("table", "r") does work.
The same is true for db_alias_find()

I broke it and don't know how to fix it, sorry.

**Comment by miconda** [comment]
I pushed a commit for lookup function. Can you try and see the results?

**Comment by khoegh** [comment]
alias_db_lookup seems correct now.
I tested with and without use_domain=1 in combination with and without flags. (none, r, dr, ur)

alias_db_find is wrong when no flags are set.

**Comment by miconda** [comment]
It was only for lookup, now I pushed one for find as well. Re-open if there is any issue with the last patch.

**Comment by khoegh** [comment]
Thanks @miconda .
alias_db_find works as it should.
