### ISSUE TITLE
ds_is_from_list() in kamailio 5 (devel)

### ISSUE THREAD

**Issue by tverlaan** [kamailio/kamailio#848]
Hi,

It seems there is a regression with `ds_is_from_list()`. When used without arguments it works on kamailio 4.4, but it doesn't work on kamailio 5.0. I used the same dispatcher set and configuration for both versions. On kamailio 4.4 `ds_is_from_list()` returned `true` and on kamailio 5.0 it returned `false`. I used the build from last night by sipwise.

I haven't had time yet to figure out what changed. I'm reporting it here to see if it is known already.

-- 
Timmo

**Comment by miconda** [comment]
Can you try with latest master? I just pushed a patch that hopefully fixes it. There was a regression introduced by the new avl indexing of the dispatcher groups.

**Comment by tverlaan** [comment]
I finally found some time to test this and it seems to be solved. Thanks for the quick fix!
