### ISSUE TITLE
presentity tabla, faster update

### ISSUE THREAD

**Issue by jresende** [kamailio/kamailio#864]
I'm testing kamailio with a SIP client with presence support, when I get a connection drop from a client (i.e when the client lost the access to the Internet connection) I do not receive the change in the status to offline immediately, I just received when the timeout from the presentity database finishes. Exists a way to define this? or it is a bug? or should be a new feature?

**Comment by miconda** [comment]
Such discussions belong to sr-users mailing list, if you are not sure if a feature exists, until it's clear that needs development, when a request for new features can be opened on this tracker with the description of the new features. Having a long discussion on tracker makes it hard to track issues and digest what needs to be done.

For now look at the readme of presence module for max expires parameter or lower the publish interval on client side.

If you need more details about what's behind the presence specs regarding the notifications or want to discuss more, write to sr-users mailing list. I am closing this here to keep the tracker clean, only with bugs and requests for new features.
