### ISSUE TITLE
sending repeated CANCEL

### ISSUE THREAD

**Issue by sergey19** [kamailio/kamailio#870]
When you call, we use dlg_manage (); function to authorize the ISP with the following settings dialog module
```
loadmodule "dialog.so"
modparam ( "dialog", "enable_stats", 0)
modparam ( "dialog", "db_url", DBURL)
modparam ( "dialog", "db_mode", 1)
modparam ( "dialog", "table_name", "dialog")
modparam ( "dialog", "dlg_match_mode", 1)
modparam ( "dialog", "dlg_flag", 4)
modparam ( "dialog", "track_cseq_updates", 1)
```

When sending a request ISP CANCEL get answers to 200 and 487, but instead of ACK otpralyaem COI new CANCEL.
```
   10.1.244.235:5060            176.99.138.244:5060│
  ──────────┬─────────          ──────────┬─────────
            │                             │        
            │                             │        
            │                             │        
            │                             │        
            │        INVITE (SDP)         │       
            │ ──────────────────────────> │ 
            │      401 Unauthorized       │         
            │ <────────────────────────── │         
            │             ACK             │         
            │ ──────────────────────────> │        
            │        INVITE (SDP)         │        
            │ ──────────────────────────> │         
            │         100 Trying          │         
            │ <────────────────────────── │         
            │         180 Ringing         │         
            │ <────────────────────────── │                
            │           CANCEL            │        
            │ ──────────────────────────> │         
            │   487 Request Terminated    │         
            │ <────────────────────────── │         
            │           200 OK            │        
            │ <────────────────────────── │         
            │           CANCEL            │         
            │ ──────────────────────────> │         
            │      500 Server error       │         
            │ <────────────────────────── │         
            │   487 Request Terminated    │         
            │ <────────────────────────── │         
            │   487 Request Terminated    │         
            │ <<<──────────────────────── │         
            │   487 Request Terminated    │         
            │ <<<──────────────────────── │    
```
how to remove the second CANCEL?

**Comment by sergey19** [comment]
if version: kamailio 4.4.4 (x86_64/linux) 852c47
 
 10.1.244.235:5060            176.99.138.244:5060
──────────┬─────────          ──────────┬─────────
          │        INVITE (SDP)         │         
          │ ──────────────────────────> │        
          │      401 Unauthorized       │        
          │ <────────────────────────── │        
          │             ACK             │        
          │ ──────────────────────────> │        
          │        INVITE (SDP)         │         
          │ ──────────────────────────> │         
          │         100 Trying          │        
          │ <────────────────────────── │         
          │         180 Ringing         │        
          │ <────────────────────────── │                 
          │           CANCEL            │        
          │ ──────────────────────────> │        
          │      500 Server error       │        
          │ <────────────────────────── │

**Comment by miconda** [comment]
Can you provide the pcap with the traffic for such case as well as the log messages from syslog with debug=3 in the kamailio.cfg?

**Comment by miconda** [comment]
Any chance to get the logs?

**Comment by greggcz** [comment]
It seems I have the same issue in "CSeq issues with CANCEL after INVITE #918". The "CANCEL" is followed by "500 Server Error" from provider due to incorrect CSeq. Only happens when canceling  the call before it's answered.

**Comment by miconda** [comment]
This should be fixed in master branch. If still problems, open a new issue with details about what happens using the latest master branch.
