### ISSUE TITLE
Kamailio bridge internal and external network

### ISSUE THREAD

**Issue by zhang90501** [kamailio/kamailio#883]
My kamailio listen at internal ip (can send message to freeswitch ) and external ip (advertise ip).
How can I make it auto using internal ip add record route to message of sending to freeswitch and external ip add record route to message of sending to public client.

**Comment by miconda** [comment]
This tracker is used to report issues about kamailio source code and make proposals of new features. It is not used as a discussion forum for users of kamailio. For such topics, send your questions to sr-users@lists.sip-router.org mailing list.
