### ISSUE TITLE
sanity: Authorization other than "digest" considered invalid

### ISSUE THREAD

**Issue by camilleoudot** [kamailio/kamailio#892]
When using the **sanity** module, with the **SANITY_CHECK_DIGEST** check enabled, if a message contains an "Authorization" header with a different scheme than "digest", the message is considered as invalid, although being perfectly valid.

In your opinion, should the module be modified to not fail when the scheme is different than "digest", or should a new flag (e.g. **SANITY_CHECK_AUTHORIZATION**) be introduced, validating the digest parameters if the scheme is digest and returning success otherwise, to keep the old flag working exactly as it is now?

**Comment by miconda** [comment]
I am ok to introduce a new flag to narrow down the check for digest and return success in other cases.
