### ISSUE TITLE
kamailio does not register new trunks

### ISSUE THREAD

**Issue by SumitRuhela** [kamailio/kamailio#895]
Hello Friends,

we have a setup of kamailio and asterisk server, where kamailio registers users, trunks and asterisk act as media server. Kamailio was working fine with old trunk but there were issues in call disconnection and new trunk registration. Calls are disconnecting in 30 sec while forwarding to mobile and in 1 min while making outbound calls. secondly, Kamailio server is unable to take new trunks info. 

I am not a VOIP expert so please bear with me. I will upload more info if required

**Comment by linuxmaniac** [comment]
This is not an issue in Kamailio software, but a matter of kamailio configuration. The tracker here is for bugs in the code and requests for new features.

For sorting out troubles with configuration, ask your questions to users mailing list at sr-users@lists.sip-router.org -- you have to join it at:

    http://lists.sip-router.org/cgi-bin/mailman/listinfo/sr-users
