### ISSUE TITLE
extra headers in rtjson

### ISSUE THREAD

**Issue by lazedo** [kamailio/kamailio#902]
Hi,
encoding \r\n in json is not desirable.
i propose we change the format of "extra" headers in rtjson from
 "extra": "X-Hdr-A: abc\r\nX-Hdr-B: bcd\r\n"
to
 "extra":  {"X-Hdr-A" : "abc" , "X-Hdr-B" :  "bcd"}

**Comment by miconda** [comment]
Overall I am fine with updating to this format (or even support both, old single value and new array), but there are some bits to clarify or sort out:

  * what is the problem with '\r\n' in a json value? A SIP header body can have '\r\n', if the next line starts with whitespace or tab. Also, there are some jsonrpc commands that expect a SIP body, where there are end of lines
  * how is going to work if one wants to add more than one header with the same name? Is json supporting multiple fields with same name in a struct?

**Comment by lazedo** [comment]
@miconda i think i jumped too fast into this. your comments make absolute sense. sorry for taking your time.
