### ISSUE TITLE
rabbitmq doc

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#903]
http://kamailio.org/docs/modules/devel/modules/rabbitmq.html

Please do provide a URL to the rabbitmq library project in addition to the name of the package name of a Linux distro. 

- Is the package name "librabbitmq-dev"  the same for all major Linux distributions?
- Have you checked this on OpenBSD or FreeBSD?

We are multi-linux-distro and multi-platform :-)

**Comment by miconda** [comment]
Extra from @oej via #904 (which was closed): The doc doesn't state any return values for the two functions. Are there no return values at all?

**Comment by miconda** [comment]
Was this solved or not yet?

**Comment by miconda** [comment]
I added the link to rabbitmq-c lib. For names on other distros, just do pull requests, we do not enforce having such things, but a lead of how to find it out there.
