### ISSUE TITLE
nsq module doc

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#905]
- Please add more details on the dependency libraries.
- There are also a lot of spelling errors
- Document return value of function
- Event routes needs to have their own section (like other modules) and not only be mentioned in the introduction
- There is no real explanation of what the transformation actually does, please add some text
- The pseudo variable needs an explanation too, there is obviously some syntax to it with two arguments

Thank you for updating this in good time for the coming release!

**Comment by eschmidbauer** [comment]
@oej 
I've submitted a PR for this issue
https://github.com/kamailio/kamailio/pull/921
please review. If i missed anything, can you please point out where?
Thanks,
Emmanuel

**Comment by oej** [comment]
Thank you!
