### ISSUE TITLE
CSeq missmatch with UAC module

### ISSUE THREAD

**Issue by vinzens** [kamailio/kamailio#919]
While placing a call though kamailio with uac Module the Cseq is not updated if the call gets rejected for any reason.

Call setup is as follow:

Asterisk -> Kamailio with UAC Module -> Starface PBX

The asterisk calls a number which is not valid on Starface. in this case the Starface rejects the call. The ACK from Kamailio to the starface has wrong CSeq and the 403 gets retransmitted.

The call sequence between Asterisk and Kamailio is not the same than on the Call from Kamailio to Starface since the Proxy Auth was handled by UAC Module. Branch module should take care of the different CSeq but it does not work for rejected calls. Wth a normal Call setup (200 OK, Bye...) everything works fine.

In the attachement there is a wireshark trace with only one call (which is the affected one) and a debug log (level 3)

[debug_trace_log.zip](https://github.com/kamailio/kamailio/files/693234/debug_trace_log.zip)

**Comment by vinzens** [comment]
The used kamailio is the actual one from master branch. We can reproduce the issue. Please let us know if we should do so with new version.

**Comment by miconda** [comment]
What are the parameters you set for the tm module?

**Comment by vinzens** [comment]
I have set no parameter. Everything should be default.

**Comment by miconda** [comment]
Can you try with latest master branch?

**Comment by greggcz** [comment]
Can I use dev debian package http://deb.kamailio.org/kamailiodev-nightly or do I have to compile ?

**Comment by linuxmaniac** [comment]
> Can I use dev debian package http://deb.kamailio.org/kamailiodev-nightly or do I have to compile ?
@greggcz if you wait for the new package to be built this night then yes

**Comment by miconda** [comment]
They are built over the night, so you have to do the testing tomorrow. You can check the date and time of the packages at:

  * http://deb.kamailio.org/kamailiodev-nightly/pool/main/k/kamailio/

**Comment by greggcz** [comment]
What prefix etc do you use to build debian binaries ? I'd like to build it from source and install in same places as the package does

**Comment by greggcz** [comment]
I compiled from source with no luck. The CSeq is still incorrect

**Comment by vinzens** [comment]
Same with me. Still see wrong cseq in ACK on an 403


[debug.log.zip](https://github.com/kamailio/kamailio/files/698102/debug.log.zip)

**Comment by miconda** [comment]
Can you get logs and pcap at the same time? I am interested to see if some specific headers are in the ACK. Also, add log_prefix global parameter to print $ci and $hdr(CSeq) -- it will make it easier to correlate the logs and pcap.

**Comment by greggcz** [comment]
Please see https://github.com/kamailio/kamailio/issues/918 I pasted ngrep log from the transaction

**Comment by miconda** [comment]
@greggcz - I saw the ngrep output there, but there are no logs corresponding to them. You can also do the same: retest and grab both pcap with sip singaling and syslog messages with debug=3 in kamailio.cfg (and log_prefix to print $ci and $hdr(CSeq)) and attach to your issue.

**Comment by miconda** [comment]
A new patch was pushed. Try again with latest master branch.

**Comment by vinzens** [comment]
The fix is working in my case!

thanks a lot for your help

**Comment by miconda** [comment]
Thanks for testing. I am closing this one, the other issue is a slightly different scenario I am working on.
