### ISSUE TITLE
Diameter AVP handling from kamailio.cfg

### ISSUE THREAD

**Issue by miricz** [kamailio/kamailio#922]
Below feature were discussed with Carsten Bock

Currently Diameter AVP values and especially Experimental Result Code is not available from the kamailio.cfg
Therefore I would like to request such kind of feature. I would like to use it mainly on Cx interface for Server-Assignment-Answer (SAA), Location-Info-Answer (LIA), Multimedia-Auth-Answer (MAA), Push-Profile-Answer (PPA)
It should be implemented such a way like in the ims_charging module. 

Thank you very much in advance!

_Cheers,
Zoltan_

**Comment by miconda** [comment]
Closing old feature request. If someone still has interest, the best is to make directly a PR.
