### ISSUE TITLE
Contact IPv6 format error in 200OK/SUBSCRIBE

### ISSUE THREAD

**Issue by riccardovarotto** [kamailio/kamailio#943]
### Description

The 200OK reply to SUBSCRIBE on IPv6 has the Contact header
wrong formatted, it's appear as:

Contact: <sip:2222:0:0:0:0:0:0:55:4060;transport=udp>

instead of 

Contact: <sip:[2222:0:0:0:0:0:0:55]:4060;transport=udp>

#### Debugging Data

```
(paste your debugging data here)
```

#### Log Messages

```
(paste your log messages here)
```

#### SIP Traffic

```
UBSCRIBE sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org SIP/2.0
Via: SIP/2.0/UDP [2221::5]:4060;branch=z9hG4bK-5-0-95675325205398405120;rport
From: <sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org>;tag=5-0-63373794482729304064
To: <sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org>
Call-ID: callid-5-0-cnt-2-23363871231378927616
Contact: <sip:+393498786882@[2221::5]:4060>;expires=80
Max-Forwards: 70
User-Agent: SIPv3 UeSIM LTE - vtrunk_C
Allow: INVITE,ACK,BYE,CANCEL,NOTIFY,MESSAGE,OPTIONS,PRACK,UPDATE,REFER
Expires: 80
Proxy-Authorization: Digest username="+393498786882@ims.mnc021.mcc292.3gppnetwork.org",
  realm="ims.mnc021.mcc292.3gppnetwork.org",
  algorithm=MD5,
  nonce="WIIsT1iCKyMEfQy/SmMqSl2b4P4n2vR7",
  uri="sip:ims.mnc021.mcc292.3gppnetwork.org",
  response="4e39c2ab34e4009dca083e4cbd2acebc",
  cnonce="59159616548176674082335766872064",
  qop=auth,
  nc=00000001
Event: presence.winfo
Allow-Events: reg, presence, presence.winfo
Privacy: none
Accept: application/watcherinfo+xml
CSeq: 76585 SUBSCRIBE
Organization: Sent by UAC Transaction Layer
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP [2221::5]:4060;branch=z9hG4bK-5-0-95675325205398405120;rport=4060;received=2221:0:0:0:0:0:0:5
From: <sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org>;tag=5-0-63373794482729304064
To: <sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org>;tag=be7ce37c4413768ae7f9747982106912-651e
Call-ID: callid-5-0-cnt-2-23363871231378927616
CSeq: 76585 SUBSCRIBE
Expires: 80
Contact: <sip:2222:0:0:0:0:0:0:55:4060;transport=udp>
Server: kamailio (4.4.5 (x86_64/linux))
Content-Length: 0
Warning: 392 [2222:0:0:0:0:0:0:55]:4060 "Noisy feedback tells:  pid=27504 req_src_ip=2221:0:0:0:0:0:0:5 req_src_port=4060 in_uri=sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org out_uri=sip:+393498786882@ims.mnc021.mcc292.3gppnetwork.org via_cnt==1"
```

```
(paste your sip traffic here)
```

### Additional Information
  * **Kamailio Version** - output of `kamailio -v`

version: kamailio 4.4.5 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled with gcc 4.9.2

```
(paste your output here)
```

* **Operating System**:

Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

```
(paste your output here)
```

**Comment by miconda** [comment]
Have you set the server_address parameter for presence module?

**Comment by riccardovarotto** [comment]
Setting this parameters now works,
thanks!

**Comment by miconda** [comment]
I just push a patch to fix it also for the case when the server address is not set. It is only in master branch. If you can test and report if works, then I will backport to 4.4.

**Comment by riccardovarotto** [comment]
I can wait until the next kamailio major release,
Thanks
