### ISSUE TITLE
Change to Makefiles.def to support building on recent versions of Solaris

### ISSUE THREAD

**Issue by hunger1** [kamailio/kamailio#963]
### Description

The version of yacc on Solaris is ancient and fails to process cfg.lex.

#### Reproduction

Run gmake

### Possible Solutions

Based on kamailio-4.4.5, change Makefiles.defs to comment out "YACC=yacc" on line 1838 for the block beginning "ifeq  ($(OS), solaris)" on line 1804.

```
$ diff -c Makefile.defs~ Makefile.defs
*** Makefile.defs~      Wed Jan 18 07:00:21 2017
--- Makefile.defs       Wed Feb  1 07:58:49 2017
***************
*** 1835,1841 ****
                #LDFLAGS=-g $(PROFILE)
                #MOD_LDFLAGS=-g -G
        endif
!       YACC=yacc

  ifeq ($(CC_NAME), suncc)
        LIBS= -ldl -lresolv
--- 1835,1841 ----
                #LDFLAGS=-g $(PROFILE)
                #MOD_LDFLAGS=-g -G
        endif
! #     YACC=yacc

  ifeq ($(CC_NAME), suncc)
        LIBS= -ldl -lresolv
```

* **Operating System**:

Solaris 11.3

**Comment by miconda** [comment]
Could you make a pull request with this change for master branch? In this way the travis-ci makes sure no build is broken and it is easier merge once reviewing the change.

**Comment by miconda** [comment]
Committed to master.
