### ISSUE TITLE
siptrace: sip_trace() a modified packet

### ISSUE THREAD

**Issue by Forty-Tw0** [kamailio/kamailio#965]
http://www.kamailio.org/docs/modules/4.2.x/modules/siptrace.html#siptrace.f.sip_trace
"Store or forward the current processed SIP message in database. **It is stored in the form prior applying changes made to it.**"

Could the functionality of sip_trace be extended to trace a packet again after it has been modified?
My setup is a bit like this: Remote device -> Kamailio -> containerised Asterisk

I am sip_trace'ing all packets, but then modifying them a bit before forwarding them to Asterisk. Yet only the original packet is sent to HOMER. Because of this, I can only see the the Remote device -> Kamailio bits of the sequence diagram showing the SIP transaction.

**Comment by miconda** [comment]
There is a flag that can be set to trace outgoing requests as well.

In latest stable, 4.4, there is an option to trace everything without making use of flags.

If you have more questions about using it, then write to sr-users mailing list. The tracker here is used for bug reports and feature requests.
