### ISSUE TITLE
Packaging: Expand the list of required 3rd party libraries for main Kamailio package

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#969]
(from devmeeting #Fosdem) - adding new dependencies as core dependencies 

- Curl
- libssl
- uuid
- libunistring
- libxml2 

Any other candidates? They have to be libraries that are commonly installed on most Linux/Unix system.

This would mean that a lot of more modules will be built by default, like TLS, HTTP_CLIENT, WEBSOCKET. 

We may also look over the names of the packages/groups for the build system and linux distress

This will require:
- Update of wiki and README/INSTALL
- Update and modification of debian control files and similar files for other distress
- Modification of build system (Makefile groups etc)

Anything else?

**Comment by oej** [comment]
This will require:
- Update of wiki and README/INSTALL
- Update and modification of debian control files and similar files for other distress
- Modification of build system (Makefile groups etc)

Anything else?

**Comment by miconda** [comment]
Following the online devel meeting discussion, this one is closed. PRs can be made based on what is considered to be adjusted in packaging.
