### ISSUE TITLE
kazoo: incomplete documentation

### ISSUE THREAD

**Issue by ovidiusas** [kamailio/kamailio#976]
There are lots of module parameters that are not documented in the README file:
    "amqp_timmer_process_interval"
    "amqp_consumer_ack_timeout_micro"
    "amqp_consumer_ack_timeout_sec"
    "amqp_interprocess_timeout_micro"
    "amqp_interprocess_timeout_sec"
    "amqp_waitframe_timeout_micro"
    "amqp_waitframe_timeout_sec"
    "amqp_consumer_workers"
    "amqp_query_timeout_micro"
    "amqp_query_timeout_sec"
    "pua_include_entity"
    "json_escape_char"
    "app_name"
    "use_federated_exchange"
    "federated_exchange"
    "amqp_heartbeats"
    "amqp_primary_zone"
    "amqp_command_hashtable_size"
    "amqp_result_avp"
    "amqps_ca_cert"
    "amqps_cert"
    "amqps_key"
    "amqps_verify_peer"
    "amqps_verify_hostname"

Also, the follwing functions are not documented:
"kazoo_json_keys"
"kazoo_async_query"

**Comment by henningw** [comment]
@lazedo - any comments on this one? I just did a quick check, there haven't been any updates to the kazoo module README.
