### ISSUE TITLE
app_lua: make mtree / mt_match available

### ISSUE THREAD

**Issue by cahlbin** [kamailio/kamailio#984]
Would be great if it was possible to register mtree functions (mt_match) to be
available to call from app_lua. mtree is currently not listed at
http://www.kamailio.org/docs/modules/4.4.x/modules/app_lua.html#app_lua.p.register
as available for registration.

**Comment by miconda** [comment]
That's the old way of exporting to lua. Starting with 5.0, there is a common interface named kemi that allows exporting same function at once to all kemi-enabled embedded interpreter (at this moment being app_lua, app_jsdt and app_python).

mt_match() is exported to kemi and should be accessible via KSR.mtree.mt_match(str, str, int)

The exports via kemi are not yet properly documented, but you can list them via RPC interface -- if you load app_lua module, see:

  - http://kamailio.org/docs/modules/devel/modules/app_lua.html#app_lua.r.list
