### ISSUE TITLE
Dialog module: dlg_ctx pv

### ISSUE THREAD

**Issue by oej** [kamailio/kamailio#991]
This pv seems to be not fully documented. When is it used and how? To me it seems like this is used as a template when creating new dialogs (but that's a guess). 

- when setting the timeout_route I use a string, like "TIMEOUT_ROUTE" and when reading the value, I get an integer value.

There's also a few parameters not documented:
- "on"
- "timeout"
- "dir"

**Comment by miconda** [comment]
Fixed in master and docs in wiki.
