### ISSUE TITLE
rtpengine_manage doesn't delete session on BYE or CANCEL method.

### ISSUE THREAD

**Issue by YanOtt** [kamailio/kamailio#992]
### Description

rtpengine_manage doesn't delete session on BYE or CANCEL method.

### Troubleshooting

I tried to use rtpengine_manage which has to delete session when Kamailio got BYE or CANCEL packet. 
But rtpengine_manage hasn't deleted RTP session after call was ended.
Session deleted later on timeout by rtpengine.

I execute "rtpengine_delete" in config by myself but is this a normal conduct for this module?

### Additional Information

* **Kamailio Version** - output of `kamailio -v`

version: kamailio 4.4.5 (x86_64/linux) f98162
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: f98162 
compiled on 18:04:29 Feb 13 2017 with gcc 4.7.2

* **Operating System**:

Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

**Comment by rfuchs** [comment]
Can you post the relevant sections of your config and log files please.

Also, what did rtpengine_manage do instead of deleting the session? Just nothing?

**Comment by YanOtt** [comment]
I've added additional logs to comment and found a logic error in the config. After as i fixed this error then rtpengine_manage has started working normally.
